mattermost/mattermost-mobile

.babelrc
package.json
src/actions/device.js
src/client/client.js

Example for using async/await

---

package.json
src/client/client.js
test/client/client.test.js
test/fetch_mock.js
test/sanity.test.js
test/test_helper.js

Obviously the hard-coded json responses need to be extracted out into fixtures or factories, but this gets us started with request mocking.

Use fetch-mock to mock requests in tests

---

src/components/channels_list_view.js
src/components/login_view.js
src/components/posts_list_view.js
src/components/select_server_view.js
src/components/select_team_view.js
src/containers/channels_list_container.js
src/containers/login_container.js
src/containers/posts_list_container.js
src/containers/select_server_container.js
src/containers/select_team_container.js
src/routes.js

This PR makes containers only concerned with mapping state and dispatch to props.
Relies on #25

Mp containers

---

src/reducers/channels.js
src/reducers/device.js
src/reducers/general.js
src/reducers/login.js
src/reducers/posts.js
src/reducers/teams.js
test/general.test.js
test/reducers/channels.test.js
test/reducers/device.test.js
test/reducers/login.test.js
test/reducers/posts.test.js
test/reducers/teams.test.js

These test cover the reducers.  There may be opportunity to abstract some of the tests, especially for the reducers that are using the handle function.

Reducer tests

---

CONTRIBUTING.md

- Emphasizing guidelines already in our docs

Proposed changes to contributor guidelines

---

src/components/login_view.js

Add secureTextEntry prop to password input field

---

src/components/channels_list_view.js
src/components/login_view.js
src/components/logout.js
src/components/select_team_view.js

This helps differentiate the new props from the current props in `componentWillReceiveProps`. It's a good practice that is used consistently in the webapp.

Use nextProps in componentWillReceiveProps

---

app/scenes/root/root.js
app/scenes/root/root_container.js

This fixes the issue when sometimes the app entered a weird state when the root component never rendered the next scene

Fix login flow

---

service/actions/users.js
test/app/actions/login.test.js
test/app/actions/select_server.test.js
test/service/actions/channels.test.js
test/service/actions/general.test.js
test/service/actions/posts.test.js
test/service/actions/preferences.test.js
test/service/actions/teams.test.js
test/service/actions/users.test.js
test/service/actions/websocket.test.js

@hmhealey this should do what we discussed with the unit tests, they are way easy to write and they get executed way faster too.

Improved unit tests

---

app/actions/views/channel.js

Now selects the first channel if the default channel can’t be found

Show town square when selecting a team

---

app/components/post_textbox/post_textbox.js
app/scenes/channel/channel.js

This just removes an unnecessary `flex: 1` and a `Text` component meant for debugging

Fixed post textbox being off screen

---

service/actions/websocket.js
service/selectors/entities/channels.js

Fix show channels that you are a member of and Fixed removal of the member when leaving the channel

Bug fixes for displaying the channels in the drawer

---

app/actions/storage/index.js
app/actions/views/channel.js
app/actions/views/login.js
app/actions/views/select_team.js
app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/channel_drawer_container.js
app/scenes/login/login.js
app/scenes/login/login_container.js
app/scenes/select_team/select_team.js
app/scenes/select_team/select_team_container.js

Now saving last channel id to local storage
Reworked local storage saving

Select last channel viewed

---

app/components/channel_drawer/channel_list.js
app/components/modal_options.js

PureComponent optimization

---

app/scenes/channel/channel.js
app/scenes/channel/channel_container.js
app/scenes/load_team/load_team.js
app/scenes/load_team/load_team_container.js
service/actions/websocket.js
service/client/websocket_client.js

The app will re-establish the WebSocket connection if the network connection is lost or if the app was in the background for a while.
It would be great to add some sort of UI to show the status of the WebSocket and the network, we could show the offline mode or connecting states while there is no WebSocket connection.

WebSocket re-establish connection

---

app/actions/navigation/index.js
app/components/member_list/index.js
app/components/member_list/member_list_row.js
app/navigation/routes.js
app/scenes/channel_info/channel_info.js
app/scenes/channel_info/channel_info_container.js
app/scenes/channel_members/channel_members.js
app/scenes/channel_members/channel_members_container.js
app/scenes/channel_members/index.js
app/scenes/index.js
service/client/client.js
service/selectors/entities/users.js

Adds ability to view members in channel from channel info screen.
Adds reusable member_list component to display members
#60 

Channel members

---

app/actions/views/select_team.js
app/scenes/channel_drawer/channel_drawer.js
app/scenes/channel_drawer/channel_drawer_container.js

Fixes the issue where a blank channel view is rendered when selecting the current team from the team selection scene. 
#202

Team selection causes blank channel view fix

---

service/client/websocket_client.js

An origin as been added to the websocket connection that matches the url of the server to avoid disconnections

Add origin to the websocket connection

---

NOTICE.txt
app/components/channel_list/channel_list.js
app/components/search_bar/index.js
app/components/search_bar/search_bar.android.js
app/components/search_bar/search_bar.ios.js
app/components/text_input_with_localized_placeholder.js
app/scenes/channel/channel_header/channel_header.js
app/scenes/channel_info/channel_info.js
app/scenes/channel_info/channel_info_container.js
app/scenes/channel_info/channel_info_row.js
app/scenes/login/login.js
app/scenes/mfa/mfa.js
app/scenes/right_menu_drawer/right_menu_drawer.js
app/scenes/select_server/select_server.js
ios/Mattermost.xcodeproj/project.pbxproj
package.json

This adds two search bars one native for ios and the one for android is constructed in react-native code.
Also included fixes for the KeyboardAvoidView for select_server, login and mfa screens, as well as using platform specific styles to set the margin from the top on ios.

Platform dependent search bar and ui fixes

---

app/components/channel_list/channel_list.js
app/initial_state.js
app/navigation/router.js
app/navigation/routes.js
app/scenes/channel/channel.js
app/scenes/channel/channel_container.js
app/scenes/channel/channel_drawer_button.js
app/scenes/channel/channel_menu_button.js
app/scenes/channel/channel_title.js
app/scenes/channel_info/channel_info_container.js
app/scenes/channel_members/channel_members_container.js
app/scenes/index.js
app/scenes/login/login_container.js
app/scenes/mfa/mfa_container.js
app/scenes/navigationSceneConnect.js
app/scenes/right_menu_drawer/right_menu_drawer.js
app/scenes/root/root.js
app/scenes/root/root_container.js
app/scenes/select_server/select_server_container.js
app/scenes/select_team/select_team_container.js
package.json
test/mocha.opts
test/setup.js

Reworks the navigation by allowing default and custom navigation props to be passed for each scene to the router for the navigation header and card scene.

Reworking navigation

---

app/components/post/post.js

Fixed post width

---

app/actions/navigation/index.js
app/actions/views/channel_add_members.js
app/components/member_list/index.js
app/components/member_list/member_list_row.js
app/navigation/routes.js
app/scenes/channel_add_members/add_member_button.js
app/scenes/channel_add_members/channel_add_members.js
app/scenes/channel_add_members/channel_add_members_container.js
app/scenes/channel_add_members/index.js
app/scenes/channel_info/channel_info.js
app/scenes/channel_info/channel_info_container.js
app/scenes/index.js
app/scenes/navigationSceneConnect.js
service/selectors/entities/teams.js
service/selectors/entities/users.js

This PR allows for users to be added to the channel from the channel info -> add members screen.

Channel Add Members

---

app/actions/views/channel.js
app/components/post_textbox/post_textbox.js
app/initial_state.js
app/reducers/views/channel.js
app/scenes/channel/channel.js

This PR implements the ability for unsent posts to be cached when switching channels. 
#231

Store post drafts

---

app/initial_state.js
app/navigation/router.js

This PR adds the ability to swipe open/close the right side menu
#230

Right menu swipe

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/at_mention/index.js
app/components/autocomplete/index.js
app/components/post_textbox/post_textbox.js
service/actions/users.js
service/client/client.js
service/constants/users.js
service/reducers/entities/users.js
service/reducers/requests/users.js
service/selectors/entities/channels.js
service/selectors/entities/users.js
test/service/actions/users.test.js

This PR adds user mention autocomplete to the channel view.
#120 

Mention autocomplete

---

app/scenes/channel/channel.js
app/scenes/login/login.js
app/scenes/mfa/mfa.js
app/scenes/select_server/select_server.js
app/scenes/thread/thread.js

This PR fixes the Keyboard on Android so it doesn't move the scene out of the screen
There is a conflict between KeyboardAvoidView in Android as the OS handles that natively so be aware whenever you need to use `KeyboardAvoidView` for IOS to have android render that component differently

Fix Android keyboard

---

app/scenes/right_menu_drawer/right_menu_drawer.js
app/scenes/right_menu_drawer/right_menu_drawer_container.js

Remove items from the right menu drawer.
https://github.com/mattermost/mattermost-mobile/issues/229

Remove items from menu drawer

---

app/components/post_textbox/post_textbox.js
app/scenes/channel/channel.js

Fixed merge conflict causing thread drafts to not work

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/at_mention/index.js
app/components/post/post.js

Fixes bugs in autocomplete
submitted on behalf of @jarredwitt
PLT-5532

Mention autocomplete bug fixes

---

app/navigation/routes.js
assets/base/i18n/en.json

Added title to Thread scene

---

app/components/layout/keyboard_layout.js
app/components/root/index.js
app/components/root/root.js
app/components/root/root_container.js
app/mattermost.js
app/scenes/channel/channel.js
app/scenes/login/login.js
app/scenes/mfa/mfa.js
app/scenes/select_server/select_server.js
app/scenes/thread/thread.js

I also moved the old "RootLayout" component since it's not really a layout as I had intended.

Added KeyboardLayout to automatically use a KeyboardAvoidingView as necessary

---

assets/base/config.json
service/actions/preferences.js
service/actions/websocket.js
service/selectors/entities/preferences.js
service/utils/channel_utils.js
service/utils/preference_utils.js
test/service/actions/preferences.test.js
test/test_helper.js

I also added a separate `TestServerUrl` config setting after accidentally running unit tests against pre-release a few times.
https://mattermost.atlassian.net/browse/PLT-5566

PLT-5566 Added clientside handling to automatically show direct channels

---

app/components/profile_picture/profile_picture.js

This PR adds channel mention autocomplete to the post textbox. 
PLT-5541
Submitted on behalf of @jarredwitt

Fix offline indicator

---

app/components/autocomplete/at_mention/at_mention.js
app/components/post_textbox/post_textbox.js

This PR solves styling issues for the mention autocomplete on Android, uses the correct cursorPosition, and correctly matches special mentions.

Android autocomplete fix

---

app/components/post/post.js

This PR allows for posts created by webhooks to be displayed correctly.
PLT-5559

Webhook post override

---

app/actions/storage/index.js
app/scenes/root/root.js
app/scenes/root/root_container.js

This PR allows for post draft's to be persisted to storage when the state of the app changes to inactive.

Post draft persist

---

app/actions/navigation/index.js
app/actions/views/channel.js
app/actions/views/root.js
app/components/post_textbox/post_textbox.js
app/components/post_textbox/post_textbox_container.js
app/initial_state.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/thread/thread.js
app/scenes/thread/thread_container.js
service/actions/posts.js
service/actions/websocket.js
service/constants/websocket.js
service/reducers/entities/channels.js
service/reducers/entities/index.js
service/reducers/entities/posts.js
service/reducers/entities/typing.js
service/selectors/entities/typing.js

This PR emits the user typing websocket event when the user starts to type in the input box, also shows the user is typing message on top of the input box when receives the websocket event from the server
https://mattermost.atlassian.net/browse/PLT-5510

PLT-5510 Show user is typing

---

Makefile

This PR will make it so every run starts the packager if necessary or updates the pid of the packager so it can be stop later on.
Also includes cleaning the android app before compiling and running
https://mattermost.atlassian.net/browse/PLT-5588

PLT-5588 Makefile cleanup

---

service/actions/websocket.js

To match the webapp Sytem Messages do not mark channels as unread
https://mattermost.atlassian.net/browse/PLT-5629

PLT-5629 don't mark channels as unread with system messages

---

app/navigation/router.js
app/scenes/channel/channel.js
app/scenes/navigationSceneConnect.js

This PR adds the ability to swipe to navigate back to the previous scene.
https://mattermost.atlassian.net/browse/PLT-5572

PLT-5572 Add swiping to close all scenes that open from the side

---

app/actions/navigation/index.js
app/actions/views/user_profile.js
app/components/post/post.js
app/components/post/post_container.js
app/components/profile_picture/profile_picture.js
app/constants/navigation.js
app/navigation/routes.js
app/reducers/navigation/index.js
app/scenes/index.js
app/scenes/navigationSceneConnect.js
app/scenes/user_profile/index.js
app/scenes/user_profile/user_profile.js
app/scenes/user_profile/user_profile_container.js
app/scenes/user_profile/user_profile_row.js
assets/base/i18n/en.json
test/app/reducers/navigation.test.js

This PR adds a user profile screen that can be accessed by clicking on the username or profile picture on a post.
https://mattermost.atlassian.net/browse/PLT-5493
@jarredwitt

PLT-5493 Add a profile scene that shows user information

---

service/reducers/entities/channels.js
service/selectors/entities/channels.js

When the user is logged in and connected to the internet, the app will crash right when another user adds them to a channel (public or private).
https://mattermost.atlassian.net/browse/PLT-5640
via @thomchop

PLT-5640 Check for channel & member in store when marking newly received channel as read

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/at_mention/index.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention/index.js
app/components/autocomplete/index.js
app/components/post_textbox/post_textbox.js

This PR adds mention and channel autocomplete to comment threads.
https://mattermost.atlassian.net/browse/PLT-5600
@jarredwitt

PLT-5600 Autocomplete mentions in the thread scene

---

app/components/custom_list/member_list_row.js
app/scenes/channel_info/channel_info.js
app/scenes/channel_info/channel_info_container.js
app/scenes/channel_members/channel_members.js
app/scenes/channel_members/channel_members_container.js
app/scenes/channel_members/channel_members_title.js
app/scenes/channel_members/remove_member_button.js
service/constants/index.js
service/selectors/entities/channels.js

This PR allows all users to manage/add members in public channels.
https://mattermost.atlassian.net/browse/PLT-5604
@jarredwitt

PLT-5604 Add/Remove members from pubic channels doesn't match the webapp functionality

---

app/scenes/channel_info/channel_info.js
app/scenes/channel_info/channel_info_header.js
app/scenes/channel_info/channel_info_row.js

This PR styles the channel info scene according to the current theme.
https://mattermost.atlassian.net/browse/PLT-5578

PLT-5578 Add theming for channel info

---

app/actions/storage/index.js
app/actions/views/root.js
app/components/root/root.js
app/components/root/root_container.js
app/scenes/login/login.js
app/scenes/login/login_container.js
service/actions/general.js
service/actions/websocket.js
service/client/client.js
service/constants/constants.js
service/constants/general.js
service/reducers/entities/general.js
test/service/actions/general.test.js

If the server get's restarted or the configuration has changed we'll request the config and license from the server to guarantee that we have the latest version.
https://mattermost.atlassian.net/browse/PLT-5589

PLT-5589 Reload configuration when the server config changes

---

service/actions/channels.js
service/actions/websocket.js
service/constants/websocket.js
test/service/actions/websocket.test.js

This PR retrieves the channel when received through the websocket
https://mattermost.atlassian.net/browse/PLT-5660

PLT-5660 Handle channel created WebSocket event

---

app/navigation/router.js

This PR improves navigation by increasing the distance from the edge of the screen that a swipe gesture will be detected.
@jarredwitt

Navigation swiping fix

---

service/actions/users.js

There wasn't any connection left opened but we were trying to get the statuses over and over again
https://mattermost.atlassian.net/browse/PLT-5678

PLT-5678 Ensure all connections are closed on logout

---

app/scenes/select_server/select_server.js
app/utils/url.js
assets/base/i18n/en.json

This PR makes sure that the url for the server starts with http or https and removes any trailing slashes from the url
https://mattermost.atlassian.net/browse/PLT-5676

PLT-5676 Validate server URL format

---

service/actions/websocket.js
service/constants/constants.js
service/utils/post_utils.js

Following the way the webapp behaves some system messages needs to mark the channel as unread, this PR takes care of that
https://mattermost.atlassian.net/browse/PLT-5677

PLT-5677 Make System messages mark channels as unread

---

app/scenes/channel/channel.js
service/actions/websocket.js
service/client/websocket_client.js
test/service/actions/websocket.test.js

Fixes the android websocket error where the wrong origin was being sent.
@jarredwitt

Fix android web socket error

---

app/scenes/thread/thread_title.js
assets/base/i18n/en.json

This will show "Channel Name" Thread or Direct Message Thread in the Thread scene title.
https://mattermost.atlassian.net/browse/PLT-5707

PLT-5707 Fix Threads title in DM channel

---

app/scenes/thread/thread_container.js

https://mattermost.atlassian.net/browse/PLT-5695

PLT-5695 Fixed replying in DM threads

---

assets/base/i18n/en.json
service/client/client.js

If we ever recieve a response not in json format we'll treat that response as invalid and will show a custom error message
https://mattermost.atlassian.net/browse/PLT-5643

PLT-5643 Handle unexpected response from the server

---

app/actions/storage/index.js
app/scenes/root/root.js
app/scenes/root/root_container.js

https://mattermost.atlassian.net/browse/PLT-5606

PLT-5606 Pre-fill the server URL from async storage if you have it.

---

service/client/websocket_client.js

We changed the WS to use options as arguments but we forgot to change a couple of places where we initialized the WS

Fix WebSocket reconnect

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

- Issue template: Add section for device information
- PR template: Add section for device the PR was tested on, and screenshots

Update PR template and Issue template

---

NOTICE.txt

The react library that we use has a [patent grant from Facebook under certain conditions](https://github.com/facebook/react/blob/master/PATENTS), so this is just to add that info to the NOTICE.txt file

Adding Patent Grant info for react library in NOTICE.txt

---

app/components/post/post.js
app/scenes/root/root.js

This fixes an issue where posts would render as blank blocks. It also includes a fix for loading the server URL when the app starts from a fresh install.
https://mattermost.atlassian.net/browse/PLT-5675
iPhone 6 iOS 10, iPhone 7 iOS 10
@jarredwitt

PLT-5675 Fix posts rendering as blank

---

app/actions/navigation/index.js
app/actions/views/channel.js
app/components/action_button.js
app/components/channel_drawer_list/channel_drawer_list.js
app/components/channel_drawer_list/channel_drawer_list_container.js
app/navigation/router.js
app/scenes/channel/channel.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel/channel_title.js
app/scenes/channel_drawer/channel_drawer.js
app/scenes/channel_drawer/channel_drawer_container.js
app/scenes/more_channels/more_channels.js
app/scenes/more_dms/more_dms.js
app/scenes/navigationSceneConnect.js
app/scenes/right_menu_drawer/right_menu_drawer.js
app/scenes/select_team/select_team.js
app/scenes/select_team/select_team_container.js

Makes transitions a little bit smoother and add activity indicators to help with transitions
This may not cover all the cases
https://mattermost.atlassian.net/browse/PLT-5836
This PR was tested on: [iPhone 6s OS 10.1.2, Nexus 6 OS 6.01]

PLT-5836 Smooth transitions and add activity indicators

---

service/utils/channel_utils.js

Reported as private channels missing which I couldn't repro, but they were sorted where capitalization had priority against lower case
https://mattermost.atlassian.net/browse/PLT-5700

PLT-5700 Fixing channel sorting in android and ios

---

NOTICE.txt
android/app/build.gradle
android/app/src/main/java/com/mattermost/MainApplication.java
android/settings.gradle
app/components/root/root.js
ios/Mattermost.xcodeproj/project.pbxproj
package.json
service/client/client.js

Added device info library that can be used to retrieve a information from the device, in this case is the user agent to be used within the driver.
https://mattermost.atlassian.net/browse/PLT-5506
This PR was tested on: [iPhone 6s OS 10.1.2, Samsung J5 OS 6.0.1]

PLT-5506 Record user agent/device type in the active sessions list

---

app/actions/storage/index.js
app/navigation/router.js

The Global error handler was misplaced causing issues on android

Fix android error handler

---

app/components/badge.js
app/scenes/channel/channel_drawer_button.js

It was bothering me the way the badges were re-drawn so i went ahead and fixed that
No ticket

Fix badge flickering

---

Makefile
android/app/build.gradle
android/app/src/main/java/com/mattermost/MainApplication.java
android/app/src/main/res/values/strings.xml
package.json

This PR upgrades RN to 0.42.0
@jarredwitt

Upgrade to RN 0.42.0

---

NOTICE.txt
android/app/build.gradle
android/app/src/main/java/com/mattermost/MainActivity.java
android/app/src/main/java/com/mattermost/MainApplication.java
android/settings.gradle
app/actions/navigation/index.js
app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_icon.js
app/components/file_attachment_list/file_attachment_list.js
app/components/file_attachment_list/file_attachment_preview.js
app/navigation/navigation_modal.js
app/navigation/router.js
app/navigation/routes.js
app/reducers/navigation/index.js
app/scenes/image_preview/image_preview.js
app/scenes/image_preview/index.js
app/scenes/index.js
ios/Mattermost.xcodeproj/project.pbxproj
package.json
test/mocha.opts
test/mocks.js
test/setup.js

This PR adds file previewing for image file types.
https://mattermost.atlassian.net/browse/PLT-5517
@jarredwitt

PLT-5517 Image file previewer

---

app/scenes/channel/channel_drawer_button.js

Changes the font size of the burger jewel to fit two digits
https://mattermost.atlassian.net/browse/PLT-5884

PLT-5884 Fix burger mention numbers

---

app/components/post/post.js

https://mattermost.atlassian.net/browse/PLT-5875

PLT-5875 Updated system message font opacity to match web app

---

app/scenes/right_menu_drawer/right_menu_drawer.js

https://mattermost.atlassian.net/browse/PLT-5603

PLT-5603 Properly applied theme colours to right menu

---

app/actions/views/channel.js
app/navigation/router.js
app/scenes/channel_drawer/channel_drawer.js

When selecting a channel from the drawer the same drawer had a small lag when it was at 95% closed or something like that, with this PR we manually handle the interactions so we know when the drawer is fully closed
https://mattermost.atlassian.net/browse/PLT-5933tes

PLT-5933 Fix drawer transition lag

---

app/components/channel_icon.js
app/scenes/channel_info/channel_info_header.js

https://mattermost.atlassian.net/browse/PLT-6056

PLT-6056 Fix channel info icon color

---

app/actions/views/file_upload.js
app/actions/views/more_dms.js
app/components/post_textbox/post_textbox.js
app/components/post_textbox/post_textbox_container.js
app/components/root/root.js
app/components/root/root_container.js
app/navigation/router.js
app/reducers/views/channel.js
app/reducers/views/thread.js
app/scenes/account_notifications/account_notifications.js
app/scenes/channel/channel_title.js
app/scenes/login/login.js
app/scenes/mfa/mfa.js
app/scenes/more_channels/more_channels.js
app/scenes/more_dms/more_dms.js
app/scenes/select_server/select_server.js
package.json

This PR adds Android back button support.
Also fixes the issue when you cannot open a DM with a user that does not belong to your team and adds a shadow over the drawer
* https://mattermost.atlassian.net/browse/PLT-5598
* https://mattermost.atlassian.net/browse/PLT-5964

PLT-5598 Android back button support

---

app/navigation/router.js

Changing the way the shadow of the drawer looks
https://pre-release.mattermost.com/core/pl/hi1ey6jisfdbukpszk5t4hiojh

Fix drawer shadow

---

README.md

Add link to developer machine setup guide to README

Add link to developer machine setup guide to README

---

app/scenes/channel_drawer/channel_drawer.js
app/scenes/thread/thread.js
app/scenes/thread/thread_container.js

Fix the new message line indicator that wasn't showing up in channel or in the thread.
The indicator for the channel follows what is done in the webapp
https://mattermost.atlassian.net/browse/PLT-5881
https://mattermost.atlassian.net/browse/PLT-5708

PLT-5881 Fix new line indicator for center channel & thread

---

app/actions/navigation/index.js
app/components/file_attachment_list/file_attachment_preview.js
app/components/post_list/post_list.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel/channel_post_list/channel_post_list_container.js
app/scenes/create_channel/create_channel.js
package.json

* Fix post list to gracefully fail image previews  …
* Do not to fetch multiple times the same posts with infinite scroll
* Fix create private channel
* move react-native orientation library to own fork
https://mattermost.atlassian.net/browse/PLT-6032
https://mattermost.atlassian.net/browse/PLT-6038

PLT-6038 & PLT-6032 Bug fixes in post list and create channel

---

app/components/markdown/markdown_list.js
app/components/post/post.js
app/navigation/router.js

* PLT-5902 Close keyboard when drawer opens
* PLT-6001 Fix right margin on markdown lists
* PLT-6036 Fix post commented on spacing
https://mattermost.atlassian.net/browse/PLT-5902
https://mattermost.atlassian.net/browse/PLT-6001
https://mattermost.atlassian.net/browse/PLT-6036

Various UI fixes

---

app/scenes/select_server/select_server.js

Reported by 2 community members

fix android crash on server url

---

app/actions/navigation/index.js
app/components/channel_drawer_list/channel_drawer_list.js
app/components/post/post.js
app/components/post/post_container.js
app/navigation/routes.js
app/scenes/edit_post/edit_post.js
app/scenes/edit_post/index.js
app/scenes/index.js
assets/base/i18n/en.json

Add the ability to edit the message of a post that belongs to the current user
https://mattermost.atlassian.net/browse/PLT-5560
IOS
Android

PLT-5660 Ability to edit a post

---

app/actions/views/channel.js
app/actions/views/load_team.js
app/actions/views/root.js
app/constants/navigation.js
app/constants/view.js
app/navigation/navigation_modal.js
app/navigation/router.js
app/navigation/routes.js
app/reducers/navigation/index.js
app/reducers/views/channel.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel/channel_post_list/channel_post_list_container.js
app/scenes/load_team/load_team.js
app/scenes/load_team/load_team_container.js
app/scenes/select_server/select_server.js

Smooths out login transition.
https://mattermost.atlassian.net/browse/PLT-5926
@jarredwitt

Fix login transition

---

README.md

Added FAQ about account deactivation and data wiping

---

app/actions/views/load_team.js
app/components/file_attachment_list/file_attachment_list.js
app/components/post/post.js
app/reducers/views/channel.js
app/scenes/channel/channel_drawer_button.js
app/scenes/channel/channel_title.js
app/scenes/load_team/load_team.js

This PR fixes the reply vertical line and hides the hamburger menu and channel title when the app is first loading.
https://mattermost.atlassian.net/browse/PLT-6015
@jarredwitt

PLT-6015 RN grey vertical line on left of replies is sometimes too short

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_image.js
app/components/file_upload_preview/file_upload_preview.js
app/scenes/image_preview/image_preview.js
app/scenes/image_preview/zoomable_image.js

This PR adds image pinch and zoom to the image preview.
https://mattermost.atlassian.net/browse/PLT-5991
@jarredwitt

Plt 5991 pinch zoom

---

app/components/channel_drawer_list/channel_drawer_list.js

https://mattermost.atlassian.net/browse/PLT-6144

PLT-6144 remove small gap in channel drawer list

---

app/actions/views/root.js
app/components/markdown/markdown.js
app/components/root/root.js
app/constants/index.js
app/constants/splash_screen.js
app/scenes/channel/channel.js
app/scenes/root/root.js
app/scenes/select_server/select_server.js

* Fix markdown issue with renderHardBreak's
* Fix issue when tapping on a push notification
* Fix splash screen dismissal

Various fixes

---

app/components/post_textbox/post_textbox.js
app/scenes/channel/channel.js

This PR fixes the input blur error.
@jarredwitt

Fix input blur error

---

assets/base/i18n/en.json

https://mattermost.atlassian.net/browse/PLT-5966

Fix grammar in delete message

---

app/components/custom_list/member_list_row.js
app/scenes/channel_add_members/channel_add_members.js
app/scenes/channel_members/channel_members.js

Also fixes a bug when de-selecting all the users in the list didn't disable the option to add/remove
https://mattermost.atlassian.net/browse/PLT-6110

PLT-6110 tap on the user name selects the row for add & manage members

---

app/components/post/post.js

https://mattermost.atlassian.net/browse/PLT-5940

PLT-5940 Remove ability to reply to system and deleted messages

---

android/app/src/main/java/com/mattermost/MainApplication.java
app/actions/navigation/index.js
app/components/channel_drawer_list/channel_drawer_list.js
app/components/channel_drawer_list/channel_drawer_list_container.js
app/components/custom_list/index.js
app/components/post/post.js
app/components/post/post_container.js
app/scenes/channel_info/channel_info.js
app/scenes/channel_info/channel_info_container.js
app/scenes/more_channels/create_button.js
app/scenes/more_channels/index.js
app/scenes/more_channels/more_channels.js
app/scenes/more_dms/index.js
app/scenes/more_dms/more_dms.js
app/scenes/user_profile/user_profile.js
app/scenes/user_profile/user_profile_container.js

This PR includes:
* Following the policies set in the System Console for creating and deleting channels, editing and deleting posts
* Performance improvements when opening the `More Channels` and `More DM's` modals
* Fix SVG issue with Android not being able to build
https://mattermost.atlassian.net/browse/PLT-6208

PLT-6208 Follow policies set in System Console

---

app/actions/views/channel.js

In case the app is fully closed and you get a DM or a GM that weren't already visible in you channel list this will make them show
https://mattermost.atlassian.net/browse/PLT-6202

PLT-6202 Make DM's and GM's visible if necessary

---

app/scenes/settings/index.js
app/scenes/settings/settings.js

Include Server and App version and build number as well as App platform to the report problem email
Also as a tests includes preventing double tap in Settings scene

Include App version and platform for Report a Problem

---

app/components/file_upload_preview/file_upload_preview.js

7:14 PM
This PR adds more styling changes to the image uploader.
https://mattermost.atlassian.net/browse/PLT-6122
@jarredwitt

PLT-6122 RN: Improvements to image upload UI

---

app/components/channel_drawer_list/channel_drawer_item.js
app/components/channel_drawer_list/channel_drawer_list.js
app/components/custom_list/channel_list_row.js
app/components/custom_list/member_list_row.js
app/components/file_attachment_list/file_attachment_list.js
app/components/post/post.js
app/components/post_list/post_list.js
app/scenes/account_notifications/account_notifications.js
app/scenes/account_settings/account_settings.js
app/scenes/channel/channel.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel_add_members/channel_add_members.js
app/scenes/channel_drawer/channel_drawer.js
app/scenes/channel_info/channel_info.js
app/scenes/channel_members/channel_members.js
app/scenes/login/login.js
app/scenes/login_options/login_options.js
app/scenes/mfa/mfa.js
app/scenes/more_channels/create_button.js
app/scenes/more_channels/more_channels.js
app/scenes/options_modal/options_modal.js
app/scenes/options_modal/options_modal_list.android.js
app/scenes/options_modal/options_modal_list.ios.js
app/scenes/select_server/select_server.js
app/scenes/select_team/select_team.js
app/scenes/thread/thread.js
app/utils/tap.js
assets/base/i18n/en.json

This PR makes sure that when a user double taps on the same component or different components on the same screen only one action is performed
this should also fix https://mattermost.atlassian.net/browse/PLT-5966
https://mattermost.atlassian.net/browse/PLT-5840
* Android 7.1.1 Simulator

PLT-5840 Prevent double tapping

---

android/app/src/main/AndroidManifest.xml
app/actions/views/connection.js
app/components/offline_indicator/index.js
app/components/offline_indicator/offline_indicator.js
app/constants/view.js
app/reducers/views/connection.js
app/reducers/views/index.js
app/scenes/channel/channel.js
app/scenes/channel/channel_container.js

Implemented offline indicator that shows whenever the phone loses internet connection or the app is not connected to the server (WS)
https://mattermost.atlassian.net/browse/RN-61
IOS
Android

RN-61 Implement offline indicator

---

app/components/file_attachment_list/file_attachment_image.js
app/scenes/image_preview/image_preview.js
app/scenes/image_preview/zoomable_image.js

This PR adds enhancements to the image previewer.
https://mattermost.atlassian.net/browse/RN-72
@jarredwitt

RN-72 RN: Improvements to image previewer

---

app/actions/views/account_notifications.js
app/actions/views/channel.js
app/actions/views/more_dms.js
app/scenes/account_notifications/account_notifications.js
app/scenes/account_notifications/index.js
app/store/index.js

This PR adds optimistic actions for save preferences, delete preferences, and update notifications.
https://mattermost.atlassian.net/browse/RN-68

RN-68: Make save and delete preferences optimistic

---

app/components/post_list_retry.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel/channel_post_list/index.js
assets/base/i18n/en.json

This PR adds a retry component for reloading channel posts.
https://mattermost.atlassian.net/browse/RN-81
Galaxy s7 - Android 6.0 API 23 
@jarredwitt

RN-81 RN: Error state for post list

---

app/store/index.js

This fixes the redux-offline store for the release-3.7 branch needed before moving to master

Fix redux-offline

---

README.md

Update beta status in README
N/A

Update beta status in README

---

NOTICE.txt
app/scenes/select_server/select_server.js
package.json

RN-50 - Accept Team URL for Server URL
Jira: https://mattermost.atlassian.net/browse/RN-50
GitHub: https://github.com/mattermost/mattermost-mobile/issues/425
This PR was tested on: Android Nexus 5 api 23

implement jira ticker RN-50 - Accept Team URL for Server URL

---

app/actions/views/file_upload.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention/index.js
app/components/file_attachment_list/file_attachment_image.js
app/components/file_upload_preview/file_upload_preview.js
app/components/file_upload_preview/index.js
app/components/post_textbox/post_textbox.js
app/constants/view.js
app/reducers/views/channel.js
app/reducers/views/thread.js
app/scenes/more_channels/index.js
app/scenes/more_channels/more_channels.js
yarn.lock

If uploading a file fails now we can retry the upload before posting, and if we try to post and there is at least one file that failed to upload we get an alert box to decide if we want to create the post without the failed attachments

Retry File Upload

---

app/components/post_textbox/post_textbox.js

Change photo quality to 0.7 instead of 0.5
Jira: https://mattermost.atlassian.net/browse/RN-122
GitHub: https://github.com/mattermost/mattermost-mobile/issues/535

[RN-122] Change photo quality to 0.7 instead of 0.5

---

yarn.lock

Update yarn dependency for redux-offline

update redux-offline dependency

---

app/components/post_textbox/post_textbox.js

There is a bug in React Native were multiline TextInput does not work in android, this PR adds a workaround to that
https://mattermost.atlassian.net/browse/RN-96

RN-96 Make Android and IOS PostTextbox grow and scroll accordingly

---

app/actions/views/login.js
app/mattermost.js
app/screens/login/login.js
app/screens/notification/notification.js
app/screens/saml/saml.js
assets/base/i18n/en.json
yarn.lock

Notify users when their mobile app session expires
https://mattermost.atlassian.net/browse/RN-17

Local push notification when session expires

---

app/components/channel_drawer_list/channel_drawer_list.js
yarn.lock

This PR fixes the unread above/below indicator in the channel list, it also works on Android now cause we replaced the `ListView` with a `FlatList` for this component
https://mattermost.atlassian.net/browse/RN-1

RN-1 Fix unread above/below and use FlatList

---

app/components/post/post.js
app/components/slack_attachments/index.js
app/components/slack_attachments/slack_attachment.js

Renders the slack attachments that a post have
https://mattermost.atlassian.net/browse/RN-30

RN-30 Render slack attachments in posts

---

app/components/post/post.js
yarn.lock

https://mattermost.atlassian.net/browse/RN-34

RN-34 tap to remove ephemeral posts

---

app/components/post_textbox/post_textbox.js

RN-103 - Updating send button on android and IOS
https://mattermost.atlassian.net/browse/RN-103
Xperia Z3, Iphone 6 (Emulator)

RN-103 - Updating send button on android and IOS

---

ios/Mattermost.xcodeproj/project.pbxproj
package.json
yarn.lock

This PR updates xcode to use the latest sentry build steps.
@jarredwitt

Fix sentry build issues

---

android/app/build.gradle
android/app/src/main/java/com/mattermost/MainApplication.java
android/settings.gradle
app/mattermost.js
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/AppDelegate.m
package.json
yarn.lock

This PR removes sentry integration.
@jarredwitt

Remove sentry to fix build

---

app/components/markdown/index.js
app/components/markdown/markdown_block_quote.js
app/components/post/post.js

Update the formatting of markdown block quotes
Jira: https://mattermost.atlassian.net/browse/RN-112
GitHub: https://github.com/mattermost/mattermost-mobile/issues/529
Please let me know if this is ok. :)

[RN-112] Update the formatting of markdown block quotes

---

app/components/post/post.js
app/screens/channel_info/channel_info_header.js
app/utils/markdown.js

Render channel info header and purpose with Markdown.
Also added a utils file to simplify the code when using the same markdown styles in multiple places

Add markdown to channel info

---

app/components/post_textbox/post_textbox.js

Using a `<Text>` component to get the content height and set it to the `PostTextbox` whenever the text changes and so making the textbox have the appropriate size when is empty or have a draft text from the beginning
https://mattermost.atlassian.net/browse/RN-149

RN-149 handle text input content size changed

---

app/components/custom_list/index.js

When searching on a screen we'll be showing an activity indicator at the center of the screen while we get the results back
https://mattermost.atlassian.net/browse/RN-118

RN-118 Update search result loading indicators

---

.gitignore
NOTICE.txt
package.json
test/app/screens/about/about.test.js
test/mocks.js
yarn.lock

This PR adds component unit testing along with coverage.

Add component unit testing with coverage

---

app/components/channel_drawer_list/channel_drawer_list.js
app/components/channel_drawer_list/unread_indicator.js

Tapping on the **Unread posts above** indicator now takes you to the top of the channel list
https://mattermost.atlassian.net/browse/RN-151

RN-151 tap on unread post above

---

app/screens/settings/settings_item.js

RN-128 - Unbolding settings categories
Also fixed the logout color.
https://mattermost.atlassian.net/browse/RN-128
IOS simulator

RN-128 - Unbolding settings categories

---

app/components/channel_drawer_teams/channel_drawer_teams.js

https://mattermost.atlassian.net/browse/RN-178

RN-178 Show unread and mention count on the current team in Team Switcher

---

NOTICE.txt
app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/status_bar/index.js
app/components/status_bar/status_bar.js
app/screens/about/about.js
app/screens/account_notifications/account_notifications.js
app/screens/account_settings/account_settings.js
app/screens/channel/channel.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_info/channel_info.js
app/screens/channel_members/channel_members.js
app/screens/create_channel/create_channel.js
app/screens/edit_post/edit_post.js
app/screens/load_team/load_team.js
app/screens/login/login.js
app/screens/login_options/login_options.js
app/screens/mfa/mfa.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js
app/screens/select_server/select_server.js
app/screens/select_team/select_team.js
app/screens/settings/settings.js
app/screens/sso/sso.js
app/screens/thread/thread.js
app/screens/user_profile/user_profile.js
package.json
yarn.lock

With this PR the status bar on IOS will change the color to use white if the theme header color is dark or to use black if the header color is light.
https://mattermost.atlassian.net/browse/RN-36

RN-36 Update status bar color

---

app/components/channel_drawer/channel_drawer.js

https://mattermost.atlassian.net/browse/RN-157
Android

RN-157 Android drawer overlay fix

---

app/components/post_textbox/post_textbox.js

RN-162 - Increasing attachment button size
https://mattermost.atlassian.net/browse/RN-162
IOS Simulator

RN-162 - Increasing attachment button size

---

app/components/post_textbox/post_textbox.js

https://mattermost.atlassian.net/browse/RN-161
* IOS 10.3.2 iPhone 5s (Simulator)

RN-161 Expand input textbox appropiately for multi-line

---

app/components/at_mention/at_mention.js
app/components/channel_link/channel_link.js
app/components/channel_link/index.js
app/components/markdown/index.js
package.json
yarn.lock

Markdown changes:
https://github.com/hmhealey/commonmark.js/commit/10bc18c0c8054088c0ec4737a8766c6b5794a323
https://github.com/hmhealey/commonmark-react-renderer/compare/1cec47814455f2eb3858864334eb4300b5103523...7be9f10cdb3408a64366a20e60975edff0b5c710
https://mattermost.atlassian.net/browse/RN-74
- Added or updated unit tests (in commonmark repo)
This PR was tested on:  iOS Simulator

RN-74 Added channel links

---

app/utils/url.js

Also adds a default for url to the rest of the url util functions

Fixes an issue where url could be undefined

---

app/actions/views/create_channel.js
app/screens/account_notifications/account_notifications.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/create_channel/create_channel.js
app/screens/more_channels/more_channels.js

RN-193: On Android always show the "Create" option in more channels and create channel
RN-197: Update the channel top bar with the newly created channel display name
https://mattermost.atlassian.net/browse/RN-193
https://mattermost.atlassian.net/browse/RN-197

RN-193 & RN-197

---

app/actions/views/select_team.js
app/components/root/index.js
app/components/root/root.js
app/constants/navigation.js
app/screens/index.js
app/screens/load_team/index.js
app/screens/load_team/load_team.js
app/screens/select_team/index.js
app/screens/select_team/select_team.js
app/screens/settings/settings.js
assets/base/i18n/en.json
yarn.lock

This handle the following cases:
* User logs in and does not belong to any teams
* User leaves all his teams while the app running
* User leaves all his teams while the app is closed or disconnected
IOS
Android

Handle the cases when a user has no teams

---

app/components/markdown/markdown_link.js

https://mattermost.atlassian.net/browse/RN-143

RN-143 Fixed links being case sensitive on Android

---

app/utils/markdown.js

https://mattermost.atlassian.net/browse/RN-176
This PR was tested on: Nexus 5, iOS Simulator

RN-176 Fixed horizontal rules not rendering

---

app/components/channel_drawer/channels_list/index.js
app/components/search_bar/search_bar.ios.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js

Updating search bar styling
IOS simulator, Xperia Z3

Updating search bar styling

---

app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js

Updating search styling for some pages
IOS Simulator

Updating search styling for some pages

---

app/components/channel_drawer/channels_list/filtered_list/filtered_list.js

Fixes an issue where search would crash if a user's name was undefined.

Fix issue where name could be undefined

---

app/components/channel_drawer/channels_list/index.js
app/screens/edit_post/edit_post.js

https://mattermost.atlassian.net/browse/RN-205

RN-205 Fixed EditPost error message not being visible

---

app/screens/settings/settings.js

https://mattermost.atlassian.net/browse/RN-202

RN-202 Fix blank help link to not crash

---

app/components/post_textbox/post_textbox.js

I think the problems seem before were caused by the width of the reference text not being correct. I also added a space to the end of the reference text because I think the Text component on Android ignores trailing newlines for sizing
https://mattermost.atlassian.net/browse/RN-161

RN-161 Fix autosizing post textbox

---

app/components/channel_drawer/channels_list/index.js

https://mattermost.atlassian.net/browse/RN-191

RN-191 Channel drawer IOS UI fixes

---

app/components/markdown/index.js
app/components/markdown/markdown_link.js
app/components/post/post.js

This PR allows URL only posts to be long pressed.
https://mattermost.atlassian.net/browse/RN-201

Can now long press on markdown links

---

app/actions/views/login.js
app/screens/login/login.js
app/screens/sso/index.js
app/screens/sso/sso.js

Set the loginId to lowercase when using email, username or LDAP to signIn.
Also fixes an issue when getting the session to set the push notification when the session expires
https://mattermost.atlassian.net/browse/RN-46

RN-46 convert loginId to lowercase

---

app/components/markdown/index.js
app/utils/markdown.js
package.json
yarn.lock

Changes to commonmark-react-renderer are here: https://github.com/hmhealey/commonmark-react-renderer/commit/11bf3a089900eda6f3e951f8b8c80663cff4d6a3
https://mattermost.atlassian.net/browse/RN-109

RN-109 Added ability to add styles to adjacent paragraphs

---

app/actions/views/channel.js
app/components/post_list/index.js
app/components/post_list/post_list.js
yarn.lock

See the commits for the changes made. This PR can't be merged until https://github.com/mattermost/mattermost-redux/pull/168 is and then the package.json/yarn.lock are updated
https://mattermost.atlassian.net/browse/RN-219
- All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)

RN-219 Attempting to fix missing posts

---

app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
app/screens/channel/channel.js

https://mattermost.atlassian.net/browse/RN-216

RN-216 Hid file upload button when files are disabled

---

app/components/post_textbox/post_textbox.js
app/screens/more_channels/index.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/index.js
app/screens/more_dms/more_dms.js

This PR Updates the channel name in the channel top bar whenever we join a channel with More Channels and when Opening a DM using the `More Direct Messages` screens.
Note: This PR also fixes the attach image icon that wasn't being shown with a 3.8 server 
https://mattermost.atlassian.net/browse/RN-234

RN-234 Update channel header whit mode dms and more channels

---

app/screens/edit_post/edit_post.js

https://mattermost.atlassian.net/browse/RN-232

RN-232 Fix cannot leave edit post screen when edit fails

---

app/components/post_textbox/post_textbox.js

https://mattermost.atlassian.net/browse/RN-238

RN-238 Fix ability to post with just images

---

app/components/channel_intro/channel_intro.js
app/components/channel_intro/index.js
app/components/post_list/post_list.js
app/screens/channel/channel_post_list/channel_post_list.js

Fixes an issue where the channel intro would not display for some channels.

Fixes an issue with channel intro not displaying

---

app/screens/select_team/index.js
app/screens/select_team/select_team.js

https://mattermost.atlassian.net/browse/RN-204

RN-204 Added error alert when failing to join a team

---

Makefile
app/components/post_textbox/post_textbox.js

I wasn't able to reproduce the issue reported in the ticket on my device, but it didn't hurt to have the workaround in, so I re-added it
https://mattermost.atlassian.net/browse/RN-237
This PR was tested on: Nexus 5 (Android 6.0.1)

RN-237 Re-added workaround for pressing enter on Android

---

app/components/post/post.js

Fixes timestamp alignment for post title.
https://mattermost.atlassian.net/browse/RN-71

RN-71 Timestamps are not aligned with username

---

app/components/channel_drawer/channels_list/index.js
app/components/channel_drawer/swiper/swiper.ios.js

on IOS if the user has only one team remove the bottom padding in the channel drawer cause it won't show the `paging` indicator
https://mattermost.atlassian.net/browse/RN-230

RN-230 remove drawer bottom padding if only one team

---

app/components/channel_drawer/swiper/swiper.ios.js
package.json
yarn.lock

Fixes the drawer for rendering incorrectly when opening the app in landscape mode on IOS
https://mattermost.atlassian.net/browse/RN-208

RN-208 Fix drawer when app opens in landscape

---

CHANGELOG.md

Draft of changelog for v1.0 release

Changelog v1.0

---

app/screens/more_channels/index.js
app/screens/more_channels/more_channels.js

https://mattermost.atlassian.net/browse/RN-240

RN-240 Fix create public channel policy

---

CHANGELOG.md

updated to include version number of push proxy

Make required push proxy version more clear

---

app/actions/views/root.js

I was investigating the crashes reported on Android, and I came across these things that might be issues. I don't think they're the cause of the reported crash, but they could help

Fixed some potential bugs in goToNotification action

---

app/components/channel_intro/channel_intro.js
app/components/post/post.js

RN-218 - Updating default font size for posts
https://mattermost.atlassian.net/browse/RN-218
IOS Simulator, Iphone 6.
Moto x first gen.

RN-218 - Updating default font size for posts

---

app/mattermost.js
yarn.lock

https://mattermost.atlassian.net/browse/RN-242

RN-242 Fix race condition and ensure server url is set when tapping a PN

---

app/screens/channel/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/login_options/login_options.js

Fix that prevents from making request to the server when logging out that was causing an error being logged and that was setting the serverVersion preventing the app from requesting the config and license in future login attempts

Fix logout/login issue

---

app/screens/channel_members/channel_members.js

Fixed Remove button being displayed in View Members modal

---

app/screens/channel_info/channel_info.js

Hid View Members option when viewing direct/group channels

---

app/screens/channel_info/channel_info_header.js

Fixed uneven margin on channel name

---

app/screens/channel_info/channel_info.js
app/screens/channel_info/index.js

Fixes an issue when trying to leave a private channel

Fix leave private channel

---

app/components/at_mention/at_mention.js
app/components/at_mention/index.js
app/components/markdown/index.js
app/components/post/post.js

This PR adds the ability to navigate to a users profile by pressing on a user mention.
https://mattermost.atlassian.net/browse/RN-38
@jarredwitt

RN-38 Clicking on an at mention should open user profile

---

app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
app/components/channel_drawer/channels_list/filtered_list/index.js

Fixes the jump to conversation error reported in https://github.com/mattermost/mattermost-mobile/issues/735

Fix undefined object issue in Jump to Conversation

---

app/components/badge.js

https://mattermost.atlassian.net/browse/RN-261

RN-261 Fix app crashing when badge is unmounted before it displays

---

app/components/post_textbox/post_textbox.js

This PR disables the send button while an attachment is uploading.

Disable the send button while attachments are uploading

---

app/screens/select_server/select_server.js
app/screens/sso/sso.js
app/utils/url.js
package.json
yarn.lock

This PR fixes the issue where a user couldn't login successfully using an SSO if they're server url had a trailing slash or space.
Additionally it also implements a better error screen when the user could not login cause of an error.

Fix SSO login

---

app/components/channel_drawer/channels_list/index.js
app/components/channel_icon.js

I also fixed the colour of the offline status icon on the channel info page
https://mattermost.atlassian.net/browse/RN-245
This PR was tested on: iOS simulator

RN-245 Made all channel icons have equal margins

---

app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
app/components/channel_drawer/channels_list/filtered_list/index.js
app/components/reactions/index.js

Adds nickname, username, email, and full name matching.
https://mattermost.atlassian.net/browse/RN-270

RN-270 "Jump to conversation" filtering

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissReceiver.java

https://mattermost.atlassian.net/browse/RN-267
* Android 7.1.1 Nexus 5 (Simulator)

RN-267 Android Notifications Support for Big View

---

app/components/channel_drawer/channels_list/index.js
app/components/search_bar/search_bar.android.js
app/components/search_bar/search_box.js
app/screens/search/search.js

https://mattermost.atlassian.net/browse/RN-292

RN-292 Adjust search box carret and selection color

---

app/components/search_preview/search_preview.js

https://mattermost.atlassian.net/browse/RN-291

RN-291 Fix Title in "Jump" pop up is not visible on default theme

---

app/screens/search/search.js

https://mattermost.atlassian.net/browse/RN-297

RN-297 Last item in search results displays with no buffer below

---

app/screens/search/search.js

Make the section headers sticky only for IOS

Fix sticky

---

app/components/search_bar/search_box.js
app/screens/search/index.js
app/screens/search/search.js
assets/base/i18n/en.json
yarn.lock

Show **No Results Found** when search does not have any results
https://mattermost.atlassian.net/browse/RN-293
* IOS 10.3.2 iPhone 6 (simulator)
* Android 7.1 Nexus 5 (Simulator)

RN-293 Show no resuls found in search for posts

---

app/screens/about/about.js
assets/base/i18n/en.json

https://mattermost.atlassian.net/browse/RN-246

Fix localized string

---

app/components/autocomplete/at_mention/index.js
app/components/autocomplete/channel_mention/index.js
app/components/autocomplete/emoji_suggestion/index.js

Fix for the bug reported in https://pre-release.mattermost.com/core/pl/ohdqp6156bdhbdt4xe7mm48zgo
@jarredwitt in the end it was needed

Fixes autocomplete to not to crash if rootId is undefined

---

README.md

Related GitHub Issue: https://github.com/mattermost/mattermost-mobile/issues/806

Update readme to use assets/override instead of config.secret.json

---

package.json
yarn.lock

Commonmark.js changes are here: https://github.com/hmhealey/commonmark.js/commit/d6a8d7db1b9798b267a99a75a8feb86f7f6c8f79
I also merged in upstream changes from jgm/commonmark.js as well
https://mattermost.atlassian.net/browse/PLT-7250

PLT-7250 Updated commonmark.js to better handle trailing periods on URLs

---

app/components/channel_drawer/channels_list/list/list.js
app/screens/create_channel/create_channel.js
app/screens/more_channels/index.js
app/screens/more_channels/more_channels.js

More channel screen was being updated because when filtering the channels it was returning a different array thus componentWillReceiveProps was updating the Navigation buttons.
https://mattermost.atlassian.net/browse/RN-302

Fix Create on Create channel to not push another Create Channel screen

---

NOTICE.txt
app/actions/views/root.js
app/mattermost.js
assets/base/config.json
fastlane/Fastfile
package.json
yarn.lock

https://mattermost.atlassian.net/browse/RN-288

RN-288 Add analytics with segment.io

---

app/components/channel_drawer/channels_list/channel_item.js

https://mattermost.atlassian.net/browse/RN-279

Fix mention badge wrap text

---

app/screens/login_options/login_options.js

https://mattermost.atlassian.net/browse/RN-313

RN-313 Add LDAP login to the login options

---

app/screens/search/search.js

https://mattermost.atlassian.net/browse/RN-306

RN-306 Don't scroll to results when recent search is removed

---

app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js

https://mattermost.atlassian.net/browse/RN-282

RN-282 Switched usage of splice to slice

---

app/selectors/preferences.js

https://mattermost.atlassian.net/browse/RN-283

RN-283 Properly render uppercase theme colours

---

android/app/src/main/res/values/strings.xml
android/app/src/main/res/xml/app_restrictions.xml

When building android for release android linter was complaining that we didn't had this values

Include title and description for Android AppConfig

---

README.md
app/components/emoji/emoji.js
app/components/file_attachment_list/file_attachment_image.js
app/components/profile_picture/profile_picture.js
app/screens/image_preview/previewer.js
assets/base/config.json
yarn.lock

We had some residual API calls using v3 and I've ported them to use v4 and to be sure I updated the minimum server version to be 4.0
https://mattermost.atlassian.net/browse/RN-317

Fetch images using APIv4

---

app/components/markdown/markdown_code_block/markdown_code_block.js
app/screens/code/code.js

RN-73 Fixed code block text colour being incorrect

---

README.md

Client had a query for building react client for their own infrastructure.  They were failing on make build-android.
Added additional documentation as requested to readme.
[Conversation on Private Channel](https://pre-release.mattermost.com/core/pl/xenmijp9sp8f7g3oet1zdafr9w)

Added Link to Device build for React native.

---

fastlane/metadata/android/en-US/full_description.txt

Update minimum server version

---

app/actions/views/channel.js
app/actions/views/root.js
app/components/root/root.js
package.json
yarn.lock

Cleaning up code to open the push notifications faster than before
https://mattermost.atlassian.net/browse/RN-344
* IOS 10.3.3 iPhone 6s
* Android 7.1.1 Emulator (Nexus 5)

RN-344 open push notifications faster

---

app/components/offline_indicator/index.js
app/components/offline_indicator/offline_indicator.js

https://mattermost.atlassian.net/browse/RN-347

Show connecting indicator after two failed attempts

---

app/screens/channel/channel_post_list/index.js

https://mattermost.atlassian.net/browse/RN-350

Show pull to retry if the offline indicator is not showing

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Improvement for stacking Android push notification
* Android 7.1.1 Emulator (Nexus5)

Android stack push notifications improvement

---

app/components/file_upload_preview/index.js
app/selectors/views.js

This was causing errors when the store was empty

Fixed post draft selectors returning null

---

app/components/autocomplete/index.js

https://mattermost.atlassian.net/browse/RN-363

Fix android search autocomplete

---

app/components/channel_drawer/channels_list/switch_teams/switch_teams.js

RN-364 Fixed switch teams button rendering with only one team

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/index.js
app/components/search_bar/search_bar.ios.js
app/screens/search/search.js

By upgrading to RN 0.48.3 we need to handle a few thing differently, this PR takes care of those in terms of the search functionality
https://mattermost.atlassian.net/browse/RN-375
https://mattermost.atlassian.net/browse/RN-376
https://mattermost.atlassian.net/browse/RN-377

Fix search issues

---

app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/drawer_swipper/drawer_swiper.js
app/components/swiper.js

Fixes the channel drawer in portrait and landscape mode for multiple and single teams
https://mattermost.atlassian.net/browse/RN-374

Fix drawer according to number of teams

---

app/components/options_context/options_context.android.js
app/components/options_context/options_context.ios.js
app/components/post/post.js
app/components/post_body/index.js
app/components/post_body/post_body.js

https://mattermost.atlassian.net/browse/RN-339

Remove context menu for system and ephemeral messages

---

app/screens/channel/channel_post_list/index.js

https://mattermost.atlassian.net/browse/RN-383

RN-383 Fixed new messages indicator

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferences.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java
fastlane/Fastfile

Fixes a crash when receiving a push notification in Android and the app is closed.

Fix Android crash on push notification

---

Makefile

Respect Android orientation lock

---

app/screens/settings/notification_settings_mobile/index.js
assets/base/i18n/en.json

https://mattermost.atlassian.net/browse/RN-404

RN-404 add missing localization strings

---

app/screens/settings/general/settings.js

Whitelabel ‘report a problem’ email
Whitelabel it by adding a config for recipient and use SiteName on subject.
@jarredwitt will coordinate modifications

Whitelabel ‘report a problem’ email

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

https://mattermost.atlassian.net/browse/RN-406
https://mattermost.atlassian.net/browse/RN-407

Fix ArrayIndexOutOfBounds and NullPointer exceptions for android PN

---

app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js

https://mattermost.atlassian.net/browse/RN-409

Fix undefined when selected sound not found

---

app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js

https://mattermost.atlassian.net/browse/RN-410

Fix undefined when default or selected sound not found

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

https://mattermost.atlassian.net/browse/RN-408

Fix Android: Permission Denial when handling push notification

---

app/screens/select_team/index.js

https://mattermost.atlassian.net/browse/RN-422

Fix currentUser is null on SelectTeam screen

---

app/components/channel_drawer/channels_list/channels_list.js
app/components/channel_drawer/channels_list/switch_teams_button/switch_teams_button.js
app/components/search_bar/search_bar.android.js
app/components/search_bar/search_bar.ios.js
app/components/search_bar/search_box.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js
app/screens/search/search.js
assets/base/i18n/en.json

https://mattermost.atlassian.net/browse/RN-307

Polishing search box text size and icon styling

---

README.md

Hi,
This PR is just fixing a missing newline in compilation instructions.
Cheers,
-- Mathieu

Fix missing newline in compilation instructions

---

app/actions/views/channel.js
app/actions/views/create_channel.js
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/search_preview/index.js
app/components/search_preview/search_preview.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js
app/screens/search/channel_display_name/channel_display_name.js
app/screens/search/channel_display_name/index.js
app/screens/search/index.js
app/screens/search/search.js
app/screens/thread/index.js
app/screens/thread/thread.js
yarn.lock

https://mattermost.atlassian.net/browse/RN-431
https://mattermost.atlassian.net/browse/RN-438

Fixed Search bugs and avoid re-renders

---

app/screens/channel/channel.js
app/store/index.js
app/utils/network.js
test/setup.js

This PR helps improve network detection by trying to connect to the client server to test the connection before reporting an online/offline state.

Add better network detection

---

app/actions/views/channel.js
app/constants/view.js
app/mattermost.js
app/reducers/app/build.js
app/reducers/app/index.js
app/reducers/app/version.js
app/reducers/index.js
app/reducers/views/channel.js
app/reducers/views/team.js
app/screens/channel/index.js
app/store/index.js
app/store/middleware.js
app/utils/network.js
assets/base/config.json

When opening the app for the first time or when sending the app to the background we will check if data from the state can be cleared in order to free memory and improve performance.
When a new version of the app is detected we're clearing the store almost in its entirety.

Data cleanup

---

yarn.lock

https://mattermost.atlassian.net/browse/RN-456

RN-456 when a channel is left we update content and title

---

app/mattermost.js

https://mattermost.atlassian.net/browse/RN-464

Fix logout and reset cache to restart the app

---

app/components/post/post.js
app/screens/thread/thread.js

https://mattermost.atlassian.net/browse/RN-463

Close Thread view when the root post has been deleted

---

app/store/middleware.js

https://mattermost.atlassian.net/browse/RN-474

RN-474 Fixed resetStateForNewVersion not working if upgrading without search state

---

yarn.lock

Redux PR: https://github.com/mattermost/mattermost-redux/pull/311
https://mattermost.atlassian.net/browse/RN-492

RN-492 Added fallback to default theme colours when missing from custom theme

---

app/components/swiper.js
app/screens/image_preview/image_preview.js

https://mattermost.atlassian.net/browse/RN-471
https://mattermost.atlassian.net/browse/RN-484

RN-471/RN-484 Fixed null pointer exceptions caused by ScrollViews

---

app/actions/views/root.js
app/initial_state.js
app/store/middleware.js
assets/base/config.json
yarn.lock

Apply the server data retention policy when the app first loads and when sending to the background
https://mattermost.atlassian.net/browse/RN-361

RN-361 Apply data retention policy

---

yarn.lock

Actual fix is here https://github.com/enahum/react-native-notifications/commit/2300824b1cbd5fff33d20847b3cc75f304613927
This PR is going to be cherry-picked for 1.4.1
https://mattermost.atlassian.net/browse/RN-473

Fix iOS RN notification lib

---

app/components/post/post.js
app/components/post_body/post_body.js
app/components/post_body_additional_content/post_body_additional_content.js
app/components/slack_attachments/index.js
app/components/slack_attachments/interactive_action/index.js
app/components/slack_attachments/interactive_action/interactive_action.js
app/components/slack_attachments/slack_attachment.js

https://mattermost.atlassian.net/browse/RN-360
IOS
Android

RN-360 Add support for interactive message buttons

---

Makefile

Fix style for inverted FlatList in Huawei devices

Fix huawei inverted list

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/at_mention/index.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention/index.js
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/autocomplete/emoji_suggestion/index.js
app/components/autocomplete/index.js
app/components/post_textbox/components/paper_clip_icon.js
app/components/post_textbox/post_textbox.js
app/screens/search/search.js

* Removed the constant draft update when a new char is typed
* TextInput value is handled in local state
* Autocomplete uses the local state value
* Update draft whenever you end editing in the TextInput
* Made the container for tapping on paper plane icon all the way to the end of the textInput container

Improve performance on post textbox

---

app/actions/views/channel.js

Use new `isFavoriteChannel` redux util

Use new isFavoriteChannel redux util

---

app/components/flag_icon.js
app/components/post/index.js
app/components/post/post.js
app/components/post_body/index.js
app/components/post_header/post_header.js

Adds SVG flag to post headers.
[RN-44](https://mattermost.atlassian.net/browse/RN-44)
* iPhone X, iOS 11 (emulated)
* iPhone 6, iOS 11 (emulated)
* iPhone 6s, iOS 11
* Nexus 6P, Android 8.0 (emulated)
* Nexus 5, Android 6

RN-44: Adds flag SVG to post header.

---

Makefile

After this gets in make sure you run a `make clean` before trying

Fix blurry look when render inverted FlatList in iOS

---

app/components/channel_drawer/channels_list/channels_list.js
app/components/search_bar/search_bar.android.js
app/components/search_bar/search_bar.ios.js
app/components/search_bar/search_box.js
app/screens/search/search.js

Hopefully this fixes the weird keyboard behaviour that Lindsay and Linda reported. I also made some improvements to how styles and functions are passed as props in the search code to reduce rerenders.
https://mattermost.atlassian.net/browse/RN-376

RN-376 Removed code that made search bar focus itself after animations

---

app/screens/search/search_result_post/search_result_post.js
app/store/middleware.js

Keep current search results when the app is sent to the background if there are any
https://mattermost.atlassian.net/browse/RN-494

Keep search results on data cleanup

---

package.json
yarn.lock

Reverts mattermost/mattermost-mobile#1153

Revert "RN-497 Updated commonmark to better handle non-latin characters in URLs"

---

app/screens/user_profile/user_profile.js

https://mattermost.atlassian.net/browse/RN-515

Fix switch to DM from thread view

---

app/components/offline_indicator/index.js
app/components/offline_indicator/offline_indicator.js

Added back the possibility to retry connecting to the server from the grey bar.
https://mattermost.atlassian.net/browse/RN-416

RN-416 Add the ability to retry the connection

---

app/actions/views/select_team.js
app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/index.js
app/mattermost.js
app/screens/channel/channel.js
app/screens/channel/index.js
app/screens/search/index.js
app/screens/search/search.js
yarn.lock

https://mattermost.atlassian.net/browse/RN-511

Sync read channels across devices/apps

---

app/components/markdown/index.js
app/components/post_body/index.js
app/components/post_body/post_body.js
package.json
yarn.lock

Adds edited indicator to posts inline with messages. 
[RN-359](https://mattermost.atlassian.net/browse/RN-359)
* iPhone 6 (iOS 11.1) emulator
* Pixel (Android 8.0.0) emulator
Note that there is a [PR pending](https://github.com/hmhealey/commonmark-react-renderer/pull/2) dependency. I will update the `package.json` when that PR has been merged.

RN-359: Adds edited indicator to post.

---

Makefile
app/actions/views/emoji.js
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/emoji_picker/emoji_picker.js
app/components/emoji_picker/emoji_picker_row.js
app/components/emoji_picker/index.js
app/components/post/index.js
app/constants/view.js
app/reducers/views/index.js
app/reducers/views/recent_emojis.js
app/store/middleware.js
assets/base/i18n/en.json
jsconfig.json
package.json
yarn.lock

This PR adds the following:
- Recently used emojis section
- Section icon buttons for scrolling to specific section
- Improved rendering
- Emoji search flatlist view

Add recently used section

---

yarn.lock

Actual fix is here https://github.com/enahum/react-native-notifications/commit/8a8e59b4fe00a574462deb94071ac73d59e8648f
https://mattermost.atlassian.net/browse/RN-522

Upgrade react-native-notifications lib

---

app/mattermost.js
yarn.lock

https://mattermost.atlassian.net/browse/RN-526

RN-526 fix broken analytics

---

app/components/custom_section_list.js
app/screens/more_dms/more_dms.js

This reverts the component that was removed by HH

Fix more dms screen

---

app/screens/thread/thread.js
app/screens/user_profile/user_profile.js

https://mattermost.atlassian.net/browse/RN-463
https://mattermost.atlassian.net/browse/RN-515

Fixes Android dismissModal from user_profile and thread screens

---

app/actions/views/command.js
app/components/autocomplete/autocomplete.js
app/components/autocomplete/slash_suggestion/index.js
app/components/autocomplete/slash_suggestion/slash_suggestion.js
app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
assets/base/i18n/en.json
package.json
yarn.lock

Adds slash command support.
https://mattermost.atlassian.net/browse/RN-272
iPhone 8 iOS 11

Add slash command support

---

app/actions/views/root.js
app/components/root/root.js
app/mattermost.js
app/screens/notification/notification.js

https://mattermost.atlassian.net/browse/RN-539

Fix reset to channel view when push notification is tapped

---

app/components/swiper.js

Repositions swiper nav dots.
[RN-518](https://mattermost.atlassian.net/browse/RN-518)
* Pixel Android 8.0 emulator
* iPhone 6 iOS 11.1 emulator

RN-518: Changes placement of swiper nav dots.

---

app/components/post_list/post_list.js

Reset the newMessagesIndex in post list to avoid crashes

reset newMessagesIndex

---

app/components/post_textbox/post_textbox.js

https://mattermost.atlassian.net/browse/RN-538

Fix the ability to send the post when an upload failed

---

app/screens/login/login.js
app/screens/mfa/mfa.js
app/screens/select_server/select_server.js

https://mattermost.atlassian.net/browse/RN-537

Prevent tap spam for server url, login and MFA

---

app/screens/select_server/select_server.js

https://mattermost.atlassian.net/browse/RN-541

Fix status bar for Android in server url screen

---

app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
assets/base/i18n/en.json

https://mattermost.atlassian.net/browse/RN-535

Fix channels category in jump to filter

---

app/screens/search/search.js

Search wasn't showing, changes order of components in JSX.
n/A
n/a
n/a

Fix for search.

---

app/components/channel_drawer/channels_list/channels_list.js
app/screens/search/search.js

https://mattermost.atlassian.net/browse/RN-534

Fix Android: Text typed in Jump to... and Search box color

---

app/actions/views/root.js
app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/teams_list/teams_list.js
app/mattermost.js
app/screens/channel/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js
app/screens/channel/index.js
app/screens/login/login.js
app/screens/root/root.js
app/screens/sso/sso.js
app/utils/segment.js
app/utils/time_tracker.js

Start tracking the following times in **ms** and send them to segment
* Start time (the amount of time it takes to first load the channel once logged in)
* Channel switch (the amount of time it takes to switch channels)
* Team switch (the amount of time it takes to switch team)
https://mattermost.atlassian.net/browse/RN-533

Track analytics for start time, channel and team switching

---

package.json
yarn.lock

For some reason I think having `master` in the package name is causing some issue with the latest commit to the Redux repo. Is it just me?
n/a

Package fix.

---

app/actions/views/file_upload.js

Allows for HEIC images to be uploaded

Add fix for heic image uploads

---

app/components/search_preview/index.js
app/screens/search/search.js

Another attempt at fixing this error. I don't know why it's failing to return a post from getPost, but it turns out that we don't even need it.
https://mattermost.atlassian.net/browse/RN-472

RN-472 Fixed undefined post error in SearchPreview screen

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/autocomplete.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/index.js

Increases the height of the search results for AtMentions and ChannelMentions to use the full available screen height.
[RN-519](https://mattermost.atlassian.net/browse/RN-519)
* iPhone X emulator
* iPhone 6 emulator
* Pixel 2 emulator

RN-519: Expands search results list height.

---

app/components/radio_button/index.js
app/components/radio_button/radio_button_group.js
app/screens/settings/notification_settings/notification_settings.js
app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js
app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js

Fixes https://github.com/mattermost/mattermost-mobile/issues/1109

Fix Android crash for mobile notifications screen

---

app/utils/segment.js

We need this to ensure the messages are being flush to segment

Tweak flushAt and flushInterval for segment

---

app/screens/image_preview/image_preview.js

https://mattermost.atlassian.net/browse/RN-552

Fix Image preview header/footer

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Change the vibration pattern for Android to use the system default.
will close #1216
This PR was tested on: Nexus 5X - Android 8.0.0

Use system default for vibration pattern

---

app/components/swiper.js
app/screens/image_preview/image_preview.js
app/screens/image_preview/image_view.ios.js

The offset wasn't being re-calculated when the device rotates, this takes cares of that

Fix swiper offset when device rotates

---

app/components/post_list/load_more_posts/load_more_posts.js
app/components/post_list/post_list.js

Loading more messages fix for Android, iOS should still work as expected
https://mattermost.atlassian.net/browse/RN-542

Android: Fix load more messages

---

app/screens/edit_channel/edit_channel.js

https://mattermost.atlassian.net/browse/RN-559

Fix channel editing for DM and GM channels

---

app/mattermost.js

https://mattermost.atlassian.net/browse/RN-564

Hide keyboard when bringing the app to the foreground

---

app/screens/login/login.js

https://mattermost.atlassian.net/browse/RN-565

Keep keyboard open in login screen

---

app/screens/image_preview/previewer.js

https://mattermost.atlassian.net/browse/RN-568

Android: Fix image not displaying in preview

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyService.java
app/components/swiper.js
app/screens/client_upgrade/client_upgrade.js

This PR solves the following bugs:
* Upgrade app screen showing with a transparent background making the UI almost unusable
* Fixes cleanNotification by receiving the application context from the services
* Fixes a bug were we deleted a function by mistake in the swiper

Multiple bug fixes

---

app/components/post/index.js
app/components/post/post.js
app/components/post_body/post_body.js

Add copy permalink to the post tooltip/bottom sheet.
@jarredwitt

Add ability to copy post permalink

---

app/screens/settings/general/settings.js

Added help text at the beginning of the email 
https://mattermost.atlassian.net/browse/RN-247

Added text about description of the problem (RN-247)(#1267)

---

app/components/markdown/markdown.js
app/components/markdown/markdown_list.js
app/components/markdown/markdown_list_item.js
app/components/markdown/transform.js

https://mattermost.atlassian.net/browse/RN-578
This PR was tested on: iPhone 6 (iOS 10.3.3), Nexus 5 (Android 6.0)

RN-578 Properly aligned list items with indices above 10

---

app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js

Removed unused props from ChannelPostList

---

app/components/badge.js

https://mattermost.atlassian.net/browse/RN-581

Fix Flickering two-digit mention badge on hamburger menu

---

Jenkinsfile

A simple jenkinsfile for testing a new pipeline build
https://mattermost.atlassian.net/browse/PLT-8427

simple jenkinsfile for testing

---

NOTICE.txt
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/autocomplete/emoji_suggestion/index.js
app/components/emoji_picker/emoji_picker.js
app/components/emoji_picker/index.js
package.json
yarn.lock

Add fuzzy search to emoji picker in order to get emojis outside of the searchTerm.
Includes fusejs library.
- iPhone 6 Simulator
- Nexus 6P Emulator

Add fuzy search to the emoji picker

---

app/components/reactions/index.js

Add reaction to recent emojis when user clicked other user's reaction from a post
Jira ticket: [RN-593](https://mattermost.atlassian.net/browse/RN-593)
This PR was tested on: [IOS, iPhone 6 - 11.2 simulator]

RN-593: Add reaction to recent emojis when user clicked other user's reaction from a post

---

Makefile
fastlane/Fastfile
fastlane/Gemfile
fastlane/Gemfile.lock
fastlane/env_vars_example
fastlane/plist.erb

This is the first step in getting easy builds for the QA team. To get a build open a terminal and paste:
```bash
ssh administrator@207.254.73.220 "bash --login -c './build_qa.sh 1330'"
```
Install links for iOS and Android are posted to the Quality Assurance channel.
Potential future improvements include:
* Triggering builds with a slash command
* Auto-build with a pull request or pull request tag
[RN-545](https://mattermost.atlassian.net/browse/RN-545)
n/a
* iPhone 6s
* Google Nexus 5
n/a

RN-545: Builds, uploads to S3, notififes channel.

---

app/actions/views/root.js
app/mattermost.js
app/push_notifications/push_notifications.ios.js

This PR fixes an issue where replies to iOS notifications would not complete if the app was shutdown

Fix notification replies for iOS

---

app/components/markdown/markdown_image/index.js
app/components/markdown/markdown_image/markdown_image.js

https://mattermost.atlassian.net/browse/ICU-596
This PR was tested on: iOS Simulator (iPhone 6, iOS 11.2)

ICU-596 Added support for relative image URLs

---

app/screens/clock_display/clock_display.android.js
app/screens/clock_display/clock_display.ios.js
app/screens/clock_display/clock_display_base.js
app/screens/clock_display/index.js
app/screens/index.js
app/screens/settings/display_settings/display_settings.js
app/screens/settings/display_settings/index.js
app/screens/settings/general/settings.js
app/screens/settings/section.js
assets/base/i18n/en.json

Add Clock Display Settings
New Settings Item called Display which includes Clock Display Settings for now
- iOS Simulator iPhone 6 iOS 11.0
- Samsung S6 Real device Android 7.0

Clock Display Settings

---

app/components/file_attachment_list/file_attachment_document.js
app/screens/image_preview/downloader.ios.js

After cancelling file download, it waits for animation to close downloading modal
https://mattermost.atlassian.net/browse/ICU-599
ios iphone 6 emulator

Icu 599 - remove download animation on cancel

---

app/components/post_body_additional_content/index.js
app/constants/view.js

Taking into account both types of preferences to display link previews pre-server 4.4 and post
https://mattermost.atlassian.net/browse/ICU-635

[ICU-536] Fix link previews preference

---

app/components/post/index.js
app/components/post/post.js
app/components/slack_attachments/slack_attachment.js

This PR fixes an issue where posts can overlap each other when the device is rotated and then rotated back. Steps to repro issue:
1. Start scrolling messages and rotate device to landscape.
2. Rotate device back to portrait.
Expected: Messages resize correctly.
Observed: Some messages overlap each other
https://mattermost.atlassian.net/browse/ICU-448

ICU-448 Overlap post fix

---

app/screens/login_options/index.js
app/screens/login_options/login_options.js

https://mattermost.atlassian.net/browse/ICU-637

[ICU 637] Fix Gitlab login option

---

app/components/post_list/index.js
app/components/post_list/new_messages_divider.js
app/components/post_list/post_list.js
app/components/post_list/with_layout.js
assets/base/i18n/en.json

Experimental scrolling implementation for scrolling to new messages
@jarredwitt

Improve scrolling to new messages

---

app/components/channel_link/channel_link.js

https://mattermost.atlassian.net/browse/ICU-633

ICU-633 Added tilde to channel shortlink to match web app

---

app/mattermost.js
app/mattermost_bucket/index.js
app/store/index.js
app/store/middleware.js
app/utils/general.js
ios/MattermostBucket.h
ios/MattermostBucket.m
ios/MattermostShare/PerformRequests.h
ios/MattermostShare/PerformRequests.m
ios/MattermostShare/ShareViewController.m
share_extension/ios/extension_channels.js
share_extension/ios/extension_post.js
share_extension/ios/extension_teams.js
share_extension/ios/index.js

So I've made a few improvements to display the teams and channels.
I'm sending the entire `entities` from the redux store to a share container in objective-C that way we have access to whatever has been loaded while using the app, and then we only need to fetch what we don't have.
It is possible that the amount of data on the shared `entities` is big enough to cause a memory pressure, so if you think there is a better way to do this let me know.
**Try and review the PR until every little detail convinces you**

Improvements on iOS Share Extension

---

app/selectors/post_list.js
package.json
test/app/selectors/post_list.test.js
yarn.lock

Redux PR: https://github.com/mattermost/mattermost-redux/pull/392
https://mattermost.atlassian.net/browse/ICU-653
- Has redux changes (please link)

ICU-653 Stopped filtering out join/leave messages about the current user

---

app/screens/select_server/select_server.js

This PR fixes an issue in the client upgrade prompt where a crash would occur if a user choose to skip the upgrade.

ClientUpgrade: Fix bad props reference in close action

---

app/components/emoji/emoji.js
app/store/index.js

This fixes a crash with the emojis as with the last PR the size was not taken into account and it was assumed that the style was always present.
Needed to fix master.

Fix emoji sizes

---

app/components/post_header/post_header.js

Adjust margins and tap area of the search icon and reply icon in search results 
https://mattermost.atlassian.net/browse/ICU-294

Adjust margin and tap area of reply icon

---

CHANGELOG.md

1.6.1 changelog

---

app/components/tooltip.js

Fixing missing tooltip function when upgrading to the latest lib

Fixing tooltip

---

app/components/post/post.js
app/components/post_body/post_body.js
app/components/reactions/reactions.js

Add a "+" button to make it easy to add Emoji Reactions
Resolves: #1293
Jira: https://mattermost.atlassian.net/browse/MM-9321
This PR was tested on: IOS, iphone 8 plus

[MM-9321] Add a "+" button to make it easy to add Emoji Reactions

---

app/components/channel_drawer/channels_list/channels_list.js
app/components/emoji_picker/emoji_picker.js
app/components/search_bar/search_bar.android.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js
app/screens/search/search.js

Android started to respect the lineHeight, so if the lineHeight was bigger than the actual height of the TextInput the text was drawn outside of the visible area.
https://mattermost.atlassian.net/browse/MM-9637

MM-9637 Fix text not visible when typing on Android search box

---

app/components/post_body/index.js
app/components/post_body/post_body.js
app/components/reactions/index.js
app/components/reactions/reactions.js

Add reactions permissions management
[MM-9620](https://mattermost.atlassian.net/browse/MM-9620)

MM-9620: Add reactions permissions

---

yarn.lock

https://mattermost.atlassian.net/browse/MM-9289

RN-9289 Updated yarn.lock to fix deleted teams appearing on teams list

---

app/components/edit_channel_info/index.js
app/screens/edit_channel/edit_channel.js
app/screens/edit_channel/index.js

Reported by a community member that editing and changing the channel display name it wasn't being updated in the UI right away.
Fixes #1472

Fix edit channel

---

app/components/channel_drawer/teams_list/index.js
app/components/channel_drawer/teams_list/teams_list.js
app/screens/select_team/index.js
app/screens/select_team/select_team.js

Fixes Open teams that you've never been a member of aren't able to be joined, the + sign is always present in the teams drawer
https://mattermost.atlassian.net/browse/MM-9690

[MM-9690] Fix Join open teams

---

app/screens/more_channels/more_channels.js

Fix searching for public channels
https://mattermost.atlassian.net/browse/MM-9706

MM-9706 Fix search for public channels

---

app/components/options_context/options_context.ios.js

https://sentry.io/mattermost-mr/mattermost-mobile-ios/issues/464858879/

Add null check to iOS tooltip

---

app/components/post_body/post_body.js
app/utils/markdown.js

Reverted changes to normalize font size

---

yarn.lock

https://mattermost.atlassian.net/browse/MM-9740

MM-9740 Fix ping url when fallback to v3

---

share_extension/android/extension_channels/extension_channel_item.js
share_extension/android/extension_post/extension_post.js
share_extension/android/extension_teams/team_item/team_item.js
share_extension/ios/extension_post.js
share_extension/ios/extension_team_item.js

https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/491645958/

Replaced occurances of wrapWithPreventDoubleTap with preventDoubleTap

---

app/screens/channel/channel_post_list/channel_post_list.js

Fix missing code from "delay post list for animation frame"
I downloaded beta and realized it doesn't work as it worked on my dev build.
(drawer is not fluidly closing)
Looks like I missed some parts of code while sending PR, I think this was it.

Fix missing code from "delay post list for animation frame"

---

app/components/formatted_time.js

Optimize formatted_time.js

---

app/components/post_list/post_list.js
app/screens/channel_info/channel_info.js
app/screens/permalink/permalink.js
app/screens/search/search.js

Handles Android's hardware back button on permalink view to close the window using the same path as the close button.

Handle permalink Android back button

---

app/screens/channel/channel.js

Disconnect WS on Android when the app is sent to the background and reconnect on foreground.
https://mattermost.atlassian.net/browse/MM-9857

MM-9857 Disconnect WS for Android when sent to the background

---

app/actions/views/file_upload.js

https://mattermost.atlassian.net/browse/MM-9415

MM-9415 Fix convertion of heic to jpg

---

app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
app/components/channel_drawer/channels_list/filtered_list/index.js

https://mattermost.atlassian.net/browse/MM-9920

MM-9920 Fix Invalid or missing team_id parameter in request URL

---

app/components/attachment_button.js

When trying to attach a photo directly from the camera the app crashes if the permissions to access the photos wasn't set before, this PR makes sure the permission is set.
https://mattermost.atlassian.net/browse/MM-9926

MM-9926 Fix iOS crash caused by permissions

---

app/utils/theme.js
yarn.lock

Requires https://github.com/mattermost/mattermost-redux/pull/428 to be merged so that the yarn.lock can be updated

Change to use theme utils from mattermost-redux

---

package.json
yarn.lock

This is to fix the release branch building on Jenkins

Locked redux to 1.7 release branch

---

app/screens/select_team/index.js

Sort teams case insensitive
https://mattermost.atlassian.net/browse/MM-9911

MM-9911 Android fix sorting for joinable teams

---

android/app/build.gradle
app/utils/file.js
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
share_extension/ios/index.js

Fix the iOS share extension crash

Fix iOS Share Extension Crash and Bump build and version numbers (master)

---

app/components/markdown/markdown.js

https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/501424344
https://sentry.io/mattermost-mr/mattermost-mobile-ios/issues/507601935

Fixed MATTERMOST-MOBILE-ANDROID-85 (1.7)

---

app/components/markdown/markdown.js
app/reducers/views/channel.js

https://github.com/mattermost/mattermost-mobile/pull/1565
https://github.com/mattermost/mattermost-mobile/pull/1566

Cherry pick fixes for Sentry issues

---

app/components/channel_drawer/channels_list/channel_item/channel_item.js

Follows the style in https://github.com/mattermost/mattermost-webapp/pull/1033

Channel mute style

---

Makefile
app/actions/views/file_upload.js
app/components/attachment_button.js
app/components/file_attachment_list/file_attachment_image.js
app/components/file_upload_preview/file_upload_item/file_upload_item.js
app/components/file_upload_preview/file_upload_item/index.js
app/components/file_upload_preview/file_upload_preview.js
app/components/file_upload_preview/file_upload_remove.js
app/components/file_upload_preview/file_upload_retry.js
app/components/file_upload_preview/index.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
app/reducers/views/channel.js
app/reducers/views/thread.js
app/selectors/file.js
app/utils/file.js
package.json
yarn.lock

Refactored file upload to show a progress indicator while the file is being uploaded to the server
https://mattermost.atlassian.net/browse/MM-9893
* iOS 11.3 iPhone 6 and iPhone X (Simulator)
* iOS 11.3 iPhone 6s
* Android 7.1.1 Nexus 5 (Emulator)
Android
iOS

Upload progress indicator

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_document.js
app/screens/code/code.js
app/screens/text_preview/text_preview.js

Sometimes I find myself in the need to copy just part of the code snippet or a text that opens in the preview, this PR adds the ability to select part of the text.
Also added support to preview more file types.

Select text in the code/text preview screens

---

app/initial_state.js
app/store/middleware.js
yarn.lock

Fixes the app from crashing by properly cleaning the postsInThread entity

Fix posts in thread

---

app/components/custom_flat_list.js
app/components/emoji_picker/emoji_picker.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js
share_extension/android/extension_channels/extension_channels.js
share_extension/ios/extension_channels.js

This PR changes the DM Search screen to show a FlatList instead of a SectionList when a search term is entered. When searching exact matches are also prioritized over partial matches.

Show FlatList when searching in More DM Screen

---

app/actions/views/channel.js
app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/autocomplete.js
app/components/post/post.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
app/constants/post_textbox.js
app/reducers/views/channel.js

This PR fixes an issue where the username would not be inserted to the post draft if `ExperimentalUsernamePressIsMention` is set true in the config.

Fix press username to mention

---

app/screens/search/search.js
app/selectors/post_list.js

Add date separator per search result item
Jira ticket: [MM-9216](https://mattermost.atlassian.net/browse/MM-9216)
This PR was tested on: [Simulator iPhone 8, 11.2] 
Posted a confirmation at UX Design Channel - https://pre-release.mattermost.com/core/pl/4aukagrynfddugu3sjio6731zc (will update this PR depending on the design decision on that post)

[MM-9216] Add date separator per search result item

---

android/app/build.gradle

https://mattermost.atlassian.net/browse/MM-9800

Fix sentry for android

---

app/components/profile_picture/profile_picture.js

https://sentry.io/mattermost-mr/mattermost-mobile-ios/issues/529883633/

Fixed null pointer in ProfilePicture

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_document.js
app/components/file_attachment_list/file_attachment_list.js
app/screens/image_preview/downloader.android.js
app/screens/image_preview/downloader.ios.js
app/screens/image_preview/image_preview.js
app/screens/image_preview/video_preview.js
package-lock.json

Fix downloads and previews for videos and docs in Android and iOS

Fix Downloads and previews

---

README.md

Add link how to compile your own apps to README

---

app/actions/views/channel.js
app/constants/view.js
app/reducers/views/team.js

When leaving a team the last channel viewed for the team was not being removed so it tried to switch to the same channel which was already removed from the state.
https://mattermost.atlassian.net/browse/MM-10300

MM-10300 Fix crash when leaving channel

---

app/selectors/autocomplete.js

Fix channel autocomplete in search to not include private channels in public channels section
https://mattermost.atlassian.net/browse/MM-10280

Fix channel autocomplete in search to not include private channels

---

app/components/autocomplete/emoji_suggestion/emoji_suggestion.js

Fixes emoji autocomplete that was not being filtered.
https://mattermost.atlassian.net/browse/MM-10306

Fix emoji autocomplete

---

app/components/profile_picture/profile_picture.js
app/utils/image_cache_manager.js
package.json

This fixes profile images not appearing on Android and makes sure that profile pictures are updated when a user updates their profile picture

Fix profile images

---

app/actions/views/select_team.js
app/screens/channel/channel.js
app/screens/channel/index.js

This PR replaces `selectFirstAvailableTeam` with `selectDefaultTeam` that honors the `ExperimentalPrimaryTeam` config value. If the config value does not exist/is not found then the first team alphabetically is used.
@jarredwitt

Add selectDefaultTeam

---

app/components/channel_loader/channel_loader.js

Use linear gradient view, move position and opacity with animation interpolation for animation
[Issue](https://github.com/mattermost/mattermost-mobile/issues/536)
[Ticket](https://mattermost.atlassian.net/browse/RN-37)
This PR was tested on [Iphone 6s simulator, Nokia 6 device] 
Gif from simulator. So not that great but it is better on a real device

Add animation to skeleton screen

---

app/components/channel_drawer/teams_list/teams_list_item/teams_list_item.js
app/components/team_icon/team_icon.js
share_extension/android/extension_teams/team_item/team_item.js
share_extension/ios/extension_team_item.js

https://mattermost.atlassian.net/browse/MM-10405
* Android 7.1.1 Emulator
* iOS 11.3 Simulator

Cache team icon and set background to always be white

---

app/components/post_header/index.js

Fixes the post header to show the `Commented on Someone's message` when needed.
Updates mattermost-redux to fix the empty usernames in the channel drawer
https://mattermost.atlassian.net/browse/MM-10558
https://mattermost.atlassian.net/browse/MM-10559

Fix commented on Someone message

---

app/utils/url.js
app/utils/url.test.js

https://mattermost.atlassian.net/browse/MM-10617

MM-10617 Fixed checking if a link is an image

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Push notification styling improvements to match https://projects.invisionapp.com/share/YJFC6W98KM4#/screens/292745847_Push_Notifications
Server PR: https://github.com/mattermost/mattermost-server/pull/8818
Push Proxy PR: mattermost/mattermost-push-proxy#30
https://mattermost.atlassian.net/browse/MM-10504

Android Push notification styling improvements

---

README.md

This is a proposal following a customer call who asked how often the Beta apps are updated, and how they will be notified if at all.
Feel free to suggest an alternative place for this info.

Update README about weekly updates to Beta app

---

package-lock.json
package.json

Updated mattermost-redux which fixes combined post ignoring other post types.
none

Updated mattermost-redux which fixes combined post ignoring other post types

---

Makefile
NOTICE.txt
android/app/build.gradle
android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
android/settings.gradle
app/actions/device/index.js
app/components/safe_area_view/safe_area_view.ios.js
app/mattermost.js
app/screens/login/login.js
app/screens/login_options/login_options.js
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/AppDelegate.m
package-lock.json
package.json

Removes the react-native-orientation dependency

Remove orientation dependency

---

app/mattermost_managed/mattermost-managed.ios.js

We merged test code for EMM config into master, this PR reverts that

Remove test code from MattermostManaged

---

app/components/safe_area_view/safe_area_view.ios.js

Fixes the jump when rendering for the first time the channel screen on iPhone X devices
https://mattermost.atlassian.net/browse/MM-10777

Fix iPhone X safe area insets to avoid jumps

---

android/app/src/main/java/com/mattermost/react_native_interface/AsyncStorageHelper.java
android/app/src/main/java/com/mattermost/react_native_interface/KeysReadableArray.java
android/app/src/main/java/com/mattermost/react_native_interface/ResolvePromise.java
android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
android/app/src/main/java/com/mattermost/rnbeta/InitializationModule.java
fastlane/Fastfile

Fixes push notification backwards compatibility as well as some fastlane build scripts
https://mattermost.atlassian.net/browse/MM-10778
Server PR:
https://github.com/mattermost/mattermost-server/pull/8913
Push Proxy PR:
mattermost/mattermost-push-proxy#31

Fix push notification styling backwards compatibility 

---

app/actions/views/root.js

I haven't been able to actually test this because I can't send receive push notifications in my test build, but I think this should fix the issue.
https://mattermost.atlassian.net/browse/MM-10372

MM-10372 Get channel if necessary when loading from push notification

---

app/components/combined_system_message/combined_system_message.test.js
app/components/custom_list/__snapshots__/index.test.js.snap
app/components/custom_list/index.js
app/components/custom_list/index.test.js

Fix scrolling issue on profiles when adding user/s to a channel.
Jira ticket: [MM-10303](https://mattermost.atlassian.net/browse/MM-10303)

[MM-10303] Fix scrolling issue on profiles when adding user/s to a channel

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Reported by Sentry
https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/574211601/

Verify that the push notification version is not null

---

app/actions/views/channel.js
app/screens/channel/channel.js

The previous code followed the same code path that's visited when you first log in, so it sent you back to your previous channel after you leave the current one
https://mattermost.atlassian.net/browse/MM-10823

MM-10823 Switch to default channel after leaving channel

---

app/components/post_textbox/components/typing/typing.js

https://mattermost.atlassian.net/browse/MM-10814

Fix user is typing cut off on iOS

---

.eslintrc.json

As per dev decision.
n/a
n/a
n/a
n/a

Disables ESLint 'complexity' rule.

---

README.md

Make it clear MNPS is required

---

package-lock.json
package.json

Update mattermost-redux with fix on duplicated user of combined system messages
Jira ticket: [MM-10929](https://mattermost.atlassian.net/browse/MM-10929)

[MM-10929] Update mattermost-redux with fix on duplicated user of combined system messages

---

package-lock.json
package.json

This is in preparation for an eventual change to stop the server from sending out the full client config to users who aren't logged in.
https://mattermost.atlassian.net/browse/MM-8701

MM-8701 Get client config after logging in

---

app/fetch_preconfig.js
package-lock.json
package.json

Silence fetch errors caused by websocket action

---

app/screens/entry/entry.js
package-lock.json
package.json

This PR fixes a small bug where entry point never ended up showing the select server screen if the user was not logged in.
Also included in this PR is the use of a forked React Native library that includes the fix for the keyboard lag on Android

Fixes entry point and keyboard lag

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-10818

Prevent "Invalid or expired session" errors from being added to error reducer

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-11016

MM-11016 Updated redux to not error when failing to parse websocket origin

---

android/app/src/main/java/com/mattermost/share/RealPathUtil.java

This PR ensures that we always create a local copy of the file before sharing so it is always accessible
https://mattermost.atlassian.net/browse/MM-11021

Always create a temp file for Android share

---

package-lock.json
package.json

Redux changes: https://github.com/mattermost/mattermost-redux/pull/553
https://mattermost.atlassian.net/browse/MM-10996

MM-10996 Fixed getting post thread after receiving posts over the websocket (1.9.2)

---

app/components/post_list/post_list.js
app/screens/permalink/permalink.js

https://mattermost.atlassian.net/browse/MM-11073
* IOS 11.4 Simulator (iPhone X)
* Android 7.1.1 Emulator

Fix jump to recent messages

---

package-lock.json
package.json

RNFetchBlob was falling into a catch that encoded the response in base64 instead of utf-8 this PR fixes that
https://mattermost.atlassian.net/browse/MM-11055

Update RNFetchBlob to allow arabic chars

---

android/app/src/main/java/com/mattermost/share/RealPathUtil.java

Fixes an crash when selecting a file that belongs to the download provider on Android

Fix uploading files from androids download provider

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-11005

MM-11052 Cherry-pick RN fix for Android keyboard emoji autocomplete

---

share_extension/android/extension_channels/extension_channels.js

https://mattermost.atlassian.net/browse/MM-11080

Fix android extension search

---

CHANGELOG.md

Changelog 1.9.2

---

app/components/post_header/index.js
app/components/sidebars/main/main_sidebar.js
app/components/swiper.js

Fix panResponders for the iOS drawer
https://mattermost.atlassian.net/browse/MM-11097

Fix Main sidebar responder

---

app/screens/select_team/select_team.js

Requesting for 200 teams similar to web for consistent behaviour.
[MM-10919](https://mattermost.atlassian.net/browse/MM-10919)
This PR was tested on: [IOS emulator] 
Before
After

MM-10919 System Admins do not see all teams available to join on mobile.

---

package-lock.json
package.json

Updated mattermost-redux to use the fix on the themes with the mentionBg property
https://mattermost.atlassian.net/browse/MM-11096

Fix badges not using the right theme prop

---

app/store/index.js
app/store/middleware.js
app/utils/error_handling.js
app/utils/sentry/index.js
ios/MattermostBucket.m

This PR attempts to fix some crashes still seen in 1.9.2

Attempt to fix some crashes

---

app/components/post_textbox/post_textbox.js
app/components/quick_text_input.js
app/components/search_bar/search_bar.android.js
app/components/text_input_with_localized_placeholder.js
app/screens/edit_profile/edit_profile_item.js
app/screens/login/login.js
app/screens/select_server/select_server.js
share_extension/android/extension_post/extension_post.js
share_extension/ios/extension_post.js

I have no words for how ugly this hack is.
https://mattermost.atlassian.net/browse/MM-11116

MM-11116 Re-added QuickTextInput and added another hack on top of it

---

app/actions/views/channel.js
app/screens/channel/channel_post_list/channel_post_list.js

Fix continuous channel loading by adding extra pages of posts loaded (similar implementation with webapp)
Jira ticket: [MM-11004](https://mattermost.atlassian.net/browse/MM-11004)

[MM-11004] Fix continuous channel loading

---

app/i18n/index.js

pt-BR i18n could not be set as there was no `case` matching it properly.
https://mattermost.atlassian.net/browse/MM-11156

fix pt-BR availability

---

NOTICE.txt
app/components/post_body_additional_content/post_body_additional_content.js
app/utils/url.js
app/utils/url.test.js
package-lock.json
package.json

The YouTube Video Id wasn't the right one when using the `youtube-video-id` library and the link with the video had the `v=` query parameter not in the first position.
This PR fixes that.
https://mattermost.atlassian.net/browse/MM-10751

Fix getting the youtube video id

---

app/actions/views/channel.js
app/utils/push_notifications.js

Fixes the replying from push notification from Android and iOS, same issue that we were trying to dispatch a function that was not a thunk
https://mattermost.atlassian.net/browse/MM-11186

Fix replying from push notification

---

app/components/sidebars/main/main_sidebar.js

https://mattermost.atlassian.net/browse/MM-11177
This PR was tested on: iOS and Android Simulators

Set the proper size to the drawer when device rotates

---

app/actions/views/edit_profile.js
app/screens/edit_profile/edit_profile.js
app/screens/edit_profile/index.js

Fix profile upload by using RNFetchBlob
Jira ticket: [MM-11199](https://mattermost.atlassian.net/browse/MM-11199)

[MM-11199] Fix profile upload by using RNFetchBlob

---

app/components/swiper.js

https://mattermost.atlassian.net/browse/MM-11185

Prevent drawer from swiping to teams when jump to channel is focused

---

app/app.js
app/components/sidebars/settings/settings_sidebar.js
app/screens/channel/channel.js
app/screens/channel/index.js
app/store/middleware.js
app/utils/network.js
assets/base/i18n/en.json
package-lock.json
package.json

Prevent the app to get into a bad state and if that happens try and recover and other simple fixes

Handle bad state

---

app/components/post/post.js

This PR adds the flag to those posts that are rendered as consecutive messages.
https://mattermost.atlassian.net/browse/MM-11200

Mark flagged posts for consecutive messages

---

app/components/sidebars/main/main_sidebar.js

https://mattermost.atlassian.net/browse/MM-11178

Fix join channel from jump to drawer

---

app/components/sidebars/main/main_sidebar.js

https://mattermost.atlassian.net/browse/MM-11308

Fix regression DMs will not open using jump to

---

app/components/sidebars/settings/user_info/user_info.js

https://mattermost.atlassian.net/browse/MM-11207

MM-11207 Fixed wrapping of username in menu

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_icon.js
app/components/file_attachment_list/file_attachment_image.js
app/components/file_attachment_list/file_attachment_list.js
app/components/markdown/markdown.js
app/components/markdown/markdown_image/index.js
app/components/markdown/markdown_image/markdown_image.js
app/components/message_attachments/message_attachment.js
app/components/post_attachment_opengraph/index.js
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/post_body/post_body.js
app/components/post_body_additional_content/post_body_additional_content.js
app/screens/image_preview/image_preview.js
app/utils/images.js
app/utils/images.test.js

This PR makes sure that the images shown in:
* Inline images (markdown)
* OpenGraph link previews
* Link preview for an image
* Images inside message attachments
do not get cropped and they should follow the same rules than the webapp.
Also created a `images` utils file to add the size calculations and to include the functions for previewing the images, cleaning up a lot of similar code.
https://mattermost.atlassian.net/browse/MM-11328
This PR was tested on: iOS and Android
Android
iOS

Fix cropped images

---

app/components/message_attachments/message_attachment.js

Fix embedded long URL in message attachment.
It happened when attachment.text is partially forwarded to Markdown component. So instead of slicing the attachment.text when it's greater than the cap multilines or text' length, such text is fully rendered on Markdown component and just hide/show when it has overflow (depends on height). Implementation is similar to long post feature.
Jira ticket: [MM-11145](https://mattermost.atlassian.net/browse/MM-11145)
Broken (before fix):
iOS (fixed):
- https://youtu.be/ktJkQwBYBNQ
Android (fixed):

[MM-11145] Fix embedded long URL in message attachment

---

app/components/post/post.js
app/components/post_list/post_list.js

PR to improve performance by recycling the views that are not visible in the Post List

Recycle the post list

---

app/screens/edit_profile/edit_profile.js
app/screens/edit_profile/edit_profile_item.js

These values match the max lengths set in the web app
https://mattermost.atlassian.net/browse/MM-11421

MM-11421 Add max lengths when editing user profile fields

---

app/components/root/index.js
app/components/root/root.js

Minor cleanup since we were calling that setter with every store change even if the value was unchanged

Only update Client4.setAcceptLanguage when locale changes

---

app/components/sidebars/main/channels_list/channels_list.js
app/components/sidebars/main/drawer_swipper/drawer_swiper.js
app/components/sidebars/main/main_sidebar.js

Clear focus of jump to on closing drawer.
[MM-11258](https://mattermost.atlassian.net/browse/MM-11258)
This PR was tested on [Iphone simulator]

[MM-11258] Clear jumpTo focus on drawerClose

---

app/components/quick_text_input.js

Update the value of QuickTextInput on componentDidUpdate
Jira ticket: [MM-11454](https://mattermost.atlassian.net/browse/MM-11454)

[MM-11454] Update the value of QuickTextInput on componentDidUpdate

---

app/components/sidebars/settings/settings_sidebar.js

Fixes: https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/626768012/

Fix close setting sidebar when setting status

---

app/components/announcement_banner/__snapshots__/announcement_banner.test.js.snap
app/components/announcement_banner/announcement_banner.test.js
app/components/channel_icon.js
app/components/post_body/index.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
app/components/reactions/index.js
app/components/reactions/reactions.js
app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
app/components/sidebars/main/channels_list/channel_item/channel_item.js
app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
app/components/sidebars/main/channels_list/channel_item/index.js
app/screens/channel/channel_nav_bar/channel_title/channel_title.js
app/screens/channel/channel_nav_bar/channel_title/index.js
app/screens/channel_info/channel_info.js
app/screens/permalink/index.js
app/screens/permalink/permalink.js
app/screens/search/index.js
app/screens/search/search.js
app/screens/thread/index.js
app/screens/thread/thread.js
assets/base/i18n/en.json
package-lock.json
package.json

Adds ability to view archived channels.
[MM-11070](https://mattermost.atlassian.net/browse/MM-11070)
Emulated iPhone 6, iOS 11.4

MM-11070: Adds ability to view archived channels.

---

app/screens/settings/notification_settings_email/index.js

Set default value whenever the getPreference returns null or undefined
Jira ticket: [MM-11485](https://mattermost.atlassian.net/browse/MM-11485)

[MM-11485] Set default value whenever the getPreference returns null or undefined

---

app/components/post_body/post_body.js

Fixes propType of replyBarStyle

Fix render prop of replyBarStyle

---

ios/MattermostBucket.m
package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-11479

Attempt to fix EXC_BAD_ACCESS from CFArrayGetValueAtIndex

---

app/app.js

This error does not cause a crash but at least now we can log when it happens
https://mattermost.atlassian.net/browse/MM-11480

Wrap set credentials for the keychain in a try/catch

---

package-lock.json
package.json

I don't know if this'll actually help as much as the other changes, but it might

MM-11477 Update react-native-sentry and sentry-javascript

---

app/actions/views/login.js
app/actions/views/root.js
app/app.js
app/fetch_preconfig.js
app/mattermost.js
app/screens/sso/sso.js
app/utils/push_notifications.js

I leaned towards handling these in the app vs redux since the app better understands how to handle these errors.

MM-11477 Ensure client calls are wrapped with error handling

---

package-lock.json
package.json

Update redux.
[MM-11586](https://mattermost.atlassian.net/browse/MM-11586)
n/a

MM-11586: Updates redux.

---

app/screens/permalink/index.js
app/screens/permalink/permalink.js

https://mattermost.atlassian.net/browse/MM-11648

Do not close permalink view when post is deleted

---

app/components/sidebars/main/main_sidebar.js

Dismiss keyboard on close of LHS
[MM-11258](https://mattermost.atlassian.net/browse/MM-11258)
This PR was tested on: [Android and IOS emulators]

[MM-11258] Close keyboard on close of LHS

---

app/screens/about/about.js
assets/base/i18n/en.json

About dialog layout fixes and changed `platform` for `server`
https://mattermost.atlassian.net/browse/MM-11615
https://mattermost.atlassian.net/browse/MM-11616

Fix About dialog layout

---

package-lock.json
package.json

Update redux to fix the MM-11576 bug.
[MM-11576](https://mattermost.atlassian.net/browse/11576)

MM-11576: Updates redux.

---

app/components/sidebars/main/main_sidebar.js
assets/base/i18n/en.json

Add a defensive check for channel obj. If channel obj does not exist exit early. 
[MM-11487](https://mattermost.atlassian.net/browse/MM-11487)

[MM-11487] Add a defensive check for channel obj

---

app/screens/more_dms/more_dms.js

Clear search after selecting a user
Jira ticket: [MM-11625](https://mattermost.atlassian.net/browse/MM-11625)
iOS: https://youtu.be/BUeubXM4YhY
Android: https://youtu.be/rVUKT91jN3k

[MM-11625] Clear search after selecting a user

---

app/screens/channel_info/channel_info.js

Updates archive channel button icon to work with themes.
[MM-11721](https://mattermost.atlassian.net/browse/MM-11721)
n/a
iPhone 6, iOS 11.4 emulator

MM-11721: Updates archive channel button icon.

---

app/components/post_body_additional_content/post_body_additional_content.js
app/utils/url.js

Displays preview for shortened image links.
[MM-11318](https://mattermost.atlassian.net/browse/MM-11318)
* Android 7.1.1 emulator 
* iPhone 6, iOS 11.4 emulator

MM-11318: Expands shortened links inline.

---

app/components/search_bar/search_box.js
app/screens/edit_profile/edit_profile_item.js

Fixes grey highlight in text fields
[MM-11684](https://mattermost.atlassian.net/browse/MM-11684)
This PR was tested on: [Iphone x simulator] 
Before:
After:

MM-11684 Fix grey highlight in the text fields in user profile

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_document.js
app/components/file_attachment_list/file_attachment_list.js
app/components/file_attachment_list/index.js
assets/base/i18n/en.json

https://mattermost.atlassian.net/browse/MM-11286

Disallow download of all file types on RN apps when disallowed in System console

---

app/screens/permalink/permalink.js

When opening a permalink check the response so it is not undefined before trying to join a channel
https://mattermost.atlassian.net/browse/MM-11769

Check if post.data has values bofore joining a channel

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_list.js
app/components/post_body/post_body.js
app/screens/long_post/long_post.js

Now tapping in the filename box on the file attachment will open the file preview, or download the doc and open the viewer for it.
https://mattermost.atlassian.net/browse/MM-11643

Open file attachment preview when tapping on the filename

---

app/components/autocomplete/date_suggestion/date_suggestion.js

https://mattermost.atlassian.net/browse/MM-11913
This PR was tested on: Android & iOS
iOS
Android

Add theming to calendar selector

---

app/screens/settings/notification_settings_email/notification_settings_email.android.js
app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js

Fix email notification setting on Android (which I thought was fixed by https://github.com/mattermost/mattermost-mobile/pull/2051)
Jira ticket: [MM-11774](https://mattermost.atlassian.net/browse/MM-11774)

[MM-11774] Fix email notification setting on Android

---

app/components/failed_network_action/index.js
app/screens/select_team/__snapshots__/select_team.test.js.snap
app/screens/select_team/index.js
app/screens/select_team/select_team.js
app/screens/select_team/select_team.test.js
assets/base/i18n/en.json

Add error screen when getTeams request fail
[MM-11603](https://mattermost.atlassian.net/browse/MM-11603)
This PR was tested on: [Ios emulator]

MM-11603 Fix select_team ui to have failed request scenario

---

app/components/message_attachments/message_attachment.js
app/components/post_body/post_body.js
app/components/show_more_button/__snapshots__/show_more_button.test.js.snap
app/components/show_more_button/index.js
app/components/show_more_button/show_more_button.js
app/components/show_more_button/show_more_button.test.js

Fix styling of show more/less on message attachment similar to "long post"
Jira ticket: [MM-11928](https://mattermost.atlassian.net/browse/MM-11928)
This PR was tested on: [iPhone simulator and Android emulator] 
iPhone: https://youtu.be/h8SMkoqYk54
Android: https://youtu.be/AFu7T-zUBqk

[MM-11928] Fix styling of show more/less on message attachment similar to "long post"

---

app/components/autocomplete/slash_suggestion/slash_suggestion.js
app/components/autocomplete/slash_suggestion/slash_suggestion_item.js

Display trigger word instead of display name for slash command autocomplete
https://mattermost.atlassian.net/browse/MM-11963

Display trigger word in slash command autocomplete

---

app/components/at_mention/at_mention.js

https://mattermost.atlassian.net/browse/MM-11968

MM-11968 Fix uppercase at mentions

---

package-lock.json
package.json

https://github.com/mattermost/mattermost-mobile/issues/1951

GH-1951 Update commonmark.js to support images with dimensions

---

app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention/index.js
app/selectors/autocomplete.js

Filter archived channels by membership on search autocomplete
[MM-11725](https://mattermost.atlassian.net/browse/11725)

MM-11725: Filter archived channels by membership on search autocomplete

---

app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/utils/image_cache_manager.js
app/utils/images.js

Fixes some race conditions with the ImageCacheManager and for the openGraph images now there is no need to use the ProgressiveImage component
https://mattermost.atlassian.net/browse/MM-11990

Make sure opengraph displays images

---

app/components/options_context/options_context.ios.js
app/components/post/post.js

https://mattermost.atlassian.net/browse/MM-12022

fix contextOption for post

---

app/components/markdown/markdown_image/markdown_image.js
app/components/options_context/options_context.ios.js

Tapping on a post wasn't transitioning to the thread view, this PR fixes that
https://mattermost.atlassian.net/browse/MM-12055

Fix iOS tap on post

---

app/components/post_body_additional_content/index.js
app/components/post_body_additional_content/post_body_additional_content.js
app/utils/url.js
package-lock.json
package.json

This matches the web app behaviour and prevents the app from directly contacting any linked address
https://mattermost.atlassian.net/browse/MM-12109

MM-12109 Switch to using server API to determine redirect location

---

app/components/post_body_additional_content/post_body_additional_content.js

https://mattermost.atlassian.net/browse/MM-12109

MM-12109 Fix handling of return value of getRedirectLocation

---

app/utils/file.js

https://mattermost.atlassian.net/browse/MM-12126

Fix unable to delete file cache in Android

---

app/screens/options_modal/__snapshots__/option_modal_list.test.js.snap
app/screens/options_modal/option_modal_list.test.js
app/screens/options_modal/options_modal_list.android.js
app/screens/options_modal/options_modal_list.ios.js

https://mattermost.atlassian.net/browse/MM-11984

Fix Option modal items tap effect off center

---

app/actions/views/more_dms.js
app/components/sidebars/main/channels_list/channels_list.js
app/components/sidebars/main/main_sidebar.js

When using the Jump to feature we were trying to perform some actions that were interfering with the UI thread, by using a combination of setTimeout and requestAnimationFrame the stuttering is no longer seen
https://mattermost.atlassian.net/browse/MM-12156

Fix drawer stutter when jumping to a DM or joining a channel

---

package-lock.json
package.json

CommonMark changes: https://github.com/mattermost/commonmark.js/commit/971456e6d3f07b14effac73718d1de768586876a
https://mattermost.atlassian.net/browse/MM-11955

MM-11955 Improve handling of whitespace around tables

---

app/actions/views/login.test.js
app/actions/views/select_server.test.js
app/actions/views/thread.test.js
app/components/custom_list/user_list_row/user_list_test.test.js
app/screens/select_team/select_team.test.js
app/screens/user_profile/user_profile.test.js
app/store/middleware.test.js
test/setup.js

Change rn-fetch-blob to mock globally in jest

Change rn-fetch-blob to mock globally in jest

---

app/components/options_context/options_context.ios.js

https://mattermost.atlassian.net/browse/MM-12190

Fix post background color from getting stuck

---

app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js
app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js

Keywords are now saved when the submit button is pressed on the keyboard
https://mattermost.atlassian.net/browse/MM-12030

Fix mention keywords setting

---

app/components/file_attachment_list/file_attachment_document.js
app/components/file_attachment_list/file_attachment_icon.js

* Fix attachment icon background-color.
* Fix attachment icon alignment when downloading.
[https://mattermost.atlassian.net/browse/MM-12038](MM-12038)
This PR was tested on: Emulators (IOS and android)

MM-12038 Fix attachment icon styling

---

app/screens/search/index.js

Hide the archived messages on search results when ViewArchivedChannels is disabled
[MM-12004](https://mattermost.atlassian.net/browse/MM-12004)

MM-12004: Hide the archived messages on search results when ViewArchivedChannels is disabled

---

app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/post_attachment_opengraph/post_attachment_opengraph.test.js

Add test to PostAttachmentOpenGraph component (did some refactor to make it easily tested)
Jira ticket: [MM-12016](https://mattermost.atlassian.net/browse/MM-12016)
This PR was tested on: [iOS and Android simulator/emulator]

[MM-12016] Add test to PostAttachmentOpenGraph component (did some refactor to make it easily tested)

---

app/selectors/autocomplete.js

Close channel autocomplete if multiple tildes are typed.
https://mattermost.atlassian.net/browse/MM-11822
Galaxy S9

MM-11822 Close channel autocomplete if multiple tildes are typed

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
app/actions/views/root.js
app/i18n/index.js
app/push_notifications/push_notifications.android.js
app/push_notifications/push_notifications.ios.js
app/utils/push_notifications.js
assets/base/i18n/en.json

When replying to a notification fails we now display a local notification giving feedback to the user
https://mattermost.atlassian.net/browse/MM-9925

Show local notification when replying to PN fails

---

app/components/file_upload_preview/file_upload_item/file_upload_item.js
app/screens/edit_profile/edit_profile.js
app/screens/image_preview/downloader.android.js

Fixed post attachments, profile image upload and file downloads
https://mattermost.atlassian.net/browse/MM-12274

Post attachments failing to upload

---

app/screens/sso/sso.js

Changed the code so that the `postMessage` is triggered once the flow is completed and no need to switch the state from having to decide if `postMessage` is triggered.
https://mattermost.atlassian.net/browse/MM-12284

Fix SSO error display

---

fastlane/Fastfile

Re-write part of the fastlane script to set the right values in the config.json file by loading and parsing the file, setting the right values and saving the file back to the filesystem, this way we ensure the right values are written and it does not depend on the previous value that the json property had.
https://mattermost.atlassian.net/browse/MM-12277

Update fastlane script to ensure right config.json output

---

app/components/file_upload_preview/file_upload_item/file_upload_item.js

Fixes alignment of progress percentage text
[https://mattermost.atlassian.net/browse/MM-11988](MM-11988)

[MM-11988] Fix File Upload loading progress indicator alignment

---

app/components/autocomplete/autocomplete.js
app/components/client_upgrade_listener/client_upgrade_listener.js
app/components/emoji_picker/emoji_picker.js
app/components/offline_indicator/offline_indicator.js
app/components/start/empty_toolbar.js
app/screens/channel/channel.js
app/screens/channel/channel_nav_bar/channel_nav_bar.js
app/screens/search/search.js

We missed a few places where we identified if the device running the app is an new iPhone model

Add support for new iPhone models in missing places

---

app/actions/views/channel.js
app/screens/channel_info/channel_info.js
app/screens/channel_info/index.js
package-lock.json
package.json

Back to previous channel on archive
[MM-11577](https://mattermost.atlassian.net/browse/MM-11577)

MM-11577: Back to previous channel on archive

---

app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention/index.js
app/components/autocomplete/channel_mention_item/channel_mention_item.js
app/components/autocomplete/channel_mention_item/index.js
app/selectors/autocomplete.js
app/selectors/channel.js
assets/base/i18n/en.json

Autocomplete search in: for DMs and GMs
[MM-11567](https://mattermost.atlassian.net/browse/MM-11567)
Depends on mattermost/mattermost-server#9430

MM-11567: Autocomplete search in: for DMs and GMs

---

app/actions/views/channel.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js

Back to prev channel on close archived channel
[MM-11606](https://mattermost.atlassian.net/browse/MM-11606)

MM-11606: Back to prev channel on close archived channel

---

app/screens/channel_info/channel_info.js
app/screens/channel_info/channel_info_header.js

Fixes typo in component import and adds missing param.
https://mattermost.atlassian.net/browse/MM-12061
This PR was tested on: iPhone 6, iOS 12.0 (emulator)
n/a

MM-12061: Fixes component name typo and adds missing param.

---

Makefile
fastlane/Fastfile
fastlane/Gemfile.lock
fastlane/Pluginfile

Updated fastlane build script so it adapts to the new process (branching and release).
This PR simplifies a lot of the env vars used to build the app and also combines the ios and android lanes to build both apps in sequence with the command **make build**
I will be updating the docs as soon as possible, but first will tackle other priority tickets
https://mattermost.atlassian.net/browse/MM-12394

Fastlane update to include new build process

---

app/constants/list.js
app/screens/search/search.js
package-lock.json
package.json

Improved how to fetch more results by using the onScroll event and adds a loading indicator in case results are not still being retrieved
MM-12399

Fix search screen from braking and improved how to get more results

---

fastlane/plist.erb

Fix the plist script used for building the app for QA tests

Fix plist used for qa builds

---

app/components/markdown/markdown_code_block/markdown_code_block.js
app/screens/thread/__snapshots__/thread.test.js.snap
app/screens/thread/thread.js
app/screens/thread/thread.test.js
package.json
test/setup.js

Fix issue that blocks adding test for thread screen and potentially to other components
Jira ticket: [MM-12266](https://mattermost.atlassian.net/browse/MM-12266)

[MM-12266] Fix issue that blocks adding test for thread screen and potentially to other components

---

android/app/build.gradle

The fresco library needed to be updated to work with RN 57
https://mattermost.atlassian.net/browse/MM-12595

Fix gifs displaying as still images on Android

---

app/screens/settings/notification_settings_mentions/notification_settings_mention_base.js
app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js

https://mattermost.atlassian.net/browse/MM-12566

Fix update keywords field on Android

---

Makefile
fastlane/Fastfile
fastlane/plist.erb

Submit the app to the stores once the apps did finish building, either individual apps or both sequentially.
Also updates the script to build PRs

Update Fastlane scripts

---

package-lock.json
package.json

Updates redux ref.
n/a
none
n/a

Updates redux ref.

---

package-lock.json
package.json

Updates redux ref.
n/a
none
n/a

Updated redux ref.

---

app/components/attachment_button.js
app/components/file_upload_preview/file_upload_preview.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
assets/base/i18n/en.json
share_extension/android/extension_post/extension_post.js

Show a message when trying to update an file larger than the allowed max file size from the post textbox, and properly show an error message for the Android Share Extension
https://mattermost.atlassian.net/browse/MM-12501
This PR was tested on: iOS and Android

Properly handle max file size

---

app/components/channel_icon.js
app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
app/components/sidebars/main/channels_list/channel_item/channel_item.js
app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
app/components/sidebars/main/channels_list/channel_item/index.js

* Add isArchived flag for all DM's and channels
* Exclude search results from channel_list component to show
results when isSearchResult flag is set
This is to let user search for deactivated users from jumpto
[MM-12491](https://mattermost.atlassian.net/browse/MM-12491)
For archive bug
For search of deactivated users

MM-12491 Fix archive channels staying in LHS

---

app/components/file_attachment_list/file_attachment_icon.js

https://mattermost.atlassian.net/browse/MM-12655

Set explicit white background to icon previews

---

app/components/post_list/post_list.android.js

Add check for renderFooter as it can be of type func or object
(MM-12652)[https://mattermost.atlassian.net/browse/MM-12652]
This PR was tested on: [Andoird]

MM-12652 Fix for android thread crash

---

app/screens/search/search.js

Re-calculate how far the search results need to scroll for iOS and for Android
https://mattermost.atlassian.net/browse/MM-12563

Scroll search results to the top

---

Makefile

By using `npm ci` instead of `npm install` we ensure that the right packages are being used and `package-lock.json` does not get updated.

Update build script to run npm ci instead of npm install

---

app/screens/channel/channel.js

The Theme was not updating the channel screen background color of the post list view, but in fact was not even necessary thus getting rid of potential overdraw and fixing the issue
https://mattermost.atlassian.net/browse/MM-12681

Fix backgroundColor when updating the theme in real time

---

Makefile

Fixes a build-typo when trying to build a PR
On review is enough

Fix typo in build script

---

app/fetch_preconfig.js
assets/base/config.json

Add custom headers from the local config as key value pairs
https://mattermost.atlassian.net/browse/MM-12673

Add ability to include custom headers with requests

---

app/components/channel_link/__snapshots__/channel_link.test.js.snap
app/components/channel_link/channel_link.js
app/components/channel_link/channel_link.test.js
app/components/channel_link/channel_link_utils.js
app/components/channel_link/channel_link_utils.test.js

Refactor ChannelLink and add test into it
none

Refactor ChannelLink and add test into it

---

app/actions/views/select_team.js
app/store/middleware.js
app/utils/teams.js
app/utils/teams.test.js

There have been some reports saying that sometimes when opening the app you reach the screen saying you don't belong to any team.
This PR attempts to handle that by retrying fetching your teams to ensure that the user actually does not belong to any team before presenting the screen and if needed it will present the screen saying that there was an error fetching the teams.
https://mattermost.atlassian.net/browse/MM-12758

Retry fetching teams if no teams are found

---

app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js

https://mattermost.atlassian.net/browse/MM-12835

Add padding to tap effect for team list item

---

app/components/sidebars/main/teams_list/index.js
app/components/sidebars/main/teams_list/teams_list.js

Checks if there are other joinable teams before showing the "+" sign in the teams sidebar
https://mattermost.atlassian.net/browse/MM-12833

Show join teams option only if there are other joinable teams

---

app/components/autocomplete/autocomplete.js
app/components/client_upgrade_listener/client_upgrade_listener.js
app/components/emoji_picker/emoji_picker.js
app/components/offline_indicator/offline_indicator.js
app/components/reactions/reactions.js
app/components/safe_area_view/safe_area_view.ios.js
app/components/slide_up_panel/index.js
app/components/slide_up_panel/slide_up_panel.js
app/components/slide_up_panel/slide_up_panel_indicator.js
app/components/start/empty_toolbar.js
app/constants/device.js
app/constants/index.js
app/screens/channel/channel.js
app/screens/channel/channel_nav_bar/channel_nav_bar.js
app/screens/client_upgrade/client_upgrade.js
app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
app/screens/reaction_list/__snapshots__/reaction_header_item.test.js.snap
app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
app/screens/reaction_list/__snapshots__/reaction_row.test.js.snap
app/screens/reaction_list/reaction_header.js
app/screens/reaction_list/reaction_header_item.js
app/screens/reaction_list/reaction_list.js
app/screens/reaction_list/reaction_list.test.js
app/screens/reaction_list/reaction_row.js
app/screens/search/search.js
app/screens/select_server/select_server.js
app/store/middleware.test.js
app/utils/client_upgrade.js
test/setup.js

Created a component that can be used with a modal to display slide up panel.
This PR uses the slideUpPanel with the reaction lists
Feel free to ask any questions about the code.
Note: @saturninoabril if you have ideas on how that code can be tested please let me know.
https://mattermost.atlassian.net/browse/MM-12228

Slide up panel for reaction list

---

package-lock.json
package.json

* Update mm-redux hash
[MM-12841](https://mattermost.atlassian.net/browse/MM-12841)

MM-12841 Fix for unread muted channels sorting

---

app/screens/image_preview/__snapshots__/downloader_bottom_content.test.js.snap
app/screens/image_preview/downloader.ios.js
app/screens/image_preview/downloader_bottom_content.js
app/screens/image_preview/downloader_bottom_content.test.js

Removes downloading message on cancelling downloads
(MM-12675)[https://mattermost.atlassian.net/browse/MM-12675]
This PR was tested on: [Android Emulator]

MM-12923 Fix Downloading message on cancelling downloads

---

app/screens/channel/index.js
app/screens/post_options/index.js

With the changes for the new post menu deleting a post was causing the app to crash
https://mattermost.atlassian.net/browse/MM-13032

Fix crash when deleting a post

---

package-lock.json
package.json

These new changes won't really affect the mobile app since they're a fix for an issue on the web app, but I'm submitting this for consistency
https://mattermost.atlassian.net/browse/MM-13020

MM-13020 Update mattermost-redux

---

app/components/post/index.js
app/components/post/post.js
package-lock.json
package.json

Add reply mention highlight to replyBar
[MM-12755](https://mattermost.atlassian.net/browse/MM-12755)
This PR was tested on: [Emulators]

MM-12755 Add reply mention highlight for replyBar

---

app/screens/search/__snapshots__/modifier.test.js.snap
app/screens/search/__snapshots__/recent_item.test.js.snap
app/screens/search/modifier.js
app/screens/search/modifier.test.js
app/screens/search/recent_item.js
app/screens/search/recent_item.test.js
app/screens/search/search.js

https://mattermost.atlassian.net/browse/MM-12953

Properly scroll to search results

---

app/screens/search/__snapshots__/modifier.test.js.snap
app/screens/search/__snapshots__/recent_item.test.js.snap

@sudheerDev fixing the failing tests on master caused by a merge after the dependency update PR went in

Fixing failed tests

---

app/components/channel_intro/channel_intro.js
app/components/file_attachment_list/file_attachment_list.js
app/components/load_more_posts/load_more_posts.js
app/components/markdown/markdown.js
app/components/markdown/markdown_image/markdown_image.js
app/components/message_attachments/attachement_pretext.js
app/components/message_attachments/attachment_actions.js
app/components/message_attachments/attachment_author.js
app/components/message_attachments/attachment_fields.js
app/components/message_attachments/attachment_image.js
app/components/message_attachments/attachment_text.js
app/components/message_attachments/attachment_thumbnail.js
app/components/message_attachments/attachment_title.js
app/components/message_attachments/index.js
app/components/message_attachments/message_attachment.js
app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
app/components/post_body/index.js
app/components/post_body/post_body.js
app/components/post_body_additional_content/post_body_additional_content.js
app/components/reactions/reactions.js
package-lock.json
package.json

Adds support for post-metadata to prevent scroll pops.
https://mattermost.atlassian.net/browse/MM-11608

Use post metadata to prevent scroll pop

---

ios/Mattermost.xcodeproj/project.pbxproj
ios/uploadDebugSymbols.sh
package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-12896

Upgrade sentry to 0.39.1

---

app/mattermost.js
assets/base/config.json

Disable sending telemetry data when running the app in a development environment
https://mattermost.atlassian.net/browse/MM-13063

Disable segment for dev env

---

app/screens/index.js
app/screens/settings/display_settings/__snapshots__/display_settings.test.js.snap
app/screens/settings/display_settings/display_settings.js
app/screens/settings/display_settings/display_settings.test.js
app/screens/settings/display_settings/index.js
app/screens/theme/__snapshots__/theme.test.js.snap
app/screens/theme/index.js
app/screens/theme/theme.js
app/screens/theme/theme.test.js
app/selectors/theme.js
app/utils/theme.js
assets/base/i18n/en.json

This change allows users to view and change their visual theme from the settings menu. 
https://jira.uberinternal.com/browse/UCHAT-3821
This PR was tested on: Nexus 6 (Android), iPhone X (iOS)
@dseawel

Theme selection screen

---

app/actions/views/channel.js

Sometimes the channel intro was not shown and instead we had an endless spinner cause the action was not considering the combined join/leave system messages and was counting all the posts.

Count the posts received after combining join/leave

---

app/components/emoji/emoji.js
app/components/file_attachment_list/file_attachment_list.js
app/components/network_indicator/network_indicator.js
app/components/post/post.js
app/components/post_body/post_body.js
app/components/post_body_additional_content/post_body_additional_content.js
app/components/reactions/reactions.js

1. with `marginTop` the emoji started to change on its own the dimensions causing the post to increase its height constantly, without the `marginTop` the emoji is actually centered with the text on iOS and Android
2. Removed Views and `flex: 1` in places where it wasn't needed removing the need to do some calculations in the layout and this should permanently fix the text being cutoff at random times.
3. Fix the placement of the network indicator on non iPhone X devices.
https://mattermost.atlassian.net/browse/MM-11965

Fix Post and network indicator Layouts

---

app/screens/post_options/post_option.js
app/screens/post_options/post_options.js

The post menu had some issues with touchables on Android, tapping on the button wasn't always caught by the pan responder.
Also made it so the the menu displays all the items at once
https://mattermost.atlassian.net/browse/MM-13202

Fix post menu touchables

---

app/actions/views/channel.js

Only back to previous channels if the channel itself is not archived. If
it is archived, back to the Town Square.
[MM-12960](https://mattermost.atlassian.net/browse/MM-12960)

MM-12960: Only back to previous channel if is not archived

---

app/components/post_body_additional_content/index.js

Fixing no parseable (by the i18n extractor) optional chaining construction

Fixing no parseable (by the i18n extractor) optional chaining construction

---

android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
android/app/src/main/java/com/mattermost/share/RealPathUtil.java

https://mattermost.atlassian.net/browse/MM-13026

Android: Fix crash when attaching files from the downloads folder

---

app/screens/more_channels/__snapshots__/more_channels.test.js.snap
app/screens/more_channels/more_channels.js

Fix displaying more public channels to join
https://mattermost.atlassian.net/browse/MM-13215

Fix fetching more channels to join

---

app/components/message_attachments/message_attachment.js
app/components/post_body/post_body.js

This PR fixes the following issues with the post layout:
* Long post with "Show More" are broken
* Code blocks are not displayed properly on RN 
* Combined system messages not wrapping in the post list
* Markdown bullets and lists are not displaying properly on RN
Also removed all the unnecessary `<View>` wrappers, the less Views we need to render the faster the components do render
https://mattermost.atlassian.net/browse/MM-13244
https://mattermost.atlassian.net/browse/MM-13246
https://mattermost.atlassian.net/browse/MM-13251
https://mattermost.atlassian.net/browse/MM-13245

More fixes to the post layout

---

Makefile

Adding i18n-extract task to the Makefile

Adding i18n-extract task to the Makefile

---

NOTICE.txt
android/app/build.gradle
android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
android/settings.gradle
app/actions/views/channel.js
app/components/file_attachment_list/file_attachment_list.js
app/components/file_attachment_list/index.js
app/components/post/post.js
app/components/post_body/post_body.js
app/components/reactions/reactions.js
app/components/slide_up_panel/slide_up_panel.js
app/components/slide_up_panel/slide_up_panel_indicator.js
app/screens/index.js
app/screens/post_options/post_option.js
app/screens/post_options/post_options.js
app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
app/screens/reaction_list/reaction_header.js
app/screens/reaction_list/reaction_list.js
app/selectors/post_list.js
app/selectors/post_list.test.js
index.js
ios/Mattermost.xcodeproj/project.pbxproj
package-lock.json
package.json
test/setup.js

Make new Post Menu responsive on Android
Also made some unrelated improvements to FileAttachments
Very involved PR
https://mattermost.atlassian.net/browse/MM-13202

post menu and file attachments

---

app/components/network_indicator/network_indicator.js

When the app is sitting in the background and there are notifications for the current channel we are going to wait for 1 second before clearing the notifications from the Notification center when the app is brought to the foreground, we do this so in case the app is being brought to the background by opening a notification for a different channel we can cancel the clearing of the notification for the channel that is in the view before the channel switch happens.
https://mattermost.atlassian.net/browse/MM-13189

Wait 1s before clearing notifications

---

share_extension/android/extension_channels/extension_channels.js

https://mattermost.atlassian.net/browse/MM-13357

Android extension channel list to display all items

---

fastlane/env_vars_example

Update the example environment variables needed to build the app with Fastlane
Resolves #2401

Update fastlane env vars example

---

app/screens/settings/display_settings/display_settings.js
app/screens/settings/display_settings/display_settings.test.js
app/screens/settings/general/settings.js
app/screens/theme/theme.js
app/screens/theme/theme.test.js

Update the Settings/Display/Theme screens navbar with the selected theme color
https://mattermost.atlassian.net/browse/MM-13362

MM-13362 Update account settings header color when changing theme

---

app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js

https://mattermost.atlassian.net/browse/MM-13350

Fix team mention badge alignment on iOS

---

app/screens/channel_info/channel_info.js
app/screens/channel_info/index.js
package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-13389

Sort pinned posts from newest to oldest

---

app/screens/image_preview/image_preview.js
app/utils/images.js
app/utils/images.test.js

Respect the viewport height to display the image preview
https://mattermost.atlassian.net/browse/MM-13368

MM-13368 Do not truncate tall images in preview screen

---

app/components/attachment_button.js
app/components/profile_picture/profile_picture.js
app/screens/edit_profile/edit_profile.js

Fix the image profile not appearing on the edit screen on the second attempt and also prevent for uploading non-images files
https://mattermost.atlassian.net/browse/MM-13365
https://mattermost.atlassian.net/browse/MM-13375

MM-13365/MM-13375 Fix edit profile image

---

app/components/post_textbox/index.js

https://mattermost.atlassian.net/browse/MM-13419

MM-13419 Fix leaving private channel from another client

---

package-lock.json
package.json

Update redux commit to fix sorting of channels at sidebar unreads section
Jira ticket: [MM-13398](https://mattermost.atlassian.net/browse/MM-13398)

[MM-13398] Update redux commit to fix sorting of channels at sidebar unreads section

---

app/components/sidebars/main/channels_list/list/index.js

https://mattermost.atlassian.net/browse/MM-13420
This PR was tested on: iOS Simulator (iPhone X, iOS 12.1)

MM-13420 Always show the Unreads section in the channel list

---

app/screens/channel_info/channel_info.js

https://mattermost.atlassian.net/browse/MM-13403

prevent double tap on Channel Info options

---

app/components/post_list/date_header/__snapshots__/date_header.test.js.snap
app/components/post_list/date_header/date_header.js
app/components/post_list/date_header/date_header.test.js
app/components/post_list/date_header/index.js

When the timezoone changes (experimental feature) update the date separators accordingly to reflect the timezone.
https://mattermost.atlassian.net/browse/MM-11611

Update date separators when timezone changes

---

app/screens/channel_info/channel_info.js

https://mattermost.atlassian.net/browse/MM-13401

Remove extra divider below Edit Channel in Channel info

---

app/actions/views/edit_profile.js
app/components/__snapshots__/profile_picture_button.test.js.snap
app/components/attachment_button.js
app/components/profile_picture/profile_picture.js
app/components/profile_picture_button.js
app/components/profile_picture_button.test.js
app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap
app/screens/edit_profile/edit_profile.js
app/screens/edit_profile/edit_profile.test.js
app/screens/edit_profile/index.js
app/screens/options_modal/options_modal_list.android.js
app/screens/options_modal/options_modal_list.ios.js

Add ability to remove profile image
https://mattermost.atlassian.net/browse/MM-12354
This PR was tested on: iPhone X Simulator, iOS 12.1

MM-12354 Remove Profile Image

---

app/components/reactions/index.js
app/components/reactions/reactions.js
app/utils/reaction.js
app/utils/reaction.test.js
package-lock.json
package.json

Fix unnecessary rendering for reactions component and reaction list screen
Jira ticket: [MM-13433](https://mattermost.atlassian.net/browse/MM-13433)
This PR was tested on: [iOS simulator, Android emulator] 
BEFORE: 
AFTER:

[MM-13433] Fix unnecessary rendering for reactions component and reaction list screen

---

app/components/slide_up_panel/slide_up_panel.js

https://mattermost.atlassian.net/browse/MM-13571

Fix post menu rounded corners

---

app/initial_state.js
app/screens/channel_members/index.js
package-lock.json
package.json

Removes 
getProfilesInChannel, searchProfiles and removeChannelMember status flags
[MM-13544](https://mattermost.atlassian.net/browse/MM-13544)

MM-13432 Remove unsed request flags from channel_members

---

app/components/post_body/post_body.js

Failed post option was not visible on screen.
https://mattermost.atlassian.net/browse/MM-13597

Fix visibility of retry failed message option

---

app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js

https://mattermost.atlassian.net/browse/MM-13660

Fix Keywords modal title on Android

---

app/screens/settings/general/settings.js

https://mattermost.atlassian.net/browse/MM-13703

MM-13703 Fix settings screen not showing joinable teams

---

app/components/file_attachment_list/file_attachment_document.js

https://mattermost.atlassian.net/browse/MM-13665

MM-13665 Prevent quick multiple taps on file to open multiple file previews

---

app/screens/thread/__snapshots__/thread.test.js.snap
app/screens/thread/thread.js

Change the prop `indicateNewMessages` on postList in thread view to be false
[MM-13752](https://mattermost.atlassian.net/browse/MM-13752)
This PR was tested on: [iPhone x simulator]

MM-13752 Thread view should not display new message indicator

---

package-lock.json
package.json

Update mattermost-redux version.

Update mattermost-redux version.

---

app/components/__snapshots__/badge.test.js.snap
app/components/badge.js
app/screens/channel/channel_nav_bar/channel_drawer_button.js

Fixes count alignment on channel drawer
[MM-13525](https://mattermost.atlassian.net/browse/MM-13525)
Emulators of ios / android mobiles and tablets

[MM-13525] Fix alignment of count on channel drawer

---

app/components/channel_link/channel_link.js
app/components/channel_link/channel_link.test.js
app/components/channel_link/index.js
app/components/markdown/markdown.js
app/components/post_body/post_body.js

Make channel link clickable and joinable for user who's not member of the public channel
Jira ticket: [MM-13295](https://mattermost.atlassian.net/browse/MM-13295)

[MM-13295] Make channel link clickable for user who's not member of the public channel

---

app/components/post_body_additional_content/post_body_additional_content.js
app/components/reactions/reactions.js

Fixes backwards compatibility with openGraph and reactions
https://mattermost.atlassian.net/browse/MM-14117

MM-14117 Fix opengraph and reactions for older servers

---

app/app.js

Not sure if this is a 1.17.0 or 1.18.0 fix, in case of 1.17 @DSchalla feel free to cherry-pick

Fix utils reference

---

package-lock.json
package.json

Updates the reference for mattermost-redux

Handle pending posts when dispatching RECEIVED_NEW_POST

---

.gitignore

Just adding the coverage directory to .gitignore!

Add coverage to .gitignore

---

app/screens/login/login.js

Fix error accessing `server_error_id` of undefined

Fix checkLoginResponse for MFA

---

package-lock.json
package.json

Fix undefined site URL when copying permalink at mattermost-redux - https://github.com/mattermost/mattermost-redux/commit/10c1e6c9200778c4d6d6ab3296be5f2b1e4fb084
Jira ticket - [MM-14315](https://mattermost.atlassian.net/browse/MM-14315)

[MM-14315] Fix undefined site URL when copying permalink

---

app/components/post_profile_picture/index.js

Show correct webhook profile picture on post icon override enabled
Jira ticket: [MM-14355](https://mattermost.atlassian.net/browse/MM-14355)

[MM-14355] Show correct webhook profile picture on post icon override enabled

---

README.md

The link pointed to the `server` issue tracker, `mobile` probably makes more sense in this case
n/a

Fix github issues link

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist

This is to bump the build number for the dot release.

Bump app build number to 179

---

android/app/src/main/AndroidManifest.xml

Changes comment format - somehow this was causing a gradle sync errror on AS 3.3.1/MacOS 10.14.3
n/a
n/a
Fixes gradle sync on on AS 3.3.1/MacOS 10.14.3

Change comment to more common xml format

---

app/constants/view.js
app/screens/login_options/login_options.js
app/screens/select_server/select_server.js
app/screens/sso/sso.js
assets/base/config.json
assets/base/i18n/en.json

Adding support to authenticate with Office 365 OAuth
https://mattermost.atlassian.net/browse/MM-13686

Add Office 365 login support

---

app/screens/settings/notification_settings_email/index.js
app/screens/settings/notification_settings_email/notification_settings_email_base.js
package-lock.json
package.json

Fix default behavior when enabling/disabling email batching
~~Note: Will ask release triage team if this will go through release-1.17.~~ 
Update: For release-1.17
Jira ticket: [MM-14527](https://mattermost.atlassian.net/browse/MM-14527)

[MM-14527] Fix default behavior when enabling/disabling email batching

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist

Bump build number
release build

Bump app build number to 180

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist

bump version 
cc @enahum jsut to be aware will merge when green

Bump app build number to 181

---

app/actions/views/channel.js
app/components/network_indicator/index.js
app/components/network_indicator/network_indicator.js
app/screens/channel_peek/channel_peek.js
app/screens/channel_peek/index.js
app/utils/push_notifications.js

When bringing the app from the background we do clear notifications that belong to that channel but we were not marking the channel as read.
https://mattermost.atlassian.net/browse/MM-14630

MM-14630 Mark channel as read and viewed when opening brought from bg

---

ios/Mattermost/AppDelegate.m
ios/UploadAttachments/UploadAttachments/StoreManager.m
ios/UploadAttachments/UploadAttachments/UploadSession.swift

Fixes the DM and GM list to show the same channels as the sidebar. Also fixes a race condition when posting a message from the share extension and adds some logs visible using the [Unified logging system](https://developer.apple.com/documentation/os/logging).
https://mattermost.atlassian.net/browse/MM-14629
https://mattermost.atlassian.net/browse/MM-14631

iOS Share Extension fix post and dm/gm list

---

app/utils/timezone.js
package-lock.json
package.json

Detect timezone updates on Android.
Note: The new detected timezone will be detected on the next app launch.
The actual fix is here https://github.com/enahum/react-native-device-info/commit/00c9ff7dc11e63b06e0624cc1c4b0cc2bc4e7a39
https://mattermost.atlassian.net/browse/MM-13795

MM-13795 Detect timezone updates on Android

---

package-lock.json
package.json

Following the ticket description I could not see anything really that stood up to identify why `this.getImageTransformer` is not a function so I went ahead and make the changes to the library to use arrow functions in the ES6 classes
https://mattermost.atlassian.net/browse/MM-14154

MM-14154 Update react-native-image-gallery

---

app/components/post_body/post_body.js
app/screens/post_options/__snapshots__/post_options.test.js.snap
app/screens/post_options/post_options.js
app/screens/post_options/post_options.test.js
package-lock.json

Fix showing of post option for system admin by passing `isSystemMessage` to `PostOptions` component
Jira ticket: [MM-14494](https://mattermost.atlassian.net/browse/MM-14494)

[MM-14494] Fix showing of post option for system admin

---

app/components/markdown/index.js
app/components/markdown/markdown.js

Support `MinimumHashtagLength` setting
Fixes https://github.com/mattermost/mattermost-server/issues/9156
https://mattermost.atlassian.net/browse/MM-4819
N/A
This PR was tested on: iOS 11.2, iPhone X simulator

Support MinimumHashtagLength setting

---

package-lock.json
package.json

updated mattermost-redux commit ID to use the latest changes
This PR was tested on: OnePlus 6

#MI-372 updated mattermost-redux commit ID to use the latest changes

---

README.md

Fix README.md iOS beta link

---

package-lock.json
package.json

The fix is in this [merged PR](https://github.com/mattermost/react-native-notifications/pull/4) of our react-native-notifications fork.
https://mattermost.atlassian.net/browse/MM-14830

[MM-14830] Check for null pushNotification prior to calling sendNotificationScheduled on it

---

CHANGELOG.md

Make it more obvious what action needs to be taken + some readability updates

Proposed changelog update regarding AppConfig compatability

---

fastlane/Fastfile

Add telemetry config for beta build
Jira ticket: [MM-15103](https://mattermost.atlassian.net/browse/MM-15103)
This PR was tested on: [Android and iOS (which is expected to not work and not have side-effect)]

[MM-15103] Add telemetry config for beta build

---

app/actions/views/channel.js
package-lock.json
package.json
share_extension/android/actions/index.js
share_extension/common/selectors/index.js

Change the concept of DEFAULT_CHANNEL to RedirectChannel
[MM-14639](https://mattermost.atlassian.net/browse/MM-14639)

Creating the concept of RedirectChannel and use it before the DefaultChannel when we are redirecting the user

---

Makefile
android/app/build.gradle
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
assets/base/i18n/en.json
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
native_modules/RNCookieManagerIOS.m
share_extension/android/extension_post/extension_post.js
share_extension/android/extension_post/index.js

This PR is for a dot release and includes:
* Bumping app build number to 187
* Bumping app version number to 1.18.1
* Fixes a crash on languages other than english cause by a malformed (non-updated) string that corresponds to the post textbox placeholder
* Fixes a crash on iOS when logging in using SSO and the provider sets some cookies without expiration date
Note: This PR should also be cherry-picked for 1.19.0 and when merging preserve the history of commits.
Fixes: #2723 
https://mattermost.atlassian.net/browse/MM-15215
https://mattermost.atlassian.net/browse/MM-15216

Fixes crashes for malformed localize string and no expiration date on cookies

---

app/actions/device/index.js
app/fetch_preconfig.js
app/mattermost.js
app/screens/select_server/select_server.js
package-lock.json
package.json

Remove Client4.online and related setOnline function.
Most of the change is on mattermost-redux - https://github.com/mattermost/mattermost-redux/pull/815, will update commit once it's merged.
Jira ticket: [MM-14619](https://mattermost.atlassian.net/browse/MM-14619)

[MM-14619] Remove Client4.online and related setOnline function

---

app/screens/post_options/post_options.js
app/screens/post_options/post_options.test.js

Remove post for user after user deletes it.
https://mattermost.atlassian.net/browse/MM-14777

[MM-14777] Remove post for user after user deletes it

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Use the sender name in the push notification when available instead of trying to guess it from the text of the notification
https://mattermost.atlassian.net/browse/MM-14885
This PR was tested on: Android 7, 8 and 9
Tested against the current push proxy and 2 server versions back as well as master and server https://github.com/mattermost/mattermost-server/pull/10736 with and without the changes in the push proxy for https://github.com/mattermost/mattermost-push-proxy/pull/49

MM-14885 Android use sender_name in push notifications

---

app/components/post_profile_picture/index.js
app/components/post_profile_picture/post_profile_picture.js

show bot icon for ephemeral posts
https://github.com/mattermost/mattermost-server/issues/10640
https://github.com/mattermost/mattermost-webapp/pull/2702
This PR was tested on: [iPhone X, 12.2 emulator]

MM-15161 show icon for bot instead of system icon in ephemeral post

---

CONTRIBUTING.md

Follow up on https://github.com/mattermost/mattermost-server/pull/10749

Remove outdated information from contributing file

---

app/components/network_indicator/network_indicator.js
app/components/post_list/post_list_base.js
app/components/safe_area_view/safe_area_view.ios.js
app/components/slide_up_panel/slide_up_panel.js
app/constants/device.js
app/mattermost_managed/mattermost-managed.ios.js
app/screens/post_options/__snapshots__/post_options.test.js.snap
ios/Mattermost/MattermostManaged.h
ios/Mattermost/MattermostManaged.m
test/setup.js

This PR fixes the layout for iPads that contain safeAreaInsets
https://mattermost.atlassian.net/browse/MM-14921

MM-14921 Fix iPad layout including safeAreaInsets

---

package-lock.json
package.json
share_extension/common/selectors/index.js

Update mattermost-redux and the usage of `completeDirectChannelDisplayName` from https://github.com/mattermost/mattermost-redux/pull/825.
https://mattermost.atlassian.net/browse/MM-15363

MM-15363 Update mattermost-redux

---

assets/base/i18n/es.json
assets/base/i18n/ja.json
assets/base/i18n/pt-BR.json
assets/base/i18n/tr.json

Ideally this PR should be review by community members for each language.
Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

translations PR 20190506

---

app/actions/views/channel.js
app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/at_mention_item/at_mention_item.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/channel_intro/channel_intro.js
app/components/combined_system_message/last_users.js
app/components/file_upload_preview/file_upload_preview.js
app/components/post_add_channel_member/post_add_channel_member.js
app/components/post_body/post_body.js
app/components/post_list/post_list.js
app/components/post_textbox/components/typing/typing.js
app/components/sidebars/main/channels_list/list/list.js
app/components/tooltip.js
app/fetch_preconfig.js
app/screens/image_preview/image_preview.js
app/screens/more_channels/more_channels.js
app/screens/options_modal/options_modal_list.android.js
app/screens/options_modal/options_modal_list.ios.js
app/screens/reaction_list/reaction_list.js
app/screens/select_team/select_team.js
app/screens/settings/general/settings.js
app/screens/settings/notification_settings_mentions/notification_settings_mention_base.js
app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js
app/screens/settings/notification_settings_mentions/notification_settings_mentions.ios.js
app/screens/thread/thread.js
app/screens/timezone/timezone.js
app/store/middleware.js
app/store/middleware.test.js

Crashes on Android have been reported due to .length being called on undefined. I've added checks / defaultProps anywhere I wasn't 100% sure could not be null. I didn't see any potential issues in mattermost-redux so no changes there this time.
https://mattermost.atlassian.net/browse/MM-15437

[MM-15437] Avoid possible reading of length property on undefined

---

fastlane/Fastfile

Updating the link to enroll in the iOS beta test program in the post created by the script

Update fastlane iOS beta tester link

---

package-lock.json
package.json

Update mattermost-redux reference
Note: If you cherry-pick this PR make sure to change the commit reference for mattermost-redux to point to the `release-5.11` branch

MM-15532 properly mark channel as read when reading the channel in another client

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-15518

MM-15518 Update rnfetchblob

---

android/app/build.gradle

Google play requires new apps to be submitted to include 64bit native code
https://mattermost.atlassian.net/browse/MM-15427

MM-15427 Google Play 64-bit requirement compliance

---

app/screens/channel/channel_post_list/channel_post_list.js
app/screens/post_options/index.js
app/screens/post_options/post_options.js
app/screens/post_options/post_options.test.js

Open the thread view by emitting an event so we can close the post menu.
https://mattermost.atlassian.net/browse/MM-15481

MM-15481 close post menu when replying to a message

---

app/components/post_textbox/post_textbox.js
app/constants/post_textbox.js

This PR allows the text box to use the auto layout so the placeholder is visible when it wraps.
https://mattermost.atlassian.net/browse/MM-15282

MM-15282 Fix cutoff placeholder on Android

---

app/screens/login/login.js
app/screens/login/login.test.js
test/setup.js

https://mattermost.atlassian.net/browse/MM-15582
iOS Simulator

MM-15582 Don't show forgot password link without email/username login

---

fastlane/Fastfile

Quick fix: link on Android beta signup message

Quick fix: link on Android beta signup message

---

package-lock.json
package.json

update mattermost-redux ref with https://github.com/mattermost/mattermost-redux/pull/839

MM-15667 if post was removed exclude it from postsInChannel

---

app/components/post_body/post_body.test.js

I did not read [Saturn's comment](https://github.com/mattermost/mattermost-mobile/pull/2829#issuecomment-495563365) closely enough so I missed adding this test in PR 2829.
https://mattermost.atlassian.net/browse/MM-15671

Add unit test for PostBody's measurePost

---

app/screens/login/login.js
app/screens/select_server/select_server.js
e2e/android/index.js
e2e/android/smoke.js
e2e/config.js
e2e/script/e2e_init.js
e2e/script/retry_exec.js
package-lock.json
package.json

This is the initial config for RN UI Automation - Appium for Android app.
How to run E2E test:
1. `make build-android` - build Android app and verify that the `Mattermost.apk` is available at root directory on successful build.
2. `npm run e2e:android` - npm script to run E2E for Android
Packages used:
- `appium@1.12.1`
- `wd@1.11.2`
- `tape@4.10.1`
- `tap-spec@5.0.0`
Jira ticket: [MM-15224](https://mattermost.atlassian.net/browse/MM-15224)
This PR was tested on: [Android]

MM-15224 Initial config for RN UI Automation - Appium for Android app

---

Makefile

Fix build for unsigned and ios-sim-x86_64.
Only release-1.20 is affected; master is not.
none

Quick fix: build for unsigned and ios-sim-x86_64

---

app/components/file_upload_preview/file_upload_item/file_upload_item.js

By removing the setState to set the percentage at 100 now the component updates accordingly
https://mattermost.atlassian.net/browse/MM-15912

MM-15912 Fix uploads stuck at 100%

---

android/app/google-services.json
android/app/src/main/AndroidManifest.xml

Without knowing we were allowing google to gather analytics data by not explicitly disabling the Firebase analytics module. This PR will disable this analytics entirely as requested here https://github.com/mattermost/mattermost-mobile/issues/566#issuecomment-497872076
https://mattermost.atlassian.net/browse/MM-15959

MM-15959 disable android firebase analytics

---

app/components/fade.js

Increase the speed of the animation of the paper plain when submitting a post
https://mattermost.atlassian.net/browse/MM-16013

MM-16013 make paperplain animation faster

---

fastlane/Fastfile

Little fix to make current version build
https://github.com/mattermost/mattermost-mobile/pull/2840

Fix build after #2840

---

app/actions/navigation.js
app/app.js
app/constants/view.js
app/mattermost.js
app/screens/entry/entry.js
app/screens/index.js
app/screens/login/index.js
app/screens/login/login.js
app/screens/login/login.test.js
app/screens/login_options/login_options.js
app/screens/select_server/index.js
app/screens/select_server/select_server.js

This lets you get up to the Channel screen in the app using the new API
https://mattermost.atlassian.net/browse/MM-16011
This PR was tested on: iOS Simulator (iPhone X)

MM-16011 Update navigation through Login and Channel screens

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

https://mattermost.atlassian.net/browse/MM-16281
This PR was tested on: Android Oreo and Pie emulators with server versions 5.12 and 5.11

MM-16281 Fix regression on android push notification messages

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-16280
- Has server changes (please link here)
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/851)
- Has mobile changes (please link here)

MM-16280 Fix when post fail to send

---

package-lock.json
package.json

The check for null on notification object was added to our react-native-notifications fork.
https://mattermost.atlassian.net/browse/MM-15899

[MM-15899] Update react-native-notifications

---

README.md

Update Github issue link where the current link will show empty issues
N/A
N/A
N/A
N/A

Update Github issues link

---

app/screens/channel_members/channel_members.js

https://mattermost.atlassian.net/browse/MM-16472

MM-16472 Fix renderItem not returning anything

---

app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
app/components/post_textbox/post_textbox.test.js
app/components/post_textbox/post_textbox_base.js

Saving the draft when the app state changes, this will allow the user to close the app without having to start composing the message again
https://mattermost.atlassian.net/browse/MM-16397

MM-16397 save draft when app state changes

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-16480
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/862)
- Has web changes (https://github.com/mattermost/mattermost-webapp/pull/3010)

MM-16480 Update mattermost-redux

---

Makefile
package.json

Revert change to use RNN v2's npm script
https://mattermost.atlassian.net/browse/MM-15994

[MM-15994] Revert change to use RNN v2's npm script

---

android/app/src/main/java/com/mattermost/rnbeta/InitializationModule.java
android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
app/mattermost.js
app/push_notifications/push_notifications.android.js

Fixes replying from the push notification to a message that belongs to a thread.
Also removes unused code from the previous implementation that used HeadlessJS
https://mattermost.atlassian.net/browse/MM-16463

MM-16463 Fix replying from push notification to a message in a thread

---

ios/UploadAttachments/UploadAttachments/MattermostBucket.m
ios/UploadAttachments/UploadAttachments/UploadSession.swift

Don't proceed in notificationReceipt if entities is nil.
https://mattermost.atlassian.net/browse/MM-16602

[MM-16602] Don't proceed in notificationReceipt if entities is nil.

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick for 1.21 and 1.20 release branches

Bump app build number to 204

---

package-lock.json
package.json

https://mattermost.atlassian.net/browse/MM-16695
- https://github.com/mattermost/mattermost-redux/pull/874

MM-16695 Update mattermost-redux to add additional null check

---

android/app/build.gradle
android/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Also updates the targetSdkVersion to 28 as required by Android

 Bump app build number to 206

---

assets/base/i18n/zh-TW.json

Ideally this PR should be review by community members for each language.
Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

translations PR 20190708

---

app/screens/channel_info/index.js
package-lock.json
package.json

I forgot to add the "Do not merge" label to [PR-2980](https://github.com/mattermost/mattermost-mobile/pull/2980) until I had updated the mattermost-redux commit so this PR is for the mattermost-redux update.
https://mattermost.atlassian.net/browse/MM-17018

[MM-17018] Handle null currentChannelMember

---

app/components/post_profile_picture/index.js
app/components/post_profile_picture/post_profile_picture.js
app/constants/view.js
app/screens/notification/notification.js

Cherry pick of #2961 on release-1.22.
- #2961: Enable emojis for profile icons from webhooks
/cc  @krjn

Automated cherry pick of #2961

---

app/screens/select_server/select_server.js

Cherry pick of #2984 on release-1.22.
- #2984: Select server fix login options transition
/cc  @enahum

Automated cherry pick of #2984

---

app/components/network_indicator/index.js
app/components/network_indicator/network_indicator.js

Cherry pick of #2983 on release-1.22.
- #2983: MM-16815 Remove the failed posts banner on WS reconnect
/cc  @enahum

Automated cherry pick of #2983

---

app/screens/sso/sso.js

Cherry pick of #2987 on release-1.21.
- #2987: MM-16829 Fix for sso with server subpaths

Automated cherry pick of #2987

---

app/screens/options_modal/options_modal.js

Cherry pick of #2993 on release-1.22.
- #2993: Fix Options modal on iOS
/cc  @enahum

Automated cherry pick of #2993

---

app/components/sidebars/main/__snapshots__/main_sidebar.test.js.snap
app/components/sidebars/main/main_sidebar.js
app/components/sidebars/main/main_sidebar.test.js

Cherry pick of #3002 on release-1.22.
- #3002: Set footerColor the same as navBarBackgroundColor
/cc  @migbot

Automated cherry pick of #3002

---

android/app/build.gradle
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist
package.json

Bump app version number to 1.22.0

---

android/app/build.gradle
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist
package.json

Cherry pick of #3009 on release-1.22.
- #3009: Bump app version number to 1.22.0

Automated cherry pick of #3009

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 211

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3012 on release-1.22.
- #3012: Bump app build number to 211

Automated cherry pick of #3012

---

app/push_notifications/push_notifications.ios.js
app/utils/push_notifications.js
app/utils/push_notifications.test.js

Cherry pick of #3014 on release-1.22.
- #3014: Add channel_id to failed push notification reply
/cc  @migbot

Automated cherry pick of #3014

---

app/actions/views/channel.js

Fixing guest login

---

app/actions/views/channel.js

Cherry pick of #3019 on release-1.22.
- #3019: Fixing guest login
/cc  @jespino

Automated cherry pick of #3019

---

app/screens/user_profile/index.js
app/screens/user_profile/user_profile.js
app/screens/user_profile/user_profile.test.js

Cherry pick of #3016 on release-1.22.
- #3016: User popToRoot over resetToChannel
/cc  @migbot

Automated cherry pick of #3016

---

app/actions/navigation.js
app/mattermost.js
app/screens/theme/index.js
app/screens/theme/theme.js
app/screens/theme/theme.test.js
app/store/ephemeral_store.js

Call `mergeOptions` for each component that has previously appeared to apply the new theme.
https://mattermost.atlassian.net/browse/MM-17015
* iPhone X simulator, iOS 12.2
* Android emulator, Android 9.0

[MM-17015] Apply changed theme to all navigation components

---

app/actions/navigation.js
app/mattermost.js
app/screens/theme/index.js
app/screens/theme/theme.js
app/screens/theme/theme.test.js
app/store/ephemeral_store.js

Cherry pick of #3005 on release-1.22.
- #3005: Apply new theme to all navigation components
/cc  @migbot

Automated cherry pick of #3005

---

app/push_notifications/push_notifications.ios.js
app/push_notifications/push_notifications.ios.test.js
package-lock.json
package.json
test/setup.js

Cherry pick of #3001 on release-1.22.
- #3001: Include in-app notifications in iOS badge number
/cc  @migbot

Automated cherry pick of #3001

---

app/components/post_list/post_list.js

Cherry pick of #3025 on release-1.22.
- #3025: Check initialIndex in callback
/cc  @migbot

Automated cherry pick of #3025

---

fastlane/Fastfile

The old image 404'ed.
https://mattermost.atlassian.net/browse/MM-17120

MM-17120 Update fastlane image to a working one

---

fastlane/Fastfile

Cherry pick of #3044 on release-1.22.
- #3044: MM-17120 Update fastlane image to a working one
/cc  @jwilander

Automated cherry pick of #3044

---

app/utils/security.js

Cherry pick of #3035 on release-1.22.
- #3035: MM-17100 setCSRFFromCookie with subpath support
/cc  @enahum

MM-17100 setCSRFFromCookie with subpath support Automated cherry pick of #3035

---

app/push_notifications/push_notifications.ios.test.js

Cherry pick of #3051 on release-1.22.
- #3051: Fix test
/cc  @migbot

Automated cherry pick of #3051

---

ios/UploadAttachments/UploadAttachments/UploadSession.swift

Cherry pick of #3046 on release-1.22.
- #3046: Check if ackId is nil first
/cc  @migbot

Automated cherry pick of #3046

---

android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java

When migrating Android to use lazy load native modules we included WebView, but the WebView also needs a View Manager
https://mattermost.atlassian.net/browse/MM-17356

Load Android WebView package instead of module

---

android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java

Cherry pick of #3053 on release-1.22.
- #3053: Load Android WebView package instead of module
/cc  @enahum

Automated cherry pick of #3053

---

fastlane/Fastfile

Send message to Mattermost on iOS VM/simulator build.  This PR is in reference to iOS build for Rainforest QA testing.
Related PRs on private ~~and shared-pipelines were~~ was submitted.
Update: This is okay to review/merge while figuring out how to make auto build across three types: prod, beta and iOS simulator. 
Jira ticket: [MM-15969](https://mattermost.atlassian.net/browse/MM-15969)
This PR was tested on: [iOS build]

MM-15969 Send message to Mattermost on iOS VM/simulator build

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3063 on release-1.22.
- #3063: Bump app build number to 214
/cc  @enahum

Automated cherry pick of #3063

---

package-lock.json
package.json

See https://github.com/mattermost/mattermost-redux/pull/888
https://mattermost.atlassian.net/browse/MM-14697

[MM-14697] Include archived teams filter change from mattermost-redux

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 216

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3068 on release-1.22.
- #3068: Bump app build number to 216

Automated cherry pick of #3068

---

NOTICE.txt

Cherry pick of #3075 on release-1.22.
- #3075: Update NOTICE.txt
/cc  @amyblais

Automated cherry pick of #3075

---

package-lock.json
package.json

Updates the `commonmark` dependency
Fixes https://github.com/mattermost/mattermost-server/issues/10774

[MM-13837] Updated Commonmark dependency

---

README.md

Please make sure you've read the [pull request](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) section of our [code contribution guidelines](https://developers.mattermost.com/contribute/getting-started/).

Add details on leaving the beta program

---

app/screens/settings/theme/theme_tile.js

Cherry pick of #3080 on release-1.22.
- #3080: Fix theme thumbnail width
/cc  @migbot

Automated cherry pick of #3080

---

app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
app/utils/markdown.js

Cherry pick of #3079 on release-1.22.
- #3079: Remove flex for horizontalRule
/cc  @migbot

Automated cherry pick of #3079

---

app/components/post_list/post_list.js

Cherry pick of #3074 on release-1.22.
- #3074: MM-17562 scroll to new message line indicator on
/cc  @enahum

Automated cherry pick of #3074

---

app/screens/interactive_dialog/interactive_dialog.js
app/screens/interactive_dialog/interactive_dialog.test.js

Cherry pick of #3048 on release-1.22.
- #3048: MM-15218 allow interactive dialogs to have no elements
/cc  @janvt

Automated cherry pick of #3048

---

app/components/post_header/post_header.js

Cherry pick of #3086 on release-1.22.
- #3086: Increase ReplyIcon dimensions
/cc  @migbot

Automated cherry pick of #3086

---

app/actions/navigation.js
app/screens/thread/thread_base.js

Cherry pick of #3092 on release-1.22.
- #3092: Fix pop thread screen when deleting the root post
/cc  @enahum

Automated cherry pick of #3092

---

app/components/network_indicator/network_indicator.js

The periodic status updates was first initialize when connecting the WS for the first time but was not being triggered on reconnect. Also the `stopPeriodicStatusUpdates` was being called on every reconnect attempt as well as `closeWebSocket`. Both issues are addressed.
https://mattermost.atlassian.net/browse/MM-17612

MM-17612 Fix fetch periodic status updates when re-connecting

---

app/components/network_indicator/network_indicator.js

Cherry pick of #3089 on release-1.22.
- #3089: MM-17612 Fix fetch periodic status updates when re-connecting
/cc  @enahum

Automated cherry pick of #3089

---

app/screens/channel/channel_base.js

Cherry pick of #3098 on release-1.22.
- #3098: MM-17630 add Navigation bar to terms of service modal
/cc  @enahum

Automated cherry pick of #3098

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 217

---

app/components/text_input_with_localized_placeholder.js
app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.test.js

Cherry pick of #3087 on release-1.22.
- #3087: Add flex 1
/cc  @migbot

Automated cherry pick of #3087

---

app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
app/screens/channel_info/channel_info_header.js
app/screens/channel_info/channel_info_header.test.js

Aligning correctly 'has guests' warning in channel info screen
[MM-17205](https://mattermost.atlassian.net/browse/MM-17205)
This PR was tested on: [Android emulator]

Aligning correctly 'has guests' warning in channel info screen

---

app/components/slide_up_panel/slide_up_panel.js
app/screens/post_options/post_options.js
app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.test.js

Cherry pick of #3107 on release-1.22.
- #3107: MM-17692 execute callback after closing post options
/cc  @enahum

Automated cherry pick of #3107

---

app/actions/navigation.js
app/screens/settings/advanced_settings/advanced_settings.js
app/screens/settings/advanced_settings/index.js
app/screens/settings/general/settings.js
app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap

Cherry pick of #3108 on release-1.22.
- #3108: MM-17693 Android fix close settings screen
/cc  @enahum

Automated cherry pick of #3108

---

app/components/markdown/markdown_image/markdown_image.js
app/init/credentials.js
app/store/ephemeral_store.js

Await getSource.
https://mattermost.atlassian.net/browse/MM-17709
* iPhone 8, iOS 12.3.1

[MM-17709] Avoid async getSource

---

app/components/markdown/markdown_image/markdown_image.js
app/init/credentials.js
app/store/ephemeral_store.js

Cherry pick of #3115 on release-1.22.
- #3115: Await getSource
/cc  @migbot

Automated cherry pick of #3115

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 218

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3118 on release-1.22.
- #3118: Bump app build number to 218

Automated cherry pick of #3118

---

app/screens/post_options/post_options.js
app/screens/post_options/post_options.test.js

Cherry pick of #3116 on release-1.22.
- #3116: Fix delete the root post on a thread to properly close
/cc  @enahum

Automated cherry pick of #3116

---

app/actions/navigation.js
app/screens/settings/display_settings/display_settings.js
app/screens/settings/display_settings/display_settings.test.js
app/screens/settings/display_settings/index.js
app/screens/settings/general/index.js
app/screens/settings/general/settings.js
app/screens/settings/theme/theme.js
app/screens/settings/theme/theme.test.js
app/store/ephemeral_store.js
app/utils/theme.js

Cherry pick of #3121 on release-1.22.
- #3121: Apply setNavigatorStyles to all navigation components
/cc  @migbot

Automated cherry pick of #3121

---

app/screens/create_channel/create_channel.js
app/screens/more_channels/more_channels.js
app/screens/more_channels/more_channels.test.js
app/screens/more_dms/more_dms.js

Cherry pick of #3123 on release-1.22.
- #3123: Set header buttons after mount
/cc  @migbot

Automated cherry pick of #3123

---

app/actions/views/select_server.js
app/init/emm_provider.js

Cherry pick of #3125 on release-1.22.
- #3125: Fix loosing the server config when handleManagedConfig
/cc  @enahum

Automated cherry pick of #3125

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 219

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3129 on release-1.22.
- #3129: Bump app build number to 219

Automated cherry pick of #3129

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 220

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3132 on release-1.22.
- #3132: Bump app build number to 220

Automated cherry pick of #3132

---

app/screens/channel_info/channel_info.js

Cherry pick of #3139 on release-1.22.
- #3139: Fix regression close/leave/archive channel redirect to
/cc  @enahum

Automated cherry pick of #3139

---

app/screens/create_channel/create_channel.js
app/screens/edit_channel/edit_channel.js
app/screens/edit_post/edit_post.js
app/screens/edit_profile/edit_profile.js
app/screens/terms_of_service/terms_of_service.js
app/screens/user_profile/user_profile.js

Cherry pick of #3138 on release-1.22.
- #3138: Fix Regression right buttons color on Android navbar when
/cc  @enahum

Automated cherry pick of #3138

---

app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js

Fix navigation button colors on Android
https://mattermost.atlassian.net/browse/MM-17884

Android screen right button colors

---

app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js

Cherry pick of #3146 on release-1.23.
- #3146: Android screen right button colors
/cc  @enahum

Automated cherry pick of #3146

---

app/components/bot_tag.js

MM-17700 - Updating bot tag css
https://mattermost.atlassian.net/browse/MM-17700
**Screens:**

MM-17700 - Updating bot tag css

---

app/components/bot_tag.js

Cherry pick of #3127 on release-1.23.
- #3127: MM-17700 - Updating bot tag css
/cc  @asaadmahmood

Automated cherry pick of #3127

---

android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java

Cherry pick of #3152 on release-1.23.
- #3152: Check for valid server URL
/cc  @migbot

Automated cherry pick of #3152

---

app/i18n/index.js

Cherry pick of #3155 on release-1.23.
- #3155: update moment locale as lowercase
/cc  @enahum

Automated cherry pick of #3155

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist
package.json

Cherry pick of #3160 on release-1.23.
- #3160: Bump app build number to 222
/cc  @enahum

Automated cherry pick of #3160

---

app/screens/image_preview/downloader.ios.js

Cherry pick of #3164 on release-1.23.
- #3164: MM-17886 Do not wait to cancel the video download
/cc  @enahum

Automated cherry pick of #3164

---

app/init/emm_provider.js
app/mattermost_managed/mattermost-managed.android.js
app/mattermost_managed/mattermost-managed.ios.js
assets/base/i18n/en.json
ios/Mattermost/MattermostManaged.m
ios/MattermostShare/ShareViewController.swift

Cherry pick of #3137 on release-1.23.
- #3137: MM-17589 Update passcode required help text in share
/cc  @hmhealey

Automated cherry pick of #3137

---

app/utils/sentry/index.js
package-lock.json
package.json

Cherry pick of #3179 on release-1.23.
- #3179: Update sentry
/cc  @enahum

Automated cherry pick of #3179

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3181 on release-1.23.
- #3181: Bump app build number to 224
/cc  @enahum

Automated cherry pick of #3181

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3186 on release-1.22.
- #3186: Bump app build number to 225
/cc  @enahum

Automated cherry pick of #3186

---

app/screens/select_server/select_server.js
e2e/package-lock.json
e2e/package.json
e2e/test/configs/android.conf.js
e2e/test/specs/smoke.test.js

- Fixd failing E2E for Android
- Updated dependencies
- Added `appium` as dependency (and not rely on global installation)
Jira ticket: [MM-18120](https://mattermost.atlassian.net/browse/MM-18120)

MM-18120 Fix failing E2E for Android

---

app/components/search_bar/search_box.js
app/components/sidebars/main/channels_list/channels_list.js

Cherry pick of #3203 on release-1.23.
- #3203: Increase cancel button width
/cc  @migbot

Automated cherry pick of #3203

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 228

---

app/components/post_textbox/post_textbox_base.js

MM-17966 - Updating background for archive wrapper
https://mattermost.atlassian.net/browse/MM-17966
Iphone X 12.4

MM-17966 - Updating background for archive wrapper

---

Makefile
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
android/settings.gradle
app/components/post/post.js
app/components/reactions/reaction.js
app/components/slide_up_panel/slide_up_panel.js
app/screens/post_options/post_options.js
app/utils/general.js
ios/Mattermost.xcodeproj/project.pbxproj
native_modules/react-native-haptic-feedback+1.8.2.patch
package-lock.json
package.json
test/setup.js

This PR reduces the delay to open the post options menu as well as improve the speed and type of animation and adds haptic feedback on open.
https://mattermost.atlassian.net/browse/MM-18349
This PR was tested on: Multiple physical devices for iOS and Android

[MM-18349] Post menu delay animation speed and haptic feedback

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 229

---

app/utils/image_cache_manager.js

Cherry pick of #3231 on release-1.23.
- #3231: Removing caching of failed image loading attempts

Automated cherry pick of #3231

---

app/components/combined_system_message/combined_system_message.js

Cherry pick of #3219 on release-1.23.
- #3219: Replicated missing user functionality for system

Automated cherry pick of #3219

---

app/screens/sso/sso.js
ios/Mattermost.xcodeproj/project.pbxproj
package-lock.json
package.json

Cherry pick of #3233 on release-1.23.
- #3233: Update webview library to remove deprecated API
/cc  @enahum

Automated cherry pick of #3233

---

android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
app/init/emm_provider.js

Cherry pick of #3242 on release-1.23.
- #3242: MM-18465 Add proper flags when opening settings
/cc  @hmhealey

Automated cherry pick of #3242

---

app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
app/components/emoji_picker/emoji_picker.android.js
app/components/emoji_picker/emoji_picker.ios.js
app/components/emoji_picker/emoji_picker.test.js
app/components/emoji_picker/emoji_picker_base.js
app/components/safe_area_view/safe_area_view.ios.js
package-lock.json
package.json

Fixes the emoji picker where the last two lines couldn't be selected as the layout was preventing it.
Also added keyboard tracking view to the emoji picker when using the search option.
https://mattermost.atlassian.net/browse/MM-18241

MM-18241 Fix emoji picker selection and added keyboard tracking on iOS

---

app/actions/views/login.js
app/utils/push_notifications.js
assets/base/i18n/en.json

Needs dev changes to inject the site_name and the number of days to expiry

Update session expiry push notification text

---

app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
app/components/sidebars/main/channels_list/channel_item/channel_item.js
app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
app/components/sidebars/main/channels_list/channel_item/index.js
app/selectors/autocomplete.js

Only show users in the autocomplete that are active
Server PR: https://github.com/mattermost/mattermost-server/pull/12178
https://mattermost.atlassian.net/browse/MM-17953

MM-17953 Do not show deactivated users in autocomplete

---

app/components/sidebars/main/drawer_swipper/drawer_swiper.js
app/components/sidebars/main/main_sidebar.js
app/components/swiper.js

Cherry pick of #3266 on release-1.24.
- #3266: Force drawer to open to channel menu when new

Automated cherry pick of #3266

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 231

---

ios/Mattermost/Info.plist

Cherry pick of #3275 on release-1.24.
- #3275: Updated Info.plist with new bluetooth usage description key

Automated cherry pick of #3275

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 232

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3277 on release-1.24.
- #3277: Bump app build number to 232

Automated cherry pick of #3277

---

app/components/post_list/post_list.js
app/components/post_list/post_list.test.js

Reverts mattermost/mattermost-mobile#3282

Revert "[MM-17001] Call scrollToIndex only when ref is set and index is in range"

---

app/components/post_list/post_list.js
app/components/post_list/post_list.test.js

Cherry pick of #3285 on release-1.24.
- #3285: Call scrollToIndex only when ref is set and index is in range
/cc  @migbot

Automated cherry pick of #3285

---

app/components/autocomplete/autocomplete.js
app/components/client_upgrade_listener/client_upgrade_listener.js
app/components/emoji_picker/emoji_picker.ios.js
app/components/emoji_picker/emoji_picker_base.js
app/components/network_indicator/network_indicator.js
app/components/safe_area_view/iphone_x_spacing/index.js
app/components/safe_area_view/safe_area_view.ios.js
app/components/sidebars/main/channels_list/list/list.js
app/components/sidebars/main/main_sidebar.js
app/components/sidebars/main/teams_list/teams_list.js
app/components/slide_up_panel/slide_up_panel.js
app/components/start/empty_toolbar.js
app/components/swiper.js
app/constants/device.js
app/screens/channel/channel.ios.js
app/screens/channel/channel_nav_bar/channel_nav_bar.js
app/screens/image_preview/image_preview.js
app/screens/search/search.js
package.json

Cherry pick of #3296 on release-1.24.
- #3296: MM-18752 Rename constant to handle iPhone X and new iPhone 11
/cc  @enahum

Automated cherry pick of #3296

---

app/screens/channel_info/channel_info_row.js

https://mattermost.atlassian.net/browse/MM-18758

MM-18758 Fix channel info row to be toggleable or with an chevron

---

app/screens/channel_info/channel_info_row.js

Cherry pick of #3297 on release-1.24.
- #3297: MM-18758 Fix channel info row to be toggleable or with an
/cc  @enahum

Automated cherry pick of #3297

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Bump app build number to 233

---

android/app/build.gradle
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
ios/NotificationService/Info.plist

Cherry pick of #3307 on release-1.24.
- #3307: Bump app build number to 233

Automated cherry pick of #3307

---

app/components/post_body/index.js
app/components/post_body/index.test.js

Cherry pick of #3289 on release-1.24.
- #3289: Properly determine if channel is archived
/cc  @migbot

Automated cherry pick of #3289

---

.circleci/config.yml

Cherry pick of #3312 on release-1.24.
- #3312: add circleci
/cc  @cpanato

Automated cherry pick of #3312

---

app/components/post_list/post_list.js
app/components/post_list/post_list.test.js

Cherry pick of #3309 on release-1.24.
- #3309: Null check on current
/cc  @migbot

Automated cherry pick of #3309

---

app/i18n/index.js
app/init/global_event_handler.js
app/init/global_event_handler.test.js
app/selectors/i18n.js

Cherry pick of #3310 on release-1.24.
- #3310: Reset moment local on logout
/cc  @migbot

Automated cherry pick of #3310
