src/actions/login.js
src/components/login.js
src/components/select_server_view.js
src/constants/index.js
src/constants/login.js
src/reducers/index.js
src/reducers/login.js
src/routes.js

For the `status` key in the `login` store, it doesn't make as much sense to use `'not fetched'|'fetching'|'fetched'`. What do you think of `'not done'|'doing'|'done'`? Perhaps we could use that in all of our stores. It seems semantic for all async actions that could succeed or fail, regardless of whether or not they actually "fetch" something (e.g. accessing local storage or a device api).

User can login to their server

---

src/actions/channels.js
src/actions/teams.js
src/components/channels_list.js
src/components/posts_list.js
src/reducers/channels.js
src/reducers/posts.js
src/reducers/teams.js

Until we are ready to handle request status in a separate store, I don't think it makes sense to singularize these collection stores (so `state.entities.teams.data` would become `state.entities.team.teams`), because inside of the components it would be confusing to see `state.team.status`. This is a step towards the intended store.

Convert entity collection stores to objects instead of arrays

---

.gitignore

`.npminstall` is a lockfile created by make. It's gitignored in the platform repo so we should gitignore it here.

Gitignore .npminstall

---

Makefile
package.json
src/i18n/i18n.js

@dmeza Do you mind pulling this branch and confirming that it works for you? I've only got an iOS environment set up and it has `Intl` predefined in it.

Added Intl polyfill for platforms that don't support it

---

src/actions/channels.js
src/actions/users.js
src/reducers/entities/helpers.js
src/reducers/entities/users.js
test/actions/channels.test.js
test/actions/users.test.js

This also fixes the `profilesInTeam`, `profilesInChannel` and `profilesNotInChannel` where the key containing either the teamId or the channelId were missing

Remove pagination for profiles in the store

---

service/actions/posts.js
service/reducers/entities/posts.js
service/store/configureStore.dev.js
service/utils/deepFreezeAndThrowOnMutation.js
test/service/actions/posts.test.js

This will catch and prevent most cases where we mutate the store. It unfortunately fails silently in a few cases (like `Reflect.deleteProperty`), but it'll at least fail if we do anything sketchy

Added deep freeze of stores in dev mode

---

service/client/client.js

Thomas, on you previous PR to use the parsed Headers we weren't using them in the login function thus the token was never set.

Fix login to use the parsed headers

---

service/actions/channels.js
service/actions/websocket.js
service/client/client.js
service/reducers/entities/channels.js
test/service/actions/channels.test.js
test/service/actions/websocket.test.js

This gets rid of the `lastViewedAt` and uses the new `viewChannel` api

Use the new API for view channel

---

app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/channel_list.js
package.json
service/reducers/entities/teams.js
service/selectors/entities/channels.js
service/utils/channel_utils.js

Fix channel selection when switching teams by instantiating a new DataSource if the currentChannel changes, if we don't do that then the rendering of the channels will happen before getting the new currentChannel and will fail to select the current ones.
Also added `deepEqual` to be able to compare the objects and prevent the component to be rendered multiple times without the need to, there are a few components that implement PureComponent which only checks for shallow equality and should compare more deeply, maybe we should take another look at those.
Also fixed another bug when the data return for teamMembers was an empty array.
Finally changed the way we were cloning an object in the channel utils

Fix channel selection when switching teams

---

service/actions/channels.js
service/actions/websocket.js
service/constants/channels.js
service/constants/constants.js
service/reducers/entities/channels.js
test/service/actions/channels.test.js

When the channel header or purpose is added/edited on another client a post gets made but if you are viewing that same channel the header and purpose do not update on the store, this will handle that scenario

Update channel header/purpose when current channel

---

android/app/build.gradle
fastlane/Fastfile

This will allow any dev to build the apk in debug mode without complaining that the ENV does not have the keystore registered

Fix gradle to build without Mattermost keys as dev

---

Makefile
service/store/configureStore.prod.js

So thanks to @jarredwitt now we can build in release mode without the need to hack the Makefile by having to always build in dev mode.
It seems that somehow the `combineReducers` in the production store was making the reducers not to be called after a dispatch, Jarred hunt it down and by doing an Object.assign fixes the issue.

Fix build in release mode

---

app/scenes/channel_info/channel_info.js
app/scenes/channel_info/channel_info_container.js
app/scenes/channel_info/channel_info_row.js

This pull request enables a user to toggle favoriting a channel from the channel_info view.
https://github.com/mattermost/mattermost-mobile/issues/197

Channel info favorite

---

Makefile
README.md
package.json

When running the app with `$ make run`, `$ make run-ios` or `$ make run-android` will start the react-native packager with the `--reset-cache` flag and that will transform the whole javascript code the first time avoiding the behavior seen in #191.
To stop the react-native packager just run `$ make stop`
#201

Reset cache when starting the app with make run

---

app/components/channel_list/channel_list.js
app/components/channel_list/channel_list_container.js
app/scenes/channel_drawer/channel_drawer_container.js
service/actions/channels.js
service/actions/general.js
service/actions/websocket.js
service/constants/constants.js
service/constants/websocket.js
test/service/actions/channels.test.js
test/service/actions/websocket.test.js

This PR get's rid of the `CHANNEL_VIEWED` WebSocket event and handles marking and unmarking the unread channels client side to match the webapp in to be performance compliant.
Additionally enabled the test for the `DIRECT_ADDED` WebSocket event as it was fixed on `platform`
https://mattermost.atlassian.net/browse/PLT-5486

PLT-5486 Removed channel_viewed websocket event

---

app/components/post_list/date_header.js
test/service/actions/websocket.test.js

This PR makes the date separator in the post list to match the one using in the web app
format `DDD, MMM DD, YYYY` 

PostList date separator to match webapp

---

app/scenes/more_dms/more_dms.js

This PR changes the way the profiles are fetched, before it was using the page number instead of the number of profiles as the offset

Fix fetch offset for more dms

---

app/components/channel_list/channel_list.js
app/components/channel_list/unread_indicator.js

The unread indicators had a fixed width of 250 causing it not to show properly on smaller screen sizes, this PR makes the indicators width dynamic
https://mattermost.atlassian.net/browse/PLT-5545

PLT-5545 Fix Unread above/below indicator size to fit on screen

---

service/actions/websocket.js
service/client/websocket_client.js

If the session has expired now the WebSocket stop trying to reconnect
https://mattermost.atlassian.net/browse/PLT-5543

PLT-5543 Fix WebSocket keeps trying to reconnect

---

app/actions/views/channel.js
service/reducers/entities/posts.js

When a channel has <60 posts, the first page of posts will be loaded. Otherwise, all posts since the last one will be loaded.
This is waiting on https://github.com/mattermost/platform/pull/5440

Improved how posts are loaded when switching to a channel

---

app/components/badge.js
app/scenes/channel/channel_drawer_button.js
service/selectors/entities/channels.js

This PR adds an indicator on the button to open the channel drawer if there are unread messages with a blank jewel or with a number containing the mentions count
https://mattermost.atlassian.net/browse/PLT-5488

PLT-5488 Add an Unread indicator on the button to open the channel drawer

---

app/components/post/post.js
app/components/post_list/date_header.js
app/components/post_list/new_messages_divider.js
app/components/post_list/post_list.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel/channel_post_list/channel_post_list_container.js
service/constants/constants.js
service/utils/post_utils.js

When they are new/unread messages in the posts list of the channel view, indicate where they start with a separator.
https://mattermost.atlassian.net/browse/PLT-5499
via @thomchop

PLT-5499 Indicate start of new messages in posts list

---

app/components/profile_picture/profile_picture.js
app/components/profile_picture/profile_picture_container.js
service/actions/helpers.js
service/actions/users.js

This PR fixes the issue where a blank status would be rendered if the status was undefined. It adds a debounced method that gathers user id's with an unknown status. The debounced method than gets the statuses after an idle period. 

Status indicator fix

---

app/components/custom_list/member_list_row.js
app/scenes/channel_members/channel_members.js
app/scenes/channel_members/channel_members_container.js

This PR removes the ability to remove yourself from the channel info manage members screen.
Submitted on behalf of @jarredwitt

Manage members fix

---

app/components/channel_drawer_list/channel_drawer_list.js
app/components/post_list/date_header.js
app/components/post_list/new_messages_divider.js
app/components/post_list/post_list.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel/channel_post_list/channel_post_list_container.js
app/scenes/channel_drawer/channel_drawer.js
service/utils/post_utils.js

This fixes several issues with the logic for the new messages divider:
* The divider would be displayed when you sent a message in a channel that didn't have any unread messages.
* The divider was not being displayed when you switch to an channel with unread messages. It would only appear once someone sent a message in that channel.
* The divider was being displayed above the last read message instead of below it.
https://mattermost.atlassian.net/browse/PLT-5605
via @thomchop

PLT-5605 Fix logic for indicating start of new messages

---

app/scenes/login/login.js
app/scenes/mfa/mfa.js
app/scenes/select_server/select_server.js

By wrapping the `Text` components in a `View` we make sure that the animation is constant for all the subcomponents when using `KeyboardAvoidingView`, this will fix the same issue for the **Select Server**, **Login** and **MFA** scenes
https://mattermost.atlassian.net/browse/PLT-5609

PLT-5609 Fix different speed for text animation

---

app/components/autocomplete/at_mention/at_mention.js

This PR modifies the mention regex to include non word characters when filtering for users.
https://mattermost.atlassian.net/browse/PLT-5601
@jarredwitt

PLT-5601 RN: autocompleting stopped when non-word chars are typed, even if there's an exact match

---

app/scenes/navigationSceneConnect.js
app/styles/index.js

In PLT-5609 (#290) we wrapped the header text in the logic scenes (select server, login, & MFA)  in a `View`. This made the text left-aligned because we had been centering the text with flex instead of `textAlign`. Now the text is centered again. Everywhere we are using `GlobalStyles.header` should've been center-aligned anyway.
Also the title text in the topbar was not being properly centered, but it was only apparent when the scene title wrapped onto a second line, like in the MFA scene. Now it is centered too.
https://mattermost.atlassian.net/browse/PLT-5644
@thomchop

PLT-5644 Center align login header text and topbar title text

---

app/scenes/login/login.js
service/client/client.js

When a user attempted to login with an unrecognized email address or an incorrect password, we were displaying the error message that's returned from the server, but in the webapp we instead display a corresponding error message from `webapp/i18n.json`. Now we are displaying the same messages here.
https://mattermost.atlassian.net/browse/PLT-5610
@thomchop

PLT-5610 Localize login error message to match what's displayed in webapp

---

app/navigation/routes.js
app/scenes/thread/thread.js
app/scenes/thread/thread_title.js
assets/base/i18n/en.json

This PR adds the channel name to the title of the thread to let the user know which channel the thread is part of
https://mattermost.atlassian.net/browse/PLT-5611

PLT-5611 Add Channel Name to thread view title

---

app/actions/navigation/index.js
app/navigation/routes.js
app/scenes/account_settings/account_settings.js
app/scenes/account_settings/account_settings_container.js
app/scenes/account_settings/index.js
app/scenes/index.js
app/scenes/right_menu_drawer/right_menu_drawer.js
app/scenes/right_menu_drawer/right_menu_drawer_container.js

This PR adds the account settings scene. Note that all setting options have been disabled for this screen at this point. Each setting option will be enabled when the corresponding screen is implemented. The following is the finished account settings screen:
https://mattermost.atlassian.net/browse/PLT-5634
@jarredwitt

PLT-5634 Add account settings scene

---

app/navigation/navigation_modal.js
app/navigation/router.js
app/reducers/navigation/index.js

This PR fixes a bug in the navigation where scenes would not be pushed onto the modal route stack if a modal was active.

Navigation modal fix

---

app/styles/index.js

By removing the right padding on the TextInput component style we are not longer truncating the autoscroll of the component making possible to auto scroll to the right when the text is too long.
https://mattermost.atlassian.net/browse/PLT-5659

PLT-5659 Server URL input box does not scroll when a long URL is entered

---

app/components/root/root.js
app/components/root/root_container.js
app/scenes/channel/channel.js
app/scenes/channel/channel_container.js

This PR moves the logic for getting profile statuses from the root component to the channel scene

Move periodic status check to channel scene

---

app/components/action_button.js
app/scenes/create_channel/create_channel.js

This PR creates a reusable component based on the create_channel_button that can be reused easily throughout the app for header buttons that call server actions.
@jarredwitt

Action button

---

app/scenes/login/login.js

Our `ErrorText` component is expecting localizable error objects (plain objects not exceptions) to have all i18n props nested inside of an `intl` key. In a couple of places in `Login` we were rendering those error objects without this key. This caused the app to crash when tried to submit a blank email or password.
https://mattermost.atlassian.net/browse/PLT-5810
@thomchop

PLT-5810 Add missing intl key to error objects in login screen

---

Makefile

Encountered build failure running ```make run-android``` in Ubuntu 16.04. See other info below:
-  android emulator is running
- versions: node 6.10.0 / npm 3.10.10 / watchman 4.7.0
Makefile failed to validate whether npm, adb and watchman are installed. In addition, it cannot determine whether adb emulator is running (```adb get-state``` to return```device```)
Actual log after running ```make run-android```: 
```
make: command: Command not found
npm is not installed
Makefile:10: recipe for target '.npminstall' failed
make: *** [.npminstall] Error 1
```
None. 
This PR was tested on: [Android emulator only, OS version: Ubuntu 16.04]

Fixed makefile for run-android

---

app/scenes/account_notifications/account_notifications.js

Fixed android app crashing on saving user notifications setting
Jira ticket: [PLT-5969](https://mattermost.atlassian.net/browse/PLT-5969)
This PR was tested on: [Android emulators only, Ubuntu 16.04]

[PLT-5969] Fixed android app crashing on saving user notifications setting

---

app/components/markdown/markdown.js
app/components/markdown/markdown_block_quote.js
app/components/markdown/markdown_code_block.js
app/components/markdown/markdown_image.js
app/components/markdown/markdown_link.js
app/components/markdown/markdown_list.js
app/components/markdown/markdown_list_item.js
app/components/post/post.js
app/constants/custom_prop_types.js
app/utils/theme.js
package.json

What this includes:
- Bold/Italics
- Explicit links `[Google](http://google.ca)`
- Headings
- Code blocks (fenced and indented)
- Inline code
- Lists
- Horizontal ines
------
What this doesn't include (https://mattermost.atlassian.net/browse/PLT-5736):
- ~~Strikethrough text~~ (not part of commonmark spec, https://mattermost.atlassian.net/browse/PLT-5736)
- Tables (not part of commonmark spec, https://mattermost.atlassian.net/browse/PLT-5736)
- Images (ran into implementation difficulties, https://mattermost.atlassian.net/browse/PLT-5736)
- Emoji (https://mattermost.atlassian.net/browse/PLT-5537)
- Various mentions and hashtags
https://mattermost.atlassian.net/browse/PLT-5717
This PR was tested on: Nexus 5 (Android 6.0.1) and iPhone Emulator (iPhone 6, iOS 10.1 )

PLT-5717 Initial markdown support

---

app/scenes/saml/saml.js

This PR fixes the issue with OneLogin cause the IDP does not return the action in the RelayState
Tested agains: https://ci-linux-mysql.mattermost.com
https://mattermost.atlassian.net/browse/PLT-5927
This PR was tested on: IOS 10.2.1 iPhone 6s, Android 6.0.1 Samsung J5

PLT-5927 - Fix SAML login with OneLogin

---

package.json

This supports all links that either start with a protocol or www. It's based off the changes I made to marked in the webapp, but it also handles surrounding asterisks and underscores better (since the previous regex messes up italics and bold when used with commonmark).
This PR doesn't make any changes to mattermost-mobile (outside of those for PLT-5717). The actual changes made are here: https://github.com/hmhealey/commonmark.js/pull/1
https://mattermost.atlassian.net/browse/PLT-5500
- Added or updated unit tests (required for all new features) (in commonmark.js repo)
This PR was tested on: iOS simulator

PLT-5500 Added URL autolinking

---

app/components/post/post.js
app/components/post/post_container.js

This PR depends on [PLT-5498 Add ability to delete a message](https://github.com/mattermost/mattermost-mobile/pull/357) and adds another set of options to flag an unflag posts
https://mattermost.atlassian.net/browse/PLT-5511
This PR was tested on: IOS 10.2.1 iPhone 6s, Android 6.0.1 Samsung J5

PLT-5511 Ability to flag and unflag posts

---

app/components/at_mention/at_mention.js
app/components/at_mention/at_mention_container.js
app/components/at_mention/index.js
app/components/markdown/markdown.js
app/components/post/post.js
package.json

Right now, this works as at mentions on the webapp do where we trim punctuation off of the mention to see if we find a username, but if we run out of punctuation, we just assume that user exists and we haven't seen them yet. This'll need some changes when I have the at mentions stored with their ID.
Clicking on the at mentions also doesn't do anything right now since it's blocked on adding search (or whatever we decide to have them do)
Changes made for this PR (since this is on top of the autolinking and markdown PRs):
https://github.com/mattermost/mattermost-mobile/commit/77a43e8a5cdada0b0862fed84472518a1228268c (Code to render at mentions)
https://github.com/hmhealey/commonmark.js/pull/2 (Code to find at mentions in the text)
https://github.com/hmhealey/commonmark-react-renderer/pull/1 …

PLT-5494 Added at mention detection

---

app/actions/navigation/index.js
app/components/badge.js
app/constants/navigation.js
app/initial_state.js
app/navigation/router.js
app/reducers/navigation/index.js
app/scenes/channel/channel.js
app/scenes/channel/channel_container.js
app/scenes/channel/channel_drawer_button.js
test/app/reducers/navigation.test.js

This PR takes care of:
1. Tapping on the hamburger button should always open the drawer
2. Drawer transition to open from below the scene and with the change of the opacity
3. Hamburger badge dot button should be centered
* https://mattermost.atlassian.net/browse/PLT-5711
* https://mattermost.atlassian.net/browse/PLT-5992
* https://mattermost.atlassian.net/browse/PLT-5996
* https://mattermost.atlassian.net/browse/PLT-6052
https://pre-release.mattermost.com/core/pl/fcaef7b1tigzpd81qjggu4ai9y

PLT-5711 Fix Tapping on the button to open the drawers not always work

---

app/actions/views/file_preview.js
app/actions/views/file_upload.js
app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_list.js
app/components/file_attachment_list/file_attachment_list_container.js
app/components/file_attachment_list/file_attachment_preview.js
app/components/file_upload_preview/file_upload_preview.js
app/components/file_upload_preview/index.js
app/components/post_textbox/post_textbox.js
app/constants/view.js
app/initial_state.js
app/reducers/views/channel.js
app/reducers/views/fetch_cache.js
app/reducers/views/index.js
app/reducers/views/thread.js
app/scenes/image_preview/image_preview.js
app/scenes/image_preview/index.js

This PR adds loading thumbnails for image previews and image upload previews. It also fixes the image preview header.
https://mattermost.atlassian.net/browse/PLT-6033
@jarredwitt

PLT-6033 Add loading spinner to image previewer

---

app/components/channel_drawer_list/channel_drawer_list.js

Known issue: The unread indicators above/below won't show up in android.
This is because of a React Native bug with the ListViews

PLT-5997 show the above unread indicator 15px below the header

---

app/actions/views/channel.js
app/components/channel_loader.js
app/components/file_attachment_list/file_attachment_preview.js
app/components/file_upload_preview/file_upload_preview.js
app/components/paper_plane.js
app/components/post/post.js
app/components/post/post_container.js
app/components/post_textbox/post_textbox.js
app/components/profile_picture/profile_picture.js
app/components/reply_icon.js
app/constants/view.js
app/initial_state.js
app/navigation/router.js
app/reducers/views/channel.js
app/scenes/account_settings/account_settings.js
app/scenes/channel/channel_post_list/channel_post_list.js
app/scenes/channel/channel_post_list/channel_post_list_container.js
app/scenes/channel/channel_title.js
app/scenes/channel_drawer/channel_drawer.js
app/scenes/channel_drawer/channel_drawer_container.js
app/scenes/image_preview/image_preview.js
app/scenes/navigationSceneConnect.js
app/scenes/settings/index.js
app/scenes/settings/settings.js
app/scenes/thread/thread_title.js

This PR takes care of the following tickets:
1. RN: Remove the error bar and log errors to the server
2. RN: Update channel header bar so it doesn't overflow
3. RN: Status indicators on the profile picture should not overlap that much
4. RN: Update design for the post textbox
5. Hide the team selection menu option if the user only belongs to one team
6. Show the reply icon with number of comments beside posts in center channel
7. Loading screen when switching channels
https://mattermost.atlassian.net/browse/PLT-5967
https://mattermost.atlassian.net/browse/PLT-5945
https://mattermost.atlassian.net/browse/PLT-6040
https://mattermost.atlassian.net/browse/PLT-6044
https://mattermost.atlassian.net/browse/PLT-5971
https://mattermost.atlassian.net/browse/PLT-5716 …

Plt 6044 plt 5971 plt 5934

---

app/components/markdown/markdown.js

This makes anything that CommonMark recognizes as HTML render as plain text instead of as `null` since RN doesn't support `null` nodes inside of `<Text>`. This also stops text recognized as HTML from being rendered as blank as it would've if the first error hadn't occurred.
This PR was tested on: iOS Simulator (iPhone 6, iOS 10.1)

Made HTML in posts render as plain text

---

app/actions/views/root.js
app/components/channel_drawer_list/channel_drawer_list.js
app/components/push_notification/index.js
app/components/push_notification/push_notification.js

This PR fixes:
* Do not show in app notifications when viewing the same channel
* Push notifications for DMs and GMs won't change the current team
* Channel drawer titles are all in caps
https://mattermost.atlassian.net/browse/PLT-6062
https://mattermost.atlassian.net/browse/PLT-6027
https://mattermost.atlassian.net/browse/PLT-6131

PLT 6062 - Fixing Push Notifications

---

Makefile
fastlane/Fastfile

To have internal builds for Android this changes the lane to be published from Beta to Alpha so we can then promote the correct builds to beta and have external testers.

Move Android lane from beta to alpha

---

app/components/file_upload_preview/file_upload_preview.js
app/components/file_upload_preview/index.js
app/components/post_textbox/post_textbox.js
app/components/post_textbox/post_textbox_container.js
app/scenes/image_preview/image_preview.js
app/scenes/load_team/load_team.js

This PR fixes the issue where the file upload modal would show during a channel switch. It also fixes an issue with being able to hit the close button on image previews when the button is hidden. 
https://mattermost.atlassian.net/browse/PLT-6145
@jarredwitt

PLT-6145 RN: File upload overlay doesn't clear

---

app/components/post_textbox/post_textbox.js
app/scenes/channel_members/channel_members.js
assets/base/i18n/en.json

Fixes an issue where messages longer than 4000 characters were allowed to be sent. Also fixes a loading message bug in channel_members.
https://mattermost.atlassian.net/browse/PLT-5963
@jarredwitt

PLT-5963 RN: Message over 4000 characters

---

app/components/channel_icon.js

Changed the color for the channel icon in the channel info scene
https://mattermost.atlassian.net/browse/PLT-6056

PLT-6056 set channel icon in channel info to use centerChannelColor

---

android/app/src/main/AndroidManifest.xml

This should make the app get push notifications on Android even after the app was killed in the Active Apps Screen.
https://mattermost.atlassian.net/browse/PLT-6171
This PR was tested on: Android 6.0.1

PLT-6171 Get Push Notifications after the app was killed

---

app/actions/views/channel.js
app/components/channel_drawer_list/channel_drawer_list_container.js
app/components/post/post_container.js

The app was loading really slow cause it was fetching every DM and GM that was used since the beginning of time, this will load just the DM's and GM's that need to be loaded.

Fix first load to include the right DM's and GM's

---

.babelrc
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mattermost/MainActivity.java
app/components/channel_intro/channel_intro.js
app/components/channel_intro/index.js
app/components/file_attachment_list/file_attachment_image.js
app/components/profile_picture/profile_picture.js
app/scenes/login/login.js
app/scenes/root/root.js
app/scenes/select_server/select_server.js

This PR fixes the following:
* Use APIv3 to get the image files cause the android Image component does not yet support headers (this has been added in RN 0.43) we could move it to APIv4 once we upgrade.
* Channel intro was using constants from the `release-3.7` branch
* Make babel to use `./src` as root for building `mattermost-redux`
* Fix android back button to not exit the app and then when opening the app again it was creating a newIntent and the root component did not mount
* Fix how we check for MFA required
* Android 7.1.1 Nexus 7

Several Fixes

---

app/actions/views/channel.js
app/actions/views/channel_add_members.js
app/components/post_list/post_list.js
app/scenes/channel_add_members/channel_add_members.js
app/scenes/channel_members/channel_members.js
app/scenes/edit_post/edit_post.js
app/scenes/edit_post/index.js
app/scenes/more_dms/more_dms.js
app/utils/member_list.js

* Fix edit post that was passing the wrong arguments to the action
* filterProfiles was renamed in `mattermost-redux` to filterProfilesMatchingTerm
* Fix a bug when opening a thread to not compute or show the channel intro message
* Fix membersToLoad in channel action
* Fix channel lists for `add members` and `manage members` where you weren't able to select users if the search function was used.
* Android 7.1.1 (Simulator Nexus 7)

Various Bug Fixes

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_list.js
app/components/post/post.js
app/scenes/image_preview/image_preview.js

This PR fixes an issue where posts with only file attachments could not be replied to.
https://mattermost.atlassian.net/browse/RN-78
@jarredwitt

RN-78: Can't reply to a post with only files

---

app/components/file_attachment_list/file_attachment.js

Remove download icon from file thumbnails
Jira: https://mattermost.atlassian.net/browse/RN-47
Github: https://github.com/mattermost/mattermost-mobile/issues/423
This PR was tested on: Emulator android 6 nexus 5

[RN-47] Remove download icon from file thumbnails

---

NOTICE.txt
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mattermost/MainActivity.java
android/app/src/main/java/com/mattermost/MainApplication.java
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/settings.gradle
app/actions/views/file_upload.js
app/components/file_attachment_list/file_attachment.js
app/components/post_textbox/post_textbox.js
ios/Mattermost.xcodeproj/project.pbxproj
package.json

9:26 AM
This PR adds a new image picking library for file uploads. This library uses the original filename for the image instead of a UUID.
https://mattermost.atlassian.net/browse/RN-79
@jarredwitt

RN-79: Images uploaded from React Native get renamed

---

app/actions/views/more_dms.js
yarn.lock

When creating a direct channel let the action handle the saving of the preference, also updates the dependency in yarn to the current master

Redux changes

---

app/components/channel_drawer_list/channel_drawer_list.js
app/components/custom_list/channel_list_row.js
app/components/custom_list/member_list_row.js
app/components/markdown/index.js
app/components/post/post.js
app/components/post_textbox/post_textbox.js
app/navigation/router.js
app/scenes/channel_add_members/channel_add_members.js
app/scenes/channel_info/channel_info_header.js
app/scenes/channel_info/channel_info_row.js
app/scenes/channel_members/channel_members.js
app/scenes/create_channel/create_channel.js
app/scenes/more_channels/more_channels.js
app/scenes/more_dms/more_dms.js
app/scenes/settings/settings_item.js

Changes include various UI improvements.
RN-42 - Fixing markdown headings
RN-43 - Making icons consistent in settings modal with other icons
RN-103 - Fixing alignment for create post buttons on Android
RN-104 - Unbold RHS categories
RN-105 - Making input fields observe similar style as post text input
RN-106 - Increase size for arrow icon, channel purpose, header, and created on text in info modal
RN-107 - Updating spacing between channel title and header in more channels info
RN-108 - Updating overlay on the center channel when LHS is open.
https://mattermost.atlassian.net/browse/RN-42
https://mattermost.atlassian.net/browse/RN-43
https://mattermost.atlassian.net/browse/RN-103
https://mattermost.atlassian.net/browse/RN-104
https://mattermost.atlassian.net/browse/RN-105 …

Multiple UI improvements

---

Makefile

Modified makefile to use `yarn cache clean` on `make clean` and call `clean` before making a build to ensure it uses the right dependencies

Ensure build uses the right dependencies

---

app/actions/views/channel.js

Whenever we loaded the app or changed teams we were checking to see if we had loaded channels for the current Team, and if that was the case we were loading just the channel members and this won't have the latests total_msg_count for each channel.
Now will be loading channel and members for when loading the app or when changing teams

Fix unread channels

---

app/scenes/settings/settings.js
assets/base/i18n/en.json

"Help" menu option should open help link in a mobile browser
Jira: https://mattermost.atlassian.net/browse/RN-48
GitHub: https://github.com/mattermost/mattermost-mobile/issues/283
This PR was tested on: Emulator Android 6.0

[RN-48] "Help" menu option should open help link in a mobile browser

---

app/screens/load_team/load_team.js

This PR fixes the known issue when tapping on a Push Notification when the app is in cold state for Android, for IOS the issue still exists and remain a known issue

Android push notification in cold state

---

package.json
yarn.lock

This PR fixes the crash when trying to upload a file in Android

Update react-native-image-picker to use a fork

---

app/screens/channel/channel_drawer_button.js
yarn.lock

Fix the unread indicator in the hamburger button to show only those that belong to the current team

Fix hamburger unread indicator

---

app/actions/views/channel.js
app/components/post_list/index.js
app/components/post_list/post_list.js
app/constants/view.js
app/reducers/views/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js
package.json
yarn.lock

This PR takes care of two things
1. Adds pull to refresh from the bottoms up in the post list to get the latest posts if necessary.
2. Modifies the post list to use an inverted ListView, that is able to show the scrollbar and removes the necessity of the hacky CSS to rotate the list and the rows in the list. (this should gain on performance)
https://mattermost.atlassian.net/browse/RN-136

RN-136 Post list pull to refresh

---

app/components/badge.js
app/components/channel_drawer_list/unread_indicator.js
app/components/loading.js
app/components/post/post.js
app/components/post_list/date_header.js
app/components/post_list/load_more_posts.js
app/components/post_list/new_messages_divider.js
app/components/post_list/post_list.js
app/screens/channel/channel.js
yarn.lock

This PR updates `mattermost-redux` that has a fix for Android WebSocket connection, also updates `View.propTypes` to `ViewPropTypes` to get rid of the deprecated warning, make sure we use an empty object if the draft for the channel is undefined and finally fixes an issue where we had a never ending loop when setting the `refreshing` prop as false

Various Updates and fixes

---

app/screens/create_channel/create_channel.js
app/screens/select_team/select_team.js

By using `dissmissModal` instead of `dismissAllModals` we make sure the navigator doesn't break (see https://github.com/wix/react-native-navigation/issues/418)

Replace dismissAllModals for dismissModal

---

app/components/file_upload_preview/file_upload_preview.js
app/components/post_textbox/post_textbox.js
assets/base/i18n/en.json

This PR fixes an issue where the upload preview icon was different than the icon shown in the channel. It also adds the ability to upload videos from both Android and iOS.
https://mattermost.atlassian.net/browse/RN-121

RN-121 Upload thumbnail

---

.gitignore
NOTICE.txt
android/app/build.gradle
android/app/src/main/java/com/mattermost/MainApplication.java
android/settings.gradle
app/mattermost.js
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/AppDelegate.m
package.json
yarn.lock

This PR adds the ability to use Sentry to log application errors. To use follow the below steps:
1. Install sentry cli using `brew install sentry-cli`
2. Create a `config.json` file in the `assets/override` folder with the following:
```
{
"EnableSentryLogging": true,
"SentryAuthToken": <YourSentryAuthToken>,
"SentryDSN": <YourSentryDSN>,
"SentryOrg": <YourSentryOrgSlug>
"SentryProject": <YourSentryProjectSlug>
}
```
3. Create a `sentry.properties` file in the `android` folder with the following:
```
defaults.org=<YourSentryOrgSlug>
defaults.project=<YourSentryProjectSlug>
auth.token=<YourSentryAuthToken>
```
Once complete run `make run-ios` or `make run-android` and the application will now report all errors and crashes to your Sentry portal. …

RN-145 Add support for sentry error tracking

---

app/components/channel_drawer/index.js
app/components/channel_drawer_list/channel_drawer_list.js
assets/base/i18n/en.json
yarn.lock

Whenever you get a new message or a mention now the channels appear under an **UNREADS** Section in the channel drawer at the very top when channels with mentions appear first and then unread channels
https://mattermost.atlassian.net/browse/RN-117
* IOS 10.3.1 iPhone 6
IOS
Android

Add "Unreads" section to channel drawer

---

app/components/markdown/index.js

I thought I might not be able to do this due to eventual emoji support requiring `<Image/>` tags within the paragraphs, but despite documentation saying that won't work properly on Android, that will still work when we add parser support for them.
https://mattermost.atlassian.net/browse/RN-124

RN-124 Improved text flow in markdown paragraphs and headers

---

app/screens/account_notifications/account_notifications.js

Fixes a bug that cause the app to crash when Email batching was enabled and the Account notifications screen was loaded
https://mattermost.atlassian.net/browse/RN-147

RN-147 Properly handle Account Notifications when Email Batching is enabled

---

app/components/channel_drawer_list/channel_drawer_list.js
app/components/channel_drawer_teams/channel_drawer_teams.js
app/screens/channel/channel_drawer_button.js

Is it still called a null pointer in Javascript? It's technically undefined instead of null, but it's basically the same thing

Fixed null pointer error in Badge component

---

app/components/custom_list/index.js

The loading indicator on the center of the screen for `More Channels` and `Direct Messages` will show only when performing a search, if no search is perform it will show the footer indicating there are more rows being loaded.
https://mattermost.atlassian.net/browse/RN-167

RN-167 custom list to show loading indicator only on search

---

app/components/channel_drawer/channel_drawer.js
app/screens/channel/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
package.json
yarn.lock

On Android there bug occurs because the wix-navigation does some weird stuff when pushing and pop-ing a screen causing the `ViewPagerAndroid` to stop responding, to fix it the screens that were being pushed on top of the channel screen are now opened as modals (only on Android) and that fixes the issue.
This also includes the update for `matterrmost-redux` that fixes RN-160
https://mattermost.atlassian.net/browse/RN-156
https://mattermost.atlassian.net/browse/RN-160

RN-156 Fix android channel drawer

---

app/screens/settings/settings_item.js

RN-128 - Unbolding settings categories
https://mattermost.atlassian.net/browse/RN-162
IOS Simulator.

RN-128 - Unbolding settings categories

---

app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/index.js
app/components/channel_drawer_teams/channel_drawer_teams.js
app/components/channel_drawer_teams/index.js
app/screens/settings/index.js
app/screens/settings/settings.js

Join other open teams in the settings screen (useful when you are in only one team)

Add join teams in settings screen

---

app/components/channel_drawer_list/channel_drawer_list.js

Removes the unread messages below indicator in the channel drawer, not needed anymore cause of the unread section in the drawer
https://mattermost.atlassian.net/browse/RN-169

RN-169 Remove "Unread below" indicator

---

app/components/offline_indicator/offline_indicator.js

The offline indicator that appears when no WS connection is present now when saying connecting.. it wont show the box surrounding the loading indicator
https://mattermost.atlassian.net/browse/RN-170

RN-170 Remove the box for the offline indicator

---

NOTICE.txt
app/actions/views/channel.js
app/components/options_context/options_context.ios.js
app/components/post/index.js
app/components/post/post.js
app/constants/view.js
app/initial_state.js
app/reducers/views/channel.js
package.json
yarn.lock

on IOS when the tooltip for a post is shown now tapping on another post will dismiss the tooltip and will not navigate to the thread view of the tapped post
https://mattermost.atlassian.net/browse/RN-148

RN-148 Tapping to dismiss post tooltip and prevent openining thread view

---

app/actions/views/channel.js
app/actions/views/select_team.js
app/components/channel_drawer_list/channel_drawer_item.js
app/components/channel_drawer_list/channel_drawer_list.js
app/components/channel_drawer_list/index.js
app/components/channel_drawer_teams/channel_drawer_teams.js
app/components/drawer.js
app/components/root/index.js
app/constants/view.js
app/reducers/views/channel.js
app/reducers/views/i18n.js
app/screens/channel/channel.js
app/screens/channel/channel_post_list/index.js
app/screens/channel/channel_title.js
app/screens/load_team/load_team.js
assets/base/config.json
test/mocks.js
yarn.lock

This PR includes fixes and improvements for the following:
* Follow user preferences to show or hide join/leave messages
* Fix the android issue when the app first loads and the post text input was off screen
* Use the device locale as the default locale instead of the `en`
* When tapping on a channel or a team in the drawer now we have visual feedback
* When switching channels the center channel title updates before the loading animation ends
https://mattermost.atlassian.net/browse/RN-166
https://mattermost.atlassian.net/browse/RN-158
https://mattermost.atlassian.net/browse/RN-181
* Android 6.0.1  Samsung J5

Various fixes & improvements

---

app/components/post_textbox/post_textbox.js
assets/base/i18n/en.json

Fix "libary" --> "library" typo
Credit to @wget who noticed it while doing translations.

Fix "libary" --> "library" typo

---

app/actions/views/channel.js
app/actions/views/root.js
app/screens/load_team/load_team.js
yarn.lock

When leaving channels and teams from another device now we make sure that they are left in RN whenever the app is re-opened or the WebSocket reconnects
https://mattermost.atlassian.net/browse/RN-185

RN-185 ensure leaving channels and teams

---

android/app/src/main/java/com/mattermost/CustomPushNotification.java
app/mattermost.js
app/push_notifications/push_notifications.android.js

Android: Push notifications will be one per channel, when receiving more than one push notification per channel the text on the push notification gets updated and it displays at the far right the amount of notifications per channel, on Android 7 it should group the notifications belonging to Mattermost.
When a channel is read in another **NON-mobile** device it will **clear the notifications from the notification center** for that channel and will subtract the amount of mentions in that channel from the badge in the app icon and if the app is in the foreground it will mark the channel as read.
IOS: Push notifications will be one per notification, when receiving more than one push notification per channel each notification will be shown individually on the notification center. When a …

RN-35 handle clear push notifications

---

app/components/post/post.js
app/utils/markdown.js

This caused uneven margins around headings
https://mattermost.atlassian.net/browse/RN-165
This PR was tested on: Nexus 5, iOS Simulator

RN-165 Removed lineHeight style from Markdown text

---

app/components/profile_picture/profile_picture.js

Hopefully this helps get the app to render the correct profile picture on a slow connection. I wasn't able to repro the bug described in the ticket, but this should prevent it from displaying an outdated picture if it reuses the component.
https://mattermost.atlassian.net/browse/RN-196

RN-196 Added a key to try to force ProfilePicture to rerender

---

app/components/markdown/index.js
app/components/markdown/markdown_block_quote.js
app/utils/markdown.js

Adding `flex: 1` to things is the RN version of adding `position: relative` all over the place in CSS
https://mattermost.atlassian.net/browse/RN-187
This PR was tested on: iOS Simulator, Nexus 5 
(Colours for illustration purposes only)

RN-187 Fixed right margin for block quotes

---

app/screens/channel_info/channel_info.js

The setting that determines `canManageUsers` is currently broken, but I'll be submitting a separate PR to fix that
https://mattermost.atlassian.net/browse/RN-207

RN-207 Fixed missing divider in ChannelInfo

---

app/components/channel_intro/channel_intro.js
app/components/post_list/post_list.js

Allows a user to get to view a user's profile by pressing on the user icon or name in the channel intro. 
https://mattermost.atlassian.net/browse/RN-179

Allow navigation to profiles using channel intro icons and names

---

NOTICE.txt
app/actions/views/login.js
app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/swiper/swiper.android.js
app/components/search_bar/search_bar.android.js
app/components/search_bar/search_bar.ios.js
app/components/search_bar/search_box.js
package.json
yarn.lock

This PR replaces the search_bar component for IOS and fixes the issue we had when regaining focus and canceling that the cancel button was still shown in the screen. Also fixes the alignment of the search placeholder and sets it to the left instead of centered.
Fixes the reset drawer for Android making so whenever you close the drawer it returns to the channels if it was sitting on the teams.
https://mattermost.atlassian.net/browse/RN-192

RN-192 Fix Cancel button in IOS search bar

---

app/actions/views/file_upload.js
app/components/post/post.js
yarn.lock

This PR reduces the opacity of a post until it either fails or is submitted successfully. 
https://mattermost.atlassian.net/browse/RN-52

Posts are now seen as pending until submitted successfully

---

app/components/channel_drawer/channels_list/index.js
app/components/channel_drawer/channels_list/list/list.js
app/components/channel_drawer/teams_list/teams_list.js
app/components/post_textbox/post_textbox.js

RN-171 - Extending border bottom on sidebar title
RN-164 - Teams title center and bold
RN-103 - Updating position for sendButton
RN-231 - Increasing left margin when only one team
https://mattermost.atlassian.net/browse/RN-171
https://mattermost.atlassian.net/browse/RN-164
https://mattermost.atlassian.net/browse/RN-103
https://mattermost.atlassian.net/browse/RN-231
- IOS simulator (6s)
- Moto x (First generation)

Ui improvements

---

app/actions/views/channel.js
app/components/channel_drawer/channel_drawer.js
app/components/inverted_flat_list/index.js
app/components/inverted_flat_list/virtual_list.js
app/components/post_list/index.js
app/components/post_list/post_list.js
app/constants/view.js
app/reducers/views/channel.js
app/screens/channel/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js
package.json
yarn.lock

This PR is a refactor of the `channel_post_list` and the `post_list`.
* `channel_post_list` was simplified and now it uses the pagination instead of `getPostsBefore` that way we ensure that we are retrieving the correct posts in order from the server, it also adds a postVisibility control where we establish the amount of posts that are going to get rendered.
* `post_list` was refactor to use the `VirtualizedList` instead of the `ListView`. In order to make the `VirtualizedList` to work as an inverted list we needed to extend the list from RN and make some adjustments.
This PR also fixes the issue were if the channel drawer was open by sliding the `channel_loader` would not disappear from the screen, that was due to a race condition with the `InteractionManager`
On IOS the refresh control …

Re-factor post_list with VirtualizedList

---

app/components/offline_indicator/offline_indicator.js

Changed offlineIndicator to be position absolute instead of relative and assign the initial position base on the Platform.
https://mattermost.atlassian.net/browse/RN-236
* IOS 10.3.2 Simulator iPhone 6

RN-236 Fix connection status bar covers part of post list

---

app/actions/views/login.js
app/components/root/index.js
app/i18n/index.js
app/styles/index.js
yarn.lock

This PR fixes localization and adds the `Accept-Language` header using the users locale or the device locale when the user hasn't logged in.
Make sure we set the correct `token` for APIv3 for those actions that still need v3 endpoints.
Changed the global style for the error message so it aligns the text to the left and not centered.

Fix localization + setting the token for APIv3

---

app/components/post_textbox/post_textbox.js

Fixes an issue where the attachment selector would fail to open.
https://mattermost.atlassian.net/browse/RN-168

RN-168 Attachment selector closes without attachment

---

app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
app/components/channel_drawer/channels_list/index.js
app/components/search_bar/search_bar.android.js
app/components/search_bar/search_bar.ios.js
app/components/search_bar/search_box.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js

When filtering the channel list in the drawer this PR makes sure that your own user is not listed as a DM and fixes the channel sorting.
As well this PR fixes the search_bar that was always a letter behind when typing something in the input field
https://mattermost.atlassian.net/browse/RN-229

RN-229 Filter channels to not return my own DM

---

app/components/markdown/markdown_link.js

We'll just make the HTTP protocol lower case to satisfy Android instead of making the whole thing lower case
https://github.com/mattermost/mattermost-mobile/issues/671

GH-671 Fixed entire link being made lower case

---

app/actions/views/root.js
app/mattermost.js

Fixes the channel name not being updated when opening the app with a push notification.
Also prevents the exception alert from being dismissed on Android

Fix push notification switch channel name

---

app/store/index.js

To ensure that there are no remaining `user is typing...` indicator we are going to prevent it for being stored permanently in redux offline

Blacklist typing state

---

app/components/badge.js
app/components/channel_drawer/channels_list/index.js
app/components/channel_drawer/teams_list/teams_list.js
app/screens/channel/channel_drawer_button.js

Fix the badge so it expands accordingly to the text it has to display without wrapping it in two or more lines
https://mattermost.atlassian.net/browse/RN-195

RN-195 Fix badge wrap for 2+ digits

---

app/components/search_bar/search_box.js

Not sure where that extra margin is coming from

Fixed uneven vertical margin on iOS search box

---

app/screens/settings/settings_item.js

These margins match the ChannelInfo modal

Fixed uneven settings dividers

---

app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
app/components/channel_drawer/channels_list/filtered_list/index.js
app/components/channel_drawer/channels_list/index.js
app/components/channel_drawer/channels_list/list/index.js
app/components/channel_drawer/channels_list/list/list.js
app/screens/channel/channel_post_list/index.js

This PR refactors the jump to conversation sidebar. It also allows the search order and display to be set by setting `SidebarSearchOrder` to an array within the config file. The possible values for the array are:
- unreads
- dms
- channels
- members
- nonmembers
For example if you do not want to display members and nonmebers while having the order be unreads, channels, dms then the `SidebarSearchOrder` config setting would be:
`"SidebarSearchOrder": ["unreads", "channels", "dms"]`
The default search order is `'unreads', 'dms', 'channels', 'members', 'nonmembers'`
@jarredwitt

Refactor Jump to Conversation

---

app/components/emoji/emoji.js
app/components/post_body/index.js
app/components/post_body/post_body.js
app/components/reactions/index.js
app/components/reactions/reaction.js
app/components/reactions/reactions.js
yarn.lock

Needs https://github.com/mattermost/mattermost-redux/pull/198 to work.
This PR adds the ability to display post reactions.
https://mattermost.atlassian.net/browse/RN-153

RN-153 Show emoji reactions on posts

---

app/screens/channel_info/channel_info.js

Fixes the issue where leaving or deleting a channel on Android would navigate back to the channel info screen of the default channel.
https://mattermost.atlassian.net/browse/RN-259

Android Leaving/Deleting channel redirects to info page of Town Square

---

app/components/inverted_flat_list/index.js

To be included in **dot release 1.0.1**
In some Android devices the style for transform does not work causing the list of post to render as blank, this PR will fix that issue by using the scaleY directly instead of a transform object.
Note: This will cause RN to display a deprecation warning in the yellowbox but it works as expected in all Android phones
https://mattermost.atlassian.net/browse/RN-269

RN-269 fix for huawei not rendering posts

---

app/components/file_attachment_list/file_attachment_image.js

Increases the quality of image thumbnails when shown in the post list. Also attempts to favor the top left corner of images that do not resize correctly 
https://mattermost.atlassian.net/browse/RN-256

RN-256 Image thumbnails are blurry

---

app/components/file_upload_preview/file_upload_preview.js
app/components/file_upload_preview/index.js

Can now start file upload in one channel and leave the channel without disrupting the file upload.
https://mattermost.atlassian.net/browse/RN-248

RN-248 Upload file and leave channel

---

app/components/search_bar/search_box.js

Made the clear button inside the search box more tappable by increasing the width and height of the container.
Also center the placeholder vertically
https://mattermost.atlassian.net/browse/RN-255
https://mattermost.atlassian.net/browse/RN-251
* IOS 10.3 iPhone 6 (simulator)
* IOS 10.3.2 iPhone 6s

RN-255 Fix search box clear button to be more tappable

---

app/components/channel_drawer/channel_drawer.js

Fix the hamburger icon opening the drawer when it was closed by swiping to close
https://mattermost.atlassian.net/browse/RN-249

RN-249 Fix opening the drawer with the hamburger

---

app/components/channel_drawer/channels_list/index.js

These margins are tricky because the settings button doesn't have a border and the search bar on iOS has padding that looks like a margin, so technically they were even before, but they didn't look that way. I tried to clean up the padding and make them actually even, but ended up being surprisingly difficult, so I didn't end up getting that working
https://mattermost.atlassian.net/browse/RN-253

PLT-253 Made margins around settings button appear even

---

app/screens/channel_info/channel_info.js
app/screens/channel_info/channel_info_header.js

This removes the "the last user of a private channel can't leave it, but is always able to delete it" functionality since that kept getting reported as a bug. There's a corresponding ticket for the platform repo that will change the required permissions on the server side and web app.
I also fixed a warning on the ChannelInfo screen at the same time since it was driving me nuts
https://mattermost.atlassian.net/browse/RN-244
https://mattermost.atlassian.net/browse/RN-274
https://mattermost.atlassian.net/browse/RN-277

PLT-244/PLT-277 Made Delete Channel visibility always depend on policy setting

---

app/screens/channel_info/channel_info.js
app/screens/channel_info/channel_info_header.js

The channel info for GM's was showing `NaN` as the amount of members of the GM cause a property was removed by mistake.
https://mattermost.atlassian.net/browse/RN-281

RN-281 Fix GM channel info memberCount

---

ios/Mattermost/Info.plist

URL scheme added to IOS, for Android adding the intent filter is causing the app to crash, bug report is on [react-native-navigation](https://github.com/wix/react-native-navigation/issues/384) lets wait and see if there is a solution for this.
https://mattermost.atlassian.net/browse/RN-262

Add mattermost:// url scheme to ios

---

app/screens/search/search.js

When using the Sticky Section Header functionality from the **RN SectionList** the section will stay at one position and then jump to the right position when it finishes rendering, so I'm adding a little timeout to give it time to render before scrolling automatically to the section
https://mattermost.atlassian.net/browse/RN-295

RN-295 Make search results scroll after a period of time

---

app/mattermost.js
app/screens/sso/sso.js

When logging in using SSO, OKTA was causing [this error](https://github.com/facebook/react-native/issues/10865) because they use `postMessage` in their login page this PR is a workaround for that.
This PR also fixes the cleanup of the token and serverVersion for the APIv3 Client used for pinging the server, this getting rid of the `[EROR] Invalid session err=GetSession: api.context.invalid_token.error` and enable the ability to re-login

Fix sso login onMessage handler

---

app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
yarn.lock

I tested this with both a master server and a 3.10 server to make sure it behaves correctly with older servers. It needs https://github.com/mattermost/mattermost-redux/pull/213 to be merged first so that yarn.lock can be updated
https://mattermost.atlassian.net/browse/PLT-6924
This PR was tested on: iOS Simulator (iOS 10.3)

PLT-6924 Added setting to disable mobile file uploads

---

app/actions/views/channel.js
app/components/post_list/index.js
app/components/post_list/post_list.js
app/constants/view.js
app/initial_state.js
app/reducers/views/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js
yarn.lock

This PR takes advantage of the post retry actions in the redux lib. It will show a loading spinner if the first request fails and then shows a failure message above the post list instructing the user to pull up to refresh the channel if all requests fail. If the channel has not been cached and the requests fail the retry post loading component is shown.

Use post retry actions to avoid missing messages

---

fastlane/Fastfile

Adds a script in Fastlane to ensure that we are cutting a build from the master or one of the releases branches

Fastlane ensure branch for cutting builds

---

app/components/custom_section_list.js
app/components/file_attachment_list/file_attachment_list.js
app/components/post_list/post_list.js

Despite not being included in the documentation, both FlatList and Section list support the keyboardShouldPersistTaps prop from ScrollView
https://mattermost.atlassian.net/browse/RN-305
https://mattermost.atlassian.net/browse/RN-310

RN-305/RN-310 Allow tapping buttons on post and DM lists without closing keyboard

---

app/components/markdown/index.js
app/utils/markdown.js
package.json

commonmark.js changes: https://github.com/hmhealey/commonmark.js/compare/57e6f0244a474a0e7d990f868531af5d98a57316...3139568442da83c5520685dc033eaf417dada2c0
commonmark-react-renderer changes: https://github.com/hmhealey/commonmark-react-renderer/commit/09d44ca4f64755e9ebf4616de676b34fc5935cd8
https://mattermost.atlassian.net/browse/RN-174

RN-174 Added support for strikethrough text in markdown

---

app/mattermost.js

This PR fixes an issue where the serverVersion is set `''` when the config is changed.

Fix empty serverVersion dispatch

---

app/screens/image_preview/image_preview.js
app/screens/image_preview/image_view.android.js
app/screens/image_preview/image_view.ios.js
app/screens/image_preview/previewer.js

Adds double tap zoom in/out and image gutters to the image preview screen.
https://mattermost.atlassian.net/browse/RN-25

Implement new image preview components

---

package.json
yarn.lock

This changes lists to work like the web app where
```
1. list
not list
```
renders as
1\. list
not list
instead of
1. list
not list
I also ported all the unit tests from https://github.com/mattermost/marked so that we have a full list of missing features and can keep track of any of our other custom behaviour.
commonmark.js changes here: https://github.com/hmhealey/commonmark.js/compare/7500afa285d7488932d7c4f805e6ff57cffeea1a...master
https://mattermost.atlassian.net/browse/RN-177

RN-177 Updated commonmark.js to match web app list behaviour

---

app/components/markdown/index.js
app/components/markdown/markdown_list_item.js
app/utils/markdown.js

@asaadmahmood For the code style, we can't apply padding or margin to inline text, so those stayed the same, but I updated font on iOS. There's not many selections for font on Android, so it's the same as it was before.
https://mattermost.atlassian.net/browse/RN-113
https://mattermost.atlassian.net/browse/RN-114

RN-113/RN-114 Updated markdown styles for lists and code

---

app/screens/create_channel/create_channel.js

on smaller screens the error was overlapping the "Name" label when creating new channels
https://mattermost.atlassian.net/browse/RN-303
This PR was tested on: iPhone 5s 

RN-303 fix small screen error overlap

---

app/components/badge.js

No surprise here that `display: 'flex'` does not work on Android, but this work around does work.
https://mattermost.atlassian.net/browse/RN-280

Fix badge display on Android

---

package.json
yarn.lock

This fixes:
1. Linking www links that don't start words like `testwww.google.ca` (changes [here](https://github.com/hmhealey/commonmark.js/commit/092171c1533338320ba079ef17e848839ae2a51e))
2. Not capturing the closing square bracket in IPv6 links like `http://[::1]` (changes [here](https://github.com/hmhealey/commonmark.js/commit/25dc6a4c456db579631797e29847752cb5e7d8d7))
https://mattermost.atlassian.net/browse/RN-319
https://mattermost.atlassian.net/browse/PLT-7553

PLT-7553/RN-319 Updated commonmark.js

---

app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/emoji/emoji.js
app/components/markdown/index.js
app/components/post_body/post_body.js
app/utils/markdown.js

- Makes non-square emojis render correctly
- Vertically centres emojis on iOS (Android doesn't support this). This looks pretty good on regular text, but is a bit off on headers. It's still much better than it was before.
- Adjusted line height and emoji sizes so that emojis don't push text out of the way
https://mattermost.atlassian.net/browse/RN-189
https://mattermost.atlassian.net/browse/RN-241
This PR was tested on: iOS Simulator (iPhone 6, iOS 10.3), Nexus 5 (Android 6.0.1)
Before (iOS): 
After (iOS):
Before (Android):
After (Android):

RN-189/RN-241 Updated emoji appearance

---

app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js

When saving the vibrate and lights preferences we weren't updating them correctly when toggling the option, this PR fixes it

Fix saving Android notification preferences

---

app/actions/views/emoji.js
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/autocomplete/emoji_suggestion/index.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js

Allows for reactions to be added using the `+` shortcut.
https://mattermost.atlassian.net/browse/RN-335

RN-335 Reaction shortcut

---

app/components/status_bar/status_bar.js

On Android it will render the status bar with dark icons and a black status bar so the icons aren't visible, this will fix it
GitHub #893

Fix status bar black on black in Android

---

app/components/file_attachment_list/file_attachment.js
app/screens/image_preview/image_preview.js
app/screens/image_preview/previewer.js

Add GIF support to the image previewer
https://mattermost.atlassian.net/browse/RN-337

RN-337 Enable GIF support in image preview

---

app/components/channel_drawer/channel_drawer.js

I just reverted the ordering issues so that the drawer closes smoothly now. This does not revert the changes to fade out the channel loader slowly (it happens instantly) or the other misc changes I made
https://mattermost.atlassian.net/browse/RN-345

RN-345 Revert changes that select channel before channel drawer is closed

---

app/actions/views/channel.js
app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/channels_list/channels_list.js
app/components/channel_drawer/channels_list/filtered_list/filtered_list.js
app/components/channel_drawer/channels_list/filtered_list/index.js
app/components/channel_drawer/channels_list/index.js
app/components/channel_drawer/channels_list/list/index.js
app/components/channel_drawer/channels_list/list/list.js
app/components/channel_drawer/channels_list/switch_teams/index.js
app/components/channel_drawer/channels_list/switch_teams/switch_teams.js
app/components/post_list/post_list.js
app/components/root/index.js
app/components/search_bar/search_bar.ios.js
app/constants/view.js
app/i18n/index.js
app/reducers/views/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js
app/selectors/i18n.js
app/store/index.js

I wasn't able to find any more major improvements to do, but I did clean up a few more places where we passed unnecessary props. I also added a new loading spinner that doesn't obscure the whole channel or cause it to bounce
https://mattermost.atlassian.net/browse/RN-345
Loading indicator:

RN-345 Additional improvements to channel switching

---

yarn.lock

state.entities.users.profilesInChannel wasn't being populated before by the actions that create new group and direct channels.
https://mattermost.atlassian.net/browse/RN-298

RN-298 Fixed profile pictures not being shown when creating new group message channel

---

app/actions/views/select_team.js
app/components/channel_drawer/teams_list/index.js
app/components/channel_drawer/teams_list/teams_list.js
app/screens/channel/channel.js
app/screens/channel/index.js

This doesn't fix the fact that I think the markChannelAsRead and viewChannel actions are overwriting each other's results, but it'll at least fire the actions in more cases
https://mattermost.atlassian.net/browse/RN-349

RN-349 Mark channel as read when switching teams and opening the app

---

package.json
yarn.lock

This is to fix an issue where a deeply nested markdown structure causes the channel to not render. React does not like when you nest components too deeply
commonmark-react-renderer changes: https://github.com/hmhealey/commonmark-react-renderer/commit/6e259b66ae87d31d2f908effcd05776b9ea3446f
https://mattermost.atlassian.net/browse/RN-369

RN-369 Added a maximum depth to the markdown renderer

---

app/components/channel_drawer/teams_list/index.js
app/selectors/teams.js

We were generating a new, sorted teams list every time the store changed so we're re-rendering this component more often than we need to

Added selector for getting sorted teams list

---

app/screens/create_channel/create_channel.js

On some Android devices for the header and purpose of a new channel tapping on Enter blurred the keyboard, now it keeps the keyboard up and creates a new line
https://mattermost.atlassian.net/browse/RN-320
* Android 7.1.1 emulator

RN-320 Tapping enter in channel header/purpose keeps the keyboard open

---

app/components/channel_drawer/channel_drawer.js

Always render the TeamsList so that the DrawerSwiper positions its contents correctly

Fixed drawer rendering empty if the user is only on one team

---

app/components/channel_drawer/teams_list/index.js
app/components/channel_drawer/teams_list/teams_list.js
app/components/channel_drawer/teams_list/teams_list_item/index.js
app/components/channel_drawer/teams_list/teams_list_item/teams_list_item.js

It turns out this issue was a lot simpler than I thought. Because we were just passing the list of teams into the FlatList here, it wasn't always re-rendering when the member object or unread count changed. I fixed this by moving the item rendering into its own file and having it listen to the store itself.
https://mattermost.atlassian.net/browse/RN-268

RN-268 Fixed teams list not always rerendering when team member changes

---

app/actions/views/channel.js
app/constants/view.js
app/reducers/device/index.js
app/reducers/device/websocket.js
app/reducers/views/channel.js
app/store/index.js

I added the time the websocket was connected/disconnected to the store, the time we last did a bulk pull of posts for the channel, and fixed the blacklist for the channel store (post drafts were broken). I also stopped using the `getXWithRetry` actions from the redux library, so I might remove those later in favour of just doing it manually like I did here.
https://mattermost.atlassian.net/browse/RN-379

RN-379 Get posts since last websocket disconnect when viewing channel

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/at_mention/index.js
app/components/autocomplete/at_mention_item/at_mention_item.js
app/components/autocomplete/at_mention_item/index.js
app/components/autocomplete/autocomplete_section_header.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention/index.js
app/components/autocomplete/channel_mention_item/channel_mention_item.js
app/components/autocomplete/channel_mention_item/index.js
app/components/autocomplete/index.js
app/components/autocomplete/special_mention_item.js
app/components/channel_intro/channel_intro.js
app/components/custom_list/user_list_row/user_list_row.js
app/components/post_profile_picture/post_profile_picture.js
app/components/profile_picture/index.js
app/constants/autocomplete.js
app/screens/notification/notification.js
app/screens/user_profile/user_profile.js
app/selectors/autocomplete.js
app/selectors/i18n.js

This PR refactors the autocomplete for at_mentions and channel_mentions, the same components are used for the `postTextBox` and the search screen.
I've added a few selectors that will take care of filtering depending on the term to match and they will only return the ids for users or channels, that way we'll prevent the *SectionList* from re-rendering if not necessary.
For the `postTextBox` the **at_mention** will show the sections for `Channel Members`, `Special Mentions` and `Not In Channel` and the **channel_mention** will show the sections for `My Channels` and `Other Channels`
For the search screen the autocomplete for **at_mentions** will show the `Members` section containing the search term for all the members in the current team, the **channel_mention** autocomplete will show the …

RN-382 Refactor at_mention & channel_mention autocomplete

---

app/components/autocomplete/at_mention/at_mention.js
app/selectors/autocomplete.js

at_mention autocomplete was broken cause the conditional channelId was wrong.
This will also fix the execution of the filters if the matchTerm is null

Fix postTextBox at_mention autocomplete

---

app/components/channel_intro/channel_intro.js
app/components/channel_intro/index.js

This PR makes sure that the channel intro shows only when there are no more posts to load and the channel has posts, if the channel is loading the initial posts it will show a spinner indicating that the posts are loading
https://mattermost.atlassian.net/browse/RN-413

Do not show channel intro while posts are being loaded

---

yarn.lock

Submitting this as a placeholder PR so that I'll remember to add the redux changes here. yarn.lock will need to be updated once https://github.com/mattermost/mattermost-redux/pull/264 is merged
https://mattermost.atlassian.net/browse/RN-268
- All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)

RN-268 Updated mattermost-redux to fix teams not being correctly marked as read

---

android/app/build.gradle
android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
android/app/src/main/res/layout/launch_screen.xml
android/app/src/main/res/values/colors.xml
android/app/src/main/res/values/styles.xml
app/mattermost.js
app/screens/load_team/load_team.js
app/screens/root/root.js

This PR changes the Android splash screen to use a layout file as well as removes the initial screen flickering that occurs when the app is opening. By switching to an Android layout file we allow for me configuration of the splash screen.
@jarredwitt will coordinate modifications

Switch android to use layout file for splash

---

app/components/channel_drawer/channel_drawer.js
app/components/drawer.js
yarn.lock

Sometimes trying to tap on the hamburger Icon or on the plus sign to attach files the drawer takes the responder making it impossible to respond to the taps.
With this PR we are creating an offset in the top and bottom so the swiping is below the navbar and above the postTextbox
https://mattermost.atlassian.net/browse/RN-428
https://github.com/mattermost/mattermost-mobile/issues/983

RN-428 Drawer panResponder offset

---

app/components/channel_drawer/channels_list/channel_item/channel_item.js
app/components/channel_drawer/channels_list/channel_item/index.js
app/components/channel_drawer/channels_list/filtered_list/filtered_list.js

With the changes for performance on the drawer channel list the filtered list was causing a crash, this is a temporary fix until we refactor the filtered list to be more performant, but until then this will make it work as expected without causing any crashes
https://mattermost.atlassian.net/browse/RN-439

Avoid crash on drawer filtered channel list

---

app/actions/views/emoji.js
app/components/post/index.js
app/components/post/post.js
app/components/post_list/index.js
app/components/post_list/post_list.js
app/components/search_preview/index.js
app/components/search_preview/search_preview.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js
app/screens/search/search.js
app/screens/thread/index.js
app/screens/thread/thread.js
app/selectors/post_list.js
test/app/selectors/post_list.test.js
yarn.lock

As discussed, this is to improve performance by making it easier to memoize props and avoid unnecessary rerenders on redux state changes.
Requires mattermost-redux PR: https://github.com/mattermost/mattermost-redux/pull/275

Changed to pass IDs to PostList instead of posts

---

.babelrc
Makefile
package.json
yarn.lock

When running a bundled app, these statements can cause a big bottleneck in the JavaScript thread. This includes calls from libraries, this PR make sure to remove them before bundling.

Babel plugin to remove console.* in production

---

app/components/formatted_time.js

This PR fixes an issue where users would report that post timestamps were wrongly based on a previous time zone that they traveled from.

Force formatted_time to use device time zone

---

app/screens/root/index.js
app/screens/root/root.js

This PR allows the app to start faster by not waiting for `loadMe` to complete if we already have the`currentUser`.

Skip await for loadMe if we have the currentUser

---

app/selectors/post_list.js
test/app/selectors/post_list.test.js

We are iterating through the posts from newest to oldest and the message indicator was the first thing being added that's why it was always rendering below all the messages.
Also the new message indicator now shows when someone else posts a message and not the current user.

Fix new message indicator

---

app/components/post_textbox/post_textbox.js

This PR fixes an issue on Android where predictive text would prepend suggestions to the post draft if messages were typed successively without blurring the input.

Fix android predictive text prepend issue

---

app/utils/network.js

Switched form deprecated `change` event to `connectionChange` instead

Fix Network detection util

---

app/components/inverted_flat_list/index.js

On Android we had the transform for the inverted list use a deprecated API cause it was causing issues rendering the post list in Huawei devices, this PR removes the deprecation and should work on Huawei devices as expected but needs to be tested.
Fix taken from https://github.com/facebook/react-native/issues/16213#issuecomment-338936748

Android: Fix inverted list deprecated warnings

---

app/screens/login/login.js
app/screens/login_options/login_options.js
assets/base/config.json
scripts/make-dist-assets.js

BASH-4
This PR allows for the login options page to be white labled via the override.json and by overriding or adding to the themes.json. Each login option can be turned off via the override.json. If the property for the login option is set to false, the server config is then checked to see if the login option needs to be displayed. The following properties were added to the config.json:
`HideEmailLoginExperimental` - Default is false.
Set to true to hide the email login option
`HideLDAPLoginExperimental` - Default is false.
Set to true to hide the LDAP login option
`HideSAMLLoginExperimental` - Default is false.
Set to true to hide the SAML login option
The UI can also be modified according to different properties within the theme.json. The following properties can be used to the change …

White label login options screen - Experimental

---

app/components/vector_icon.js
app/screens/settings/settings_item/index.js
app/screens/user_profile/user_profile.js
app/screens/user_profile/user_profile_row.js
docs/base_configs.md

Allow url link buttons in the user profile to be configured via overrides.
Add 1docs/base_configs.md` to demonstrate settings
- [ x ] Has UI changes
@jarredwitt will coordinate modifications

Allow profile button configuration

---

app/screens/image_preview/image_preview.js
assets/base/i18n/en.json

This PR fixes an issue where if a post was deleted while a user was previewing it's attachments on mobile the app would crash. With this PR if a post is deleted while a user has the previewer open on mobile, an alert showing that the post was deleted will be displayed and then the previewer screen will be closed once the OK button is pressed.
https://mattermost.atlassian.net/browse/RN-420

Handle post deleted while image preview is open

---

app/components/channel_intro/channel_intro.js

Channel intro was showing the members and names even if the channel wasn't a DM or GM
https://mattermost.atlassian.net/browse/RN-455

Show profile images and names only for DMs in channel intro

---

app/store/middleware.js

By keeping the post visibility we make sure that it doesn't gets reset to 0 when loading more messages by scrolling up in a channel.
Also we are going to keep the users statuses that are present in the current Channel
https://mattermost.atlassian.net/browse/RN-459

Keep user statuses for current channel and all post visibilities

---

app/components/post_body_additional_content/post_body_additional_content.js

Posts with youtube videos used to have nested Image components but that was deprecated by RN and instead they ask for the use of ImageBackground

Use ImageBackground for youtube videos instead of nested Images

---

app/components/channel_drawer/channels_list/list/list.js

The unread indicator was being shown even if the unread channel was visible cause we weren't waiting for an interaction with the section list to occur.

Fix Unread indicator shown when unread channel visible

---

app/components/post_profile_picture/post_profile_picture.js

Something I did while trying to repro an issue that couldn't be reproed.

Changed PostProfilePicture to be a PureComponent

---

app/components/post_list/load_more_posts/index.js
app/components/post_list/load_more_posts/load_more_posts.js
app/components/post_list/post_list.js
assets/base/i18n/en.json

The most important part of this is that the channelId is now passed into the LoadingMorePosts component so that it can actually detect if it's loading.
The other changes are refactoring to add a proper container and change "Loading Messages..." to "Loading messages..." so that it matches the capitalization in "Load more messages".
https://mattermost.atlassian.net/browse/RN-435

RN-435 Fixed Loading messages... message not appearing

---

app/actions/views/channel.js

If you're wondering, the return value of that action wasn't actually used, so I removed it instead of having to figure out if we still needed had more posts to load when we already have the posts loaded already
https://mattermost.atlassian.net/browse/RN-414

RN-414 Reduce loading of posts in increasePostVisibility action

---

yarn.lock

This is to remind me to update mattermost-redux after the other PR is merged
Redux PR: https://github.com/mattermost/mattermost-redux/pull/310
https://mattermost.atlassian.net/browse/RN-470
https://mattermost.atlassian.net/browse/RN-485

RN-470/RN-485 Stopped returning null post ID arrays when not logged in

---

app/screens/user_profile/user_profile.js

This only happened once to one user, so I'm not super concerned about why it was trying to render a user profile for a user that it didn't have
https://mattermost.atlassian.net/browse/RN-487

RN-487 Added null check for user in UserProfile

---

app/components/post/post.js
app/screens/search/search.js
app/screens/search/search_result_post/index.js
app/screens/search/search_result_post/search_result_post.js

When a post that appears in the search results is deleted, it no longer displays the reply icon, and the click handlers are removed from it.
Also, I removed the reply bar from appearing in search results since it felt out of place. This is how it used to look
https://mattermost.atlassian.net/browse/RN-472

RN-472 Improved handling of deleted search results

---

app/screens/settings/notification_settings/index.js
app/screens/settings/notification_settings/notification_settings.js
app/screens/settings/notification_settings_email/index.js
app/screens/settings/notification_settings_email/notification_settings_email.js
app/screens/settings/notification_settings_mentions/index.js
app/screens/settings/notification_settings_mentions/notification_settings_mention_base.js
app/screens/settings/notification_settings_mentions_keywords/index.js
app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js
app/utils/notify_props.js

In some edge cases the user's notify_props is null and the components were expecting some kind of value, now in the event that notify_props is not defined we'll be returning an object with the default values in order to avoid any kind of crash related to this
This PR will be cherry-picked for v1.4.1
https://mattermost.atlassian.net/browse/RN-412
https://mattermost.atlassian.net/browse/RN-426
https://mattermost.atlassian.net/browse/RN-483

Prevent notify props from causing a crash

---

app/components/badge.js
app/components/channel_drawer/teams_list/teams_list_item/index.js

Fixes the badges for unread indicators on the Teams to always show when the team has unread messages
Cherry pick for 1.4.1
https://mattermost.atlassian.net/browse/RN-499

Fix badge render

---

app/components/offline_indicator/offline_indicator.js
app/utils/network.js
assets/base/i18n/en.json

Ping the Mattermost server instead of google to detect if the app has network connection
This PR will be cherry-picked for the 1.4.1 dot release

Network detection by pinging Mattermost server

---

app/screens/user_profile/user_profile.js
app/screens/user_profile/user_profile_row.js

Allows iconSize to be passed in from the config when configuring profile buttons from the app config.

Allow iconSize to be passed from config

---

app/components/post_textbox/post_textbox.js

The clickable area now includes the padding around the icon as well. The green area in the screenshots below is the new clickable area while the old one was just the square enclosing the actual icon.
Also, @asaadmahmood, I made a couple small UI tweaks to make this easier to work with. The buttons are now exactly the same size instead of the Android one being 1 pixel taller with slightly different margins
This PR was tested on: iPhone 6 (iOS 10.3.3), iPhone 6 Simulator (iOS 11.1), Nexus 5 (Android 6.0.1)
The colours obviously aren't included in the PR, and the attachment icon is in the correct place in the submitted version.
iOS:
Android:

Increased clickable area around send post button

---

app/components/autocomplete/emoji_suggestion/emoji_suggestion.js

When doing the actual replacement, it won't capture the preceding character any more.
https://mattermost.atlassian.net/browse/RN-480

RN-480 Fixed emoji autocomplete removing spaces before emoji

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/at_mention_item/at_mention_item.js
app/components/autocomplete/autocomplete.js
app/components/autocomplete/autocomplete_divider/autocomplete_divider.js
app/components/autocomplete/autocomplete_divider/index.js
app/components/autocomplete/autocomplete_section_header.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention_item/channel_mention_item.js
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/autocomplete/special_mention_item.js
app/components/post_textbox/post_textbox.js
app/screens/search/search.js

This is basically just a lot of changes to move the borders onto the Autocomplete component instead of the list item components so that the entire list has a border instead of just the rows in the results

Updated borders on autocomplete to wrap entire list

---

package.json
yarn.lock

Adds the XRegExp library (which I thought we already used there) and changes the URL pattern to use `\pL` which matches all unicode letters (including CJK characters, Cyrillic letters, accented letters, etc) instead of using `[a-z]` which only matches latin letters
Commonmark.js changes here: https://github.com/hmhealey/commonmark.js/commit/fe78a8538cd080fa6765f94589870458b59958d1
https://mattermost.atlassian.net/browse/RN-497
- Added or updated unit tests

RN-497 Updated commonmark to better handle non-latin characters in URLs

---

app/components/options_context/options_context.ios.js

Post context menu wasn't being updated whenever the actions changed. ej: Once a post was flag the option wasn't changing to unflag

Fix iOS post context menu

---

app/components/post_textbox/components/attachment_button.js

This prevents OutOfMemoryErrors when posting images of e.g. 4MB size. See the ticket for more details.
#1157 
Samsung S7, Nougat, and a Lollipop device

Request image quality 1 (=100%) to avoid scaling (and failing with OOME) (#1157)

---

Makefile

Remove the `--reset-cache` flag for the packager when running the app locally and leave it in for building purposes

Use reset-cache flag to start the packager only for building

---

app/components/offline_indicator/offline_indicator.js
app/components/vector_icon.js
app/screens/settings/notification_settings_mentions/notification_settings_mentions.android.js
app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js

Some older users may be missing those fields on their notification props, so we need to provide a default case for them.
https://mattermost.atlassian.net/browse/RN-483

RN-483 Ensured switch statements used for i18n have a default case

---

app/actions/views/channel_add_members.js
app/actions/views/channel_members.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/utils/general.js

This PR adds an utility function to show and Alert if the action being executed returns a status code 403 from the server.
List of current actions:
1. create channel (already handled)
2. update channel (not in RN yet)
3. patch channel (not in RN yet)
4. delete channel (already handled)
5. leave channel (optimistic action, wondering how to show the error here)
6. add channel member (covered in this PR)
7. remove channel member (covered in this PR)
8. delete post (optimistic action, wondering how to show the error here)
9. edit post (already handled)
Note: This PR will need more work if #1189 is merged first or that PR will need to include this function when editing the channel
https://mattermost.atlassian.net/browse/RN-524

Add general util to handle actions that are forbidden

---

app/components/emoji/emoji.js
app/components/markdown/index.js
app/components/markdown/markdown_block_quote.js
app/components/markdown/markdown_image.js
app/components/markdown/markdown_link.js
app/components/markdown/markdown_list.js
app/components/markdown/markdown_list_item.js
app/components/markdown/transform.js
app/utils/markdown.js
app/utils/url.js
assets/base/i18n/en.json
test/app/components/markdown/transform.test.js

This one is a bit more complicated than the regular markdown changes because it requires moving images out of paragraphs, lists, etc because React Native doesn't support nesting them within text except under very specific circumstances (that emoji have to follow). This means that if you had something like
```
This is a sentence with ![an image](http://example.com/image) in it
```
it's instead converted into something more like
```
This is a sentence with
in it
```
I added Asaad to this in case there's any changes that should be made to the appearance of the images or the text that's displayed when they cannot be loaded. Also, if you want to test this yourself, here's some test images you can use:
```
```
https://mattermost.atlassian.net/browse/RN-173
- Added or updated unit tests …

 RN-173 Added support for Markdown images

---

app/components/radio_button/radio_button.js

Fixes a weird color behind the radio buttons on android caused by the initial values for opacity and scale
https://pre-release.mattermost.com/core/pl/hdixdwx5obbd7naw1sago7k4zw
Android

Android: Fix weird colors in radio buttons

---

app/components/post_list/post_list.js

Makes sure that the message index we want to scroll to is not out of the range of postIds

Defensive fix for post list scrollToIndex

---

app/actions/views/command.js
app/components/post_textbox/post_textbox.js

Fixes an issue where a slash command could not be used when commenting on a post.

Fix slash command for post comment

---

app/components/markdown/index.js
app/utils/theme.js

This PR was tested on: Nexus 5 (Android 6.0)

Applied correct text colour to (edited) indicator on Android

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/autocomplete.js
app/components/autocomplete/channel_mention/channel_mention.js
app/screens/search/search.js

Re-position autocomplete in search screen and fixed the styling so it works in both android and ios.
PostList autocomplete still works as expected
This PR needs to be merged before #1225 
https://mattermost.atlassian.net/browse/RN-375

fix autocomplete positioning

---

Makefile
fastlane/Fastfile

This update will let us add new java files inside the **com.mattermost.rnbeta** package without the need to include them in the *fastlane* script when building for release

update java package when preparing for release

---

app/components/layout/keyboard_layout/keyboard_layout.js
app/components/post_textbox/post_textbox.js
app/components/text_input_with_localized_placeholder.js
app/screens/login/login.js

The KeyboardAvoidingView sometimes caused the keyboard to be placed on top of the postTextBox, this PR will prevent that.
also prevents Android for showing the textInput in fullscreen.
resolves #1239

Replace KeyboardAvoidingView with custom

---

app/components/layout/keyboard_layout/keyboard_layout.js

Fixes the post textbox component staying behind the keyboard on ios 10 and 9.
This PR was tested on: iOS simulators with version 11, 10 and 9
iPhone 6, iPhone 5s, iPhone X

Fix keyboard layout for ios 9 and 10

---

app/screens/user_profile/user_profile.js

Ensures that we send the user to the channel view regardless if the user profile was pushed or if it is a modal on Android when the send message button is pressed.
https://mattermost.atlassian.net/browse/RN-550

Android: Show center screen from user profile

---

app/components/post_textbox/index.js

The post text box component was ignoring the channelId being passed as an ownProp
https://mattermost.atlassian.net/browse/RN-563

Fix replying to a search result

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Report from google play
```
java.lang.RuntimeException: 
at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3314)
at android.app.ActivityThread.-wrap21 (ActivityThread.java)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1565)
at android.os.Handler.dispatchMessage (Handler.java:102)
at android.os.Looper.loop (Looper.java:154)
at android.app.ActivityThread.main (ActivityThread.java:6077)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: 
at com.mattermost.rn.CustomPushNotification.clearNotification (CustomPushNotification.java:59)
at …
```

Android: Avoid crash when clearing notifications (1.5)

---

app/store/index.js
app/utils/promise_timeout.js

Add a timeout around any api calls so we can assure the `effect` decorate action always returns.
This will allow any api call that takes too long to fail faster.
Specially for the Client4.createPost method.  If the api never returns, the post is in a pending state and the user is not able to retry.
This PR depends on: https://github.com/mattermost/mattermost-redux/pull/342
For some context this behavior may occur with a flaky network connection.  User in a train, elevator or switching from LTE to Wifi.
@miguelespinoza

Create post timeout

---

Makefile

There are some who are trying to run the make commands on a linux machine and trying to install cocoapods fails, this change to the makefile will only check and run cocoapods if is ran from a mac

Run podinstall if the OS is mac

---

app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js

It turns out that these weren't updated to handle the actions an object with a data field.
https://mattermost.atlassian.net/browse/RN-462
This PR was tested on: iOS 6 Simulator (iOS 11.2)

RN-462 Allow user and channel lists to load more than one additional page of content

---

app/components/channel_intro/index.js
app/components/post_list/post_list.js
app/utils/list_view.js

The PostList footer (aka the ChannelInfo component) wasn't being re-rendered in certain circumstances when the channel changed, so adding the channel ID to the extraData prop will force it to re-render. The other refactoring is just left over from my other PR
https://mattermost.atlassian.net/browse/RN-566
This PR was tested on: iPhone 7 Simulator (iOS 11.2)

RN-566 Re-rendered PostList footer when channel ID changes

---

app/components/channel_drawer/channel_drawer.js
app/components/channel_drawer/channels_list/channels_list.js
app/components/channel_drawer/index.js
app/components/channel_drawer/teams_list/teams_list.js
app/components/profile_picture/index.js
app/components/profile_picture/profile_picture.js
app/components/safe_area_view/safe_area_view.android.js
app/components/safe_area_view/safe_area_view.ios.js
app/components/settings_drawer/drawer_item.js
app/components/settings_drawer/index.js
app/components/settings_drawer/settings_drawer.js
app/components/settings_drawer/status_label/index.js
app/components/settings_drawer/status_label/status_label.js
app/components/settings_drawer/user_info/index.js
app/components/settings_drawer/user_info/user_info.js
app/components/user_status/index.js
app/components/user_status/user_status.js
app/screens/channel/channel.js
app/screens/channel/channel_nav_bar/channel_drawer_button.js
app/screens/channel/channel_nav_bar/channel_nav_bar.js
app/screens/channel/channel_nav_bar/channel_search_button/channel_search_button.js
app/screens/channel/channel_nav_bar/channel_title/channel_title.js
app/screens/channel/channel_nav_bar/channel_title/index.js
app/screens/channel/channel_nav_bar/settings_drawer_button.js
app/screens/settings/general/index.js
app/screens/settings/general/settings.js

Implementing initial right drawer, the user info and the status buttons aren't functional but they do accept an onPress prop
https://mattermost.atlassian.net/browse/RN-557
* iOS 11.1 iPhone X and iPhone 6 emulator
* iOS 11.2 iPhone 6
* Android 7.1.1 Nexus 5 Emulator

Right drawer

---

android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java
app/notification_preferences/notification_preferences.android.js
app/screens/settings/notification_settings/notification_settings.js

In some cases Android devices need permission for `READ_EXTERNAL_STORAGE` to access the RingtoneManager, with this PR we make sure that the user has set the permission before requesting the preferences with the `NotificationPreferencesModule`, if the user hasn't granted the permission yet we do ask for it before trying to get the Preferences, if the use denies it we still show the mobile notification screen but without loading the device specific prefs thus avoiding any potential crash.
Also if the device does not have a `RingtoneManager.getActualDefaultRingtoneUri` set, we just set the default sound as none.
https://mattermost.atlassian.net/browse/RN-588
* Android 7.1.1 Nexus 5 emulator
* iPhone simulator (just to make sure it doesn't …

Ensure the user has permission to access ringtones

---

app/components/layout/keyboard_layout/keyboard_layout.js

Fixes the keyboard positioning on top of the textbox when switching back and forth keyboard types in iOS
resolves #1302

Fix keyboard avoiding view when switching keyboard

---

app/actions/views/file_upload.js
app/components/file_upload_preview/file_upload_preview.js

When uploading a video from Android the returned object has a `path` property instead of `fileName`, this PR makes sure that if fileName is not defined it will fallback to use path instead
Also fixes the upload of gif files in iOS, this type of file returns just the uri of the file, so we make sure any of the three options is available when getting the name of the file, etc..
Also added support to show the preview of gif files in the image upload preview.
https://mattermost.atlassian.net/browse/RN-572
https://mattermost.atlassian.net/browse/RN-574

Fix uploading videos from Android

---

app/mattermost.js
app/push_notifications/push_notifications.android.js

On Android sometimes when requesting the refreshToken it was causing the app to not respond.
This is being fixed by:
Instead of requesting a refresh token in the configure method, we now request the token when to class is initiated removing the need to ask for the token a second time.
https://mattermost.atlassian.net/browse/RN-585

Fix Application Not Responding (ANR) executing service android

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Sometimes channelIdToNotification is null for certain channels that haven't received previous push notifications, with this PR we ensure that the app doesn't crashes when that happens.
https://mattermost.atlassian.net/browse/RN-587

Make sure that channelIdToNotification is not null

---

app/components/post/post.js
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/post_body/post_body.js
app/components/post_body_additional_content/post_body_additional_content.js

When a post with opengraph (link previews) is render inside a thread now renders appropiately
https://mattermost.atlassian.net/browse/RN-569
Before
Now

Fix UI when rendering link previews in a reply

---

NOTICE.txt

They just added a license file: https://github.com/charliesbox/react-native-media-controls/blob/master/LICENSE

react-native-media-controls is Apache v2, not MIT

---

app/screens/channel/channel_nav_bar/channel_drawer_button.js
app/screens/channel/channel_nav_bar/channel_nav_bar.js
app/screens/channel/channel_nav_bar/channel_search_button/channel_search_button.js
app/screens/channel/channel_nav_bar/channel_title/channel_title.js
app/screens/channel/channel_nav_bar/channel_title/index.js
app/screens/channel/channel_nav_bar/settings_drawer_button.js

With the inclusion of the right drawer, we are now moving the title in the channel view navbar to be aligned to the left in order to have more space for the title if needed.
https://mattermost.atlassian.net/browse/RN-591
* iOS 11.2 iPhone X, iPhone 6 (simulator) and iPhone 6s (device)
* Android 7.1.1 Emulator
Android
iOS

Left align title text in channel view navbar

---

app/components/markdown/markdown_link.js

This fixes a crash that occurs on Android if you post `[click me]()` and then click on it.
https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/421001308/

Don't try to open empty Markdown links

---

app/components/slack_attachments/slack_attachment.js

This PR wraps the interactive buttons within the view instead of just placing one after the other.
Resolves #1326
https://mattermost.atlassian.net/browse/RN-600
Android 7.1.1 Nexus 5 emulator
iOS 11.2 iPhone X simulator
Android
iOS

Wrap interactive buttons when needed

---

app/store/middleware.js
app/utils/sentry/index.js

As we discussed last week, parts of the state in action.payload are empty for whatever reason, so we're wrapping the whole `cleanupState` action in a try-catch to keep the app from crashing, but we're still logging to Sentry to still be able to investigate the error itself
https://mattermost.atlassian.net/browse/RN-523
https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/417670104/
This PR was tested on: iOS Simulator (iPhone 6, iOS 11.2)

RN-523 Added a try-catch when cleaning up state following a rehydrate

---

app/actions/views/login.js
app/actions/views/root.js

Because we weren't checking if the user was actually logged in there was a case when requesting the data retention policy returned 401 sending the user back to the server url screen.
https://mattermost.atlassian.net/browse/ICU-605

Request data retention policies only when the user is logged in

---

app/actions/views/select_server.js
app/mattermost.js
app/screens/login/login.js
app/screens/select_server/index.js
app/screens/select_server/select_server.js
yarn.lock

Sometimes when the session expires or is revoked the user was unable to get past the server url screen because we were waiting for the config and license request to be executed, but becase once the user was logged out some other request were setting the server url we didn't made the request for the config and license, this PR fixes that.
https://mattermost.atlassian.net/browse/ICU-594

Fix login after session expires or is revoked

---

NOTICE.txt
app/constants/index.js
app/constants/permissions.js
app/screens/image_preview/image_preview.js
assets/base/i18n/en.json
ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/Info.plist
package.json
yarn.lock

When downloading an image or saving a video in a iOS device which hasn't granted the permission to write to the Photo library, the app was crashing with a SIGNAL 6, this PR checks and requests the needed permissions to avoid the crash.
https://mattermost.atlassian.net/browse/ICU-479
* iOS 11.2 iPhone 5s, iPhone 6 and iPhone X (Simulators)
* iOS 11.2 iPhone 6s

iOS request permissions if needed to save files to the photo library

---

app/components/post_header/post_header.js

When a slash commands responds with an ephemeral post, the post is marked as system message but it also has a from_webhook prop, this PR will render the header giving priority to the from_webhook prop.
This was found during the investigation of https://mattermost.atlassian.net/browse/ICU-634 which is working just fine and I couldn't replicate the behavior.
https://mattermost.atlassian.net/browse/ICU-634

Post header priority

---

app/components/badge.js

Fixes the flickering on the mention badge as well as the text wrapping in smaller screens for two digits
https://mattermost.atlassian.net/browse/ICU-581
* iOS 11.2 iPhone 5s and iPhone X (simulators)

Fix mention badge

---

app/components/post_body/index.js

I still wasn't able to cause the post to get stuck as pending naturally, but I tested with some code that always made the first request fail.
This isn't the nicest since it relies on something else causing the post to re-render, but since the post should only get stuck in this state after the app is closed, I don't think that's a problem.
https://mattermost.atlassian.net/browse/ICU-616

RN-616 Added a fallback to prevent posts from being stuck as pending

---

share_extension/ios/extension_channels.js
share_extension/ios/extension_post.js
share_extension/ios/extension_teams.js

iOS Share extension was having some issues displaying the list of teams cause the loop through the teams was using an `async` inside a forEach, that was fix with a simple for loop.
Some User Profiles were not retrieved cause the user Preferences had some missing `CATEGORY_DIRECT_CHANNEL_SHOW` causing the request to **getProfilesByIds** to return an invalid argument.
Important: I've said this a few times now but I'll repeat. In iOS there is a known issue if a file that is being shared is too large causing the extension to be terminated, this is because the share extension on iOS has a memory limit and by reading the content of the file we surpass that limit.
The workaround for the above needs some server changes.

iOS Share extension, fix teams and dm channels

---

app/screens/channel/channel.js

If you look at the render method of the Channel screen, there's two ChannelLoader instances, one before the PostTextbox and one after it, so I removed the first one

Removed duplicate ChannelLoader instance

---

app/components/emoji/emoji.js
app/components/markdown/markdown.js

I did this as part of the markdown tables PR, but it relates to Stephen's work, so I submitted it early. It now calculates the fontSize from the text style instead of passing it in separately

Removed fontSize prop from Emoji

---

assets/base/config.json

As discussed the option for Check for Updates and App Upgrade is disabled by default, EE customers can enable it if needed by building the apps themselves.
https://mattermost.atlassian.net/browse/ICU-642

ICU-642 Remove Check for Updates screen by default

---

app/components/channel_drawer/channels_list/channel_item/channel_item.js
app/components/channel_drawer/channels_list/channel_item/index.js
app/components/channel_icon.js
app/components/channel_intro/index.js
app/components/post_textbox/index.js
app/components/post_textbox/post_textbox.js
app/components/status_icons/archive_icon.js
app/components/status_icons/index.js
app/selectors/channel.js

Add support for DM with deactivated channel (teammate) similar to webapp.
- check whether the use of icon `trash` is appropriate
- check about the position of archived message below (in placed of `PostTextbox`)
Jira ticket: [ICU-629](https://mattermost.atlassian.net/browse/ICU-629)
This PR was tested on: [IOS and Android emulators, OS versions Iphone6/11.2, Nexus 5/6.0/API23] 
Android:
IOS:

[ICU-629] Add support for DM with deactivated channel (teammate)

---

Makefile
android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java

There is a bug in `RNN` that causes the app to enter an infinite loop between the SplashActivity and the first activity of the app giving the sensation that the app is stuck in the Splash Screen, I've reported the [Bug](https://github.com/wix/react-native-navigation/issues/2610) and there seems to be a workaround for it (referenced in the issue).
But when closing the app with the hardware back button and re-open the app indeed was stuck, that is why I've added the changes in the Makefile to handle the back button with a different behavior and solving the issue.
RNN = react native navigation
RNN are saying that they are fixing this and other issues in their v2 but is not yet ready but we should be on the look out.
https://mattermost.atlassian.net/browse/ICU-592
cc: @grundleborg just to …

Fix Android app stuck in splash screen when killed by the OS

---

app/components/post_list/post_list.js
app/components/post_list/with_layout.js

This PR fixes an issue where `onLayoutCalled` would not always be called by the new message or date headers which causes the list not to scroll to the new message. Accuracy has also been improved for the placement of the new message header within the view window.

ScrollToNewMessage: Fix onLayoutCalled issue and improve accuracy

---

app/components/slack_attachments/slack_attachment.js

The post attachments were showing the border color if an hex was used a a color but didn't handle the case when the colors were `good`, `warning` and `danger`

Handle the good, warning, danger status for post attachments

---

app/components/options_context/options_context.ios.js
app/components/post/post.js
app/components/tooltip.js
app/utils/tooltip.js
package.json
yarn.lock

This PR helps us get rid of the fork for the react-native-tooltip, I'm going to keep the fork around for a couple of releases and then will delete it

Update tooltip library

---

android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java

When the app is running in the background and a push notification is tapped to open the app it was getting stuck in the Splash Screen (yes another thing causing the same issue)
This fix was found by Shift.
To be cherry-picked for a 1.6.1 dot release

Fix Android stuck when opening from push notification

---

app/components/search_bar/search_bar.android.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js

This PR internalizes the android's search input's value to the local state. The issue seemed to be the slight delay between propogating the value up the component tree, then back into the component as a prop caused the keyboard to duplicate input. 
It now handles state internally, unless the prop sent in is different (**case insensitive**) than the state, then is uses the prop value.
See video : https://www.youtube.com/watch?v=S69bPljpRFc
https://mattermost.atlassian.net/browse/ICU-639
This PR was tested on: Emulated Nexus 5X with Samsung S8 Keyboard
https://www.youtube.com/watch?v=S69bPljpRFc

ICU-639- Fixes bug with Samsung keyboard

---

app/components/channel_drawer/channels_list/list/index.js
app/components/post/index.js
app/components/post/post.js
app/screens/channel_info/index.js
app/screens/more_channels/index.js
package.json
yarn.lock

Use the new advanced permissions (mainly solved in the redux library)
Depends on mattermost/mattermost-redux#360 and the
mattermost/mattermost-server#8159 PRs.
[XYZ-45](https://mattermost.atlassian.net/browse/XYZ-45)
This PR was tested on: [OnePlus5, Android 8]

[XYZ-45] New permissions implementation

---

app/actions/views/emoji.js
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/autocomplete/emoji_suggestion/index.js
app/components/emoji/emoji.js
app/components/emoji/index.js
app/components/emoji_picker/emoji_picker.js
app/components/emoji_picker/emoji_picker_row.js
app/components/emoji_picker/index.js
app/constants/view.js
app/mattermost.js
app/reducers/views/emoji.js
app/reducers/views/index.js
app/screens/channel_info/channel_info.js
app/screens/channel_info/index.js
app/screens/select_server/index.js
app/screens/select_server/select_server.js
app/store/index.js
app/utils/markdown.js
yarn.lock

This PR does the following:
* Modified emojis to show blank until either the emoji metadata is loaded or found not to exist
* Adds an action when the channel info is shown to load any missing emojis in the channel header
* Adds a server request to emoji autocomplete (similar to how it's done for users)
* Adds custom emoji paging to the emoji picker
Two things to note:
1. I did not add any clearing of the new `nonExistentEmoji` entity when bringing the app to the foreground. The consequence of this is that if someone posts `:some_emoji_that_does_not_exist:`, you switch your app to the background, someone adds that emoji, you're not going to get the new emoji until close and re-open the app. I don't think it's worth clearing it every time you switch to the foreground but let me know if this …

ABC-123 Add handling for loading custom emojis asynchronously

---

app/components/markdown/markdown.js
app/components/markdown/markdown_code_block/markdown_code_block.js
app/components/markdown/markdown_table/index.js
app/components/markdown/markdown_table/markdown_table.js
app/components/markdown/markdown_table_cell/index.js
app/components/markdown/markdown_table_cell/markdown_table_cell.js
app/components/markdown/markdown_table_image/index.js
app/components/markdown/markdown_table_image/markdown_table_image.js
app/components/markdown/markdown_table_row/index.js
app/components/markdown/markdown_table_row/markdown_table_row.js
app/components/markdown/transform.js
app/screens/index.js
app/screens/table/index.js
app/screens/table/table.js
app/screens/table_image/index.js
app/screens/table_image/table_image.js
app/utils/markdown.js
assets/base/i18n/en.json
package.json
test/app/components/markdown/transform.test.js
yarn.lock

A large portion of the changes for this are in the commonmark.js fork. The rest is mostly styling to render them as `<table><tr><td>...` is rendered in the web app.
The only really notable thing that doesn't work quite as expected is that images inside of markdown tables are rendered as links that open the image when you click on them. This is because getting images to work inside a table is incredibly difficult
commonmark changes: https://github.com/hmhealey/commonmark.js/pull/3
commonmark-react-renderer changes: https://github.com/hmhealey/commonmark-react-renderer/commit/86fa63f898802953842526c2030f3b63c5d1ae7a
https://mattermost.atlassian.net/browse/ICU-624
- Includes text changes and localization file …

ICU-624 Added markdown tables

---

android/app/build.gradle
app/mattermost.js
app/screens/settings/advanced_settings/advanced_settings.js
app/screens/settings/settings_item/index.js
app/screens/settings/settings_item/style.android.js
app/screens/settings/settings_item/style.ios.js
assets/base/config.json
assets/base/i18n/en.json
ios/bundleReactNative.sh
ios/makeSentryProperties.sh
ios/uploadDebugSymbols.sh
package.json
yarn.lock

The only real changes that we needed were to update the path of some files in node_modules and provide extra configuration during the Android build process. I also came across an odd behaviour that must've appeared in RN since the last time one of us worked on the exception handler since it was being triggered with no argument for PropType warnings, so that's been fixed.
This time, I also left in some extra Advanced Settings options to crash the app, but they're controlled by the local build config, so normal users won't see them.
https://mattermost.atlassian.net/browse/MM-9379
This PR was tested on: Nexus 5 (Android 6.0) using `make run-android`, iPhone 6 (iOS 10.3.3) using `make run-ios` and building from XCode in …

RN-9379 Updated react-native-sentry to 0.34.0

---

share_extension/ios/extension_channels.js
share_extension/ios/extension_post.js
share_extension/ios/extension_team_item.js
share_extension/ios/extension_teams.js

Fixes two issues for the iOS Share Extension.
Search for channels is now part of the TableView header so it does not dismiss the keyboard as it won't be re-rendered.
Team listing is now using TableView
https://mattermost.atlassian.net/browse/MM-9626
https://mattermost.atlassian.net/browse/MM-9627

[MM-9626 & MM-9627] iOS share fixes

---

app/selectors/post_list.js

I think this issue occurred because we ended up with multiple date lines due to an old pending post from a previous day, and then RN freaked out because we had multiple items with the same key. If I simulated that situation and switched channels, the duplicated date lines were still left on the screen
https://mattermost.atlassian.net/browse/MM-9612

MM-9612 Better handled out of order posts causing duplicate date headers

---

app/components/post_list/post_list.js

This PR fixes an issue where the `itemMeasurements` were not being ordered correctly causing the scroll to new message to be off.

Fix scroll to new message

---

app/mattermost.js
yarn.lock

This pairs up with the corresponding mattermost-redux changes to split
apart these events. For now, we still assume a configuration change when
detecting a server version change, given that the app may run with older
mattermost servers. In the future, we could fine-tine or remove this duplicate
config/license loading.
TODO: Depend on mattermost-redux changes in yarn.lock.
https://mattermost.atlassian.net/browse/MM-8604
This PR was tested on: iPhone 6 (Simulator)

MM-8604: handle SERVER_VERSION_CHANGED and CONFIG_CHANGED events

---

app/screens/options_modal/options_modal.js
app/screens/options_modal/options_modal_list.ios.js

on iOS the Cancel option in the options modal screen (ActionSheet) wasn't working, this PR fixes it

Fix iOS Options modal cancel press

---

yarn.lock

Commonmark changes here: https://github.com/hmhealey/commonmark.js/commit/bcd754c640ed8192fa959f2416f183acf9e1cfaf
Basically, it just adds a case for `reMain` to stop capturing text when it sees something that looks like an email, and then it adds a regex that looks for emails after that. We already support mailto links in the app, so no changes were needed outside of that.
https://mattermost.atlassian.net/browse/MM-9347
This PR was tested on: iOS Simulator (iPhone 6, iOS 11.2), Nexus 5 (Android 6.0.1)

MM-9347 Added email autolinking

---

app/components/post/post.js
app/components/post_body/index.js
app/components/post_body/post_body.js

Feedback was that we should be able to reply to a post by tapping on the space left to the text and below the image profile
This also fixes https://mattermost.atlassian.net/browse/MM-9768

Add reply to post handler below the profile image

---

app/components/channel_drawer/channels_list/switch_teams_button/switch_teams_button.js
app/screens/select_team/select_team.js
share_extension/android/extension_teams/team_item/team_item.js
share_extension/ios/extension_team_item.js

Switching teams was crashing the extension as the TeamIcon component is a connected component and in the iOS Share extension we do not have access to the redux store.
Also fixes the style for the team icon when there is no image

Fix team_icon to reference the pure component

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_document.js
app/components/file_attachment_list/file_attachment_icon.js
app/components/file_attachment_list/file_attachment_image.js
app/components/file_attachment_list/file_attachment_list.js
app/components/file_attachment_list/index.js

Show file attachments in one row inside an Horizontal ScrollView
Part of the 4K post limit
* iOS 11.2 iPhone 5s, iPhone 6 and iPhone X (Simulator)
* Android 7.1.1 Nexus 5 (Emulator)
Android
iOS
iPhone 5s
iPhone 6
iPhone X

Show attachments in horizontal ScrollView

---

app/components/markdown/markdown_list.js
app/components/markdown/markdown_list_item.js

We weren't specifying that the body of list items could flex, so they wouldn't shrink as we got deeper into the list
https://mattermost.atlassian.net/browse/MM-9709
This PR was tested on: iPhone 6 Simulator, iPhone X Simulator, Nexus 5

MM-9709 Fixed max width of markdown list items

---

app/components/app_icon.js
app/components/deleted_post.js
app/components/post_list/post_list.js
app/components/post_profile_picture/post_profile_picture.js
app/constants/view.js
app/screens/thread/thread.js

Disables threads with a deleted root post and displays a data-retention system message.
[MM-9545](https://mattermost.atlassian.net/browse/MM-9545)
* Android 7.1.1 emulator
* iOS 11.2 emulator (iPhone X)

MM-9545: Disables threads with deleted root post, display system message.

---

app/components/root/root.js

I'm not very pleased with this but it works, somehow the `componentDidMount` lifecycle is not being called so I changed it for this and it does work.
https://mattermost.atlassian.net/browse/MM-9921

MM-9921 Load select team screen when user has no teams

---

app/components/edit_channel_info/index.js
app/components/post_header/post_header.js

Quick fix on JS warnings on PostHeader and EditChannelInfo.
PostHeader:
Make `displayName` and `username` props not required. The logic inside the code does not really expect those to be required like, so:
```
//
if (displayName) {
name = displayName;
} else {...}
//
} else if (this.props.displayName) {
return (
<TouchableOpacity onPress={this.handleUsernamePress}>
<Text style={style.displayName}>
{this.props.displayName}
</Text>
</TouchableOpacity>
);
}
```
EditChannelInfo:
Make it accepts either string or object since the `ErrorText` expects it either of those as well
none
This PR was tested on: [iPhone 8, macOS]

Quick fix on JS warnings on PostHeader and EditChannelInfo

---

app/actions/views/post.js
app/components/post_add_channel_member/index.js
app/components/post_add_channel_member/post_add_channel_member.js
app/components/post_body/index.js
app/components/post_body/post_body.js
app/selectors/post_list.js
test/app/selectors/post_list.test.js

Add feature to add user to channel after at-mention
Jira ticket: [MM-9516](https://mattermost.atlassian.net/browse/MM-9516)
This PR was tested on: [iPhone 8, iOS 11, Android]

[MM-9516] Add feature to add user to channel after at-mention

---

yarn.lock

As reported [here](https://github.com/mattermost/mattermost-mobile/issues/1534), React Native on Android has a bug with String.prototype.startsWith that causes it to return false for strings containing some unicode characters. It's supposedly fixed in React Native 0.54, but this is easier
CommonMark changes here: https://github.com/hmhealey/commonmark.js/commit/7c20ebc1b60f5bb56c1ed9ad3239f53293278d5c
https://mattermost.atlassian.net/browse/MM-9940

MM-9940 Updated CommonMark to not use String.prototype.startsWith

---

yarn.lock

As reported [here](https://github.com/mattermost/mattermost-mobile/issues/1534), React Native on Android has a bug with String.prototype.startsWith that causes it to return false for strings containing some unicode characters. It's supposedly fixed in React Native 0.54, but since we're not backporting this to 1.7, I went with just not using startsWith.
CommonMark changes here: https://github.com/hmhealey/commonmark.js/commit/7c20ebc1b60f5bb56c1ed9ad3239f53293278d5c
https://mattermost.atlassian.net/browse/MM-9940

MM-9940 Updated CommonMark to not use String.prototype.startsWith (1.7)

---

android/app/build.gradle
app/utils/file.js
ios/Mattermost/Info.plist
ios/MattermostShare/Info.plist
ios/MattermostTests/Info.plist
share_extension/ios/index.js

The iOS Share extension is crashing on the latest release, this PR fixes it

Fix iOS Share Extension Crash and Bump build and version numbers (1.7)

---

app/components/channel_drawer/channels_list/channel_item/channel_item.js
app/components/channel_drawer/channels_list/channel_item/index.js
app/screens/channel/channel_nav_bar/channel_title/channel_title.js
app/screens/channel/channel_nav_bar/channel_title/index.js
app/screens/channel_info/channel_info.js
app/screens/channel_info/index.js
yarn.lock

Ability to Mute/Unmute a channel from the mobile app, also show the muted channels at the end of each section in the channel drawer.
https://mattermost.atlassian.net/browse/MM-9376
* iOS 11.2 (Simulators)

MM-9376 Channel mute

---

app/components/post_textbox/index.js

The prop was being passed as a string instead of a number

Fix max length prop to be a number

---

package.json
yarn.lock

Also updates the XRegExp library that's used by in our fork of commonmark.js so that we can get rid of our XRegExp fork

Move forked dependencies into Mattermost org

---

app/components/channel_drawer/channels_list/channel_item/channel_item.js

Fixes the channel item to ensure that the icon and the text are centered
https://mattermost.atlassian.net/browse/MM-10016

MM-10016 Globe icon not centered to the channel title in LHS

---

android/app/src/main/java/com/mattermost/share/RealPathUtil.java
android/app/src/main/java/com/mattermost/share/ShareModule.java

Fixes a crash when trying to share content from a custom keyboard (SwiftKey in this case was used to test) and also removes the temp files from the cache dir if there were some created while sharing content.
Fixes #1532 
* Android 7.1.1 Emulator

Fix share from SwiftKey Keyboard and clear temp files

---

app/screens/channel_members/channel_members.js
app/screens/channel_members/index.js

Filter out deactivated user when viewing channel members
Jira ticket: [MM-10055](https://mattermost.atlassian.net/browse/MM-10055)
This PR was tested on: [Simulator iPhone 6/11.2]

[MM-10055] Filter out deactivated user when viewing channel members

---

app/components/at_mention/at_mention.js
app/components/at_mention/index.js

This PR makes the rendering of at-mentions to follow the teammate display name setting.
https://mattermost.atlassian.net/browse/MM-9575

Render at-mentions by the teammate name display

---

app/components/post_list/with_layout.js
app/components/profile_picture/profile_picture.js

After submitting a post on a newly rendered channel that has the new messages indicator the channel was being scrolled to the indicator once more, the reason being that the `PostWithLayout` component was re-creating the post component and called the onLayout function that was causing the postlist to scroll after it updated.
This PR prevents the re-creation of the post component thus fixing two thing:
1. The post list is not re-rendering the items that do not need to be re-rendered
2. The post list won't scroll if not needed.
https://mattermost.atlassian.net/browse/MM-10236

Fix post with layout to not create new post components

---

package-lock.json
package.json

This is to make our link parsing slightly more forgiving and GitHub-like since we don't currently allow links containing periods followed by punctuation like https://example.com/?text=Test+phrase.+Please+ignore
This is based off https://github.com/mattermost/mattermost-mobile/pull/1602
Commonmark changes here: https://github.com/mattermost/commonmark.js/commit/c9c29834005af6eedd1a979d913b75e34f16a83b
https://mattermost.atlassian.net/browse/MM-10180

MM-10180 Better handle characters after periods in URLs

---

app/components/channel_drawer/channels_list/channel_item/channel_item.js

The badges were out of the view cause the text of the channel display name was taking 100% of the view
https://mattermost.atlassian.net/browse/MM-10299

Fix mention badges in channel drawer

---

package-lock.json
package.json

Use last mattermost-redux version to fix a permissions problem showing edit/delete links in team info
[MM-10298](https://mattermost.atlassian.net/browse/MM-10298)
This PR was tested on: [Android, 8.0.0]

MM-10298: Fix the ability to edit or delete a channel (new permission system)

---

package-lock.json
package.json

Commonmark changes here: https://github.com/mattermost/commonmark.js/commit/21742b9d51070b6abba82d88590a0c51ee552a47
The gist of those changes is that we're making `reMain` more efficient by making it look for what only might start an email instead of what does start an email. By doing that, it does less backtracking when it sees something that looks like an email but doesn't have an at sign. It still backtracks a fair bit which isn't ideal, but it's more than fast enough for the length of text that we support. A better fix would be to wait until we find an at sign and then backtrack to find which text is part of the email address, but that's not really possible with how this is written.

Improved performance while autolinking emails

---

android/app/src/main/java/com/mattermost/share/RealPathUtil.java
android/app/src/main/java/com/mattermost/share/ShareModule.java
app/utils/file.js
share_extension/android/extension_post/extension_post.js

When sharing a file that does not have an extension on Android was uploading the file without extension and with mime type `application/octet-stream`, with this fix we are retrieving the file extension and mime type so the file is correctly uploaded

Fix Android sharing files without extension

---

app/components/markdown/markdown_link/markdown_link.js

If SiteURL isn't configured, its value will be undefined causing escapeRegex to throw an error

Fixed Markdown links when SiteURL isn't configured

---

app/components/post_attachment_opengraph/post_attachment_opengraph.js
package-lock.json
package.json

Some pages (like a GitHub PR with no description set) include an empty OpenGraph description, so this null check prevented the OpenGraph data for those pages from being saved into the store and eventually shown in a preview
Redux PR: https://github.com/mattermost/mattermost-redux/pull/478
https://mattermost.atlassian.net/browse/MM-10360

MM-10360 Render OpenGraph previews for pages with an empty description

---

app/components/post_attachment_opengraph/post_attachment_opengraph.js

The previous version didn't work because the OpenGraph library returns an empty description for any valid link.
I swear this is the last time you'll have to review basically the same change.
https://mattermost.atlassian.net/browse/MM-10360

MM-10360 Only show link previews if they have a url defined

---

app/components/post_attachment_opengraph/post_attachment_opengraph.js

Fix for an issue introduced in https://github.com/mattermost/mattermost-mobile/commit/3b33b51f11349ba7fd22f9ce39d7fd1879670aa5 where an empty string is rendered outside of a <Text> node causing RN to crash.

Fixed empty OpenGraph previews from trying to render an empty string

---

app/screens/flagged_posts/flagged_posts.js
app/screens/recent_mentions/recent_mentions.js
app/screens/search/search.js
package-lock.json
package.json

The code to prevent duplicate flagged posts is in the mattermost-redux lib which this PR is updating but it also includes keys for the date components to avoid render warnings
https://mattermost.atlassian.net/browse/MM-10333

Prevent duplicate flagged posts

---

app/store/middleware.js

Add roles to the cleanup middleware to avoid inconsistences in the store after
IOS application stop and restore.
[MM-10454](https://mattermost.atlassian.net/browse/MM-10454)
This PR was tested on: [One Plus 5 (Android 8.1.0)]

MM-10454: Adding roles to the cleanup middleware

---

app/store/middleware.js
app/store/middleware.test.js

When the application was suspended while a post was in-flight, the subsequent restoration would duplicate the `effect` of the redux-offline action. This turned out to be due to a bug in the middleware which returned a spurious `"persist/REHYDRATE"` action type when the incoming action had actually been `ViewTypes.DATA_CLEANUP`.
https://mattermost.atlassian.net/browse/MM-10460
This PR was tested on: iOS Mobile Simulator

MM-10460: avoid double post on restore

---

app/actions/views/channel.js
package-lock.json
package.json

Include "id" to data for UserTypes actions - RECEIVED_PROFILE_IN_CHANNEL
Note: Will update commit of mattermost-redux once corresponding change is merged - https://github.com/mattermost/mattermost-redux/pull/499.
Jira ticket: [MM-10455](https://mattermost.atlassian.net/browse/MM-10455)
This PR was tested on: [iOS 11.2 iPhone 8 simulator]

Include "id" to data for UserTypes actions - RECEIVED_PROFILE_IN_CHANNEL

---

package-lock.json
package.json

Fixed the react-native-image-gallery to be able to perform zoom and panning the image, also fixes the scrolling between images and files to be smoother.
Actual fixes: https://github.com/enahum/react-native-image-gallery/commit/8a60c303a130b204bc717ebb67d6898deb3577ae and https://github.com/enahum/react-native-image-gallery/commit/a98b1051e94f5a394541ca1ff9b15e2c9ffed84f
https://mattermost.atlassian.net/browse/MM-10302

Fix image preview zoom & scrolling jumps

---

app/components/announcement_banner/__snapshots__/announcement_banner.test.js.snap
app/components/announcement_banner/announcement_banner.js
app/components/announcement_banner/announcement_banner.test.js
app/components/announcement_banner/index.js

Fix JS error on announcement banner when no license is set
none
This PR was tested on: [iPhone 8 simulator]

Fix JS error on announcement banner when no license is set

---

app/actions/views/channel.js
app/actions/views/more_dms.js

This PR fixes an issue where auto closed DMs would not show if they were reopened.
The issue occurs when the following is true:
- Automatically close DM's set to true
- Try to start a DM with a user who's DM's have been automatically closed
This PR updates the `CATEGORY_CHANNEL_OPEN_TIME` value for the channel to ensure that it is shown if the user has auto close DMs set to true.

Fix issue where auto closed DMs would not show again

---

app/actions/views/login.js
app/actions/views/login.test.js

We made a change to use cached credentials from Keychain/KeyStore instead of redux after rehydration to either route to `SelectServer` or `Channel`.  This works once the credentials are stored.  Unfortunately that was only happening after redux rehydration.
So now this change stores the credentials immediately after login.

Save credentials immediately after login

---

package-lock.json

Fix bundling failed with "mime-db" error.
```
error: bundling failed: Error: Unable to resolve module `mime-db` from `/mattermost-mobile/app/utils/file.js`: Module `mime-db` does not exist in the Haste module map
```
Not sure what happened with my latest upgrade to redux but this one works for me. 
Build successfully completed for iOS and Android.
None but reported here https://pre-release.mattermost.com/core/pl/g9otpe1mafgwuby88b8uzhdahe

Fix bundling failed with "mime-db" error

---

app/components/channel_loader/channel_loader.js
app/components/post_body/post_body.js
package-lock.json

On Android some posts were taking too long but where shown as a normal post instead of a Long Post, with this fix we ensure that if the posts is longer that 1.2 the device height then we treat it as a long post.
Also included a small fix for the channel loader background color.
https://mattermost.atlassian.net/browse/MM-10680

Fix long post detection

---

app/components/combined_system_message/__snapshots__/combined_system_message.test.js.snap
app/components/combined_system_message/__snapshots__/last_users.test.js.snap
app/components/combined_system_message/combined_system_message.js
app/components/combined_system_message/combined_system_message.test.js
app/components/combined_system_message/index.js
app/components/combined_system_message/last_users.js
app/components/combined_system_message/last_users.test.js
app/components/post_body/post_body.js
package-lock.json
package.json

- Fix missing username by supporting backward compatibility on `addedUsername` props when adding user to the channel or team
- Fix styling issue of combined system messages
Jira ticket: 
- [MM-10727](https://mattermost.atlassian.net/browse/MM-10727)
- [MM-10755](https://mattermost.atlassian.net/browse/MM-10755)

[MM-10727 and MM-10755] Fix missing username and styling issue of combined system messages

---

app/screens/more_dms/more_dms.js

Fix DM's channel displayname (instead of "Someone") after creating a DM.
Note: I've attempted to add test but I'm getting weird `ReferenceError: self is not defined` after mocking `react-native-fetch-blob/fs`.  I may just deal with this separately.
Jira ticket: [MM-10646](https://mattermost.atlassian.net/browse/MM-10646)

[MM-10646] Fix DM's channel displayname (instead of "Someone") after creating a DM

---

app/store/index.js

The entities object being saved in the device after doing a JSON.stringify was not saving the javascript sets correctly, this PR converts those Sets into Arrays
https://mattermost.atlassian.net/browse/MM-10759

Fix change team and channel in iOS share extension

---

app/components/markdown/markdown_image/markdown_image.js

Inline images in long post were being overlapped
https://mattermost.atlassian.net/browse/MM-10720
This PR was tested on: iPhone and Android

Fix inline images in long posts

---

app/components/markdown/transform.js
app/components/markdown/transform.test.js

RN goes against spec and specifically disallows the previous `Object.assign(Object.create(Reflect.getPrototypeOf(node)), node)`, so we just need to manually create a new Node and copy the fields. Behaviour should be identical to what it was before

Fixed dev-mode error relating to adjacent images

---

app/components/channel_drawer/teams_list/teams_list_item/teams_list_item.js

Fixes the border radius on Android and makes sure the background is always white for the team icons.
https://mattermost.atlassian.net/browse/MM-10799

Fix Team icon background and radius in team lists

---

app/utils/network.js

Related to the OOM Error, this avoids tricking logic that depends on `networkChangeListener` to still think the app is online.
1.  The app immediately sets the state in redux as offline/online
2. Afterwards, makes a call to the server if a connection exists
3. If there's no connection a timeout exists so the call doesn't take the entirety of the app being offline.
https://mattermost.atlassian.net/browse/MM-10773

Ping server after setting app offline/online.  Also include timeout

---

app/screens/more_channels/more_channels.js
package-lock.json
package.json

Remove converted channel (into private) from "MoreChannels" screen of  joinable channels
Jira ticket: [MM-10519](https://mattermost.atlassian.net/browse/MM-10519)
BEFORE:  Converted channel is not removed from the list.  Clicking the converted channel gets permission error (since that's already a private channel).
AFTER:
Converted channel is automatically removed from the list.
(With search term)
If with search term, remaining channel/s is still filtered with the term.

[MM-10519] Remove converted channel (into private) from "MoreChannels" screen of  joinable channels

---

app/screens/entry/entry.js
app/screens/notification/notification.js

Fixes a crash in iOS cause of the change in the way the notification is sent and fixes the way the in-app notification is parsed to be presented
**Important Note:** iOS 1.8 will crash if a notification is sent while the app is in the foreground with servers 5.0+

Fix inApp notification handler

---

app/components/post_body/post_body.js

Adds 'Delete' long-press action for system messages.
[MM-10819](https://mattermost.atlassian.net/browse/MM-10819)
n/a
iPhone 6 iOS 11.4 (emulated)

MM-10819: Adds 'Delete' long-press action for system messages.

---

app/actions/views/channel.js
app/components/post_list/post_list.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js

For a FlatList, `onEndReached` doesn't trigger before the list gets enough content to scroll, so we need to manually trigger it to load more posts. This may be called repeatedly if there's a lot of people joining and leaving the channel, but `loadMorePosts` is throttled by the debounce function, so it shouldn't have a huge impact in most cases.
https://mattermost.atlassian.net/browse/MM-10815

MM-10815 Load more posts when post list is under 1 screen long

---

app/screens/sso/sso.js

This PR parses the SAML errors and display them in a friendly way, also makes use of a header that in combination with https://github.com/mattermost/mattermost-server/pull/8943 will make sure that the response for mobile SAML login is always in JSON format.
Also fixes some issues with the JS executed inside the webview for onelogin
https://mattermost.atlassian.net/browse/MM-10905
* Android 7.0 Emulator
* iOS 11.4 Simulator

Render SAML json errors and include special header in webview requests

---

app/components/combined_system_message/combined_system_message.js
app/components/combined_system_message/combined_system_message.test.js
app/components/combined_system_message/index.js
package-lock.json
package.json

The redux changes filter out combined system messages that don't relate to the current user while this makes combined system messages for the current user only show the parts that affect the current user. This only affects users that have join/leave messages turned off in Account Settings.
User adding and removing people:
User being added and removed:
Redux PR: https://github.com/mattermost/mattermost-redux/pull/532
https://mattermost.atlassian.net/browse/MM-10888

MM-10888 Hide parts of combined system messages that don't affect the current user

---

app/components/combined_system_message/combined_system_message.js
app/components/combined_system_message/combined_system_message.test.js
app/components/combined_system_message/index.js
package-lock.json
package.json

Fix memory leak on combined_system_message component
- by removing async call which sometimes resolves and sets state even after the component is unmounted
- eliminating undefined user profile (of `actions.getProfilesByIds` and/or `actions.getProfilesByUsernames`) when server is unreachable (network problem) or the server returns an error by letting redux to handle such user's state.
- [UPDATE] only get missing profiles
None but was reported on pre-release:
- https://pre-release.mattermost.com/core/pl/ofbk3xz7jp8u38ckm78usbe5ih
- https://pre-release.mattermost.com/core/pl/ck75xrjispd8mdn4h9edzw1y8c
This PR was tested on: [Primarily Android emulator, and iOS simulator]

Fix memory leak on combined_system_message component

---

app/fetch_preconfig.js
app/mattermost.js
app/screens/permalink/permalink.js
package-lock.json
package.json

Replaces the default implementation of Fetch with RNFetchBlob (also used for CBA on iOS)
This PR also fixes a memory leak in the permalink screen

Replacing fetch with RNFetchBlob

---

app/components/post_textbox/post_textbox.js
app/components/quick_text_input.js

This is porting over the QuickInput from the web app to hopefully improve the behaviour of the post textbox slightly.
https://mattermost.atlassian.net/browse/MM-10822

MM-10822 Change post textbox to only be partially connected

---

app/components/channel_drawer/channels_list/channel_item/channel_item.js
app/components/channel_drawer/channels_list/channels_list.js
app/components/channel_drawer/channels_list/switch_teams_button/switch_teams_button.js
app/components/channel_drawer/teams_list/teams_list_item/teams_list_item.js
app/screens/channel/channel_nav_bar/channel_drawer_button.js

The unread badge background is always white and does not use the defined theme's "mentionBg". If the "mentionColor" is white the badge will be completely white with no number.
This PR was tested on: [Nexus 5 API 24, Android 7.0 (Google APIs)
Before:
After: (my mentionBg is #da202d)

Unread badge background is always white

---

app/screens/select_server/select_server.js

This complements the subpath epic changes in the server and webapp to allow RN to connect to Mattermost when hosted at a `/subpath`.
https://mattermost.atlassian.net/browse/MM-10990

MM-10990: allow a pathname when selecting a server

---

app/screens/user_profile/index.js
app/screens/user_profile/user_profile.js

Add option to send message via user profile even coming from DM channel, by just checking whether the user (on profile) is not the current user.
(Note:  I tried adding test but I kept getting error like `ReferenceError: self is not defined`.  Need to figure out separately.)
Jira ticket: [MM-10817](https://mattermost.atlassian.net/browse/MM-10817)

[MM-10817] Add option to send message via user profile even coming from DM channel

---

app/app.js

The first time the user opens the app after upgrading from 1.8 to 1.9 the app didn't recognized that the user was logged in and presented the select server screen instead.
This PR makes sure that case is handled when the user upgrades.
https://mattermost.atlassian.net/browse/MM-10993

Fix user being "logged out" after upgrading

---

app/components/search_bar/search_bar.android.js

Fixes android issue of search input field population with in: and from: keywords
[MM-11006](https://mattermost.atlassian.net/browse/MM-11006)
This PR was tested on: [Nexus emulator]

Fix android seach field population for in and from keywords

---

app/utils/sentry/middleware.js

I don't know what is dispatching an invalid action, but the warnings should help us track it down later
https://mattermost.atlassian.net/browse/MM-11018

MM-11018 Provide default message for Sentry breadcrumbs (1.9.2)

---

app/components/attachment_button.js

The file was not being found as the document picker returned the file path as encoded, this decodes the file path so the file is actually found when uploading it
https://mattermost.atlassian.net/browse/MM-11019

Fix uploading files with blank spaces in the filename

---

app/components/markdown/markdown_table_cell/markdown_table_cell.js

I had implemented most of this except for actually applying the right styles to the text. Also, the `heading` style wasn't used since it was implemented a different way, so I removed it.
https://mattermost.atlassian.net/browse/MM-10325

MM-10325 Add cell alignment to markdown tables

---

app/screens/image_preview/downloader.ios.js
app/screens/image_preview/video_preview.js

When uploading a video file it is not possible to playback the file unless the cache is cleaned as the object contains a `localPath` property, this PR fixes that.
https://mattermost.atlassian.net/browse/MM-11020

Fix opening video when file has localPath set

---

android/app/build.gradle
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties

This is something I worked on during OOM issue.
Upgrading Gradle helps significantly in build times for the native Android app.
Release build still takes a while because of the way it bundles the JS code.
The gain is in debug/incremental builds.

Upgrade to Gradle 3.0

---

android/app/src/main/java/com/mattermost/share/ShareModule.java

Set the default mime type for images to jpeg and videos to mp4 when the Android share extension cannot determine the correct mime type
https://mattermost.atlassian.net/browse/MM-11050

Set Android share extension default mime type for images and videos

---

assets/base/i18n/en.json
ios/MattermostShare/SessionManager.h
ios/MattermostShare/SessionManager.m
ios/MattermostShare/ShareViewController.m
share_extension/ios/extension_post.js

Fixes iOS Share extension crash when tapping to change the channel when channels haven't loaded yet.
Also keeps the extension open until the message is posted, in case of an error it gives feedback to the user.
https://mattermost.atlassian.net/browse/MM-11049

Fix iOS Share extension crash

---

app/actions/views/root.js
app/utils/push_notifications.js

It was not possible to get the posts when the app is closed, it has to be done in native code and there is no bridge to send it back to the js code, so this PR attempts to get the posts as soon as possible
https://mattermost.atlassian.net/browse/MM-10392

Fetch posts when receive push notifications as soon as possible

---

app/components/post_body_additional_content/post_body_additional_content.js

The parser to extract the time was returning a blank string instead of 0 causing a crash for those youtube links without time on iOS
https://mattermost.atlassian.net/browse/MM-11095

Fix youTube crash on iOS providing the right prop type

---

app/screens/channel_add_members/channel_add_members.js

Add missing loading screen when the Add Members to channel screen is loading
* Add showNoResults state to custom_list
[MM-11035](https://mattermost.atlassian.net/browse/MM-11035)
This PR was tested on: [Ios emulator, Android emulator Pixel 7.1]

MM-11035 Add loader when the Add Members to channel screen is loading

---

ios/MattermostShare/SessionManager.m
share_extension/ios/extension_post.js

Fixed crash for the iOS Share Extension when the cba certificate is not present.
Also this PR fixes the share extension when sharing files from the files app, the fix consists in decoding the uri for the file.

MM-11098 Fix ios extension crash and ability to share from files app

---

app/components/post_textbox/post_textbox.js
app/components/quick_text_input.js
app/components/search_bar/search_bar.android.js
app/components/text_input_with_localized_placeholder.js
app/screens/edit_profile/edit_profile_item.js
app/screens/login/login.js
app/screens/select_server/select_server.js
share_extension/android/extension_post/extension_post.js
share_extension/ios/extension_post.js

The cause of the issue with Chinese/Japanese keyboards is that setting either the value or defaultValue prop for a TextInput or using `setNativeProps` to change that value breaks the autocomplete part of those keyboards. To get around this, the new version of QuickTextInput doesn't use either of those props and only calls `setNativeProps` when the value doesn't match the current value of the text input (as stored in `this.storedValue`).
https://mattermost.atlassian.net/browse/MM-11116
https://github.com/mattermost/mattermost-mobile/issues/1816
https://forum.mattermost.org/t/ios-mobile-app-1-9-0-doesn-t-work-with-japanese-keyboard/5187
This PR was tested on: iOS Simulator, currently confirming this still works on Android

MM-11116 Re-added updated QuickTextInput component to work around RN issue

---

app/store/index.js

As part of my other PR, Eric and I discussed having the announcement banner dismiss permanently when you dismiss it instead of the current behaviour where it comes back after you close and re-open the app.
https://mattermost.atlassian.net/browse/MM-11139

MM-11139 Remember announcement banner dismissal after app closes

---

app/components/quick_text_input.js

This is forward-porting (if that's even a word) part of https://github.com/mattermost/mattermost-mobile/pull/1871 into 1.10
https://mattermost.atlassian.net/browse/MM-11116

MM-11116 Work around setNativeProps not working for TextInputs (1.10)

---

app/screens/permalink/index.js
app/selectors/post_list.js

The reason the previous fix for the issue wasn't working sometimes is that it didn't show the error message when the user deleted the post from their own app, leaving a "(message deleted)" message in the redux store. Since that post existed, we displayed it instead of the error message.
I also fixed some weird code that I couldn't identify that hid any of the current user's posts that were marked as deleted, so the current user couldn't see their own posts as "(message deleted)" if another user deleted them. I couldn't identify the cause of that since it was added in the PR that split mattermost-redux into its own repo, so I assume it was added by accident.
https://mattermost.atlassian.net/browse/MM-10826

MM-10826 Show error when viewing permalink for locally deleted post

---

app/components/quick_text_input.js

I also went through and checked everywhere I could find us using refs on a TextInput to make sure there weren't any other methods of QuickTextInput that were missing
https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/597592442/

Add setNativeProps to QuickTextInput (1.9)

---

app/components/quick_text_input.js

I also went through and checked everywhere I could find us using refs on a TextInput to make sure there weren't any other methods of QuickTextInput that were missing
https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/597592442/

Add setNativeProps to QuickTextInput 

---

app/components/sidebars/main/channels_list/filtered_list/filtered_list.js

On the Jump to Channel search drawer now the unread channels are being bolded.
I do not like this hack as I think the whole component should be refactored, but for now I think this is more than enough
https://mattermost.atlassian.net/browse/MM-11033

Bold unread channels in jump to channel

---

app/components/announcement_banner/__snapshots__/announcement_banner.test.js.snap
app/components/announcement_banner/announcement_banner.js
app/components/announcement_banner/announcement_banner.test.js
app/components/announcement_banner/index.js
app/components/channel_link/channel_link.js
app/components/markdown/markdown.js
app/components/remove_markdown.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/expanded_announcement_banner/expanded_announcement_banner.js
app/screens/expanded_announcement_banner/index.js
app/screens/index.js
assets/base/i18n/en.json

Based on the new design, the announcement banner strips all Markdown from the banner when it's collapsed, but the new expanded view will have full Markdown support. There's an outstanding design issue where you can't permanently dismiss the banner on mobile that we want to address before merging this.
https://mattermost.atlassian.net/browse/MM-10012

MM-10012 Added Markdown rendering to expanded announcement banner

---

app/screens/more_dms/more_dms.js

On search success and other user/s are selected already, remove current user first before profile match filtering
Jira ticket: [MM-11072](https://mattermost.atlassian.net/browse/MM-11072)

[MM-11072] On search success and other user/s are selected already, remove current user first before profile match filtering

---

ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/AppDelegate.m

The Keychain on iOS does not get cleared when the app is uninstalled but the `NSUserDefaults` does, so this PR uses `NSUserDefaults` to keep track if the app is **FirstRun** so it removes the credentials stored in the app if any.
In the case the user is still logged in and the app is just upgrading the user will stay logged in, but if the app was uninstalled then the user is being forced to the select server URL.
https://mattermost.atlassian.net/browse/MM-11159

Clear iOS Keychain data on first run

---

app/components/post_header/post_header.js

When we increased the tappable area of that icon, it pushed the post username and timestamp down. Using a negative margin fixes that.
https://mattermost.atlassian.net/browse/MM-11203
The red area represents is the tappable area

MM-11203 Adjust reply icon margins to not affect other components

---

app/components/post_textbox/post_textbox.js

Reverting QuickTextInput to use TextInput on Android, the QuickTextInput was causing the Android's input lose focus when submitting a post, the same is not happening on iOS.
It seems that the reason for the QuickTextInput existence is actually to properly fix iOS input in Chinese/Japanese (this after talking to @hmhealey)
Anyway I believe once this is merged QA should verify and validate that, if that's not the case and we start seeing issues with Japanese/Chinese on Android then we should consider trying a different approach.
https://mattermost.atlassian.net/browse/MM-11240

Use TextInput instead of QuickTextInput on Android

---

app/screens/settings/notification_settings_email/notification_settings_email.android.js
app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
app/screens/settings/notification_settings_email/notification_settings_email_base.js

Fix email preference to not change value on cancel.
(Tested working on save as well.)
Jira ticket: [MM-11290](https://mattermost.atlassian.net/browse/MM-11290)
GH comment: https://github.com/mattermost/mattermost-mobile/pull/1909#issuecomment-403808814
This PR was tested on: [mostly on Android emulator but also tested on iOS simulator]

[MM-11290] Fix email preference to not change value on cancel

---

app/components/formatted_markdown_text.js

Don't throw error when passing HTML to `FormattedMarkdownText` component, render it escaped and print console warning.
n/a
n/a
iPhone 6 emulated.

Render escaped HTML in FormattedMarkdownText; no throw error.

---

app/utils/image_cache_manager.js

I haven't been able to track down the source of the undefined string here, so I added some defensive code instead. The only way `undefined` could be passed into that function is through `ImageCacheManager.cache` and the only time that I can find where that could happen is if a `ProgressiveImage` is created with a `thumbnailUri` prop but no `imageUri`, but we never do that outside of some weird state transition.
https://mattermost.atlassian.net/browse/MM-11324
https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/585744399
https://sentry.io/mattermost-mr/mattermost-mobile-ios/issues/591176259

MM-11324 Added defensive code to hashCode function

---

app/screens/long_post/index.js

`post` can sometimes be undefined
https://mattermost.atlassian.net/browse/MM-11323
https://sentry.io/mattermost-mr/mattermost-mobile-ios/issues/593176730
https://sentry.io/mattermost-mr/mattermost-mobile-android/issues/601120888

MM-11323 Added defensive code in LongPost makeMapStateToProps

---

Makefile

Output from procps' ps with -e only produces the process name, so grepping for "cli.js start" fails every time. This change adds (POSIX-compliant) -f to all ps calls to get the full command. AWK print parameter is adjusted accordingly where needed.
[Issue #1359](https://github.com/mattermost/mattermost-mobile/issues/1359) resulted in [PR #1370](https://github.com/mattermost/mattermost-mobile/pull/1370), but only addressed the stop: target. The changes here address the rest of the ps calls the same way.

Add -f to all ps calls in Makefile

---

app/components/sidebars/settings/settings_sidebar.js

The Android back button was always returning true cause it was wrongly handled by the settings drawer.
https://mattermost.atlassian.net/browse/MM-11381

Fix closing app with Android Back Button

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

On Android every time a push notification was received the pending intent was storing and updating the bundle for all channels, with this PR the bundle is stored and update but on a per channel basis, so notifications from two different channels will have two different pending intents for replying.
https://mattermost.atlassian.net/browse/MM-11309

Fix reply pending intent per channel

---

app/actions/views/root.js
app/components/post_body/index.js
app/components/reactions/index.js
app/components/root/root.js
app/screens/permalink/permalink.js
app/screens/search/channel_display_name/index.js

Can't exactly pin point what's causing the `undefined is not an object (evaluating 'e.channel_id')` so I just add extra protection to those channel/object followed immediately by accessing its "channel_id" field.
Jira ticket: [MM-11494](https://mattermost.atlassian.net/browse/MM-11494)

[MM-11494] Add extra protection to those channel/object followed immediately by accessing its "channel_id" field

---

app/actions/views/channel.js
app/actions/views/root.js
app/components/reactions/index.js

Can't exactly tell the root cause of`Undefined is not an object (evaluating 'y.team_id')` so I just added protection in accessing ".team_id" field when it's immediately accessed after the object is created.
Jira ticket: [MM-11492](https://mattermost.atlassian.net/browse/MM-11492)

[MM-11492] Add protection in accessing ".team_id" field when it's immediately accessed after the object is created

---

android/app/src/main/java/com/mattermost/share/RealPathUtil.java
assets/base/i18n/en.json
share_extension/android/extension_post/extension_post.js

This PR changes the way the temporary files are created when using the share extension in a way that we can define the filename instead of having a random id.
Also the problem that we were seeing is that the use of `getLastPathSegment` was returning a decoded string and sometimes appended a `\n` new line to it, RNFetchBlob was failing cause it trims the new lines before checking for the existence of the file or getting the stats thus the file not found error.
More so now we handle the null or file not founds gracefully and we present the user with a message.
Note: the above will happen when trying to share a contact instead of a file.
https://mattermost.atlassian.net/browse/MM-11490

Fix Android share extension and better handle errors

---

app/components/combined_system_message/index.js
app/components/sidebars/main/channels_list/switch_teams_button/index.js
app/components/sidebars/settings/index.js
app/screens/settings/notification_settings/index.js
app/screens/timezone/index.js

Can;t exactly pinpoint the reason why getting this error `undefined is not an object (evaluating 'c.id')`.  So just add protection (empty object) when immediately accessing id after declaring an object.
Jira ticket: [MM-11491](https://mattermost.atlassian.net/browse/MM-11491)

[MM-11491] Add protection (empty object) when accessing id after declaring an object.

---

.eslintrc.json
app/mattermost_managed/mattermost-managed.android.js
app/mattermost_managed/mattermost-managed.ios.js
app/utils/error_handling.js
app/utils/sentry/index.js
index.js

First part of an attempted fix for https://mattermost.atlassian.net/browse/MM-11477. This'll catch any uncaught promise rejections that we can handle and turn them into Sentry breadcrumbs so that we can see them when other errors are logged, although it won't prevent Sentry from handling them on it's own.
Also adds some defensive code to the error handler to prevent errors that happen in dev mode with the error handler enabled.

MM-11477 Attempt to capture uncaught redux errors as Sentry breadcrumbs

---

app/utils/sentry/index.js

Fixes a typo in the code to set `breadcrumb.message` and updates how we parse `breadcrumb.data.url` so that we aren't capturing part of the Site URL

MM-11477 Fix error in breadcrumb generation and parse URL correctly

---

app/screens/sso/sso.js

When logging in using SAML or OAuth the cookies that are set in the WebView are kept after a logout making it so that when the user tries to re-login it will use the past entered credentials as they are kept in the Cookies.
This PR makes sure we clear all the cookies before loading the WebView so they need to enter their credentials again.
https://mattermost.atlassian.net/browse/MM-11115

Clear Cookies before login in with SSO

---

app/app.js

Mattermost mobile app crashes on iOS 9.3.
Here's debugger log when app crashes (It crashes both simulator and real iPhone, but real iPhone does not display this error screen because it builds production mode)
I just added `babel-polyfill` to fix this crash issue. 
(`babel-polyfill` already contained in this project via dependency tree)
After this PR
Github #1988 
This PR was tested on
* Apple iPad Pro 12.9 (2nd generation), iOS 11.4
* Apple iPhone 6, iOS 9.3
* Apple iPhone 5, iOS 11
* Samsung Galaxy S7 Edge, Android 7.0
I already uploaded in summary.
cc : @enahum

Fix app crashes on iOS 9.3

---

app/actions/views/edit_profile.js
app/components/profile_picture/index.js
app/components/profile_picture/profile_picture.js
app/constants/view.js
app/reducers/views/index.js
app/reducers/views/user.js
app/screens/edit_profile/edit_profile.js
app/screens/edit_profile/index.js
app/selectors/views.js

Use profile image from local after editing a profile image.
The way it works is:
- set profile image to local views (`state.views.user.profileImageUri`) whenever the user uploads a profile image
- use that profile image as profile picture for every post of the user
- when the user's picture URL is available, it replaces the profile picture using that URL and clear the profile image in local views/store (`state.views.user.profileImageUri`)
Note:  ~~In the screen capture below, you'll notice that the profile picture is being used in the post messages as soon as the user is taken out of the EditProfile screen.  However, once the picture URL becomes available, there's a short flicker during transition in switching profile image from local view to picture URL. Not sure what's the better …

[MM-11613] Use profile image from local after editing a profile image

---

app/utils/push_notifications.js

Sometimes there seems to be a race condition when bringing the the app to the foreground after tapping a push notification so the user is not being sent to the right channel, I've added a setTimeout around the call to `loadFromNotification` so it is executed in the next cycle.
https://mattermost.atlassian.net/browse/MM-11729

Add a timeout to avoid race conditions when opening the app from a push notification

---

app/components/sidebars/main/channels_list/channel_item/index.js

The current implementation was checking if `channel.delete_at !== 0` and just because we do build some fake `channels` and do not set the value for `delete_at` we had that the condition was returning **true** when evaluating `undefined !== 0`, I changed it so it checks that the value fo deleted at is grater than 0

Fix Jump to Channel DMs not showing

---

app/components/message_attachments/message_attachment.js

Somehow the clipping subviews on Android was causing the rest of the post not to display on screen
https://mattermost.atlassian.net/browse/MM-11719

Fix long message not displaying for message attachments in android

---

app/actions/device/index.js

While doing some testing I came across the use case that when the app opened and you did not have a connection to the server the offline indicator was showing correctly but when reconnecting manually the redux-offline state wasn't updated nor the online indication in the client so no request could be made, this PR fixes that.

Fix network change status

---

app/components/profile_picture/profile_picture.js

Set the user profile camera icon background to use the `theme.centerChannelBg` instead of `white`.

Make profile camera icon use theme.centerChannelBg for background

---

app/components/post_add_channel_member/post_add_channel_member.js
app/components/post_body/post_body.js

Makes the add user system message use the text styles from the theme.
Without theme text styles:
With theme text styles:

Make post_add_channel_member follow theme text style

---

app/store/index.js

After a user clears their cache, settings like Timezone that depend on a specific server version do not show until the user kills the app and restarts. This PR solves that issue by keeping the serverVersion around during the cache clear.

Keep server version after cache clear

---

app/screens/more_dms/more_dms.js

When opening the more_dms modal screen if `this.props.config.RestrictDirectMessage !== General.RESTRICT_DIRECT_MESSAGE_ANY` a blank screen is shown instead of a list of users(most noticeable after a cache clear). This is because the request fails due the `currentTeamId` not being passed in. This PR solves that issue by making sure that the teamId is passed to the `getProfilesInTeam` call.

Make sure team is passed to initial getProfilesInTeam call

---

app/components/post_body/index.js

Disallow in the interface to react to any archived channel. (The remove
reaction part was already implemented).
[MM-11270](https://mattermost.atlassian.net/browse/11270)
This PR was tested on: [Android 8.1]

MM-11270: Disallow to react to posts in archived channels

---

app/fetch_preconfig.js
app/screens/select_server/select_server.js
app/screens/sso/sso.js
app/utils/url.js
app/utils/url.test.js

This PR does a few things
1. When connecting to a server if there is no protocol we will try to connect first using `https` and then `http`
2. When connecting to a server using the protocol `http` we will try to first connect with `https`
3. SSO login will get the cookie based on the last redirected URL thus getting rid of the `{status: "OK"}` message that was preventing the login
4. Just in case we are going to handle `http` to `https` redirection when connecting to a server with `Forward80to443` enabled
https://mattermost.atlassian.net/browse/MM-11587
https://mattermost.atlassian.net/browse/MM-11778

Gracefully handle http and https redirection

---

app/components/post_attachment_opengraph/post_attachment_opengraph.js
package-lock.json
package.json

mattermost-redux will no longer save the OpenGraph data if it isn't valid, so we don't need to check it in the render function
Required redux changes: https://github.com/mattermost/mattermost-redux/pull/619
https://mattermost.atlassian.net/browse/MM-11449

MM-11449 Show OpenGraph previews for pages with any of the required fields

---

share_extension/android/extension_channels/extension_channels.js
share_extension/android/extension_post/index.js
share_extension/ios/extension_channels.js
share_extension/ios/extension_post.js

Show only non-archived channels on Share, and if you share being in a
archived channel, the proposed channel become Town Square instead of
your current channel.
[MM-11718](https://mattermost.atlassian.net/browse/11718)
This PR was tested on: [One Plus 5, Android 8.1] 

MM-11718: Show only non-archived channels on Share

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyService.java
app/components/channel_intro/channel_intro.js
app/components/channel_intro/index.js
app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js
package-lock.json
package.json

This PR improves the support for push notifications on Android.
Android running OS 8 and 9 will create what is called a notification channel so users can set the priority, sound, vibration, light and how the notification displays in the phone settings, thus removing those options from the Notification settings inside the app, Phones with OS version 7 and below will still have those options.
By specifying the notification channels the bug where the notification was stopping any other sounds playing in the phone (like music) is fixed.
This is a temporary fix, we still need to migrate from GCM to FCM but that is a bigger task
There is also a small fix when receiving a push notification the channel Intro was rendering a loader that is no longer needed. …

Android notification support for O and P

---

app/screens/channel_info/channel_info.js
app/screens/channel_info/index.js
app/screens/edit_channel/edit_channel.js
app/screens/edit_channel/index.js

Reload channel on archived channel errors (on edit and archive channel).
When you are seing an archived channel and don't have the connection
active, you can miss the websocket event for mark the channel as
deleted. So you will see the channel in normal state. This will reload
the channel when the server returns the fail on edition or when you try
to archive the channel.
[MM-11728](https://mattermost.atlassian.net/browse/11728)

MM-11728: Reload channel on archived channel errors (on edit and archive channel)

---

app/screens/search/index.js
app/screens/search/search.js
app/utils/timezone.js
package-lock.json
package.json

when retrieving the timezone to pass to the server during a date flag search (on: before: after:) check user's settings and use their selected timezone if present instead of the browser's timezone
N/A
N/A
This PR was tested on: [iOS Simulator, OS 11.4] 
N/A

bug fix: use user's timezone setting for search date flags

---

app/components/emoji/emoji.js
app/components/emoji_picker/emoji_picker.js
app/components/emoji_picker/emoji_picker_row.js
app/components/options_context/options_context.android.js
app/components/options_context/options_context.ios.js
app/components/post/index.js
app/components/post/post.js
app/components/post_body/post_body.js
app/components/post_header/post_header.js
app/components/post_list/post_list.js
app/components/post_list/with_layout.js
app/screens/entry/entry.js
app/screens/entry/index.js
app/utils/why_did_you_update.js

This PR fixes the text of the posts being cut off in some cases after replying to a post or even after sending a new message in the channel's post list, the main reason was the `PixelRatio` changing the dimension of the emoji's causing a disruption in the post layout.
Other fixes in this PR:
* Post was being re-rendered without need cause of the `config` and `license` props, those props were used to mark the post as it cannot be edited anymore (but that function was actually broken) now we handle the time a post can be edited in a different more effective way.
* Added an `overflow: hidden` to the emoji picker so the `FlatList` and `SectionList` can recycle the Views
* No system emoji's were being added and unnecessary request made to the server that returned an error
* WhyDidYouUpdate …

Fix Posts cutoff

---

app/components/emoji/emoji.js

This PR fixes the rendering of custom emojis by using the emojiName as the file name to be saved on the device

Fix custom emoji render

---

app/components/custom_list/user_list_row/__snapshots__/user_list_test.test.js.snap
app/components/custom_list/user_list_row/user_list_row.js
app/components/custom_list/user_list_row/user_list_test.test.js

Add deactivated string next to username in user search modal for deactivated users.
[MM-11942](https://mattermost.atlassian.net/browse/MM-11942)
This PR was tested on Emulators

MM-11942 Add deactivate user state to more users modal

---

app/components/show_more_button/__snapshots__/show_more_button.test.js.snap
app/components/show_more_button/show_more_button.js

Add bottom margin of 10 to "show more/less button"
Jira ticket: [MM-11986](https://mattermost.atlassian.net/browse/MM-11986) & [MM-11987](https://mattermost.atlassian.net/browse/MM-11987)
This PR was tested on: [iPhone and Android simulator/emulator] 
iPhone:
Android:

[MM-11986 & MM-11987] Add bottom margin of 10 to "show more/less button"

---

app/components/autocomplete/date_suggestion/date_suggestion.js

bug: enable arrows on the calendar for date search flags
N/A
N/A
This PR was tested on: [ios 11.4 iphone 6 simulator] 
N/A

bug: enable arrows on the calendar for date search flags

---

app/actions/views/select_team.js
app/components/root/root.js
app/constants/navigation.js
app/screens/error_teams_list/__snapshots__/error_teams_list.test.js.snap
app/screens/error_teams_list/error_teams_list.js
app/screens/error_teams_list/error_teams_list.test.js
app/screens/error_teams_list/index.js
app/screens/index.js

Add an error screen when for failure in fetching teams
[MM-11603](https://mattermost.atlassian.net/browse/MM-11603)
This PR was tested on: Emulators

MM-11603 Add a retry screen when fetching teams fails

---

app/components/announcement_banner/announcement_banner.test.js
app/components/custom_list/__snapshots__/index.test.js.snap
app/components/custom_list/index.test.js
app/components/formatted_text.js
app/components/post_list/date_header/date_header.test.js
app/components/show_more_button/__snapshots__/show_more_button.test.js.snap
app/components/show_more_button/show_more_button.test.js
app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
app/screens/forgot_password/__snapshots__/forgot_password.test.js.snap
app/screens/forgot_password/forgot_password.test.js
app/screens/more_channels/more_channels.test.js
app/screens/select_team/__snapshots__/select_team.test.js.snap
app/screens/select_team/select_team.test.js
app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.ios.test.js.snap
app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
package.json
test/setup.js

Fix warnings in running unit tests, by:
- Using context for `intl` at FormattedText component
- Add `setup.js` at Jest config to let all requirements run before all tests
- Add console checks to not allow JS warning in the future.  This makes the test faster (similar to web app).
This eliminates warnings like in the screenshot:
none
This PR was tested on: [iPhone simulator, Android emulator]

Fix warnings in running jest test

---

app/components/autocomplete/date_suggestion/date_suggestion.js
app/components/quick_text_input.js
app/components/search_bar/search_bar.android.js
app/screens/search/search.js
package-lock.json
package.json

This PR fixes a couple of tickets, one for letting the user use the keyboard while having the date picker active and the second one that closes the Android keyboard when performing a search, the latter was caused by the QuickTextBox reclaiming the focus that we use for autocompletion, so this is a small hack that makes the QuickTextBox not reclaim the focus.
Note: When showing the calendar in order to allow selecting a date with the keyboard open we needed to fork the lib to add a prop for `keyboardShouldPeristTabs` we'll use the fork in the meantime but I already submitted a PR to the lib. PR can be found here https://github.com/wix/react-native-calendars/pull/620
https://mattermost.atlassian.net/browse/MM-11996
https://mattermost.atlassian.net/browse/MM-12041

Search Fixes

---

app/components/custom_list/index.js
app/components/layout/keyboard_layout/keyboard_layout.js
app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/__snapshots__/more_channels.test.js.snap
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js
app/screens/search/search.js

The current version of KeyboardLayout just moves the child upwards, so some of the contents get cut off at the top of the screen.
This adds the KeyboardLayout to the following screens:
- More DMs
- More channels
- Manage channel members
- Add channel members
- Search results
https://mattermost.atlassian.net/browse/MM-12025
This PR was tested on: iOS Simulator (iPhone 6, iOS 11.4), Nexus 5 (Android 6.0.1)

MM-12025 Use KeyboardLayout in more places and have it change height instead of moving upwards

---

app/screens/sso/sso.js

We were getting a `onMessage` error when OKTA was rendering as they need to use the postMessage function for some internal stuff and we were overriding it, now it is applied only when needed.
https://mattermost.atlassian.net/browse/MM-12136

Fix okta login

---

app/screens/entry/entry.js
share_extension/android/extension_post/extension_post.js

Remove `backgroundColor` from styles.video of Android share extension that's probably causing app to crash.
Below is the screenshot of the error in local dev after sharing video file.  Note that it didn't occurred when image file type was shared.
Note: Is it expected that the share extension theme (at least on Android) is always Mattermost (light) and does not change according to what is set by the user (e.g. if the user set it to Dark).
Jira ticket: [MM-12166](https://mattermost.atlassian.net/browse/MM-12166)
This PR was tested on: [Android emulator]

[MM-12166] Remove backgroundColor from styles.video of Android share extension that's probably causing app to crash

---

app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/channel_mention/index.js
app/components/autocomplete/emoji_suggestion/index.js
app/components/emoji_picker/index.js
package-lock.json
package.json

Using the new server endpoint to autocomplete channels for search (list
the searchable channels, where you are member, archived or not).
[MM-11725](https://mattermost.atlassian.net/browse/11725)

MM-11725: Using the new server endpoint to autocomplete channels

---

app/components/markdown/markdown.js
package-lock.json

Fix build error on Hashtag component
```
BUILDING MODULES FOR ios
error: bundling failed: Error: Unable to resolve module `app/components/hashtag` from `/Users/nnn/go/src/github.com/mattermost/mattermost-mobile/app/components/markdown/markdown.js`: Module `app/components/hashtag` does not exist in the Haste module map
```
none

Fix build error on Hashtag component

---

Makefile
package-lock.json
package.json

I've always found the fact that you can't just `npm install mattermost/mattermost-redux` kind of annoying, but moving the build step to `prepublish` or `prepare` (both are very similar, but `prepare` happens after `prepublish`) instead of `prepublishOnly` so that it triggers automatically on `npm install` should fix that.
This also lets us remove the `.npminstall` files on each repo since we can just check if `node_modules` is up to date rather than creating a new file.
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1717
Redux PR: https://github.com/mattermost/mattermost-redux/pull/635

Remove .npminstall and don't explicitly build mattermost-redux

---

app/screens/image_preview/image_preview.js

Missing prop was causing the alert box saying that downloads has been disable to popup even if downloads are enabled in the image preview screen
https://mattermost.atlassian.net/browse/MM-12253

Fix can download file for documents in preview screen

---

app/components/channel_icon.js
app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
app/components/sidebars/main/channels_list/channel_item/channel_item.js
app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
app/components/sidebars/main/channels_list/channel_item/index.js
app/components/sidebars/main/channels_list/filtered_list/filtered_list.js

Add status of a deactivated user to LHS search.
Add (you) to current user in jumpto search.
[MM-11980](https://mattermost.atlassian.net/browse/MM-11980)
[MM-11974](https://mattermost.atlassian.net/browse/MM-11974)
This PR was tested on emulators

MM-11974, MM-11980 Add deactivated user to LHS search

---

app/screens/thread/index.js
app/screens/thread/thread.js

As rootId might not be in the state there is a flicker initially showing a data retention message. 
(https://mattermost.atlassian.net/browse/MM-12199)[MM-12199]
This PR was tested on: [Emulators]

MM-12199 Add a check for loading on threads

---

app/screens/channel_peek/channel_peek.js

This is because https://github.com/mattermost/mattermost-redux/pull/645 means that this selector will no longer return a default array

Use defaultProps to ensure postIds prop exists for ChannelPeek

---

app/components/safe_area_view/safe_area_view.ios.js
package-lock.json
package.json

The new set of iPhones XR, XS and XS Max were not being considered when setting the Safe Area this PR adds support for those devices
https://mattermost.atlassian.net/browse/MM-12281
Closes: #2152 
This PR was tested on: iOS 12 Simulator for XR, XS and XS Max

Add support for iPhone XR, XS and XS Max

---

package-lock.json
package.json

The code I added to commonmark.js to check the minimum length of hashtags was using a `> 3` instead of a `>= 3` for valid hashtags
Commonmark changes here: https://github.com/mattermost/commonmark.js/commit/95999d98559338f0249ffb3ab72984b48eccea42
https://mattermost.atlassian.net/browse/MM-10273

MM-10273 Fix 3 character hashtags not being rendered

---

app/components/post_body_additional_content/post_body_additional_content.js

Aligns the YouTube play button to the center (after the upgrade to RN 57 it was being drawn at the top left corner)

Fix YouTube play button position

---

app/components/channel_icon.js
app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
app/components/sidebars/main/channels_list/channel_item/channel_item.js
app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
app/components/sidebars/main/channels_list/channel_item/index.js
app/selectors/views.js

Add a pencil icon in the Channel sidebar and the jump to channel sidebar when the channel has a draft. does not considers drafts in threads
https://mattermost.atlassian.net/browse/MM-12049
This PR was tested on: iOS and Android

Add draft indicator to the channel item

---

app/screens/image_preview/downloader.android.js

With the upgrade to RN 0.57 the download option was always showing as the container for it had a height of 0 and somehow that was causing the text to show up but not the container
https://mattermost.atlassian.net/browse/MM-12289

Fix Android previewer download option

---

app/fetch_preconfig.js

This PR fixes an issue that brings the app totally unusable when the server is configured in HA mode and there is a mismatch in the config between the servers involved.
Example:
appserver1: `5.3.0.master.733.6f44e8089aa43c309e7d38e7bcbdccfa.true`
appserver2: `5.3.0.master.733.e1684f7a33feead334cceb4aadf11790.true`
What was causing the issue is that for every request the header `X-Version-Id` would be different then the client was requesting the config and license again and again in a constant loop cause an event was being emitted blocking almost completely the UI.
Now the config is requested at the following cases:
* Entering a server URL
* When the WS connects
* When the WS event for the config or license change is triggered
This was being reported by an E20 customer and I got that …

Fix config fetch loop when HA config mismatch

---

app/screens/search/search.js

This fixes the issue with hashtag search where the cancel button isn't visible until the search bar gains focus. Ideally, we wouldn't need to focus the search box since that takes up a large part of the screen, but the cancel button being visible is heavily attached to that box receiving focus, and changing that would require some significant changes that I don't think I can have done for feature complete tomorrow.
https://mattermost.atlassian.net/browse/MM-10273

MM-10273 Always focus search input when first opening

---

app/components/post_body/post_body.js
app/components/reactions/reactions.js
app/constants/emoji.js
app/screens/index.js
app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
app/screens/reaction_list/__snapshots__/reaction_header_item.test.js.snap
app/screens/reaction_list/__snapshots__/reaction_list.test.js.snap
app/screens/reaction_list/__snapshots__/reaction_row.test.js.snap
app/screens/reaction_list/index.js
app/screens/reaction_list/reaction_header.js
app/screens/reaction_list/reaction_header.test.js
app/screens/reaction_list/reaction_header_item.js
app/screens/reaction_list/reaction_header_item.test.js
app/screens/reaction_list/reaction_list.js
app/screens/reaction_list/reaction_list.test.js
app/screens/reaction_list/reaction_row.js
app/screens/reaction_list/reaction_row.test.js
app/utils/reaction.js
assets/base/i18n/en.json

Add reaction list but this is different from the specs as it's lacking the animation.  Therefore, the reaction list is here on P1, and then the modal animation to follow in P2.
I'd like to get a first pass review first before providing unit tests.
Specs: https://projects.invisionapp.com/share/YJFC6W98KM4#/screens/293894143_Emoji_Reaction_List
[Latest]
Android: - https://youtu.be/qYyMoEZxXtU
iPhone: - https://youtu.be/EMPLfsNNkzM

[MM-9490] Add reaction list

---

app/screens/search/search.js

Only attempt to get more search results if the value is set. without it the search screen was trying to fetch more results when the screen loaded
Also updated mattermost-redux as the previous PR did not include the commit for `getMorePostsForSearch` action thus causing a crash

 Get more search results only if value is set

---

app/components/custom_list/custom_list_row.js
app/components/custom_list/user_list_row/__snapshots__/user_list_test.test.js.snap
app/components/custom_list/user_list_row/user_list_row.js
app/components/custom_list/user_list_row/user_list_test.test.js
assets/base/i18n/en.json

Make user info of user list on two rows: first with username and second with teammate display
- show ellipsis on text overflow of either username or teammate display
- if username is equal to teammate display, only show in one row with username
Note that Add/Manage Members screen is also affected by this change.
Jira ticket: [MM-12145](https://mattermost.atlassian.net/browse/MM-12145)
iOS:
Android:
Other screen affected by the change on CustomListRow which looks the same as before: 
Add Members Screen:
Manage Members screen:
Mor Channels screen:

[MM-12145] Make user info of user list on two rows: first with username and second with teammate display

---

app/screens/thread/thread.js

If the thread screen already had the root post we still waited until the request finished, that slowed viewing the thread even if there was no need for it

Do not show a loading spinner if thread has root post loaded

---

app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
app/utils/images.js
app/utils/images.test.js

With all white PNG image from link preview and theme of white background, the image is hidden and makes a significant space on link preview.
Discussion on pre-release: https://pre-release.mattermost.com/core/pl/ytqicfj99tngf8dd6wq5ugcmkr
Solution is to add border to image of link preview.
This PR also includes:
- not allowing such image width to exceed the view port width
- set border radius of 3 pixel to link and image preview containers
Jira ticket: [MM-12149](https://mattermost.atlassian.net/browse/MM-12149)

[MM-12149] Add border to image of link preview and not allow such image width to exceed the view port width

---

app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/post_attachment_opengraph/post_attachment_opengraph.test.js

Fix blank space on link preview when no site name.
Note that this PR is submitted on top of https://github.com/mattermost/mattermost-mobile/pull/2189 just to prevent merge conflict on unit testing.  Will rebase once that PR is merged.
Also, no milestone is set yet since I'm not sure if this should be part of 1.13.
Jira ticket: [MM-12390](https://mattermost.atlassian.net/browse/MM-12390)

[MM-12390] Fix blank space on link preview when no site name

---

app/utils/reaction.js
app/utils/reaction.test.js

Fixed empty reaction row when profile is missing.
Also, added test to some utility functions.
Jira ticket: [MM-12417](https://mattermost.atlassian.net/browse/MM-12417)

[MM-12417] Fix empty reaction row when profile is missing

---

app/components/sidebars/main/channels_list/filtered_list/filtered_list.js

Adds a key `name` for sorting as DM's profiles will not have the key.
Redux utils function for sorting fails as it checks for name to sort if two display_names are equal
Reverts a minor change from https://github.com/mattermost/mattermost-mobile/commit/a6e15320d4110799c78c4a02b7600af6c1065c4a#diff-23e5d2f83331fd7fccf6be48c0aa6052L214
[MM-12347](https://mattermost.atlassian.net/browse/MM-12347)
This PR was tested on: [Ios emulator and android emulators]

MM-12347 Fix crash of app when accessing jumpTo

---

app/components/layout/keyboard_layout/index.js
app/components/layout/keyboard_layout/keyboard_layout.js
app/screens/channel/channel.js
app/screens/more_channels/__snapshots__/more_channels.test.js.snap
app/screens/thread/thread.js

This is some extra work done along with https://github.com/mattermost/mattermost-mobile/pull/2201. Of the removed props:
- `statusBarHeight` wasn't actually used
- `theme` was only used to add a background colour which was already set everywhere except for the Thread screen which was attempting to set it through a `style` prop that didn't work previously
- `behavior` and `keyboardVerticalOffset` were being passed from the Thread screen, but they didn't do anything. They were left over from using RN's built-in KeyboardAvoidingView
https://mattermost.atlassian.net/browse/MM-12424
This PR was tested on: iOS Simulator (iPhone 5s, iOS 12), Nexus 5 (Android 6.0)

MM-12424 Remove unused props from KeyboardLayout and simplify methods

---

app/components/sidebars/main/channels_list/channel_item/index.js

The draft indicator should not be present if the draft only contains whitespaces
https://mattermost.atlassian.net/browse/MM-12337

Draft channel indicator to ignore message with whitespaces only

---

app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
app/components/post_attachment_opengraph/post_attachment_opengraph.js
app/components/post_attachment_opengraph/post_attachment_opengraph.test.js

Fix empty space on link preview when title and URL is not present in open graph meta
- when title and URL is not present, use the link instead similar to how we're doing in the webapp.
Jira ticket: [MM-12418](https://mattermost.atlassian.net/browse/MM-12418)
BEFORE:
AFTER:

[MM-12418] Fix empty space on link preview when title and URL is not present in open graph meta

---

app/components/file_attachment_list/file_attachment_image.js
app/components/file_upload_preview/file_upload_item/file_upload_item.js

By setting the wrapper container height and width the same as the file upload previewer images now look centered
https://mattermost.atlassian.net/browse/MM-12445

image thumbnail not centered

---

app/components/error_text/__snapshots__/error_text.test.js.snap
app/components/error_text/error_text.js
app/components/error_text/error_text.test.js
app/components/error_text/index.js
app/screens/edit_profile/edit_profile.js

Adds padding to error screen from edit profile props
[MM-12301](https://mattermost.atlassian.net/browse/MM-12301)
This PR was tested on: [Emulators]

MM-12301 Add padding for error text on edit profile screen

---

app/actions/views/post.js
app/components/message_attachments/action_menu/action_menu.js
app/components/message_attachments/action_menu/index.js
app/constants/view.js
app/reducers/views/post.js
app/screens/menu_action_selector/index.js

When choosing an option in the interactive menus, have the choice persist after channel switch and have threaded view and main channel view share choices. The web app does something similar.
https://mattermost.atlassian.net/browse/MM-12348
Android Galaxy S9
iOS Simulator

MM-12348 Persist interactive menu choices past channel switch and share with thread view

---

android/app/src/main/java/com/mattermost/rnbeta/NotificationsLifecycleFacade.java

Setting this value as per https://github.com/wix/react-native-navigation/blob/master/docs/android-specific-use-cases.md#adjusting-soft-input-mode. It was previously set through the AndroidManifest, but that's not used once we switch to the NavigationActivity used by that library.
Setting this causes the app content to shrink appropriately when the soft keyboard is visible.
https://mattermost.atlassian.net/browse/MM-12424
This PR was tested on: Nexus 5 (Android 6.0)

MM-12424 Properly set softInputMode on Android

---

app/components/file_attachment_list/file_attachment_image.js
app/components/file_upload_preview/file_upload_item/file_upload_item.js

This reverts commit 5f31374e746531c77233d965ea48d0c7ef05edc5 as it made the attachment preview of the image larger than the other file types. and properly centers the image in the attachment preview
https://mattermost.atlassian.net/browse/MM-12445

Revert "image thumbnail not centered (#2210)" and fix it properly

---

app/components/autocomplete/at_mention/at_mention.js
app/components/autocomplete/autocomplete.js
app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/date_suggestion/date_suggestion.js
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/autocomplete/slash_suggestion/slash_suggestion.js
app/components/file_upload_preview/file_upload_preview.js
app/components/file_upload_preview/index.js
app/components/post_textbox/post_textbox.js

The most important change here is that all autocompletes (except for the DateSuggestion) now have a variable max height. The post textbox autocompletes are based off the remaining space above the View containing the post textbox itself. Note that it can't be on the outermost view due to some weird Android behaviour, although that doesn't matter since it's now a fragment.
https://mattermost.atlassian.net/browse/MM-12189
This PR was tested on: iOS Simulator (iPhone 5S, iOS 12), Nexus 5 (Android 6.0)

MM-12189 Set autocomplete max height based off available space

---

app/screens/channel/channel_post_list/channel_post_list.js

When reaching the top of a channel and then switch to a different channel, it wasnt loading more posts as the flag was not being reset
https://mattermost.atlassian.net/browse/MM-12527

Reset isLoadingMoreTop flag when switching channels

---

app/screens/permalink/__snapshots__/permalink.test.js.snap
app/screens/permalink/permalink.js
app/screens/permalink/permalink.test.js
app/selectors/post_list.js

Fix hangup on permalink view when user deleted the post in it
With post on permalink view, when a user deleted that same post on permalink view, the selector `getPost` returns null, and so the channelName/Id and postIds from that deleted post becomes null and empty array.  It causes to erase all post on screen and hitting "Jump to recent messages" causes it to hangup.
https://github.com/mattermost/mattermost-mobile/blob/master/app/screens/permalink/index.js#L36
Jira ticket: [MM-12550](https://mattermost.atlassian.net/browse/MM-12550)
- iOS screen capture: https://youtu.be/6xNC5McNgXg
- Android screen capture: https://youtu.be/nts6LaoHxR4

[MM-12550] Fix hangup on permalink view when user deleted the post in it

---

app/components/user_status/__snapshots__/user_status.test.js.snap
app/components/user_status/user_status.js
app/components/user_status/user_status.test.js

Add opacity of 0.3 to circle stroke of offline status.
@enahum Please confirm if we can make it for release-1.13.
Jira ticket: [MM-12622](https://mattermost.atlassian.net/browse/MM-12622)
iPhone:
Android:

[MM-12622] Add opacity of 0.3 to circle stroke of offline status

---

app/fetch_preconfig.js
app/store/index.js
app/store/thunk.js
app/utils/sentry/index.js
app/utils/sentry/index.test.js
package-lock.json
package.json

As stated in the Redux PR, using a modified version of thunk will allow us to intercept and reformat the unhandled network errors so that we'll be able to figure out where they're not being handled properly.
Redux changes: https://github.com/mattermost/mattermost-redux/pull/666

MM-11477 Use custom thunk middleware to intercept leaked network errors

---

app/components/emoji_picker/emoji_picker.js
app/screens/mfa/mfa.js
app/screens/select_server/select_server.js

The KeyboardAvoidView was causing issues on Android, not letting the buttons to be tapped while the keyboard was opened, by setting the KeyboardAvoidView as disabled the issue is fixed.
Also added a few missing translations in the same PR.
https://mattermost.atlassian.net/browse/MM-12554

Fix KeyboardAvoidView for android

---

app/screens/search/index.js
app/screens/search/search.js

Adds parameter required to retrieve archived channel search results.
https://mattermost.atlassian.net/browse/MM-12552
iPhone 6, iOS 12.0 (emulator)
n/a

MM-12552: Adds parameter to include archived channel search results.

---

app/components/post_body/post_body.js

In case the post does not have text we do not show the option to copy the post as there is nothing to copy
https://mattermost.atlassian.net/browse/MM-12349

Do not show the option to copy post if there is no text

---

app/components/post_list/post_list_base.js
app/screens/thread/__snapshots__/thread.test.js.snap
app/screens/thread/thread.js
app/screens/thread/thread.test.js

Fixes infinite loader for thread view
Though the status for post loading changes props to postList does not change(As it is func reference and not a component or Obj) causing it not to render again.
Flatlist accepts react component too so changing this to accept component as it causes the render.
There should not cause any unnecessary render cycles as only initial state changes cause renders and after that this.renderFooter return null and `null === null`.
[MM-12560](https://mattermost.atlassian.net/browse/MM-12560)

MM-12560 Fix for infinite loading indicator for thread from search

---

share_extension/ios/extension.js

If `AppGroupId` was not set correct, iOS share extension crashes.
mattermost-mobile/share_extension/ios/extension.js
```
mattermostBucket.readFromFile('entities', props.appGroupId).then((value) => {
this.entities = value || initialState;
this.setState({init: true});
});
```
`this.entities = value || initialState;`
must be 
`this.entities = value || initialState.entities;`
- Device Name: all iOS device
- OS Version: Test on iOS 12
- Mattermost App Version: 1.12.0

Fix iOS Share Extension crashes

---

app/screens/channel_info/channel_info.js
app/screens/channel_members/index.js

Adds 'View Members' button to archived channels.
https://mattermost.atlassian.net/browse/MM-11589
iPhone 6, iOS 12.0 (emulator)

MM-11589: Adds 'View Members' button to archived channels.

---

app/screens/permalink/permalink.js

If postsIds is null this was causing a crash.
https://mattermost.atlassian.net/browse/MM-12658

Fix crash when loading the permalink view

---

app/components/attachment_button.js

on iOS the ImagePicker does not set the `path` on the returned response like for Android but an `uri` this PR handles that so it upload the video files correctly on both platforms
https://mattermost.atlassian.net/browse/MM-12663

Fix uploading iOS videos

---

app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
app/components/sidebars/main/channels_list/channel_item/channel_item.js
app/components/sidebars/main/channels_list/channel_item/channel_item.test.js
app/components/sidebars/main/channels_list/channel_item/index.js
test/setup.js

Fix for populating (you) in LHS for currenUser
1. From search result currentUser id will be in channel.id
2. If in LHS currentUser id will be in channel.teammate_id
[MM-12676](https://mattermost.atlassian.net/browse/MM-12676)

Fix for LHS populating you next to current user

---

app/components/attachment_button.js
ios/MattermostShare/ShareViewController.m

By lowering the quality we ensure that the file size is definitely lower, the main issue here is that for images and videos the library actually process and re-encodes the image, so it is actually not the original file, I've looked to replace the library but did not find one that satisfies what we need. The share extension on iOS also does the same process by using `UIImageJPEGRepresentation` but the quality values were different than the one used the RN code now they are set at `0.8` in both places.
On the other hand the Share Extension for Android actually uses a copy of the original file, so sizes might in fact be different.
I also found this in another similar library that also process and re-encodes the images and videos
> Compress image with quality (from 0 to 1, where 1 is best …

Fix Upload file size

---

app/screens/sso/sso.js

This PR fixes signing in with some OKTA deployments that make use of the `postMessage` event to handle some internal stuff.
Candidate for a dot release
https://mattermost.atlassian.net/browse/MM-12756

Hook the onMessage event only when needed

---

Makefile

The `build-android` target calls the `pre-build` target as `pre-buid`, resulting in build failure for the `build-android` target. This PR fixes the issue.
([PR #2272](https://github.com/mattermost/mattermost-mobile/pull/2272) did the same for a typo in the `build-pr` target.)

Fix 'pre-buid' typo in build-android target

---

app/components/attachment_button.js

When changing the quality to reduce the file size videos had a low quality when being recorded directly, this ensures that they are recorded in high quality.
One thing to note is that recording a new video an uploading it directly will have a larger file size than the same video when selected from the image library, the reason is that the underlaying library do not apply the same conversion to the files.
https://mattermost.atlassian.net/browse/MM-12246

Capture video in high quality

---

app/components/autocomplete/autocomplete_section_header.js
app/components/autocomplete/slash_suggestion/slash_suggestion.js
app/components/autocomplete/slash_suggestion/slash_suggestion_item.js

This removes the duplicate borders at the top of some lists and also removes the borders around the autocomplete section headers
https://mattermost.atlassian.net/browse/MM-12467

MM-12467 Made borders between autocomplete items consistent

---

NOTICE.txt
app/components/sidebars/drawer_layout.js
app/components/sidebars/main/main_sidebar.js
app/components/sidebars/settings/settings_sidebar.js
package-lock.json
package.json

The library that we were using for the DrawerLayout (react-native-drawer-layout) was using the panHandler when swiping horizontally preventing the drawer to go from the team list back to the channel list and so we had it locked so we could do the above, but then we could not close the drawer when in the team list.
this PR removes the library dependency but we have a local copy (1 file) with a modification that will let us set a variable in the drawer to allow the drawer to be closed, so when the drawer is displaying the team list, that variable is set to false and so the swiper captures the panResponder instead.
https://mattermost.atlassian.net/browse/MM-12834

Allow channel drawer to close when showing the team list

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/network_security_config.xml

This will allow Android to establish a network connection with any server that uses a Self sign certificate that has the CA certificate installed on the device
More info [here](https://developer.android.com/training/articles/security-config)  and in this [blog post](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html)
Resolves #2139

Allow user system CA's for Android

---

app/components/markdown/transform.js
app/components/markdown/transform.test.js

Some background information: `combineTextNodes` is used because the Markdown parser sometimes breaks up a string of plain text into a multiple text nodes. Notably, a word followed by a colon and then a space like `test: ` is broken up into one node for each character by the autolinker.
The bug that was happening was that for text like `test: *italics*`, after running `combineTextNodes`, you'd end up with a Text node for `test: ` and an Emphasis node for the rest, but they wouldn't be correctly linked as siblings which would make the source tree invalid, sometimes causing other parts of the formatting to break. That was due to some behaviour that I had missed in the NodeWalker that's fixed by calling `walker.resumeAt` to reset the NodeWalker's internal state …

MM-12880 Properly link the next sibling following a combined text node

---

app/screens/error_teams_list/error_teams_list.js

When on the failed teams screen the user retried to get the teams we were setting the connection back to false thus every request made right after it was failing, here we only set the flag back as false if the action fails

Keep connection as active when retrying teams

---

app/fetch_preconfig.js
package-lock.json
package.json

This is another attempt at stopping the "non-error exceptions" that Sentry keeps getting because we're not catching the errors thrown by Client4 correctly, and Sentry doesn't provide any helpful debugging information unless you're throwing an actual Error object.
Waiting on redux changes from: https://github.com/mattermost/mattermost-redux/pull/704

MM-11477 Wrap objects thrown by Client4 in a proper error type

---

app/components/file_attachment_list/file_attachment_list.js

Image preview is not working on Android cause the images need the `file://` prefix

Fix Android image preview

---

app/actions/views/post.js
app/components/message_attachments/action_menu/action_menu.js
app/components/message_attachments/action_menu/index.js
app/components/message_attachments/message_attachment.js
app/reducers/views/post.js

When a message attachment had multiple actions there were a few issues:
1. The actions did not wrap properly so I changed it to be vertically align instead of horizontal
2. The reducer was taking into account only one selection per post so all the actions had the same selection
3. the tappable area was on the text and the chevron icon instead of the whole button
4. When the datasource is `users` the result was not following the Teammate display name setting
https://mattermost.atlassian.net/browse/MM-12977

Fix when message have multiple actions

---

app/components/autocomplete/channel_mention/channel_mention.js
app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
app/components/autocomplete/slash_suggestion/slash_suggestion.js

As I said this is a super hacky solution that will replace the text twice on iOS just to avoid the autocorrect for overriding the values, this is the best way I was able to fix it after HH spent about a day trying to come up with a different solution
https://mattermost.atlassian.net/browse/MM-12952

MM-12952 Avoid iOS autocorrect from overriding autocomplete values

---

app/screens/search/search.js

Reverted the change in the condition in componentDidUpdate and when the request fails but there were already posts loaded
https://mattermost.atlassian.net/browse/MM-13016

Fix regression when scrolling in search screen

---

app/components/autocomplete/autocomplete_section_header.js
app/components/autocomplete/channel_mention/channel_mention.js

When using the channel autocomplete there is a delay before showing the autocomplete channels component. The delay occurs because the component is waiting for the search channels request to complete. It is most noticeable on a slow network or when there are thousands of channels. This PR changes the behavior of the channel autocomplete component to instantly show what is currently in the state while showing a loading indicator at the right of the autocomplete section header while the request is in flight.

Instantly show autocomplete channels

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationDrawer.java
android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java
app/components/network_indicator/index.js
app/components/network_indicator/network_indicator.js
app/push_notifications/push_notifications.android.js
app/push_notifications/push_notifications.ios.js
app/screens/channel/channel.js
app/screens/channel/channel_nav_bar/channel_drawer_button.js
ios/Mattermost/AppDelegate.m
ios/Mattermost/Info.plist

This PR improves Android push notifications by:
* Opening the app does not clear the push notifications
* If multiple notifications only the notification that was selected gets cleared when opening the app the rest remain in the notification center
* If there is a notification for a channel in the notification center, using the app to switch to that channel removes the notification from the device
* Notifications get cleared when the channel is read in desktop/browser
See #2292 for more details on iOS
https://mattermost.atlassian.net/browse/MM-12542

 Android/iOS leave notifications until channel is read

---

app/components/post_list/post_list.ios.js
app/components/post_list/post_list_base.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/channel/channel_post_list/index.js

This fixes an issue on iOS where the refresh indicator was not properly showing while a channel's posts are being refreshed
This PR was tested on: Nexus 6 (Android), iPhone X (iOS)

Refresh indicator fix

---

share_extension/android/extension.js
share_extension/android/index.js
share_extension/android/selectors/index.js

The Android Share extension also initializes the app and we were initializing the store twice, with this PR we use the same redux store initialized by the app to avoid conflicts
https://mattermost.atlassian.net/browse/MM-13029

On fresh install the share extension will not properly show available channels

---

app/actions/views/user.js
app/actions/views/user.test.js
app/components/network_indicator/index.js
app/components/network_indicator/network_indicator.js

When the user goes offline (either loses internet connection or cannot connect to the server) we set the current user status to offline and then we fetch the user's status from the server when the device regains connection to the server.
https://mattermost.atlassian.net/browse/MM-13082

Set the current user status as offline when the app loses connection

---

app/components/post_body_additional_content/index.js
app/components/post_list/post_list.ios.js

* Added support to keep the postlist in place without scrolling when new content is available (iOS only)
* Using post metadata for opengraph as a fallback as I encounter a case where for some reason the metadata was not set in the reducer but it was still in the metadata object

Keep postlist scroll position on iOS and fix opengraph

---

app/components/error_text/error_text.js

Fixes the screen going blank if when creating a channel errors out
https://mattermost.atlassian.net/browse/MM-13150

Fix error text when intl object is not provided

---

app/components/emoji/index.js
app/utils/emoji_utils.js
app/utils/emoji_utils.test.js

Render text when named emoji does not match with the existing custom emojis
Jira ticket: [MM-13074](https://mattermost.atlassian.net/browse/MM-13074)

[MM-13074] Render text when named emoji does not match with the existing custom emojis

---

app/components/post_list/post_list.ios.js

on iOS the post list will not scroll or pop when new messages arrive not even when you were at the bottom, this PR adds a threshold so the post lists scrolls you to the new messages as they arrive if you are at the bottom or above the bottom by a max of 60px, above those 60px the list won't scroll

Add a threshold of 60px from the bottom to show new messages

---

share_extension/android/actions/index.js
share_extension/android/extension_post/extension_post.js
share_extension/android/extension_post/index.js
share_extension/android/index.js

Fetch the current team channels when the extension opens to ensure we have them in the store, also fetch the channels when switching teams regardless if the default channel is already loaded to keep the list up to date.
https://mattermost.atlassian.net/browse/MM-13029

Fetch team channels on extension init

---

app/components/autocomplete/channel_mention_item/channel_mention_item.js

Direct message channels have no display name, except for search
autocompleted results. If we don't have display name, we don't show it
in the autocomplete results (until we receive from the autocomplete API
response).
Besides I fixed a problem with autocompletion of group message channels.
[MM-13041](https://mattermost.atlassian.net/browse/MM-13041)

MM-13041: Not show direct channels without display name

---

app/components/message_attachments/message_attachment.js

Fixes an issue where message attachments were empty if text came through on fallback
n/a

Fixed empty message attachment text

---

app/components/file_attachment_list/file_attachment.js
app/components/file_attachment_list/file_attachment_list.js

This change addresses a bug where image preview was not working specifically for new images or after resetting cache. 
https://mattermost.atlassian.net/browse/MM-13237

File image attachments sometimes do not open the image preview

---

app/utils/markdown.js

see https://github.com/mattermost/mattermost-webapp/pull/2056
This PR attempts to add support for syntax highlighting of Elixir code and supports https://github.com/mattermost/mattermost-webapp/pull/2056
N/A 
N/A
N/A

Add support for Elixir syntax highlighting

---

app/screens/settings/advanced_settings/advanced_settings.js

There are should be `mobile.advanced_settings.delete_file_cache` instead of `mobile.advanced_settings.clear_downloads`.

Fixed typo in i18nId

---

app/screens/channel_info/channel_info.js
app/screens/channel_info/index.js
assets/base/i18n/en.json

Channel notification setting for disabling channel mentions
https://github.com/mattermost/mattermost-server/issues/9505
This PR was tested on: Nexus 9, Android 8
https://lh3.google.com/u/0/d/1eUx8pWFHB2FAnopfXzQQoAmnaOy_63gp=w1920-h978

[MM-8404] Channel notification setting for disabling channel mentions (#MM-8404)

---

app/components/__snapshots__/badge.test.js.snap
app/components/badge.js
app/components/badge.test.js
app/components/sidebars/main/channels_list/channel_item/channel_item.js
app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
app/screens/channel/channel_nav_bar/channel_drawer_button.js

Make circular badge on jewel for single-digit mention
Jira ticket: [MM-13171](https://mattermost.atlassian.net/browse/MM-13171)
Screen recording - https://youtu.be/sXRYsXdPFk0.  The incremental changes in mention count of emoji channel there was due to continuous posting of at-mention by other user on a browser.
iOS screenshots:
Android screenshots:

[MM-13171] Make circular badge on jewel for single-digit mention

---

app/components/emoji/index.js

Render text for non-existent emoji when post metadata is enabled.
This is a proper fix for the original Jira issue of https://mattermost.atlassian.net/browse/MM-13074
Jira ticket: [MM-13174](https://mattermost.atlassian.net/browse/MM-13174) & [MM-13074](https://mattermost.atlassian.net/browse/MM-13074)
Server PR - https://github.com/mattermost/mattermost-server/pull/9970

[MM-13074] Render text for non-existent emoji when post metadata is enabled

---

app/components/file_attachment_list/file_attachment_document.js

The library that we use to open documents implements `MimeTypeMap.getFileExtensionFromUrl(url)` on Android to detect the file extension which in some cases it fails.
As to why `MimeTypeMap.getFileExtensionFromUrl(url)` fails? It's expecting a properly formatted URL String, which if the filename has spaces or any other weird character it will just fail. so we will first encode it using URLEncoder.
Also the underlying library is concatenating the `fileName` and `fileExtension` so we are now removing the extension from the filename
https://mattermost.atlassian.net/browse/MM-13355
This PR was tested on: Android & iOS

Fix opening documents on Android

---

app/components/slide_up_panel/slide_up_panel.js

Fixes:
1. On Android when there are so may different reaction s the you can scroll it's very hard to scroll back up from the bottom of the list without just closing the screen.
2. It seems like when there are so may different reactions that you have to scroll, the bottom record is not shown on Android. And, the bottom 1 and 1/2 emojis is missing on iOS
https://mattermost.atlassian.net/browse/MM-12228

Fix reaction list cutoff at end of list

---

app/screens/select_team/select_team.js

Make the background image of the Team Icon white in the Join other teams screen to be consistent with the webapp
https://mattermost.atlassian.net/browse/MM-13361

MM-13361 Set Open Teams icons background to white

---

app/components/sidebars/main/channels_list/list/index.js

Check if there are favorite channels before showing the section in the channel sidebar
https://mattermost.atlassian.net/browse/MM-13395

Hide Favorite channel section when there are not favorite channels

---

app/components/post_body_additional_content/post_body_additional_content.js

When post-metadata a shortened link was not displaying the image cause we checked if the link is an image but we were using the shortened one instead of the full location.
https://mattermost.atlassian.net/browse/MM-13356

Properly check if link is an image when link is shortened

---

app/components/attachment_button.js
app/screens/edit_profile/edit_profile.js

Three things got fixed with this PR:
1. File size was 20 Kb instead of 20 Mb
2. If the image to be set is larger than 20Mb now we show an alert box (instead of no feedback)
3. Disable video library for Android
https://mattermost.atlassian.net/browse/MM-13365

Fix edit profile image

---

app/components/markdown/markdown_link/markdown_link.js

Copying a link from Md was crashing the app

Fix copy markdown link

---

app/components/sidebars/main/channels_list/list/list.js

When receiving new props, `buildSections` is called with the new props, but it would then call `getSectionConfigByType` which just uses `this.props`, so it wouldn't know to apply newly received permissions right away.
https://mattermost.atlassian.net/browse/MM-13421
This PR was tested on: iOS Simulator (iPhone X, iOS 12.1)

MM-13421 Fix channel sidebar sometimes using old permissions

---

app/actions/views/channel.js
app/constants/view.js
app/reducers/views/channel.js

Load more posts of a channel by determining the amount of posts shown regardless of how many are in the store.
We were loading more posts into the channel if the amount of posts that we had in `postsInChannel` was <= to the desired amount of posts that we wanted to show, BUT sometimes we had more posts in `postsInChannel` and they can actually be out of order, here we add a new reducer to keep track of the actual amount of loaded posts that we have for a channel and then if we need more from the server those get loaded.
https://mattermost.atlassian.net/browse/MM-13431

MM-13431 Fix load more posts

---

app/screens/post_options/post_options.js

on iPhone X family the initial position will be set at 280 and the rest of iOS and Android will be at 305 so one option is cutoff at the end of the option list to indicate that there are more options to be shown
https://mattermost.atlassian.net/browse/MM-13366

Post Menu initial position to show one option cut off

---

app/components/post/post.js

Fix minor alignment issue with reply thread indicator
* Add a pixel to margin right for profile_picture container
to compensate status icon platform styles
Post with profile picture is always off by 1px in android not just the replyBar
[MM-13333](https://mattermost.atlassian.net/browse/MM-13333)
This PR was tested on: [Android and IOS simulators]

MM-13333 Fix minor alignment issue with reply thread indicator

---

app/screens/select_team/index.js
app/screens/select_team/select_team.js
app/screens/select_team/select_team.test.js

When joining a team failed, the app was "showing" the alert box but also errors out as after the request failed it continue to switch to the selected team even after it was unable to join.
We now await for the response and only if it succeeded we send the user to the channel screen, if not we just present the user with an alert box displaying the reason why it failed. 
Note: The actual bug described in the ticket no longer reproduces on server version 5.6
https://mattermost.atlassian.net/browse/MM-9220

Show an alert box when the team could not be joined

---

app/screens/sso/sso.js

Some OKTA deployments use `window.postMessage` internally to handle their own flow, maybe this is true with other SSO providers that we don't know about.
By adding the `onMessage` event handler we were hijacking the `postMessage` from OKTA thus it did not complete the flow needed.
With this PR we only set the `onMessage` handler when we've reached the final page for the login flow in the Mattermost server
https://mattermost.atlassian.net/browse/MM-13570

Add the onMessage handler when sso completes

---

app/components/message_attachments/attachment_fields.js
app/components/message_attachments/message_attachment.js

This change fixes both (1) an issue where text was duplicated on message attachments  and (2) an empty space above the message would appear when the attachment did not have a "title" field
https://mattermost.atlassian.net/browse/MM-13535
https://mattermost.atlassian.net/browse/MM-13538

MM-13535/MM-13538 Fixes for duplicate text on message attachments and empty space

---

app/components/sidebars/main/channels_list/list/index.js

When a favorite channel had an unread message it was displayed in the unread section and not in the favorite section. BUT if there was only one favorite channel with unread messages it was also keeping the favorite section empty. The reason for this is that `getFavoriteChannelIds` does not filter the channels in the unread section but `getSortedFavoriteChannelIds` does.
https://mattermost.atlassian.net/browse/MM-13517

LHS use getSortedFavoriteChannelIds instead of getFavoriteChannelIds

---

app/screens/channel/channel_post_list/index.js
app/screens/thread/thread.js

Handling nulls in getMyCurrentChannelMembership, to adapt the code to
one new change in the mattermost-redux library
Related to the PR: mattermost/mattermost-redux#746
[MM-13322](https://mattermost.atlassian.net/browse/MM-13322)

Handling nulls in getMyCurrentChannelMembership

---

app/components/markdown/markdown.js
app/components/markdown/markdown_table/markdown_table.js
app/components/markdown/markdown_table_cell/markdown_table_cell.js
app/components/markdown/markdown_table_row/markdown_table_row.js
app/screens/table/table.js
package-lock.json
package.json

This makes it so that the columns in Markdown tables are a fixed width instead of fitting all columns into the available space so that tables with more columns be readable. A few things to note with this:
1. I'm unable to make the tables scroll horizontally in the post view as requested, but you can scroll horizontally once tapping on the table for the full view
2. When viewing the whole table, Android does not support diagonal scrolling so you can only scroll horizontally and then vertically. 
3. I've increased the max height of tables in the post list from 120 to 300 points
As part of this ticket, I've also made a small change to commonmark-react-renderer to make it so that the MarkdownTable component knows the number of rows and columns to be rendered. Those changes are here: …

MM-11232 Fix table column width to better support wide tables 

---

app/actions/views/user.js
app/actions/views/user.test.js
app/components/network_indicator/index.js
app/components/network_indicator/network_indicator.js

on first run the `startPeriodicStatusUpdates` action was not being called, also changed it for a local action that will fetch the current status of the users when called before starting the periodic updates
https://mattermost.atlassian.net/browse/MM-13594

MM-13594 Fix other users status changes

---

app/components/sidebars/main/channels_list/channel_item/index.js
app/screens/channel_peek/index.js

As part of the migration to flow the getMyChannelMember will return `null`
instead of `{}`. This PR handle that properly.
The mattermost-redux change was made here: mattermost/mattermost-redux#749

Handling nulls in getMyChannelMember

---

app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
app/components/file_attachment_list/file_attachment_list.js
app/components/file_attachment_list/file_attachment_list.test.js
app/components/file_attachment_list/index.js

While removing request state flags in https://github.com/mattermost/mattermost-redux/pull/748
getFilesForPost is also removed which is used in the app here. The flag does not serve the purpose here as it is just one instance where it should have been an array of flags one for each post. 
Instead using react state here for the flag as it serves the purpose.
[MM-13544](https://mattermost.atlassian.net/browse/MM-13544)

MM-13432 Remove getFilesForPost request state and use react state

---

app/utils/emoji_utils.js
app/utils/emoji_utils.test.js

If the post begins with 4 or more spaces treat is as a regular Markdown and not Emoji Only markdown
https://mattermost.atlassian.net/browse/MM-13666

MM-13666 Detect post as emoji only if not a codeblock

---

app/screens/post_options/index.js

Fix for incorrect display of 'Delete' button without permissions.
https://mattermost.atlassian.net/browse/MM-13751
* iPhone X, iOS 12.1 emulator

MM-13751: Fix for incorrect access to delete button.

---

app/components/post/post.js

This change addresses an issue where users viewing a read-only channel could press a user's name and the username would appear in the post textbox allowing the user to send a post. This applies to environments where config key `ExperimentalUsernamePressIsMention` is set to `true`. Instead of mentioning the user in the post textbox, pressing a user's name in a read-only channel will fallback to opening the user's profile detail screen.
N/a

Clicking username in read-only allows sending message

---

app/screens/channel/channel_nav_bar/channel_drawer_button.js

This fixes an edge case when a new notification is received and the app is opened directly from the home icon instead of the notification.
Now the application badge is being set every time the mention count changes, when the mention count is equals to 0 the badge gets cleared along with every notification in the notification manager
https://mattermost.atlassian.net/browse/MM-13722

MM-13722 Reset application badge when there are no more mentions

---

app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap
app/screens/edit_profile/edit_profile.js
assets/base/i18n/en.json

Changes the left button in the edit profile page to Cancel instead of the default close icon.
https://github.com/mattermost/mattermost-server/issues/10078
This PR was tested on: iPhone XR Simulator, iPhone X, 12.1.3

[MM-13439] Change "X" to "Cancel" on Profile page

---

app/components/attachment_button.js
app/screens/terms_of_service/terms_of_service.js
app/utils/status.js

Based on [Android Material Design](https://material.io/design/components/dialogs.html#anatomy) and [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/)
Alert boxes should have the most common action to take by the user to the right and if a cancel option is available it should always be at the left
https://mattermost.atlassian.net/browse/MM-13846

MM-13846 Alert boxes to follow UX Guidelines

---

app/components/__snapshots__/badge.test.js.snap
app/components/badge.js
app/screens/channel/channel_nav_bar/channel_drawer_button.js

Fixes the mention and unread jewel alignment on IOS tablets.
Badge component and unread components needs to be wrapped with a `</view>`  to keep styles relative to each other
[MM-13525](https://mattermost.atlassian.net/browse/MM-13525)
This PR was tested on: [Mobile and tablets emulators of both android and IOS]

MM-13525 Fix alignment of jewel on channel drawer icon

---

app/screens/post_options/post_options.js
app/screens/post_options/post_options_utils.js
app/screens/post_options/post_options_utils.test.js

- Allow showing of all post options if possible to fit 60% of the screen height
- If not, make the last viewable option partially show to indicate more options below on slide up
Jira ticket: [MM-13412](https://mattermost.atlassian.net/browse/MM-13412)
Also added fix to: [MM-13711](https://mattermost.atlassian.net/browse/MM-13711)
Small screen size, iPhone 5s - https://youtu.be/MsFR9mLG3YI
Big Screen size, iPhone x - https://youtu.be/_BfCrLw8acU
Small screen, Android Nexus 5 - https://youtu.be/QzxfNxaDOxA
Big screen, Android Nexus 5 - https://youtu.be/8Z-oy2-HtHo

[MM-13412 & MM-13711] Allow showing of all post options if possible to fit 75% of the screen height

---

app/components/post/index.js
app/components/post_header/index.js
app/components/post_profile_picture/index.js
app/screens/notification/notification.js

When a Webhook is configured to use the user icon instead of the icon override but the server has the `EnablePostIconOverride` config set to true the icon used was the default icon instead. This PR fixes that.
https://mattermost.atlassian.net/browse/MM-13875

MM-13875 Fix user profile icon for a Webhook to follow the prop for use_user_icon

---

app/components/sidebars/main/channels_list/filtered_list/filtered_list.js

This pull request enables tapping on channels while the "Jump to ..." field is in focus by specifying the correct property setting on the FlatList component. Previously, tapping on a channel only dismissed the keyboard and required tapping the channel again. The specified property also allows tapping off of channels to just dismiss the keyboard without loading a channel.
[MM-13649](https://mattermost.atlassian.net/browse/MM-13649)
n/a
This PR was tested on: iPhone 7 Plus (iOS 12.1.3), iPhone X simulator (iOS 12.1),  Android Pixel 2 emulator (Android 8.1.0)
n/a

Enable tapping on channels when jump to textfield is focused.

---

share_extension/android/extension_post/extension_post.js

`loaded` flag is used for showing loader and is only set to true if token and url are present. If app is unauthenticated then the flag never becomes true showing an infinite loader. 
Irrespective of token and url set flag to true at the end of function as async calls will also be completed.
[MM-13866](https://mattermost.atlassian.net/browse/MM-13866)
This PR was tested on: [Android emulator running 8.0]

MM-13866 Never ending loader if app is un authenticated

---

app/screens/edit_profile/edit_profile.js
assets/base/i18n/en.json

This PR removes the possibility to change the eMail within the app, since with https://github.com/mattermost/mattermost-server/pull/10207 we will require the password being submitted as part of an eMail update request. 
CC @crspeller 
https://mattermost.atlassian.net/projects/MM/issues/MM-13839
This PR was tested on: Android Emulator (9.0)

[MM-13839] Remove possibility to change eMail within mobile app

---

app/push_notifications/push_notifications.ios.js
app/screens/channel/channel.js
app/screens/channel/channel_nav_bar/channel_drawer_button.js
ios/Mattermost/AppDelegate.m

Previously we were using the `ChannelDrawerButton` lifecycle to set the badge for the app icon, but if for any reason the `mentionCount` was **0** all the previous notifications got cleared.
Now instead we use the function that clears the notifications for a specific channel to calculate the the badge count based on the remaining notifications.
https://mattermost.atlassian.net/browse/MM-13897

MM-13897 preserve iOS push notifications when opening the app

---

app/store/index.js
app/utils/image_cache_manager.js

The endpoint fetch images through the push proxy needs to be Authorized either by using the cookie or the Authorization header. The image proxy uses the **SiteURL** config setting to set the base URL of the image. In our community/daily deployment the *SiteURL* is set to `https://community.mattermost.com` so when connecting the mobile app to `community-daily` the Cookie will not be use to Authenticate the request thus we need to make sure we set the header correctly to allow the request. This could happen in other deployments if they use the same strategy that we have in community/daily.
https://mattermost.atlassian.net/browse/MM-13859

MM-13859 set the auth token when fetching images from the server

---

app/components/file_attachment_list/file_attachment_document.js

After the initial fix android was not previewing a document file more than once. the reason for it is because the library that we use do not have a handler for `DoneButtonEvent` so we are going to wait for 4 seconds before enabling the option.
https://mattermost.atlassian.net/browse/MM-13665

Fix previewing doc files more than once on Android

---

app/components/profile_picture/profile_picture.js

For some reason android was not re-rendering the Image component when only setting the defaultSource property thus the decision to render the component with the profile placeholder as the source.
https://mattermost.atlassian.net/browse/MM-13976

MM-13976 Fix placeholder image on Android when profile pic is removed

---

app/actions/views/login.js
app/screens/login/login.js
app/screens/select_server/index.js
app/screens/select_server/select_server.js
app/screens/sso/index.js
app/screens/sso/sso.js

Sometimes after we login the session is not retrieved successfully from the server, with this PR we are going to wait 10 seconds before retrieving the session information and then schedule the session expired notification
**Note:** The best way to ensure this is by having access to the session length but the config does not provide that info.
https://mattermost.atlassian.net/browse/MM-13830
This PR was tested on: Android 7, 8 and 9 as well as iOS

Ensure schedule of session expired notification

---

app/components/markdown/markdown_link/markdown_link.js
app/utils/url.js

Enable permalink view via relative links.
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2330
Propose that this PR should be added in the 1.16.0 release as this is a common case with community and community-daily
https://mattermost.atlassian.net/browse/MM-14005
Discussion: https://community-daily.mattermost.com/private-core/pl/fqo3s4w5w38x7f48m6pbxccpee

Add support for relative permalinks

---

app/fetch_preconfig.js
app/screens/select_server/select_server.js
app/utils/network.js
package-lock.json
package.json

When iOS devices are enrolled with an EMM provider that has a setup to use an on-demand VPN in the actual VPN is not connected by the time the Mattermost app is opened, the first connection (ping) will always fail. This causes the users not to be able to connect to the server until the VPN is manually connected.
With this PR we added an option called [waitsForConnectivity](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/2908812-waitsforconnectivity?language=objc) only available in iOS 11+ that will wait until the VPN actually connects. The default timeout is **7 days** but I've changed it to be 10 seconds.
The actual fix that adds the above explain property is [here in our react-native-fetch-blob fork](https://github.com/enahum/react-native-fetch-blob/tree/8f …

MM-13337 Fix EMM connections using VPN on-demand

---

package-lock.json
package.json

Uses https://github.com/mattermost/mattermost-redux/pull/735 hash for fixing Opening channels with unreads has loading indicator placed above unread messages line
[MM-13428](https://mattermost.atlassian.net/browse/MM-13428)

MM-13428 Opening channels with unreads has loading indicator placed above unread messages line

---

app/components/network_indicator/network_indicator.js

Fixes the UI for the "No internet connection" banner not showing. Turns out the app was successfully detecting the connection toggling, however, the UI didn't show because a property (`opacity`) setting the opacity wasn't triggering render on the component and so remained hidden until the next render was triggered.
This PR converts the `opacity` properly into a component prop, allowing RN to detect changes and re-render the component as needed.
This PR also fixes a case where the app doesn't recognize the connection coming back if it was launched while the device is offline.
[MM-13720](https://mattermost.atlassian.net/projects/MM/issues/MM-13720)
n/a
This PR was tested on: iPhone 7 Plus (iOS 12.1.3), iPhone X Simulator (iOS 12.1), Android Pixel 2 Emulator (Android 8.1.0)
n/a

[MM 13720] Fix for "No internet connection" banner not always showing

---

app/components/post_body/post_body.js
app/components/post_body/post_body.test.js

The web app has the `PostAttachmentOpenGraph` component not mount for system messages, but I didn't want to pass `isSystemMessage` all the way down to it. I also couldn't think of any cases where `PostBodyAdditionalContent` would be needed for a system message.
https://mattermost.atlassian.net/browse/MM-14001
- [Added or updated unit tests (required for all new features)

MM-14001 Don't mount PostBodyAdditionalContent for system messages

---

app/screens/permalink/permalink.js

Load channel from server if it doesn't exist in Redux even if not joining.
https://mattermost.atlassian.net/browse/MM-14055
* iPhone X, iOS 12.1 (emulator)

MM-14055: Load the channel even if not joining.

---

app/components/markdown/transform.js
app/components/markdown/transform.test.js

A blank mention key would cause the app to try to match, via regex, the boundary of every word character for every post for the current channel. This PR prevents blank matches from being considered as valid mentions, preventing the app from trying to make every word boundary character into a match and crashing in the process.
[MM-13934](https://mattermost.atlassian.net/projects/MM/issues/MM-13934)
This PR was tested on: iPhone X Simulator (iOS 12.1)

[MM 13934] Prevent blank mention keys from crashing the app

---

app/actions/views/channel.js
app/actions/views/root.test.js
app/components/markdown/markdown_link/index.js
app/components/markdown/markdown_link/markdown_link.js
app/components/post_list/__snapshots__/post_list.test.js.snap
app/components/post_list/index.js
app/components/post_list/post_list.test.js
app/components/post_list/post_list_base.js
app/constants/deep_linking.js
app/constants/index.js
app/utils/url.js

This change allows for deep linking within the app of valid channel links (e.g. "https://server-url.com/[team-name]/channels/[channel-name]"). Channel links posted within a chat, when clicked,  open the channel referenced in the link mimicking the behavior of channel mention.
N/a
This PR was tested on: iPhone X (iOS), iPad Air 2 (iOS), Nexus 6 (Android)

Deep linking based on channel url

---

app/components/post_list/post_list.ios.js
app/components/post_list/post_list_base.js
app/constants/screen.js
app/screens/thread/__snapshots__/thread.test.js.snap
app/screens/thread/thread.js

The issue is isolated only on iOS but not on Android.  It's happening both on channel and thread screen when the height of the layout is greater than the content - (in short, the entire screen is not filled up by posts).
Posting a message like multiline or jumbo emojis causes the FlatList component for iOS to render RefreshControl component and remain the space as is when it's unmounted, leaving a whitespace of ~64 units of height between input box and post list.  I don't have a minimal repro steps but looks like it's a bug with the react-native's FlatList component.
The fix explicitly pull down the list to recent post when pageOffsetY is less than zero, and the height of the layout is greater than its content or is on a thread screen.  Might not be a good solution but this fixes the …

[MM-14017] Fix whitespace between input box and post list on iOS

---

app/actions/views/login.js
app/actions/views/login.test.js
app/app.js
app/mattermost.js
app/utils/security.js

This sets the CSRF token after login / after page load in the Client4, which is returned as part of the login flow from the server.
**Note:** This was tested on Android only, I would appreciate some testing on iOS.
https://mattermost.atlassian.net/browse/MM-10346
**Redux:** https://github.com/mattermost/mattermost-redux/pull/753
**Server:** https://github.com/mattermost/mattermost-server/pull/10067
This PR was tested on: Android Emulator (9.0)

[MM-10346] Set CSRF Token from Cookie after Login / on App load

---

android/app/src/main/java/com/mattermost/share/RealPathUtil.java
android/app/src/main/java/com/mattermost/share/ShareModule.java

Sometimes when sharing files it could be that the mime type returns null, this PR will prevent a crash when that happens.
https://mattermost.atlassian.net/browse/MM-14249

Prevent the app from crashing when file mime type is null

---

android/app/build.gradle
package-lock.json
package.json

This PR migrates Android to use FCM instead of GCM.
> As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more.
* If the server still uses GCM before April 11 2019 the apps with GCM and with this PR that includes FCM will receive notifications.
* If the server is updated to use FCM (see https://github.com/mattermost/mattermost-push-proxy/pull/38) the apps using GCM and FCM (with this PR) will receive notifications
* If the server still uses GCM after April 11 2019 the apps won't receive notifications at all.
The actual migration was …

[MM-10380] Migrate Android from GCM to FCM

---

app/screens/reaction_list/reaction_list.js
app/screens/reaction_list/reaction_list.test.js

Fixes the prop type for a post's reactions. There's a related change in [mattermost-redux](https://github.com/mattermost/mattermost-redux/pull/778) but it is not required to update the mattermost-redux dependency in `package.json`. 
https://mattermost.atlassian.net/browse/MM-13954
* iPhone 8, iOS 12.1.4

[MM-13954] Fix prop type for post reactions

---

app/components/message_attachments/attachment_title.js
app/components/message_attachments/message_attachment.js

This PR makes it possible to render emojis in Message Attachment title.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-14193) | Fixes [GitHub issue #10291](https://github.com/mattermost/mattermost-server/issues/10291)
N/A
This PR was tested on: iPhone X with iOS 12.1, Nexus 5X with Android 9.0

[MM-14193] Render emojis in Message Attachment title

---

app/utils/network.js

In order to better support connection scenarios like VPN's connecting etc, a change was made that caused the "No internet connection" banner to not show up for a minute (native timeout value) after a connection is lost while waiting for confirmation from a ping of the MM server. This PR allows the "No internet connection" banner to show up immediately when a connection is actually down.
[MM-14044](https://mattermost.atlassian.net/projects/MM/issues/MM-14044)
n/a
This PR was tested on: iPhone X Simulator (iOS 12.1), iPhone Xs (iOS 12.1.4)
n/a

[MM-14044] Fix for "No internet connection" not showing up for a minute after connection loss

---

package-lock.json
package.json

We're seeing Android crashes due to a NullPointerException being thrown when [getReactEventEmitter()](https://github.com/wix/react-native-navigation/blob/v1/android/app/src/main/java/com/reactnativenavigation/bridge/EventEmitter.java#L95) returns null. A patch is included in a fork of the library that recreates the event emitter if it is null prior to emitting the app launched event (commits [71c064](https://github.com/migbot/react-native-navigation/commit/71c06483c9a5a6f36911abf02456c3763f3a085a) and [03c623](https://github.com/migbot/react-native-navigation/commit/03c623c373f818827a463ca0fe90f86f56e71b2f))
[MM-14078](https://mattermost.atlassian.net/browse/MM-14078)
Samsung SM-G930V, Android 7.0

[MM-14078] Use forked react-native-navigation with v1 patch for NullPointerException

---

android/app/src/main/java/com/mattermost/share/ShareModule.java

Proceed to get path to shared content only if the uri is not null. This will prevent a crash from calling `getScheme()` on null.
https://mattermost.atlassian.net/browse/MM-14150
* Samsung SM-G930V, Android 7.0

[MM-14150] Check for null uri prior to getting path to shared content

---

android/app/src/main/java/com/mattermost/share/ShareModule.java

Proceed to extract URL from data and upload shared content only if data has the `url` key. This will prevent a crash from a NoSuchKeyException.
https://mattermost.atlassian.net/browse/MM-14151
* Samsung SM-G930V, Android 7.0

[MM-14151] Ensure data has url key before attempting upload

---

android/app/build.gradle
android/build.gradle
package-lock.json
package.json

The mobile app was crashing on Android after migrating to FCM, this PR updates the notification library as well as the google-services plugin to avoid that.
https://mattermost.atlassian.net/browse/MM-14352

Fix crash when fresh install android when getting the fcm token

---

app/initial_state.js
app/screens/login/index.js
app/screens/login/login.js
app/screens/mfa/mfa.js
app/utils/security.js

This pull request is the mobile changes related to Server PR https://github.com/mattermost/mattermost-server/pull/10356 - It changes the current way how we determine if a user has MFA enabled or not. 
Previously a separate request was made with the user eMail to determine if MFA is turned or not, which resulted in a leak of the users MFA status without having any information but the users email. The new implementation will attempt to login without MFA, and if the server returns an MFA error show MFA form.
**To Do - Pointers appreciated:**
- Don't show error on first login request if MFA error is returned and MFA screen wasn't shown yet
- Remove ESLint line ignore (?)
https://mattermost.atlassian.net/projects/MM/issues/MM-14081
This PR was tested on: Android 9.0 Emulator, Fedora 28

[MM-14081] Show MFA Prompt after Server returned error for login request

---

app/components/combined_system_message/combined_system_message.js

Adds new strings for team/channel related messages for better translatability.
Proper translation to the german language  was impossible before.
https://github.com/mattermost/mattermost-server/issues/10335
[MM-13824]

[MM-13824] add one_you strings for better translatability

---

.gitignore
Makefile

Add make command to generate unsigned x86_64 build for VM/simulator.  The resulting app (in zip file) is verified as working for Rainforest.  Generated and submitted zip file can be found here - [Mattermost-unsigned-x86_64.app.zip](https://s3.amazonaws.com/x86-64/ios-1.16.1/Mattermost-unsigned-x86_64.app.zip).
This PR does not include yet the following:
- code signing
- auto-upload to S3
Will address separately if those are necessary to be incorporated in our build workflow.
Note that our existing Android release app is confirmed to be working on Rainforest's VM/emulator.
Jira ticket: [MM-14238](https://mattermost.atlassian.net/browse/MM-14238)
This PR was tested on: [iOS simulator]

[MM-14238] Add make command to generate unsigned x86_64 build for VM/simulator

---

app/components/markdown/markdown_link/markdown_link.js
app/components/post_list/post_list_base.js
app/utils/url.js
app/utils/url.test.js

Fix intermittent crash when selecting a link.  The crash happen when it tries to do regex (replace) on undefined text.  Such text is either serverURL or siteURL which eventually resolves with the correct value.
Note that this fix is also to be backported to 1.16.
Jira ticket: [MM-14312](https://mattermost.atlassian.net/browse/MM-14312)

[MM-14312] Fix intermittent crash when selecting a link

---

app/screens/settings/notification_settings_email/index.js

Fix default email notification interval from never to immediate.
Main issue on ticket being out of sync between RN and desktop app was fixed by https://github.com/mattermost/mattermost-webapp/pull/2416.  This is just a follow up PR to correct the dafault value.
Jira ticket: [MM-14296](https://mattermost.atlassian.net/browse/MM-14296)
This PR was tested on: [iOS, Android simulators]

[MM-14296] Fix default email notification interval from never to immediate

---

ios/UploadAttachments/UploadAttachments/UploadManager.swift

If the name of the filename contains spaces we need to url encoded it.
https://mattermost.atlassian.net/browse/MM-14387

Fix regression when sharing files with spaces in the filename

---

app/actions/views/channel.js
app/components/sidebars/main/main_sidebar.js

Fixes a regression when switching teams was not updating the channel name in the channel screen
https://mattermost.atlassian.net/browse/MM-14376

Set the correct channel display name when switching teams

---

ios/Mattermost.xcodeproj/project.pbxproj

Fixes the build by adding `UploadAttachments` library as a target of Mattermost and MattermostShare in iOS
FYI: @dseawel thanks for reporting

Add target to Mattermost and MattermostShare

---

app/fetch_preconfig.js
app/utils/network.js
package-lock.json
package.json

Previously we added a property to fetch `waitsForConnectivity` that only applied for the `ping` endpoint that indicated that the request should wait until the VPN connection was established.
The previous approach had some issues:
1. Users that did not need a VPN connection were force to wait for 60 seconds if their server wasn't using SSL and even 120 seconds if the server was down to get an error message.
2. Users under VPN had some other issues when the VPN was disconnected and they were already logged in as the flag only worked for the `ping` endpoint instead of every request, thus the app was behaving strangely.
This PR handles the flag for `waitsForConnectivity` and also includes a value for `timeout` with a couple of AppConfig settings (managed configuration through EMM providers) …

Wait for VPN connection only when appconfig flag is set

---

app/screens/channel_add_members/channel_add_members.js
app/screens/channel_add_members/channel_add_members.test.js
app/screens/channel_add_members/index.js

Do not show deactivated users when adding members.
Unit test is added, not exhaustive but good start to have.
Jira ticket: [MM-13418](https://mattermost.atlassian.net/browse/MM-13418)

[MM-13418] Do not show deactivated users when adding members

---

app/components/markdown/transform.js
app/components/markdown/transform.test.js

Enable to highlight CJK mention key in sentense.
[\[Help Wanted\] \[MM\-10193\] Words that trigger mentions does not support Chinese · Issue \#8642 · mattermost/mattermost\-server](https://github.com/mattermost/mattermost-server/issues/8642)
[\[MM\-10193\] Words that trigger mentions does not support Chinese \- Mattermost](https://mattermost.atlassian.net/browse/MM-10193)
This PR was tested on: iOS 11.2, iPhone X Simulator

[MM-10193] Enable to highlight CJK mention key

---

app/components/message_attachments/attachment_title.js

This PR makes it possible to render hyperlinks in Message Attachment title.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-14192) | Fixes [GitHub issue #10292](https://github.com/mattermost/mattermost-server/issues/10292)
N/A
This PR was tested on: iPhone X with iOS 12.1, Nexus 5X with Android 9.0

[MM-14192] Render hyperlinks in Message Attachment title

---

app/actions/views/channel.js
app/screens/channel/channel_post_list/channel_post_list.js
app/screens/flagged_posts/flagged_posts.js
app/screens/long_post/long_post.js
app/screens/permalink/index.js
app/screens/permalink/permalink.js
app/screens/permalink/permalink.test.js
app/screens/pinned_posts/pinned_posts.js
app/screens/recent_mentions/recent_mentions.js
app/screens/search/search.js
app/store/middleware.js
app/store/middleware.test.js
package-lock.json
package.json

The two major changes here are:
1. As in the web app changes, `increasePostVisibility` now uses `getPostsBefore` and `getPostsAfter` instead of paging. @enahum I had to comment out some of that logic used for bi-directional scrolling because it doesn't actually work with `postVisibility`.
2. I had to refactor some of the cleanup middleware so that I could properly test that it still works with the new `postInChannel`
See https://github.com/mattermost/mattermost-redux/pull/781 for more details.
Redux PR: https://github.com/mattermost/mattermost-redux/pull/781
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2411
https://mattermost.atlassian.net/browse/MM-13958
https://mattermost.atlassian.net/browse/MM-13959
This …

MM-13958/MM-13959 Make postsInChannel into a sparse array

---

app/screens/channel_add_members/channel_add_members.js
app/screens/channel_members/channel_members.js
app/screens/more_channels/more_channels.js
app/screens/more_dms/more_dms.js
app/screens/selector_screen/selector_screen.js

Fix multiple text entries when typing with Shift+Letter on Android
- by keeping the text case sensitivity on state, means the textbox will show case-sensitive letters
- by doing lowercase if necessary, like calling search action, filter action, etc
Note:  Issue is happening only Android but I also verified that this change don't have side effect to iOS functionality.
Jira ticket: [MM-14476](https://mattermost.atlassian.net/browse/MM-14476)
This PR was tested on: [Android emulator, iOS simulator]

[MM-14476] Fix multiple text entries when typing with Shift+Letter on Android

---

app/screens/settings/notification_settings_email/notification_settings_email.android.js
app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
app/screens/settings/notification_settings_email/notification_settings_email.ios.js
app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
app/screens/settings/notification_settings_email/notification_settings_email_base.js

This ticket is related to Android but minor change is done to iOS as well.  Tested on both platforms.
On Android:
- do not save email interval preference on cancel
- remove duplicate call in saving email interval preference on back button since saving is handled already on pressed on save button.
- only save when there's actual change
On iOS:
- only save when there's actual change
Jira ticket: [MM-14460](https://mattermost.atlassian.net/browse/MM-14460)

[MM-14460] Do not save email interval preference on cancel on Android device

---

app/actions/views/channel.js
app/actions/views/root.js

Fix channel mention when app is started from push notification by adding flag to `handleSelectChannel` that the call is from push notification.
Jira ticket: [MM-14466](https://mattermost.atlassian.net/browse/MM-14466)

[MM-14466] Fix channel mention when app is started from push notification

---

app/selectors/autocomplete.js
app/selectors/autocomplete.test.js

Invoke `toLowerCase()` on the match result, matching the webapp behaviour re: same.
We /could/ also do this on the server, but there are local at-mention autocompletes as well and they need the same `toLowerCase()` logic anyway.
https://mattermost.atlassian.net/browse/MM-14461

MM-14461: make @-mentions (and searches) case insensitive

---

app/utils/url.js

Fix relative URL permalink by removing null/empty check to `rootURL` of `matchPermalink` and continue to return matched relative URL. 
This only happened on release-1.17 but not on master.
Jira ticket: [MM-14589](https://mattermost.atlassian.net/browse/MM-14589)

[MM-14589] Fix relative URL permalink

---

app/actions/views/channel.js
app/actions/views/root.js
app/fetch_preconfig.js
app/utils/push_notifications.js

Fix channel mention badge and posts after opening the app from push notification (which was initially at closed state)
- the `app.startAppFromPushNotification` is being set twice, first as `true` then `false` causing the post visibility to have `NaN` value and wiped out the posts which were initially rendered in a channel screen.
- clearing of mention badge is fixed by correctly identifying the case when to mark channel as read and viewed
- commented online check that potentially causing to stop API requests.  Such online check is actually handled natively but added a note just in case we encountered related out-of-memory issue on Android in the future.
@enahum Thank you very much for figuring this out and giving your full time.  I really appreciate it very much and sorry for asking for …

[MM-14587] Fix channel mention badge and posts after opening the app from push notification (which was initially at closed state)

---

app/screens/settings/notification_settings_email/notification_settings_email.android.js
app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
app/screens/settings/notification_settings_email/notification_settings_email.ios.js
app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
app/screens/settings/notification_settings_email/notification_settings_email_base.js

Fix email setting of being set to "Never" when first saved (hitting back button on iOS) without actually changing the selection.
Jira ticket: [MM-14527](https://mattermost.atlassian.net/browse/MM-14527)

[MM-14527] Fix email setting to "Never" when first saved (hitting back button on iOS) without actually changing the selection

---

ios/Mattermost.xcodeproj/project.pbxproj
ios/Mattermost/AppDelegate.m
ios/Mattermost/Dummy.swift
ios/Mattermost/RuntimeUtils.swift

When the app receives a clear notification it will then remove the notifications that belong to that channel from the notification center.
The problem was that `didReceiveRemoteNotification` needs to inform the notification center that something has changed by using the `completionHandler` and we were always returning that there was no new data.
In this PR we return the `completionHandler` with `UIBackgroundFetchResultNewData` that will tell the notification center that it needs to update, thus the notification are properly removed.
The **RuntimeUtils** is just a way to add a delay, the reason for this is that the notification center function `removeDeliveredNotificationsWithIdentifiers` is asynchronous and we need to make sure that completes before we call the `completionHandler`, so by …

MM-14292 Clear iOS notifications on channel read

---

app/components/search_bar/search_bar.android.js

Honestly, I cannot reproduced the issue of "extra text in search box after using autocomplete drop down - Android only".  Looks like easy to repro from Dylan but I couldn't have it even a single one out of many trials.
This PR eliminates the use of state.value and just rely on props.value for the searchbar on Android.  I'm guessing it's somewhat a race condition between the state and an update from props' value.  If not solving the issue, then this is a good first step in realizing the root cause.
Jira ticket: [MM-14389](https://mattermost.atlassian.net/browse/MM-14389)
This PR was tested on: [Android emulator]

[MM-14389] Remove state.value and rely only on props.value for searchbar on Android

---

Makefile
native_modules/RNCWKWebView.m
native_modules/RNCWebViewManager.java

This PR adds support for **Integrated Windows Authentication** on both Android and iOS. The changes are made in the RNCW* on `native_modules` folder to avoid the need to fork the `react-native-webview` library.
When the webview receives a `Kerberos` or `NTLM` authentication challenge the app will then show a system dialog prompting the user for credentials and then completing the authentication challenge using those credentials.
https://mattermost.atlassian.net/browse/MM-13714
https://mattermost.atlassian.net/browse/MM-13715
This PR was tested on: Android 7,8 and 9 and iOS 10.3 and 12.1
The test was against the Lab created by `@john.thompson` that includes authenticating using O365

MM-13714 & MM-13715 IWA support for Android and iOS

---

app/mattermost.js
app/store/index.js
app/store/middleware.js

When opening a notification the first thing that happens is we check if the `hydrationComplete` is true to ensure that the redux store has been loaded and we have access to its data.
When sending the app to the background we perform a cleanup of the redux state to try and avoid memory pressure (that can cause performance degradation). When this happens sometimes the `hydrationComplete` under `views.root` was reset and the original value is set to **false**.
Also when resetting the `Cache and Documents data` the same state is set to its original value which is **false**
This PR corrects that by ensuring in both cases that `hydrationComplete` remains as **true**
https://mattermost.atlassian.net/browse/MM-14459

MM-14459 Ensure hydrationComplete is set to true

---

app/actions/views/create_channel.js
app/actions/views/create_channel.test.js

Generate random channel URL name from display names that don't clean into a usable name. This will fix cases where non-latin characters are used in the display name but are not convertible to a usable channel name.
https://mattermost.atlassian.net/browse/MM-14498

MM-14498 Generate random channel URL name from display names that don't clean into a usable name

---

app/components/message_attachments/action_button/action_button.js
app/utils/tap.js

This PR submits a basic approach using react state to disable buttons immediately after clicking.
More consideration could be made to disable appropriate buttons only - for cases where buttons can be clicked more than once, this here is a demonstration of a basic implementation.

MM-13151 Increase double tap delay for post action buttons

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Call setNumber on notification only if badge is not null and add bundle to empty list so that test notification message is handled.
https://mattermost.atlassian.net/browse/MM-14866

[MM-14866] Fix app crash due to parseInt call on null and display test notification message

---

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java

Previously, the sender name was set by taking the first result from splitting the message on `:`. Since generic messages do not contain a `:`, the message itself was being set as the sender name.
https://mattermost.atlassian.net/browse/MM-14871
* Emulator, Android 9

[MM-14871] Fix extraction of sender name for push notifications

---

app/components/file_upload_preview/file_upload_item/file_upload_item.js
app/screens/edit_profile/edit_profile.js

This PR manually sets the `X-CSRF-Token` header for operations that do not rely on `Client4` for non-get HTTP requests to avoid missing token warning.
https://mattermost.atlassian.net/projects/MM/issues/MM-14698
This PR was tested on: Android 9 Emulator

[MM-14698] Add CSRF Header in File Upload and Profile Image Set Operations

---

package-lock.json
package.json

Update commit of commonmark.js that fixes "blank spaces break markdown table".  Actual fix can be found at - https://github.com/mattermost/commonmark.js/commit/6c3136c18ae8bb7842f8491d160f370a334fd903.  Unit test is added there as well.
Jira ticket: [MM-13516](https://mattermost.atlassian.net/browse/MM-13516)

[MM-13516] Update commit of commonmark.js that fixes "blank spaces break markdown table"

---

ios/MattermostShare/ShareViewController.swift

Use the `as?` operator over `as!` to return nil and avoid a crash in the case where `item` is not a URL.
https://mattermost.atlassian.net/browse/MM-14821
* iPhone 8, iOS 12.1.4

[MM-14821] Avoid force casting items to URL

---

android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java

Removed package name from push notification content.
https://mattermost.atlassian.net/browse/MM-14918
* Android emulator running Android 9

[MM-14918] Do not display package name in failed push notification reply message

---

ios/MattermostShare/ShareViewController.swift

Added handling of UIImage type items in the iOS share extension.
https://mattermost.atlassian.net/browse/MM-14899
* iPhone 8, iOS 12.1.4

[MM-14899] Support sharing of screenshots via the iOS share extension

---

app/components/channel_icon.js
app/components/vector_icon.js

The PR that introduced support for bot accounts #2669 changed the icons from `FontAwesome` to `FontAwesome5` causing the icons to change, this PR reverts to use the same `FontAwesome` for previous icons to avoid changes in the UI and includes support for `FontAwesome5` for the new bot account type
https://mattermost.atlassian.net/browse/MM-14960

MM-14960 Use the correct icon set for channel types

---

app/screens/post_options/index.js

Set `canFlag` to false for system messages.
https://mattermost.atlassian.net/browse/MM-14954

[MM-14954] Set canFlag to false for system messages

---

app/components/message_attachments/action_button/action_button.js
app/components/message_attachments/action_button/action_button_text.js
app/components/message_attachments/action_button/action_button_text.test.js
app/utils/emoji_utils.js

This PR makes it possible to render emojis in Interactive Message Buttons.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-14823) | Fixes [GitHub issue #10290](https://github.com/mattermost/mattermost-server/issues/10290)
N/A
This PR was tested on: iPhone X with iOS 12.1, Nexus 5X with Android 9.0

[MM-14823] Render emojis in Interactive Message Buttons

---

ios/MattermostShare/ChannelsViewController.swift
ios/MattermostShare/ShareViewController.swift
ios/MattermostShare/TeamsViewController.swift

on iOS 11+ the way the search bar is displayed is as part of the Navigation bar instead of in the table header, the Search bar then looks trimmed in comparison, so in this PR we do a few things:
1. Show the Search bar when entering the select channel screen
2. Modify the Search Bar to add some padding at the top (this is done by adding an offset to the background and then moving the Cancel button down)
3. The title of the navigation bar to select the channel now shows the team display name instead of the word "Channels"
4. The title of the navigation bar to select the team is now singular (Team instead of Teams)
5. The placeholder to write text is now "Write to <Channel name>"
https://mattermost.atlassian.net/browse/MM-14959

MM-14959 iOS Share Extension channel search open by default

---

app/components/channel_loader/index.js

This change avoids the situation where the `state.views.channel.loading` value is used if `ownProps.channelIsLoading` is false. This may or may not be a contributing issue to MM-15022.
https://mattermost.atlassian.net/browse/MM-15022

[MM-15022] Ensure the correct value for channelIsLoading is used

---

app/screens/flagged_posts/flagged_posts.js
app/screens/pinned_posts/pinned_posts.js
app/screens/recent_mentions/recent_mentions.js
app/screens/search/search.js

After [#2693](https://github.com/mattermost/mattermost-mobile/pull/2693) merged to `master` branch, there's bug in the post search screen. `DateHeader` component doesn't render the date properly. Now, it looks like this.
So i fixed `app/screens/search.js` file to render the `DateHeader` normally.
This PR has just 2 lines of code change, so there's no ticket but related to [#2693](https://github.com/mattermost/mattermost-mobile/pull/2693)
None apply
This PR was tested on: Samsung Galaxy Note 9, Android 9
Mattermost Server: v5.6.0

DateHeader rendering bug fix

---

app/components/message_attachments/action_menu/action_menu.js
app/components/message_attachments/action_menu/action_menu.test.js
app/components/message_attachments/attachment_actions.js

This PR is pretty straightforward. This value starts selected in the dropdown, allowing integrations to "save" a value which we wanted for the NPS plugin.
Server PR: https://github.com/mattermost/mattermost-server/pull/10659
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2677
https://mattermost.atlassian.net/browse/MM-14741

MM-14741 Add default option to post action dropdown

---

app/components/post_body/post_body.js

This change address a bug where Reminder ephemeral posts (using the `/remind` command) did not show message text.
https://mattermost.atlassian.net/browse/MM-15050

MM-15050 Reminder message (`/remind`) do not show message text on mobile.

---

app/components/search_bar/search_bar.android.js
app/components/search_bar/search_bar.ios.js
app/components/search_bar/search_box.js
app/components/sidebars/main/channels_list/channels_list.js
app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
app/components/sidebars/main/main_sidebar.js
app/screens/more_channels/__snapshots__/more_channels.test.js.snap
app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap

There are two scenarios where the search bar animation stutters in the main side bar for iOS:
1. When the drawer is expanded on focus of the search box and then shrunk on cancel of the search.
2. When the SwitchTeamsButton goes in and out of view on focus of the search box.
This PR removes the expansion of the drawer as well as passes the SwitchTeamsButton to SearchBox via a new prop, `leftComponent`, so that the SwitchTeamsButton animation can be handled along with the search bar animations.
https://mattermost.atlassian.net/browse/MM-14541
* iPhone 8, iOS 12.1.4
Before:
iOS
Android
After:
iOS
Android

MM-14541 Fix search bar animation stutter in main search bar

---

app/constants/image.js
app/utils/images.js
app/utils/images.test.js

When a 0 height and/or width is passed to `calculateDimensions`, a `NaN` value can be returned for width and/or height. Passing this value to the Image component crashed the app. With this change we check for 0 height/width and return default dimensions.
https://mattermost.atlassian.net/browse/MM-14669
* iPhone XS emulator, iOS 12.1
iOS
Android

[MM-14669] Return null dimensions when height or width is falsy

---

ios/MattermostShare/ShareViewController.swift
ios/UploadAttachments/UploadAttachments/AttachmentArray.swift
ios/UploadAttachments/UploadAttachments/AttachmentItem.swift
ios/UploadAttachments/UploadAttachments/Constants.h
ios/UploadAttachments/UploadAttachments/Constants.m
ios/UploadAttachments/UploadAttachments/StoreManager.h
ios/UploadAttachments/UploadAttachments/StoreManager.m

The share extension on iOS was crashing when it received a 400 response due to a shared image being too large. These changes are for checking attached image sizes and alerting the user if any images are over the size limit. The value for `DEFAULT_SERVER_MAX_IMAGE_SIZE` was taken from [file.go](https://github.com/mattermost/mattermost-server/blob/master/app/file.go#L57).
https://mattermost.atlassian.net/browse/MM-14836
Image attachment:
File attachment:

[MM-14836] Prevent sharing of images over max pixels

---

app/screens/channel_info/channel_info_header.js

The PostBody passes a [lineHeight](https://github.com/mattermost/mattermost-mobile/blob/MM-13650/app/components/post_body/post_body.js#L478) of 20 to the Markdown component. I do the same in ChannelInfoHeader for iOS so emojis in the channel's header and purpose sections render the same as in a post.
https://mattermost.atlassian.net/browse/MM-13650
iOS
Android

Match lineHeight used in ChannelInfoHeader to PostBody's

---

app/components/post_list/post_list.ios.js
app/components/post_textbox/components/typing/typing.js

There were some app crashes caused by `handleScrollToRecentPost` scrolling to an index that was out of range. While I wasn't able to reproduce that scenario, I found that the cause of the blank space issue described in [MM-14017](https://mattermost.atlassian.net/browse/MM-14017) was the Typing component height animation being too quick when it's set back to 0. By increasing the duration a bit, the FlatList has enough time to handle the content size change resulting from a new post arrival before handling the change caused by the Typing component height change.
https://mattermost.atlassian.net/browse/MM-14834
Before:
After:

[MM-14834] [MM-14835] Increase Typing animation duration and remove handleScrollToRecentPost

---

android/app/src/main/java/com/mattermost/share/ShareModule.java

Check for null activity in ShareModule before calling finish.
https://mattermost.atlassian.net/browse/MM-14837

[MM-14837] Check for null activity in ShareModule before calling finish.

---

app/components/post_textbox/post_textbox.js

On iOS, if the PostTextbox height increases from its initial height (due to a multiline post or a post whose message wraps, for example), then when the text is cleared the PostTextbox height decrease will be animated. This animation in conjunction with the PostList animation as it receives the newly created post is causing issues in the iOS PostList component as it fails to properly react to its content size changes. While a proper fix is determined for the PostList component, a small delay in triggering the height decrease animation gives the PostList enough time to first handle content size changes from the new post.
There is a similar issue that was fixed by [PR-2730](https://github.com/mattermost/mattermost-mobile/pull/2730), however, I overlooked this problem when I removed …

[MM-14834] [MM-14835] Delay PostTextbox animation on iOS when clearing text

---

app/components/__snapshots__/attachment_button.test.js.snap
app/components/__snapshots__/profile_picture_button.test.js.snap
app/components/attachment_button.js
app/components/attachment_button.test.js
app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap
app/screens/edit_profile/edit_profile.js
assets/base/i18n/en.json
package-lock.json
package.json

This is the same as [PR-2715](https://github.com/mattermost/mattermost-mobile/pull/2715) but for release-1.19. The mattermost-redux commit hash is for the latest release-5.11 commit.

[MM-14887] Allow only jpeg, png, and bmp profile image uploads

---

app/fetch_preconfig.js
app/mattermost_managed/mattermost-managed.ios.js
ios/Mattermost/MattermostManaged.h
ios/Mattermost/MattermostManaged.m

While checking some EMM configurations I realized that we were listening to the wrong event in the fetch_preconfig file, and improved the Native module by removing the bridge.
N/A

Remove the RN bridge from MattermostManaged
