mattermost/mattermost-mobile

app/components/post_list/post_list_base.js, app/screens/flagged_posts/flagged_posts.js, app/screens/pinned_posts/pinned_posts.js, app/screens/recent_mentions/recent_mentions.js, app/screens/search/search.js
We were listening to the wrong event type for mattermostManaged configuration changes and is crashing iOS (at least in dev mode)
=> Fix mattermostManaged event name

android/app/src/main/AndroidManifest.xml
Please make sure you've read the [pull request](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) section of our [code contribution guidelines](https://developers.mattermost.com/contribute/getting-started/).
Cannot install Mattermost when there is no enough space in internal memory, So when add this line
android:installLocation="auto" 
to the manifest file user can install Mattermost on the sd card.
https://developer.android.com/guide/topics/data/install-location
None
This PR was tested on: LG K8 - Android 6.0
=> Allow user to install mattermost on sd card

android/app/src/main/java/com/mattermost/rnbeta/MattermostPackage.java, android/app/src/main/java/com/mattermost/rnbeta/RNTextInputResetModule.java, app/components/autocomplete/autocomplete.js, app/components/post_textbox/post_textbox.js
On some Android keyborads (Samsung for example), autocompleting and then typing would cause the cursor to jump backwards to the position it was in before the autocomplete suggestion was selected.
Thanks to @hmhealey for pointing me at https://github.com/facebook/react-native/pull/12462 which contained the workaround to fix this.
https://mattermost.atlassian.net/browse/MM-15315
Galaxy S9, Android 9, Samsung and Google keyboards
=> MM-15315 Add native module to reset TextInput to fix bad cursors in some Android keyboards

app/components/file_attachment_list/file_attachment.js, app/components/markdown/markdown.js, app/components/markdown/markdown_image/markdown_image.js, app/components/message_attachments/attachment_fields.js, app/components/message_attachments/attachment_image.js, app/components/message_attachments/attachment_pretext.js, app/components/message_attachments/attachment_text.js, app/components/message_attachments/message_attachment.js, app/components/post_attachment_image/index.js, app/components/post_attachment_opengraph/post_attachment_opengraph.js, app/components/post_attachment_opengraph/post_attachment_opengraph.test.js, app/components/post_body/post_body.js, app/components/post_body_additional_content/post_body_additional_content.js, app/utils/images.js, app/utils/images.test.js
This should hopefully fix the mobile app running out of memory when it attempts to load a large gif into memory. The sample gif that I've been using is only a few MB on disk, but it expands to a few hundred when loaded into memory which quickly causes the OS to terminate the app.
For now, I just have those large gifs render as null instead of using some sort of placeholder. I don't expect this case to come up frequently, so I don't think we need to add a fancy placeholder.
Server PR: https://github.com/mattermost/mattermost-server/pull/10757
https://mattermost.atlassian.net/browse/MM-14030
This PR was tested on: Moto G6 (Android 8), iPhone 6 (iOS 12.2)
=> MM-14030 Don't show large gifs in posts

android/app/src/main/AndroidManifest.xml
Disables backing up the Android app using ADB. Android has it enabled by default and it seems like RN may have enabled it by default at some point, but it's considered a good practice to disable it to prevent people from misusing it.
https://mattermost.atlassian.net/browse/MM-15284
Moto G6 (Android 8)
=> MM-15284 Disable allowBackup on Android

app/components/at_mention/at_mention.js, app/components/markdown/markdown_code_block/markdown_code_block.js, app/components/markdown/markdown_image/markdown_image.js, app/components/markdown/markdown_link/markdown_link.js, app/components/post_list/post_list_base.js, app/mattermost_managed/mattermost-managed.android.js, app/mattermost_managed/mattermost-managed.ios.js, app/screens/flagged_posts/flagged_posts.js, app/screens/pinned_posts/pinned_posts.js, app/screens/recent_mentions/recent_mentions.js, app/screens/search/search.js
Some customers using EMM providers reported that the managed configuration was not being applied in some cases, and this was caused by the managed configuration being accessed asynchronously and not updated properly in the components.
This PR address the issue by having the managed configuration accessing a cached version of it.
This goes into the 1.19 release but two other PR's needs to be cherry-picked at the same time:
* #2741
* #2754
https://mattermost.atlassian.net/browse/MM-15380
=> Use of cached managed config in components

app/components/file_attachment_list/file_attachment_list.js, app/utils/file.js, app/utils/file.test.js, app/utils/image_cache_manager.js, app/utils/image_cache_manager.test.js, test/setup.js
When receiving a post with a file attachment, the `FileAttachmentList` component calls `getCacheFile` which returns a path with the correct extension extracted from the file name. This path is passed down the props to be used in the `Gallery` component when the user taps on the file attachment. Shortly after, the `FileAttachmentImage` component calls `ImageCacheManager.cache` which fetches the file from the server. The server returns an incorrect MIME type (a separate issue will be opened for this) in the response headers so the file is rewritten to a new path with an extension determined from that incorrect MIME type. When the user taps on the file attachment, the path provided to the Gallery component no longer exists so the error component is rendered.
This PR adds changes to determine …
=> [MM-15401] Fix setting of extension when caching files

app/screens/channel/channel_post_list/__snapshots__/channel_post_list.test.js.snap, app/screens/channel/channel_post_list/channel_post_list.js, app/screens/channel/channel_post_list/channel_post_list.test.js
This is only happening in **release-1.19**.
On Android for some reason at some point after logging in, the props passed to the `channel_post_list` is null thus the app crashes. By looking at the selector it should return an empty array but for some reason the first value received by the component is null.
This PR handles the case when the postIds prop is null or undefined to avoid the crash.
https://mattermost.atlassian.net/browse/MM-15402
Note: No need to cherry pick as this PR is directly against the release branch as this is not happening on master.
=> Handle postIds null or undefined in channel_post_list

app/utils/file.js
The Jenkins build process was failing when encountering this regex:
`app/utils/file.js: Invalid regular expression: /inline;filename=".*\.(?<ext>[a-z]+)";/: Invalid group in file app/utils/file.js at 21:35`.
=> Use numbered capture over named capture

app/mattermost_managed/mattermost-managed.ios.js
the iOS managed configuration is set as undefined when not set, this PR makes it so instead of undefined an empty object is used to avoid a crash.
https://mattermost.atlassian.net/browse/MM-15428
=> MM-15428 Fix iOS when managed config is not set

android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java, app/components/at_mention/at_mention.js, app/components/markdown/markdown_code_block/markdown_code_block.js, app/components/markdown/markdown_image/markdown_image.js, app/components/markdown/markdown_link/markdown_link.js, app/components/post_list/post_list.android.js, app/components/post_list/post_list.ios.js, app/mattermost_managed/mattermost-managed.ios.js, app/screens/post_options/index.js, ios/Mattermost/MattermostManaged.m
Previous fix wasn't working as expected, in this PR we are returning an empty object from the native code when no managed configuration has been set and just in case we check for null or undefined before accessing the managed configuration object.
https://mattermost.atlassian.net/browse/MM-15428
=> MM-15428 Return empty object for native managed configuration when not set

NOTICE.txt, app/app.js, package-lock.json, package.json
Minimum iOS version is 10.3, so @babel/polyfill and check for iOS version < 10.x are no longer needed
=> Removed @babel/polyfill

app/actions/views/channel.js, app/actions/views/channel.test.js, package-lock.json, package.json
Crashes on Android have been reported due to `.name` being called on undefined. `currentTeams[currentTeamId]` is the only object that I wasn't 100% sure could not be null so I added a check for that. A similar check was added in this [mattermost-redux PR](https://github.com/mattermost/mattermost-redux/pull/830). I'll update the mattermost-redux hash once that PR is merged.
https://mattermost.atlassian.net/browse/MM-15379
=> [MM-15379] Avoid possible reading of .name on undefined

app/components/post_body/post_body.js, app/components/post_list/post_list.js, app/screens/channel/channel_post_list/channel_post_list.js, app/screens/permalink/permalink.js, app/screens/thread/__snapshots__/thread.test.js.snap, app/screens/thread/thread.js, app/telemetry/telemetry_utils.js
- Addressed the missing props warning at Thread and Permalink views by adding `lastPostIndex` props into Thread and Permalink screens.
- While at it, added markers in opening Thread and Permalink screens from channel's post list instead of just adding default props (`-1`).  Note that there are other several ways to get into the said screens (e.g. from flag, pinned posts screens, etc) which is not covered by the said markers.
- Other: remove `posts:list_update` marker as it's found to be giving inconsistent result (having a false long time period in case of new post added but the "last post" did not re-render).  It's placed for extra monitoring only, will revisit in the future if such marker is found to be helpful.
GitHub issue: https://github.com/mattermost/mattermost-mobile/pull/2719#disc …
=> [MM-13955] Add lastPostIndex props to Thread and Permalink, and add markers for those screens

app/components/attachment_button.test.js, app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap, app/screens/edit_profile/edit_profile.js
Ogi found that some BMP images received a warning due to the image having a MIME type of `x-ms-bmp`.
https://mattermost.atlassian.net/browse/MM-14887
=> [MM-14887] Include all png, jpeg, and bmp MIME types

android/app/build.gradle, package-lock.json, package.json
v3.13.1 includes support for non-ascii characters in the MultipartBody so now files with names that include non-ascii characters can be shared with the Android share extension.
https://mattermost.atlassian.net/browse/MM-15378
=> [MM-15378] Update react-native-fetch-blob dependency to use okhttp3 v3.13.1

app/components/sidebars/main/channels_list/channel_item/index.js
A brief state between render cycles for channel items in the channel drawer can have channel.isBot undefined in a filtered list.  This PR handles the undefined state gracefully by returning false.
An alternative to using channel.isBot would be to use the existing several calls to state for channel and user, which would slow the filtered channel item.  If that is the desired approach (or another approach), I would be happy to follow that.
https://github.com/mattermost/mattermost-server/issues/10821
This PR was tested on: IPhoneX 12.2 emulator
=> MM-15442 Filtered list not showing bot account icon

app/components/sidebars/main/channels_list/list/index.js, app/components/sidebars/main/channels_list/list/list.js
Restict the permissions for guests (in this case is only need to remove the create public channel icon)
[MM-15059](https://mattermost.atlassian.net/browse/MM-15059)
=> MM-15059: Restict the permissions for guests

app/screens/channel_add_members/channel_add_members.js, app/screens/channel_add_members/channel_add_members.test.js, app/screens/channel_add_members/index.js, package-lock.json, package.json
Uses team and channel `group_constrained` property when loading users to add to channels.
https://mattermost.atlassian.net/browse/MM-14751
This PR was tested on: [Android Emulator for Pixel 2XL, with Android 9]
=> [MM-14751] Take group_constrained into account when adding users to channels

app/actions/views/channel.js, package-lock.json, package.json, share_extension/android/actions/index.js
This PR https://github.com/mattermost/mattermost-mobile/pull/2674 introduced a bug when selecting the default channel as it was using the selector `getChannelByName` instead of the utility of the same name thus it selected the first available channel that matched the name regardless of the team that it actually belonged.
=> Fix select default channel

app/screens/edit_post/edit_post.js
I'm not sure why these were set to false originally, but removing them matches what the post textbox uses
https://mattermost.atlassian.net/browse/MM-14802
=> MM-14802 Add autocorrect when editing a post

app/screens/post_options/index.js, app/screens/post_options/index.test.js
Allow flagging/unflagging of read-only channel posts.
https://mattermost.atlassian.net/browse/MM-15483
=> [MM-15483] Allow flagging/unflagging of read-only channel posts

.gitignore, Makefile
Move i18n check from shared pipelines to makefile as i18n-extract-ci.
Related PR - https://github.com/mattermost/mattermost-shared-pipelines/pull/14
Jira ticket: [MM-15695](https://mattermost.atlassian.net/browse/MM-15695)
=> [MM-15695] Move i18n check from shared pipelines to makefile as i18n-extract-ci

package-lock.json, package.json
PR build fails on `make i18n-extract-ci` due to mmjstool not adding `\n` when generating en.json.
This PR updates mmjstool to latest commit with fix on newline to end of file.
Actual fix is at https://github.com/mattermost/mattermost-utilities/commit/89543752e9c3b7fe4ad41d3af3821d3923198c20
none
=> Update mmjstool commit with fix on newline to end of file

package-lock.json, package.json
Version 0.43.1 [supports RAM bundles](https://docs.sentry.io/clients/react-native/ram-bundles/#enabling-ram-bundles). I tested with a test Sentry project and Android errors are now useful:
```
TypeError
undefined is not an object (evaluating '{}.doesNotExist.callFunc')
```
https://mattermost.atlassian.net/browse/MM-14123
=> Upgrade react-native-sentry to 0.43.1 which supports RAM bundles

app/components/sidebars/drawer_layout.js
When switching a team the panResponder for the channel drawer was not responding as we were not updating the variable to allow the panResponder to capture the gesture to open the drawer again.
=> Allow drawer pan responder when switching teams

package-lock.json, package.json
By updating the dependency for react-native-device-info we fix the crash for `getDiskStats` referenced here https://github.com/mattermost/react-native-device-info/commit/219f18eff5aeaf13d324621d40432e614241297f
Fixes #2806
=> update react-native-device-info crash fix

app/components/channel_loader/__snapshots__/channel_loader.test.js.snap, app/components/channel_loader/channel_loader.js, app/components/channel_loader/channel_loader.test.js, app/screens/channel/channel.js, package-lock.json, package.json
We previously defaulted to six placeholder rows in portrait view and four for landscape. These changes allow for the number of rows to be calculated from height. I've also removed the `top` adjustment per feedback from Andrew. I've tested the loader on entry, channel loading, flagged and recent screens and all look good.
https://mattermost.atlassian.net/browse/MM-15552
* Pixel C emulator, Android 9.0
* iPad Pro (11 inch), iOS 12.2
* iPad Pro (10.5 inch) simulator, iOS 12.2
* iPhone X simulator, iOS 12.2
Pixel C, channel loading, portrait
iPad Pro (10.5 inch), channel loading, portrait
=> [MM 15552] Determine number of placeholder rows from height

app/components/post_body/post_body.js
This change allows `isLongPost` to be set to false.
I wanted to add some tests like:
```
const longMessage = 'A really long message';
wrapper.setProps({message: longMessage});
expect(wrapper.state().isLongPost).toEqual(true);
expect(wrapper.find(ShowMoreButton).exists()).toEqual(true);
const shortMessage = 'A short message';
wrapper.setProps({message: shortMessage});
expect(wrapper.state().isLongPost).toEqual(false);
expect(wrapper.find(ShowMoreButton).exists()).toEqual(false);
```
but found that I needed to mount the PostBody component, however, I then get the error:
`It looks like you called mount() without a global document being loaded.`.
I could use some guidance with how to write the appropriate tests.
https://mattermost.atlassian.net/browse/MM-15671
* iPhone …
=> [MM-15671] Allow updating of isLongPost after editing message

app/screens/entry/entry.js
Upgrading to RNN v2 seems to change the order of things on startup, so this makes the Entry screen handle rehydration properly regardless of when it happens
https://mattermost.atlassian.net/browse/MM-15575
=> MM-15575 Make Entry mount properly after hydration

android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java, app/mattermost_managed/mattermost-managed.android.js
As discussed on Zoom, adding `System.exit(0)` properly terminates the app so that react-native-navigation re-initializes it when the app is reopened
https://mattermost.atlassian.net/browse/MM-15643
This PR was tested on: Moto G6 (Android 8)
=> MM-15643 Better close app when checking for pin code

fastlane/Fastfile
This fixes the issue of Android mobile build for not collecting telemetry data due to telemetry config not properly setup.
The config is setup for `fastlane android build` but skip for `fastlane build` since on the first run of build, it's already configured.
Tested and it's collecting data.
Jira ticket: [MM-15885](https://mattermost.atlassian.net/browse/MM-15885)
This PR was tested on: [Android]
=> [MM-15885] Configure telemetry on build 

Makefile, app/components/network_indicator/network_indicator.js, app/utils/network.js, native_modules/RNCNetInfo.m, package-lock.json, package.json
A customer was reporting that the current implementation of Internet Reachability is not working on LTE networks that assign IPv6 addresses, the current implementation uses a hostname based to test for reachability and the hostname does not have IPv6 addresses causing the check to fail.
With this PR we implemented the Internet connectivity test exposed in [this example](https://developer.apple.com/library/archive/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11)
it uses a different mechanism.
```
- reachabilityWithHostName and SCNetworkReachabilityCreateWithName:  Internally, this API works be resolving the host name to a set of IP addresses (this can be any combination of IPv4 and IPv6 addresses) and establishing separate …
```
=> Update netInfo to check for internet connectivity

package-lock.json, package.json
Updates package.json after commonmark.js markdown parser [update](https://github.com/mattermost/commonmark.js/pull/7) (#9155)
[Jira ticket](https://mattermost.atlassian.net/browse/MM-11287)
* Has commonmark.js library changes mattermost/commonmark.js#7
* Has server changes mattermost/mattermost-server#10852
Support for `taco.hell://` and `taco+hell://` url scheme
=> MM-11287 Add support for plus sign and period/dot in custom URL schemes (#9155)

app/telemetry/telemetry.android.js
Fix server version for Android telemetry.  `serverVersion` is successfully sent to metrics server but it failed to parse correctly since it's expected to be [server_version](https://github.com/mattermost/mattermost-metrics-server/blob/master/src/post_metric.js#L31).
none
=> Fix server version for Android telemetry

app/components/sidebars/settings/settings_sidebar.js, app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap, app/screens/edit_profile/edit_profile.js, app/screens/edit_profile/edit_profile.test.js, app/screens/user_profile/index.js, app/screens/user_profile/user_profile.js, app/screens/user_profile/user_profile.test.js
- Add "Edit Profile" button above the "Settings" option in the right panel menu
- Make user info of right panel menu opens the users own profile
- Add an Edit button in the header of the users own profile pop-over
- Have changes on navigation codes to support `showModal` and `push`
Fixes https://github.com/mattermost/mattermost-server/issues/10624
- Nexus 5X, Android 8.1.0
- iOS Simulator 11.4 (iPhone XS)
iOS
Android
=> [MM-13879] Add Edit profile button to RHS menu and own profile pop-over

app/app.js, app/mattermost.js
detect if passcode has been removed while the app in the background
There was a race condition that set the value of `app.inBackgroundSince` in different appStates, the appState has 3 values: `active`, `background` and `inactive` while bringing the app from the background the `background` and `inactive` states are set thus the value of `app.inBackgroundSince` was being set more than once. Also we are now only prompting the user for a passcode when the appState transitions from `background` to `active`.
Also this PR is changing when we check if the passcode is set, before we were checking if the device is secure only when we needed to prompt the user for a passcode, meaning that we only checked for this when the app was in the background for 5 minutes or more. Now it is being checked every …
=> MM-15643 Fix race condition to prompt for passcode and

app/components/post_attachment_opengraph/post_attachment_opengraph.js
Open graph images were displaying out of screen on Tablets as the viewport width was not taking into account that the sidebar is constantly open
=> Fix opengraph image on tablet to account for the sidebar

app/components/sidebars/main/channels_list/channels_list.js, app/components/sidebars/main/channels_list/index.js, app/components/sidebars/main/drawer_swipper/drawer_swiper.js, app/components/sidebars/main/main_sidebar.js, app/components/swiper.js
When closing the sidebar when the teams were displayed it was causing very strange behaviors as the offset was not being re-calculated. Also you were able to close the sidebar while filtering and the search bar was not being reset.
https://mattermost.atlassian.net/browse/MM-16070
=> MM-16070 Fix channel sidebar state while filtering

app/components/file_upload_preview/file_upload_preview.js, app/components/file_upload_preview/index.js, app/components/post_textbox/post_textbox.android.js, app/screens/channel/channel.ios.js, app/screens/thread/__snapshots__/thread.ios.test.js.snap, app/screens/thread/thread.ios.js
Previously this was partially fixed, but there was another issue with this, for some reason the channelId received in the `FileUploadPreview` component was referring to the previous channel thus the draft was always in **loading** state and never completed.
https://mattermost.atlassian.net/browse/MM-15912
=> Fix file upload not completing

app/components/post_body_additional_content/post_body_additional_content.js
Image previews were displaying out of screen on Tablets as the viewport width was not taking into account that the sidebar is constantly open
=> Fix image preview width on tablets

app/components/markdown/markdown_image/markdown_image.js
When an image does not have dimensions like an SVG we'll show a broken image instead.
Note: As of today we do not have support to render svg images
https://mattermost.atlassian.net/browse/MM-16091
=> Show broken image for inline images without dimensions

app/actions/views/channel.js, app/components/sidebars/main/channels_list/list/index.js, app/constants/view.js, app/reducers/views/channel.js
The channel sidebar behaves differently in mobile than in the webapp, but after making the sidebar so it is always shown on tablets, we needed to adapt it so the unread channels would not jump around when selecting the channel keeping the position in the section as we do in the webapp.
https://mattermost.atlassian.net/browse/MM-16061
=> MM-16061 Keep unread channels in place on Tablets

ios/MattermostShare/ShareViewController.swift, ios/UploadAttachments/UploadAttachments/StoreManager.h, ios/UploadAttachments/UploadAttachments/StoreManager.m
This change filters out archived channels if excludeArchived is true.
https://mattermost.atlassian.net/browse/MM-16078
* iPhone 8, iOS 12.3.1
=> [MM-16078] Allow excluding archived channels in getChannelsBySections

app/components/emoji/index.js
As `ExperimentalEnablePostMetadata` is defaulted to true we need to check for server version of 5.12 
[MM-16228](https://mattermost.atlassian.net/browse/MM-16228)
=> MM-16228 Add compatibility for removal of ExperimentalEnablePostMetadata data flag from config

app/actions/navigation.js, app/mattermost.js, app/screens/select_server/select_server.js
Android requires a [top bar height of 0 to be hidden](https://github.com/wix/react-native-navigation/issues/3843#issuecomment-416943345).
https://mattermost.atlassian.net/browse/MM-16293
=> [MM-16293] Fix navigation top bar style

app/screens/post_options/post_options.js
- As `SlideUpPanel` calculates `initialPosition` only in constructor, rotating device will not cause re-caculation of `initialPosition`.
- Adding `marginFromTop` as a key to `SlideUpPanel` can fix this problem in simplest way.
Fixes https://github.com/mattermost/mattermost-server/issues/10275
This PR was tested on
- Samsung Galaxy S10 (Android 9.0)
- iOS Simulator (iPhone XS, iOS 12.2)
=> [MM-14105] Long-press menu cannot be dragged up when rotating device to landscape while menu is open

native_modules/RNCookieManagerIOS.m
Fix iOS SSO when running on top-level domain (like example.com instead of www.example.com / chat.example.com)
Fixes https://github.com/mattermost/mattermost-mobile/issues/2722
This PR was tested on: ios / emulator, iphone x 
no ui changes
=> fix ios sso cookie bug when running on top-level domain

app/screens/settings/notification_settings_mobile/index.js, app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js, app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js
This pull request should avoid the user notification settings from being saved only after pressing back on notifications settings screen. The expected behavior is that the data should be saved right after pressing the save button on notification/notification status options dialog.
Fixes mattermost/mattermost-server#10582
This PR was tested on: Xiaomi Mi A1 (Android 9) and on iPhone XS emulator
=> [MM-14917] RN Android: Push notification settings are only saved when closing settings page

app/screens/channel_members/__snapshots__/channel_members.test.js.snap, app/screens/channel_members/channel_members.js, app/screens/channel_members/channel_members.test.js
This change allows for selectable item lists in the Manager Members screen but not in the View Members screen.
https://mattermost.atlassian.net/browse/MM-15668
Fixes https://github.com/mattermost/mattermost-server/issues/10146
=> [MM-15668] Member list items are selectable and enabled only when canManagerUsers is true

app/screens/edit_profile/edit_profile.js, app/screens/edit_profile/edit_profile.test.js, app/screens/edit_profile/index.js
In 5.12 there were some configuration changes for the position, this PR will take those into account but also keeps backwards compatibility with previous server versions.
In this PR I've also removed the need of the config prop and we are checking if the fields are editable or not in the connector.
https://mattermost.atlassian.net/browse/MM-16239
=> MM-16239 disable fields according to SAML or LDAP

android/app/google-services.json, package-lock.json, package.json
For the react-native-device-info change see this [PR](https://github.com/react-native-community/react-native-device-info/pull/693)
For the status value change, 0 is an invalid value; it should be 2.
https://mattermost.atlassian.net/browse/MM-16426
* Android emulator
=> [MM-16426] Update react-native-device-info and fix status value

android/app/build.gradle
The readme file in https://github.com/react-native-community/jsc-android-buildscripts changes the way we should be setting up android-jsc in build.gradle.
https://mattermost.atlassian.net/browse/MM-16464
=> Update gradle to use android-jsc as instructed

android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
I was unable to repro the crash, however, [getReplyMessage can return null](https://github.com/mattermost/mattermost-mobile/blob/a3bfaba64916e5081777055d77819bea909e66a8/android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java#L157) so this change returns early if it is.
https://mattermost.atlassian.net/browse/MM-16422
* Emulator running Android 8.1
=> Return if message is null

package-lock.json, package.json
Some android devices where crashing because of the version of JSC, with this update crashes are fixed.
**NOTE:** this PR should be cherry-picked all the way down to the release-1.20 branch
=> Fix crash on Android by Updating JSC

package-lock.json, package.json
There was an edge case in 1.20 where we could be missing posts
https://mattermost.atlassian.net/browse/MM-16496
This needs to be cherry-picked for 1.20 and use the corresponding mm-redux refs in every branch
=> MM-16432 Fix missing posts when using since API

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java, app/app.js, app/components/sidebars/main/main_sidebar.js, app/mattermost.js, app/mattermost_managed/mattermost-managed.android.js, app/mattermost_managed/mattermost-managed.ios.js, app/screens/channel/channel_base.js, app/screens/channel/channel_nav_bar/channel_nav_bar.js, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Mattermost+RCTUITextView.h, ios/Mattermost/Mattermost+RCTUITextView.m, ios/Mattermost/MattermostManaged.m
Now when the app is opened on a tablet with split screen the drawer will not be present at all times but it will behave like it does on phones allowing more real state to display the messages.
https://mattermost.atlassian.net/browse/MM-16392
This PR was tested on: iPad Pro 11" and Android Tablet running Pie
=> MM-16392 Split view support & hide sidebar on tablets

app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap, app/components/sidebars/main/channels_list/channel_item/channel_item.js, app/screens/settings/settings_item/style.ios.js
This change fixes an issue where iOS users who utilize "Larger Text" option (see "Settings" App > Accessibility > Larger Text) cannot see text in the LHS menu and all settings screens. There are lots of other places that need to be adapted to large text, but this gets around some of the major issues.
https://mattermost.atlassian.net/browse/MM-15771
This PR was tested on: iPhone X (iOS), Moto G6 (Android)
- LH Menu issue
- Settings Screens
=> Ios accessibility fixes

app/components/post_list/post_list.js
[When the ref attribute is used on a custom class component, the ref object receives the mounted instance of the component as its current.](https://reactjs.org/docs/refs-and-the-dom.html#accessing-refs) In this case, `Flatlist` might be unmounted once the setTimeout timer expires.
https://mattermost.atlassian.net/browse/MM-16456
=> [MM-16456] Ensure Flatlist is mounted prior to calling scrollToOffset

app/components/post_body_additional_content/post_body_additional_content.js, app/components/safe_area_view/safe_area_view.ios.js
on iOS devices that have a SafeAreaView (aka X series) when opening the a youtube video and rotating the device to landscape and then back to portrait was not setting the right safe area view as the status bar gets hidden by the YouTube player.
To fix it once the YouTube Video finish playback and the player is removed, we are now setting the StatusBar as visible and then emit an event to re-calculate the safe area view.
https://mattermost.atlassian.net/browse/MM-16467
=> MM-16467 Fix iOS layout when playing a youtube video in landscape

android/app/build.gradle
`localCompare` was returning different values for Android and iOS. Updating to jsc-intl fixes this.
https://mattermost.atlassian.net/browse/MM-16532
=> [MM-16532] Update jsc to intl version

package-lock.json, package.json
Updates the mattermost-redux ref to use the one for the release-5.13 branch instead of the release-5.12 branch
This was the cause of the crash on build 202.
=> Update redux update to use the release-5.13 branch

app/components/message_attachments/action_button/action_button.js, app/components/message_attachments/action_button/index.js, app/components/message_attachments/attachment_actions.js
This PR fixes an issue where post actions would fail because the cookie associated with the action is not being used. `doPostActionWithCookie` is now used instead of `doPostAction`.
https://mattermost.atlassian.net/browse/MM-15084
This PR was tested on: [Google Pixel 2, Android 8.1.0]
=> [MM-15084] Pass cookie for post actions

app/screens/edit_profile/index.js
The actual user property is `auth_service` instead of `service`
https://mattermost.atlassian.net/browse/MM-16239
HH: I think one review is enough
=> Fix AD/LDAP & SAML profile sync properties

app/screens/select_server/select_server.js
The server url if previously defined (as in after a logout) and you tried to clear it completely it was being reset to the previous url set.
=> Allow the server url to be cleared

app/components/post_attachment_opengraph/post_attachment_opengraph.js, app/components/post_body_additional_content/post_body_additional_content.js, app/components/post_list/post_list.js, app/reducers/views/channel.js, app/reducers/views/channel.test.js
This PR fixes the issue where new messages appeared below the keyboard when the new message indicator is present. We now place the new message indicator as far up in the list as possible but always visible.
Other fixes in this PR:
* Scroll pop in certain cases with open graph metadata where the image url does not match the images in the metadata
* Post visibility was set to 0 at times causing a refresh of the post list.
=> Place the new message indicator at the top of the screen

app/components/post_body_additional_content/index.js
Checks if `remove_link_preview` is set to `true`
https://mattermost.atlassian.net/browse/MM-16468
Not possible.
=> Don't show preview if remove_link_preview is set to true

package-lock.json, package.json
This PR updates device-info so that devices with screen sizes bigger than 7.9" are considered tablets instead of the previous 6.9", this solves the issues on moto g(7) devices where the manufacturer was reporting the wrong size.
https://mattermost.atlassian.net/browse/MM-16807
=> Update device info ref

app/actions/views/channel.js, app/push_notifications/push_notifications.android.js, app/push_notifications/push_notifications.ios.js, app/utils/push_notifications.js
This PR fixes a current regression in master when opening the app from a push notification, the app is detecting the notification as being captured while the app is on the foreground and does not send the user to the right channel.
Also makes sure that when switching channels by tapping on a notification the new message indicator is properly displayed
=> Fix regression opening a channel from a push notification

app/mattermost.js
Deleting the cache was not properly restarting the app in the Channel Screen as the properties passed to the `Navigation.startSingleScreenApp` were wrong.
PR: Direct against the release branch as master is not affected.
https://mattermost.atlassian.net/browse/MM-16823
=> MM-16823 Fix "Freeze" after deleting cache

app/actions/views/command.js
Fix app crashing when sending invalid slash command
Note: I think this happened in past few releases already (and not a recent regression) but would be nice for 1.21.
Jira ticket: [MM-16859](https://mattermost.atlassian.net/browse/MM-16859)
=> MM-16859 Fix app crashing when sending invalid slash command

app/actions/views/typing.js
Fix by correctly accessing websocket state - introduced by the recent change https://github.com/mattermost/mattermost-mobile/commit/0ff6dba3c86e88b53fcee19d12e82cd4601ed862
Issue is on master only.
Jira ticket - [MM-16858](https://mattermost.atlassian.net/browse/MM-16858)
This PR was tested on: [Android simulator and iOS emulator]
=> MM-16858 Fix app crash after typing

app/components/sidebars/main/main_sidebar.js
The drawer contents were taking a while to render which affected the channel rendering.
https://mattermost.atlassian.net/browse/MM-16294
* Emulator, Android 9.0
=> [MM-16294] Fix white transition screen displayed on app relaunch to Channel screen

app/screens/long_post/index.js
This PR fixes the tapping on the long post show more option to ask for `Relaunch app` as the selector was being imported from the wrong file
https://mattermost.atlassian.net/browse/MM-16857
=> MM-16857 Fix long posts

android/app/src/main/res/xml/network_security_config.xml, package-lock.json, package.json
After updating the `targetSdkVersion` to 28 as required by Google Play the react-native-notifications package was causing a security exception as `uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` is now required, also the `startForeground` service that receives a notification now needs to set a notification channel, both of this issues were addressed in the library fork here https://github.com/mattermost/react-native-notifications/commit/1b7ec8513606b42237ab4674de9dacb4d1935e38
Also included the `cleartextTrafficPermitted` in the `network_security_config` to allow http requests instead of only allowing https.
https://mattermost.atlassian.net/browse/MM-16855
=> Fix android crash on Android O & P after upgrading target to 28

app/components/post_list/post_list.js
Similar issue to https://github.com/mattermost/mattermost-mobile/pull/2925. Added a check to ensure that the ref's current is not null prior to calling scrollToIndex.
https://mattermost.atlassian.net/browse/MM-17016
=> [MM-17016] Ensure Flatlist is mounted prior to calling scrollToIndex

app/screens/channel_info/index.js
Only access `notify_props` if `currentChannelMember` is not null.
https://mattermost.atlassian.net/browse/MM-17018
=> [MM-17018] Handle null currentChannelMember

app/components/post_profile_picture/index.js, app/components/post_profile_picture/post_profile_picture.js, app/constants/view.js, app/screens/notification/notification.js
An `icon_emoji` parameter was added to incoming webhook requests, that overrides the profile icon and the `icon_url` parameter.
https://mattermost.atlassian.net/browse/MM-16389
- Android Emulator (29)
Related PRs:
- https://github.com/mattermost/mattermost-server/pull/11586
- https://github.com/mattermost/mattermost-webapp/pull/3074
- https://github.com/mattermost/docs/pull/2832
- https://github.com/mattermost/mattermost-developer-documentation/pull/321
=> [MM-16389] Enable emojis for profile icons from webhooks

app/screens/select_server/select_server.js
The select server screeen in componentDidUpdate was passing the previous props to the login options handler instead of the current props, thus causing a race condition when the config or the license was not set.
=> Select server fix login options transition

app/screens/sso/sso.js
With https://github.com/mattermost/mattermost-server/pull/10493 we are supporting cookies for different subpaths so mobile needs to look for cookies in subpaths instead or root urls.
https://mattermost.atlassian.net/browse/MM-16829
Android and IOS emulators
=> MM-16829 Fix for sso with server subpaths

app/screens/options_modal/options_modal.js
For some reason iOS needs us to dismiss the modal before running the animation.
https://mattermost.atlassian.net/browse/MM-17090
=> Fix Options modal on iOS

app/components/sidebars/main/__snapshots__/main_sidebar.test.js.snap, app/components/sidebars/main/main_sidebar.js, app/components/sidebars/main/main_sidebar.test.js
Set `footerColor` the same as `navBarBackgroundColor`.
https://mattermost.atlassian.net/browse/MM-16910
* iPhone X simulator, iOS 12.2
=> [MM-16910] Set footerColor the same as navBarBackgroundColor

app/push_notifications/push_notifications.ios.js, app/utils/push_notifications.js, app/utils/push_notifications.test.js
Adding channel_id to the failed push notification reply ensures that it is cleared when `clearChannelNotifications` is called. The test for `clearChannelNotifications` is part of [PR 3001](https://github.com/mattermost/mattermost-mobile/pull/3001).
https://mattermost.atlassian.net/browse/MM-14923
=> [MM-14923] Add channel_id to failed push notification reply

app/screens/user_profile/index.js, app/screens/user_profile/user_profile.js, app/screens/user_profile/user_profile.test.js
Using `popToRoot` over `resetToChannel` avoid a white screen when transitioning to the channel screen.
https://mattermost.atlassian.net/browse/MM-17040
* Emulator, Android 9.0
=> [MM-17040] User popToRoot over resetToChannel

app/components/post_list/post_list.js
I moved the null check inside the `requestAnimationFrame` callback. (Previous fix attempt: https://github.com/mattermost/mattermost-mobile/pull/2977)
https://mattermost.atlassian.net/browse/MM-17016
=> [MM-17016] Call scrollToIndex only if flatListRef.current is not null

app/components/post_list/post_list.js
Cherry pick of #3022 on release-1.22.
- #3022: Call scrollToIndex only if flatListRef.current is not null
/cc  @migbot
=> Automated cherry pick of #3022

app/push_notifications/push_notifications.ios.js, app/push_notifications/push_notifications.ios.test.js, package-lock.json, package.json, test/setup.js
Tracks in-app notifications using `AsyncStorage` since `react-native-notifications` only tracks notifications delivered to the Notifications Center. The fix for Android will be done as a separate PR for https://mattermost.atlassian.net/browse/MM-17110.
https://mattermost.atlassian.net/browse/MM-14926
=> [MM-14926] Include in-app notifications in iOS badge number

app/components/post_list/post_list.js
While the `initialIndex` was > 0 prior to the `requestAnimationFrame` call, it was -1 inside the callback so I moved the check inside the callback. I was able to repro this consistently by scrolling on a channel, switching channels, and then re-running the app in XCode.
https://mattermost.atlassian.net/browse/MM-17001
=> [MM-17001] Check initialIndex in callback

app/utils/security.js
Using the full server url so Cookies are retrieved when a subpath is used.
https://mattermost.atlassian.net/browse/MM-17100
=> MM-17100 setCSRFFromCookie with subpath support

app/app.js, app/screens/entry/entry.js, app/screens/entry/index.js
on Android there was a race condition setting the user credentials, when this happened we were trying to set the credentials stored in the redux store. At this point we removed the session token from the redux store so it was being set to `undefined` then when the app makes the decision to show the server url screen or the channel screen then the server screen was shown as there was **no** session token at this point.
With this PR we are removing the second call to `setAppCredentials` so only the credentials stored in the keyChain are used.
**IMPORTANT:** This only applies to 1.21 as 1.22 does not do this after the entry refactor.
After this PR is merged we need to cut a dot release.
https://mattermost.atlassian.net/browse/MM-17220
=> Fix assigning credentials during app init

app/init/global_event_handler.js, app/init/global_event_handler.test.js, app/push_notifications/push_notifications.android.js, app/push_notifications/push_notifications.ios.js, app/push_notifications/push_notifications.ios.test.js
This is a follow up to https://github.com/mattermost/mattermost-mobile/pull/3001.
https://mattermost.atlassian.net/browse/MM-14926
=> [MM-14926] Clear foreground notifications from AsyncStorage on logout and server upgrade

app/init/global_event_handler.js, app/init/global_event_handler.test.js, app/push_notifications/push_notifications.android.js, app/push_notifications/push_notifications.ios.js, app/push_notifications/push_notifications.ios.test.js
Cherry pick of #3033 on release-1.22.
- #3033: Clear foreground notifications from AsyncStorage
/cc  @migbot
=> Automated cherry pick of #3033

ios/UploadAttachments/UploadAttachments/UploadSession.swift
I'm unable to repro the crash, however, the exception in `notificationReceipt` is only happening with server versions 5.11 and below which don't include `ack_id` in the notification payload. I've added a null check for that ack id prior to running the body of the function.
https://mattermost.atlassian.net/browse/MM-17157
=> [MM-17157] Check if ackId is nil first

app/push_notifications/push_notifications.ios.test.js
The part of the test running inside the callback to `getDeliveredNotifications` wasn't being run since it's async.
https://mattermost.atlassian.net/browse/MM-14926
=> [MM-14926] Fix for test code that wasn't being run

app/screens/entry/entry.js, app/screens/entry/index.js
The call to dispatch `setDeviceToken` was previously made in `setAppCredentials` of the entry screen which was removed in [PR-3034](https://github.com/mattermost/mattermost-mobile/pull/3034). I'm just adding back the call to `setDeviceToken`.
https://mattermost.atlassian.net/browse/MM-17401
* Galaxy S7, Android 8.1
=> [MM-17401] Dispatch setDeviceToken after hydration

package-lock.json, package.json
Now that the mobile repo has been updated for core-js 3 I can update the mattermost-redux commit hash to point to https://github.com/mattermost/mattermost-redux/commit/c93aa5fd83601ef226eb07d26e36a1ad65b5af95 which is built on top of the mattermost-redux update to core-js 3.
**Note: The commit hash on the cherry-pick to 1.22 needs to point to the 5.14 commit of my mattermost-redux change (https://github.com/mattermost/mattermost-redux/commit/482c5d4ecfe0818295d6e539eac102c935989b4b). I'm omitting the cherry pick approved label so I can do this manually.
https://mattermost.atlassian.net/browse/MM-15379
=> [MM-15379] Include null check on name from mattermost-redux

app/actions/views/channel.js, app/actions/views/channel.test.js, test/test_helper.js
In case the redux state for `websocket` is not defined we fallback to 0 as the value for lastConnectAt, that way we look for the last create_at post and fetch posts since then.
https://mattermost.atlassian.net/browse/MM-16752
=> MM-16752 Fix unhandled promise rejection TypeError state.websocket.lastConnectAt

app/screens/settings/theme/theme_tile.js
Get the device width inside the component and use it to calculate the thumbnail width.
https://mattermost.atlassian.net/browse/MM-17512
iOS:
Android:
=> [MM-17512] Fix theme thumbnail width

app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap, app/utils/markdown.js
While I did find this [react-native issue](https://github.com/facebook/react-native/issues/22927), removing `flex` displays the horizontal rule.
https://mattermost.atlassian.net/browse/MM-17431
* Pixel 2 emulator, Android 8.1
Pixel 2 emulator:
iOS:
=> [MM-17431] Remove flex for horizontalRule

app/components/post_list/post_list.js
After the crash fixes around `scrollToIndex` the app is no longer scrolling to the new message line  indicator, this was happening cause of a race condition.
In order to fix it, the decision to scroll to the new message line indicator happens when the component updates, scrolling to the line does not update the component once again.
https://mattermost.atlassian.net/browse/MM-17562
=> MM-17562 scroll to new message line indicator on componentDidUpdate

app/screens/interactive_dialog/interactive_dialog.js, app/screens/interactive_dialog/interactive_dialog.test.js
Allow interactive dialogs to have no elements
https://github.com/mattermost/mattermost-server/issues/10686
https://mattermost.atlassian.net/browse/MM-15218
This PR was tested on: None (sorry)
=> MM-15218 allow interactive dialogs to have no elements

app/components/post_header/post_header.js
Increasing the ReplyIcon's width and height fixes the cutoff issue.
https://mattermost.atlassian.net/browse/MM-17597
* iPhone 8+, iOS 12.2
Android:
iOS:
=> [MM-17597] Increase ReplyIcon dimensions

app/actions/navigation.js, app/screens/thread/thread_base.js
Fixes a race condition when trying to pop the thread view once the root post is deleted. The fix is done by passing the componentId that we want the Navigator to pop
https://mattermost.atlassian.net/browse/MM-17633
=> Fix pop thread screen when deleting the root post

app/screens/channel/channel_base.js
With the changes to the navigation library the Terms of Service modal had no Navigation bar set, and the buttons to agree with the terms was not being displayed
https://mattermost.atlassian.net/browse/MM-17630
=> MM-17630 add Navigation bar to terms of service modal

app/components/text_input_with_localized_placeholder.js, app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap, app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js, app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.test.js
Added `flex: 1` to the wrapper view like in `NotificationSettingsAutoResponder`.
https://mattermost.atlassian.net/browse/MM-17637
* iPhone X simulator, iOS 11.4
=> [MM-17637] Add flex 1 to wrapper view

app/screens/channel/channel.ios.js
With the landscape work the channel.ios screen was defining the components based on iPhone X and landscape causing components to be unmount and new ones to mount without need every time the device changed orientations
Before
After
=> Remove unnecessary component definition

app/screens/select_server/select_server.js
Fixes the header in the select server screen
previous
after this fix
=> Exclude the SafeAreaHeader in Select Server screen

app/push_notifications/push_notifications.ios.js, app/push_notifications/push_notifications.ios.test.js
When tracking foreground notifications to set the app icon badge number, we were tracking and incrementing the number by when the notification was being opened, causing the badge number to be wrong at times.
=> Do not track foreground notifications when notification is opened

app/push_notifications/push_notifications.ios.js, app/push_notifications/push_notifications.ios.test.js
Cherry pick of #3105 on release-1.22.
- #3105: Do not track foreground notifications when notification is
/cc  @enahum
=> Automated cherry pick of #3105

app/components/slide_up_panel/slide_up_panel.js, app/screens/post_options/post_options.js, app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap, app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.test.js
There was a race condition when executing options from the post options when the option needed to open a secondary screen, on slow devices the top component ID was referencing the post options screen instead of the channel screen thus once the post option screen was removed the app was not able to navigate to the secondary screen. The way to address this was to add a callback function that gets executed once the post options screen is dismissed.
https://mattermost.atlassian.net/browse/MM-17692
=> MM-17692 execute callback after closing post options

app/actions/navigation.js, app/screens/settings/advanced_settings/advanced_settings.js, app/screens/settings/advanced_settings/index.js, app/screens/settings/general/settings.js, app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap, app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.test.js
On Android the settings screen back button was being replaced by a normal back button after applying the them thus it was not rendering the actual close button.
Also for some reason when setting a root Android is not automatically dismissing all the modals as iOS does, so when resetting the cache the settings screen was not being dismissed.
https://mattermost.atlassian.net/browse/MM-17693
=> MM-17693 Android fix close settings screen

app/screens/post_options/post_options.js, app/screens/post_options/post_options.test.js
Delete the post in the callback after closing the post options screen.
=> Fix delete the root post on a thread to properly close the thread screen

app/actions/navigation.js, app/screens/settings/display_settings/display_settings.js, app/screens/settings/display_settings/display_settings.test.js, app/screens/settings/display_settings/index.js, app/screens/settings/general/index.js, app/screens/settings/general/settings.js, app/screens/settings/theme/theme.js, app/screens/settings/theme/theme.test.js, app/store/ephemeral_store.js, app/utils/theme.js
IDs for components that have appeared are now tracked in a separate array of EphemeralStore so that when the theme changes, `setNavigatorStyles` can be called on all of them rather than in each component's `componentDidAppear`.
https://mattermost.atlassian.net/browse/MM-17817
Before:
After:
=> [MM-17817] Apply setNavigatorStyles to all navigation components on theme change

app/screens/create_channel/create_channel.js, app/screens/more_channels/more_channels.js, app/screens/more_channels/more_channels.test.js, app/screens/more_dms/more_dms.js
While I was only able to reproduce the issue once, I have a feeling the issue is that `Navigation.mergeOptions` is being called with a component ID _prior_ to the component being added to the navigation stack since it's triggered in the component constructor.
https://mattermost.atlassian.net/browse/MM-17565
* iPhone 8, iOS 12.3.1
=> [MM-17565] Set top bar buttons once component is mounted

app/actions/views/select_server.js, app/init/emm_provider.js
Reported by a customer:
on Android when the app is brought up from the background the `managedConfigDidChange` gets triggered and if a default server url is set either in the managed config or the local config then it will set the serverURL but will wipe the config/license from the general entities.
With this PR we will only set the server url without wiping the existing config/license.
Fixes: #3110
=> Fix loosing the server config when handleManagedConfig

app/components/formatted_date.js, app/components/formatted_time.js, app/components/post_header/post_header.js, app/components/post_list/date_header/__snapshots__/date_header.test.js.snap, app/components/post_list/date_header/date_header.js, app/i18n/index.js, app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap, app/screens/channel_info/channel_info_header.js, app/screens/channel_info/index.js
When the timezone setting is disabled instead of moment we were relying on `react-intl` to format the date/time but for some reason intl is only using the UTC value of the time.
With this PR we handle the format of date/time values with moment (including localization) to use either the user's timezone or the device local time.
https://mattermost.atlassian.net/browse/MM-17812
Fixes: #3049
=> Migrate to moment to fix timestamps based on timezone or local time

app/screens/channel_info/channel_info_header.js
The `renderHasGuestText` function was removed but the call was left behind causing a crash when opening the channel info.
* iOS simulator
=> Remove renderHasGuestText

app/components/autocomplete/at_mention/at_mention.js, app/components/autocomplete/autocomplete.js, app/components/autocomplete/channel_mention/channel_mention.js, app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/autocomplete/slash_suggestion/slash_suggestion.js, app/components/edit_channel_info/edit_channel_info.js, app/components/edit_channel_info/edit_channel_info.test.js, app/screens/channel_info/channel_info.js, app/screens/channel_info/channel_info_header.js, app/screens/channel_info/index.js
This pull request makes the autocomplete function of the header section in edit channel the same as when you posting a message (Autocomplete appears above the text input box in the "Header" section, exactly the same as when typing in the channel or a thread.)
Fixes https://github.com/mattermost/mattermost-server/issues/10160
This PR was tested on: OnePlus 5T, Android version 9, OxygenOS version: 9.0.7
Don't have an iOS device so not sure if it works on Iphone the same way
https://streamable.com/2r0ug
=> [MM-13843] Edit channel autocomplete is same as the posting message one

app/screens/channel_info/channel_info.js
The channel info screen on both Android and iOS is now pushed to the stack, on previous versions for Android it was opened as a modal. This PR will cause the screen to be popped on both Android and iOS alike when closing/leaving/archiving a channel.
https://mattermost.atlassian.net/browse/MM-17880
=> Fix regression close/leave/archive channel redirect to channel screen on Android

app/screens/create_channel/create_channel.js, app/screens/edit_channel/edit_channel.js, app/screens/edit_post/edit_post.js, app/screens/edit_profile/edit_profile.js, app/screens/terms_of_service/terms_of_service.js, app/screens/user_profile/user_profile.js
Explicitly set the right button color in the navbar so Android does not lose it
https://mattermost.atlassian.net/browse/MM-17878
=> Fix Regression right buttons color on Android navbar when enable

android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
As part of the app initialization refactoring of 1.22, the server URL is now stored in AsyncStorage when the app is first launched. When a push notification is received we grab that server URL to send an ack request, however, the app was crashing in the scenario where the app was upgraded to 1.22 but not yet relaunched and push notifications were being received. This PR fixes the crash by falling back to extracting the server URL from the token and also checking that the server URL is valid.
https://mattermost.atlassian.net/browse/MM-17970
=> [MM-17970] Check for valid server URL

app/i18n/index.js
By using moment to create everything related to time using locales zh-TW was failing to load as moment requires the locales to be defined in lowercase.
https://mattermost.atlassian.net/browse/MM-17971
=> MM-17971 update moment locale as lowercase

app/screens/image_preview/downloader.ios.js
Once we cancelled the download there was a 2 second wait to actually remove and trigger the cancel callback, this gave time to a race condition if we initiated the download once again, thus the file downloaded was incomplete and the video failed to playback.
https://mattermost.atlassian.net/browse/MM-17886
=> MM-17886 Do not wait to cancel the video download

app/init/emm_provider.js, app/mattermost_managed/mattermost-managed.android.js, app/mattermost_managed/mattermost-managed.ios.js, assets/base/i18n/en.json, ios/Mattermost/MattermostManaged.m, ios/MattermostShare/ShareViewController.swift
The previous help text told the user to go to the "Touch ID & Passcode" section of the settings, even if the device didn't support Touch ID. This fixes that by checking whether or not the phone supports Touch ID.
https://mattermost.atlassian.net/browse/MM-17589
This PR was tested on: iPhone 6, iPad Pro, iPhone 7 Simulator, iPhone X Simulator
=> MM-17589 Update "passcode required" help text

app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.test.js
Fix failing on lint due to merge conflict
``Duplicate key 'isLandscape'.eslint(no-dupe-keys)``
none
=> Fix failing on lint due to merge conflict

app/utils/push_notifications.js
Cherry pick of #3183 on release-1.22.
- #3183: do not dispatch navigation actions when opening the app from
/cc  @enahum
=> Automated cherry pick of #3183

app/components/search_bar/search_box.js, app/components/sidebars/main/channels_list/channels_list.js
Increase cancel button width to accommodate "Cancel" translations
https://mattermost.atlassian.net/browse/MM-17601
* iOS simulator, 12.3
German:
English:
Chinese:
=> [MM-17601] Increase cancel button width to accommodate "Cancel" translations

app/components/emoji_picker/emoji_picker.js, app/components/emoji_picker/emoji_picker.test.js
Fixes PR https://github.com/mattermost/mattermost-mobile/pull/3191
https://mattermost.atlassian.net/browse/MM-17513
* iOS simulator, 12.3
=> [MM-17513] Rebuild emojis when emojis change and use props.deviceWidth

app/components/post_textbox/post_textbox.test.js, app/components/post_textbox/post_textbox_base.js
The current implementation was checking and sending an alert each time a user changed the value of the textbox, if the message was too long. This PR makes sure only one alert is sent when a message of large length is added. It will only fire an alert when the message has gone from being of proper length (or 0) to too long.
https://mattermost.atlassian.net/browse/MM-18172
Android Emulator, Pixel 2 Android Q
iOS Simulator, iPhone XS iOS 12.4
=> [MM-18172] Added state for message length such that alerts for long length aren't fired too often

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Podfile.lock, package-lock.json, package.json
Upgraded to the latest @sentry/react-native and made changes to ensure that the debug symbols only upload when Sentry is enabled.
https://mattermost.atlassian.net/browse/MM-18336
* iOS simulator, 12.3
=> [MM-18336] Upload Sentry debug symbols only when SENTRY_ENABLED is true

app/components/sidebars/main/channels_list/list/index.js, app/components/sidebars/main/channels_list/list/list.js, app/screens/options_modal/options_modal_list.android.js
When using the sidebar to combined all the channel types we were using a modal to display the options and opening the following screen from there, the problem was that the modal was being dismissed before being able to open the next one, so both got dismissed.
This PR changes it so it uses the native Action Sheet on iOS an even anchors it on iPad as well as the equivalent for Android.
With this PR we also fixed an issue where the option to create a new public channel was available even if the user did not have permission to do so.
Fixes: #3216
https://mattermost.atlassian.net/browse/MM-18223
=> MM-18223 Fix channel actions on combined sidebar

app/utils/image_cache_manager.js
Our `ImageCacheManager` was caching listeners even when the file failed to download (due to not being connected or otherwise). This PR removes those listeners such that if the image failed to download it will always retry when the screen is reloaded.
https://mattermost.atlassian.net/browse/MM-18178
iOS Simulator, iPhone X iOS 12.4
OnePlus 5, Android 9.0.7
=> [MM-18178] Removing caching of failed image loading attempts

app/screens/sso/sso.js, ios/Mattermost.xcodeproj/project.pbxproj, package-lock.json, package.json
This PR fixes the warning given by Apple when deploying the app to TestFlilght
```
Dear Developer,
We identified one or more issues with a recent delivery for your app, "Mattermost Beta" 1.23.0 (229). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
Best regards,
The App Store Team
```
=> Update webview library to remove deprecated API

app/components/message_attachments/__snapshots__/attachment_footer.test.js.snap, app/components/message_attachments/attachment_footer.js, app/components/message_attachments/attachment_footer.test.js, app/components/message_attachments/message_attachment.js, app/constants/attachment.js
Adds support for the `footer` and `footer_icon` fields that are rendered at the bottom of message attachments.
This is the same change that was made to the webapp here: https://github.com/mattermost/mattermost-webapp/pull/3569
https://github.com/mattermost/mattermost-server/issues/11994
This PR was tested on
- Pixel 3 Android emulator, Android 9.0, API 28
- iPhone X emulator, iOS 12.4
Android:
iOS:
=> GH-11994: Add support for footer and footer_icon in attachments

android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java, app/init/emm_provider.js
Not sure how I missed this before, but this flag is needed when starting an activity outside of the app.
https://mattermost.atlassian.net/browse/MM-18465
This PR was tested on: Android emulator
=> MM-18465 Add proper flags when opening settings

app/screens/settings/advanced_settings/advanced_settings.js
When resetting the cache on the mobile app the theme changes so it uses the default one as there is no data in the redux store right after the cache is reset. This causes a momentary white screen to be displayed. (there is no way to avoid the screen from flashing white as the theme will eventually change while data is being loaded again) but with this PR at least we preserve the current theme in the Advanced settings screen so only the channel loader displays in white for a shorter period of time.
https://mattermost.atlassian.net/browse/MM-18353
=> MM-18353 Do not update the theme when resetting the cache

app/components/post_list/date_header/__snapshots__/date_header.test.js.snap, app/components/post_list/date_header/date_header.js, app/components/recent_date.js, app/components/recent_date.test.js, assets/base/i18n/en.json
Followup to the Appscon hackathon where we decided to change recent date separators to read Today/Yesterday instead of the date. Days before that still appear as the actual date.
https://mattermost.atlassian.net/browse/MM-18466
https://github.com/mattermost/mattermost-webapp/pull/3652
This PR was tested on: Android emulator
=> MM-18466 Change recent date separators to yesterday/today

share_extension/android/extension_post/extension_post.js
Add `flex: 1` setting to TextInput/ScrollView in Share extension post window (Android) to utilize all available screen real estate, up to the Team and Channel selectors below.
#3261 
This PR was tested on: OnePlus 5, Android 9
**Before**
**After**
=> MM-18588 Expand text input area in Android Share extension to use available space

app/components/sidebars/main/drawer_swipper/drawer_swiper.js, app/components/sidebars/main/main_sidebar.js, app/components/swiper.js
When a user is added to a new team where they didn't have a second one before, the teams page would be added to the `drawer_swiper` component, but the drawer position was not updated, thus it would open to the teams menu. This PR forcibly updates the drawer position such that the channel menu is still the first menu shown when opening the sidebar.
https://mattermost.atlassian.net/browse/MM-18550
iOS Simulator, iPhone XS iOS 12.4
OnePlus 5, Android 9
=> [MM-18550] Force drawer to open to channel menu when new teams are added

app/init/global_event_handler.js, app/init/global_event_handler.test.js, test/setup.js
Attempts to access `store.dispatch` when the app state changed failed due to the global event handler not yet being configured. This change ensures that `onAppStateChange` only runs after the `store` is set.
https://mattermost.atlassian.net/browse/MM-18608
* Galaxy S7, Android 8.0
* iPhone 8, iOS 12.4.1
=> [MM-18608] Ensure onAppStateChange runs only after GlobalEventHandler is configured

app/init/global_event_handler.js, app/init/global_event_handler.test.js, test/setup.js
Cherry pick of #3268 on release-1.24.
- #3268: Ensure onAppStateChange runs only after GlobalEventHandler is
/cc  @migbot
=> Automated cherry pick of #3268

ios/Mattermost/Info.plist
`NSBluetoothPeripheralUsageDescription` is deprecated in iOS 13. Adding the new `NSBluetoothAlwaysUsageDescription` key to support that.
=> Updated Info.plist with new bluetooth usage description key

app/components/post_list/post_list.js, app/components/post_list/post_list.test.js
I'm unable to reproduce the crash, however, I made the following changes that might help:
moved the check on `index` and on `flatListRef?.current` to inside the `requestAnimationFrame` callback so the checks are run right before the call to `scrollToIndex`. Also, `this.hasDoneInitialScroll` is set to `true` now only if `this.scrollToIndex` will be called.
I'll keep an eye on Sentry and if the issue still occurs, we'll need to spend more time understanding why the index is out of range.
https://mattermost.atlassian.net/browse/MM-17001
* iPhone 8, iOS 12.4
=> [MM-17001] Call scrollToIndex only when ref is set and index is in range

app/components/autocomplete/autocomplete.js, app/components/client_upgrade_listener/client_upgrade_listener.js, app/components/emoji_picker/emoji_picker.ios.js, app/components/emoji_picker/emoji_picker_base.js, app/components/network_indicator/network_indicator.js, app/components/safe_area_view/iphone_x_spacing/index.js, app/components/safe_area_view/safe_area_view.ios.js, app/components/sidebars/main/channels_list/list/list.js, app/components/sidebars/main/main_sidebar.js, app/components/sidebars/main/teams_list/teams_list.js, app/components/slide_up_panel/slide_up_panel.js, app/components/start/empty_toolbar.js, app/components/swiper.js, app/constants/device.js, app/screens/channel/channel.ios.js, app/screens/channel/channel_nav_bar/channel_nav_bar.js, app/screens/image_preview/image_preview.js, app/screens/search/search.js, package.json
With the new iPhone 11 models the device constant for `IS_PHONE_X` got obsolete and the iPhone 11 devices where not using the insets accordingly.
After updating the library for react-native-device-info to detect iPhone 11 devices we renamed the constant to `IS_IPHONE_WITH_INSETS` to make it more general and changed the constant value to take iPhone X and 11 into account.
https://mattermost.atlassian.net/browse/MM-18752
=> MM-18752 Rename constant to handle iPhone X and new iPhone 11 insets

app/components/post_body/index.js, app/components/post_body/index.test.js
`ownProps.channelIsArchived` was undefined, so `!ownProps.channelIsArchived` was returning true. We now check if `ownProps` has the `channelIsArchived` property. If so, use that, otherwise use `channel.delete_at` to determine if the channel is archived.
https://mattermost.atlassian.net/browse/MM-18325
* iPhone X simulator, iOS 12.4
=> [MM-18325] Properly determine if channel is archived

app/screens/channel_info/channel_info.js
minor fix to trim away the extra spaces after a channel's `display_name` on the `Archive Channel` and `Leave Channel` alerts.
https://mattermost.atlassian.net/browse/MM-18662
* Google Pixel 3 Emulator (Android 9)
Note: Notice the empty space before the `?`  
* Before:
---
* After:
=> [MM-18662] Trimming display_name in delete/leave channel alerts

app/i18n/index.js, app/init/global_event_handler.js, app/init/global_event_handler.test.js, app/selectors/i18n.js
There was a crash on Android in the call to `setMomentLocale`. I've removed that function and instead am resetting the moment locale to the DEFAULT_LOCALE on logout to handle https://mattermost.atlassian.net/browse/MM-18226.
Will manually cherry-pick into 1.23.
https://mattermost.atlassian.net/browse/MM-18779
* iPhone sim, iOS 12.3
=> [MM-18779] Reset moment local on logout

app/components/post_textbox/post_textbox.test.js, app/components/post_textbox/post_textbox_base.js, app/screens/channel/channel.android.js, app/screens/channel/channel.ios.js, app/screens/thread/thread.android.js, app/screens/thread/thread.ios.js
The implementation to handle pasting files/images, etc in the post text input required us to emit an Global event instead of a component event. The reason for this is that we cannot properly extend the native TextInput views.
With this PR we are preventing the event to be handled by multiple instances, and restrict it to the instance that is in the current top most screen.
https://mattermost.atlassian.net/browse/MM-18792
=> MM-18792 Fix paste files with multiple instances of PostTextbox

app/components/network_indicator/network_indicator.js
When the Network indicator component updated at times the previous request status from the WebSocket was different than `STARTED` thus the animation to dismiss the connecting bar was not being ran. Now we check if the current status is `SUCCESS` and the previous one was different than that to determine if the animation needs to run or not.
https://mattermost.atlassian.net/browse/MM-18176
=> MM-18176 Fix network indicator stock after re-connect

app/components/autocomplete_selector/autocomplete_selector.js, app/components/autocomplete_selector/index.js, app/components/custom_list/option_list_row/index.js, app/components/custom_list/option_list_row/option_list_row.js, app/components/widgets/settings/bool_setting.js, app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap, app/screens/interactive_dialog/__snapshots__/interactive_dialog.test.js.snap, app/screens/interactive_dialog/dialog_element.js, app/screens/interactive_dialog/dialog_introduction_text.js, app/screens/interactive_dialog/dialog_introduction_text.test.js, app/screens/interactive_dialog/interactive_dialog.js, app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap, app/screens/selector_screen/index.js, app/screens/selector_screen/selector_screen.js, app/screens/selector_screen/selector_screen.test.js
Updated Interactive Dialog for support of SafeAreaView on iOS
https://mattermost.atlassian.net/browse/MM-18464
=> MM-18464 Interactive dialog renders out of safe area view on landscape orientation

app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap, app/screens/channel/channel_nav_bar/channel_title/channel_title.js, app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
The localization string has a variable called `displayName` and we were passing `displayname`
=> Fix channel navbar title displayName variable

app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap, app/components/sidebars/main/channels_list/channel_item/channel_item.js
With the recent improvements to the sidebar the channel item was too bright causing confusion with unread channels.
This PR makes it so the applied opacity is the same as the webapp.
https://mattermost.atlassian.net/browse/MM-19076
=> Set Sidebar channel item  display name opacity as 0.6 (same as webapp)

app/components/emoji_picker/emoji_picker_base.js, app/components/emoji_picker/emoji_picker_row.js
The emoji picker after the change for using native emojis was cutting off a bit on the right edge some of the emojis, by giving a bit more space to the width and height we are preventing that from happening.
=> Fix native emojis being cutoff in emoji picker

app/components/markdown/markdown_table/markdown_table.js
Adds a button on the bottom-right corner of markdown tables to hint at the fact that they can be expanded upon being tapped
Fixes https://github.com/mattermost/mattermost-server/issues/11948
* Google Pixel 3 Emulator (Android 9)
=> GH-11948 Adding expand button to markdown tables

app/components/file_attachment_list/__snapshots__/file_attachment.test.js.snap, app/components/file_attachment_list/file_attachment.js, app/components/file_attachment_list/file_attachment.test.js
`style.fileInfoContainer` was a prop of the `TouchableOpacity` component prior to using the custom `TouchableWithFeedback` component so here I just remove the wrapping `View` and pass the style directly to `TouchableWithFeedback`.
https://mattermost.atlassian.net/browse/MM-19209
* iPad and Android emulator
=> [MM-19209] Pass fileInfoContainer style directly to Touchable

app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap, app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
MM-19180 - Updating spacing for mention component
https://mattermost.atlassian.net/browse/MM-19180
iPhone X 13.0
=> MM-19180 - Updating spacing for mentions component

app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap, app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap, app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap, app/utils/markdown.js, package-lock.json
Changes a mention's text color to use `mentionHighlightLink` instead of `linkColor`
This issue becomes most noticeable when the `linkColor` and `mentionHighlightBg` are set to be the same. This is the theme I used when I noticed the bug:
```
{"sidebarBg":"#327c7e","sidebarText":"#ffffff","sidebarUnreadText":"#ffffff","sidebarTextHoverBg":"#001f7e","sidebarTextActiveBorder":"#001f7e","sidebarTextActiveColor":"#ffffff","sidebarHeaderBg":"#001f7e","sidebarHeaderTextColor":"#ffffff","onlineIndicator":"#00ff00","awayIndicator":"#ffff00","dndIndicator":"#f74343","mentionBj":"#00ffff","mentionColor":"#ffffff","centerChannelBg":"#dcdfe2","centerChannelColor":"#000000","newMessageSeparator":"#f80","linkColor":"#0000ff","buttonBg":"#0000ff","buttonColor":"#ffffff","errorTextColor":"#fd5960","mention …
```
=> Fixing mention text color

app/store/store.js, ios/MattermostShare/ShareViewController.swift, ios/UploadAttachments/UploadAttachments/StoreManager.m, ios/UploadAttachments/UploadAttachments/UploadSession.swift
The receipt notification needs the serverURL to be set, at some point the url was removed from the `general.credentials` entities and is only being set when resetting the cache.
This fix consist on writing the url to the entities file as needed and also make sure to invoke the requests only if the serverURL and session token are set.
https://mattermost.atlassian.net/browse/MM-17157
=> MM-17157 Only send notification receipt if server url and session token are set

app/screens/flagged_posts/__snapshots__/flagged_posts.test.js.snap, app/screens/flagged_posts/flagged_posts.js, app/screens/flagged_posts/flagged_posts.test.js, app/screens/recent_mentions/__snapshots__/recent_mentions.test.js.snap, app/screens/recent_mentions/recent_mentions.js, app/screens/recent_mentions/recent_mentions.test.js
The `dismissModal` navigation action must complete prior to calling `showSearchModal`.
https://mattermost.atlassian.net/browse/MM-17381
* iPad and Android emulator
=> [MM-17381] Await dismissModal before calling showSearchModal

app/components/post_header/post_header.js
Not show the guest badge for system messages. When a guest joins to a channel
the system message is showing the badge for guest and shouldn't.
[MM-18930](https://mattermost.atlassian.net/browse/MM-18930)
This PR was tested on: [One Plus 5, Android 9]
=> Not show the guest badge for system messages

app/components/reactions/index.js
This PR disables the ability to add emoji reactions to posts in a read-only channel. The plus sign is now not present, and tapping on an existing emoji now has no effect.
https://mattermost.atlassian.net/browse/MM-19243
I had reacted to a post before making the channel read-only, to show the behavior of the fix:
=> [MM-19243] Disable reactions on read only channel

app/actions/views/channel_add_members.js
Removed getState from Add Channel Member method.
Removed getState from Add Channel Member method since the Redux store is not looking for it. 3rd param for this method is a postRootID, which is not sent from this request.
https://mattermost.atlassian.net/browse/MM-18173
No changes to the UI or the result of the request.
iPhone Xs Mac 12.3
=> MM-18173 Removed getState from Add Channel Member method

app/screens/settings/section.js
Added marginHorizontal spacing to the footer for sections.
Added a marginHorizontal to the footer text found in the Section element to resolve the spacing issue on the helper text.
https://mattermost.atlassian.net/browse/MM-18791
iPhone Xs Max 12.3
=> MM-18791: Add spacing to Helper text on Settings Screen

app/components/post/index.js, app/components/post/post.js, app/components/post_header/post_header.js, app/components/post_list/post_list.js
Added a check for previousPost to use in validating new messages in thread to check if we should display Commented On message.
Added boolean to check if a previousPost object is available.
Used the boolean to validate if a Commented On message should be displayed, as in testing on continued messages in a thread separated by the 'New Messages' line, a previousPost object would not be available.
https://mattermost.atlassian.net/browse/MM-18054
No items from checklist other than validating line does not display.
iPhone Xs Max 12.3
Android Pixel 2 API 29 (Simulator)
=> MM-18054: Removed Commented On from new messages in thread with same poster

app/screens/sso/index.js, app/screens/sso/sso.js
Added SafeAreaView padding for the SSO screen
This change applies SafeAreaView padding to the SSO screen. Due to limitations of the SSO screen, the applied SafeAreaView will apply padding to the entire view of the SSO login, instead of individual elements within.
https://mattermost.atlassian.net/browse/MM-18935
iPhone Xs Max 12.3
=> MM-18935: Added SafeAreaView padding for the SSO screen

patches/react-native-image-picker+0.28.1.patch
Patch react-native-image-picker with the fix from [react-native-image-picker/pull/1118](https://github.com/react-native-community/react-native-image-picker/pull/1118)
https://mattermost.atlassian.net/browse/MM-19425
* iPad, 13.1.2
=> [MM-19425] Patch react-native-image-picker

app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap, app/components/sidebars/main/channels_list/channel_item/channel_item.js
This PR makes the channel item display name more narrow, so the name does not overlap with the mention count.
https://mattermost.atlassian.net/browse/MM-19307
This PR was tested on: Google Pixel 2, Android 8.1.0
Before fix:
80% max width (This PR is currently at this value):
75% max width:
=> [MM-19307] Make LHS channel item display name not overlap with mention count

assets/base/i18n/en.json, share_extension/android/extension_post/extension_post.js, share_extension/android/extension_post/extension_post.test.js
On Android, one can't manually enter text into the share extension's text box past 4000 characters (the default/defined text size limit). However, this restriction can still be circumvented by sharing a large item of text. In this latter case, the textarea displays just the first 4000 characters, but the value buffer still contains the entire shared text. On hitting "Send", the oversize text can still be posted.
This commit implements [MM-15469](https://mattermost.atlassian.net/browse/MM-15469) to better align the Android sharing user experience with the existing iOS experience.
Bonus: Additional widget to show number of available characters remaining until textarea limit (default = 4000). Similar to iOS experience.
~Since a pre-existing i18n string was used …
=> MM-15469 (Android) Alert if shared text is longer than message limit

app/components/safe_area_view/__snapshots__/safe_area_view.ios.test.js.snap, app/components/safe_area_view/safe_area_view.ios.js, app/components/safe_area_view/safe_area_view.ios.test.js, app/screens/permalink/index.js, app/screens/permalink/permalink.js, app/screens/permalink/permalink.test.js
We previously listened to dimension changes and called `SafeArea.getSafeAreaInsetsForRootView` when the dimension change occurred, however, `getSafeAreaInsetsForRootView` wasn't returning the appropriate insets for the changed dimension probably because the dimension change hadn't yet been processed by `SafeArea`. We now just listen for `safeAreaInsetsForRootViewDidChange` and handle updating the insets then.
I also removed `setChannelLoading` and `setChannelDisplayName` from `permalink.js` as they are already dispatched in [handleSelectChannel](https://github.com/mattermost/mattermost-mobile/blob/11e2bdfc40ef13b1a923d47fd579a4fb6b464603/app/actions/views/channel.js#L382-L396).
https://mattermost.atlassian.net/browse/MM-18983
* iPhone X simulator
=> [MM-18983] Listen to safeAreaInsetsForRootViewDidChange over Dimension change

app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap, app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js, app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.test.js, assets/base/i18n/en.json
Adds an accessibility label to the channel drawer button.
Fixes https://github.com/mattermost/mattermost-server/issues/12839
JIRA: https://mattermost.atlassian.net/browse/MM-19328
- iPhone X iOS 12.4 Simulator
- iPhone 11 Pro iOS 13.1 Simulator
**X - 12.4**
**11 Pro - 13.1**
=> MM-19328 | Add accessibility label to channel drawer button.

app/screens/settings/notification_settings_auto_responder/notification_settings_auto_responder.js
Resolved the autoresponder keyboard flash by adding a 500ms delay to the keyboard focus, allowing for a smooth keyboard interaction without the color flash.
https://mattermost.atlassian.net/browse/MM-18790
Pixel 2 API 29 (Simulator)
Demo video of change
[MM-18790_demo.mov.zip](https://github.com/mattermost/mattermost-mobile/files/3700615/MM-18790_demo.mov.zip)
=> MM-18790 Fix Keyboard Color Flash

app/components/profile_picture/profile_picture.js, app/components/retry_bar_indicator/retry_bar_indicator.js, app/components/search_bar/search_box.js
Remove deprecated lifecycle methods from misc components.
- app/components/search_bar/search_box.js
- app/components/retry_bar_indicator/retry_bar_indicator.js
- app/components/profile_picture/profile_picture.js
JIRA: [MM-18770](https://mattermost.atlassian.net/browse/MM-18770)
Fixes mattermost/mattermost-server#12349
=> Remove deprecated lifecycle methods from misc components

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java, ios/Mattermost/AppDelegate.m
This is a cherry-pick of the changes made in https://github.com/mattermost/mattermost-mobile/pull/3352 so that the 1.25 version of the Android app will be compatible with the `update_badge` notifications being added for Mark as Unread in 1.26
https://mattermost.atlassian.net/browse/MM-18463
https://mattermost.atlassian.net/browse/MM-19071
=> MM-18463 Added update_badge notification when marking a channel as unread (1.25)

app/components/safe_area_view/safe_area_view.ios.js, app/components/safe_area_view/safe_area_view.ios.test.js, app/constants/view.js, app/store/ephemeral_store.js
While https://github.com/mattermost/mattermost-mobile/pull/3413 fixed the original issue, it introduced another problem where the insets were removed on a previous screen when navigating back to it. Rather than continuously apply the insets returned by `safeAreaInsetsForRootViewDidChange`, we now store the values returned by it in the ephemeral store and stop listening for changes when both portrait and landscape values have been stored. With those values stored, we can apply the correct insets when the orientation changes.
https://mattermost.atlassian.net/browse/MM-18983
* iOS simulator
=> [MM-18983] Store insets in ephemeral store

app/screens/edit_post/edit_post.js
Add Autocomplete to Edit Post screen.
* [Jira](https://mattermost.atlassian.net/browse/MM-13842)
* Fixes https://github.com/mattermost/mattermost-server/issues/10159
* OnePlus 5, Android 9
* iPhone X (Simulator)
| iOS | Android |
| --- | --- |
| <img alt="iOS" width="487" src="https://user-images.githubusercontent.com/887849/65430389-3a34bb00-ddee-11e9-96c3-e3340d31b281.gif"> | <img alt="Android" width="487" src="https://user-images.githubusercontent.com/887849/65430434-52a4d580-ddee-11e9-8b95-1624d162331f.gif"> |
Fixes https://github.com/mattermost/mattermost-server/issues/10159
=> MM-13842 Add Autocomplete to post edit screen

.circleci/config.yml, fastlane/Fastfile
For iOS the lane `upload_to_tesflight` is not available on circleCI and we needed to switch back to `pilot`
For Android we needed to include the private repo to get the keystore
For both: Fixed the deployment file path
=> Fix android and iOS deployment on circleCI

app/components/post_header/__snapshots__/post_header.test.js.snap, app/components/post_header/post_header.js, app/components/post_header/post_header.test.js
Updated the displayName to check for the reply button and bot tag. If seen the displayName container is set from 60% to 55% to allow for the extra space.
https://mattermost.atlassian.net/browse/MM-19308
iPhone Xs Max 12.3
=> MM-19308 Fixed date wrapping

patches/react-native+0.59.9.patch
There is an outstanding bug in RN that adds a placeholder to an image where the image is inside a Text node, this happens only on iOS 13 but the fix does not causes side effects in previous iOS versions.
The RN commit is https://github.com/facebook/react-native/commit/06599b3e594355a1d5062ede049ff3e333285516 but has not been cherry-picked to any of the current releases
https://mattermost.atlassian.net/browse/MM-19734
=> MM-19734 Patch RN to remove the placeholder for emojis in a markdown

app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap, app/screens/settings/notification_settings/notification_settings.js, app/screens/settings/notification_settings/notification_settings.test.js
When `saveNotificationProps` was called after pressing back from the NotificationSettingsMobile screen, `updateMe` was called with a `notifyProps` object that did not include previously set notify props keys for the user (like `auto_responder_active`).
https://mattermost.atlassian.net/browse/MM-19246
* Android and iOS simulators
=> [MM-19246] Include previous notify props when saving new ones

app/selectors/autocomplete.js, app/selectors/autocomplete.test.js
Reported by whitestar `at-mentions` autocomplete was not returning out of channel results in any type of channel
https://mattermost.atlassian.net/browse/MM-19731
=> MM-19731 Fix at-channel autocomplete to return out of channel mentions

package-lock.json, package.json
Updated package.json for mattermost-redux hash to resolve issue where Favorites were not updating when mobile app was not in foreground.
Actual Redux changes are here: https://github.com/mattermost/mattermost-redux/pull/956
https://mattermost.atlassian.net/browse/MM-19448
=> [MM-19448] Get user preferences on WebSocket reconnect

app/selectors/autocomplete.js, app/selectors/autocomplete.test.js
Cherry pick of #3477 on release-1.25.
- #3477: MM-19731 Fix at-channel autocomplete to return out of
/cc  @enahum
=> Automated cherry pick of #3477

app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap, app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap, app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap, app/utils/markdown.js
Reverted mentions color to use `linkColor` to fix inconsistencies with the webapp and the related bug.
Fixes [MM-19655](https://mattermost.atlassian.net/browse/MM-19655)
=> MM-19655 - Reverted mention color to user linkColor

app/components/message_attachments/attachment_image/__snapshots__/index.test.js.snap, app/components/message_attachments/attachment_image/index.js, app/components/progressive_image/progressive_image.js, package-lock.json
Image container should respect the padding and be larger than the image dimensions and center the image.
https://mattermost.atlassian.net/browse/MM-18934
=> MM-18934 Fix padding on image attachment border

app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap, app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap, app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap, app/utils/markdown.js
Cherry pick of #3472 on release-1.25.
- #3472: Reverted mention color to user linkColor
/cc  @marianunez
=> Automated cherry pick of #3472

.circleci/config.yml
In circleCi we are trying to persist the `mattermost-mobile*` directories but the root path was set to `/` instead of the home directory `~/`
=> circleCI change persist root from / to ~/

patches/react-native-youtube+1.1.0.patch
Takes the AVKit fix on react-native-youtube v2 and applies it to our v1 fork. We're already using v2 on master so this is not necessary there.
https://mattermost.atlassian.net/browse/MM-19861
* iOS 13.1 simulator
=> [MM-19861] Apply AVKit fix to react-native-youtube

app/screens/channel/channel_base.js, app/screens/channel/channel_base.test.js
The Channel component ID is not yet included in the ephemeral store's `allNavigationComponentIds` when it receives a new theme after login so I added a direct call to `setNavigatorStyles` with the component ID.
This change also fixes transitions back to the channel screen after logging in / clearing data from the advanced settings.
https://mattermost.atlassian.net/browse/MM-19698
https://mattermost.atlassian.net/browse/MM-19084
* iOS simulator, 13.1
=> [MM-19698] [MM-19084] Ensure setNavigatorStyles is called with Channel componentId

app/screens/channel/channel_base.js, app/screens/channel/channel_base.test.js
Cherry pick of #3515 on release-1.25.
- #3515: Ensure setNavigatorStyles is called with Channel componentId
/cc  @migbot
=> Automated cherry pick of #3515

app/initial_state.js, app/screens/select_server/select_server.js
With the recent changes to the custom SafeAreaView component, the server url screen was not using the right inset at times, by using the one provided by RN this is fixed. We do not need to use any of the custom component functionality in this screen.
https://mattermost.atlassian.net/browse/MM-19853
=> MM-19853 Fix iOS SafeAreaView for Server URL screen

app/store/store.js, package-lock.json, package.json
Because the current team's theme was lost during a state reset, the header color in the Advanced Settings screen would revert to the default Mattermost theme color. This is fixed by keeping currentTeamId and the theme preferences in the state.
https://mattermost.atlassian.net/browse/MM-19841
* iOS simulator, 13.1
=> [MM-19841] Keep currentTeamId and team theme preferences when resetting state

app/push_notifications/push_notifications.ios.js, app/utils/push_notifications.test.js
With the upgrade to the notifications library the `consumeBackgroundQueue` API was removed. This was responsible for getting the initial push notification when the app is launched from a push notification. We now fetch the initial push notification on iOS with `getInitialNotification`.
https://mattermost.atlassian.net/browse/MM-19927
* iPhone 11, iOS 13.1.3
=> [MM-19927] Fix launching app from push notification on iOS

app/screens/settings/notification_settings_mobile/notification_settings_mobile_base.js
As part of the effort to remove deprecated lifecycle events, `componentWillReceiveProps` was removed in favor of `componentDidUpdate` in the `NotificationSettingsMobileBase` and `NotificationSettingsMobileAndroid` components on master, however, probably due to a cherry-pick that included changes only in `NotificationSettingsMobileAndroid`, `componentWillReceiveProps` remained and `componentDidUpdate` was missing in the base component on release-1.25.
https://mattermost.atlassian.net/browse/MM-19967
* Android emulator, 8.0
=> [MM-19967] Use componentDidUpdate

android/app/src/main/AndroidManifest.xml
Apply the following changes from master: https://github.com/mattermost/mattermost-mobile/commit/1efb01deda81cc0ee0fa0a36af8c02e342272f11#diff-020edf1fd6d483b0e2c8f5a5734ea1f2L32-L55
This prevents a white screen flashing when returning the app to the foreground on Android.
* Android emulator, 8.0
=> Set launchMode to singleInstance

app/utils/push_notifications.js
The changes to handle `update_badge` notifications made in #3352 and #3465 missed updating the in-app notification handling, so this adds handling for those notifications when the app is currently open.
https://mattermost.atlassian.net/browse/MM-19812
=> MM-19812 Properly handle in-app update_badge notifications

app/actions/views/channel.js, app/actions/views/channel.test.js, app/actions/views/root.js, app/screens/notification/__snapshots__/notification.test.js.snap, app/screens/notification/notification.test.js, app/utils/push_notifications.js, test/setup.js
Prior to the changes in this PR, when launching the app from a push notification to a channel that had not yet been loaded, `lastViewedAt` was undefined and since `SELECT_CHANNEL_WITH_MEMBER` was not dispatched it remained undefined. This prevented the `START_OF_NEW_MESSAGES` item from being added to the postIds list. I've fixed this by always dispatching `SELECT_CHANNEL_WITH_MEMBER`, regardless of whether `handleSelectChannel` was called from a push notification, and regardless of whether the `channelId` pass is the `currentChannelId`.
https://mattermost.atlassian.net/browse/MM-19968
* iPhone 11, iOS 13.1
=> [MM-19968] Ensure SELECT_CHANNEL_WITH_MEMBER is dispatched when app opened from a push notification

app/screens/settings/notification_settings/notification_settings.js, app/screens/settings/notification_settings/notification_settings.test.js
Fixed the save functionality for props. There was a change to combine notification settings that then did a deep comparison on two like objects. This change makes the comparison of the newly changed notification props and the previous props.
https://mattermost.atlassian.net/browse/MM-19966
Android Pixel API 29 (Simulator)
=> MM-19966 Fixed Notification Settings

package-lock.json, package.json
As discussed, because we can't properly save that `isManuallyUnread` state between sessions, we're going to remove this special behaviour when using the Mark as Unread feature.
https://mattermost.atlassian.net/browse/MM-19482
Redux: https://github.com/mattermost/mattermost-redux/pull/968
Web: https://github.com/mattermost/mattermost-webapp/pull/4138
=> MM-19482 Stop rendering New Messages line differently for manually unread channels

app/actions/views/channel.js, app/actions/views/channel.test.js
The action for `markChannelViewedAndRead` is a thunk and it does not get trigger when is part of a batch, dispatching the action independently fixes the issue.
https://mattermost.atlassian.net/browse/MM-20149
=> MM-20149 Fix marking channels as read

app/actions/views/channel.js, app/actions/views/channel.test.js
Cherry pick of #3549 on release-1.25.
- #3549: MM-20149 Fix marking channels as read
/cc  @enahum
=> Automated cherry pick of #3549

app/screens/image_preview/downloader.ios.js, ios/Podfile.lock, package.json
Switched CameraRoll over to the react-native-community version as it was removed from the core package with RN 0.61.2
https://mattermost.atlassian.net/browse/MM-19697
iPhone 11 Pro 13.1
=> MM-19697 - Fixed CameraRoll for iOS

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
The server will return a localized default message with the ID loaded push notification so there's no need to add one on the Android side when the fetch fails.
https://mattermost.atlassian.net/browse/MM-16232
=> [MM-16232] Android: remove ID loaded default message

app/screens/more_channels/__snapshots__/more_channels.test.js.snap, app/screens/more_channels/more_channels.js
The options were using the default color for the font which is `black` this PR changes to use the `theme.centerChannelColor`
=> Fix theme color for the more channel options

app/components/message_attachments/attachment_thumbnail.js, app/components/progressive_image/progressive_image.js, app/screens/image_preview/image_preview.js, package-lock.json
Use `FastImage` for the **ProgressiveImage** component and in the **ImagePreview** that has a better image processing and memory management that the RN `Image` component. After applying this change iOS no longer crash on some `gif` images.
https://mattermost.atlassian.net/browse/MM-20007
This PR was tested on: iPhone 6s, iPhone Xs, Android emulator
=> MM-20007 Fix app crashes when previewing some gif files

.circleci/config.yml
Install watchman on circleCI to avoid watchman from crashing
=> Fix CircleCI iOS build by adding watchman

package-lock.json, package.json
When forking the [react-native-cookie repo](https://github.com/mattermost/react-native-cookies) we forgot to include [the patched](https://github.com/mattermost/react-native-cookies/commit/a54c0ffd28679871dd11e3396d8382cc8ff204d1) that lived in `native_modules` causing this bug to re-appear.
Note: This needs to be cherry-picked to the release-1.26 and **release-1.25** so it can be included in the next release and 1.25.1 dot release
**Important: The cherry-pick for 1.25 needs to be done manually**
https://mattermost.atlassian.net/browse/MM-20355
=> Fixes crash when sso cookies does not contain an expiration date

ios/MattermostShare/ShareViewController.swift
There appears to be a bug on iOS 13 (the operating system) where setting `charactersRemaining` and `placeholder` properties the memory spikes all the way up to 120Mb which is the limit of a Share Extension and thus causing the extension to close (crash).
This PR removes that functionality on iOS 13 only.
https://mattermost.atlassian.net/browse/MM-20224
=> Avoid OOM crash on iOS13 Share Extension

app/components/at_mention/__snapshots__/at_mention.test.js.snap, app/components/at_mention/at_mention.js, app/components/at_mention/at_mention.test.js, app/components/at_mention/index.js
Updated the AtMention to check if it will be highlighted before applying its color. The highlight function was applying its color before the AtMention color, so it was being overwritten.
https://mattermost.atlassian.net/browse/MM-19834
iPhone X 13.2 (Simulator)
=> MM-19834 Fixed direct mentions highlight color

assets/base/release/splash_screen/android/layout/launch_screen.xml
When running the build script for Android release the splash screen layout is being overwritten by the one in the assets folder, that file was not updated to make use of `androidx` and the previous `android.support` libraries are no longer included causing the crash.
**Note:** This PR also updates the Podfile.lock that was outdated.
https://mattermost.atlassian.net/browse/MM-20667
=> [MM-20667] Fixes crash on Android release build

app/components/autocomplete/autocomplete.js, app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap, app/components/edit_channel_info/edit_channel_info.js, app/components/edit_channel_info/edit_channel_info.test.js
Moved the autocomplete below the header input and made it so that it expands down. In order to have enough space for the autocomplete dropdown to show correctly, we auto-scroll so that the header section is at the top of the screen.
https://mattermost.atlassian.net/browse/MM-20200
* iOS simulator, 13
Android:
iOS:
=> [MM-20200] Fix autocomplete when editing channel header

app/screens/image_preview/image_preview.js, app/screens/image_preview/image_preview.test.js
Using a modal to show download options in the image preview screen did not play nice with our safe area view component when the modal was dismissed and the status bar visibility returned, so it's been replaced with an action sheet. There was also an issue on Android that when hiding the status bar a white area would be displayed where the status bar previously was, so for Android we are no longer hiding the status bar.
https://mattermost.atlassian.net/browse/MM-20673
* iPhone simulator, iOS 13
* iPad simulator
iPhone:
iPad:
=> Use bottom sheet over modal

app/components/post_header/__snapshots__/post_header.test.js.snap, app/components/post_header/index.js, app/components/post_header/post_header.js, app/components/post_header/post_header.test.js
Adjusted landscape maxWidth for both the base display of the name and the adjusted width with bot/reply buttons.
https://mattermost.atlassian.net/browse/MM-19708
iPhone X 13.2 (Simulator)
Android Pixel API 29 (Simulator)
=> MM-19708 Adjusted display name width to 80% for landscape

app/init/global_event_handler.js, app/screens/sso/sso.js
SSO login cannot use share cookies but instead the only use the share process pool in order to be able to access to cookie values.
When removing the cache folder on logout the app was hanging if there was a failure (the cache folder does not exists or something similar)
=> Fix SSO login on iOS

app/components/combined_system_message/combined_system_message.js, app/components/formatted_markdown_text.js, app/components/markdown/markdown.js
Removed the opacity that was set on the base text style for the markdown on AtMention for system messages.
https://mattermost.atlassian.net/browse/MM-19837
Pixel 2 API 29 Simulator
=> MM-19837 Remove Opacity from AtMention Markdown

app/screens/post_options/index.js, app/screens/post_options/index.test.js, app/screens/post_options/post_options.js, app/screens/post_options/post_options.test.js
* Check for server version with min 5.18v for showing the option to mark as unread
https://mattermost.atlassian.net/browse/MM-20790
Tested on an iphone X simulator
Before:
After:
=> MM-20790 Mark as Unread option should not be available on mobile if the server does not support it

app/components/sidebars/settings/settings_sidebar.js
When the change status options modal is open tapping on the hardware back button now closes the modal first and then tapping again closes the settings drawer
https://mattermost.atlassian.net/browse/MM-20682
=> MM-20682 Android back button to dismiss status modal first

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
The notification number was being set to 0 when not null, overriding the correct count.
Note: Stylianos found the same issue on iOS, however, I've been unable to reproduce.
https://mattermost.atlassian.net/browse/MM-20964
=> [MM-20964] Set number to 0 only if null

app/components/autocomplete/autocomplete.js, app/screens/edit_post/edit_post.js
The view wrapping the autocomplete is rendered atop the post view even when there are no autocomplete children, thus preventing taps from registering on the post view. With these changes, the view wrapping the autocomplete only shows when there are autocomplete children.
https://mattermost.atlassian.net/browse/MM-20930
* iOS simulator, 13.2.2
=> [MM-20930] Show autocomplete view only when there are children

app/mattermost.js, app/store/utils.js
For some reason, even though the promise in `waitForHydrarion` called `resolve()`, the await call would not resolve. By passing a callback we avoid this issue.
https://mattermost.atlassian.net/browse/MM-20976
=> [MM-20976] Pass callback to waitForHydration instead of using await

app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/autocomplete/emoji_suggestion/index.js, app/components/emoji_picker/emoji_picker_base.js, app/components/emoji_picker/index.js, app/utils/emoji_utils.js, app/utils/emoji_utils.test.js
This PR introduces support for custom sorting rules for emojis. It gives the option to add additional rules if needed.
Fixes https://github.com/mattermost/mattermost-server/issues/11437
This PR was tested on:  TBA
Web app changes https://github.com/mattermost/mattermost-webapp/pull/4354
=> [GH-11437] Fix thumbs emoji sorting logic for mobile

android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
The push notification sent on a failed reply was missing `channel_id` so when `clearChannelNotifications` was called it did not find any delivered notifications for the channel.
https://mattermost.atlassian.net/browse/MM-20967
=> [MM-20967] Add channel ID to push notification sent on failed reply

app/actions/views/channel.js, app/components/network_indicator/index.js, app/components/network_indicator/network_indicator.js
When the app comes from the background, it reconnects to the websocket which triggers the current channel to be marked as read. This no longer happens for manually unread channels.
Note that this doesn't change the behaviour when the app is closed and reopened, but that's a much more difficult case to change since I think that's caused by the "select channel" logic being triggered similar to switching to the channel in the first place.
https://mattermost.atlassian.net/browse/MM-20947
=> MM-20947 Don't mark channel as read when reconnecting to manually unread channel

app/actions/views/channel.js, app/components/network_indicator/index.js, app/components/network_indicator/network_indicator.js
Cherry pick of #3685 on release-1.26.
- #3685: MM-20947 Don't mark channel as read when reconnecting to
/cc  @hmhealey
=> Automated cherry pick of #3685

app/components/__snapshots__/send_button.test.js.snap, app/components/attachment_button/index.js, app/components/post_textbox/__snapshots__/post_textbox.test.js.snap, app/components/post_textbox/post_textbox_base.js, app/components/send_button.js
Fixes the alignment of the attach file icon and the send icon on the post textbox area
https://mattermost.atlassian.net/browse/MM-19920
https://mattermost.atlassian.net/browse/MM-19924
Android
iOS
=> MM-19920 MM-19924 Fix mis-align post input field attach and send icons

app/components/widgets/settings/bool_setting.js, app/components/widgets/settings/bool_setting.test.js
Match the webapp behaviour so as to avoid stringifying booleans in the interactive dialog payloads.
Fixes: https://mattermost.atlassian.net/browse/MM-17519
This PR was tested on: iOS mobile simulator
Using the demo plugin's `/dialog` trigger, the behaviour before:
and after:
=> MM-17519: do not stringify booleans for interactive dialogs

app/components/post_textbox/post_textbox.test.js, app/components/post_textbox/post_textbox_base.js
When a slash command failed to execute an alert is being displayed but the execution was not stopped thus the text and draft was cleared
https://mattermost.atlassian.net/browse/MM-21176
=> MM-21176 Preserve text on input if command fails

app/screens/image_preview/downloader.ios.js
* componentWillReceiveProps is being deprecated. Replace its usage in app/screens/image_preview/downloader.ios.js.
* Bonus UI polish - The download progress component's contents shift up after the component is displayed - avoid this jitter. 
GH: https://github.com/mattermost/mattermost-server/issues/12353 (the ticket calls out several components - since this my first contribution I wanted to keep the PR small and started with just one).
JIRA:  https://mattermost.atlassian.net/browse/MM-18766
This PR was tested on: iPhone X Simulator Running IOS 13.
Successfully download the image:
Canceling the download then trying again:
=> MM-18766 - componentWillReceiveProps is being deprecated

app/actions/views/channel.js, app/reducers/views/channel.js, app/reducers/views/channel.test.js, app/screens/channel/channel_post_list/channel_post_list.js, app/screens/channel/channel_post_list/channel_post_list.test.js, app/screens/channel/channel_post_list/index.js, package-lock.json, package.json
Manual cherry pick of #3662. Updated the mattermost-redux hash to point to 5.19.
=> Manual cherry pick of #3662

app/components/widgets/settings/bool_setting.js, app/components/widgets/settings/bool_setting.test.js
Cherry pick of #3693 on release-1.27.
- #3693: MM-17519: do not stringify booleans
/cc  @lieut-data
=> Automated cherry pick of #3693

app/components/sidebars/settings/settings_sidebar.test.js
Cherry pick of #3664 on release-1.27.
- #3664: MM-20682 Unit test for dimissing the status modal before the
/cc  @enahum
=> Automated cherry pick of #3664

package-lock.json, package.json
`jsc-android` was accidentally downgraded when I updated to RN 61 and we're seeing many crashes originating in `libjsc.so` in Android. This change upgrades `jsc-android` to the version used in v1.25.
=> Upgrade jsc-android

app/components/post_textbox/__snapshots__/post_textbox.test.js.snap, app/components/post_textbox/post_textbox_base.js
This PR makes sure that while a user is writing a post, they won't need to dismiss the keyboard before being able to tap any of the buttons in the post draft area.
https://mattermost.atlassian.net/browse/MM-20989
=> MM-20989: Ensuring keyboard doesn't dismiss while submitting post

package-lock.json, package.json
updated mmjstool reference
Fixes: https://mattermost.atlassian.net/browse/MM-21148
mmjstool - https://github.com/mattermost/mattermost-utilities/pull/21
webapp - https://github.com/mattermost/mattermost-webapp/pull/4580
=> MM-21148 -  `make i18n-extract` throws an error if mobile repo is not checked out

android/app/build.gradle
There seems to be two possible causes for these ANRs: [background execution limits](https://stackoverflow.com/questions/46117554/firebasemessagingservice-crashes-on-android-o-due-to-background-execution-limits) introduced in Android 8 and [timing issues](https://github.com/firebase/quickstart-android/issues/594#issuecomment-451528198).
While I've been unable to repro, the [release notes for v17.3.2](https://firebase.google.com/support/release-notes/android#version_1732) state that an issue causing ANRs when receiving messages was fixed. 
https://mattermost.atlassian.net/browse/MM-16604
* Samsung S7, Android 8.0.0
=> [MM-16604] Upgrade to firebase-messaging v17.3.4

android/app/src/main/AndroidManifest.xml
#1805 enabled support for deep links for iOS. The link parsing mechanism remains the same for both platforms, but this commit enables registration of the URL scheme to the Android OS so that deep links can be accessed.
This PR was tested on: Android 9 device (OnePlus 5)
| to Permalink | to Channel |
| --- | --- |
| <img width="373" alt="permalink" src="https://user-images.githubusercontent.com/887849/71643891-28409f00-2c9e-11ea-9b5b-b1e15487acc7.gif"> | <img width="373" alt="channel" src="https://user-images.githubusercontent.com/887849/71643893-2c6cbc80-2c9e-11ea-8f1a-221b80efbe9b.gif"> |
**Deep Link URL patterns**
* `mattermost://<teamname>/channels/<channelname>`
* `mattermost://<teamname>pl/<permalinkID>`
=> Enable Deep Links for Android

app/components/post_textbox/__snapshots__/post_textbox.test.js.snap, app/components/post_textbox/post_textbox_base.js
This PR disables the `@` button in the post draft when the user has already tapped it, or manually inputted `@` (the icon is re-enabled once the user inputs more text or selects a user from the suggestion list)
https://mattermost.atlassian.net/browse/MM-20998
- iPhone 11 Simulator
`@` icon disabled when button was just pressed
=> MM-20998 - Preventing the @ icon from being repeatedly tappable

patches/react-native+0.61.2.patch
React Native `ScrollViews` (including `FlatLists`) are flipped upside down when the prop `inverted` is set to `true`. This is the root of many bugs one of them affecting `PostList`: tapping on the status bar in iOS should scroll the `Flatlist` up to the top.
The solution proposed is to detect natively if the ScrollView is inverted, on such case, prevent it from scrolling it to the beginning of the `ScrollView` (as a non-inverted ScrollView would do) and force a scroll to the end of it.
I've been careful not to force the scroll if the user explicitly selected not to do it or if it's happening in a nested `ScrollView`, as it's default in iOS.
Fixes https://github.com/mattermost/mattermost-server/issues/13220
Jira Ticket: https://mattermost.atlassian.net/browse/MM-9548 …
=> MM-9548 - Scroll to top when iOS status bar is pressed

app/init/fetch.js, app/init/fetch.test.js
The `X-*` headers returned in responses from the community server are lower case and since we were not checking for lower case `HEADER_X_VERSION_ID`, the mobile app never had a `serverVersion` to use in `isMinimumServerVersion` calls. 
https://mattermost.atlassian.net/browse/MM-21270
* iOS simulator, 13.3
=> [MM-21270] Handle lower case headers

assets/base/i18n/en.json, ios/MattermostShare/ShareViewController.swift, share_extension/android/extension_post/extension_post.js
When not a member of any team and trying to share a file via the share extension, the Android app would crash as it allowed for posting of a message without a channel ID. This crash did not happen on iOS since the "post" button is greyed out until a team and channel are selected, however, the channel dropdown just displayed a loading spinner. With this change we alert the user that they must be a part of a team before they can share files. The alert message is `You must belong to a team before you can share files.` Let me know if that needs to change.
https://mattermost.atlassian.net/browse/MM-21582
* Android emulator, Q
* iOS simulator, 13.3
Android:
iOS:
=> [MM-21582] Show alert when not a member of a team

app/components/autocomplete/at_mention_item/at_mention_item.js, app/components/autocomplete/at_mention_item/index.js, app/selectors/autocomplete.js, app/selectors/autocomplete.test.js, assets/base/i18n/en.json
Includes the current user in autocomplete suffixed with '(you').
Fixes https://github.com/mattermost/mattermost-server/issues/12313
This PR was tested on: iPhone 11 emulator, ios 13.3
=> MM-18571: Include self user in autocomplete

app/components/file_attachment_list/file_attachment_list.js, app/components/file_attachment_list/file_attachment_list.test.js, app/components/file_upload_preview/file_upload_item/file_upload_item.js, app/components/file_upload_preview/file_upload_item/file_upload_item.test.js, app/components/post_textbox/components/typing/typing.js, app/components/post_textbox/components/typing/typing.test.js, app/components/post_textbox/post_textbox.test.js, app/components/post_textbox/post_textbox_base.js
Remove deprecated lifecycle methods from these files:
- app/components/file_upload_preview/file_upload_item/file_upload_item.js
- app/components/emoji_picker/emoji_picker_base.js
- app/components/post_textbox/post_textbox_base.js
- app/components/file_attachment_list/file_attachment_list.js
- app/components/post_textbox/components/typing/typing.js
JIRA: https://mattermost.atlassian.net/browse/MM-18767
Fixes https://github.com/mattermost/mattermost-server/issues/12352
=> MM-18767 Remove deprecated lifecycle methods from post textbox

android/app/src/main/AndroidManifest.xml, app/utils/url.js, fastlane/Fastfile, fastlane/env_vars_example, ios/Mattermost/Info.plist
Default deep link URL prefix is now `mattermost-beta`
To set to `mattermost-mobile` (or anything else, for that matter) in production releases, set new fastlane ENV variable `DEEPLINK_PREFIX` to `mattermost-mobile`
**IMPORTANT: New ENV variable for Release builds!**
* [MM-12215](https://mattermost.atlassian.net/browse/MM-12215)
* Android 9 (OnePlus 5 device)
**Release Build**
| to Permalink | to Channel |
| --- | --- |
| <img width="250" alt="permalink-release" src="https://user-images.githubusercontent.com/887849/71686984-80010800-2d7b-11ea-87ce-34fd3843009b.gif"> | <img width="250" alt="channel-release" src="https://user-images.githubusercontent.com/887849/71686983-7f687180-2d7b-11ea-8b78-8005a604cd81.gif"> |
**Beta Build**
| to Permalink | …
=> [MM-12215] Make deep link URL prefix configurable for Release/Beta

app/store/store.js, ios/UploadAttachments/UploadAttachments/UploadSession.swift
When removing the user session token from the entities file the `config` and `license` were also removed, this PR adds back the `config` and `license` needed by the share extension.
Also makes a bit more robust the parsing of the file_info of the uploaded files to avoid creating a complete empty post.
https://mattermost.atlassian.net/browse/MM-21613
=> MM-21613 Fix iOS Share extension alert message when file size is larger than allowed

app/components/widgets/settings/bool_setting.js, app/components/widgets/settings/bool_setting.test.js
This reverts commit 765545570f88fd99c186c2b7927787b939ea90e3, with the original and now larger set of improvements to checkbox handling in interactive dialogs deferred until the next release.
Fixes: https://mattermost.atlassian.net/browse/MM-21632
=> Revert "MM-17519: do not stringify booleans (#3717)"

android/app/src/main/AndroidManifest.xml, app/mattermost.js
Changed the `launchMode=singleInstance` from the MainActivity to the Share Activity and now images and videos can be upload again from within the app when no default gallery or camera app is selected. Intent works as normal.
To fix the splash screen being stuck when opening the share extension and then the app, the `launchApp` is now called regardless and works as expected.
https://mattermost.atlassian.net/browse/MM-21288
=> MM-21288 Fix attaching files on Android

app/actions/views/channel.js, app/actions/views/channel.test.js, app/components/markdown/markdown_link/markdown_link.js, assets/base/i18n/en.json
Alerts when clicking on a link to a private channel/group.
* [MM-21068](https://mattermost.atlassian.net/browse/MM-21068)
* Android 9 device (OnePlus 5)
* iPhone X (simulator)
| Denied (Private) | Permitted (Public) |
| --- | --- |
| <img width="373" alt="denied" src="https://user-images.githubusercontent.com/887849/71517837-a233eb00-288e-11ea-88f0-c96926a1bbbe.gif"> | <img width="373" alt="permitted" src="https://user-images.githubusercontent.com/887849/71517838-a2cc8180-288e-11ea-8df3-f582fb7a0c08.gif"> | 
---
**Open Questions**
* ~~I've reused the pre-existing Permalink message (`Permalink belongs to a deleted message or to a channel to which you do not have access`). Should we have a different, more-specific message for this use case?~~
=> [MM-21068] Notify when attempting to enter private channel/group via explicit link

app/components/post_list/post_list.js
Previously, deep links would only work when the app was already open/previously launched.
Now, invoking a deep link launches the app if not already open, and opens the deep link destination.
* [MM-14470](https://mattermost.atlassian.net/browse/MM-14470)
* Android 9 (OnePlus 5 device)
---
**Format for deep links (Beta builds)**
* Channel: `mattermost-beta://<server-url>/<team-name>/channels/<channelID>`
* Permalink: `mattermost-beta://<server-url>/<team-name>/pl/<permalinkID>`
=> [MM-14470] Deep links launch when app is not already open

app/screens/interactive_dialog/dialog_element.js, app/screens/interactive_dialog/dialog_element.test.js, app/screens/interactive_dialog/interactive_dialog.js, app/screens/interactive_dialog/interactive_dialog.test.js
My fix for [MM-17519](https://mattermost.atlassian.net/browse/MM-17519) broke the /rendering/ of the boolean toggle, but not the underlying interactive dialog state (and the thrust of the original issue). I think I was too focussed on the encoding in the original issue to realize the UI had not reflected the change.
My original change was [reverted](https://github.com/mattermost/mattermost-mobile/pull/3803) in v1.27, 
but this ticket continues to capture the required changes to complete the effort.
https://mattermost.atlassian.net/browse/MM-21632
https://mattermost.atlassian.net/browse/MM-21683
=> MM-21632: fix toggling interactive dialog boolean

app/actions/views/login.js, app/actions/views/login.test.js, app/init/fetch.js, app/init/fetch.test.js
Because of this [change](https://github.com/mattermost/mattermost-mobile/pull/3710/files#diff-090700099e8f4c1cf06a416092bd7a9aR117) to set the server version from headers in `doFetchWithResponse`, mattermost-redux no longer emits `General.SERVER_VERSION_CHANGED` and so [GlobalEventHandler's onServerVersionChanged](https://github.com/mattermost/mattermost-mobile/blob/get-config/app/init/global_event_handler.js#L226), which dispatches `loadConfigAndLicense`, never gets called. This leads to `config.CloseUnusedDirectMessages` being undefined and [`isAutoClose`](https://github.com/mattermost/mattermost-redux/blob/d4b655287768cd72089a3f82e43652a9b4e1008b/src/utils/channel_utils.ts#L174) returning an incorrect value causing all DMs to be listed in the main sidebar. To fix this we now dispatch …
=> [MM-21865] Dispatch loadConfigAndLicense on successful login

app/components/markdown/markdown_code_block/markdown_code_block.js
Fixes the keyboard not dismissing when entering the code screen that in turn was causing the keyboard staying open when showing  the channel drawer.
https://mattermost.atlassian.net/browse/MM-21634
=> MM-21634 Fix keyboard glitch when returning to channel screen from the code screen

android/app/src/main/AndroidManifest.xml, app/components/post_list/post_list.test.js, app/utils/url.test.js, fastlane/Fastfile, fastlane/env_vars_example, ios/Mattermost/Info.plist
Was originally set to `mattermost-beta` as per #3767 . Setting default to `mattermost` per apps grooming conversation.
**IMPORTANT**
Environment variables in various CircleCI schemes must be updated with `APP_SCHEME` set to `mattermost`, instead of current `mattermost-beta`.
=> Set default app scheme to `mattermost`

fastlane/Fastfile
Updates the package.json and package-lock.json files with the new version number and adds a new line at the end of each file
=> Fix Fastlane script to bump version number

android/app/build.gradle
Fixes following fatal error with Release builds:
`java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so`
* Android 9 device (OnePlus 5)
=> Fix Android unsigned releases to work with Hermes

android/app/build.gradle
Cherry pick of #3841 on release-1.28.
- #3841: Fix Android unsigned releases to work with Hermes
/cc  @chuttam
=> Automated cherry pick of #3841

android/app/src/main/AndroidManifest.xml, app/mattermost.js
Calling `Linking.getInitialURL()` in `launchApp` ensures that it's called regardless of `EphemeralStore.appStarted`'s value in `init`. I added `launchMode=singleTask` to the MainActivity since without it I would see a second instance of Mattermost opened via deeplink if one was previously running in the background. I tested https://mattermost.atlassian.net/browse/MM-21288 and the `singleTask` change does not cause any issues for me but should be tested by QA as well. iOS should also be tested to ensure deeplink continue to work there.
https://mattermost.atlassian.net/browse/MM-21771
https://mattermost.atlassian.net/browse/MM-21288
* Android 10 emulator
=> [MM-21771] Call Linking.getInitialURL() in launchApp

ios/Mattermost/UIPasteboard+GetImageInfo.m
`getMimeAndExtensionWithData` threw an exception when handling pasted files with type `com.compuserve.gif` because `fileData` in this case is of type `UIImage` rather than `NSData`. I didn't find a way to convert `UIImage` to `NSData` while conserving the GIF, however, the use of `dataForPasteboardType` worked fine in v1.25.
https://mattermost.atlassian.net/browse/MM-21990
* iPhone 8, iOS 13.3
=> [MM-21990] Handle com.compuserve.gif type with dataForPasteboardType

app/screens/login/login.js, app/screens/select_server/select_server.js
Fixes VoiceOver's inability to focus on text inputs on the `select_server` and `login` screens.
`TouchableWithoutFeedback` is by default, accessible, and it overlayed the whole screen, thus preventing VoiceOver from focusing on any inputs. `accessible={false}` fixes that issue.
Fixes https://mattermost.atlassian.net/browse/MM-17649
iPhone 6s, 13.3
=> MM-17649 - fix VoiceOver on server select & login

app/components/formatted_time.js, app/components/formatted_time.test.js, app/components/post_header/__snapshots__/post_header.test.js.snap, app/components/root/root.js, app/i18n/index.js
ReactIntl formatTime does not play well with android and timezones, with this PR we are using the moment locale formats instead. For some languages moment-locale does not have AM/PM format and we want to ensure we are able to display the time in 12/24 hour format, so when this happens then we fallback to `h:mm A` for the 12 hour format and `H:mm` for 24 hour format.
Also with this PR we have the ability to pick up the language switch from the webapp in real time without having to restart the app as well as limiting the amount of translations loaded to 1 instead of multiple, as we only use one at a time, saving a little bit of memory. 
https://mattermost.atlassian.net/browse/MM-21961
=> MM-21961 Fix Incorrect Timestamp on Android Mobile App

app/components/sidebars/drawer_layout.js
Missing functionality from MM-18530 on iOS you can slide open the main sidebar (channels/teams) from anywhere on the screen. Android remains unchanged.
https://mattermost.atlassian.net/browse/MM-18530
=> MM-18530 iOS Slide open main sidebar from anywhere

app/utils/url.js, app/utils/url.test.js
Default to current server or site URL.
Example case: `<jump to convo>` links generated from autolink plugin have their server/site URL stripped, and it is assumed that generated links are relative to the current server.
Conversation: https://community.mattermost.com/core/pl/78j4a7ozupbci8qxwx1sczc1ua
https://mattermost.atlassian.net/browse/MM-22096
This PR was tested on: iPhone 11 simulator
=> MM-22096 Handle links with no server URL provided

app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/emoji_picker/emoji_picker_base.js, app/utils/emoji_utils.js, app/utils/emoji_utils.test.js
Applies the same emoji sorting in `EmojiPicker` as in `EmojiSuggestion` for consistency and passes the search term to `compareEmojis` so that the results are sorted correctly.
https://mattermost.atlassian.net/browse/MM-22078
https://mattermost.atlassian.net/browse/MM-22083
* iOS 13.3 
`EmojiSuggestion`
`EmojiPicker`
=> [MM-22078] [MM-22083] Sort emojis in EmojiPicker

app/init/global_event_handler.js, app/init/global_event_handler.test.js
Importing from `semver` and not `semver/preload` causes an exception in the [semver.valid(version) call](https://github.com/mattermost/mattermost-mobile/blob/63829c8c7c75dbc2b5f709b5a8fa97868e33f7d7/app/init/global_event_handler.js#L234) causing the `else if` statement that dispatches `loadConfigAndLicense` to be inaccessible.
I added unit tests but they don't test against a failure in the import because it seems `import semver from 'semver'` works fine in the node environment 🤷‍♂ 
https://mattermost.atlassian.net/browse/MM-22159
=> [MM-22159] Import from semver/preload

README.md
Added instructions to open iOS URL from the phone as it will not work on non-iOS devices.
=> iOS - open link from phone

app/components/sidebars/drawer_layout.js
While testing the latest build on iOS is clear how the drawer can be opened by sliding from anywhere in the screen, the open gesture will use the `dx` to keep track of the gesture and position the drawer accordingly, but when closing `dx` will just position the drawer erratically providing a weird behavior.
This PR revert the use of `dx` in favor of `moveX` as it was when the drawer is closing.
https://mattermost.atlassian.net/browse/MM-22165
=> MM-22165 Fix channel sidebar close gesture

app/screens/channel_info/channel_info.js, app/screens/channel_info/channel_info.test.js
Since the ChannelInfo screen is now opened as a modal it must be closed as a modal.
https://mattermost.atlassian.net/browse/MM-22300
* Galaxy S7, Android 8
=> [MM-22300] Use dismissModal to close ChannelInfo screen

app/screens/channel_info/channel_info.js, app/screens/channel_info/channel_info.test.js
Cherry pick of #3890 on release-1.28.
- #3890: Use dismissModal to close ChannelInfo screen
/cc  @migbot
=> Automated cherry pick of #3890

app/screens/image_preview/downloader.ios.js
Typo when checking `error.message` caused `showDownloadFailedAlert` to be called.
https://mattermost.atlassian.net/browse/MM-22301
* Galaxy S7, Android 8
=> [MM-22301] Fix typo in error.message

app/components/post_list/new_messages_divider.js, app/components/post_list/post_list.js, app/screens/channel/channel_post_list/channel_post_list.js
Re-renders were occuring because of prop and state updates that created new object references, despite being of identical value. A key culprit was `postListHeight` in `PostList` which goes through a few calls to `handleContentSizeChange` when loading posts.
Also, "New Messages" divider line is a pure component now (via `memo`) to reduce unnecessary re-renders here too.
[MM-22253](https://mattermost.atlassian.net/browse/MM-22253)
Note: This is not a fix for the ticket, but an improvement that emerged from analysis of the root issue (still a mystery).
* Android 9 device (OnePlus 5)
=> MM-22253 Reduce unnecessary re-renders in channel switching

app/mattermost.js
The problem where all DM/GDM are shown in the left sidebar occurs when certain config keys are missing and this seems to only happen when the default config, usually returned when a server is selected, overrides a previous config. This probably happens as a consequence of not yet having credentials loaded so the config fetch is not authenticated, returning the default config. To avoid this possible (but not easily reproducible) scenario, we call `loadConfigAndLicense` after the app launches and the credentials have loaded.
https://mattermost.atlassian.net/browse/MM-22120
Sven has been testing on his Android device since Sunday and has not yet experienced the issue.
=> [MM-22120] Dispatch loadConfigAndLicense on launchApp

patches/react-native-notifications+2.0.6.patch
Because of [background service limitations](https://developer.android.com/about/versions/oreo/background.html#services) introduced in Android 8.0, functionality that relies on IntentService may not work properly.
While I wasn't able to reproduce, it seems that the IntentService is not playing nice with the background limitations mentioned above. I've opened a [PR on react-native-notifications](https://github.com/wix/react-native-notifications/pull/491) as well.
https://mattermost.atlassian.net/browse/MM-22092
=> Use JobIntentService over IntentService

android/app/build.gradle, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/MattermostTests/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #3935 on release-1.29.
- #3935: Bump app version number to 1.29.0
/cc  @migbot
=> Automated cherry pick of #3935

app/components/file_attachment_list/file_attachment_image.js
Visual treatment of "tall & thin" image attachments (width < 48 pixels) was pushed left-aligned, instead of center-aligned.
Regression introduced by #3807 
Bug reported in community: https://community.mattermost.com/core/pl/yy39ajg1ajfm386dms6tdyjrtw
[MM-22629](https://mattermost.atlassian.net/browse/MM-22629)
This PR was tested on: Android 10 Simulator (Pixel 3)
| Old | New |
| --- | --- |
| <img width="373" alt="Old" src="https://user-images.githubusercontent.com/887849/74672081-451c2d80-518b-11ea-9db1-82b84c58653b.jpg"> | <img width="373" alt="New" src="https://user-images.githubusercontent.com/887849/74672164-73017200-518b-11ea-81e4-7b597c630d7c.png"> |
=> [MM-22629] Center-align tall & thin image attachments

patches/rn-fetch-blob+0.12.0.patch
There's been a recent [fix](https://github.com/joltup/rn-fetch-blob/pull/530) on rn-fetch-blob for an issue that appears to be affecting us: the failed response from a file fetch was not being handled properly.
=> Fix casting crash in RNFetchBlob

package-lock.json, package.json
Updated react-native-cookies ([PR](https://github.com/mattermost/react-native-cookies/pull/1)) to delete the following on `clearAll`:
`Cookies/Cookies.binarycookies`
`WebKit/com.mattermost.rnbeta/WebsiteData/**/*`
https://mattermost.atlassian.net/browse/MM-22492
=> [MM-22492] Update react-native-cookies

app/actions/navigation/index.js, app/actions/navigation/index.test.js, app/screens/notification/notification.js
With the changes to the navigation library, if the overlay screen contains the same id it will cause the data not to be assigned and therefore causing a crash.
With this PR we ensure that the Notification overlay screen does not have the same id as a previous one.
https://mattermost.atlassian.net/browse/MM-22702
=> Fix in-app notification crashing when receiving multiple

app/components/slide_up_panel/slide_up_panel.js
This PR resolves an issue where an Emoji Reaction List of over ~12 or so would stutter/jitter when swiping up at the end of the list (as if trying to scroll further).
There are cases where the ` onHandlerStateChange` function leaves `destSnapPoint` to be undefined. An edge case which has this outcome is when the user swipes up on the Pan component so far, as to release their touch beyond the safe area. The subsequent swipe will then have the jitter. This PR attempts to cover these scenarios.
Ticket: https://mattermost.atlassian.net/browse/MM-13669
Fixes:  https://github.com/mattermost/mattermost-server/issues/13028
This PR was tested on: moto g7 play (Android 9), iPhone 7 (iOS 13.2), iPhone 11 Simulator (iOS 13)
=> MM-13669: Fix stutter on long reaction lists

package-lock.json, package.json
As part of https://mattermost.atlassian.net/browse/MM-14661 we need to update the mattermost-redux version.
https://mattermost.atlassian.net/browse/MM-14661
- [ x] All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)
=> Update mattermost-redux version to latest

app/screens/post_options/index.js, app/screens/post_options/index.test.js
This PR removes the option to "Mark as Unread" after long pressing on posts in Archived Channels. This also removes the "Mark as Unread" option after long pressing on the post in search results. This functionality was removed in the webapp and needed parity on mobile.
Ticket https://mattermost.atlassian.net/browse/MM-22375
Fixes https://github.com/mattermost/mattermost-server/issues/13872
This PR was tested on: iPhone 11 simulator, 13.0
=> MM-22375: Remove mark as unread post option in archived channels

app/components/post_textbox/post_textbox_base.js, app/screens/edit_post/edit_post.js, app/utils/markdown.js, app/utils/markdown.test.js
This PR adds a fix to prevent iOS from converting double dash (--) / triple dash (---) to an emdash (–) while typing a Code Block (w/ triple backtick ``` markdown). 
The iOS smart dash behavior occurs based on the keyboard type ( ‘default’). The proposed solution here is to change keyboardType to ‘email-address’ when cursorPosition is within the bounds of a Code Block and back to ‘default’ when otherwise.
The TextInput’s onSelectionChange handles cursor movements without key strokes. The TextInput’s onChangeText handles cursor movements upon new keystrokes once the TextInput’s (state) value has finished updating.
Ticket https://mattermost.atlassian.net/browse/MM-12148
Fixes https://github.com/mattermost/mattermost-server/issues/9432
This PR was tested on: iPhone 7 simulator, 13.0;  iPhone …
```
=> MM-12148: Prevent emdash convert in a Code Block on ios

app/screens/image_preview/downloader.android.js, assets/base/i18n/en.json
This PR removes the `upload successful` for a file downloaded on android phone.
https://mattermost.atlassian.net/browse/MM-22687
This PR was tested on:   Oneplus 5T
=> [MM-22687] Update Android downloader

app/components/emoji/emoji.js, app/components/file_attachment_list/file_attachment_document/file_attachment_document.js, app/components/file_attachment_list/file_attachment_image.js, app/components/file_attachment_list/file_attachment_list.js, app/components/markdown/markdown_image/markdown_image.js, app/components/message_attachments/attachment_image/index.js, app/components/message_attachments/attachment_image/index.test.js, app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap, app/components/post_attachment_opengraph/post_attachment_opengraph.js, app/components/post_body_additional_content/post_body_additional_content.js, app/components/profile_picture/profile_picture.js, app/components/progressive_image/__snapshots__/progressive_image.test.js.snap, app/components/progressive_image/progressive_image.js, app/components/progressive_image/progressive_image.test.js, app/components/team_icon/team_icon.js, app/init/global_event_handler.js, app/utils/file.js, package-lock.json
When using `ImageCacheManager` we download the image and then set a hash which can be a bit expensive, also the fact that it needs to use the bridge to set/get the file path. When multiple images are present (eg. user profile image, emojis, image attachments, md images, opengraph, etc..) in the same channel this can lock the UI until all images are loaded.
This PR replaces almost every `ImageCacheManager` call in favor of using the cache mechanism of `FastImage` that happens natively and boost perf. Also as part of this PR there is a change in the way we calculate the cache size and how we clean the cache folder.
Finally the emojis were using `Image` instead of `FastImage` which caused a major perf degradation when multiple custom emojis were being rendered in a channel but specially in …
=> MM-22379 & MM-22598 Boost perf by using FastImage cache in favor of ImageCacheManager

android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java, ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Passing `set_online=false` in the post request sent when replying from a push notification so that the user's status is not set to online. ~~I've confirmed that a v5.20 server parses the query param and does not call `c.App.SetStatusOnline`, however, the user's status is still set to online. This might be the server not working properly...I'm still investigating and will add a QA reviewer once I can confirm the server fix for it.~~ The status in the database remains `offline` for the user, however, the webapp displays the user as online for some time after receiving the reply. I've created the following ticket for that issue: https://mattermost.atlassian.net/browse/MM-22706
https://mattermost.atlassian.net/browse/MM-21355
=> [MM-21355] Add set_online=false query param

app/actions/views/channel.js, app/actions/views/select_team.js, app/init/fetch.js, app/screens/channel/channel_base.js
This PR adds a global timeout setting of 5s for every request, also included in this PR is a fix to unset the current channel when switching teams as well as handling the case when not online or fetching the channels for the team fail to use the previously loaded channels for the team.
https://mattermost.atlassian.net/browse/MM-22752
https://mattermost.atlassian.net/browse/MM-22686
=> MM-22752/MM-22686 global timeout and team switch

app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap, app/components/markdown/markdown_table/markdown_table.js, app/components/markdown/markdown_table/markdown_table.test.js
* Apply background color to first row in table preview
* Determine maxPreviewColumns on mount
* Fix expand button offset
* Fix moreBelow gradient
https://mattermost.atlassian.net/browse/MM-22152
https://mattermost.atlassian.net/browse/MM-22321
* iPhone simulator
iOS
Android
=> [MM-22152] [MM-22321] Fix Markdown table issues 

app/components/attachment_button/index.js, app/components/attachment_button/index.test.js, app/components/post_textbox/components/camera_button.js, app/components/post_textbox/components/camera_button.test.js, app/components/post_textbox/components/image_upload_button.js, app/components/post_textbox/components/image_upload_button.test.js
This PR fixes the issue of the StatusBar being hidden or not recognized when Photo/Camera post is called in landscape mode and returned to portrait mode. Photo and Camera post both use react-native-image-picker which utilizes native `UIImagePickerController` on iOS. According to [Apple docs](https://developer.apple.com/documentation/uikit/uiimagepickercontroller), `UIImagePickerController` only supports portrait mode which may cause the unexpected behavior. This issue can also be reproduced with the Take Photo/Photo Library picker for a user's profile picture in Landscape mode (uses same library).
The proposed solution calls to re-enable StatusBar in the `ImagePicker` callback. Thereafter, StatusBar is recognized after switching back to Portrait mode (behaves as expected).
Fixes …
=> MM-22134: Fix StatusBar after Photo-Camera post in landscape mode

app/components/network_indicator/network_indicator.js, package-lock.json, package.json
Updates mm-redux to preserve channel memberships from other teams and when offline keep the network indicator visible on team switch
https://mattermost.atlassian.net/browse/MM-22752
=> MM-22752 Preserve other teams channel membership

app/components/file_attachment_list/file_attachment_image.js
Use `Client4.getFileUrl()` over `Client4.getFilePreviewUrl()` for GIFs.
https://mattermost.atlassian.net/browse/MM-21310
=> [MM-21310] Use file URL over preview URL for GIFs

app/actions/views/channel.js, app/components/post_textbox/index.js, app/components/post_textbox/post_textbox.test.js, app/components/post_textbox/post_textbox_base.js
After the removal of the channel loader when switching channels, there was some unwanted/unneeded code tracking if the channel was being loaded to not let people write a message in the wrong channel.
https://mattermost.atlassian.net/browse/MM-22905
=> Fix typing on input box after returning from an archived channel

app/components/sidebars/settings/settings_sidebar_base.js
Fixes a race condition that would case some screens not to have the close icon on the top left.
Affected screens on  both iOS and Android:
* Flagged posts
* Recent Mentions
*  Settings
* User Profile
* Edit Profile
https://mattermost.atlassian.net/browse/MM-22865
=> Ensure modals opened from the Settings Sidebar have a close icon

android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditTextOnPasteListener.java
With the work done in #3971 we were deleting every file and folder under `cache` and when trying to attach a GIF or any other element from the Android Keyboard (including paste of files) there was no attachment and it failed silently.
This PR will create the needed folder if it does not exists to allow the file to be stored.
https://mattermost.atlassian.net/browse/MM-22953
=> MM-22963 Fix Android post GIF from keyboard

app/components/sidebars/settings/settings_sidebar_base.js
Cherry pick of #3994 on release-1.29.
- #3994: Ensure modals opened from the Settings Sidebar have a
/cc  @enahum
=> Automated cherry pick of #3994

patches/react-native-image-picker+2.0.0.patch
Added a null check on `imageConfig` as [`getResizedImage` can return null](https://github.com/react-native-community/react-native-image-picker/blob/v2.0.0/android/src/main/java/com/imagepicker/utils/MediaUtils.java#L104). There's an [open issue](https://github.com/react-native-community/react-native-image-picker/issues/1278) for this on react-native-image-picker.
Cannot reproduce the crash so not adding QA review.
https://mattermost.atlassian.net/browse/MM-22859
=> [MM-22859] Check for null imageConfig

app/utils/file.js, patches/react-native-vector-icons+6.6.0.patch
Vector icons (as in the close icon) on Android are saved in the cache folder. When we logout / clear cache, the cache folder was completely removed.
With this PR we create a custom `vectorIcons` folder inside the cache folder and when cleaning that folder we will keep the `vectorIcons` so any previous cached icon will remain accessible.
The reason why it was not being regenerated unless you closed and re-opened the app is cause `react-native-vector-icons` keeps a list of "cached" files in a SET to avoid the need to hit the Native side.
iOS is unaffected.
https://mattermost.atlassian.net/browse/MM-23014
=> MM-23014 Keep Android cache for vector icons

ios/NotificationService/NotificationService.swift
The forced downcasting of channel name to type String is throwing an error. I'm not sure how this can happen as, from my understanding, the server always returns a non-empty string for the channel name for ID loaded push notifications. I've updated all the force downcasts to conditional ones and only set `bestAttemptContent` values when the downcast succeeds. I tested this by removing the channel ID from the server response and verified that the generic message is not displayed but instead the post message without the channel title.
I'm not adding QA review as I don't have repro steps.
https://mattermost.atlassian.net/browse/MM-22860
ID loaded push notification with message contents but no channel name:
=> [MM-22860] Override bestAttemptContent only when we have values

app/actions/views/channel.js, app/actions/views/channel.test.js, app/actions/views/root.js, app/push_notifications/push_notifications.ios.js, app/screens/channel/channel_base.js, app/screens/channel/index.js, app/store/ephemeral_store.js, app/utils/push_notifications.js
Opening the app from a push notification then led to an app hang showing the channel loader when switching to another team. This was caused by the fact that the `EphemeralStore.appStartedFromPushNotification` was still set as **true** because it wasn't an atomic update.
With the applied changes we should also see an improvement in speed when switching to a channel by opening the app from a push notification
https://mattermost.atlassian.net/browse/MM-23022
=> Fix app hanging when switching to a team after opening push notification

app/screens/settings/notification_settings_auto_responder/notification_settings_auto_responder.js
This PR ensures the textbox doesn't get obstructed by the iPhone's notch in the Automatic Reply settings screen (Landscape view)
Fixes https://github.com/mattermost/mattermost-server/issues/13871
* iPhone 11 (Simulator)
Before:
After:
=> MM-22385 RN: iOS - Automatic Replies custom message SafeAreaView fix

app/components/post_body/__snapshots__/system_message_helpers.test.js.snap, app/components/post_body/system_message_helpers.js, app/components/post_body/system_message_helpers.test.js
With the addition for unarchiving channels there is a system message that is being parsed, if the post props does not contain the username of whom unarchived the channel then the app just renders a blank screen.
This PR handles the case to avoid the fix.
@jasonblais this was a community contribution and I think the problem is at the server level where the username is not set in the post properties if you want to take another look or file a ticket.
https://mattermost.atlassian.net/browse/MM-23039
Notice how the unarchived message does not link the username
=> MM-23039 Fix crash for unarchived system message

app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap, app/screens/channel_info/channel_info_header.js
https://github.com/mattermost/mattermost-mobile/pull/3975 was merged a bit prematurely since I was still doing a UX review with @michaelgamble but I forgot to add a UX review label
- This is a small follow up to disable channel mention highlights in the channel info header section.
https://mattermost.atlassian.net/browse/MM-22622
This PR was tested on: iOS 11
=> [MM-22622] Disable at channel mention highlight in channel header

app/components/sidebars/main/channels_list/filtered_list/index.js, app/reducers/views/channel.js, package-lock.json, package.json
With the performance optimizations done for 1.29 a reducer that listened for `SELECT_CHANNEL` was expecting an `extra` property which is not set when a channel is deleted/archived, this PR handles that.
Also this PR requires https://github.com/mattermost/mattermost-redux/pull/1069 that addresses some WebSocket bugs related to this issue.
https://mattermost.atlassian.net/browse/MM-22934
https://mattermost.atlassian.net/browse/MM-22975
=> MM-22975 Fix archive handle when server does not allow view archive channel

app/components/post_list/__snapshots__/post_list.test.js.snap, app/components/post_list/post_list.js
This PR fixes a race condition that cause the postList to try and scroll to an index of a previous visited channel when switching quickly between them, thus the index did not exist and was out of range and the app crashed.
The fix consist of two things:
1. Cancel all pending requestAnimationFrames and timeouts when the channel is switched
2. Avoid trying to jump to the new line message indicator if there was a scrolling interaction
https://mattermost.atlassian.net/browse/MM-23176
=> MM-23176 Fix crash due to scrollToIndex out of range

app/components/post_body_additional_content/index.js, app/components/post_body_additional_content/post_body_additional_content.js, app/components/post_body_additional_content/post_body_additional_content.test.js
We now get `expandedLink` from state and `actions.getRedirectLocation(link)` is now only called if we don't already have `expandedLink` or if the `link` has changed. 
For QA, just test that links and shortened links continue working as expected.
https://mattermost.atlassian.net/browse/MM-23241
=> [MM-23241] Use expanded link from state

package-lock.json, package.json
Only dispatch actions in handleUserTypingEvent for the current channel. Changes made in [mattermost-redux](https://github.com/mattermost/mattermost-redux/pull/1080)
QA need only check that the display of a user typing still works as expected.
https://mattermost.atlassian.net/browse/MM-23235
=> [MM-23235] Update mattermost-redux to bring in typing event fix

app/components/reactions/__snapshots__/reactions.test.js.snap, app/components/reactions/reactions.js, app/components/reactions/reactions.test.js
- Actually check `canAddReaction` inside of the reactions component when determining if we should show the user the `addReaction` button
https://mattermost.atlassian.net/browse/MM-23271
This PR was tested on: iOS 11
With Permission:
Without Permission
=> [MM-23271] Check canAddReaction permission inside of render reactions

app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
When using the autocomplete for emojis the `codePoint` mapping was wrongly implemented thus some emojis were incorrectly rendered like (man/woman shrug, flags, and a few others), this PR corrects the parsing
https://mattermost.atlassian.net/browse/MM-22318
Fixes: #4039
=> MM-22318 Fix autocomplete selection char code for native emojis

ios/Mattermost/Info.plist
Change 'mattermost' to 'Mattermost' on iOS camera permissions alert text.
[MM-22237](https://mattermost.atlassian.net/browse/MM-22237)
This PR was tested on: iPhone 11 Simulator
=> [MM-22237] Fix text capitalization

app/init/global_event_handler.js
`setDeviceOrientation` and `setDeviceDimensions` used to get called on any navigation change (e.g. modal launches) and triggered multiple needless dispatches.
[MM-23162](https://mattermost.atlassian.net/browse/MM-23162)
This PR was tested on: Android 11 (OnePlus 5)
=> [MM-23162] Remove unnecessary dimension and orientation dispatches

android/app/src/main/java/com/mattermost/share/ShareModule.java
Users are hitting legitimate exceptions when using the Android Share extension.
However, in some cases where the channel ID isn't available from the user's actions that triggered the exception, the Sentry error reporting message payload can't be successfully formed and it bombs.
This commit allows Sentry's payload to be successfully formed, so that we can now see the actual underlying exception (with its associated user data) in Sentry. The single, catch-all `NoSuchKeyException` should now stop, and be replaced by a few new Sentry exception reports to analyze and tackle individually.
* [MM-21582](https://mattermost.atlassian.net/browse/MM-21582)
This PR was tested on: Android 10 (OnePlus 5 device)
=> [MM-21582] Parse payload safely to report Sentry exception with needed information

app/components/network_indicator/index.js, app/screens/error_teams_list/index.js, app/screens/select_team/index.js, app/screens/terms_of_service/index.js
Unify usage to one set of defined dispatch actions in codebase, instead of a mix of (almost) identical actions defined in `mattermost-mobile` and `mattermost-redux` .
As part of investigation done for [MM-23234](https://mattermost.atlassian.net/browse/MM-23234)
=> MM-23234 Prefer mobile-defined state actions

app/components/post_list/__snapshots__/post_list.test.js.snap, app/components/post_list/post_list.js
Enabled virtualization so that loading many posts does not degrade performance.
https://mattermost.atlassian.net/browse/MM-23506
=> [MM-23506] Enable FlatList virtualization

app/components/network_indicator/network_indicator.js, app/screens/channel/channel.android.js, app/screens/channel/channel_nav_bar/channel_nav_bar.js
The backgroundColor was removed from the drawer content's parent View component, however, this backgroundColor is needed to appropriately display the network indicator banner. iOS is not affected.
https://mattermost.atlassian.net/browse/MM-23483
* Android 10 emulator
=> [MM-23483] Add backgroundColor to drawer content parent View

app/actions/navigation/index.js, app/actions/views/channel.js, app/actions/views/post.js, app/components/sidebars/main/main_sidebar_base.js, app/utils/general.js
On a new DM/GM channel there are no posts when the channel is initially created and when posting a new message this was triggering loading more messages so it fills the screen, the problem here is that it was attempting to load previous messages with a `pending_post_id`.
On this PR we are not calling `getPostsBefore` if the fist post in the list is a pending post.
Also a few other regression fixes:
* When opening a DM/GM on Android the sidebar was not closing.
* When creating a new channel on Android the sidebar was not closing.
* When fetching for posts in a channel the first time we were not dispatching the `receivedPostInChannel` action and this caused the block for recent posts not being created.
https://mattermost.atlassian.net/browse/MM-23341
Note: Marked for 1.30 as this is had 4 …
=> MM-23341 Fix message failed banner when posting first message

app/components/network_indicator/network_indicator.js
With this PR #4067 the tap events on the Android Navbar to go to channel info, open the drawers and the search screen were not responding, this is because although not visible the Network Indicator component was capturing the panResponder.
=> Fix Android Navbar tap events

app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap, app/components/markdown/markdown_table/markdown_table.js
React was throwing warnings because `setState` was called in render through `renderPreviewRows`. I also made some changes to ensure that the expand button is not rendered until we have a width to calculate a positive left offset. 
https://mattermost.atlassian.net/browse/MM-23514
=> [MM-23514] Don't use state for rowsSliced/colsSliced

app/initial_state.js, app/reducers/views/root.js, app/store/index.js, app/store/middleware.js, app/store/middleware.test.js, app/store/store.js
_This PR merges into branch `MM-23490/state-cache-middleware`._
Exposes persistence configuration as a static reference, so that cache purging can be invoked on demand anywhere else in the codebase.
While middleware still may not be the best spot for this singular "action" (purge cache), existing functionality reacting to `OFFLINE_STORE_PURGE` is maintained.
Aso removes the need for `state.views.root.purge` to exist in the state tree.
* [MM-23493](https://mattermost.atlassian.net/browse/MM-23493)
Same as existing functionality. Cache size goes to 0 bytes.
**Before**
**After**
---
**Notes**
* [middleware.js](https://github.com/mattermost/mattermost-mobile/blob/MM-23493/cache-purge-action/app/store/middleware.js) …
=> MM-23493 Move app cache purge from store subscription to middleware

app/components/file_attachment_list/file_attachment_image.js
Cherry pick of #4084 on release-1.30.
- #4084: Revert "Use file URL over preview URL for GIFs (#3981)"
/cc  @enahum
=> Automated cherry pick of #4084

app/actions/views/post.js
With the batching of actions we adding to the `receivedPostsInChannel` before `receivedPosts` and this caused the reducers to fail as `receivedPostsInChannel` actually depends on the `receivedPosts` reducer to be executed first.
Batching actions are performed in sequence following the order they were added to the batch
https://mattermost.atlassian.net/browse/MM-23669
Note: This is the PR for the `release-1.30` branch
=> Fix post in channel batching order (release-1.30)

app/actions/views/post.js, app/store/utils.js, app/store/utils.test.js
With the batching of actions we adding to the `receivedPostsInChannel` before `receivedPosts` and this caused the reducers to fail as `receivedPostsInChannel` actually depends on the `receivedPosts` reducer to be executed first.
Batching actions are performed in sequence following the order they were added to the batch
This PR also preserves all the preferences when resetting the cache so there are no missing profiles to load in the sidebar. (The profiles for GM's won't load until this PR #4087 gets merged)
https://mattermost.atlassian.net/browse/MM-23669
Note: This is the PR for the `master` branch
=> Fix post in channel batching order

android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java, app/components/post_textbox/post_textbox_base.js
There have been reports of messages being submitted on Android when pressing enter on a virtual keyboard. We now check if and when a HW keyboard is connected and only send the press event when connected.
https://mattermost.atlassian.net/browse/MM-23708
* Mi A3, Android 9 with BT keyboard
* iPhone 7, iOS 13 with BT keyboard
=> [MM-23708] Send HW key pressed event only when a HW keyboard is connected

app/initial_state.js, app/reducers/views/root.js, app/store/middleware.js, app/store/middleware.test.js, app/store/store.js
Currently for iOS, a subset of store state is saved to an on-device file, so that the Share Extension can have access to information it needs (teams and channels) to function.
This file saving would happen via a store subscription which triggers a file save for every dispatched action. By moving this logic to a middleware function, when this function gets invoked is now limited to a configurable set of action dispatches. (e.g. `LOGIN`, `CONNECTION_CHANGED`, `WEBSOCKET_SUCCESS`), etc.
* [MM-23490](https://mattermost.atlassian.net/browse/MM-23490)
* [MM-23493](https://mattermost.atlassian.net/browse/MM-23493) (merged via #4069 )
* iPhone 11 (Simulator)
---
* [persistor function in …
=> [MM-23490] Save state to file via async middleware vs store subscription

patches/react-native-navigation+6.3.0.patch
RNN on Android was not resolving the promise if there are no modals to dismiss, this PR adds a patch to resolve the promise as we do on iOS
https://mattermost.atlassian.net/browse/MM-23714
=> Patch react-native-navigation to resolve promise when no modals to dismiss

patches/react-native-navigation+6.3.0.patch
Cherry pick of #4103 on release-1.30.
- #4103: Patch react-native-navigation to resolve promise when no
/cc  @enahum
=> Automated cherry pick of #4103

app/actions/views/post.js, app/actions/views/post.test.js
A typo in https://github.com/mattermost/mattermost-mobile/pull/4078 prevented `RECEIVED_PROFILES_LIST` and `RECEIVED_STATUSES` actions from being dispatched when loading unread channel posts.
https://mattermost.atlassian.net/browse/MM-23780
=> [MM-23780] Correctly add additional actions when loading unread channel posts

app/mm-redux/actions/posts.test.js, app/mm-redux/actions/posts.ts, app/screens/edit_post/__snapshots__/edit_post.test.js.snap, app/screens/edit_post/edit_post.js, app/screens/edit_post/edit_post.test.js, app/screens/edit_post/index.js
Added a call to `Keyboard.dismiss()` before closing the EditPost screen. This ensured the keyboard closed when pressing cancel. For the keyboard to remain closed after a successful save I removed `autofocus={true}`. Also, instead of relying on the edit post request status we now await the edit post action and use its return value.
* Note: I had accidentally commented out some mm-redux post tests in the port commit. I uncommented them here.
https://mattermost.atlassian.net/browse/MM-23609
=> Dismiss keyboard on edit post close

app/components/markdown/markdown_table/markdown_table.js
Removed condition that `moreBelow` or `moreRight` not be null in order to show the expand button.
https://mattermost.atlassian.net/browse/MM-23874
=> [MM-23874] Always show expand button

ios/MattermostShare/ShareViewController.swift
`isContentValid` is called before `viewDidLoad` so `maxMessageSize`, which is initalized to 0, is not yet set from the store value. This is fixed by getting the store data in the view controller's `init` function.
https://mattermost.atlassian.net/browse/MM-22386
=> [MM-22386] Get store data on init

app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
Replace SlashSuggestionItem's `height` with `paddingVertical`.
https://mattermost.atlassian.net/browse/MM-22632
| Before  | After|
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/3208014/78701730-5b598680-78bc-11ea-9164-0d28f27f6cad.PNG)  | ![IMG_0381](https://user-images.githubusercontent.com/3208014/78711359-b2b32300-78cb-11ea-86c9-092ab1c103f9.PNG)  |
=> [MM-22632] Set vertical padding for SlashSuggestionItemi

app/components/post/index.js
On comments that belong to the same thread had a commented on post header if a date separator existed between the two, this PR removes the `commented on` header for this use case.
https://mattermost.atlassian.net/browse/MM-22198
=> MM-22198 Don't show commented on for post on the same thread after a date separator

app/components/post/post.js, app/components/post_header/index.js, app/mm-redux/utils/post_utils.ts
When a user commented on a post by an integration the `Commented on` header was showing the creator's name instead of the `override_username` prop for that integration, this PR fixes that.
https://mattermost.atlassian.net/browse/MM-22683
=> MM-22683 use override_username on commented on post header

app/push_notifications/push_notifications.ios.js, app/push_notifications/push_notifications.ios.test.js
The badge count is set to the number of delivered notifications first. If the redux store is set, then the badge count is overridden with the value from state so there is no need to subtract the delivered count.
https://mattermost.atlassian.net/browse/MM-23893
=> [MM-23893] No need to subtract delivered notifications from badge count

app/mm-redux/utils/post_list.test.js, app/mm-redux/utils/post_list.ts
The `isDateLine` was not taking into account that the item could be `null` or `undefined` causing this issues https://github.com/mattermost/mattermost-mobile/pull/4093#pullrequestreview-391542323 found by @josephbaylon who thought they are related to the other PR where in fact this issue was introduced by #4129 and missed during QA Review.
=> Fix isDateLine function to check for null and undefined

app/components/post_body/__snapshots__/system_message_helpers.test.js.snap, app/components/post_body/index.js, app/components/post_body/system_message_helpers.js, app/components/post_body/system_message_helpers.test.js
On old system messages the post props did not have the username set, and when trying to render the post the app crashed.
The fix has two parts:
1. If the post is a system message and it does not have the username who originated the action set then we add the username from the post user_id
2. Handle the case when there is no username in the renderer of System Messages.
https://mattermost.atlassian.net/browse/MM-24093
=> MM-24093 Fix crash when system message does not contain a username in post props

app/actions/navigation/index.js, app/actions/navigation/index.test.js
`topBar.backButton.color` is needed in the root screen so that it applies that color in transitions back to the screen.
https://mattermost.atlassian.net/browse/MM-24026
=> [MM-24026] Set back button color

app/components/post_body/index.js, app/components/post_body/post_body.js
Changes made in https://github.com/mattermost/mattermost-mobile/commit/6667962e1f7946549ad383f6c3d0e989f7d8121f introduced the possibility of `postProps` being undefined. We now default `postProps` to and empty object to avoid crashes when accessing `postProps` properties.
=> Ensure postProps is not null/undefined

ios/MattermostShare/ShareViewController.swift
Cherry pick of #4127 on release-1.31.
- #4127: Get store data on init
/cc  @migbot
=> Automated cherry pick of #4127

app/components/post_body/__snapshots__/system_message_helpers.test.js.snap, app/components/post_body/system_message_helpers.js, app/components/post_body/system_message_helpers.test.js
Cherry pick of #4131 on release-1.31.
- #4131: MM-22043 Render Channel purpose message without markdown
/cc  @enahum
=> Automated cherry pick of #4131

app/mm-redux/client/client4.ts
See contribution that fixes this in the Redux repo: https://github.com/mattermost/mattermost-redux/pull/1116
I have confirmed with product and bizops that this will not break existing analytics we have done, as we are able to fix backwards compatibility manually with low effort.
No impact to users or admins as it's only used for diagnostics collection.
=> Fix typo in telemetry entry

app/components/post_textbox/index.js, app/components/post_textbox/index.test.js, app/screens/post_options/index.js, app/screens/post_options/index.test.js
Default `canPost` to true and apply permission check only for v5.22+ server versions.
https://mattermost.atlassian.net/browse/MM-24427
=> [MM-24427] Check canPost permissions for v5.22+

app/components/file_attachment_list/file_attachment_list.js
Right now if all the attachments of a post are removed the component update code enters into an infinite loop because the comparison between arrays always returns false.
https://mattermost.atlassian.net/browse/MM-23907
Nvidia Shield, Android 7
=> Fix infinite loop retrieving post files

app/mattermost_managed/mattermost-managed.android.js, app/screens/select_server/select_server.js, ios/Podfile.lock, patches/react-native-local-auth+1.6.0.patch
This PR affects 1.30 and another PR exists for master/1.31
The react-native-local-auth library was not being linked for iOS and then when this functionality was requested the app crashed.
Also fixes Passcode authentication on Android that was not being triggered and finally fixes the header being present and allowing going back to the select server screen when EMM disallowed using other servers.
https://mattermost.atlassian.net/browse/MM-24446
=> MM-24446 Fix Crash on iOS with EMM enabled (1.30)

app/init/global_event_handler.js, app/reducers/app/previousVersion.js, app/store/utils.js, app/store/utils.test.js
Because `previousVersion` was not set until state was persited and because persisting is not triggered when placing the app in the background using backspace, when `launchApp` ran on returning the app to the foreground the version validation was provided a null `previousVersion` causing a logout. Likewise when clearing data, `previousVersion` was unset so the former scenario would occur on backspace. We now ensure `previousVersion` is set on logout if it was previously not set and is kept when clearing data.
Note: These changes will be applied to https://github.com/mattermost/mattermost-mobile/pull/4197 for master/1.31.
https://mattermost.atlassian.net/browse/MM-24451
=> [MM-24451] Handle setting previousVersion on logout and clearing data

app/mattermost_managed/mattermost-managed.android.js, app/screens/select_server/select_server.js, ios/Podfile.lock, patches/react-native-local-auth+1.6.0.patch
This PR affects master and 1.31 and another PR will be submitted against 1.30
The react-native-local-auth library was not being linked for iOS and then when this functionality was requested the app crashed.
Also fixes Passcode authentication on Android that was not being triggered and finally fixes the header being present and allowing going back to the select server screen when EMM disallowed using other servers.
https://mattermost.atlassian.net/browse/MM-24446
=> MM-24446 Fix Crash on iOS with EMM enabled

app/store/middleware.js
(**This is the PR for 1.30. Separate PR to follow for `master` and 1.31**)
Only posts in channels, searched posts and flag posts are recalculated (as per data retention policy, if applicable). The rest of state is cloned from existing state.
On a version upgrade, data cleanup gets run anyway.
* [MM-24463](https://mattermost.atlassian.net/browse/MM-24463)
This PR was tested on: OnePlus 5 (Android 10 device)
=> [MM-24463] Run message retention cleanup off of pre-existing state instead of a reconstructed "zero" state (1.30)

app/init/global_event_handler.js, app/store/utils.js, app/store/utils.test.js
Set the previous version of the app to the current one once the user is logged out or when deleting documents & data.
https://mattermost.atlassian.net/browse/MM-24451
=> MM-24451 Set prev app version to current on logout/reset cache

app/screens/search/search.js
This PR fixes a bug where the searchbar rendered incorrectly on iPhone X on landscape mode.
Note: This PR should not change anything on the Android side of things
https://mattermost.atlassian.net/browse/MM-24498
* iPhone X (simulator)
* Google Pixel 3XL (simulator)
Before:
After:
=> MM-24498 Fixing padding of SearchBar in Search screen

app/screens/channel/channel_base.js, app/utils/tap.js, app/utils/tap.test.js
Cherry pick of #4133 on release-1.31.
- #4133: MM-22089 set default prevent double tap to 1s
/cc  @enahum
=> Automated cherry pick of #4133

app/screens/index.js
Swipe to dismiss works fine in iOS but on Android it requires the Notification screen to be [wrapped in gestureHandlerRootHOC](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation).
https://mattermost.atlassian.net/browse/MM-23053
=> Wrap screen in gestureHandlerRootHOC

app/store/middlewares/helpers.js, app/store/middlewares/message_retention.js, ios/Podfile.lock
**Note: Similar functionality went into 1.30 release via #4211** 
Only posts in channels, searched posts and flag posts are recalculated (as per data retention policy, if applicable). The rest of state is cloned from existing state.
On a version upgrade, data cleanup gets run anyway.
* [MM-24463](https://mattermost.atlassian.net/browse/MM-24463)
This PR was tested on: OnePlus 5 (Android 10 device)
=> [MM-24463] Run message retention cleanup off of pre-existing state

fastlane/Fastfile, ios/Podfile.lock
`group.com.mattermost.rnbeta` needs to be replaced with the provided `app_group_id` in MMKVStorage.m
This change does take effect with test builds so QA will need to test on a release build.
https://mattermost.atlassian.net/browse/MM-24583
=> [MM-24583] Add find_replace_string for MMKVStorage

app/components/sidebars/main/channels_list/channels_list.js
This PR ensures that the search bar in the channels list renders properly in landscape mode  on Iphone X
https://mattermost.atlassian.net/browse/MM-24444
* iPhone 11
* iPhone X
Before:
After:
=> Fixing improper padding of searchBar container

app/actions/views/channel.js
This feature may be causing problems in 1.31. Once cherry-picked into 1.31 we'll push another beta build.
We need to take a closer look at the following before we enable again:
* Server rate-limiting
* Should we queue requests?
* If queued, how do we handle a user switching to an unread channel prior to the queued pre-fetch request being called?
* Should we set a minimum delta since last websocket connection before pre-fetching?
=> Disable loadUnreadChannelPosts

app/actions/views/channel.js
This reverts commit 8de77754ef398488db22d31e6027bea058f4ea6f.
Reverting due to banner issue being caused by a missed [cherry-pick](https://github.com/mattermost/mattermost-mobile/pull/4090) to 1.31.
=> Revert "Disable loadUnreadChannelPosts (#4245)"

app/store/middlewares/helpers.js, app/store/middlewares/middleware.test.js
Cleanup was setting `views.root.hydrationComplete` to false and it remained so on returning the app to the foreground because `persist/REHYDRATE` is only fired on app launch from an exited state. When a push notification returned the app to the foreground it waited for rehydration which never happened.
https://mattermost.atlassian.net/browse/MM-24639
Mi A3, Android 9
=> [MM-24639] Set rehydrated values to true on store cleanup.

app/screens/channel/channel_nav_bar/channel_nav_bar.js, app/screens/channel/channel_nav_bar/channel_nav_bar.test.js
Hamburger menu to show on Android when:
* "persistent sidebar" setting is not on (or)
* device is not using split view for multiple apps
Hamburger icon to not show on iPads, just as before.
* [MM-24061](https://mattermost.atlassian.net/browse/MM-24061)
* Android 9 tablet emulator (Nexus 3)
* Android 10 device (OnePlus 5)
* iPad Pro Simulator
**Before**
**After**
=> [MM-24061] Bring back channel sidebar hamburger icon for tablets

app/screens/image_preview/__snapshots__/image_preview.test.js.snap, app/screens/image_preview/image_preview.js, app/screens/image_preview/image_preview.test.js
Since local images are not cached FastImage could not find the image. 
https://mattermost.atlassian.net/browse/MM-24706
* iPhone simulator
=> [MM-24706] Use cache only for http URIs

app/components/autocomplete/slash_suggestion/index.js, app/screens/channel/channel.android.js
Fixes crash on Android when attempting to redirect back to a read-only channel (default channel) after using the `/leave` command.
Also, enables official support of `leave` slash command. Added as auto-complete suggestion.
* [MM-24113](https://mattermost.atlassian.net/browse/MM-24113)
* Android 10 device (OnePlus 5)
=> [MM-24113] Support 'leave' slash command

app/components/autocomplete/slash_suggestion/index.js, app/screens/channel/channel.android.js
This reverts commit fd450f998824f366ad63017d09d176467ddc8132.
Per [conversation](https://github.com/mattermost/mattermost-mobile/pull/4273#issuecomment-625379784), the `/leave` command cannot be supported at this time because of the various cases that need to be explicitly considered on the client-side based on the server action/response.
* [MM-24113](https://mattermost.atlassian.net/browse/MM-24113)
=> Revert "MM-24113 Support 'leave' slash command (#4273)"

app/components/autocomplete/slash_suggestion/index.js, app/screens/channel/channel.android.js
Cherry pick of #4279 on release-1.31.
- #4279: Revert "MM-24113 Support 'leave' slash command (#4273)"
/cc  @chuttam
=> Automated cherry pick of #4279

app/actions/views/post.js, app/actions/views/post.test.js
`RECEIVED_POSTS` and `RECEIVED_POSTS_IN_CHANNEL` rely on [nextPosts](https://github.com/mattermost/mattermost-mobile/blob/62fd36127659d89f4af12d1fe174de187457ae6b/app/mm-redux/reducers/entities/posts.ts#L1174-L1175) being computed by `RECEIVED_POSTS` so we need to ensure that `receivedPosts` is dispatched first.
https://mattermost.atlassian.net/browse/MM-24793
=> Ensure receivedPosts runs first

app/components/autocomplete/at_mention/index.js, app/components/post_draft/index.js, app/components/post_draft/index.test.js, app/components/reactions/index.js, app/mm-redux/selectors/entities/roles.test.js, app/mm-redux/selectors/entities/roles.ts, app/mm-redux/selectors/entities/roles_helpers.ts, app/screens/post_options/index.js, app/screens/post_options/index.test.js
- Currently if the roles for a channel or team are not loaded into the state then any permission check that requires those roles returns false, so setting any kind of default beforehand is pointless since it just gets overridden to be false by the permission check
- This PR adds an optional attribute to the `PermissionsOptions` parameter passed in to all permission checks to specify a default in the case where the roles for the specified resource (team or channel) do not exist.
- Not sure what the best way to test this is but, I just modified the code to think there were no roles in the state and then ensured that the default values are honoured.
- https://mattermost.atlassian.net/browse/MM-24891
- https://mattermost.atlassian.net/browse/MM-24572
~Has UI changes~
~Includes text changes …
=> [MM-24891] [MM-24572] Add ability to specify default value when role not found for selector

app/components/autocomplete/at_mention/index.js, app/components/post_textbox/index.js, app/components/post_textbox/index.test.js, app/components/reactions/index.js, app/mm-redux/selectors/entities/roles.test.js, app/mm-redux/selectors/entities/roles.ts, app/mm-redux/selectors/entities/roles_helpers.ts, app/screens/post_options/index.js, app/screens/post_options/index.test.js
* MM-24891 Allow permissions to have defaults set in case where roles not in state
* MM-24891 Add tests for haveIPermission
* MM-24891 Apply the defaults to more channel permission checks
- Original PR https://github.com/mattermost/mattermost-mobile/pull/4277/
=> cherry-pick #4277 - [MM-24891] Add ability to specify default value when role not found for selector

app/screens/select_server/select_server.js, assets/base/i18n/en.json, patches/rn-fetch-blob+0.12.0.patch
Some server installations use internally-trusted SSL certificates that fail standard SSL handshakes, and therefore prevent the Mattermost mobile client from connecting. However, users receive a generic "unable to connect" message which is misleading.
This PR presents a new alert specific to SSL connection/certificate trust issues when attempting to connect to the server.
* [MM-18642](https://mattermost.atlassian.net/browse/MM-18642)
| iPhone | Android |
| --- | --- |
| <img width="300" alt="SSL trust alert" src="https://user-images.githubusercontent.com/887849/81373947-54e54700-90d4-11ea-98ce-68a334283c43.png"> |  <img width="300" alt="SSL trust alert" src="https://user-images.githubusercontent.com/887849/81373940-50 …
=> [MM-18642] Notify on server certificate trust problems when connecting

app/components/post_draft/index.js, app/components/post_draft/index.test.js
When removed from the channel you are viewing, `currentChannel` can be null when the PostDraft component re-renders and the permission checks can throw an error when attempting to access `currentChannel` properties.
https://mattermost.atlassian.net/browse/MM-25002
=> [MM-25002] Ensure currentChannel set

app/components/post_textbox/index.js, app/components/post_textbox/index.test.js
Cherry pick of #4288 on release-1.31.
- #4288: Ensure currentChannel set
/cc  @migbot
=> Automated cherry pick of #4288

app/store/index.ts
Intro:
in 1.31 we upgraded the persistent store to use MMKV instead of AsyncStorage for performance reasons. 
What was happening:
- When the app is installed for the first time, there is no  previous version set for obvious reasons although the current version is set.
- When the upgrade happens, we run a store migration and in here the previous version was obviously empty as it is taken from the previous persisted store and this logs you out based on the condition that we have.
What is the fix:
Set the previous version of the app to the app version set in the persisted store during the migration, this will ensure that the right previous version is being set. **The migration only occurs once**
What is expected:
* Upgrading from 1.30.x to 1.31 should not be logged out no matter how many …
=> Set previous app version on persist store migration

patches/rn-fetch-blob+0.12.0.patch
Without the explicitly thrown exception, the TLS handshake never exits cleanly as it should.
Context: [see conversation](https://community.mattermost.com/private-core/pl/36cp76j5g3r7z8hre1pr8hfhmy)
* [MM-18642](https://mattermost.atlassian.net/browse/MM-18642)
This PR was tested on: Android 10 emulator
=> [MM-18642] Ensure SSL exception is thrown for bad servers

patches/rn-fetch-blob+0.12.0.patch
For Android, changes in #4282 took care of servers running invalid SSL/TLS configuration for server certificate trust chains. This PR adds additional, missing hostname verification.
* [MM-25240](https://mattermost.atlassian.net/browse/MM-25240)
* Android 10 (OnePlus 5 device & Nexus 3 emulator)
=> [MM-25240] Add host verification check for SSL servers

android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java, ios/NotificationService/NotificationService.swift
When an attempt to retrieve push notification message payload from server fails, initiate subsequent retry attempts using the following request backoff schedule (Fibonacci).
0 seconds to attempt 1 (original try)
1 seconds to attempt 2
2 seconds to attempt 3
3 seconds to attempt 4
5 seconds to attempt 5
8 seconds to attempt 6
6 attempts in ~20 seconds, not including response latency for each failure.
* [MM-22181](https://mattermost.atlassian.net/browse/MM-22181)
=> MM-22181 Backoff retries for ID-loaded push notification messages

app/components/file_attachment_list/file_attachment_image.js, app/components/markdown/markdown_image/markdown_image.js, app/components/message_attachments/attachment_author.js, app/components/message_attachments/attachment_footer.js, app/components/post_attachment_opengraph/post_attachment_opengraph.js, app/components/profile_picture/profile_picture.js, app/components/progressive_image/progressive_image.test.js, app/components/team_icon/team_icon.js, test/setup.js
When FastImage or Glide failed to create the source for the image to preload it crashes the app as there is no error handler baked in any of those libraries.
The fact remains that there is no much benefit in preloading the images while the image component is being mounted as chances are that the request has not yet finished and the image cached before the FastImage component attempts to get the image, so in the end the request is made again.
This PR removes the preloading of images.
Smoke test around images should be perform and there should not be any changes in the way it behaves.
https://mattermost.atlassian.net/browse/MM-25347
Fixes: https://github.com/mattermost/mattermost-mobile/issues/4310
=> Do not preload images with FastImage

patches/react-native-navigation+6.4.0.patch
The navigation library attempts to cast the current activity to class NavigationActivity but fails when the current activity is the ShareActivity. This change catches the exception so the app doesn't crash. A separate [ticket](https://mattermost.atlassian.net/browse/MM-25416) was opened to fix push notifications not displayed while the share extension is open.
Note for QA: this only needs to be tested for Android.
https://mattermost.atlassian.net/browse/MM-25344
=> [MM-25344] Catch ClassCastException

app/components/video_controls.js
Defining just `height` and `aspectRatio` fixes the cut-off issues with the play and replay icons.
https://mattermost.atlassian.net/browse/MM-24899
* iPhone SE
=> [MM-24899] Update control icon style

app/components/sidebars/main/channels_list/channels_list.js
The overflow hidden added to prevent the `Cancel` button to be displayed in the search bar on iOS while in landscape cause this little regression
https://mattermost.atlassian.net/browse/MM-25434
=> MM-25434 Fix switch team badge cut off

app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap, app/components/sidebars/main/channels_list/channel_item/channel_item.js, app/components/sidebars/main/channels_list/channel_item/channel_item.test.js, app/components/sidebars/main/channels_list/channel_item/index.js
Added a check to determine if the channel was manually set as unread so it can stay bolded in the LHS regardless of if it's active or not.
https://mattermost.atlassian.net/browse/MM-24932
=> MM-24932 Bold LHS active channel manually marked as unread

app/mm-redux/actions/teams.test.js, app/mm-redux/actions/teams.ts, app/mm-redux/reducers/entities/users.ts, app/screens/select_team/index.js, app/screens/select_team/select_team.js, app/screens/select_team/select_team.test.js
When the user joined a new team the team member was not being added to the store and in case it was the first team the user joined the roles were not yet loaded.
**Note**: This PR removes backwards compatibility to join teams on servers below 5.19
https://mattermost.atlassian.net/browse/MM-24895
=> MM-24895 fetch roles if needed and add team member to the store when joining a team

app/actions/helpers/channels.test.js, app/actions/helpers/channels.ts
While the actions to save channel visibility preferences were dispatched when a DM/GM was received, the preferences were not saved in the server as there were no Client4 calls made.
https://mattermost.atlassian.net/browse/MM-25146
=> [MM-25146] Add calls to Client4.savePreferences

app/actions/helpers/channels.test.js, app/actions/helpers/channels.ts
Cherry pick of #4341 on release-1.32.
- #4341: Add calls to Client4.savePreferences
/cc  @migbot
=> Automated cherry pick of #4341

app/components/post/post.js
The post menu is showing by long pressing a post. The long press seemed to be very short and felt too sensitive, by increasing it to 200ms it feels much better UX.
https://mattermost.atlassian.net/browse/MM-25510
=> MM-25510 Increase post options long press delay to 200ms

app/components/post_draft/uploads/upload_item/upload_item.js
There have been reports the when the antivirus plugin is enabled the files upload are failing due to timing out, this PR is bumping the timeout to help determine if that is the actual cause.
Based on this convo: https://community.mattermost.com/private-core/pl/onw9nyodzid13e8gf3oxe63tde this PR solves the issue.
https://mattermost.atlassian.net/browse/MM-25561
=> Bump upload timeout to 1 min

app/components/slide_up_panel/slide_up_panel.js, app/screens/reaction_list/index.js, app/utils/error_handling.js
Applies to both iOS and Android. Fixes the Relaunch Alert and the crash when swiping the reaction list from the top to half way.
Note: Also dismissing all the modals when tapping on the Alert `Relaunch` option. <- no need to test this
https://mattermost.atlassian.net/browse/MM-25562
=> MM-25562 Fix dismiss reaction list crash

app/init/global_event_handler.js, app/mm-redux/actions/teams.ts
When the app restarts after a state reset, the subsequent `loadMe` only fetches a user's already-joined teams, which doesn't populate `state.entities.teams.teams` with the entire set of teams available, including potentially joinable teams.
[MM-24501](https://mattermost.atlassian.net/browse/MM-24501)
Fixes https://github.com/mattermost/mattermost-mobile/issues/4209
* iPhone 11 Simulator 
* Android 10 emulator (Nexus 3)
=> [MM-24501] Load all (including joinable) teams when resetting app state

app/screens/select_team/index.js
Listing of available teams to join was not sorted alphabetically, but was based on team creation date/time.
Now the list is alphabetized, and matches webapp behaviour.
* [MM-24201](https://mattermost.atlassian.net/browse/MM-24201)
This PR was tested on: iPhone 11 Simulator
**Before**
**After**
=> [MM-24201] List joinable teams alphabetically

app/components/safe_area_view/__snapshots__/safe_area_view.ios.test.js.snap, app/components/safe_area_view/safe_area_view.ios.js, app/screens/long_post/__snapshots__/long_post.test.js.snap, app/screens/long_post/long_post.js, app/screens/permalink/__snapshots__/permalink.test.js.snap, app/screens/permalink/permalink.js, app/screens/search/search.js
Rather than return a null top bar component when the status bar changes, we now animated the top bar's height/padding.
https://mattermost.atlassian.net/browse/MM-24068
=> [MM-24068] Animate top bar height/padding

app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap, app/screens/edit_profile/edit_profile.js, app/screens/edit_profile/edit_profile.test.js, app/screens/edit_profile/index.js
Do not allow the user to update their profile picture if the account is using LDAP or SAML to login and the profile picture attribute is set
https://mattermost.atlassian.net/browse/MM-25694
=> MM-25694 Disallow profile picture update is set by LDAP

app/actions/helpers/channels.ts, app/actions/views/channel.js, app/actions/views/select_team.js, app/mm-redux/types/store.ts
Currently when switching teams, the selected channel is empty, which shows the channel loader until the team channels are fetched from the server and the initial channel gets selected. This PR helps to select the channel  in advance when switching teams if we already have them.
https://mattermost.atlassian.net/browse/MM-25695
=> MM-25695 Select channel when switching teams if available

android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
Changes in #4302 piggy-backed on the existing [exception catching logic](https://github.com/mattermost/mattermost-mobile/pull/4302/files#diff-266cddcf80a6bc300b40cc922e7a659bL101-L102) to retry failed request (status != 200). However, the change applied retries for any type of push notification.
Android only.
* [MM-25849](https://mattermost.atlassian.net/browse/MM-25849)
This PR was tested on: Android 10 device (OnePlus 5)
=> MM-25849 Android: Apply backoff & retry logic only for ID-loaded push notifications

android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
Cherry pick of #4391 on release-1.32.
- #4391: MM-25849 Apply backoff & retry logic only for ID-loaded push
/cc  @chuttam
=> Automated cherry pick of #4391

app/screens/select_server/select_server.js
With `getUrl` recently [becoming async](https://github.com/mattermost/mattermost-mobile/commit/293470ff#diff-60b06b1c4aab028b96d9b207e84000c6R316), the global definition of the cancelPing function wasn't being made available in time for use by other functions (e.g. `handleSslProblem` and `handleConnect`)
[MM-25831](https://mattermost.atlassian.net/browse/MM-25831)
=> [MM-25831] Fix timing issue with cancelPing

NOTICE.txt, app/actions/views/root.js, app/init/global_event_handler.js, app/mm-redux/types/module.d.ts, app/store/index.ts, package-lock.json, package.json, packager/moduleNames.js, packager/modulePaths.js
Make sure previous redux state is cleared when you logout from a server so there is no conflicting data or data that  does not belong when you switch servers.
https://mattermost.atlassian.net/browse/MM-25792
=> MM-25792 Ensure previous state is cleared when logout

app/components/post_draft/post_draft.js
Removed unnecessary trim before creating the post that was preventing displaying as code blocks when the text was preceded with 4 spaces. 
[MM-25809](https://mattermost.atlassian.net/browse/MM-25809)
This PR was tested on: iOS simulator.
Issue originally introduced in: https://github.com/mattermost/mattermost-mobile/pull/4122
=> MM-25809 - Fixed rendering code blocks when starting with 4 spaces

app/mm-redux/reducers/entities/channels.ts
The current reducer implementation for channel members was too slow as it was looping through all the current channel memberships to determine if some of them needed to be removed as the user was no longer a member of that channel.
The change now consist in determine if there are memberships to be removed first by filtering the current memberships with those returned by the server and then loop through them.
The issue being fixed is more noticeable when you have a large amount of channels ad multiple teams.
https://mattermost.atlassian.net/browse/MM-25782
=> MM-25782 improve channel member reducer speed to sync memberships

ios/NotificationService/NotificationService.swift
Bug found in #4302 that delayed delivery/receipt of normal (non id-loaded) iOS push notifications. Response handling was happening within the guard block for id-loaded messages.
* [MM-25929](https://mattermost.atlassian.net/browse/MM-25929)
=> MM-25929 Decouple id-loaded retries from regular notification run

ios/NotificationService/NotificationService.swift
* Removes duplicate calls to content handler
* Removes need to track global instance variable for success/fail state of receipt retrieval
* Aligns with Swift best practices
* Removes need to manually trigger a timer (via `DispatchQueue#asyncAfter`)
Triggered per [this conversation](https://github.com/mattermost/mattermost-mobile/pull/4302#discussion_r426426887)
Raised question https://stackoverflow.com/questions/62293185/recursive-function-with-delay-in-between-calls?noredirect=1#comment110172449_62293185 which resolved the recursion.
* [MM-25955](https://mattermost.atlassian.net/browse/MM-25955)
This PR was tested on: iPhone 11 device
* Do not attempt retries if server response is a `401 Unauthenticated`
I preferred to no intermix this logic addition with the refactoring for the sake of …
=> [MM-25955] iOS: Refactor backoff/retry logic for failed id-loaded notifications

app/screens/select_team/index.js
When the user logins and do not belong to any team the select team screen  shows, if the user decides to logout from this screen there was an unhandled error as the `currentUser` is no longer set.
https://mattermost.atlassian.net/browse/MM-26185
=> MM-26185 Fix unhandled error when logging out from the select team screen

app/components/root/root.js
| **Old** | **New** |
| --- | --- |
| <img width="373" alt="Old" src="https://user-images.githubusercontent.com/887849/84390292-b6b23880-abcd-11ea-8eb5-3b76032d7f62.png"> | <img width="373" alt="New" src="https://user-images.githubusercontent.com/887849/84390163-93878900-abcd-11ea-842e-43e35fe41fc9.png"> |
* [MM-25350](https://mattermost.atlassian.net/browse/MM-25350)
This PR was tested on: iPhone 11 Simulator
When the device is offline, the error message that renders is not "Something Went Wrong", but "Device is not connected to Internet. Please try again". The navigation screen setups for the "offline" message is entirely different from the "server response error" and are not affected by this PR. The code changes here only apply when the device is online and the server exhibits some …
=> [MM-25350] Hide 'Select Team' title on modal when server error occurs

app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap, app/components/sidebars/main/channels_list/channel_item/channel_item.js, app/components/sidebars/main/channels_list/channel_item/channel_item.test.js, app/components/sidebars/main/channels_list/channel_item/index.js
Cherry pick of #4332 on release-1.33.
- #4332: MM-24932 Bold LHS active channel manually marked as unread
/cc  @enahum
=> Automated cherry pick of #4332

app/components/post_draft/post_input/post_input.js, app/screens/search/search.js
Adds the ability to press the Enter key in a Hardware keyboard to perform a search.
Testing notes: Have a text entered in the input box in the center channel and then go to the search screen without previously sent the message in the center channel, perform a search by pressing the Enter key, message in the center channel should remain in the input box.
https://mattermost.atlassian.net/browse/MM-25670
=> MM-25670 perform search when hitting Enter on HW keyboard

app/screens/post_options/post_option.js, app/screens/post_options/post_options.js
The current implementation of the post options (when you long press a post) can trigger multiple times if you tap on them repeatedly.
With this PR we prevent that from happening by allowing once single tap every half a second, that gives enough time  for the post options to disappear from the view.
https://mattermost.atlassian.net/browse/MM-25820
=> MM-25820 prevent double tap in post options

app/mm-redux/selectors/entities/channels.ts, app/store/index.ts, app/utils/general.js, ios/Mattermost.xcodeproj/project.pbxproj
* Dispatch REHYDRATED if already hydrated after getStoredState call
* Handle null currentUser when getting locale
* Empty/null prev version is valid
* Update iOS target to 11.0
=> Fix initialization issues due to hydration

android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java, ios/NotificationService/NotificationService.swift, ios/UploadAttachments/UploadAttachments/UploadSession.swift
These changes ensure that we don't retry failed ID-loaded requests if the server response code is 401. For iOS we also prevent the 401 response message from overriding the default ID-loaded message.
https://mattermost.atlassian.net/browse/MM-25781
* iPhone SE, iOS 13
=> [MM-25781] Don't retry nor use response message on 401

share_extension/android/index.js
With the mobile app open and when leaving the last team from another client, the mobile app's `currentTeamId` is not unset so the Share extension still loads data for that team. Also, because you can leave/join channels through another client while the mobile app is not running, the Share extension will not have up-to-date team and membership data to use if opened first.
With these changes, the Share extension dispatches `getMyTeams` and `getMyTeamMembers` to update the state then handles selection of a default team and channel.
https://mattermost.atlassian.net/browse/MM-25794
* Android 10 emulator
=> [MM-25794] Ensure state teams and members are up-to-date

app/store/index.ts
This PR fixes a bug when opening the app was causing an "Unexpected Error" because of a failed migration as the action executed after the migration did not include `data` but `state` as the action payload property.
TBD
=> Avoid throwing when purging

app/screens/sso/sso.js
This PR disables the use of Shared Process Pool for the WebView used during SSO login. For some reason while this setting is enabled even if we clear the cookies the WebView stores them in memory and makes use of them every time until the app is fully closed, this means that further attempts to login to the same IdP even on different servers the user is not prompt for credentials and leads to unexpected behavior.
After this PR gets merged the user will always be prompt for their credentials when attempting to sign in using SSO.
Applies only to iOS but we can test on Android too.
https://mattermost.atlassian.net/browse/MM-25967
=> MM-25967 Disable Shared Process Pool in WebView

app/mattermost.js, app/mattermost.test.js
Emits the correct event so that the keyboard is dismissed when the main sidebar opens.
https://mattermost.atlassian.net/browse/MM-23079
=> [MM-23079] Ensure keyboard is dismissed when the main sidebar opens

app/screens/post_options/post_options.js
When the keyboard was previously opened there seems to be a race condition of some sort causing the newly "opened" screen to get closed immediately. By awaiting until the modal is dismissed, the new screens opens and remains opened.
https://mattermost.atlassian.net/browse/MM-26638
https://mattermost.atlassian.net/browse/MM-26656
=> MM-26638 MM-26656 await when dismissing post options modal

app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap, app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/autocomplete/emoji_suggestion/emoji_suggestion.test.js, app/components/autocomplete/emoji_suggestion/index.js
Rendering the FlatList after first rendering a null component was causing the EmojiSuggestion list not to be scrollable. Instead of returning a null component we now just set the height to 0 so that the FlatList is not displayed. While testing I found that `componentDidUpdate` would continuously be called after typing an initial `:` because the `fuse` prop would always be a new object. I've moved `fuse` into the component and reset it only on `props.emojis` change, then tested and ensured the issue in https://mattermost.atlassian.net/browse/MM-25470 did not occur.
https://mattermost.atlassian.net/browse/MM-26077
* iOS 13 simulator and iPhone SE
=> [MM-26077] Emoji autocomplete fixes

app/screens/login/login.js
When the username is being set by an EMM provider the TextInput value was being set but not the local variable used to set the username before executing the login flow, this PR makes sure both values are set
https://mattermost.atlassian.net/browse/MM-26667
=> MM-26667 Set EMM username as the initial loginId

app/mattermost.js
Make sure the redux store has been hydrated before switching to the start screen.
Test:
App should open and take you to either the channel screen if you are signed in or  to the server url screen.
If previously connected to a server when opening the app the previous server url should be in the input box on the server url screen.
Do test on first install and app upgrades.
Based on https://community.mattermost.com/core/pl/bdx8nidq4fnijr69fzjjt13frc
=> Wait for hydration before app launch

app/utils/markdown.js, app/utils/markdown.test.js, test/setup.js
The JSC that ships with iOS 11 or below does not support the regex to verify if the user is typing inside a code block. This PR disables the feature for iOS below v12
https://mattermost.atlassian.net/browse/MM-26722
This PR was tested on: iOS Simulator running 11.2
=> MM-26722 check for switchKeyboardForCodeBlocks only on iOS 12+

app/utils/markdown.js, app/utils/markdown.test.js, test/setup.js
Cherry pick of #4537 on release-1.33.
- #4537: MM-26722 check for switchKeyboardForCodeBlocks only on iOS
/cc  @enahum
=> Automated cherry pick of #4537

app/screens/create_channel/create_channel.js, app/screens/more_channels/more_channels.js, app/screens/more_dms/more_dms.js
When dismissing the screen to add a DM/Group join a Public Channel or create a public/private channel if the keyboard is opened cause of having set the focus on any input field, the keyboard now dismisses when closing the screen.
https://mattermost.atlassian.net/browse/MM-26490
Fixes: https://github.com/mattermost/mattermost-mobile/issues/4471
=> MM-26490 Dismiss keyboard when closing more dms / channels / create channel

app/components/at_mention/at_mention.js, app/components/channel_intro/channel_intro.js, app/components/post/post.js, app/components/sidebars/settings/settings_sidebar_base.js, app/screens/channel/channel_base.js, app/screens/reaction_list/reaction_row/reaction_row.js, app/screens/user_profile/user_profile.js, app/screens/user_profile/user_profile.test.js
This PR changes other user profiles (tap a user profile image on a post header) to be opened through a modal instead of being pushed to navigation
Fixes https://github.com/mattermost/mattermost-server/issues/14896
JIRA: https://mattermost.atlassian.net/browse/MM-25956
* iPhone X (Simulator)
* Google Pixel 3XL (Simulator)
=> MM-25956 Use new mobile modal style on Other User Profile

app/actions/views/root.js, app/init/push_notifications.js, app/mattermost.js, app/push_notifications/push_notifications.android.js, app/push_notifications/push_notifications.ios.js, app/screens/channel/channel_base.js
Currently there is a race condition when loading the channel from the push notification finishes before loading the channel screen and so because the `EphemeralStore` flag for **startFromNotification**  is set to false before it reaches the ` loadChannels` methods we are switching back to the "last" channel you were in.
This was happening for both Android and iOS and reproducing is not consistent hence the race condition.
Happened on:
* Opening the app from cold start
* With the app in the background and receiving a notification on different team than the current one visible in the app.
In this PR we set the flag after the channel screen has been loaded instead of doing that at the action level.
https://mattermost.atlassian.net/browse/MM-26749
=> MM-26749 Fix race condition when open from PN

app/mm-redux/types/config.ts, app/screens/user_profile/__snapshots__/user_profile.test.js.snap, app/screens/user_profile/user_profile.js
Adds the `ShowFullName` property to be used by the mobile app the same way `ShowEmailAddress` is being used for the user profile view. `ShowFullName` property is being used to control whether or not to display the `first_name` and `last_name` in profile view based on the system console settings.
Tested on iOS simulator. First and last name fields are displayed/hidden as expected, just like the `ShowEmailAddress` property.
Related to: 
- PR in mattermost-server [#14189](https://github.com/mattermost/mattermost-server/pull/14189)
- PR in mattermost-mobile [#4092](https://github.com/mattermost/mattermost-mobile/pull/4092)
JIRA: https://mattermost.atlassian.net/browse/MM-26827
=> MM-26827 Add ShowFullName property

app/components/post_draft/index.js, app/mm-redux/selectors/entities/users.ts, app/screens/channel_info/index.js
The selector for `isCurrentChannelReadOnly` relies on the currentUser being set, when this selector runs while logging out, the currentUser will be `undefined` leading to an unhandled exception.
No test needed: This only adds defensive code.
TBD
=> Fix unhandled exception when current user is not defined

app/components/post_draft/post_draft.js, app/components/post_draft/post_input/post_input.js
On Low end Android devices when continue typing immediately after sending a previous message the newly typed characters were being appended to the last sent message. This was happening as the device is slow it takes too long to process message and clear the input field.
With this PR we clear the text input as soon as the user taps to send the message and if it errors then we restore the message that was typed (for example when a slash commands fails). This introduces a small change in UX as the text input clears faster than the message being displayed in the post list in both Android and iOS.
https://mattermost.atlassian.net/browse/MM-22029
=> MM-22029 clear the text input as soon as possible

app/components/post_body_additional_content/post_body_additional_content.js
When posting an invalid YouTube link, the metadata of the post is present but there is no image metadata in it, as we were relying  on the presence of the images metadata the app gets an unhandled exception leading it to become unusable until the link is corrected or the post deleted.
This PR handles the scenario where the YouTube link is invalid. As the link is invalid the thumbnail of the video will be blank.
https://mattermost.atlassian.net/browse/MM-26946
=> MM-26946 Handle invalid YouTube links

app/actions/views/root.js, app/components/post_list/more_messages_button/index.js, app/components/post_list/more_messages_button/more_messages_button.js, app/components/post_list/more_messages_button/more_messages_button.test.js, app/screens/channel/channel_base.js, app/screens/channel/channel_base.test.js, app/screens/channel/index.js
Resetting of the unread count was previously done on MoreMessages mount. This was to ensure that the unread count was reset if you exited the app and re-launched it in the same channel. This didn't work well when launching the app from a push notification so we now reset the unread count when the app becomes inactive. Other changes include hiding the more messages button when the unread count decreases to 0 and not using an unreadCount of 0 to return early in `onViewableItemsChanged` as the `(newMessageLineIndex <= 0 || viewableItems.length === 0 || this.disableViewableItems)` condition is sufficient.
https://mattermost.atlassian.net/browse/MM-26855
=> [MM-26855] Ensure More Messages button works as expected when app is launched from a push notification

app/screens/image_preview/downloader.ios.js, ios/Podfile.lock, package-lock.json, package.json
This dependency is used to save images / videos to the camera roll in the  device.
=> Update camera-roll dependency

app/components/post_draft/quick_actions/quick_actions.js
There's no need to set `state.inputValue` from props in the constructor. It's sufficient to handle `inputValue` changes in `componentDidUpdate`.
https://mattermost.atlassian.net/browse/MM-26635
=> [MM-26635] Don't set state.inputValue in constructor

app/components/post_draft/quick_actions/file_quick_action/index.js, app/utils/file.js, app/utils/file.test.js
There's no need to use `decodeURIComponent` on Android.
https://mattermost.atlassian.net/browse/MM-26489
* iPhone SE, iOS 13
=> [MM-26489] No need to decode file URI on Android

app/screens/channel/channel_post_list/channel_post_list.js, app/screens/thread/__snapshots__/thread.ios.test.js.snap, app/screens/thread/thread.android.js, app/screens/thread/thread.ios.js, app/screens/thread/thread.ios.test.js, app/screens/thread/thread_base.js
`registerTypingAnimation` was passed to the Thread screen through props from ChannelPostList, however, this is not the only way to access the Thread screen. Defining `registerTypingAnimation` in the Thread screen as well allows for the typing animations to be registered from children components when navigating to the Thread screen from any other way other than ChannelPostList (ie, permalink in search results).
https://mattermost.atlassian.net/browse/MM-27313
=> [MM-27313] Define registerTypingAnimation in Thread screen

app/components/autocomplete/slash_suggestion/slash_suggestion.js
This PR fixes autocomplete experience after deleted cache
Fixes https://mattermost.atlassian.net/browse/MM-27381
This PR was tested on: iOS sumulator
=> [MM-27381] Fix autocomplete after cache delete

app/actions/navigation/index.js, app/actions/navigation/index.test.js, app/components/post_list/post_list.js, app/components/post_list/post_list.test.js, app/constants/navigation.js, app/screens/user_profile/user_profile.js
When pressing `Send Message` from the UserProfile screen, we only closed the modal. If you had navigated to the UserProfile screen from anywhere other than the Channel screen, you were not redirected to the Channel screen. Because the navigation stack can include both screens and modals, we now dismiss all modals and then pop to the root component. Also, the PostList component now calls `handleClosePermalink` when we pop to the root component. This will reset the `selectFocusedPostId` and set `showingPermalink` to false if a focused postId was set and `showingPermalink` was true.
https://mattermost.atlassian.net/browse/MM-27294
=> [MM-27294] Allow returning to Channel screen without resetting the navigation root

app/components/autocomplete/at_mention/at_mention.js
This is fixed in master through the [RN 0.63 upgrade PR](https://github.com/mattermost/mattermost-mobile/pull/4566/files#diff-5bc9f633ffdf43bfb77161cac509413cR65). This PR is to apply that single change to v1.34.
https://mattermost.atlassian.net/browse/MM-26678
* iPhone SE 2020
=> Set results count to 0

.circleci/config.yml, fastlane/Fastfile
Fix by correcting the output build. I realized that my build preference is different from the default value. That's why my original commit didn't work.
I'm requesting to include this to release-1.34.
Ref: https://github.com/mattermost/mattermost-mobile/pull/4605/files
Jira ticket - https://mattermost.atlassian.net/browse/DOPS-90
=> DOPS-90 fix folder for iOS simulator CI build

app/init/fetch.js, app/screens/sso/sso.js
When receiving an error from the server, the url should not be shown in the error string.
Only in the SSO screen (no need to replicate this one) -> don't know how to... this is to help with a customer issue
=> Cleanup fetch error & add details to sso

app/components/autocomplete/autocomplete.js, app/components/autocomplete/emoji_suggestion/__snapshots__/emoji_suggestion.test.js.snap, app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap, app/components/edit_channel_info/edit_channel_info.js, app/screens/edit_post/__snapshots__/edit_post.test.js.snap, app/screens/edit_post/edit_post.js, app/screens/post_options/post_options.js
In the post edit input box was being blocked by an invisible view that rendered on top of the input capturing the events before the input was able to do so blocking the text selection.
That view was added by the emoji autocomplete which had a different issue resolved by https://github.com/mattermost/mattermost-mobile/pull/4512. That PR in fact fixed the ability to scroll the emoji autocomplete list but created this bug as a side effect.
This PR prevents the emoji autocomplete picker from being rendered if there is no need as well as repositions the autocomplete element in the edit post screen fixing both issues at once.
https://mattermost.atlassian.net/browse/MM-27488
All Autocompletes (channel, users, slash commands, emojis) available in the following screens: Channel, Thread, Edit Post, …
=> MM-27488 Fix edit post input text selection

app/actions/views/root.js, app/components/post_list/more_messages_button/more_messages_button.js, app/components/post_list/more_messages_button/more_messages_button.test.js
When loading from a push notification we need to fetch the latest channel and member from the server in order to have the latest counts from which to calculate the unread message count.
https://mattermost.atlassian.net/browse/MM-27483
* iPhone SE, iOS 13
=> [MM-27483] Fetch channel and member when loading from push notification

app/actions/views/channel.js, app/mm-redux/client/client4.ts
- Skips pagination when calling `getGroups` in the `loadGroupData` fn to load _all_ groups instead of just the first 60 
- https://mattermost.atlassian.net/browse/MM-26972
- 60+ Groups loaded 
- Tested on iOS simulator
=> [MM-26972] Ignore pagination when loading group data

app/components/post_draft/draft_input/index.js
Only check for `USE_GROUP_MENTIONS` when channel is defined.
https://mattermost.atlassian.net/browse/MM-27576
* iPhone SE, iOS 13.5.1
=> [MM-27576] Check for undefined channel

app/screens/channel_add_members/channel_add_members.js, app/screens/channel_members/channel_members.js, app/screens/more_dms/more_dms.js, app/screens/selector_screen/selector_screen.js
When searching for user profiles the code assumed that results were being returned. If the network request failed for any reason, results are `undefined`, now this use case is handled.
Affected: 
* New conversation (+ sign for Direct Messages sidebar)
* Add channel member
* Interactive dialog user selector
https://mattermost.atlassian.net/browse/MM-27607
=> MM-27607 Fix filter undefined when searching profiles

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
PushNotification's `digestNotification` does not call `sendEventToJS` if the ReactContext is not initialized so I added a check in our `onReceived()` function as well.
https://mattermost.atlassian.net/browse/MM-25348
* MiA3, Android 10
=> [MM-25348] Send event to JS only if React initialized

app/components/post_body_additional_content/post_body_additional_content.js
Correctly plays a YouTube video when shared using a short link, to play the video we'll use the expanded link instead of the short link if available.
Test: short link as specified in the ticket and a regular link as well.
https://mattermost.atlassian.net/browse/MM-27711
=> MM-27711 Play YouTube video using expanded link

app/components/sidebars/main/main_sidebar.ios.js, app/components/sidebars/main/main_sidebar_base.js
When filtering the sidebar is cancelled the flag to allow the sidebar to be closed by a swipe was not included in the cancel handler.
https://mattermost.atlassian.net/browse/MM-27527
=> MM-27527 Allow swipe to close the sidebar after search is cancelled

app/mm-redux/client/client4.ts, app/screens/permalink/__snapshots__/permalink.test.js.snap, app/screens/permalink/permalink.js, app/screens/permalink/permalink.test.js
The Permalink view was using `getDerivedStateFromProps` lifecycle which wasn't needed as well as having two other issues:
1. Channel name was not present at times as the title was not being update with prop changes
2. Posts were being loaded multiple times (~4-5 times) when the view loaded as well as when retrying.
On this PR we removed the unnecessary lifecycle as well as we load post once as needed.
Test 1: Open a permalink from the same team.
Test 2: Open a permalink from a different team that you **have** loaded
Test 3: Open a permalink from a different team that you **have not** loaded
Test 4: Reset cache -> go to the channel with a permalink -> Disconnect from internet -> Open permalink -> Connect to internet -> Tap Retry
Found while trying to reproduce …
=> MM-25832 Prevent permalink view from loading posts multiple times

app/components/markdown/markdown_emoji/markdown_emoji.js, app/utils/emoji_utils.js, app/utils/emoji_utils.test.js
For a specific message format that included emoji's only like hair on fire `:fire:<space>\n:-)` the CommonMark parser was handling it as a paragraph instead of text or emoji, and the paragraph renderer for the emoji markdown component did not include a `<Text>` wrapper on the children as any of the other markdown components.
The code causing the soft crash has been unchanged for the past 2 years with this commit https://github.com/mattermost/mattermost-mobile/commit/d8abeabd70e612c22a42c148b1e7085c14c33c23
https://mattermost.atlassian.net/browse/MM-27982
This PR was tested on: iOS and Android
=> MM-27982 Fix soft crash for edge emoji formatting

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
The `senderName` may include special chars that are used in regex matching and so `replaceFirst` can throw an exception. To avoid this we now use `substring` to extract the message without the sender name.
https://mattermost.atlassian.net/browse/MM-28006
* Android 10 emulator
=> [MM-28006] Use substring over replaceFirst when removing sender name

app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap, app/components/emoji_picker/emoji_picker.ios.js, app/components/emoji_picker/emoji_picker_base.js
Applied `flex: 1` style needed to properly center the `ListEmptyComponent` only when the list is empty. Also updated the `keyboardOffset` so that the last list item is not hidden behind the keyboard.
https://mattermost.atlassian.net/browse/MM-28074
* iPhone SE
Before:
After:
=> [MM-28074] Apply flex style only when list is empty

app/components/at_mention/index.js, app/components/autocomplete/at_mention/index.js, app/components/post_body/index.js, app/components/post_draft/draft_input/index.js, app/mm-redux/selectors/entities/groups.ts, app/mm-redux/selectors/entities/roles.ts, app/mm-redux/selectors/entities/search.test.js, app/mm-redux/selectors/entities/search.ts
- Fixes a bug where a group (not synced to channel) is mentioned in a group synced channel but still shows as highlighted for the current user (if the user belongs in that group).
- Example: In this screenshot the user `board.one` is a member of `@board` _and_ `@executive`  however only `@board` group is synced to the current group constrained channel so only that group is being highlighted
- https://mattermost.atlassian.net/browse/MM-27132
Tested on iPhone 11 Simulator
=> [MM-27132] Handle group mention keys for group synced channels and teams 

app/screens/sso/sso.js
There have been reports of people unable to login using GitLab SSO. For SSO login attempts we were removing any potential query strings from the final url so they are not included as part of the server base url used for API calls.
Based on a small investigation it could be that GitLab not only appends query strings but also a hash as part of the redirect_uri, this hash in case it is present is not being explicitly removed.
With this PR, we attempt to fix this by reconstructing the base url using the base origin and the pathname in case that the mattermost server is hosted on a subpath
Potentially Resolves: https://github.com/mattermost/mattermost-mobile/issues/4712
=> SSO: Rebuild the server url without query string and/or hash

app/components/post_draft/draft_input/draft_input.js, app/components/post_draft/draft_input/draft_input.test.js
Resetting the text input in `handleSendMessage` makes the value inaccessible later in `doSubmitMessage` when using dictation. We know assign the value to a variable before resetting the text input and pass this value down to `doSubmitMessage`.
https://mattermost.atlassian.net/browse/MM-27824
* iPhone SE
=> [MM-27824] Store value before resetting text input

app/components/autocomplete/date_suggestion/date_suggestion.js
With the update to  react-native-calendars passing the width & height of the arrows is now mandatory, if not set arrows are not visible.
Test: In the calendar showed in the search screen, arrows should be visible and working
=> Show arrows in calendar

app/components/at_mention/__snapshots__/at_mention.test.js.snap, app/components/at_mention/at_mention.js
With #4733 we fixed the highlight for at (all | channel | here) mentions but did not set any boundaries so something like `@TheRebeccaShow` would format `here` as a mention without highlight.
This PR adds the boundaries needed so it does not happen.
=> Add word boundaries for (all | channel | here)

app/components/post_draft/uploads/uploads.js, app/components/post_draft/uploads/uploads.test.js
Return early in `handleUploadFiles` if the screen is not the top screen.
https://mattermost.atlassian.net/browse/MM-28245
=> [MM-28245] Handle upload files only for top screen

app/screens/channel_info/convert_private/convert_private.tsx
This PR fixes the Alert shown to the user once a channel was converted from public to private where the display name of the channel was not being applied to the translation string.
https://mattermost.atlassian.net/browse/MM-28307
=> MM-28307 Fix display name in convert channel to private alert

app/actions/views/channel.js, app/mm-redux/selectors/entities/posts.ts, app/screens/channel/channel_post_list/channel_post_list.js, app/screens/channel/channel_post_list/channel_post_list.test.js, app/screens/channel/channel_post_list/index.js, app/screens/flagged_posts/flagged_posts.js, app/screens/flagged_posts/flagged_posts.test.js, app/screens/flagged_posts/index.js, app/screens/long_post/__snapshots__/long_post.test.js.snap, app/screens/long_post/index.js, app/screens/long_post/long_post.js, app/screens/long_post/long_post.test.js, app/screens/permalink/index.js, app/screens/permalink/permalink.js, app/screens/permalink/permalink.test.js, app/screens/pinned_posts/index.js, app/screens/pinned_posts/pinned_posts.js, app/screens/pinned_posts/pinned_posts.test.js, app/screens/recent_mentions/index.js, app/screens/recent_mentions/recent_mentions.js, app/screens/recent_mentions/recent_mentions.test.js, app/screens/search/index.js, app/screens/search/search.js
At times, the thread screen seems to not display all the post in a thread. Repro steps are unclear but I have seen this happening to me a couple of times.
With this PR, we fetch the thread every time it is being opened in the thread view as well as modified the selector to build the thread from the posts and not `postInThread` reducer.
TDB
=> Always load the thread & modify thread selector

app/store/ephemeral_store.js
When the channel screen disappears into the background it gets removed from the stack, probably something got updated in the underlying navigation dependency that caused this change in behavior from 1.34
This PR avoids removing the Channel screen from the stack.
https://mattermost.atlassian.net/browse/MM-28295
=> MM-28295 Android fix opening sidebar after closing setting screen

app/components/at_mention/at_mention.js
For the ephemeral message that gets posted to add mentioned users to the channel the `textStyle` was undefined and  deconstructing it was causing the crash.
https://mattermost.atlassian.net/browse/MM-28450
=> MM-28450 Fix crash when posting at-mention that does not belong to the channel

package-lock.json, package.json
The `placeholderTextColor` prop was not applied due to a bug in `react-native-elements` which was fixed with https://github.com/react-native-elements/react-native-elements/pull/2531
https://mattermost.atlassian.net/browse/MM-28276
=> [MM-28276] Update react-native-elements

ios/MattermostShare/ShareViewController.swift
In the share extension the currentTeamId could still be set so we also check that the team count is 0 and how the error message if so.
https://mattermost.atlassian.net/browse/MM-28465
=> [MM-28465] Show share extension error if team count is 0

app/components/at_mention/at_mention.js
- Not sure how this happened - or how this ever actually worked... since mentionKeys is of the format `@groupname` and `getGroupFromMentionName()` returns the actual name without the `@` prepended. 
- https://mattermost.atlassian.net/browse/MM-27132
- Tested on iPhone 11 sim
=> [MM-27132] Fix groups not actually being highlighted for self on mobile

app/components/post_draft/post_input/post_input.js
Draft was only being saved when blurring the input, now it also saves when the component unmounts (leaving the thread screen while the input has focus)
Original issue reported in the ticket is already fixed on master (can be verified with the app created by this PR)  https://mattermost.atlassian.net/browse/MM-28488?focusedCommentId=98071
=> Save draft when post input unmounts

app/actions/navigation/index.js, app/constants/navigation.js, app/mattermost.js, app/store/ephemeral_store.js
With #4777 we attempted to fix an issue on the Android navigation, but that introduced a second bug that was affecting both Android and iOS:
* Open the app in a channel that contains posts
* Tap a post the Thread opens
* Go back to the channel screen
* Long Press on a Post and close the post options
* Tap on the post  to go to the thread screen again
Observed:  Nothing happened after tapping the post again.
The same could be accomplished by
* switching teams
*  opening the search screen
* opening the channel info screen
*  opening the emoji picker
* opening the gallery
* Opening the reaction list
In fact it  was  happening when opening any modal from the channel screen.
https://mattermost.atlassian.net/browse/MM-28295
=> MM-28295 Do not remove the Channel screen from the stack tracking

app/components/announcement_banner/__snapshots__/announcement_banner.test.js.snap, app/components/announcement_banner/announcement_banner.js, app/components/remove_markdown.js, app/screens/expanded_announcement_banner/expanded_announcement_banner.js, app/screens/expanded_announcement_banner/index.js
Announcement banners with hashtags or inline images were crashing as the ast for markdown removal did not include handling hashtags or images.
Also this PR fixes the layout of the extended banner  (when you tap on the banner) as well as the animation for showing / hiding the announcement banner.
https://mattermost.atlassian.net/browse/MM-28602
=> MM-28602 Fix announcement banner crash if it includes a hashtag

detox/e2e/support/server_api/channel.js, detox/e2e/support/server_api/index.js, detox/e2e/support/server_api/post.js, detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
MM-T109 User can't send the same message repeatedly
Test case: https://automation-test-cases.vercel.app/test/MM-T109
This PR was tested on: iOS simulator and Android emulator
=> MM-T109 Detox/E2E: "User can't send the same message repeatedly"

app/screens/long_post/index.js
Import `getPostThread` from the correct module.
https://mattermost.atlassian.net/browse/MM-28884
=> [MM-28884] Fix getPostThread import

app/reducers/views/channel.js, app/reducers/views/thread.js
After purging the store `state.views.channel.drafts` is an empty object so destructuring `state[action.channelId].files` would throw an error. This is fixed by using a default empty array when `state[action.channelId]?.files` is undefined.
https://mattermost.atlassian.net/browse/MM-28973
=> [MM-28973] Prevent destructuring of undefined

app/screens/channel_info/__snapshots__/channel_info.test.js.snap, app/screens/channel_info/channel_info.js, app/screens/channel_info/channel_info.test.js, app/screens/channel_info/index.js
Exclude NotificationPreference from ChannelInfo screen for DMs.
https://mattermost.atlassian.net/browse/MM-28975
=> [MM-28975] Exclude NotificationPreference for DMs

app/components/autocomplete/channel_mention/channel_mention.js
- Revert ordering change for `in:` auto-suggest search after user feedback. The ordering now is Public Channels, Private Channels, and finally DMs and GMs.
This PR only fixes ordering. Further search improvements are planned in https://mattermost.atlassian.net/browse/MM-26805
- https://mattermost.atlassian.net/browse/MM-28706
- The Jira ticket above reverts the changes in https://mattermost.atlassian.net/browse/MM-27540 (Parent: https://mattermost.atlassian.net/browse/MM-15477) which was implemented in https://github.com/mattermost/mattermost-mobile/pull/4704
Android Emulator - Pixel 3 XL running Android 11
=> [MM-28706] revert ordering change for `in:` auto-suggest search

assets/base/i18n/en.json, ios/MattermostShare/ShareViewController.swift, ios/UploadAttachments/UploadAttachments/StoreManager.h, ios/UploadAttachments/UploadAttachments/StoreManager.m, share_extension/android/extension_post/__snapshots__/extension_post.test.js.snap, share_extension/android/extension_post/extension_post.js, share_extension/android/extension_post/extension_post.test.js, share_extension/android/extension_post/index.js
Check to see if file uploads from mobile are disabled and if so show an error message.
QA: For iOS, please test all the scenarios in which [getCanUploadFiles](https://github.com/mattermost/mattermost-mobile/compare/MM-29216/share-ext-fix?expand=1#diff-d95e0ee731354c8e1142b425819d140aR218) can return false.
https://mattermost.atlassian.net/browse/MM-29216
* iOS 14 simulator
Android:
iOS:
=> [MM-29216] Don't allow sharing of files if file uploads are disabled

app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
In a recent PR https://github.com/mattermost/mattermost-mobile/pull/4531 , the display of slash command suggestions is changed. The first character is removed in order to get rid of the preceding slash on each suggestion. However with subcommands and command args, the first letter is not always a slash. This results in incomplete suggesitons like `iew` for `jira view`.
This PR makes it so the char is checked to be a slash first. In order to know if a given suggestion is for a command (and not a subcommand or argument), we can check if `item.complete` is only one word. This is the full value of the suggestion. For example `jira` versus `jira view`.
Fixes https://mattermost.atlassian.net/browse/MM-29275
-----
Before
-----
After
-----
Top level command looks correct before and after this …
=> [MM-29275]: Remove first char of slash cmd autocomplete suggestion text, only if it is a top-level command

android/gradle/wrapper/gradle-wrapper.properties
Fixes build error `Could not initialize class org.codehaus.groovy.runtime.InvokerHelper`
=> Update gradle version

android/app/src/main/java/com/mattermost/rnbeta/RNPasteableActionCallback.java, app/components/pasteable_text_input/index.js, app/components/pasteable_text_input/index.test.js
Even though we check the top screen ID when handling the `PASTE_FILES` event in the Upload component, a second `onPaste` event was emitted from the Channel screen which causes the Thread screen to emit a second `PASTE_FILES` event. We now only emit if the `onPaste` subscriber is the latest subscriber.
https://mattermost.atlassian.net/browse/MM-29300
=> [MM-29300] Emit PASTE_FILES event only from last subscribed input

app/store/index.ts, app/store/utils.js, app/store/utils.test.js
Fixes the redux-persist serializer to return the value based on the type of the argument.
https://mattermost.atlassian.net/browse/MM-28968
=> MM-28968 Fix redux-persist serializer

app/components/post_draft/__snapshots__/post_draft.test.js.snap, app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap, app/components/post_draft/post_input/post_input.js
Added props to TextInput based on RN docs to prevent devices from displaying autofill options.
https://mattermost.atlassian.net/browse/MM-29620
=> MM-29620 Add props to post input to prevent autofill

app/components/post_draft/__snapshots__/post_draft.test.js.snap, app/components/post_draft/uploads/index.js, app/components/post_draft/uploads/uploads.js, app/components/post_draft/uploads/uploads.test.js, assets/base/i18n/en.json
Verify  that file uploads are enabled before uploading pasted files, in case it is disabled an error is displayed.
https://mattermost.atlassian.net/browse/MM-29948
=> MM-29948 Display error msg when pasting files and uploads are disabled

ios/Podfile.lock
With the addition of Storybook a few iOS native dependencies were not linked cause of not running pod install after adding the dependencies.
=> Fix Storybook iOS Pods dependencies

app/screens/flagged_posts/flagged_posts.js
With the permalink refactor the function to open the permalink view from the save posts screens was missed.
https://mattermost.atlassian.net/browse/MM-30185
=> MM-30185 Fix bad permalink reference for saved posts screen

app/screens/channel_notification_preference/channel_notification_preference.android.js, app/screens/channel_notification_preference/channel_notification_preference.ios.js, app/screens/channel_notification_preference/channel_notification_preference.test.js, app/screens/channel_notification_preference/channel_notification_preference_base.js, app/screens/channel_notification_preference/index.js, assets/base/i18n/en.json, test/intl-test-helper.js
reflect inherited the default notification preference for channel level notification preference.
Note: The preference updates real time.
https://mattermost.atlassian.net/browse/MM-30101
This PR was tested on: Android & iOS
=> MM-30101 Match channel specific global notification preference

ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
The completion handler in our swizzled method should run on the main queue like in the [original method](https://github.com/wix/react-native-notifications/blob/master/lib/ios/RNNotificationsStore.m#L50)
https://mattermost.atlassian.net/browse/MM-30243
* iPhone SE, iOS 14.1
=> [MM-30243] Execute completion handler on main queue

android/app/src/main/AndroidManifest.xml, app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap, app/components/file_attachment_list/file_attachment.js, app/components/file_attachment_list/file_attachment_image.js, app/components/file_attachment_list/file_attachment_list.js, app/components/post_list/post_list.js, app/components/progressive_image/__snapshots__/progressive_image.test.js.snap, app/components/progressive_image/progressive_image.js, app/components/progressive_image/progressive_image.test.js
This PR loads the image progressively as the image comes into view-port instead of loading all the images on mount.
Fixes https://github.com/mattermost/mattermost-server/issues/15644
This PR was tested on: Poco F1, Android 9
=> MM-27354 Progressive image loading

patches/react-native-keyboard-tracking-view+5.7.0.patch
For some reason on iOS 14.2 the event for Keyboard did appear was being triggered when the text input loses focus, this caused the observer to re-calculate the frame of the post list as if the keyboard was opened creating a gap between  the list and the text input area.
This patch also addresses the posts displayed under the text input area when a hardware keyboard was being used.
@josephbaylon not sure if you want to give this a try, but @migbot was able to repro before, so he could confirm the fix.
* iPad Pro with iOS 14.1 & 14.2
* iPhone Xs with iOS 14.2
* iPhone 11 Simulator with iOS 14.1
=> Fix the Post List gap visible on iOS 14.2

app/components/autocomplete/at_mention/at_mention.js, detox/e2e/test/autocomplete/at_mention.e2e.js
This PR fixes an issue with being able to select `@` mentions multiple times in the same post draft and adds an E2E test to prevent the same issue from happening in the future.
https://mattermost.atlassian.net/browse/MM-29965
* iPhone 11 (Simulator)
* Pixel 3a XL (Simulator)
=> MM-29965 Fix at_mention autocomplete selection bug

app/components/autocomplete/at_mention/at_mention.js, app/mm-redux/selectors/entities/groups.ts
This PR updates the group names shown in the autocomplete when there is any change in the group data.
https://mattermost.atlassian.net/browse/MM-26785
This PR was tested on: iPhone 11 (Simulator)
=> On change, Group mentions are updated in autocomplete

app/constants/database.ts, app/database/default/migration/index.ts, app/database/default/models/app.ts, app/database/default/models/global.ts, app/database/default/models/server.ts, app/database/default/schema/index.ts, ios/Podfile.lock, package-lock.json, tsconfig.json, types/database/app.d.ts, types/database/global.d.ts, types/database/server.d.ts
This PR lays the foundation for the default schema that will be used on our storage layer.
It currently comprises of three entities; namely 'app', 'global' and 'server' and an empty migration object for the time being.
This PR is all about Model definition and it does not include unit tests.
https://mattermost.atlassian.net/browse/MM-30475
=> MM-30475 [v2] watermelondb default schema

scripts/postinstall.sh
I finally received the hardware to get setup on OSX. Setting up my dev environment didn't show me any errors, but I was getting strange ios simulator errors. After poking around a bit it, turns out my dev setup was broken (note: Xcode 12.2 does not work, you'll see `ruby/config.h` not found errors. Xcode 11.7 works). The install errors were masked because both stdout and stderr had been redirected to `/dev/null`. I've removed the redirect. The output is more verbose, but atleast we know if the setup completes successfully.
=> don't hide developer setup installation errors

app/screens/gallery/footer/index.tsx, app/screens/gallery/footer/summary/actions/actions.tsx, app/screens/gallery/footer/summary/actions/index.ts, types/screens/gallery.d.ts
Take into the server config `EnablePublicLink ` to show or hide the option to copy the file public link, this option also follows the EMM setting for `copyAndPasteProtection` and only applies to files attached to posts.
https://mattermost.atlassian.net/browse/MM-30858
=> MM-30858 fix: follow config to show the option to copy file public link

app/components/autocomplete/channel_mention_item/channel_mention_item.js
When the autocomplete/channel_mention_item was refactored as a functional component we missed to change the onPress handler
https://mattermost.atlassian.net/browse/MM-31114
=> MM-31114 fix: regression for in: autocomplete modifier in search screen

app/screens/gallery/footer/prepare_file/prepare_file.tsx
Adding a prefix for Android is no longer needed.
https://mattermost.atlassian.net/browse/MM-30850
=> MM-30850 fix(android): Failure to share self-uploaded file

app/components/sidebars/main/channels_list/filtered_list/filtered_list.js, app/components/sidebars/main/channels_list/list/list.js, app/screens/create_channel/create_channel.js, app/screens/more_channels/more_channels.js
Removes  deprecated lifecycle methods
Fixes https://github.com/mattermost/mattermost-server/issues/12355
This PR was tested on:  Redmi Note 8, Android
=> MM-18764 Remove deprecated lifecycles

app/init/push_notifications.test.js, app/init/push_notifications.ts
There's a scenario where, having 2+ push notifications and thus should have a badge count of 2+ when the app is launched via a push notification tap, the badge count is transitionally set to 0. This causes all push notifications to be cleared, losing any push notifications from other channels in the process. While the proper fix is to avoid this transitional setting of the badge count to 0 (and this fix will be part of v2), for v1 it is sufficient to only set the badge count to 0 in the case where there are no delivered push notifications. We can also force set the badge count to 0 by passing in a `force = true` param, as we'd do when logging out.
Note to QA: Please also test that all delivered push notifications are cleared when logging out. …
=> [MM-31216] iOS - Only set badge to 0 if there are no delivered notifications or it is forced

app/components/post_body_additional_content/post_body_additional_content.js, app/components/post_body_additional_content/post_body_additional_content.test.js
Prevent calling `Object.keys()` on `undefined` when checking for `props.metadata.images`.
Note: The `eslint-disable-line no-import-assign` in the unit tests were added due to being unable to `jest.mock('@utils/url')`
https://mattermost.atlassian.net/browse/MM-31198
* iOS 14 simulator
=> [MM-31198] Check for undefined metadata images

patches/react-native-keyboard-tracking-view+5.7.0.patch
Decrease the `kHeight` value by `bottomSafeArea` when the `kHeight` is not 0 and the keyboard is shown or will be shown.
Note to QA: Please also test transitions back into a screen that initially had the keyboard open, for example, have the keyboard up in the channel screen, press a post to go to the thread screen, then return back to the channel screen. Also include testing with a  Hardware Keyboard.
https://mattermost.atlassian.net/browse/MM-31231
iOS 14.2 devices:
* iPhone SE
* iPhone 12 simulator
iOS 13.7 devices:
* iPhone SE simulator
=> [MM-31231] Fix gap between post list and draft input

app/screens/permalink/__snapshots__/permalink.test.js.snap, app/screens/permalink/permalink.js, detox/e2e/support/server_api/channel.js, detox/e2e/support/ui/screen/index.js, detox/e2e/support/ui/screen/permalink.js, detox/e2e/test/smoke_test/search.e2e.js
- Added test for MM-T3235 in `smoke_test/search.e2e.js`
- Pulled out some functions for readability
Notes:
1. Created this PR on top of https://github.com/mattermost/mattermost-mobile/pull/4990 as I needed existing components and screens in there.
JIRA: https://mattermost.atlassian.net/browse/MM-30286
TM4J Cases:
- [MM-T3235](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3235)
=> MM-30286 Detox/E2E: Add e2e test for MM-T3235

app/actions/navigation/index.js
When we changed the navigation to lock the orientation to portrait, for tablets it was set as `undefined` but the navigation library is not handling the `undefined` value gracefully thus causing a crash, by setting the orientation explicitly to `all` everything works as it should.
https://mattermost.atlassian.net/browse/MM-31491
=> MM-31491 Set Tablet orientation explicitly to all

app/components/channel_loader/channel_loader.js, app/components/channel_loader/channel_loader.test.js
Fix for warning:
`Failed prop type: The prop type "retryLoad" is marked as required in "ChannelLoader", but it's value is undefined`
=> Fix ChannelLoader prop warning

app/components/sidebars/main/channels_list/channel_item/index.js
There's a race condition when state is set after leaving the current channel and selecting a default channel. The channel ID of the channel being left still exists in the sidebar but is not included when the ChannelItem component re-renders. I tried to batch the [`selectDefaultChannel` and `leaveChannelService` actions](https://github.com/mattermost/mattermost-mobile/blob/499c749a6fd90fa5cb3f42b9d86ea1cc1a5e5800/app/actions/views/channel.js#L487-L491) but that prevented the selected default channel from being loaded. Defaulting to an empty object is a quick fix for the crash and I'll open a [new ticket](https://mattermost.atlassian.net/browse/MM-31770) for a more thorough fix.
https://mattermost.atlassian.net/browse/MM-31754
https://mattermost.atlassian.net/browse/MM-31756
This PR was …
=> [MM-31754] [MM-31756] Default to an empty channel object

app/components/markdown/markdown_link/markdown_link.js
- Tapping a channel link always showed an alert saying "This link belongs to a deleted channel or to a channel to which you do not have access". 
- https://mattermost.atlassian.net/browse/MM-31778 
- Android and ios emulators
=> [MM-31778]: fix false error message on tapping channel link

detox/e2e/support/ui/component/alert.js, detox/e2e/support/ui/component/index.js, detox/e2e/support/ui/component/post_options.js, detox/e2e/support/ui/screen/channel.js, detox/e2e/support/ui/screen/thread.js, detox/e2e/test/autocomplete/edit_post.e2e.js, detox/e2e/test/messaging/recent_emojis.e2e.js, detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js, detox/e2e/test/messaging/tapping_channel_url_link_joins_channel.e2e.js, detox/e2e/test/notifications/in_app_notification.e2e.js, detox/e2e/test/smoke_test/message_deletion.e2e.js
- Added tests for MM-T3232 and MM-T3234 in `smoke_test/message_deletion.e2e.js`
- Added new alert component `support/component/alert.js`
- Added `deletePost` on channel screen, thread screen, and post options
- Updated other tests to use `postMessage` and minor cleanup
JIRA: https://mattermost.atlassian.net/browse/MM-31272
TM4J Cases:
- [MM-T3232](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3232)
- [MM-T3234](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3234)
=> MM-31272 Detox/E2E - Add e2e tests for MM-T3232 and MM-T3234

app/utils/file.js, app/utils/file.test.js
When a file was being shared and its filename contained multiple dots (including the extension) the file wasn't being able to preview as we split the filename without considering multiple dots and the extension was wrongly  set.
https://mattermost.atlassian.net/browse/MM-31705
=> MM-31705 allow file local path to use multiple dots

app/actions/views/channel.js, app/actions/views/channel.test.js, app/selectors/channel.js
- Fix viewing/joining archived channels using channel links. Include all channels in query for channels, and respect the `ExperimentalViewArchivedChannels` setting
- https://mattermost.atlassian.net/browse/MM-30976
- Android and ios emulators.
=> [MM-30976] fix viewing/joining archived channels using channel links

app/components/autocomplete/at_mention_item/at_mention_item.tsx
The "(you)" suffix for the  current user in the at mention autocomplete was only being shown if the first/last name or nickname were set.
https://mattermost.atlassian.net/browse/MM-31196
=> MM-31196 Add missing "(you)" in at_mention autocomplete

detox/e2e/environment.js
- Fix CustomDetoxEnvironment constructor args due to upgrade
This only fixes the error Jesse experienced.  I'll address other failures in a separate PR once I'm able to run the whole suite
=> Detox/E2E: Fix CustomDetoxEnvironment constructor args

app/components/reactions/index.js, app/screens/post_options/index.js, app/selectors/emojis.js
The number of  reactions to a post was limited to 40, but the way it was done instead of limiting the reactions to 40 different emojis is was limiting a total of 40 reactions instead. This PR fixes that.
https://mattermost.atlassian.net/browse/MM-31990
=> MM-31990 fix limit reacting to a post to 40 different emojis

android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java, app/screens/notification/index.tsx, patches/react-native-navigation+7.8.1.patch
The in-app overlay was conflicting with RNSafeAreaContext thus once the in-app notification was shown, gestures outside the overlay were not captured, this PR applies a patch to the overlay in the nav library and also fixes a couple of styles.
On top of that the Keychain manager required a couple of options in order to actually retrieve the session token from the native side on Android.
Tests: It would be good to test notifications with id loaded on Android to ensure the device is able to retrieve the session token and use it to get the actual message from the server.
https://mattermost.atlassian.net/browse/MM-32183
Android 11 Pixel 4
iOS 14.3 iPhone XS & 12
=> MM-32183 Fix in-app notification + Android ack

app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/autocomplete/emoji_suggestion/emoji_suggestion.test.js, app/components/emoji_picker/emoji_picker.test.js, app/components/emoji_picker/index.js
- Tweak emoji search options for better results. We drop the location and threshold options in favour of matching anywhere in the emoji alias string. For smaller search terms there will more results returned but the general ordering does not change (i.e. low confidence results will still be lower in the list, and usually beyond the start scroll limit of the flat list).
For longer search terms we will have better results. I dont think there are any performance regressions - according to `app/utils/emojis.js` there are only about 1447 emojis.
- https://mattermost.atlassian.net/browse/MM-30994
- 
- ios emulator running ios 13.7
**Before**
**After**
=> [MM-30994] tweak emoji search options for better results

app/components/markdown/markdown.test.js, package-lock.json, package.json
This fixes an error that would occur when someone posts a message containing a large number of asterisks. This caused an error because the message would be parsed as a very deeply nested structure of bold/unbold tags which would cause us to cut off the rendering at a certain depth, and then the part of commonmark-react-renderer responsible for rendering bold/unbold would hit an error due to the Markdown tree only being partially rendered. The actual fix for that is here: https://github.com/mattermost/commonmark-react-renderer/commit/81af294317ebe19b5cc195d7fbc4f4a58177854c
For QA (and anyone curious), note that we are still cutting off the rendered Markdown once it hits a certain depth, so the sample message in the ticket renders as empty (see attached screenshot). We could always look at …
=> MM-32254 Update CommonMark and fix handling of deeply nested Markdown

app/actions/views/permalink.ts, app/components/markdown/markdown_link/index.js, app/components/markdown/markdown_link/markdown_link.js, app/components/post_list/index.js, app/components/post_list/post_list.js, app/utils/url.js, detox/e2e/test/messaging/permalink.e2e.js
Some time ago, support for `_redirect` was added to the webapp permalink handler code. The exact semantics there effectively replaced it with the current team name, allowing the server to generate permalinks to DMs and GMs without having to know more context about the enduser and which teams they access.
This PR extends the mobile application to do same, though it works even better here, since it resolves non-DM and non-GM permalinks across team boundaries. We may revisit the webapp implementation to do same at some point, but all of this is only lightly used at present.
This is my first stab at writing a Detox test, though the Cypress familiarity made it relatively straightforward. Big thanks to @josephbaylon for various assists :)
https://mattermost.atlassian.net/browse/MM-31322
This PR …
=> MM-31322: redirect permalink handler

app/components/markdown/markdown.js, app/components/markdown/markdown.test.js
Converts `this.props.value` to a string so that the Commonmark parser does not complain.
https://mattermost.atlassian.net/browse/MM-32734
Fixes: #5162
=> [MM-32734] Convert value to string to prevent crash

app/components/progressive_image/progressive_image.js, app/components/retriable_fast_image/index.tsx, app/components/retriable_fast_image/retriable_fast_image.test.js
FastImage does not provide a way to retry failed requests. This won't be an issue in v2 since swizzling the request will apply any retry interceptors added to the APIClient, but for v1 the easiest thing to do was to add a `key` prop and update it to force a re-render and hence a new request.
https://mattermost.atlassian.net/browse/MM-32579
=> [MM-32579] Add retriable FastImage component

detox/e2e/test/smoke_test/message_reply.e2e.js
- Added `smoke_test/message_reply.e2e.js` for MM-T3218
JIRA: https://mattermost.atlassian.net/browse/MM-30695
TM4J Cases:
- [MM-T3218](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3218)
=> MM-30695 Detox/E2E: Add e2e for MM-T3218

app/screens/channel_info/channel_info_row.js, detox/e2e/support/ui/screen/channel_info.js, detox/e2e/test/smoke_test/favorite_channels.e2e.js
- Added `smoke_test/favorite_channels.e2e.js` for MM-T3191
- Added switch testIDs
JIRA: https://mattermost.atlassian.net/browse/MM-30698
TM4J Cases:
- [MM-T3191](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3191)
=> MM-30698 Detox/E2E: Add e2e for MM-T3191

app/screens/edit_post/__snapshots__/edit_post.test.js.snap, app/screens/edit_post/edit_post.js, detox/e2e/support/ui/screen/edit_post.js, detox/e2e/test/autocomplete/edit_post.e2e.js, detox/e2e/test/smoke_test/logout.e2e.js, detox/e2e/test/smoke_test/message_edit.e2e.js
- Added tests for MM-T3273 and MM-T3228 in
- `smoke_test/message_edit.e2e.js` 
- `smoke_test/logout.e2e.js`
- Added/updated testIDs
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-30697
- https://mattermost.atlassian.net/browse/MM-30699
TM4J Cases:
- [MM-T3273](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3273)
- [MM-T3228](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3228)
=> [MM-30697, MM-30699] Detox/E2E: Add e2e for MM-T3273 and MM-T3228

app/components/markdown/markdown_link/index.js, app/components/markdown/markdown_link/markdown_link.js, app/components/post_list/index.js, app/components/post_list/post_list.js, app/utils/url.js, detox/e2e/support/server_api/channel.js, detox/e2e/support/server_api/preference.js, detox/e2e/support/ui/component/channels_list.js, detox/e2e/support/ui/component/main_sidebar.js, detox/e2e/test/messaging/permalink.e2e.js, detox/e2e/test/smoke_test/channels.e2e.js
- Added tests for MM-T3184 and MM-T3186 in `smoke_test/channels.e2e.js`
- Added new api in `support/server_api/channel.js` and `support/server_api/preference.js`
JIRA: https://mattermost.atlassian.net/browse/MM-30289
TM4J Cases:
- [MM-T3184](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3184)
- [MM-T3186](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3186)
=> MM-30289 Detox/E2E - Add e2e tests for MM-T3184 and MM-T3186

app/screens/interactive_dialog/dialog_element.js, app/screens/interactive_dialog/dialog_element.test.js
The `select` support for interactive dialogs was missing support for handling the default value provided by the server.
Fixes: https://mattermost.atlassian.net/browse/MM-32851
=> MM-32851: honour defaults in interactive dialogs

app/screens/permalink/permalink.js
Was unable to open post previews in modal from search, pinned and mentions. Team name is not sent for post previews. Now team check is made optional while we show the prompt to join a private channel. 
This PR was tested on: iOS 14.4
=> Unable to open previews from search, pinned and mentions after permalink prompt implemented

app/actions/websocket/apps.ts, app/actions/websocket/index.ts, app/constants/websocket.ts
Add refresh bindings websocket event.
This naïve approach is the first iteration on handling changes in the bindings on server side. When the event is sent, we fetch one more time the bindings. Eventually we will look into better ways to handle this, maybe sending information through the websocket event.
https://mattermost.atlassian.net/browse/MM-33129
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/83
Webapp: https://github.com/mattermost/mattermost-webapp/pull/7599
=> Add refresh websocket event to refetch bindings

app/mm-redux/reducers/entities/__snapshots__/apps.test.js.snap, app/mm-redux/reducers/entities/apps.test.js, app/mm-redux/reducers/entities/apps.ts, app/screens/channel_info/bindings/bindings.tsx, app/screens/post_options/bindings/bindings.tsx, app/utils/apps.test.ts, app/utils/apps.ts
Add binding validation on binding fetch. Any binding without a call or an app id in a leaf node (either by inheritance or having it itself) is considered not valid and filtered. Also, certain locations have certain requisites (for mobile, right now, just the label for each location).
Very similar changes as in https://github.com/mattermost/mattermost-redux/pull/1381
None
=> Add binding validation on binding fetch

app/actions/apps.ts, app/actions/views/command.js, app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.test.ts, app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts, app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts, app/components/autocomplete/slash_suggestion/slash_suggestion.tsx, app/components/embedded_bindings/button_binding/button_binding.tsx, app/components/embedded_bindings/button_binding/index.ts, app/components/embedded_bindings/menu_binding/index.ts, app/components/embedded_bindings/menu_binding/menu_binding.tsx, app/mm-redux/client/client4.ts, app/mm-redux/types/apps.ts, app/screens/apps_form/apps_form_component.tsx, app/screens/apps_form/apps_form_container.tsx, app/screens/apps_form/index.ts, app/screens/channel_info/bindings/bindings.tsx, app/screens/channel_info/bindings/index.ts, app/screens/post_options/bindings/bindings.tsx, app/screens/post_options/bindings/index.ts
The `Call` struct has been split into two structs.
- The `Call` struct is now a smaller struct provided by the App.
- The `CallRequest` contains the `Call`, and the other values sent to the server, such as `Type` and `Context`.
Other changes:
- `State` field added to `Call`
- `SelectedField` and `Query` added to remove the nested values in `Values`. Now `Values` is just the form values.
```go
type Call struct {
Path   string      `json:"path,omitempty"`
Expand *Expand     `json:"expand,omitempty"`
State  interface{} `json:"state,omitempty"`
}
type CallRequest struct {
Call
Type          CallType               `json:"type"`
Values        map[string]interface{} `json:"values,omitempty"`
Context       *Context               `json:"context,omitempty"`
RawCommand    string …
```
=> Use App CallRequest structure

app/utils/apps.ts
Use the right feature flag when checking if apps are enabled or not.
DISCLAIMER: Since the server PR is not yet merged, this will render apps unusable on the client until that PR gets merged. After that, only server initialized with the feature flag set to true will show apps related code in the client.
None
Server: https://github.com/mattermost/mattermost-server/pull/16851
Webapp: https://github.com/mattermost/mattermost-webapp/pull/7643
=> Add feature flag

app/components/markdown/markdown.js, app/components/markdown/markdown_image/markdown_image.js, app/components/progressive_image/__snapshots__/progressive_image.test.js.snap, app/components/progressive_image/progressive_image.js, app/constants/image.js, app/screens/gallery/gallery_viewer.tsx, app/utils/images.test.js
When an inline image url contains some query strings, the metadata for the image doesn't match the link thus the image was not showing, with this PR if the link does not match the one in the metadata, we will then use the first image available in the metadata to be displayed.
PR also takes care of black images on top of a black background.
https://mattermost.atlassian.net/browse/MM-31341
https://mattermost.atlassian.net/browse/MM-25811
=> MM-31341 Use first metadata info for inline md images

app/components/sidebars/main/channels_list/filtered_list/filtered_list.js, app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap, app/components/sidebars/main/channels_list/list/list.js, app/components/sidebars/main/channels_list/unread_indicator/unread_indicator.base.js, app/screens/channel_members/__snapshots__/channel_members.test.js.snap, app/screens/channel_members/channel_members.js, app/screens/long_post/__snapshots__/long_post.test.js.snap, app/screens/long_post/long_post.js, detox/e2e/support/ui/component/alert.js, detox/e2e/support/ui/component/channels_list.js, detox/e2e/support/ui/component/main_sidebar.js, detox/e2e/support/ui/component/teams_list.js, detox/e2e/support/ui/screen/channel.js, detox/e2e/support/ui/screen/channel_members.js, detox/e2e/support/ui/screen/index.js, detox/e2e/support/ui/screen/long_post.js, detox/e2e/test/channels/archived_channels.e2e.js, detox/e2e/test/main_sidebar/select_channel.e2e.js, detox/e2e/test/messaging/permalink.e2e.js, detox/e2e/test/messaging/tapping_channel_url_link_joins_channel.e2e.js, detox/e2e/test/notifications/channel_notification_default.e2e.js, detox/e2e/test/notifications/channel_notification_preference.e2e.js, detox/e2e/test/smoke_test/channels.e2e.js, detox/e2e/test/smoke_test/direct_messages.e2e.js, detox/e2e/test/smoke_test/favorite_channels.e2e.js, detox/e2e/test/smoke_test/manage_members.e2e.js, detox/e2e/test/smoke_test/message_posting.e2e.js, detox/e2e/test/smoke_test/mute_channels.e2e.js, detox/e2e/test/smoke_test/unread_channels.e2e.js, detox/e2e/test/smoke_test/user_status.e2e.js
- Added tests for MM-T3188, MM-T3193, MM-T3198, MM-T3229 in
- `detox/e2e/test/smoke_test/manage_members.e2e.js`
- `detox/e2e/test/smoke_test/message_posting.e2e.js`
- `detox/e2e/test/smoke_test/mute_channels.e2e.js` 
- `detox/e2e/test/smoke_test/unread_channels.e2e.js`
- Added new component
- `detox/e2e/support/ui/screen/channel_members.js`
- Pulled `goToChannel` helper function to channel screen and updated affected tests
- Added new testIDs
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-30426
TM4J Cases:
- [MM-T3188](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3188)
- [MM-T3193](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins …
=> MM-30426 Detox/E2E: Add e2e for MM-T3188, MM-T3193, MM-T3198, MM-T3229

app/components/reactions/reaction.js, app/screens/add_reaction/__snapshots__/add_reaction.test.js.snap, app/screens/add_reaction/index.js, app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap, app/screens/channel_info/channel_info_header.js, detox/e2e/support/ui/component/post_options.js, detox/e2e/support/ui/screen/add_reaction.js, detox/e2e/support/ui/screen/channel_info.js, detox/e2e/test/channel_info/header.e2e.js, detox/e2e/test/guest_account/guest_experience.e2e.js, detox/e2e/test/messaging/permalink.e2e.js, detox/e2e/test/messaging/tapping_channel_url_link_joins_channel.e2e.js, detox/e2e/test/smoke_test/add_reaction.e2e.js, detox/e2e/test/smoke_test/channels.e2e.js, detox/e2e/test/smoke_test/direct_messages.e2e.js, detox/e2e/test/smoke_test/edit_channel.e2e.js, detox/e2e/test/smoke_test/group_messages.e2e.js, detox/e2e/test/smoke_test/message_posting.e2e.js, detox/e2e/test/teams/select_team.e2e.js
- Added tests for MM-T3199, MM-T3223, MM-T3224 in
- `detox/e2e/test/smoke_test/add_reaction.e2e.js`
- `detox/e2e/test/smoke_test/edit_channel.e2e.js`
- Added new testIDs
- Stabilized some other e2e tests for both iOS and Android
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-30428
TM4J Cases:
- [MM-T3199](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3199)
- [MM-T3223](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3223)
- [MM-T3224](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.ka …
=> MM-30428 Detox/E2E: Add e2e for MM-T3199, MM-T3223, MM-T3224

app/screens/apps_form/apps_form_component.tsx
Avoid double submitting modals for apps.
Same PR as https://github.com/mattermost/mattermost-mobile/pull/5235 but had to make a new one due to the feature/cloud-apps branch being deleted. All reviewers approved this earlier, so it should be fine to merge.
https://mattermost.atlassian.net/browse/MM-34112
=> Handle double submit on modals

detox/e2e/plugins/post_message_as.js, detox/e2e/support/server_api/index.js, detox/e2e/support/server_api/plugin.js, detox/e2e/support/server_api/system.js, detox/e2e/utils/webhook_utils.js, detox/package-lock.json, detox/package.json, detox/webhook_server.js
- Added Plugins API
- `detox/e2e/support/server_api/plugin.js`
- Added webhook server
- `detox/e2e/plugins/post_message_as.js`
- `detox/e2e/utils/webhook_utils.js`
- `detox/webhook_server.js`
1. Feature flags via split.io - I don't think this is implemented in Cypress e2e just yet; @saturninoabril may have a better idea to implement in both Cypress and Detox e2e
2. Apps proxy plugin installed and enabled --> this is achieved in Cypress via MM API calls; the same is done for Detox
3. webhook server --> similar to Cypress webhook server.
In summary, the feature flag capability is not yet available and any new detox tests may need to be disabled until the feature flag is permanently enabled.
JIRA: https://mattermost.atlassian.net/browse/MM-34444
=> MM-34444 Detox/E2E: Prepare plugin API and webhook server

app/actions/views/command.ts
There is an issue where an iPhone with Smart Punctuation enabled will convert `--` with an em dash `—`. Many commands rely on double dashes being preserved in the submitted text. This PR makes it so if a command is being submitted, the em dashes are replaced with double dashes.
Fixes https://mattermost.atlassian.net/browse/MM-33892
=> [MM-33892] Replace em dash with double dash for commands

app/actions/views/command.ts, app/actions/views/post.js, app/components/embedded_bindings/button_binding/button_binding.tsx, app/components/embedded_bindings/button_binding/index.ts, app/components/embedded_bindings/menu_binding/index.ts, app/components/embedded_bindings/menu_binding/menu_binding.tsx, app/components/post_header/__snapshots__/post_header.test.js.snap, app/components/post_header/post_header.js, app/mm-redux/types/apps.ts, app/screens/apps_form/apps_form_container.tsx, app/screens/apps_form/index.ts, app/screens/channel_info/bindings/bindings.tsx, app/screens/channel_info/bindings/index.ts, app/screens/post_options/bindings/bindings.tsx, app/screens/post_options/bindings/index.ts, types/actions/posts.d.ts
This PR makes it so any ephemeral message that is posted as a result of a call response, is posted by the app's bot user.
Fixes https://mattermost.atlassian.net/browse/MM-31083
https://github.com/mattermost/mattermost-webapp/pull/7789
https://github.com/mattermost/mattermost-plugin-apps/pull/119
=> Post app call response ephemeral messages as bot

android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java, patches/react-native-keychain+6.2.0.patch
This PR attempts to reduce the amount of times we access the KeyStore to retrieve session information with help of an in-memory cache.
The cache is initialized with every Keychain instance, one for the app running and another one for the notifications.
https://mattermost.atlassian.net/browse/MM-32725
=> MM-32725 Reduce KeyStore qty access

app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
Instead of using the appID as the root command trigger, respect the label send by the app.
https://mattermost.atlassian.net/browse/MM-34491
This PR was tested on: None
=> [MM-34491] Respect slash command root label

app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap, app/components/post_attachment_opengraph/post_attachment_opengraph.js, app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
Some link previews may include opengraph with an invalid image url or a valid url without an actual image.
With this PR we try and ensure that we only render the image component of the openGraph if an actual image with dimensions is found
Test link: https://atarinft.io/
https://mattermost.atlassian.net/browse/MM-34681
Before
After
=> MM-34681 Validate OpenGraph Image before attempting to load

app/components/post/post.js, app/screens/channel/channel_base.js, app/screens/channel/channel_base.test.js, app/screens/channel/index.js
Switch teams when opening the app on a team that was archived.
does happened in iOS and Android.
Note: Archiving the team while the mobile app or webapp are opened, the client remains in the team. Another thing to note is that the server is not checking if the team has been archived so posting in a channel that belongs to the team is also possible while the client can still access the team. Not sure if the above reproduces while using **mmctl** instead of the binary cli.
https://mattermost.atlassian.net/browse/MM-29317
=> MM-29317 Select default team when current team is archived

app/components/profile_picture/profile_picture.js
Ensure that `id` is only accessed if `user` is defined.
* iPhone 12 simulator, iOS 14.4
=> Fix testID

app/screens/channel/channel_base.js, app/screens/channel/index.js
After https://github.com/mattermost/mattermost-mobile/pull/5295 logging out from the app caused the app to wrongly show the ErrorTeamsList as it attempted to load the default team after the user was logged out. This PR prevents that code from executing.
=> Fix logout by preventing the app from showing ErrorTeamsList screen

app/components/autocomplete/at_mention/at_mention.js, app/components/autocomplete/channel_mention/channel_mention.js, app/components/autocomplete/channel_mention/index.js
After the introduction of #5199 the autocomplete for user and channel mentions that uses a SectionList were not working properly when displaying multiple sections, not allowing the user to tap on a result or scroll the list.
By setting the `removeSubclipViews` to false on iOS the issue is resolved, Android still applies the prop and works as expected.
=> MM-34585 Fix at_mention and channel_mention autocomplete on iOS

app/actions/views/channel.js, app/actions/websocket/websocket.test.js, app/client/rest/channels.ts, app/mm-redux/actions/channels.ts
Since server 5.28 we added the ability to retrieve archived channels since a moment in time to reduce the amount of channels that were return for a given request, now that the supported ESR is 5.31 we can safely introduce this feature.
We use the last known timestamp we had the WS connected when fetching the user channels.
https://mattermost.atlassian.net/browse/MM-27251
=> MM-27251 Fetch team channels including archived since last known timestamp

README.md, fastlane/metadata/changelog
[Due to a bug in the server](https://github.com/mattermost/mattermost-mobile/pull/5339), the minimum server version is 5.31.3.
This value should include the dot release in future updates
=> Specifying minimum server version in README.md

app/screens/edit_post/edit_post.js
Adds padding for iOS (`30`) alongside with existing `40` for android.
Fixes https://mattermost.atlassian.net/browse/MM-25709
- Android Pixel 4 v29 (Simulator)
- iPhone 12 v14.4 (Simulator)
https://user-images.githubusercontent.com/456511/116016608-7d1cdb80-a680-11eb-8539-59a81fc6efe7.mov
```release-note
Fixes iOS keyboard overlap on long edit posts
```
=> [MM-25709] Keyboard / Input height in iOS for post edits

app/actions/views/channel.js, app/actions/websocket/index.ts, app/client/rest/groups.ts
Cherry pick of #5163 on release-1.43.
```release-note
On web socket reconnect, Instead of getting all the groups, fetch only the updated groups
```
=> Automated cherry pick of #5163

android/app/src/main/java/com/mattermost/share/ShareModule.java, share_extension/types/index.d.ts, share_extension/utils/index.tsx
This now explicitly checks that a "shared" text is actually a string before being treated as such.
The selected text being shared is available in `intent.getStringExtra(Intent.EXTRA_TEXT);` where we check for it - if it is blank and `text/plain` intent is still sent, we can safely assume it a `.txt` file.
Boolean `isString` is available on the JS side to check.
Fixes https://mattermost.atlassian.net/browse/MM-26160
- Pixel 4 Simulator Android v29
https://user-images.githubusercontent.com/456511/116178057-431f0880-a758-11eb-9e9d-f35c6248ae7d.mov
```release-note
Fixed text files being shared to Mattermost when part of a group of a files.
```
=> [MM-26160] Updates to check if text is string before attaching as string

app/mm-redux/actions/users.ts
Some actions can get a sanitized version of the current user in the response, thus it was excluded when updating the redux store to avoid the current user from being overwritten but it was also excluded from the action returned value. This PR keeps the current user from not being overwritten but it keeps it in the returned values.
https://mattermost.atlassian.net/browse/MM-34069
```release-note
Fixed User Autocomplete by adding the current user to the list
```
=> MM-34069 include current user in return values from getProfile* actions

app/components/at_mention/__snapshots__/at_mention.test.js.snap, app/components/at_mention/at_mention.js
In a previous PR #5268 then mention color used was the wrong one, this PR applies the `mentionHighlightLink` color to mentions that are highlighted.
Note: No dev review needed, it only replaces the color used.
https://mattermost.atlassian.net/browse/MM-31874
```release-note
NONE
```
=> MM-31874 Properly use theme mention highlight link color

app/components/post_draft/__snapshots__/post_draft.test.js.snap, app/components/post_draft/post_draft.js, patches/react-native-keyboard-tracking-view+5.7.0.patch
This PR attempts to prevent the last message in a channel to be rendered behind the input box without the ability to fully show the message in the channel post list.
https://mattermost.atlassian.net/browse/MM-31510
```release-note
Fixed last message rendered behind the input box on iPad
```
=> MM-31510 fix: last message is rendered behind the input box on iPad

app/actions/websocket/index.ts, app/client/websocket/index.ts, app/components/network_indicator/network_indicator.js, app/init/fetch.js, app/mm-redux/types/config.ts
We send connection_id and sequence_number as part of the query params.
On receiving an event, we check if it's a hello packet, and if so,
we inspect the connection_id sent with it. If it's different to what
we have already, then we make the API calls and set sequence to 0.
And if the sequence number is different to what we expect, then
we just disconnect the connection, and expect the server to send
from where we left off.
https://mattermost.atlassian.net/browse/MM-32591
https://github.com/mattermost/mattermost-webapp/pull/7921
```release-note
NONE
```
=> MM-32591: Reliable Websockets: Client side changes

app/components/post_draft/post_input/post_input.js, app/components/post_draft/post_input/post_input.test.js, app/constants/device.js
Because tablets have the permanent sidebar it is possible to switch channels while the post message input is still in focus, by the time the input gets blurred the channelId has already changed causing the draft to be saved for the channel being switched to instead of the channel from.
This PR provides a different behavior for tablets to prevent the above from happening.
https://mattermost.atlassian.net/browse/MM-35320
```release-note
Fixed an issue that cause the draft to be saved for a different channel when running the app on Tablets
```
=> MM-35320 Fix race condition when saving draft on tablets

patches/jail-monkey+2.3.4.patch, patches/react-native-haptic-feedback+1.11.0.patch, patches/react-native-hw-keyboard-event+0.0.4.patch, patches/react-native-local-auth+1.6.0.patch, patches/react-native-webview+7.0.1.patch
- Patched affected node modules minSdkVersion as suggested here: https://github.com/wix/Detox/issues/2712#issuecomment-840490767
- These were failing when running `./gradlew assembleAndroidTest` and are now passing
- I also smoke tested the app, especially the affected areas by the modules
NA
```release-note
NONE
```
=> Patch node modules minSdkVersion affected by RN 0.64.1 upgrade

detox/e2e/test/channels/channels_list.e2e.js, detox/e2e/test/messaging/message_posting.e2e.js
- Added tests for MM-T844, MM-T847, MM-T848, MM-T864, MM-T889, MM-T891 in
- `detox/e2e/test/channels/channels_list.e2e.js`
- `detox/e2e/test/messaging/message_posting.e2e.js`
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35356
Zephyr cases:
- [MM-T844](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T844)
- [MM-T847](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T847)
- [MM-T848](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T848) …
=> MM-35356 Detox/E2E: Add e2e for channels list and message posting

app/components/post_list/more_messages_button/more_messages_button.js, app/components/post_list/new_messages_divider.js, app/components/post_list/post_list.js, detox/e2e/support/server_api/channel.js, detox/e2e/support/server_api/common.js, detox/e2e/support/server_api/ldap.js, detox/e2e/support/server_api/plugin.js, detox/e2e/support/server_api/post.js, detox/e2e/support/server_api/system.js, detox/e2e/support/server_api/user.js, detox/e2e/support/ui/component/post_list.js, detox/e2e/support/ui/screen/channel.js, detox/e2e/test/channel_moderation/remove_user_from_channel.e2e.js, detox/e2e/test/messaging/mark_as_read.e2e.js, detox/e2e/test/messaging/mark_as_unread.e2e.js
- Added tests for MM-T119, MM-T120, MM-T245, MM-T258, MM-T1280 in
- `detox/e2e/test/messaging/mark_as_read.e2e.js`
- `detox/e2e/test/messaging/mark_as_unread.e2e.js`
- Added new testIDs and helper functions and some cleanup
- Renamed `apiDeleteUserFromChannel` to `apiRemoveUserFromChannel`
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35670
Zephyr cases:
- [MM-T119](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T119)
- [MM-T120](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T120)
- [MM-T245](https://mattermost.atlassian.net/projects/MM?selectedI …
=> MM-35670 Detox/E2E: Add e2e for mark post unread and read

app/components/markdown/markdown.js, app/components/markdown/markdown_block_quote.js, app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap, app/components/markdown/markdown_table/markdown_table.js, app/screens/table/index.js, detox/e2e/support/ui/component/post.js, detox/e2e/support/ui/component/post_list.js, detox/e2e/support/ui/screen/index.js, detox/e2e/support/ui/screen/long_post.js, detox/e2e/support/ui/screen/search_result_post.js, detox/e2e/support/ui/screen/table.js, detox/e2e/test/messaging/markdown_block_quote.e2e.js, detox/e2e/test/messaging/markdown_separator.e2e.js, detox/e2e/test/messaging/markdown_table.e2e.js, ios/Podfile.lock
- Added tests for MM-T190, MM-T191, MM-T195, MM-T1441, MM-T1443, MM-T1444, MM-T1445 in
- `detox/e2e/test/messaging/markdown_block_quote.e2e.js`
- `detox/e2e/test/messaging/markdown_separator.e2e.js`
- `detox/e2e/test/messaging/markdown_table.e2e.js`
- Added new screen
- `detox/e2e/support/ui/screen/table.js`
- Added new testIDs and helper variables
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35671
Zephyr cases:
- [MM-T190](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T190)
- [MM-T191](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T191)
- …
=> MM-35671 Detox/E2E: Add e2e for markdown table, separator, and block quote

detox/e2e/support/ui/component/alert.js, detox/e2e/support/ui/component/post_options.js, detox/e2e/test/messaging/message_deletion.e2e.js, detox/e2e/test/messaging/message_draft.e2e.js, detox/e2e/test/messaging/message_edit.e2e.js, detox/e2e/test/messaging/message_posting.e2e.js
- Added tests for MM-T100, MM-T101, MM-T107, MM-T108, MM-T115, MM-T116, MM-T128, MM-T151 in
- `detox/e2e/test/messaging/message_deletion.e2e.js`
- `detox/e2e/test/messaging/message_draft.e2e.js`
- `detox/e2e/test/messaging/message_edit.e2e.js`
- `detox/e2e/test/messaging/message_posting.e2e.js`
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35673
Zephyr cases:
- [MM-T100](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T100)
- [MM-T101](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T101)
- …
=> MM-35673 Detox/E2E: Add e2e for messaging

app/screens/channel_info/index.js
Fixed the warning about the `isCustomStatusEnabled` prop in the ChannelInfo screen
https://community.mattermost.com/core/pl/5w7c6hji7trjxx8gryzhakjhba
- iPhone 12 Simulator - iOS 14.4
- Android Emulator - Pixel_3a_API_30_x86 - Android 10
```release-note
NONE
```
=> Fixed custom status warning issue

.editorconfig, app/database/manager/__mocks__/index.ts, app/database/manager/index.ts, app/database/manager/test.ts, app/database/manager/test_manual.ts, app/database/operator/utils/create_test_connection.ts, app/database/operator/utils/test.ts, app/utils/database.ts
In the init process I need to know what the active server URL is. I extracted out querying of that value into `getMostRecentServerUrl` and then used that function in `getMostRecentServerDatabase` which used to be called `getMostRecentServerConnection`. There's more work to be done here (like tests and mocks) but wanted your thoughts. Regarding the term "connection" in the previous method, I'd rather use "database" as that's what is actually being returned. Regarding the term "most recent", I think we should use "active" instead, at least in the functions here. More broadly, maybe we can get rid of the `RECENTLY_VIEWED_SERVERS` and instead add some timestamp field (ie, lastViewed) to the Server model. We could then query for active server.
=> Add getMostRecentServerUrl function

app/components/post_draft/post_draft.js, app/components/post_list/post_list.tsx, app/hooks/index.ts, app/hooks/reset_native_scrollview.ts, app/screens/channel/channel.ios.js, app/screens/channel/channel_base.js, app/screens/channel/channel_post_list/channel_post_list.js
Properly reset the scrollView on iOS when the channel is switched
Fixes: https://github.com/mattermost/mattermost-server/issues/17638
```release-note
NONE
```
=> fix: reset iOS scrollView when switching channels

app/components/network_indicator/network.tsx
Connect the WebSocket when the network indicator component mounts. The first time the network component mounts the networkConnectionListener triggers and that was causing the websocket to connect the first time, but when mounting a second time the network listener did not change thus after a second mount WS was not connected.
This was very easy to reproduce by logging out and then log back in or switching servers.
Reported in community server at https://community.mattermost.com/core/pl/isu7f7zbcbfm9y9ibm8dt5rknr
```release-note
NONE
```
=> fix: connect WebSocket when the network component mounts

app/actions/websocket/index.ts, app/components/custom_status/custom_status_emoji.tsx, app/components/post_list/post/header/header.tsx, detox/e2e/test/custom_statuses/custom_status.e2e.js
- Fixed MM-36571 - RN: Custom status does not reflect changes from webapp when backgrounded
- Fixed MM-36601 - RN Custom status is not shown in right sidebar after setting custom status from webapp
- Fixed selector memoization for multiple instances of CustomStatusEmoji component
- Fixed MM-T3893 failing e2e test
- https://mattermost.atlassian.net/browse/MM-36571
- https://mattermost.atlassian.net/browse/MM-36601
- iPhone 12 Simulator - iOS 14.4
- Android Emulator - Pixel_3a_API_30_x86 - Android 10
```release-note
Fixed MM-36571 and MM-36601 issues
Fixed selector memoization for multiple instances of CustomStatusEmoji component
Fixed MM-T3893 failing e2e test
```
=> Fixed custom status issues

detox/e2e/test/messaging/pinned_messages.e2e.js, detox/e2e/test/smoke_test/search.e2e.js
- Revert back e2e because of https://github.com/mattermost/mattermost-mobile/pull/5482
NA
```release-note
NONE
```
=> Detox/E2E: Fix search and pinned messages e2e

app/components/post_list/post/body/content/embedded_bindings/index.tsx, app/components/post_list/post/body/content/index.tsx, ios/Podfile, ios/Podfile.lock
This PR adds some safety checks around post message attachments and app bindings to prevent the app from crashing when `null` is present in the post metadata for some reason.
Also includes a fix for YouTube video playback (for example this one https://www.youtube.com/watch?v=eWCXZIRm7iU&t=707). Fix taken from https://github.com/0xced/XCDYouTubeKit/issues/534
```release-note
* Prevented crash when message attachments or app bindings are `null`
* Fixed iOS YouTube video playback
```
=> Content safety

app/components/post_list/post_list.tsx
Reported in [community server](https://community.mattermost.com/core/pl/95b4s1ftkpnwdeegnba4j7ubow)
Ticket: https://mattermost.atlassian.net/browse/MM-36686
```release-note
Fixes a crash when bringing the app from the background after tapping on a DeepLink
```
=> Do not recreate onViewableItemsChange when the deeplink changes

app/components/post_list/index.ts
A race condition can cause the app to display the more messages above banner while there isn't yet a new line message indicator in the post list, that in turn has the initialIndex to be -1. If a user tries to scroll to the -1 index, FlatList will throw and error which is not really being caught.
This PR prevents the initialIndex to be less than 0 at all times.
Fixes: #5500
```release-note
NONE
```
=> Prevent the initialIndex from being less than 0

app/components/post_draft/index.js
As the Thread screen can be opened for a channel other than the current channel we should check if the channel that holds the posts in the thread is marked as readOnly instead of the current channel.
https://mattermost.atlassian.net/browse/MM-34619
```release-note
Fixes the post draft to correctly detect if the channel being viewed is read only, including when the thread view is from a different channel than the current channel.
```
=> MM-34619 post draft to use the channelId prop when assigned

patches/react-native-navigation+7.11.3.patch
Patch for the RNN library so that the Keyboard is hidden on Android when a screen is popped.
https://mattermost.atlassian.net/browse/MM-28880
```release-note
Fixes Android not being hidden when going back in the thread screen with the Keyboard is opened.
```
=> Patch RNN to dismiss keyboard when screen is popped

app/components/autocomplete/at_mention_item/at_mention_item.tsx, assets/base/i18n/en.json
https://mattermost.atlassian.net/browse/MM-32802
```release-note
Removed the nickname from the user autocomplete when the item is the current user
```
=> MM-32802 don't display nickname for current user in autocomplete
