mattermost/mattermost-mobile

- app/components/post_textbox/post_textbox.test.js
- app/components/post_textbox/post_textbox_base.js
- app/screens/channel/channel.android.js
- app/screens/channel/channel.ios.js
- app/screens/thread/thread.android.js
- app/screens/thread/thread.ios.js
Cherry pick of #3302 on release-1.24.
- #3302: Fix paste files with multiple instances of post textbox
/cc  @enahum
> Automated cherry pick of #3302

- app/components/file_attachment_list/__snapshots__/file_attachment_list.test.js.snap
- app/components/file_attachment_list/file_attachment.js
- app/components/file_attachment_list/file_attachment_list.js
- app/components/file_attachment_list/index.js
- app/components/sidebars/drawer_layout.js
- app/components/sidebars/main/__snapshots__/main_sidebar.test.js.snap
- app/components/sidebars/main/index.js
- app/components/sidebars/main/main_sidebar.js
- app/components/sidebars/settings/index.js
- app/components/sidebars/settings/settings_sidebar.js
- package-lock.json
Cherry pick of #3321 on release-1.24.
- #3321: MM-18542 Fix file attachment scroll on tablets, MM-18732 Slow
/cc  @enahum
> Automated cherry pick of #3321

- app/push_notifications/push_notifications.ios.js
- app/screens/channel/channel_nav_bar/channel_drawer_button/index.js
- app/selectors/views.js
- app/utils/push_notifications.js
https://mattermost.atlassian.net/browse/MM-18740
> MM-18740 Sync app badge number when opening a push notification

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package.json
Bump app version number to 1.23.1
> Bump app version number to 1.23.1

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 234

- app/push_notifications/push_notifications.ios.js
- app/screens/channel/channel_nav_bar/channel_drawer_button/index.js
- app/selectors/views.js
- app/utils/push_notifications.js
Cherry pick of #3322 on release-1.24.
- #3322: MM-18740 Sync app badge number when opening a push
/cc  @enahum
> Automated cherry pick of #3322

- app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
- app/screens/channel/channel_nav_bar/channel_title/channel_title.js
- app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
- app/screens/channel/channel_nav_bar/channel_title/index.js
Cherry pick of #3293 on release-1.24.
- #3293: Add (you) suffix to self DM channel title
/cc  @migbot
> Automated cherry pick of #3293

- app/components/post_body/post_body.js
> Revert long post as ScrollView instead of View

- app/components/post_body/post_body.js
Cherry pick of #3333 on release-1.24.
- #3333: Revert long post as ScrollView instead of View
/cc  @enahum
> Automated cherry pick of #3333

- app/components/network_indicator/network_indicator.js
Cherry pick of #3329 on release-1.24.
- #3329: MM-18176 Fix network indicator stock after re-connect
/cc  @enahum
> Automated cherry pick of #3329

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 235

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3338 on release-1.24.
- #3338: Bump app build number to 235
> Automated cherry pick of #3338

- app/components/autocomplete_selector/autocomplete_selector.js
- app/components/autocomplete_selector/index.js
- app/components/custom_list/option_list_row/index.js
- app/components/custom_list/option_list_row/option_list_row.js
- app/components/widgets/settings/bool_setting.js
- app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
- app/screens/interactive_dialog/__snapshots__/interactive_dialog.test.js.snap
- app/screens/interactive_dialog/dialog_element.js
- app/screens/interactive_dialog/dialog_introduction_text.js
- app/screens/interactive_dialog/dialog_introduction_text.test.js
- app/screens/interactive_dialog/interactive_dialog.js
- app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
- app/screens/selector_screen/index.js
- app/screens/selector_screen/selector_screen.js
- app/screens/selector_screen/selector_screen.test.js
Cherry pick of #3335 on release-1.24.
- #3335: MM-18464
> Automated cherry pick of #3335

- app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
- app/screens/channel/channel_nav_bar/channel_title/channel_title.js
- app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
Cherry pick of #3344 on release-1.24.
- #3344: Fix channel navbar title displayName variable
/cc  @enahum
> Automated cherry pick of #3344

- app/components/post_textbox/post_textbox_base.js
- assets/base/i18n/en.json
Update message count string.
https://mattermost.atlassian.net/browse/MM-18832
> MM-18832 Update message count string

- app/components/__snapshots__/fade.test.js.snap
- app/components/fade.js
- app/components/sidebars/main/channels_list/list/list.js
- app/components/sidebars/main/channels_list/unread_indicator/index.js
https://mattermost.atlassian.net/browse/MM-18997
> MM-18997 Fix More unread overlay preventing interactions

- app/components/__snapshots__/fade.test.js.snap
- app/components/fade.js
- app/components/sidebars/main/channels_list/list/list.js
- app/components/sidebars/main/channels_list/unread_indicator/index.js
Cherry pick of #3342 on release-1.24.
- #3342: MM-18997 Fix More unread overlay preventing interactions
/cc  @enahum
> Automated cherry pick of #3342

- app/init/fetch.js
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #3353 on release-1.24.
- #3353: Use updated react-native-keyboard-tracking-view
/cc  @migbot
> Automated cherry pick of #3353

- app/components/autocomplete/channel_mention/channel_mention.js
- app/components/autocomplete/channel_mention_item/channel_mention_item.js
- app/components/autocomplete/channel_mention_item/index.js
- app/components/sidebars/main/channels_list/channel_item/index.js
Cherry pick of #3343 on release-1.24.
- #3343: MM-18999 Fix search in: modifier to show the appropriate
/cc  @enahum
> Automated cherry pick of #3343

- app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
- app/components/sidebars/main/channels_list/channel_item/channel_item.js
Cherry pick of #3359 on release-1.24.
- #3359: Set Sidebar channel item  display name opacity as 0.6 (same
/cc  @enahum
> Automated cherry pick of #3359

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3365 on release-1.24.
- #3365: Bump app build number to 236
/cc  @enahum
> Automated cherry pick of #3365

- NOTICE.txt
Cherry pick of #3306 on release-1.24.
- #3306: Update NOTICE.txt
/cc  @amyblais
> Automated cherry pick of #3306

- .gitignore
That folder seems to just contain a bunch of build artifacts from Android Studio
> Add android/app/bin to .gitignore

- app/components/sidebars/drawer_layout.js
Cherry pick of #3385 on release-1.24.
- #3385: Fix running mm-i18n that crashes on conditional operators
/cc  @enahum
> Automated cherry pick of #3385

- app/components/file_attachment_list/__snapshots__/file_attachment.test.js.snap
- app/components/file_attachment_list/file_attachment.js
- app/components/file_attachment_list/file_attachment.test.js
Cherry pick of #3379 on release-1.24.
- #3379: Pass fileInfoContainer style directly to Touchable
/cc  @migbot
> Automated cherry pick of #3379

- app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
- app/screens/channel/channel_nav_bar/channel_title/channel_title.js
- app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
- app/screens/channel_info/__snapshots__/channel_info.test.js.snap
- app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
- app/screens/channel_info/channel_info.js
- app/screens/channel_info/channel_info.test.js
- app/screens/channel_info/channel_info_header.js
- app/screens/channel_info/channel_info_header.test.js
- app/screens/channel_info/index.js
The DMs where showing the guest label in any case where a DM has any guest, so
if you are the guest it was showing that for all the DMs, now only show you the
warning when the other user is a guest.
[MM-18939](https://mattermost.atlassian.net/browse/MM-18939)
This PR was tested on: [One Plus 5, Android 9]
> Fixing DMs guest label behavior

- app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
- app/screens/channel/channel_nav_bar/channel_title/channel_title.js
- app/screens/channel/channel_nav_bar/channel_title/channel_title.test.js
- app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
- app/screens/channel_info/channel_info.js
- app/screens/channel_info/channel_info_header.js
- app/screens/channel_info/channel_info_header.test.js
- app/screens/channel_info/index.js
* Fixing DMs guest label behavior
* Adding tests
* Addressing PR review comments
Cherry-picking PR #3383
> Fixing DMs guest label behavior (#3383)

- app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
- app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
Cherry pick of #3384 on release-1.24.
- #3384: MM-19180 - Updating spacing for mentiosn component
/cc  @asaadmahmood
> Automated cherry pick of #3384

- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Bump app build number for v1.24.0 to 237
> Bump app build number to 237

- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3395 on release-1.24.
- #3395: Bump app build number
> Automated cherry pick of #3395

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 238

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3397 on release-1.24.
- #3397: Bump app build number to 238
> Automated cherry pick of #3397

- app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
- app/screens/interactive_dialog/__snapshots__/dialog_introduction_text.test.js.snap
- app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
- app/utils/markdown.js
- package-lock.json
Cherry pick of #3372 on release-1.24.
#3372: Fixing mention text color
> Manual cherry pick of #3372

- app/components/post_header/post_header.js
Cherry pick of #3393 on release-1.24.
- #3393: Not show the guest badge for system messages
/cc  @jespino
> Automated cherry pick of #3393

- app/components/reactions/index.js
Cherry pick of #3404 on release-1.24.
- #3404: disable add reaction for read only channels
> Automated cherry pick of #3404

- patches/react-native-image-picker+0.28.1.patch
Cherry pick of #3411 on release-1.24.
- #3411: Patch react-native-image-picker
/cc  @migbot
> Automated cherry pick of #3411

- app/constants/device.js
- app/utils/general.js
Set the fallback for the haptic feedback to false.
https://mattermost.atlassian.net/browse/MM-19286
iPhone X 12.4 (Simulator) - Haptic works
iPhone 5 12.4 (Simulator) - Haptic doesn't work
iPhone 6 12.4 (Simulator) - Haptic doesn't work
*I do not have a physical device to test this on for the non-haptic support
> MM-19286 Disable Haptic Feedback

- app/constants/device.js
- app/utils/general.js
Cherry pick of #3402 on release-1.24.
- #3402: MM-19286 Disable Haptic Feedback
> Automated cherry pick of #3402

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 239

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3421 on release-1.24.
- #3421: Bump app build number to 239
> Automated cherry pick of #3421

- Makefile
- ios/Mattermost/Info.plist
> Fix building unsigned apps

- Makefile
- ios/Mattermost/Info.plist
Cherry pick of #3430 on release-1.25.
- #3430: unsigned
/cc  @enahum
> Automated cherry pick of #3430

- app/screens/search/search.js
Cherry pick of #3356 on release-1.25.
- #3356: only focus search box when we enter through the search icon
> Automated cherry pick of #3356

- app/store/store.js
- ios/MattermostShare/ShareViewController.swift
- ios/UploadAttachments/UploadAttachments/StoreManager.m
- ios/UploadAttachments/UploadAttachments/UploadSession.swift
Cherry pick of #3375 on release-1.25.
- #3375: MM-17157 Only send notification receipt if server url and
/cc  @enahum
> Automated cherry pick of #3375

- app/screens/flagged_posts/__snapshots__/flagged_posts.test.js.snap
- app/screens/flagged_posts/flagged_posts.js
- app/screens/flagged_posts/flagged_posts.test.js
- app/screens/recent_mentions/__snapshots__/recent_mentions.test.js.snap
- app/screens/recent_mentions/recent_mentions.js
- app/screens/recent_mentions/recent_mentions.test.js
Cherry pick of #3362 on release-1.25.
- #3362: Add unit tests
/cc  @migbot
> Automated cherry pick of #3362

- app/components/post/index.js
- app/components/post/post.js
- app/components/post_header/post_header.js
- app/components/post_list/post_list.js
Cherry pick of #3351 on release-1.25.
- #3351: MM-18054:
> Automated cherry pick of #3351

- app/screens/sso/index.js
- app/screens/sso/sso.js
Cherry pick of #3346 on release-1.25.
- #3346: MM-18935
> Automated cherry pick of #3346

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package.json
Bump app version number to 1.25.0
> Bump app version number to 1.25.0

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 240

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3443 on release-1.25.
- #3443: Bump app build number to 240
> Automated cherry pick of #3443

- app/components/safe_area_view/__snapshots__/safe_area_view.ios.test.js.snap
- app/components/safe_area_view/safe_area_view.ios.js
- app/components/safe_area_view/safe_area_view.ios.test.js
- app/screens/permalink/index.js
- app/screens/permalink/permalink.js
- app/screens/permalink/permalink.test.js
Manual cherry pick of https://github.com/mattermost/mattermost-mobile/pull/3413 on release-1.25.
https://github.com/mattermost/mattermost-mobile/pull/3413: Listen to safeAreaInsetsForRootViewDidChange over Dimension change
> Manual cherry pick of #3413

- app/screens/settings/notification_settings_auto_responder/notification_settings_auto_responder.js
Cherry pick of #3380 on release-1.25.
- #3380: MM-18790 Fix Keyboard Color Flash
> Automated cherry pick of #3380

- package-lock.json
- package.json
Pulling the changes from https://github.com/mattermost/mattermost-redux/pull/950 into the mobile app
https://mattermost.atlassian.net/browse/MM-19493
> MM-19493 For manually unread channel, don't mark as read on new message

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3467 on release-1.25.
- #3467: Bump app build number to 241
/cc  @enahum
> Automated cherry pick of #3467

- app/components/safe_area_view/safe_area_view.ios.js
- app/components/safe_area_view/safe_area_view.ios.test.js
- app/constants/view.js
- app/store/ephemeral_store.js
Cherry pick of #3457 on release-1.25.
- #3457: Store insets in ephemeral store
/cc  @migbot
> Automated cherry pick of #3457

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Fixes an issue with a bad cherry-pick from #3465
> Fix Android senderName call

- app/actions/views/login.js
- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
- app/screens/settings/timezone/timezone.js
- app/utils/timezone.js
- package-lock.json
- package.json
Fixes automatic timezone selection by updating react-native-device-info and modifying getting the values from a constant to a function that returns it as a promise.
https://mattermost.atlassian.net/browse/MM-18313
> MM-18313 Fix update timezone automatically

- app/actions/views/login.js
- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
- app/screens/settings/timezone/timezone.js
- app/utils/timezone.js
- package-lock.json
- package.json
Cherry pick of #3462 on release-1.25.
- #3462: MM-18313 Fix update timezone automatically
/cc  @enahum
> Automated cherry pick of #3462

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
mark-as-unread branch version of https://github.com/mattermost/mattermost-mobile/pull/3469
> Fix android senderName call (mark-as-unread)

- .circleci/config.yml
Cherry pick of #3474 on release-1.25.
- #3474: Fix app deploy path
/cc  @enahum
> Automated cherry pick of #3474

- .circleci/config.yml
- fastlane/Fastfile
Cherry pick of #3476 on release-1.25.
- #3476: Fix android and iOS deployment on circleCI
/cc  @enahum
> Automated cherry pick of #3476

- app/components/radio_button/radio_button_group.js
- app/screens/settings/notification_settings/notification_settings.js
- app/screens/settings/notification_settings_email/index.js
- app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
- app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
- app/screens/settings/notification_settings_email/notification_settings_email_base.js
- app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js
Cherry pick of #3357 on release-1.25.
- #3357: Map currentUser from state to props
/cc  @migbot
> Automated cherry pick of #3357

- patches/react-native+0.59.9.patch
Cherry pick of #3481 on release-1.25.
- #3481: MM-19734 Patch RN to remove the placeholder for emojis in a
/cc  @enahum
> Automated cherry pick of #3481

- ios/Mattermost.xcodeproj/project.pbxproj
Accidentally removed SwimeProxy when I merged the RN 61 changes.
> Add SwimeProxy to Compile Sources

- app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap
- app/screens/settings/notification_settings/notification_settings.js
- app/screens/settings/notification_settings/notification_settings.test.js
Cherry pick of #3482 on release-1.25.
- #3482: Include previous notify props when saving new ones
/cc  @migbot
> Automated cherry pick of #3482

- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/post_header/post_header.js
- app/components/post_header/post_header.test.js
Cherry pick of #3445 on release-1.25.
- #3445: MM-19308 Fixed date wrapping
> Automated cherry pick of #3445

- package-lock.json
- package.json
> Manual Cherrypick of #3493

- app/components/message_attachments/attachment_image/__snapshots__/index.test.js.snap
- app/components/message_attachments/attachment_image/index.js
- app/components/progressive_image/progressive_image.js
Manual cherrypick of 3466 for 1.25 release.
> Cherrypick for #3466 into 1.25 release

- .circleci/config.yml
Cherry pick of #3503 on release-1.25.
- #3503: circleCI change persist root from / to ~/
/cc  @enahum
> Automated cherry pick of #3503

- .circleci/config.yml
Cherry pick of #3506 on release-1.25.
- #3506: deploy-to-store job attach_workspace in home directory
/cc  @enahum
> Automated cherry pick of #3506

- app/initial_state.js
- app/screens/select_server/select_server.js
Cherry pick of #3513 on release-1.25.
- #3513: MM-19853 Fix iOS SafeAreaView for Server URL screen
/cc  @enahum
> Automated cherry pick of #3513

- app/store/store.js
- package-lock.json
- package.json
> Manual cherry-pick of #3519

- app/push_notifications/push_notifications.ios.js
- app/utils/push_notifications.test.js
Cherry pick of #3527 on release-1.25.
- #3527: Call getInitialNotification on configure
/cc  @migbot
> Automated cherry pick of #3527

- app/utils/push_notifications.js
Cherry pick of #3531 on release-1.25.
- #3531: MM-19812 Properly handle in-app update_badge notifications
/cc  @hmhealey
> Automated cherry pick of #3531

- app/screens/settings/notification_settings/notification_settings.js
- app/screens/settings/notification_settings/notification_settings.test.js
Cherry pick of #3535 on release-1.25.
- #3535: MM-19966 Fixed Notification Settings
> Automated cherry pick of #3535

- app/actions/views/channel.js
- app/actions/views/channel.test.js
- app/actions/views/root.js
- app/screens/notification/__snapshots__/notification.test.js.snap
- app/screens/notification/notification.test.js
- app/utils/push_notifications.js
> Manual cherry-pick of #3533

- package-lock.json
- package.json
Updates mattermost-redux to https://github.com/mattermost/mattermost-redux/pull/985 and includes `util` as a dev dependency to be able to build the app.
https://mattermost.atlassian.net/browse/MM-19961
> MM-19961 Sync persisted channels with the ones returned by the server

- app/components/autocomplete_selector/autocomplete_selector.js
- app/components/message_attachments/action_button/action_button.js
- app/components/message_attachments/action_menu/action_menu.js
- app/components/message_attachments/action_menu/action_menu.test.js
- app/components/message_attachments/attachment_actions.js
- package-lock.json
Adds ability to disable slack attachment action buttons and fields.
https://mattermost.atlassian.net/browse/MM-19517
Tested on Android 9, OnePlus 5
> Adding ability to disable attachment buttons and fields.

- app/push_notifications/push_notifications.ios.js
- ios/NotificationService/NotificationService.swift
- ios/UploadAttachments/UploadAttachments/UploadSession.swift
Fetch ID loaded push notification from server to add missing fields to `bestAttemptContent`.
https://mattermost.atlassian.net/browse/MM-16232
> [MM-16232] iOS: Fetch id-loaded push notification from server

- app/components/sidebars/main/teams_list/teams_list.js
https://mattermost.atlassian.net/browse/MM-19600
> MM-19600 Align Sidebar separator line between Teams and Channel view

- app/components/post/post.js
- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/post_header/post_header.js
- app/components/post_header/post_header.test.js
Added check for prev post to stop the "Commented on" line when in same thread.
https://mattermost.atlassian.net/browse/MM-18054
Android Pixel 29 API (Simulator)
> MM-18054 Checked for prev post comment line

- app/components/autocomplete/autocomplete_section_header.js
- app/components/custom_list/__snapshots__/index.test.js.snap
- app/components/custom_list/index.js
- app/components/edit_channel_info/edit_channel_info.js
- app/components/emoji_picker/emoji_picker_base.js
- app/components/load_more_posts/load_more_posts.js
- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/components/post_list/post_list.js
- app/screens/channel/channel_base.js
- app/screens/channel_add_members/channel_add_members.js
- app/screens/channel_members/channel_members.js
- app/screens/edit_post/edit_post.js
- app/screens/edit_profile/edit_profile.js
- app/screens/error_teams_list/error_teams_list.js
- app/screens/more_channels/more_channels.js
- app/screens/more_dms/more_dms.js
- app/screens/permalink/__snapshots__/permalink.test.js.snap
- app/screens/permalink/permalink.js
- app/screens/search/search.js
- app/screens/select_team/__snapshots__/select_team.test.js.snap
- app/screens/select_team/select_team.js
- app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
- app/screens/terms_of_service/terms_of_service.js
- app/screens/thread/__snapshots__/thread.ios.test.js.snap
- app/screens/thread/thread.android.js
- app/screens/thread/thread.ios.js
- app/screens/thread/thread_base.js
Sets activity indicator color to centerChannelColor to play well with themes
https://mattermost.atlassian.net/browse/MM-19993
> MM-19993 Fix Channel spinner is black on dark theme

- app/components/autocomplete/autocomplete_section_header.js
- app/components/custom_list/__snapshots__/index.test.js.snap
- app/components/custom_list/index.js
- app/components/edit_channel_info/edit_channel_info.js
- app/components/emoji_picker/emoji_picker_base.js
- app/components/load_more_posts/load_more_posts.js
- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/components/post_list/post_list.js
- app/screens/channel/channel_base.js
- app/screens/channel_add_members/channel_add_members.js
- app/screens/channel_members/channel_members.js
- app/screens/edit_post/edit_post.js
- app/screens/edit_profile/edit_profile.js
- app/screens/error_teams_list/error_teams_list.js
- app/screens/more_channels/more_channels.js
- app/screens/more_dms/more_dms.js
- app/screens/permalink/__snapshots__/permalink.test.js.snap
- app/screens/permalink/permalink.js
- app/screens/search/search.js
- app/screens/select_team/__snapshots__/select_team.test.js.snap
- app/screens/select_team/select_team.js
- app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
- app/screens/terms_of_service/terms_of_service.js
- app/screens/thread/__snapshots__/thread.ios.test.js.snap
- app/screens/thread/thread.android.js
- app/screens/thread/thread.ios.js
- app/screens/thread/thread_base.js
Cherry pick of #3558 on release-1.26.
- #3558: MM-19993 Fix Channel spinner is black on dark theme
/cc  @enahum
> Automated cherry pick of #3558

- app/screens/more_channels/__snapshots__/more_channels.test.js.snap
- app/screens/more_channels/more_channels.js
Cherry pick of #3565 on release-1.26.
- #3565: Fix theme color for the more channel options
/cc  @enahum
> Automated cherry pick of #3565

- app/components/message_attachments/attachment_thumbnail.js
- app/components/progressive_image/progressive_image.js
- app/screens/image_preview/image_preview.js
- package-lock.json
Cherry pick of #3563 on release-1.26.
- #3563: MM-20007 Fix app crashes when previewing some gif files
/cc  @enahum
> Automated cherry pick of #3563

- app/components/autocomplete/channel_mention_item/index.js
- app/selectors/autocomplete.js
Cherry pick of #3561 on release-1.26.
- #3561: MM-19991 Filtering search by channel should also show the
/cc  @enahum
> Automated cherry pick of #3561

- .circleci/config.yml
- Makefile
- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
- app/push_notifications/push_notifications.ios.js
- ios/NotificationService/NotificationService.swift
- ios/UploadAttachments/UploadAttachments/UploadSession.swift
- patches/react-native-notifications+2.0.6.patch
Cherry pick of #3562 on release-1.26.
- #3562: Android: Fetch notification in
/cc  @migbot
> Automated cherry pick of #3562

- .circleci/config.yml
Cherry pick of #3574 on release-1.26.
- #3574: Fix CircleCI iOS build by adding watchman
/cc  @enahum
> Automated cherry pick of #3574

- app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
- app/components/markdown/markdown_table/index.js
- app/components/markdown/markdown_table/markdown_table.js
- app/components/markdown/markdown_table/markdown_table.test.js
Cherry pick of #3571 on release-1.26.
- #3571: Preview markdown table as 5x5 max
/cc  @migbot
> Automated cherry pick of #3571

- ios/MattermostShare/ShareViewController.swift
Cherry pick of #3579 on release-1.26.
- #3579: Avoid OOM crash on iOS13 Share Extension
/cc  @enahum
> Automated cherry pick of #3579

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Create notification channels only for Android O and above.
https://mattermost.atlassian.net/browse/MM-20640
* Android emulator, 7.0
> [MM-20640] Create notification channels only if supported

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Cherry pick of #3590 on release-1.25.
- #3590: Create notification channels only if supported
/cc  @migbot
> Automated cherry pick of #3590

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
- ios/NotificationService/NotificationService.swift
- ios/UploadAttachments/UploadAttachments/UploadSession.swift
Handles the new flag for ID loaded push notifications on Android and iOS
https://mattermost.atlassian.net/browse/MM-20347
> MM-20347 Handle Flag for ID Loaded Push Notifications

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
- ios/NotificationService/NotificationService.swift
- ios/UploadAttachments/UploadAttachments/UploadSession.swift
Cherry pick of #3586 on release-1.26.
- #3586: Fix id-loaded on Android
/cc  @enahum
> Automated cherry pick of #3586

- app/screens/edit_profile/edit_profile.js
Added optional prop to the Nickname and Position field, which removes the asterisk
https://mattermost.atlassian.net/browse/MM-20201
This PR was tested on: iPhone X 13.2 (Simulator)
> MM-20201 Fixed asterisk on Nickname

- app/screens/edit_profile/edit_profile.js
Cherry pick of #3588 on release-1.26.
- #3588: MM-20201 Fixed asterisk on Nickname
> Automated cherry pick of #3588

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package.json
Cherry pick of #3601 on release-1.26.
- #3601: Bump app build number to 248
/cc  @enahum
> Automated cherry pick of #3601

- app/screens/image_preview/video_preview.js
Refs were not updated correctly due to a bad merge. This fixes them.
> Fix video player refs

- app/screens/image_preview/video_preview.js
Cherry pick of #3604 on release-1.26.
- #3604: Fix video player refs
/cc  @migbot
> Automated cherry pick of #3604

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
- app/components/at_mention/at_mention.test.js
- app/components/at_mention/index.js
Cherry pick of #3572 on release-1.26.
- #3572: MM-19834 Fixed direct mentions highlight color
> Automated cherry pick of #3572

- assets/base/release/splash_screen/android/layout/launch_screen.xml
Cherry pick of #3609 on release-1.26.
- #3609: Android release launch screen
/cc  @enahum
> Automated cherry pick of #3609

- app/mattermost.js
- app/store/utils.js
- app/utils/push_notifications.js
Fixes a race condition that causes the app to open in the default channel of the default team.
https://mattermost.atlassian.net/browse/MM-20694
> MM-20694 Fix race condition when the store has not rehydrated

- app/mattermost.js
- app/store/utils.js
- app/utils/push_notifications.js
Cherry pick of #3610 on release-1.26.
- #3610: MM-20694 Fix race condition when the store has not
/cc  @enahum
> Automated cherry pick of #3610

- app/components/autocomplete/autocomplete.js
- app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
- app/components/edit_channel_info/edit_channel_info.js
- app/components/edit_channel_info/edit_channel_info.test.js
Cherry pick of #3595 on release-1.26.
- #3595: Fix autocomplete when editing channel header
/cc  @migbot
> Automated cherry pick of #3595

- app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
- app/components/markdown/markdown_table/markdown_table.js
MM-20326 - Updating markdown table css
https://mattermost.atlassian.net/browse/MM-20326
This PR was tested on: Nexus 6P API 25
> MM-20326 - Updating markdown table css

- app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
- app/components/markdown/markdown_table/markdown_table.js
Cherry pick of #3608 on release-1.26.
- #3608: MM-20326 - Updating markdown table css
/cc  @asaadmahmood
> Automated cherry pick of #3608

- app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
- app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.ios.test.js.snap
- app/screens/settings/notification_settings_email/index.js
- app/screens/settings/notification_settings_email/notification_settings_email.android.js
- app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
- app/screens/settings/notification_settings_email/notification_settings_email.ios.js
- app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
- app/screens/settings/notification_settings_email/notification_settings_email_base.js
- assets/base/i18n/en.json
- package-lock.json
Update to email notifications helper text
https://mattermost.atlassian.net/browse/MM-19896
Has webapp changes (https://github.com/mattermost/mattermost-webapp/pull/4349)
> MM-19896 Correct helper text on Email Notifications

- app/screens/long_post/__snapshots__/long_post.test.js.snap
- app/screens/long_post/index.js
- app/screens/long_post/long_post.js
Removed file previews from long posts and use the available space
https://mattermost.atlassian.net/browse/MM-20689
> MM-20689 Long post to use all available space

- app/screens/long_post/__snapshots__/long_post.test.js.snap
- app/screens/long_post/index.js
- app/screens/long_post/long_post.js
Cherry pick of #3623 on release-1.26.
- #3623: MM-20689 Long post to use all available space
/cc  @enahum
> Automated cherry pick of #3623

- app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
- app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.ios.test.js.snap
- app/screens/settings/notification_settings_email/index.js
- app/screens/settings/notification_settings_email/notification_settings_email.android.js
- app/screens/settings/notification_settings_email/notification_settings_email.android.test.js
- app/screens/settings/notification_settings_email/notification_settings_email.ios.js
- app/screens/settings/notification_settings_email/notification_settings_email.ios.test.js
- app/screens/settings/notification_settings_email/notification_settings_email_base.js
- assets/base/i18n/en.json
- package-lock.json
Cherry pick of #3614 on release-1.26.
- #3614: MM-19896 Correct helper text on Email Notifications
/cc  @enahum
> Automated cherry pick of #3614

- app/screens/image_preview/image_preview.js
- app/screens/image_preview/image_preview.test.js
Cherry pick of #3618 on release-1.26.
- #3618: Use bottom sheet over modal
/cc  @migbot
> Automated cherry pick of #3618

- NOTICE.txt
Cherry pick of #3607 on release-1.26.
- #3607: Update NOTICE.txt
/cc  @amyblais
> Automated cherry pick of #3607

- app/screens/terms_of_service/terms_of_service.js
- app/screens/terms_of_service/terms_of_service.test.js
With the new navigation updates we just need to log the user out without dismissing any modals
https://mattermost.atlassian.net/browse/MM-19990
> MM-19990 Prevent glimpse of the app if TOS not accepted

- app/screens/post_options/__snapshots__/post_options.test.js.snap
- app/screens/post_options/post_options.js
- assets/base/i18n/en.json
Just a simple text update
https://mattermost.atlassian.net/browse/MM-20228
> MM-20228 Update Mark as Unread menu option text

- app/screens/post_options/__snapshots__/post_options.test.js.snap
- app/screens/post_options/post_options.js
- assets/base/i18n/en.json
Cherry pick of #3634 on release-1.26.
- #3634: MM-20228 Update Mark as Unread menu option text
/cc  @hmhealey
> Automated cherry pick of #3634

- app/actions/views/channel.js
- app/components/custom_list/__snapshots__/index.test.js.snap
- app/components/custom_list/index.js
- app/components/custom_list/index.test.js
- app/screens/channel_members/__snapshots__/channel_members.test.js.snap
- app/screens/more_channels/__snapshots__/more_channels.test.js.snap
- app/screens/more_channels/index.js
- app/screens/more_channels/more_channels.js
- app/screens/more_channels/more_channels.test.js
- app/screens/select_team/__snapshots__/select_team.test.js.snap
- app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
The new feature that allows a user to search for archived channels was showing the option to display archived channels even if the setting was turned off on the server. Also public channels was not filtering out the ones that were archived.
https://mattermost.atlassian.net/browse/MM-20758
https://mattermost.atlassian.net/browse/MM-20762
> MM-20758 MM-20762 Fix archived channels in more channels screen

- app/actions/views/channel.js
- app/components/custom_list/__snapshots__/index.test.js.snap
- app/components/custom_list/index.js
- app/components/custom_list/index.test.js
- app/screens/channel_members/__snapshots__/channel_members.test.js.snap
- app/screens/more_channels/__snapshots__/more_channels.test.js.snap
- app/screens/more_channels/index.js
- app/screens/more_channels/more_channels.js
- app/screens/more_channels/more_channels.test.js
- app/screens/select_team/__snapshots__/select_team.test.js.snap
- app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
Cherry pick of #3635 on release-1.26.
- #3635: MM-20758 MM-20762 Fix archived channels in more channels
/cc  @enahum
> Automated cherry pick of #3635

- app/init/credentials.js
Details in Jira
https://mattermost.atlassian.net/browse/MM-20789
> MM-20789 Enfroce SECURE_SOFTWARE

- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
Details on the ticket
https://mattermost.atlassian.net/browse/MM-20779
> MM-20779 Handle Android notification reply with special characters

- app/init/credentials.js
Cherry pick of #3637 on release-1.26.
- #3637: MM-20789 Enforce SECURE_SOFTWARE
/cc  @enahum
> Automated cherry pick of #3637

- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
Cherry pick of #3636 on release-1.26.
- #3636: MM-20779 Handle Android notification reply with special
/cc  @enahum
> Automated cherry pick of #3636

- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
Remove extra data from logs
Based of #3636 
https://mattermost.atlassian.net/browse/MM-20806
> MM-20806 Remove extra info from logs

- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
Cherry pick of #3644 on release-1.26.
- #3644: MM-20779 Handle Android notification reply with special
/cc  @enahum
> Automated cherry pick of #3644

- package-lock.json
- package.json
Updates the redux hash to match latest redux hash for member role redux changes
https://mattermost.atlassian.net/browse/MM-20164
> WIP: [MM-20164] Update Redux hash for member role changing

- package-lock.json
- package.json
Cherry pick of https://github.com/mattermost/mattermost-mobile/pull/3650 on release-1.26.
> Cherry Pick of #3650

- app/screens/image_preview/downloader.android.js
- app/utils/file.js
- app/utils/file.test.js
See ticket for details
https://mattermost.atlassian.net/browse/MM-20778
> MM-20778 Remove caption as part of the file path

- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
- app/screens/sso/sso.js
- app/utils/file.js
- test/setup.js
See tickets for description
https://mattermost.atlassian.net/browse/MM-20780
https://mattermost.atlassian.net/browse/MM-20782
> MM-20780 MM-20782 Clear cookies on logout

- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
- app/screens/sso/sso.js
- app/utils/file.js
- test/setup.js
Cherry pick of #3645 on release-1.26.
- #3645: MM-20780 MM-20782 Clear cookies on logout
/cc  @enahum
> Automated cherry pick of #3645

- app/screens/image_preview/downloader.android.js
- app/utils/file.js
- app/utils/file.test.js
Cherry pick of #3646 on release-1.26.
- #3646: MM-20778 Remove caption as part of the file path
/cc  @enahum
> Automated cherry pick of #3646

- app/init/global_event_handler.js
- app/screens/sso/sso.js
Cherry pick of #3657 on release-1.26.
- #3657: Fix SSO login on iOS
/cc  @enahum
> Automated cherry pick of #3657

- app/screens/post_options/index.js
- app/screens/post_options/index.test.js
- app/screens/post_options/post_options.js
- app/screens/post_options/post_options.test.js
Cherry pick of #3655 on release-1.26.
- #3655: MM-20790 Mark as Unread option should not be available on
> Automated cherry pick of #3655

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3659 on release-1.26.
- #3659: Bump app build number to 249
/cc  @enahum
> Automated cherry pick of #3659

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Cherry pick of #3668 on release-1.26.
- #3668: Set number to 0 only if null
/cc  @migbot
> Automated cherry pick of #3668

- app/components/autocomplete/autocomplete.js
- app/screens/edit_post/edit_post.js
Cherry pick of #3665 on release-1.26.
- #3665: Show autocomplete view only when there are children
/cc  @migbot
> Automated cherry pick of #3665

- app/mattermost.js
- app/store/utils.js
Cherry pick of #3667 on release-1.26.
- #3667: Pass callback to waitForHydration
/cc  @migbot
> Automated cherry pick of #3667

- app/screens/code/index.js
https://mattermost.atlassian.net/browse/MM-20875
> MM-20875 migrate code screen to realm

- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
Cherry pick of #3673 on release-1.26.
- #3673: Add channel ID to push notification sent on failed reply
/cc  @migbot
> Automated cherry pick of #3673

- app/store/utils.js
Updated the hydration of the store to first check if it completed as this was being caused due to a race condition.
https://mattermost.atlassian.net/browse/MM-21085
Android Pixel 2 API 29 Simulator
> MM-21085 Updated waitHydration

- app/store/utils.js
Cherry pick of #3677 on release-1.26.
- #3677: MM-21085 Updated waitHydration
> Automated cherry pick of #3677

- app/components/emoji/emoji.js
- app/components/reactions/reaction.js
Added margin to custom emoji style to match native emoji.
https://mattermost.atlassian.net/browse/MM-21062
Android Pixel 2 API 29 Simulator
> MM-21062 Added margin to custom Emoji

- app/components/emoji/emoji.js
- app/components/reactions/reaction.js
Cherry pick of #3682 on release-1.26.
- #3682: MM-21062 Added margin to custom Emoji
> Automated cherry pick of #3682

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3684 on release-1.26.
- #3684: Bump app build number to 250
/cc  @enahum
> Automated cherry pick of #3684

- .circleci/config.yml
Cherry pick of #3689 on release-1.26.
- #3689: Use ruby 2.6.3 on circleCI
/cc  @enahum
> Automated cherry pick of #3689

- .circleci/config.yml
Cherry pick of #3691 on release-1.26.
- #3691: Set up Ruby step
/cc  @enahum
> Automated cherry pick of #3691

- app/components/post/index.js
- app/components/post/post.js
- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/post_header/post_header.js
Restructured the check for the previous post to make sure comment line does not appear for posts on same thread, but from different users.
https://mattermost.atlassian.net/browse/MM-18054
Android Pixel 2 API 29 Simulator
> MM-18054 Fix Comment Line showing

- app/components/post/index.js
- app/components/post/post.js
- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/post_header/post_header.js
CherryPick for 1.26
Auto cherrypick failed
> MM-18054 CherryPick for 1.26

- package-lock.json
- package.json
See https://github.com/mattermost/mattermost-redux/pull/1013
https://mattermost.atlassian.net/browse/MM-21153
> MM-21153 Count mentions in DM channels using mention_count

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3703 on release-1.26.
- #3703: Bump app build number to 251
/cc  @enahum
> Automated cherry pick of #3703

- app/selectors/views.js
- package-lock.json
- package.json
Redux PR: https://github.com/mattermost/mattermost-redux/pull/1015/commits
https://mattermost.atlassian.net/browse/MM-21153
> Fix Hamburger and iOS App Icon badge number when marking channel as unread

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3706 on release-1.26.
- #3706: Bump app build number to 252
/cc  @enahum
> Automated cherry pick of #3706

- app/init/fetch.js
- app/screens/select_team/index.js
- app/screens/select_team/select_team.js
- app/screens/select_team/select_team.test.js
- package-lock.json
- package.json
Fixing team join without the invite id
[MM-21270](https://mattermost.atlassian.net/browse/MM-21270)
> [MM-21270] Fixing team join without the invite id

- app/init/fetch.js
- app/screens/select_team/index.js
- app/screens/select_team/select_team.js
- app/screens/select_team/select_team.test.js
- package-lock.json
- package.json
> [MM-21270] Fixing team join without the invite id (#3710)

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3713 on release-1.26.
- #3713: Bump app build number to 253
/cc  @migbot
> Automated cherry pick of #3713

- app/components/__snapshots__/send_button.test.js.snap
- app/components/attachment_button/index.js
- app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
- app/components/post_textbox/post_textbox_base.js
- app/components/send_button.js
Cherry pick of #3631 on release-1.27.
- #3631: MM-19920 MM-19924 Fix mis-align post input field attach and
/cc  @enahum
> Automated cherry pick of #3631

- app/components/post_textbox/post_textbox.test.js
- app/components/post_textbox/post_textbox_base.js
Cherry pick of #3695 on release-1.27.
- #3695: MM-21176 Preserve text on input if command fails
/cc  @enahum
> Automated cherry pick of #3695

- app/components/sidebars/settings/settings_sidebar.js
Cherry pick of #3628 on release-1.27.
- #3628: MM-20682 Android back button to dismiss status modal first
/cc  @enahum
> Automated cherry pick of #3628

- app/components/combined_system_message/combined_system_message.js
- app/components/formatted_markdown_text.js
- app/components/markdown/markdown.js
Cherry pick of #3640 on release-1.27.
- #3640: MM-19837 Remove Opacity from AtMention Markdown
> Automated cherry pick of #3640

- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/post_header/index.js
- app/components/post_header/post_header.js
- app/components/post_header/post_header.test.js
> MM-19708 Adjusted display name width to 80% for landscape

- app/screens/terms_of_service/terms_of_service.js
- app/screens/terms_of_service/terms_of_service.test.js
Cherry pick of #3617 on release-1.27.
- #3617: MM-19990 Prevent glimpse of the app if TOS not accepted
/cc  @enahum
> Automated cherry pick of #3617

- package-lock.json
- package.json
Manual cherry pick of #3720
* Upgrades jsc-android
> Manual cherry pick of #3720

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package.json
Cherry pick of #3730 on release-1.26.
- #3730: Bump app version number to 1.26.1
/cc  @migbot
> Automated cherry pick of #3730

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3733 on release-1.26.
- #3733: Bump app build number to 254
/cc  @migbot
> Automated cherry pick of #3733

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3741 on release-1.26.
- #3741: Bump app build number to 255
/cc  @migbot
> Automated cherry pick of #3741

- patches/react-native+0.61.2.patch
Cherry pick of #3746 on release-1.26.
- #3746: Fix RN patch for CBA support
/cc  @enahum
> Automated cherry pick of #3746

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3749 on release-1.26.
- #3749: Bump app build number to 256
/cc  @enahum
> Automated cherry pick of #3749

- CHANGELOG.md
@enahum Can I ask your help to list all the issues fixed in v1.26.1? We don't have Jira tickets for all of them so it's harder to keep track.
> v1.26.1 Changelog

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package.json
Cherry pick of #3763 on release-1.27.
- #3763: Bump app version number to 1.27.0
/cc  @migbot
> Automated cherry pick of #3763

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3764 on release-1.27.
- #3764: Bump app build number to 257
/cc  @migbot
> Automated cherry pick of #3764

- android/app/build.gradle
Cherry pick of #3769 on release-1.27.
- #3769: Upgrade to firebase-messaging v17.3.2
/cc  @migbot
> Automated cherry pick of #3769

- app/screens/edit_profile/edit_profile.js
- assets/base/i18n/en.json
Updated verbiage for profile image error
https://mattermost.atlassian.net/browse/MM-20949
Android Pixel 2 API 29 Simulator
> MM-20949 Updated verbiage for profile image error

- app/screens/about/about.js
- app/screens/about/index.js
Realm migration for the About screen.
https://mattermost.atlassian.net/browse/MM-20871
> Realm migration for About Screen

- app/init/fetch.js
- app/init/fetch.test.js
Cherry pick of #3790 on release-1.27.
- #3790: Handle lower case headers
/cc  @migbot
> Automated cherry pick of #3790

- app/screens/edit_profile/edit_profile.js
- assets/base/i18n/en.json
Cherry pick of #3768 on release-1.27.
- #3768: MM-20949 Updated verbiage for profile image error
> Automated cherry pick of #3768

- app/store/store.js
- ios/UploadAttachments/UploadAttachments/UploadSession.swift
Cherry pick of #3792 on release-1.27.
- #3792: Fix iOS Share extension alert message when file size is
/cc  @enahum
> Automated cherry pick of #3792

- app/components/no_results.js
- app/screens/flagged_posts/__snapshots__/flagged_posts.test.js.snap
- app/screens/flagged_posts/flagged_posts.js
- app/screens/flagged_posts/flagged_posts.test.js
- app/screens/flagged_posts/index.js
- app/screens/pinned_posts/__snapshots__/pinned_posts.test.js.snap
- app/screens/pinned_posts/index.js
- app/screens/pinned_posts/pinned_posts.js
- app/screens/pinned_posts/pinned_posts.test.js
- app/screens/recent_mentions/__snapshots__/recent_mentions.test.js.snap
- app/screens/recent_mentions/index.js
- app/screens/recent_mentions/recent_mentions.js
- app/screens/recent_mentions/recent_mentions.test.js
- app/screens/search/index.js
- app/screens/search/search.js
Remove search unused status flags - requests.search
one part to close mattermost/mattermost-server#12522
that https://github.com/mattermost/mattermost-redux/pull/1026 depends on this PR
> MM-18900 - Remove search unused status flags

- app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
- app/screens/channel_info/channel_info_header.js
Removed Markdown from Purpose on Channel Info
https://mattermost.atlassian.net/browse/MM-17083
This PR was tested on: iPhone X 12.2
> [MM-17083] Removed Markdown from Purpose on Channel Info

- app/components/post_list/post_list.js
Cherry pick of #3786 on release-1.27.
- #3786: MM-21230 Added check for first post
> Automated cherry pick of #3786

- app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
- app/components/progressive_image/progressive_image.test.js
Unit tests for Image loader
https://mattermost.atlassian.net/browse/MM-20625
This PR was tested on: iPhone X Simulator 12.2
> MM-20625 Unit Tests

- app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
- app/components/progressive_image/progressive_image.test.js
Cherry pick of #3787 on release-1.27.
- #3787: MM-20625 Unit Tests
> Automated cherry pick of #3787

- app/components/markdown/markdown_link/markdown_link.js
- app/components/post_list/post_list.js
- app/components/post_list/post_list.test.js
- app/utils/url.js
- app/utils/url.test.js
- assets/base/i18n/en.json
- fastlane/Fastfile
Deep links now need to have the server (or site) URL as a part of the request. An absent or incorrect URL throws up an alert popup stating that the link was incorrect.
**Old (only worked without serverURL or siteURL)**
Beta
* `mattermost-beta://<teamname>/channels/<channelname>`
* `mattermost-beta://<teamname>/pl/<permalinkID>`
Release
* `mattermost-mobile://<teamname>/channels/<channelname>`
* `mattermost-mobile://<teamname>/pl/<permalinkID>`
**New working deep link patterns**
Note: Transport protocol (http, https, etc.) is optional.
Beta
* `mattermost-beta://<server-or-site-URL><teamname>/channels/<channelname>`
* `mattermost-beta://<server-or-site-URL><teamname>/pl/<permalinkID>`
* `mattermost-beta://https://<server-or-site-URL><teamname>/channels/<channelname>`
* …
> [MM-21369] Require server/site URL for deep links

- app/components/__snapshots__/formatted_time.test.js.snap
- app/components/__snapshots__/swiper.test.js.snap
- app/components/edit_channel_info/__snapshots__/edit_channel_info.test.js.snap
- app/components/formatted_time.js
- app/components/formatted_time.test.js
- app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/screens/channel_info/__snapshots__/channel_info.test.js.snap
- app/screens/interactive_dialog/__snapshots__/interactive_dialog.test.js.snap
- app/screens/long_post/__snapshots__/long_post.test.js.snap
- app/screens/reaction_list/__snapshots__/reaction_header.test.js.snap
- app/screens/settings/notification_settings/__snapshots__/notification_settings.test.js.snap
- app/screens/settings/notification_settings_email/__snapshots__/notification_settings_email.android.test.js.snap
- app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
- app/screens/terms_of_service/__snapshots__/terms_of_service.test.js.snap
- app/screens/user_profile/__snapshots__/user_profile.test.js.snap
- package-lock.json
- package.json
- fixes leading zero by rendering post time with react-intl as default and moment-timezone as fallback (for those unsupported timezone of react-intl)
- add [@testing-library/react-native](https://github.com/testing-library/native-testing-library#readme) to better test component rendering.  It offers APIs which are aligned with [testing-library](https://testing-library.com/) - growing adoption in testing due to its better philosophies and practices. With enzyme, this component (FormattedTime) is untestable since `mount` is not supported and react-intl does not generate formatting/localization. 
Note: this renders the same as the webapp - https://github.com/mattermost/mattermost-webapp/pull/4661
Jira ticket: https://mattermost.atlassian.net/browse/MM-21342
This PR was tested on: iOS …
> MM-21342 Fix leading zero on post by using react-intl by default and fallback to moment-timezone for unsupported locale

- android/app/src/main/AndroidManifest.xml
- app/mattermost.js
Cherry pick of #3805 on release-1.27.
- #3805: MM-21288 Fix attaching files on Android
/cc  @enahum
> Automated cherry pick of #3805

- app/components/no_results.js
- app/screens/channel/channel_base.js
- app/screens/channel/channel_base.test.js
- app/screens/channel_info/channel_info.js
- package-lock.json
Changes the channel info screen transition from push to modal
https://mattermost.atlassian.net/browse/MM-13953
> MM-13953 Channel Info screen transition

- SECURITY.md
Copied over some additional wording changes from the server repo.
https://mattermost.atlassian.net/browse/MM-20627
> MM-20627: Update wording in SECURITY.md

- ios/Podfile.lock
- package-lock.json
- package.json
- patches/rn-fetch-blob+0.12.0.patch
As part of the dependency updates I went about patching `rn-fetch-blob`, with this patch we can then remove the need of the current fork.
Note: Keeping the fork will allow us to easily re-create the patch file when needed.
> Patch rn-fetch-blob with CBA support

- app/screens/interactive_dialog/dialog_element.js
- app/screens/interactive_dialog/dialog_element.test.js
- app/screens/interactive_dialog/interactive_dialog.js
- app/screens/interactive_dialog/interactive_dialog.test.js
Cherry pick of #3793 on release-1.28.
- #3793: MM-21632: fix toggling interactive dialog boolean
/cc  @lieut-data
> Automated cherry pick of #3793

- app/actions/views/login.js
- app/actions/views/login.test.js
- app/init/fetch.js
- app/init/fetch.test.js
Cherry pick of #3819 on release-1.28.
- #3819: Dispatch loadConfigAndLicense on successful login
/cc  @migbot
> Automated cherry pick of #3819

- app/components/markdown/markdown_code_block/markdown_code_block.js
Cherry pick of #3813 on release-1.28.
- #3813: MM-21634 Fix keyboard glitch when returning to channel screen
/cc  @enahum
> Automated cherry pick of #3813

- package-lock.json
- package.json
Update mattermost-redux (#3823)
> Manual cherry-pick of #3823

- android/app/src/main/AndroidManifest.xml
- app/components/post_list/post_list.test.js
- app/utils/url.test.js
- fastlane/Fastfile
- fastlane/env_vars_example
- ios/Mattermost/Info.plist
Cherry pick of #3827 on release-1.28.
- #3827: Set default app scheme to `mattermost`
/cc  @chuttam
> Automated cherry pick of #3827

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3829 on release-1.27.
- #3829: Bump app build number to 260
/cc  @migbot
> Automated cherry pick of #3829

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package.json
Will cherry-pick into both release-1.27 and release-1.28.
> Bump app version number to 1.27.1

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package.json
Cherry pick of #3832 on release-1.27.
- #3832: Bump app version number to 1.27.1
/cc  @migbot
> Automated cherry pick of #3832

- android/app/src/main/AndroidManifest.xml
- app/mattermost.js
Cherry pick of #3843 on release-1.28.
- #3843: Call Linking.getInitialURL() in launchApp
/cc  @migbot
> Automated cherry pick of #3843

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #3848 on release-1.28.
- #3848: Bump app build number to 261
/cc  @enahum
> Automated cherry pick of #3848

- ios/Mattermost/UIPasteboard+GetImageInfo.m
Cherry pick of #3854 on release-1.28.
- #3854: Handle com.compuserve.gif type with dataForPasteboardType
/cc  @migbot
> Automated cherry pick of #3854

- app/components/formatted_time.js
- app/components/formatted_time.test.js
- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/root/root.js
- app/i18n/index.js
Cherry pick of #3861 on release-1.28.
- #3861: MM-21961 Fix Incorrect Timestamp on Android Mobile App
/cc  @enahum
> Automated cherry pick of #3861

- app/components/sidebars/drawer_layout.js
Cherry pick of #3859 on release-1.28.
- #3859: iOS Slide open main sidebar from anywhere
/cc  @enahum
> Automated cherry pick of #3859

- app/utils/url.js
- app/utils/url.test.js
Cherry pick of #3862 on release-1.28.
- #3862: Handle links with no server URL provided
/cc  @chuttam
> Automated cherry pick of #3862

- app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
- app/components/emoji_picker/emoji_picker_base.js
- app/utils/emoji_utils.js
- app/utils/emoji_utils.test.js
Cherry pick of #3865 on release-1.28.
- #3865: Sort emojis in EmojiPicker
/cc  @migbot
> Automated cherry pick of #3865

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3871 on release-1.28.
- #3871: Bump app build number to 262
/cc  @migbot
> Automated cherry pick of #3871

- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
Cherry pick of #3874 on release-1.28.
- #3874: Import from semver/preload
/cc  @migbot
> Automated cherry pick of #3874

- README.md
- android/app/build.gradle
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/changelog
- fastlane/metadata/en-US/name.txt
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
This PR bumps the build number but also sets the new minimum supported server version
> Bump Build number to 263

- README.md
- android/app/build.gradle
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/changelog
- fastlane/metadata/en-US/name.txt
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3877 on release-1.28.
- #3877: Bump app build number to 263
/cc  @enahum
> Automated cherry pick of #3877

- app/components/sidebars/drawer_layout.js
Cherry pick of #3879 on release-1.28.
- #3879: MM-22165 Fix channel sidebar close gesture
/cc  @enahum
> Automated cherry pick of #3879

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3888 on release-1.28.
- #3888: Bump app build number to 264
/cc  @migbot
> Automated cherry pick of #3888

- app/components/post_textbox/components/camera_button.js
- app/components/post_textbox/components/camera_button.test.js
- app/components/post_textbox/components/file_upload_button.js
- app/components/post_textbox/components/file_upload_button.test.js
- app/components/post_textbox/components/image_upload_button.js
- app/components/post_textbox/components/image_upload_button.test.js
Compare requested permission result with `Permissions.RESULTS.GRANTED` not `Permissions.RESULTS.AUTHORIZED`. 
https://mattermost.atlassian.net/browse/MM-22236
* Galaxy S7, Android 8
> [MM-22236] Check against Permissions.RESULTS.GRANTED

- app/components/post_textbox/components/camera_button.js
- app/components/post_textbox/components/camera_button.test.js
- app/components/post_textbox/components/file_upload_button.js
- app/components/post_textbox/components/file_upload_button.test.js
- app/components/post_textbox/components/image_upload_button.js
- app/components/post_textbox/components/image_upload_button.test.js
Cherry pick of #3892 on release-1.28.
- #3892: Check agains Permissions.RESULTS.GRANTED
/cc  @migbot
> Automated cherry pick of #3892

- app/screens/image_preview/downloader.ios.js
Cherry pick of #3891 on release-1.28.
- #3891: Fix typo in error.message
/cc  @migbot
> Automated cherry pick of #3891

- app/components/post_list/new_messages_divider.js
- app/components/post_list/post_list.js
- app/screens/channel/channel_post_list/channel_post_list.js
Cherry pick of #3900 on release-1.28.
- #3900: MM-22253 Reduce unnecessary re-renders in channel switching
/cc  @chuttam
> Automated cherry pick of #3900

- app/components/conditionalWrapper.js
- app/components/file_upload_preview/file_upload_item/file_upload_item.js
- app/components/file_upload_preview/file_upload_preview.js
- app/components/file_upload_preview/file_upload_remove.js
- app/components/file_upload_preview/file_upload_retry.js
- app/components/pasteable_text_input/__snapshots__/index.test.js.snap
- app/components/pasteable_text_input/index.js
- app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
- app/components/post_textbox/post_textbox_base.js
- app/constants/view.js
Tighten up post draft UI.
Android:
https://pr-builds.mattermost.com/mattermost-mobile/build-pr-3898/Mattermost_Beta.apk
iOS:
itms-services://?action=download-manifest&url=https://pr-builds.mattermost.com/mattermost-mobile/build-pr-3898/Mattermost_Beta.plist
https://mattermost.atlassian.net/browse/MM-22034
* iPhone 8 and 11 simulators, iOS 13.3
iPhone 11:
iPhone 8:
Android:
> [MM-22034] Tighten up post draft UI

- app/components/conditionalWrapper.js
- app/components/file_upload_preview/file_upload_item/file_upload_item.js
- app/components/file_upload_preview/file_upload_preview.js
- app/components/file_upload_preview/file_upload_remove.js
- app/components/file_upload_preview/file_upload_retry.js
- app/components/pasteable_text_input/__snapshots__/index.test.js.snap
- app/components/pasteable_text_input/index.js
- app/components/post_textbox/__snapshots__/post_textbox.test.js.snap
- app/components/post_textbox/post_textbox_base.js
- app/constants/view.js
Cherry pick of #3898 on release-1.28.
- #3898: Tighten up post draft UI
/cc  @migbot
> Automated cherry pick of #3898

- app/mattermost.js
Cherry pick of #3902 on release-1.28.
- #3902: Dispatch loadConfigAndLicense on launchApp
/cc  @migbot
> Automated cherry pick of #3902

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3909 on release-1.28.
- #3909: Bump app build number to 265
/cc  @migbot
> Automated cherry pick of #3909

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3914 on release-1.28.
- #3914: Bump app build number to 266
/cc  @enahum
> Automated cherry pick of #3914

- app/screens/channel/channel_base.js
- package-lock.json
- package.json
On login when the channel screen mounted if the current channel wasn't yet selected there was a call to get the channel stats that will return a 401 from the server causing the user to force logout.
This was more prominent when using SSO as login method
https://mattermost.atlassian.net/browse/MM-22487
> MM-22487 Fix race condition causing the user to logout

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3917 on release-1.28.
- #3917: Bump app build number to 267
/cc  @migbot
> Automated cherry pick of #3917

- ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
I think the calling of `handleReplyAction_didReceiveNotificationResponse`'s completion handler right after calling `sendReply` prevented, in some cases, the session task from completing. With these changes I have not been able to reproduce the issue.
https://mattermost.atlassian.net/browse/MM-22591
> [MM-22591] Call completionHandler in sendReply

- ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Cherry pick of #3925 on release-1.28.
- #3925: Call completionHandler in sendReply
/cc  @migbot
> Automated cherry pick of #3925

- android/app/build.gradle
- fastlane/metadata/android/en-US/full_description.txt
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3927 on release-1.28.
- #3927: Bump app build number to 268
/cc  @migbot
> Automated cherry pick of #3927

- patches/react-native-notifications+2.0.6.patch
Cherry pick of #3913 on release-1.29.
- #3913: Use JobIntentService over IntentService
/cc  @migbot
> Automated cherry pick of #3913

- app/components/sidebars/drawer_layout.js
Cherry pick of #3919 on release-1.29.
- #3919: MM-20184 Remove ios drawer hack and Fix right drawer
/cc  @enahum
> Automated cherry pick of #3919

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Manual cherry pick of https://github.com/mattermost/mattermost-mobile/pull/3934/
> Bump app build number to 269 (#3934)

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3942 on release-1.29.
- #3942: Bump app build number to 270
/cc  @migbot
> Automated cherry pick of #3942

- app/components/file_attachment_list/file_attachment_image.js
Cherry pick of #3931 on release-1.29.
- #3931: MM-22629 Center-align tall & thin image attachments
/cc  @chuttam
> Automated cherry pick of #3931

- patches/rn-fetch-blob+0.12.0.patch
Cherry pick of #3952 on release-1.29.
- #3952: Fix rn-fetch-blob cast exception
/cc  @migbot
> Automated cherry pick of #3952

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3953 on release-1.29.
- #3953: Bump app build number to 271
/cc  @migbot
> Automated cherry pick of #3953

- package-lock.json
- package.json
Cherry pick of #3923 on release-1.29.
- #3923: Update react-native-cookies
/cc  @migbot
> Automated cherry pick of #3923

- app/screens/post_options/post_options.js
- assets/base/i18n/en.json
As part of https://mattermost.atlassian.net/browse/MM-22129 I need to change the text in the long press menu
https://mattermost.atlassian.net/browse/MM-22129
https://github.com/mattermost/mattermost-webapp/pull/4930#pullrequestreview-362049697
> [MM-22129] - Change "Copy Permalink" text in post options menu

- package-lock.json
- package.json
Update redux library to include [this changes](https://github.com/mattermost/mattermost-redux/pull/1051) 
https://mattermost.atlassian.net/browse/MM-22201
- Pixel 3a XL with Android 10
- Nvidia Shield, Android 7
> Update redux to include new changes

- package-lock.json
- package.json
> Update redux (#3947)

- app/actions/navigation/index.js
- app/actions/navigation/index.test.js
- app/screens/notification/notification.js
Cherry pick of #3967 on release-1.29.
- #3967: Fix in-app notification crashing when receiving multiple
/cc  @enahum
> Automated cherry pick of #3967

- app/actions/views/channel.js
Fetch archived channels introduced here https://github.com/mattermost/mattermost-redux/pull/1051
> Fetch archived channels

- app/actions/views/channel.js
Cherry pick of #3964 on release-1.29.
- #3964: Fetch archived channels
/cc  @enahum
> Automated cherry pick of #3964

- app/screens/image_preview/downloader.android.js
- assets/base/i18n/en.json
Cherry pick of #3970 on release-1.29.
- #3970: update android downloader
/cc  @hahmadia
> Automated cherry pick of #3970

- app/components/emoji/emoji.js
- app/components/file_attachment_list/file_attachment_document/file_attachment_document.js
- app/components/file_attachment_list/file_attachment_image.js
- app/components/file_attachment_list/file_attachment_list.js
- app/components/markdown/markdown_image/markdown_image.js
- app/components/message_attachments/attachment_image/index.js
- app/components/message_attachments/attachment_image/index.test.js
- app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
- app/components/post_attachment_opengraph/post_attachment_opengraph.js
- app/components/post_body_additional_content/post_body_additional_content.js
- app/components/profile_picture/profile_picture.js
- app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
- app/components/progressive_image/progressive_image.js
- app/components/progressive_image/progressive_image.test.js
- app/components/team_icon/team_icon.js
- app/init/global_event_handler.js
- app/utils/file.js
- package-lock.json
Cherry pick of #3971 on release-1.29.
- #3971: MM-22379 & MM-22598 Boost perf by using FastImage cache
/cc  @enahum
> Automated cherry pick of #3971

- app/components/channel_intro/channel_intro.js
- ios/Podfile.lock
- package-lock.json
- package.json
- patches/react-native-keyboard-tracking-view+5.6.1.patch
Cherry pick of #3921 on release-1.29.
- #3921: MM-21276 & MM-22419 Fix PostList insets and Channel Intro
/cc  @enahum
> Automated cherry pick of #3921

- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
- ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Cherry pick of #3940 on release-1.29.
- #3940: Add set_online query param
/cc  @migbot
> Automated cherry pick of #3940

- app/init/global_event_handler.js
- app/screens/channel/channel_base.js
- app/screens/settings/advanced_settings/advanced_settings.js
- app/store/store.js
- app/store/utils.js
- app/store/utils.test.js
Manual cherry-pick of #3929 - Don't reset the navigation root when clearing data
> Manual cherry-pick of #3929

- app/actions/views/channel.js
- app/actions/views/select_team.js
- app/init/fetch.js
- app/screens/channel/channel_base.js
Cherry pick of #3978 on release-1.29.
- #3978: MM-22686 decrease request timeout to 5s
/cc  @enahum
> Automated cherry pick of #3978

- app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
- app/components/markdown/markdown_table/markdown_table.js
- app/components/markdown/markdown_table/markdown_table.test.js
Cherry pick of #3924 on release-1.29.
- #3924: Ensure isFirstRow prop is set on first row
/cc  @migbot
> Automated cherry pick of #3924

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #3984 on release-1.29.
- #3984: Bump app build number to 272
/cc  @enahum
> Automated cherry pick of #3984

- app/screens/more_channels/more_channels.js
- app/screens/more_channels/more_channels.test.js
The stop condition that prevents the scroll from loading more channels was inverted
https://mattermost.atlassian.net/browse/MM-22790
> MM-22790 Fix Load more joinable/archived channels in more channels screeen

- app/screens/more_channels/more_channels.js
- app/screens/more_channels/more_channels.test.js
Cherry pick of #3988 on release-1.29.
- #3988: MM-22790 Fix Load more joinable/archived channels in more
/cc  @enahum
> Automated cherry pick of #3988

- app/actions/views/channel.js
- app/components/post_textbox/index.js
- app/components/post_textbox/post_textbox.test.js
- app/components/post_textbox/post_textbox_base.js
Cherry pick of #3992 on release-1.29.
- #3992: Fix typing on input box after returning from an archived
/cc  @enahum
> Automated cherry pick of #3992

- android/app/src/main/java/com/mattermost/rnbeta/RNPasteableEditTextOnPasteListener.java
Cherry pick of #3996 on release-1.29.
- #3996: MM-22963 Fix Android post GIF from keyboard
/cc  @enahum
> Automated cherry pick of #3996

- app/init/global_event_handler.js
With the latest performance changes when a user was logged out we were not flushing the redux store.
https://mattermost.atlassian.net/browse/MM-22973
> Flush store on logout

- app/init/global_event_handler.js
Cherry pick of #4002 on release-1.29.
- #4002: Flush store on logout
/cc  @enahum
> Automated cherry pick of #4002

- app/utils/file.js
- patches/react-native-vector-icons+6.6.0.patch
Cherry pick of #4011 on release-1.29.
- #4011: MM-23014 Keep Android cache for vector icons
/cc  @enahum
> Automated cherry pick of #4011

- app/actions/views/channel.js
- app/actions/views/channel.test.js
- app/actions/views/root.js
- app/push_notifications/push_notifications.ios.js
- app/screens/channel/channel_base.js
- app/screens/channel/index.js
- app/store/ephemeral_store.js
- app/utils/push_notifications.js
Cherry pick of #4013 on release-1.29.
- #4013: Fix app hanging when switching to a team after opening push
/cc  @enahum
> Automated cherry pick of #4013

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4017 on release-1.29.
- #4017: Bump app build number to 274
/cc  @migbot
> Automated cherry pick of #4017

- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/components/post_list/post_list.js
Cherry pick of #4026 on release-1.29.
- #4026: MM-23176 Fix crash due to scrollToIndex out of range
/cc  @enahum
> Automated cherry pick of #4026

- app/components/post/post.js
- assets/base/config.json
Undocumented experimental build time feature that was never used.
No ticket created
Note: **this PR should not need QA as it is removing a feature that was never enabled**
> Remove ExperimentalUsernamePressIsMention build time feature

- ios/Podfile.lock
Update Podfile.lock that was out of sync
> Update ios Podfile.lock

- ios/Podfile.lock
Cherry pick of #4048 on release-1.30.
- #4048: Update ios Podfile.lock
/cc  @enahum
> Automated cherry pick of #4048

- app/init/global_event_handler.js
Cherry pick of #4046 on release-1.30.
- #4046: MM-23162 Remove unnecessary dimension and orientation
/cc  @chuttam
> Automated cherry pick of #4046

- android/app/src/main/java/com/mattermost/share/ShareModule.java
Cherry pick of #4047 on release-1.30.
- #4047: MM-21582 Parse payload safely to report Sentry exception with
/cc  @chuttam
> Automated cherry pick of #4047

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4051 on release-1.30.
- #4051: Bump app version number to 1.30.0
/cc  @enahum
> Automated cherry pick of #4051

- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/components/post_list/post_list.js
Cherry pick of #4062 on release-1.30.
- #4062: Enable FlatList virtualization
/cc  @migbot
> Automated cherry pick of #4062

- app/components/network_indicator/network_indicator.js
- app/screens/channel/channel.android.js
- app/screens/channel/channel_nav_bar/channel_nav_bar.js
Cherry pick of #4067 on release-1.30.
- #4067: Add backgroundColor
/cc  @migbot
> Automated cherry pick of #4067

- app/actions/navigation/index.js
- app/actions/views/channel.js
- app/actions/views/post.js
- app/components/sidebars/main/main_sidebar_base.js
- app/utils/general.js
Cherry pick of #4064 on release-1.30.
- #4064: MM-23341 Fix message failed banner when posting first
/cc  @enahum
> Automated cherry pick of #4064

- app/components/network_indicator/network_indicator.js
Cherry pick of #4074 on release-1.30.
- #4074: Fix Android Navbar tap events
/cc  @enahum
> Automated cherry pick of #4074

- app/components/markdown/markdown_table/__snapshots__/markdown_table.test.js.snap
- app/components/markdown/markdown_table/markdown_table.js
Cherry pick of #4075 on release-1.30.
- #4075: Don't use state for rowsSliced/colsSliced
/cc  @migbot
> Automated cherry pick of #4075

- android/app/build.gradle
- fastlane/Gemfile
- fastlane/Gemfile.lock
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Manual cherry-pick to 1.30 to update mm-redux with the proper hash
> Bump app build number to 278

- NOTICE.txt
Cherry pick of #4079 on release-1.30.
- #4079: Update NOTICE.txt
/cc  @amyblais
> Automated cherry pick of #4079

- app/components/file_attachment_list/file_attachment_image.js
Reverts mattermost/mattermost-mobile#3981
> Revert "[MM-21310] Use file URL over preview URL for GIFs"

- package-lock.json
- package.json
- scripts/pre-commit.sh
- tsconfig.json
This PR adds a pre-commit hook that will run a lint check on the modified JavaScript and TypeScript files as well as the Types checking so you can fix your code before submitting a PR and having the CI fail cause of lint or type check issues.
N/A: This is a dev driven PR just to help developers avoid the need to push a commit with a fix for common code format errors
> Add husky pre-commit hook

- app/components/post_textbox/post_textbox_base.js
Default `canPost` to true.
https://mattermost.atlassian.net/browse/MM-23636
> MM-23636: Default 'canPost' to true.

- app/components/post_textbox/post_textbox_base.js
Cherry pick of #4085 on release-1.30.
- #4085: MM-23636: Default 'canPost' to true.
/cc  @mkraft
> Automated cherry pick of #4085

- app/actions/views/channel.js
With batching actions for the Sidebar we forgot to fetch the status of those users in the sidebar
This PR is for the `release-1.30` branch as the one for `master` the code path differs from this one
https://mattermost.atlassian.net/browse/MM-23659
> fetch statuses for users in DM/GM's (release 1.30)

- android/app/src/main/java/com/mattermost/share/ShareModule.java
Fixes regression introduced in f5369ac9c5a75a71bc8bcd7bc8612f8f390b2313
* [MM-23687](https://mattermost.atlassian.net/browse/MM-23687)
> MM-23687 Fix Android Share Extension (currently can't post)

- android/app/src/main/java/com/mattermost/share/ShareModule.java
Cherry pick of #4095 on release-1.30.
- #4095: MM-23687 Fix Android Share Extension (currently can't post)
/cc  @chuttam
> Automated cherry pick of #4095

- app/actions/helpers/channels.ts
With batching actions for the Sidebar we forgot to fetch the status of those users in the sidebar
This PR is for the `master` branch as the one for `release-1.30` the code path differs from this one
https://mattermost.atlassian.net/browse/MM-23659
> fetch statuses for users in DM/GM's

- android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java
- app/components/post_textbox/post_textbox_base.js
Cherry pick of #4100 on release-1.30.
- #4100: Check if HW keyboard is connected
/cc  @migbot
> Automated cherry pick of #4100

- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/components/post_list/post_list.js
Tweaks the postlist windowSize, maxToRenderPerBatch depending on the platform to keep it as smooth as possible while allowing it to be responsive
https://mattermost.atlassian.net/browse/MM-23790
> Tweak post list numbers

- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/components/post_list/post_list.js
Cherry pick of #4105 on release-1.30.
- #4105: Tweak post list numbers
/cc  @enahum
> Automated cherry pick of #4105

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4114 on release-1.30.
- #4114: Bump app build number to 279
/cc  @migbot
> Automated cherry pick of #4114

- app/actions/views/post.js
- app/actions/views/post.test.js
- app/mm-redux/utils/channel_utils.ts
Don't pre-fetch posts for unread archived channels.
https://mattermost.atlassian.net/browse/MM-23795
> [MM-23795] Don't pre-fetch posts for unread archived channels

- app/components/sidebars/main/channels_list/channels_list.js
- app/components/sidebars/main/channels_list/unread_indicator/unread_indicator.base.js
Update the 'More Unreads' button to match the new design changes.
Fixes https://github.com/mattermost/mattermost-server/issues/14141
- OnePlus 7 running on Android 10
> Update `more unreads` button to new design

- app/components/autocomplete/at_mention_item/at_mention_item.js
- app/components/autocomplete/at_mention_item/index.js
- app/selectors/autocomplete.js
- app/selectors/autocomplete.test.js
Adds the ability to find users by nickname when searching using @. Also displays the users nickname, if set, in parenthesis next to the users display name. Matches functionality of the web app.
Added `nickname` property to `profiles` in autocomplete.test.js.
[MM-23755](https://mattermost.atlassian.net/browse/MM-23755)
- iPhone 11, iOS 13.4 (simulator)
- Pixel 3, Android 9 (simulator)
- [iPhone 11, iOS 13.4 (simulator)](https://i.imgur.com/tS19VjV.png)
- [Pixel 3, Android 9 (simulator)](https://i.imgur.com/sKa4CeR.png)
> [MM-23755] Add nickname as searchable property

- app/components/markdown/markdown_table/markdown_table.js
Cherry pick of #4121 on release-1.30.
- #4121: Always show expand button
/cc  @migbot
> Automated cherry pick of #4121

- patches/rn-fetch-blob+0.12.0.patch
Cherry pick of #4126 on release-1.30.
- #4126: MM-23927 patch RNFetchBlob to report progress using
/cc  @enahum
> Automated cherry pick of #4126

- app/screens/user_profile/__snapshots__/user_profile.test.js.snap
- app/screens/user_profile/user_profile.js
Adds the first and last name to the user profile view and reorganizes the order to match the web app and edit profile view. Also removes the username entry since it's already displayed in the second line below the user photo (matches web app). Also, adds language support for display labels.
Fixes: [mattermost-server #14187](https://github.com/mattermost/mattermost-server/issues/14187)
JIRA ticket: [MM-23584](https://mattermost.atlassian.net/browse/MM-23584), [MM-23675](https://mattermost.atlassian.net/browse/MM-23675)
- [iPhone 11, iOS 13.4 (simulator)](https://i.imgur.com/Hto0Lhd.png)
- [Pixel 3, Android 10 (simulator)](https://i.imgur.com/dAj9cpI.png)
> [MM-23584][MM-23675] Add first and last name to user profile view & language support

- app/components/post_body/__snapshots__/system_message_helpers.test.js.snap
- app/components/post_body/system_message_helpers.js
- app/components/post_body/system_message_helpers.test.js
Removes the markdown for channel purpose system messages.
https://mattermost.atlassian.net/browse/MM-22043
> MM-22043 Render Channel purpose message without markdown

- app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
- app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
Fix the glitch on the keyboard seen when opening Keywords (settings>notifications>mentions and replies) 
https://mattermost.atlassian.net/browse/MM-22041
> MM-22041 Fix Keyboard flashing when entering keyboards screen

- app/push_notifications/push_notifications.ios.js
- app/push_notifications/push_notifications.ios.test.js
Cherry pick of #4135 on release-1.30.
- #4135: Don't subtract from badge count
/cc  @migbot
> Automated cherry pick of #4135

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4139 on release-1.30.
- #4139: Bump app build number to 280
/cc  @migbot
> Automated cherry pick of #4139

- README.md
- android/app/build.gradle
- fastlane/metadata/android/en-US/full_description.txt
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4148 on release-1.30.
- #4148: Bump app build number to 281
/cc  @enahum
> Automated cherry pick of #4148

- app/components/post_body/index.js
- app/components/post_body/post_body.js
Cherry pick of #4150 on release-1.30.
- #4150: Ensure postProps is not null/undefined
/cc  @migbot
> Automated cherry pick of #4150

- app/components/file_attachment_list/file_attachment_image.js
- app/components/progressive_image/__snapshots__/progressive_image.test.js.snap
- app/components/progressive_image/progressive_image.js
- app/mattermost.js
- app/store/middleware.js
- app/utils/general.js
- patches/react-native-fast-image+8.1.5.patch
PR to validate the previous installed version to migrate the store.
Probably the cherry-pick will need to be manual as master has drifted a lot from the release branch, Also after this PR goes in, a few of the other pending PR's will need to resolve conflicts.
> Validate previous app version

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/MattermostTests/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4154 on release-1.30.
- #4154: Bump app build number to 282
/cc  @enahum
> Automated cherry pick of #4154

- app/init/global_event_handler.js
- app/mattermost.js
- app/store/middleware.js
- app/store/store.js
- app/store/utils.js
- app/utils/general.js
https://mattermost.atlassian.net/browse/MM-24202
> MM-24202 Add ability to invalidate specific versions

- app/components/file_attachment_list/file_attachment_image.js
- app/components/file_attachment_list/file_attachment_list.js
- app/components/progressive_image/progressive_image.js
- app/screens/image_preview/image_preview.js
https://mattermost.atlassian.net/browse/MM-24218
> Correctly load file attachment images

- app/components/file_attachment_list/file_attachment_image.js
- app/components/file_attachment_list/file_attachment_list.js
- app/components/progressive_image/progressive_image.js
- app/screens/image_preview/image_preview.js
Cherry pick of #4160 on release-1.30.
- #4160: Correctly load file attachment images
/cc  @enahum
> Automated cherry pick of #4160

- app/components/file_attachment_list/file_attachment_image.js
- app/init/credentials.js
QA will test cherry-pick PR build.
> Fix headers when preloading images

- app/components/file_attachment_list/file_attachment_image.js
- app/init/credentials.js
Cherry pick of #4165 on release-1.30.
- #4165: Fix headers when preloading images
/cc  @migbot
> Automated cherry pick of #4165

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Will the 1.30 cherry-pick after merging https://github.com/mattermost/mattermost-mobile/pull/4166.
> Bump app build number to 285

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Manual cherry-pick of https://github.com/mattermost/mattermost-mobile/pull/4167
> Manual cherry-pick of #4167

- app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
Cherry pick of #4125 on release-1.31.
- #4125: Set minHeight
/cc  @migbot
> Automated cherry pick of #4125

- app/actions/views/post.js
- app/actions/views/post.test.js
Cherry pick of #4108 on release-1.31.
- #4108: Correctly add additional actions
/cc  @migbot
> Automated cherry pick of #4108

- app/actions/views/post.js
- app/actions/views/post.test.js
- app/mm-redux/utils/channel_utils.ts
Cherry pick of #4113 on release-1.31.
- #4113: Don't pre-fetch posts for unread archived channels
/cc  @migbot
> Automated cherry pick of #4113

- app/mm-redux/actions/posts.test.js
- app/mm-redux/actions/posts.ts
- app/screens/edit_post/__snapshots__/edit_post.test.js.snap
- app/screens/edit_post/edit_post.js
- app/screens/edit_post/edit_post.test.js
- app/screens/edit_post/index.js
Cherry pick of #4110 on release-1.31.
- #4110: Dismiss keyboard on edit post close
/cc  @migbot
> Automated cherry pick of #4110

- app/components/post/index.js
Cherry pick of #4129 on release-1.31.
- #4129: MM-22198 Don't show commented on for post on the same thread
/cc  @enahum
> Automated cherry pick of #4129

- app/components/post/post.js
- app/components/post_header/index.js
- app/mm-redux/utils/post_utils.ts
Cherry pick of #4130 on release-1.31.
- #4130: MM-22683 use webhook override_username instead of webhook
/cc  @enahum
> Automated cherry pick of #4130

- app/screens/settings/notification_settings_mentions_keywords/__snapshots__/notification_settings_mentions_keywords.test.js.snap
- app/screens/settings/notification_settings_mentions_keywords/notification_settings_mentions_keywords.js
Cherry pick of #4132 on release-1.31.
- #4132: MM-22041 Fix Keyboard flashing when entering keyboards
/cc  @enahum
> Automated cherry pick of #4132

- app/mm-redux/utils/post_list.test.js
- app/mm-redux/utils/post_list.ts
Cherry pick of #4142 on release-1.31.
- #4142: Fix isDateLine function to check for null and undefined
/cc  @enahum
> Automated cherry pick of #4142

- app/actions/navigation/index.js
- app/actions/navigation/index.test.js
Cherry pick of #4138 on release-1.31.
- #4138: Set back button color
/cc  @migbot
> Automated cherry pick of #4138

- app/mattermost.js
- app/reducers/app/index.js
- app/reducers/app/previousVersion.js
- app/store/middleware.js
- app/store/middleware.test.js
- app/utils/general.js
There will be a separate PR for master/1.31.
https://mattermost.atlassian.net/browse/MM-24426
> [MM-24426] Set previous app version in redux store (1.30)

- app/components/post_textbox/index.js
- app/components/post_textbox/index.test.js
- app/screens/post_options/index.js
- app/screens/post_options/index.test.js
Cherry pick of #4193 on release-1.31.
- #4193: Check canPost permissions for v5.22+
/cc  @migbot
> Automated cherry pick of #4193

- patches/react-native-image-picker+2.3.1.patch
This PR includes an additional patch to the Image Picker on Android that should:
1. Resolve the crash
2. Allow selecting images and videos
https://mattermost.atlassian.net/browse/MM-24387
> Patch react-native-image-picker to allow selecting video

- patches/react-native-image-picker+2.3.1.patch
Cherry pick of #4195 on release-1.30.
- #4195: Patch react-native-image-picker to allow selecting video
/cc  @enahum
> Automated cherry pick of #4195

- app/screens/code/code.js
- app/screens/code/index.js
Fixes an issue where iPhone X notch is blocking code block
Fixes https://mattermost.atlassian.net/browse/MM-22387
Fixes https://github.com/mattermost/mattermost-server/issues/13870
Simulator iPhone 11 (13.1)
> [MM-22387] iOS only - Code block numbering obstructed by the iPhone's notch

- app/screens/code/code.js
- app/screens/code/index.js
Cherry pick of #4188 on release-1.31.
- #4188: added isLandscape
> Automated cherry pick of #4188

- app/components/post_textbox/index.js
- app/components/post_textbox/index.test.js
- app/screens/post_options/index.js
- app/screens/post_options/index.test.js
Manual cherry-pick of #4193: Check canPost permissions for v5.22+
> Manual cherry-pick of #4193

- app/init/global_event_handler.js
- app/mattermost.js
- app/reducers/app/index.js
- app/reducers/app/previousVersion.js
- app/store/middlewares/helpers.js
- app/store/middlewares/message_retention.js
- app/store/middlewares/middleware.test.js
- app/store/utils.js
- app/store/utils.test.js
- app/utils/general.js
Changes from
https://github.com/mattermost/mattermost-mobile/pull/4196
https://github.com/mattermost/mattermost-mobile/pull/4205
but for master/1.31.
https://mattermost.atlassian.net/browse/MM-24426
https://mattermost.atlassian.net/browse/MM-24451
> [MM-24426] [MM-24451] Set previous app version in redux store

- app/actions/views/user.js
This PR retrieves the CSRF cookie right after login so it is set for future requests
https://mattermost.atlassian.net/browse/MM-24385
> MM-24385 Fix ExperimentalStrictCSRFEnforcement

- app/actions/views/user.js
Cherry pick of #4207 on release-1.31.
- #4207: MM-24385 Fix ExperimentalStrictCSRFEnforcement
/cc  @enahum
> Automated cherry pick of #4207

- app/mattermost_managed/mattermost-managed.android.js
- app/screens/select_server/select_server.js
- ios/Podfile.lock
- patches/react-native-local-auth+1.6.0.patch
Cherry pick of #4203 on release-1.31.
- #4203: Fix Crash on iOS with EMM enabled
/cc  @enahum
> Automated cherry pick of #4203

- app/components/file_attachment_list/file_attachment_list.js
Cherry pick of #4192 on release-1.31.
- #4192: Fix infinite loop retrieving post files
/cc  @ethervoid
> Automated cherry pick of #4192

- app/init/global_event_handler.js
- app/mattermost.js
- app/reducers/app/index.js
- app/reducers/app/previousVersion.js
- app/store/middlewares/helpers.js
- app/store/middlewares/message_retention.js
- app/store/middlewares/middleware.test.js
- app/store/utils.js
- app/store/utils.test.js
- app/utils/general.js
Manual cherry-pick of #4197: MM-24426] [MM-24451] Set previous app version in redux store (#4197)
[MM-24451]: https://mattermost.atlassian.net/browse/MM-24451
> Cherry pick of #4197

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
this will require a manual cherry-pick for 1.30
I still need to bump the version number
> Bump app build number to 286

- app/init/global_event_handler.js
- app/store/utils.js
- app/store/utils.test.js
Cherry pick of #4225 on release-1.31.
- #4225: MM-24451 Set prev app version to current on logout/reset
/cc  @enahum
> Automated cherry pick of #4225

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Will cherry-pick into 1.31 as well.
> Bump app build number to 287

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 287 (#4229)

- app/screens/search/search.js
Cherry pick of #4223 on release-1.31.
- #4223: Fixing padding of searchbar in search screen
/cc  @avasconcelos114
> Automated cherry pick of #4223

- app/screens/index.js
Cherry pick of #4137 on release-1.31.
- #4137: Wrap screen in gestureHandlerRootHOC
/cc  @migbot
> Automated cherry pick of #4137

- fastlane/Fastfile
- ios/Podfile.lock
Cherry pick of #4240 on release-1.31.
- #4240: Add find_replace_string for MMKVStorage
/cc  @migbot
> Automated cherry pick of #4240

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Manual cherry pick of #4242: Bump app build number to 289
> Manual cherry pick of #4242

- app/actions/views/channel.js
Cherry pick of #4245 on release-1.31.
- #4245: Disable loadUnreadChannelPosts
/cc  @migbot
> Automated cherry pick of #4245

- app/actions/views/post.js
- app/store/utils.js
- app/store/utils.test.js
Cherry pick of #4090 on release-1.31.
- #4090: Fix post in channel batching order
/cc  @enahum
> Automated cherry pick of #4090

- app/actions/views/channel.js
Cherry pick of #4251 on release-1.31.
- #4251: Revert "Disable loadUnreadChannelPosts (#4245)"
/cc  @migbot
> Automated cherry pick of #4251

- app/store/mmkv_adapter.ts
To see if this positively impacts performance lag issues (channel sidebar opening, etc.) in 1.31 release.
Conversation [here](https://community.mattermost.com/core/pl/ranb7t859pyoipi189rq7jc3zw) .
(To be added)
This PR was tested on: Android 10 device (OnePlus 5)
> Serialize/Deserialize state as string in store, instead of map

- app/store/mmkv_adapter.ts
Cherry pick of #4253 on release-1.31.
- #4253: Serialize/Deserialize state as string in store, instead
/cc  @chuttam
> Automated cherry pick of #4253

- README.md
Cherry pick of #4264 on release-1.31.
- #4264: Update README.md
/cc  @enahum
> Automated cherry pick of #4264

- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
Ensure that the event listener for in-app notifications is registered just once
https://mattermost.atlassian.net/browse/MM-24852
> MM-24852 ensure only one listener for in-app notification is registered

- app/store/middlewares/helpers.js
- app/store/middlewares/middleware.test.js
Cherry pick of #4258 on release-1.31.
- #4258: Set rehydration values to true on clean up
/cc  @migbot
> Automated cherry pick of #4258

- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
Cherry pick of #4267 on release-1.31.
- #4267: MM-24852 ensure only one listener for in-app notification is
/cc  @enahum
> Automated cherry pick of #4267

- app/screens/channel/channel_nav_bar/channel_nav_bar.js
- app/screens/channel/channel_nav_bar/channel_nav_bar.test.js
Cherry pick of #4244 on release-1.31.
- #4244: MM-24061 Bring back channel sidebar hamburger icon for
/cc  @chuttam
> Automated cherry pick of #4244

- app/screens/image_preview/__snapshots__/image_preview.test.js.snap
- app/screens/image_preview/image_preview.js
- app/screens/image_preview/image_preview.test.js
Cherry pick of #4257 on release-1.31.
- #4257: Use cache only for http URIs
/cc  @migbot
> Automated cherry pick of #4257

- app/components/autocomplete/slash_suggestion/index.js
- app/screens/channel/channel.android.js
Cherry pick of #4273 on release-1.31.
- #4273: MM-24113 Support 'leave' slash command
/cc  @chuttam
> Automated cherry pick of #4273

- app/actions/views/post.js
- app/actions/views/post.test.js
Cherry pick of #4281 on release-1.31.
- #4281: Ensure receivedPosts runs first
/cc  @migbot
> Automated cherry pick of #4281

- app/store/index.ts
Cherry pick of #4294 on release-1.31.
- #4294: Set previous app version on persist store migration
/cc  @enahum
> Automated cherry pick of #4294

- ios/Podfile.lock
- package-lock.json
- package.json
- share_extension/android/extension_post/extension_post.js
- share_extension/android/navigation.js
With the deps update the Android Share extension broke, this PR fixes it.
There is no ticket for this.
> Fixes Android Share Extension

- ios/Podfile.lock
- package-lock.json
- package.json
- share_extension/android/extension_post/extension_post.js
- share_extension/android/navigation.js
Cherry pick of #4305 on release-1.32.
- #4305: Fixes Android Share Extension
/cc  @enahum
> Automated cherry pick of #4305

- app/screens/login/login.js
- app/screens/login/login.test.js
- app/screens/mfa/mfa.js
- app/utils/security.js
Cherry pick of #4308 on release-1.32.
- #4308: Handle MFA error in MFA screen
/cc  @migbot
> Automated cherry pick of #4308

- app/components/file_attachment_list/file_attachment_image.js
- app/components/markdown/markdown_image/markdown_image.js
- app/components/message_attachments/attachment_author.js
- app/components/message_attachments/attachment_footer.js
- app/components/post_attachment_opengraph/post_attachment_opengraph.js
- app/components/profile_picture/profile_picture.js
- app/components/progressive_image/progressive_image.test.js
- app/components/team_icon/team_icon.js
- test/setup.js
Cherry pick of #4314 on release-1.32.
- #4314: Do not preload images with FastImage
/cc  @enahum
> Automated cherry pick of #4314

- app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
- app/components/emoji_picker/emoji_picker.ios.js
- app/components/search_bar/index.js
- app/components/sidebars/main/channels_list/channels_list.js
- app/screens/channel_add_members/channel_add_members.js
- app/screens/channel_members/__snapshots__/channel_members.test.js.snap
- app/screens/channel_members/channel_members.js
- app/screens/more_channels/__snapshots__/more_channels.test.js.snap
- app/screens/more_channels/more_channels.js
- app/screens/more_dms/more_dms.js
- app/screens/search/search.js
- app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
- app/screens/selector_screen/selector_screen.js
- app/screens/settings/timezone/select_timezone/select_timezone.js
Make sure the Search bar cancel button is not visible when the iOS device is placed in landscape mode.
https://mattermost.atlassian.net/browse/MM-25358
> Fix overflow of searchbar for iOS in Landscape

- app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
- app/components/emoji_picker/emoji_picker.ios.js
- app/components/search_bar/index.js
- app/components/sidebars/main/channels_list/channels_list.js
- app/screens/channel_add_members/channel_add_members.js
- app/screens/channel_members/__snapshots__/channel_members.test.js.snap
- app/screens/channel_members/channel_members.js
- app/screens/more_channels/__snapshots__/more_channels.test.js.snap
- app/screens/more_channels/more_channels.js
- app/screens/more_dms/more_dms.js
- app/screens/search/search.js
- app/screens/selector_screen/__snapshots__/selector_screen.test.js.snap
- app/screens/selector_screen/selector_screen.js
- app/screens/settings/timezone/select_timezone/select_timezone.js
Cherry pick of #4312 on release-1.32.
- #4312: Fix overflow of searchbar for iOS in Landscape
/cc  @enahum
> Automated cherry pick of #4312

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4318 on release-1.32.
- #4318: Bump app version number to 1.32.0
/cc  @migbot
> Automated cherry pick of #4318

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4320 on release-1.32.
- #4320: Bump app build number to 294
/cc  @migbot
> Automated cherry pick of #4320

- patches/react-native-navigation+6.4.0.patch
Cherry pick of #4317 on release-1.32.
- #4317: Catch ClassCastException activity
/cc  @migbot
> Automated cherry pick of #4317

- app/store/index.ts
Increase redux-persist timeout to 1 minute.
https://mattermost.atlassian.net/browse/MM-25418
> [MM-25418] Increase redux-persist timeout to 1 minute

- app/store/index.ts
Cherry pick of #4322 on release-1.32.
- #4322: Incrase redux-persist timeout to 1 min
/cc  @migbot
> Automated cherry pick of #4322

- app/components/video_controls.js
Cherry pick of #4325 on release-1.32.
- #4325: Update control icon style
/cc  @migbot
> Automated cherry pick of #4325

- patches/react-native-navigation+6.3.0.patch
Same as https://github.com/mattermost/mattermost-mobile/pull/4317 but for 1.31.
> [MM-25344] Catch ClassCastException

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Will cherry-pick to release-1.31 as well.
> Bump app build number to 295

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4335 on release-1.32.
- #4335: Bump app build number to 295
/cc  @migbot
> Automated cherry pick of #4335

- app/components/sidebars/main/channels_list/channels_list.js
Cherry pick of #4331 on release-1.32.
- #4331: MM-25434 Fix switch team badge cut off
/cc  @enahum
> Automated cherry pick of #4331

- app/components/post/post.js
Cherry pick of #4346 on release-1.32.
- #4346: MM-25510 Increase post options long press delay to 250ms
/cc  @enahum
> Automated cherry pick of #4346

- app/utils/general.js
> Invalidate versions for iOS

- app/utils/general.js
Cherry pick of #4349 on release-1.31.
- #4349: Invalidate versions for iOS
/cc  @enahum
> Automated cherry pick of #4349

- app/components/file_upload_preview/file_upload_item/file_upload_item.js
Cherry pick of #4345 on release-1.31.
- #4345: Bump upload timeout to 1 min
/cc  @enahum
> Automated cherry pick of #4345

- app/components/slide_up_panel/slide_up_panel.js
- app/screens/reaction_list/index.js
- app/utils/error_handling.js
Cherry pick of #4353 on release-1.32.
- #4353: MM-25562 Fix dismiss reaction list crash
/cc  @enahum
> Automated cherry pick of #4353

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4360 on release-1.32.
- #4360: Bump app build number to 296
/cc  @enahum
> Automated cherry pick of #4360

- app/screens/login_options/login_options.js
https://mattermost.atlassian.net/browse/MM-21605
> MM-21605 Remove border to login option buttons

- app/components/search_bar/index.js
- app/components/sidebars/main/channels_list/channels_list.js
- app/components/sidebars/main/main_sidebar_base.js
Sidebar search bar fixes for padding and to improve animations. QA please test on both Android and iOS, for both a user that belongs to one team and a user that belongs to multiple teams, and on both portrait and landscape views.
https://mattermost.atlassian.net/browse/MM-24894
> [MM-24894] Fix sidebar search bar

- NOTICE.txt
Cherry pick of #4357 on release-1.32.
- #4357: Update NOTICE.txt
/cc  @amyblais
> Automated cherry pick of #4357

- app/screens/select_server/select_server.js
- app/screens/sso/sso.js
Some customers have the SSO IdP configured to redirect back to a URI but in practice they can have multiple URI's that the user can input in the select server url field.
With this PR when the webpage finishes to load instead of checking for the cookie that matches the server address entered by the user we then make use of the one we got redirected to by the IdP, if  the cookie is then present we proceed to log the user in and change the client url to the final one.
https://mattermost.atlassian.net/browse/MM-25699
More info: https://community.mattermost.com/core/pl/1ozgeawx9i8m3dwjk1wdgue6co
> Handle SSO redirecting to a different URL than specified by the user

- app/screens/select_server/select_server.js
- app/screens/sso/sso.js
Cherry pick of #4372 on release-1.32.
- #4372: Handle SSO redirecting to a different URL than specified
/cc  @enahum
> Automated cherry pick of #4372

- app/screens/edit_profile/__snapshots__/edit_profile.test.js.snap
- app/screens/edit_profile/edit_profile.js
- app/screens/edit_profile/edit_profile.test.js
- app/screens/edit_profile/index.js
Cherry pick of #4377 on release-1.32.
- #4377: MM-25694 Disallow profile picture update is set by LDAP
/cc  @enahum
> Automated cherry pick of #4377

- app/components/autocomplete/at_mention/at_mention.js
Currently, at-mention and search autocomplete do not render if there is a server request or network problem/outage, because the only data used to populate autocomplete results is a server request.
Now, these autocompletes will render initially with user data currently in store, and then re-rendered in place, once the server response completes.
* [MM-13076](https://mattermost.atlassian.net/browse/MM-13076)
* Android 10 device (OnePlus 5)
**Old**  
Autocomplete doesn't open (no results) with no network connection
**New**
Autocomplete opens with in-store results with no network connection
> [MM-13076] Start with store results for at-mention/search autocomplete 

- app/screens/select_server/select_server.js
Cherry pick of #4389 on release-1.32.
- #4389: MM-25831 Fix timing issue with cancelPing
/cc  @chuttam
> Automated cherry pick of #4389

- app/screens/login_options/login_options.js
Ticket: https://mattermost.atlassian.net/browse/MM-25778
> [MM-25778] clear cookies on again trying to login

- NOTICE.txt
- app/actions/views/root.js
- app/init/global_event_handler.js
- app/mm-redux/types/module.d.ts
- app/store/index.ts
- package-lock.json
- package.json
- packager/moduleNames.js
- packager/modulePaths.js
Cherry pick of #4390 on release-1.32.
- #4390: Ensure previous state is cleared when logout
/cc  @enahum
> Automated cherry pick of #4390

- app/screens/login_options/login_options.js
Cherry pick of #4387 on release-1.32.
- #4387: clear cookies on again trying to login
/cc  @promehul
> Automated cherry pick of #4387

- app/components/post_draft/post_draft.js
Cherry pick of #4397 on release-1.32.
- #4397: Removed unnecessary trim
/cc  @marianunez
> Automated cherry pick of #4397

- app/mm-redux/reducers/entities/channels.ts
Cherry pick of #4400 on release-1.32.
- #4400: MM-25782 improve channel member reducer speed to sync
/cc  @enahum
> Automated cherry pick of #4400

- ios/NotificationService/NotificationService.swift
Cherry pick of #4401 on release-1.32.
- #4401: MM-25929 Decouple id-loaded retries from regular notification
/cc  @chuttam
> Automated cherry pick of #4401

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4404 on release-1.32.
- #4404: Bump app build number to 299
/cc  @enahum
> Automated cherry pick of #4404

- app/init/global_event_handler.js
- app/screens/login_options/login_options.js
as in the ticket
https://mattermost.atlassian.net/browse/MM-25967
> MM-25967 await until cookies are cleared

- app/init/global_event_handler.js
- app/screens/login_options/login_options.js
Cherry pick of #4411 on release-1.32.
- #4411: MM-25967 await until cookies are cleared
/cc  @enahum
> Automated cherry pick of #4411

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4414 on release-1.32.
- #4414: Bump app build number to 300
/cc  @migbot
> Automated cherry pick of #4414

- app/init/global_event_handler.js
- app/screens/login_options/login_options.js
Cherry pick of #4418 on release-1.32.
- #4418: Wrap await calls in try/catch
/cc  @migbot
> Automated cherry pick of #4418

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4425 on release-1.32.
- #4425: Bump app build number to 302
/cc  @enahum
> Automated cherry pick of #4425

- app/screens/select_server/select_server.js
Cherry pick of #4333 on release-1.33.
- #4333: MM-24964 select server url correctly animate error with
/cc  @enahum
> Automated cherry pick of #4333

- app/mm-redux/actions/teams.test.js
- app/mm-redux/actions/teams.ts
- app/mm-redux/reducers/entities/users.ts
- app/screens/select_team/index.js
- app/screens/select_team/select_team.js
- app/screens/select_team/select_team.test.js
Cherry pick of #4330 on release-1.33.
- #4330: MM-24895 fetch roles if needed and add team member to the
/cc  @enahum
> Automated cherry pick of #4330

- app/screens/login_options/login_options.js
Cherry pick of #4354 on release-1.33.
- #4354: Remove border to login option buttons
/cc  @enahum
> Automated cherry pick of #4354

- app/init/global_event_handler.js
- app/mm-redux/actions/teams.ts
Cherry pick of #4362 on release-1.33.
- #4362: MM-24501 Load all (joinable) teams when resetting app
/cc  @chuttam
> Automated cherry pick of #4362

- app/screens/select_team/index.js
Cherry pick of #4365 on release-1.33.
- #4365: MM-24201 List joinable teams alphabetically
/cc  @chuttam
> Automated cherry pick of #4365

- app/components/search_bar/index.js
- app/components/sidebars/main/channels_list/channels_list.js
- app/components/sidebars/main/main_sidebar_base.js
Cherry pick of #4350 on release-1.33.
- #4350: Fix sidebar search bar
/cc  @migbot
> Automated cherry pick of #4350

- app/components/autocomplete/date_suggestion/date_suggestion.js
Cherry pick of #4368 on release-1.33.
- #4368: MM-24029 Fix date re-selection on search bar
/cc  @chuttam
> Automated cherry pick of #4368

- app/components/safe_area_view/__snapshots__/safe_area_view.ios.test.js.snap
- app/components/safe_area_view/safe_area_view.ios.js
- app/screens/long_post/__snapshots__/long_post.test.js.snap
- app/screens/long_post/long_post.js
- app/screens/permalink/__snapshots__/permalink.test.js.snap
- app/screens/permalink/permalink.js
- app/screens/search/search.js
Cherry pick of #4370 on release-1.33.
- #4370: Animate top bar height/padding
/cc  @migbot
> Automated cherry pick of #4370

- app/actions/helpers/channels.ts
- app/actions/views/channel.js
- app/actions/views/select_team.js
- app/mm-redux/types/store.ts
Cherry pick of #4375 on release-1.33.
- #4375: MM-25695 Select channel when switching teams if available
/cc  @enahum
> Automated cherry pick of #4375

- app/components/autocomplete/at_mention/at_mention.js
Cherry pick of #4385 on release-1.33.
- #4385: MM-13076 Start with store results for at-mention/search
/cc  @chuttam
> Automated cherry pick of #4385

- app/components/post_draft/index.js
- app/constants/post_draft.js
- app/screens/edit_post/edit_post.js
- app/screens/edit_post/edit_post.test.js
- app/screens/edit_post/index.js
- assets/base/i18n/en.json
- share_extension/android/extension_post/extension_post.js
Cherry pick of #4371 on release-1.33.
- #4371: MM-21368 Notify user when editing message that's too long
/cc  @chuttam
> Automated cherry pick of #4371

- ios/NotificationService/NotificationService.swift
Cherry pick of #4409 on release-1.33.
- #4409: MM-25955 Refactor backoff/retry logic for failed id-loaded
/cc  @chuttam
> Automated cherry pick of #4409

- app/components/root/root.js
Cherry pick of #4412 on release-1.33.
- #4412: MM-25350 Hide 'Select Team' title on modal when error occurs
/cc  @chuttam
> Automated cherry pick of #4412

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Will cherry-pick into release-1.33 as well.
> Bump build number

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4459 on release-1.33.
- #4459: Bump build number
/cc  @migbot
> Automated cherry pick of #4459

- app/screens/post_options/post_option.js
- app/screens/post_options/post_options.js
Cherry pick of #4448 on release-1.33.
- #4448: MM-25820 prevent double tap in post options
/cc  @enahum
> Automated cherry pick of #4448

- app/mm-redux/selectors/entities/channels.ts
- app/store/index.ts
- app/utils/general.js
- ios/Mattermost.xcodeproj/project.pbxproj
Cherry pick of #4465 on release-1.32.
- #4465: Various fixes:
/cc  @migbot
> Automated cherry pick of #4465

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4468 on release-1.33.
- #4468: Bump app build number to 304
/cc  @migbot
> Automated cherry pick of #4468

- app/actions/views/emoji.js
- app/store/middlewares/helpers.js
- app/utils/error_handling.js
* Fix map call on Set
* Ensure we don't destructure non-iterable values
* Include error message and stack in Alert
https://mattermost.atlassian.net/browse/MM-26448
> [MM-26448] Fix errors found in Sentry

- app/actions/views/emoji.js
- app/store/middlewares/helpers.js
- app/utils/error_handling.js
Cherry pick of #4474 on release-1.33.
- #4474: Various fixes:
/cc  @migbot
> Automated cherry pick of #4474

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4477 on release-1.33.
- #4477: Bump build number to 305
/cc  @migbot
> Automated cherry pick of #4477

- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
- ios/NotificationService/NotificationService.swift
- ios/UploadAttachments/UploadAttachments/UploadSession.swift
Cherry pick of #4433 on release-1.33.
- #4433: Don't retry nor use response message on 401
/cc  @migbot
> Automated cherry pick of #4433

- share_extension/android/index.js
Cherry pick of #4454 on release-1.33.
- #4454: Ensure state teams and members are up-to-date
/cc  @migbot
> Automated cherry pick of #4454

- app/store/index.ts
Cherry pick of #4489 on release-1.32.
- #4489: Avoid throwing when purging
/cc  @enahum
> Automated cherry pick of #4489

- app/screens/sso/sso.js
Fixes SSO login with servers that are under a subpath
Test should cover all SSO methods with and without subpath servers.
https://mattermost.atlassian.net/browse/MM-26547
Fixes: #4473
> MM-26547 Fix SSO login with subpaths

- app/screens/sso/sso.js
Cherry pick of #4490 on release-1.32.
- #4490: Fix SSO login with subpaths
/cc  @enahum
> Automated cherry pick of #4490

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4494 on release-1.33.
- #4494: Bump app version number to 1.32.2
/cc  @enahum
> Automated cherry pick of #4494

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4500 on release-1.32.
- #4500: Bump app build number to 307
/cc  @enahum
> Automated cherry pick of #4500

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4509 on release-1.33.
- #4509: Bump app build number to 308
/cc  @enahum
> Automated cherry pick of #4509

- app/screens/sso/sso.js
Cherry pick of #4511 on release-1.33.
- #4511: MM-25967 Disable Shared Process Pool in WebView
/cc  @enahum
> Automated cherry pick of #4511

- app/screens/post_options/post_options.js
Cherry pick of #4518 on release-1.33.
- #4518: MM-26638 MM-26656 await when dismissing post options modal
/cc  @enahum
> Automated cherry pick of #4518

- app/screens/login/login.js
Cherry pick of #4519 on release-1.33.
- #4519: MM-26667 Set EMM username as the initial loginId
/cc  @enahum
> Automated cherry pick of #4519

- app/mattermost.js
Cherry pick of #4523 on release-1.33.
- #4523: Wait for hydration before app launch
/cc  @enahum
> Automated cherry pick of #4523

- assets/base/i18n/es.json
Until this PR: https://github.com/mattermost/mattermost-mattermod/pull/152 is deployed, the translation merge conflicts need to unfortunately be manually resolved. Sorry about that. 
> Resolve translation merge conflict

- app/components/team_icon/team_icon.js
When switching teams the TeamIcon component was not updating.. with this PR we changed the logic to always try and render the image if available and then fallback to text.
https://mattermost.atlassian.net/browse/MM-26703
> Fix LHS team icon on team switch

- app/components/team_icon/team_icon.js
Cherry pick of #4534 on release-1.33.
- #4534: Fix LHS team icon on team switch
/cc  @enahum
> Automated cherry pick of #4534

- app/actions/navigation/index.js
- app/actions/navigation/index.test.js
- app/screens/search/search.js
- app/store/ephemeral_store.js
on iOS 12 the functions to dismissModal or dismissAllModals only resolve if there are modals in the stack, if this is not the case they will never resolve.
With this PR we track specifically the modal stack so in case there are no modals we resolve the promise as soon as possible.
https://mattermost.atlassian.net/browse/MM-26699
> MM-26699 Track open modals

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4549 on release-1.33.
- #4549: Bump app build number to 309
/cc  @enahum
> Automated cherry pick of #4549

- android/app/src/main/java/com/mattermost/share/ShareActivity.java
- app/screens/channel/channel.android.js
- assets/base/i18n/en.json
Fixes https://github.com/mattermost/mattermost-server/issues/14480
JIRA: https://mattermost.atlassian.net/browse/MM-24328
> Show toast when pressing back button on channel screen

- assets/base/i18n/de.json
- assets/base/i18n/pt-BR.json
- assets/base/i18n/uk.json
https://github.com/mattermost/mattermost-mobile/pull/4552
> Fix i18n release-1.33

- app/actions/views/root.js
- app/init/push_notifications.js
- app/mattermost.js
- app/push_notifications/push_notifications.android.js
- app/push_notifications/push_notifications.ios.js
- app/screens/channel/channel_base.js
Cherry pick of #4556 on release-1.33.
- #4556: MM-26749 Fix race condition when open from PN
/cc  @enahum
> Automated cherry pick of #4556

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4560 on release-1.33.
- #4560: Bump app build number to 310
/cc  @enahum
> Automated cherry pick of #4560

- app/components/post_body_additional_content/post_body_additional_content.js
Cherry pick of #4571 on release-1.33.
- #4571: Handle invalid YouTube links
/cc  @enahum
> Automated cherry pick of #4571

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4576 on release-1.33.
- #4576: Bump app build number to 311
/cc  @enahum
> Automated cherry pick of #4576

- app/init/analytics.ts
Rename actual_user_id to user_actual_id to be more consistent with the rest of MM telemetry.
JIRA: https://mattermost.atlassian.net/browse/MM-26829
> MM-26829 Rename actual_user_id to user_actual_id to be more consistent with the rest of MM telemetry.

- app/mm-redux/client/client4.ts
Cherry pick of #4521 on release-1.34.
- #4521: We can allow events to RudderStack since we don't have any
/cc  @Adovenmuehle
> Automated cherry pick of #4521

- app/init/analytics.ts
Cherry pick of #4520 on release-1.34.
- #4520: Rename actual_user_id to user_actual_id to be more consistent
/cc  @Adovenmuehle
> Automated cherry pick of #4520

- app/components/post_draft/post_draft.js
With #4536 to clear the text input as soon as possible, we introduced a bug that disallowed posting a message with attachments only, this  PR fixes it.
> Allow to post attachment only messages

- app/components/post_draft/post_draft.js
Cherry pick of #4590 on release-1.34.
- #4590: Allow to post attachment only messages
/cc  @enahum
> Automated cherry pick of #4590

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4600 on release-1.34.
- #4600: Bump app version number to 1.34.0
/cc  @migbot
> Automated cherry pick of #4600

- .circleci/config.yml
Simulator job is failing when building app in CircleCI
> Remove simulator job

- app/actions/views/root.js
- app/actions/views/user.js
- app/components/autocomplete/slash_suggestion/slash_suggestion.js
- app/components/post_draft/uploads/upload_item/upload_item.js
- app/init/analytics.ts
- app/init/credentials.js
- app/init/global_event_handler.js
- app/mm-redux/actions/channels.ts
- app/mm-redux/actions/gifs.ts
- app/mm-redux/actions/integrations.ts
- app/mm-redux/actions/posts.ts
- app/mm-redux/actions/search.ts
- app/mm-redux/actions/users.ts
- app/mm-redux/client/client4.ts
- app/mm-redux/utils/helpers.ts
This PR will add analytics for slash command autocomplete
Testing notes: verify that analytics data being tracked is correct for commands and previous collected data types.
Fixes https://mattermost.atlassian.net/browse/MM-27134
This PR was tested on: iphone 11, OS 13.5(simulator)
No UI changes
> Add analytics to the command autocomplete

- app/actions/views/user.js
- app/init/fetch.js
- app/screens/sso/sso.js
When a user signs in using SSO, if anything fails we currently display and endless spinner, this PR aims to display the  error if any on the screen to help understand why the login failed.
Not adding QA as I don't really know of a way to force it to fail in production environment.
> Fix the display the error message if ssoLogin action fails

- app/actions/views/user.js
- app/init/fetch.js
- app/screens/sso/sso.js
Cherry pick of #4609 on release-1.34.
- #4609: Fix the display the error message if ssoLogin action
/cc  @enahum
> Automated cherry pick of #4609

- ios/Podfile.lock
- package-lock.json
- package.json
Updates the dependency, no visible changes made.
> Update async-storage dependency

- assets/base/i18n/it.json
- assets/base/i18n/ko.json
- assets/base/i18n/pt-BR.json
- assets/base/i18n/ro.json
- assets/base/i18n/ru.json
- assets/base/i18n/tr.json
- assets/base/i18n/zh-CN.json
Fix merge conflicts with weblate. 
> Fix merge conflicts i18n

- app/components/autocomplete/slash_suggestion/slash_suggestion.js
Cherry pick of #4623 on release-1.34.
/cc  @iomodo
> Automated cherry pick of #4623

- app/actions/navigation/index.js
- app/actions/navigation/index.test.js
- app/components/post_list/post_list.js
- app/components/post_list/post_list.test.js
- app/constants/navigation.js
- app/screens/user_profile/user_profile.js
Cherry pick of #4619 on release-1.34.
/cc  @migbot
> Automated cherry pick of #4619

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4627 on release-1.34.
/cc  @migbot
> Automated cherry pick of #4627

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4630 on release-1.34.
/cc  @migbot
> Automated cherry pick of #4630

- app/init/fetch.js
- app/screens/sso/sso.js
Cherry pick of #4642 on release-1.34.
/cc  @enahum
> Automated cherry pick of #4642

- package-lock.json
- package.json
Affected areas: Emojis autocomplete and Reaction screen
> Upgrade fuse.js dependency

- app/actions/views/root.js
- app/components/post_list/more_messages_button/more_messages_button.js
- app/components/post_list/more_messages_button/more_messages_button.test.js
Cherry pick of #4648 on release-1.34.
/cc  @migbot
> Automated cherry pick of #4648

- app/actions/views/channel.js
- app/mm-redux/client/client4.ts
Cherry pick of #4644 on release-1.34.
/cc  @fmunshi
> Automated cherry pick of #4644

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4652 on release-1.34.
/cc  @enahum
> Automated cherry pick of #4652

- app/components/file_attachment_list/__snapshots__/file_attachment_image.test.js.snap
- app/components/file_attachment_list/file_attachment_image.js
- app/components/file_attachment_list/file_attachment_image.test.js
- app/components/file_attachment_list/file_attachment_list.js
Use file preview URL for images in post
https://mattermost.atlassian.net/browse/MM-27139
* iPhone SE, iOS 13.6
> [MM-27139] Use file preview URL for images in post

- app/screens/channel_add_members/channel_add_members.js
- app/screens/channel_members/channel_members.js
- app/screens/more_dms/more_dms.js
- app/screens/selector_screen/selector_screen.js
Cherry pick of #4657 on release-1.34.
/cc  @enahum
> Automated cherry pick of #4657

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4661 on release-1.34.
/cc  @migbot
> Automated cherry pick of #4661

- app/components/radio_button/radio_button_group.js
- app/screens/settings/notification_settings/notification_settings.js
- app/screens/settings/notification_settings_email/notification_settings_email_base.js
[MM-18765] Remove deprecated lifecycle methods from settings screens
Fixes https://mattermost.atlassian.net/browse/MM-18765
Fixes https://github.com/mattermost/mattermost-server/issues/12354
This PR was tested on: iPhone 11 (13.1) Simulator
[MM-18765]: https://mattermost.atlassian.net/browse/MM-18765
> [MM-18765] remove lifecycle methods from settings

- ios/Podfile.lock
- package-lock.json
- package.json
Affected: 
- Attach files
- Browse & attach images from files in Edit Profile
This only applies to Files (not the attach image / video / camera option)
> Upgrade react-native-document-picker dependency

- app/components/post_draft/quick_actions/file_quick_action/index.js
- app/utils/file.test.js
Cherry pick of #4610 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4610

- app/screens/image_preview/downloader.ios.js
- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #4595 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4595

- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #4599 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4599

- app/actions/websocket/users.ts
- app/mm-redux/constants/general.ts
- app/screens/channel/channel_base.js
- app/screens/channel/channel_base.test.js
- assets/base/i18n/en.json
Cherry pick of #4633 on release-1.35.
/cc  @kylejwatson
> Automated cherry pick of #4633

- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #4636 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4636

- package-lock.json
- package.json
Cherry pick of #4640 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4640

- app/components/emoji_picker/emoji_picker_base.js
- assets/base/i18n/en.json
Cherry pick of #4641 on release-1.35.
/cc  @avasconcelos114
> Automated cherry pick of #4641

- app/components/file_attachment_list/__snapshots__/file_attachment_image.test.js.snap
- app/components/file_attachment_list/file_attachment_image.js
- app/components/file_attachment_list/file_attachment_image.test.js
- app/components/file_attachment_list/file_attachment_list.js
Cherry pick of #4656 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4656

- package-lock.json
- package.json
- patches/react-native-elements+2.2.0.patch
Cherry pick of #4658 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4658

- app/components/post_body_additional_content/post_body_additional_content.js
Cherry pick of #4666 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4666

- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #4669 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4669

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Cherry pick of #4668 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4668

- ios/Podfile.lock
- package-lock.json
- package.json
- patches/react-native-mmkv-storage+0.3.5.patch
Affected areas:
- Persistent storage
Test from upgrade:
- previous data should be kept (upgrade smoothly)
Test common:
- As new data gets added closing and opening keeps new data
> Upgrade react-native-mmkv-storage dependency

- ios/Podfile.lock
- package-lock.json
- package.json
- patches/react-native-mmkv-storage+0.3.5.patch
Cherry pick of #4671 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4671

- app/mm-redux/utils/post_utils.ts
Cherry pick of #4660 on release-1.35.
/cc  @mkraft
> Automated cherry pick of #4660

- ios/Podfile.lock
- package-lock.json
- package.json
Affected areas: Camera, Fotos, Files access permissions.
> Upgrade react-native-permissions dependency

- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #4693 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4693

- app/components/sidebars/main/main_sidebar.ios.js
- app/components/sidebars/main/main_sidebar_base.js
Cherry pick of #4688 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4688

- app/mm-redux/client/client4.ts
- app/screens/permalink/permalink.js
- app/screens/permalink/permalink.test.js
Cherry pick of #4696 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4696

- app/components/markdown/markdown_emoji/markdown_emoji.js
- app/utils/emoji_utils.js
- app/utils/emoji_utils.test.js
Cherry pick of #4705 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4705

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Cherry pick of #4707 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4707

- NOTICE.txt
Cherry pick of #4717 on release-1.35.
/cc  @amyblais
> Automated cherry pick of #4717

- app/components/emoji_picker/__snapshots__/emoji_picker.test.js.snap
- app/components/emoji_picker/emoji_picker.ios.js
- app/components/emoji_picker/emoji_picker_base.js
Cherry pick of #4728 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4728

- app/screens/sso/sso.js
Cherry pick of #4731 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4731

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4740 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4740

- app/components/autocomplete/date_suggestion/date_suggestion.js
Cherry pick of #4745 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4745

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
- app/components/at_mention/at_mention.test.js
- app/components/markdown/transform.js
- app/components/markdown/transform.test.js
This PR highlights the at-mentions is a post that are followed by a period.
https://mattermost.atlassian.net/browse/MM-25684
> MM-25684 Highlight at-mention followed by a period

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
- app/components/at_mention/at_mention.test.js
- app/components/markdown/transform.js
- app/components/markdown/transform.test.js
Cherry pick of #4733 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4733

- app/components/post_draft/post_draft.js
- app/components/post_draft/post_draft.test.js
Same changes as https://github.com/mattermost/mattermost-mobile/pull/4744 but for 1.35 since 1.35 does not include the post draft refactor.
> [MM-27824] Store value before resetting text input

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4749 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4749

- app/components/autocomplete/channel_mention/channel_mention.js
- app/components/autocomplete/channel_mention/index.js
- app/selectors/autocomplete.js
- app/selectors/autocomplete.test.js
- Fix ordering of `in:` suggestions: DMs, GMs, Private and then Public channels
- Return only DMs and GMs for `in:@` search, unless a channel name/display name also starts with `@`, in which case it will also be included.
- https://mattermost.atlassian.net/browse/MM-15477
- https://mattermost.atlassian.net/browse/MM-27540
- https://mattermost.atlassian.net/browse/MM-27541
- There is some issue with my local setup. I'm not able to run apps through the adb bridge or build an apk. I'm still trying to figure this out.
For now I've tested in an Android Emulator - Pixel 3 XL running Android 11
> [MM-15477][MM-27540][MM-27541]: fix search inconsistencies using `in:@` / `in:`

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
Cherry pick of #4754 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4754

- app/mm-redux/constants/permissions.ts
- app/screens/channel_info/convert_private/index.js
- Adds and enforces converting channels to private using the new convert public channel to private permission.
- https://mattermost.atlassian.net/browse/MM-27274
This PR was tested on: iPhone 11 sim
> [MM-27274] Add and enforce convert public channel to private permission

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
Fix mention rendering on the screen when turning on or off the setting for Notification > Mentions & Replies & non-case sensitive username 
https://mattermost.atlassian.net/browse/MM-28296
> MM-28296 Fix Android @mention render

- app/screens/channel_info/convert_private/convert_private.tsx
Cherry pick of #4767 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4767

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
Cherry pick of #4764 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4764

- app/actions/views/channel.js
- app/mm-redux/selectors/entities/posts.ts
- app/screens/channel/channel_post_list/channel_post_list.js
- app/screens/channel/channel_post_list/channel_post_list.test.js
- app/screens/channel/channel_post_list/index.js
- app/screens/flagged_posts/flagged_posts.js
- app/screens/flagged_posts/flagged_posts.test.js
- app/screens/flagged_posts/index.js
- app/screens/long_post/__snapshots__/long_post.test.js.snap
- app/screens/long_post/index.js
- app/screens/long_post/long_post.js
- app/screens/long_post/long_post.test.js
- app/screens/permalink/index.js
- app/screens/permalink/permalink.js
- app/screens/permalink/permalink.test.js
- app/screens/pinned_posts/index.js
- app/screens/pinned_posts/pinned_posts.js
- app/screens/pinned_posts/pinned_posts.test.js
- app/screens/recent_mentions/index.js
- app/screens/recent_mentions/recent_mentions.js
- app/screens/recent_mentions/recent_mentions.test.js
- app/screens/search/index.js
- app/screens/search/search.js
Cherry pick of #4771 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4771

- app/store/ephemeral_store.js
Cherry pick of #4777 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4777

- app/components/at_mention/at_mention.js
Cherry pick of #4778 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4778

- package-lock.json
- package.json
Cherry pick of #4779 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4779

- ios/MattermostShare/ShareViewController.swift
Cherry pick of #4781 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4781

- app/components/at_mention/at_mention.js
Cherry pick of #4776 on release-1.35.
/cc  @fmunshi
> Automated cherry pick of #4776

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4787 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4787

- app/actions/navigation/index.js
- app/constants/navigation.js
- app/mattermost.js
- app/store/ephemeral_store.js
Cherry pick of #4793 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4793

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4791 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4791

- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/xml/app_restrictions.xml
- app/init/fetch.js
Override the request default timeout with an AppConfig setting set by an EMM provider. Also bumping the default value to 10s
> AppConfig setting to control the default request timeout

- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/xml/app_restrictions.xml
- app/init/fetch.js
Cherry pick of #4797 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4797

- app/init/fetch.js
Cherry pick of #4801 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4801

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4802 on release-1.35.
/cc  @enahum
> Automated cherry pick of #4802

- detox/e2e/test/smoke_test/login_email.e2e.js
E2E for "Log in - Email / password"
Test case - https://automation-test-cases.vercel.app/test/MM-T3179
This PR was tested on: iOS simulator and Android emulator
> Detox/E2E: MM-T3179 Log in - Email / password

- app/screens/long_post/index.js
Cherry pick of #4819 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4819

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Bump app version number to 1.35.1
> Bump app version number to 1.35.1

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4823 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4823

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 326

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4825 on release-1.35.
/cc  @migbot
> Automated cherry pick of #4825

- CHANGELOG.md
Had trouble opening a pull request today, finally got this to work...
> v1.35.1 Changelog

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Bump app version number to 1.36.0
> Bump app version number to 1.36.0

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
> Bump app build number to 327

- app/reducers/views/channel.js
- app/reducers/views/thread.js
Cherry pick of #4832 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4832

- app/constants/view.js
Update RequiredServer to ESR version 5.25.0
https://mattermost.atlassian.net/browse/MM-27615
> [MM-27615] Update RequiredServer

- app/screens/channel_info/__snapshots__/channel_info.test.js.snap
- app/screens/channel_info/channel_info.js
- app/screens/channel_info/channel_info.test.js
- app/screens/channel_info/index.js
Cherry pick of #4831 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4831

- app/constants/view.js
Cherry pick of #4830 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4830

- app/actions/views/channel.js
- app/mm-redux/actions/channels.test.js
- app/mm-redux/actions/channels.ts
- A channel is fetched from the server if it doesn't already exist in state. When checking reachability use this updated state. 
- When selecting a channel, ensure that we belong to the channel before attempting to get posts. 
- https://mattermost.atlassian.net/browse/MM-28100
- Iphone 11 emulator running ios 13.7
- Pixel 3XL emulator running Android 10
- Server: https://github.com/mattermost/mattermost-server/pull/15525
> [MM-28100] fix reachability check and ensure channel membership before getting posts 

- app/screens/select_server/select_server.js
- assets/base/i18n/en.json
- Better error message if url is empty
- - https://mattermost.atlassian.net/browse/MM-23909
- Iphone 11 emulator running ios 13.7
- Pixel 3XL emulator running Android 10
The URL in the text box is the placeholder text.
> [MM-23909] better error message if url is empty

- app/actions/views/channel.js
- app/mm-redux/actions/channels.test.js
- app/mm-redux/actions/channels.ts
Cherry pick of #4810 on release-1.36.
> Automated cherry pick of #4810

- app/screens/select_server/select_server.js
- assets/base/i18n/en.json
Cherry pick of #4821 on release-1.36.
> Automated cherry pick of #4821

- app/components/autocomplete/channel_mention/channel_mention.js
Cherry pick of #4818 on release-1.36.
> Automated cherry pick of #4818

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4848 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4848

- app/components/post_draft/uploads/upload_item/upload_item.js
- app/components/post_draft/uploads/upload_item/upload_remove.js
Reduced font size of progress text and fixed close icon position.
https://mattermost.atlassian.net/browse/MM-29132
iOS:
Android:
> [MM-29132] Update upload item styling

- app/components/post_draft/uploads/upload_item/upload_item.js
- app/components/post_draft/uploads/upload_item/upload_remove.js
Cherry pick of #4853 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4853

- NOTICE.txt
Cherry pick of #4836 on release-1.36.
/cc  @amyblais
> Automated cherry pick of #4836

- assets/base/i18n/en.json
- ios/MattermostShare/ShareViewController.swift
- ios/UploadAttachments/UploadAttachments/StoreManager.h
- ios/UploadAttachments/UploadAttachments/StoreManager.m
- share_extension/android/extension_post/extension_post.js
- share_extension/android/extension_post/extension_post.test.js
- share_extension/android/extension_post/index.js
Cherry pick of #4857 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4857

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4864 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4864

- app/mm-redux/actions/posts.ts
- app/mm-redux/utils/helpers.ts
- detox/e2e/support/server_api/post.js
Remove consecutive occurrences of 'the'
None
> Fix typo in 3 files: consecutive occurrences of 'the'

- app/components/autocomplete/slash_suggestion/slash_suggestion_item.js
Cherry pick of #4868 on release-1.36.
> Automated cherry pick of #4868

- android/app/src/main/java/com/mattermost/rnbeta/RNPasteableActionCallback.java
- app/components/pasteable_text_input/index.js
- app/components/pasteable_text_input/index.test.js
Cherry pick of #4872 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4872

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4876 on release-1.36.
/cc  @migbot
> Automated cherry pick of #4876

- detox/e2e/init.js
- detox/e2e/support/server_api/common.js
- detox/e2e/support/server_api/setup.js
- detox/e2e/support/server_api/system.js
Make error handling on unreachable server to be explicit
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29083
This PR was tested on: iOS simulator and Android emulator
> MM-29083 Detox/E2E: Make error handling on unreachable server to be explicit

- detox/e2e/test/messaging/message_posting.e2e.js
- detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
- detox/e2e/test/on_boarding/login.e2e.js
- detox/e2e/test/smoke_test/login_email.e2e.js
- Add comment guideline to existing E2E
NA
> Detox/E2E: Add E2E comment guideline

- detox/e2e/test/autocomplete/edit_channel.e2e.js
- detox/e2e/test/autocomplete/edit_post.e2e.js
- detox/e2e/test/autocomplete/post_draft.e2e.js
- detox/e2e/test/autocomplete/search.e2e.js
- detox/e2e/test/smoke_test/channels.e2e.js
- detox/e2e/test/smoke_test/login_ldap.e2e.js
- Added missing comment guideline for previously merged PRs
NA
> Detox/E2E: Added missing comment guideline

- app/components/autocomplete/at_mention/at_mention.js
- app/components/autocomplete/at_mention_item/at_mention_item.js
- app/constants/autocomplete.js
- app/selectors/autocomplete.js
- app/selectors/autocomplete.test.js
- detox/e2e/test/autocomplete/at_mention.e2e.js
Cherry pick of #4880 on release-1.37.
/cc  @edtrist
> Automated cherry pick of #4880

- .circleci/config.yml
- app/constants/view.js
- app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
- app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
- fastlane/Fastfile
- fastlane/plist.erb
Align hamburger menu badges screenshots shared in this thread https://community.mattermost.com/core/pl/6e6qqzdry3ghtd7rfx6m4b5eeh
https://mattermost.atlassian.net/browse/MM-28336
> MM-28336 Align hamburger menu badges

- .circleci/config.yml
- app/constants/view.js
- app/screens/channel/channel_nav_bar/channel_drawer_button/__snapshots__/channel_drawer_button.test.js.snap
- app/screens/channel/channel_nav_bar/channel_drawer_button/channel_drawer_button.js
- fastlane/Fastfile
- fastlane/plist.erb
Cherry pick of #4894 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4894

- app/components/sidebars/main/drawer_swiper/drawer_swiper.js
- app/components/sidebars/main/main_sidebar_base.js
- app/components/swiper.js
- app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
- app/screens/channel/channel_nav_bar/channel_title/channel_title.js
- detox/e2e/support/utils.js
- detox/e2e/test/autocomplete/at_mention.e2e.js
- detox/e2e/test/channels/create_public_channel.e2e.js
- detox/e2e/test/main_sidebar/select_channel.e2e.js
- detox/e2e/test/smoke_test/login_email.e2e.js
- detox/e2e/test/smoke_test/login_ldap.e2e.js
When selecting the current channel in the sidebar, close the sidebar while keeping the user in the same channel.
https://mattermost.atlassian.net/browse/MM-28688
> MM-28688 Close sidebar when current channel is selected

- app/components/sidebars/main/drawer_swiper/drawer_swiper.js
- app/components/sidebars/main/main_sidebar_base.js
- app/components/swiper.js
- app/screens/channel/channel_nav_bar/channel_title/__snapshots__/channel_title.test.js.snap
- app/screens/channel/channel_nav_bar/channel_title/channel_title.js
- detox/e2e/support/utils.js
- detox/e2e/test/autocomplete/at_mention.e2e.js
- detox/e2e/test/main_sidebar/select_channel.e2e.js
- detox/e2e/test/smoke_test/login_email.e2e.js
> Manual Cherry pick #4897

- package-lock.json
- package.json
Cherry pick of #4912 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4912

- app/store/index.ts
- app/store/utils.js
- app/store/utils.test.js
Cherry pick of #4918 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4918

- app/components/post_draft/__snapshots__/post_draft.test.js.snap
- app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
- app/components/post_draft/post_input/post_input.js
Cherry pick of #4916 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4916

- detox/e2e/test/autocomplete/edit_channel.e2e.js
- detox/e2e/test/autocomplete/edit_post.e2e.js
- detox/e2e/test/channels/create_public_channel.e2e.js
- detox/e2e/test/in_app_notification/notification.e2e.js
- detox/e2e/test/main_sidebar/select_channel.e2e.js
- detox/e2e/test/messaging/message_posting.e2e.js
- detox/e2e/test/messaging/tap_send_button_repeatedly.e2e.js
- detox/e2e/test/on_boarding/login.e2e.js
- detox/e2e/test/smoke_test/channels.e2e.js
- Fix some failing specs
- Fix some comment formats
NA
Note: Discovered these when running tests against https://github.com/mattermost/mattermost-mobile/pull/4917
> Detox/E2E: Fix some specs and comments

- app/actions/views/channel.js
- app/actions/views/permalink.ts
- app/components/post_body/system_message_helpers.js
- app/components/post_list/index.js
- app/components/post_list/post_list.js
- app/components/post_list/post_list.test.js
- app/screens/channel_info/channel_info.js
- app/screens/channel_info/channel_info.test.js
- app/screens/channel_info/index.js
- app/screens/flagged_posts/flagged_posts.js
- app/screens/flagged_posts/flagged_posts.test.js
- app/screens/flagged_posts/index.js
- app/screens/permalink/permalink.js
- app/screens/pinned_posts/index.js
- app/screens/pinned_posts/pinned_posts.js
- app/screens/pinned_posts/pinned_posts.test.js
- app/screens/recent_mentions/index.js
- app/screens/recent_mentions/recent_mentions.js
- app/screens/recent_mentions/recent_mentions.test.js
- app/screens/search/index.js
- app/screens/search/search.js
- app/utils/general.js
Shows an error when permalink team is invalid.
Note: Refactored the way we open/close permalinks to reduce the amount of code.
https://mattermost.atlassian.net/browse/MM-29252
> MM-29252 Tapping on invalid permalink shows an error

- app/actions/views/channel.js
- app/actions/views/permalink.ts
- app/components/post_body/system_message_helpers.js
- app/components/post_list/index.js
- app/components/post_list/post_list.js
- app/components/post_list/post_list.test.js
- app/screens/channel_info/channel_info.js
- app/screens/channel_info/channel_info.test.js
- app/screens/channel_info/index.js
- app/screens/flagged_posts/flagged_posts.js
- app/screens/flagged_posts/flagged_posts.test.js
- app/screens/flagged_posts/index.js
- app/screens/permalink/permalink.js
- app/screens/pinned_posts/index.js
- app/screens/pinned_posts/pinned_posts.js
- app/screens/pinned_posts/pinned_posts.test.js
- app/screens/recent_mentions/index.js
- app/screens/recent_mentions/recent_mentions.js
- app/screens/recent_mentions/recent_mentions.test.js
- app/screens/search/index.js
- app/screens/search/search.js
- app/utils/general.js
Cherry pick of #4926 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4926

- detox/.detoxrc.json
- fastlane/Fastfile
For iOS - reverted some change from https://github.com/mattermost/mattermost-mobile/pull/4884/files#diff-dff4b99d4e651ab9d7597876ec8dbe92aa934e42c0fb55f4aadd6c106fc96688R358-R367
For Android, need to run `jetify` for Detox's Android build
none
> Fix build for iOS for local simulator and Android test

- app/components/post_draft/__snapshots__/post_draft.test.js.snap
- app/components/post_draft/uploads/index.js
- app/components/post_draft/uploads/uploads.js
- app/components/post_draft/uploads/uploads.test.js
- assets/base/i18n/en.json
Cherry pick of #4927 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4927

- app/screens/flagged_posts/flagged_posts.js
Cherry pick of #4938 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4938

- android/app/src/main/AndroidManifest.xml
This makes Mattermost resizeable on Android Desktops like Samsung DeX
https://github.com/mattermost/mattermost-mobile/issues/3427
This PR was tested on: Samsung S9
> make mattermost resizeable on Android DeX #3427

- app/screens/channel_notification_preference/channel_notification_preference.android.js
- app/screens/channel_notification_preference/channel_notification_preference.ios.js
- app/screens/channel_notification_preference/channel_notification_preference.test.js
- app/screens/channel_notification_preference/channel_notification_preference_base.js
- app/screens/channel_notification_preference/index.js
- assets/base/i18n/en.json
- test/intl-test-helper.js
Cherry pick of #4935 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4935

- ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m
Cherry pick of #4947 on release-1.37.
/cc  @migbot
> Automated cherry pick of #4947

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4952 on release-1.37.
/cc  @migbot
> Automated cherry pick of #4952

- patches/react-native-keyboard-tracking-view+5.7.0.patch
Cherry pick of #4960 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4960

- app/components/autocomplete/at_mention/at_mention.js
- detox/e2e/test/autocomplete/at_mention.e2e.js
Cherry pick of #4937 on release-1.37.
/cc  @avasconcelos114
> Automated cherry pick of #4937

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4964 on release-1.37.
/cc  @enahum
> Automated cherry pick of #4964

- app/components/post_list/__snapshots__/post_list.test.js.snap
- app/components/post_list/post_list.js
- app/screens/flagged_posts/flagged_posts.js
- app/screens/pinned_posts/pinned_posts.js
- app/screens/recent_mentions/recent_mentions.js
- app/screens/search/search.js
- ios/Podfile.lock
This PR fixes the images to be progressively loaded in the thread screen.
Test: Have a post that contains an image, tap on the post to go to the thread screen, image loads progressively.
> MM-27354 Emit the event for visible items in the thread screen

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #4972 on release-1.38.
/cc  @migbot
> Automated cherry pick of #4972

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4973 on release-1.38.
/cc  @migbot
> Automated cherry pick of #4973

- NOTICE.txt
Cherry pick of #4976 on release-1.38.
/cc  @amyblais
> Automated cherry pick of #4976

- app/components/autocomplete/at_mention/at_mention.js
- app/components/autocomplete/channel_mention/channel_mention.js
- app/components/autocomplete/slash_suggestion/slash_suggestion.js
Removed ComponentwillreceiveProps as it would be deprectated.
Fixes https://github.com/mattermost/mattermost-server/issues/12348
Redmi Note 8, Android
> MM-18771 Removed componentwillreceiveprops

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #4998 on release-1.38.
/cc  @migbot
> Automated cherry pick of #4998

- app/screens/gallery/footer/prepare_file/prepare_file.tsx
Cherry pick of #5010 on release-1.38.
/cc  @enahum
> Automated cherry pick of #5010

- app/components/autocomplete/channel_mention_item/channel_mention_item.js
Cherry pick of #5009 on release-1.38.
/cc  @enahum
> Automated cherry pick of #5009

- app/screens/gallery/footer/index.tsx
- app/screens/gallery/footer/summary/actions/actions.tsx
- app/screens/gallery/footer/summary/actions/index.ts
- types/screens/gallery.d.ts
Cherry pick of #5011 on release-1.38.
/cc  @enahum
> Automated cherry pick of #5011

- README.md
> Typo error update in README.md

- app/init/push_notifications.test.js
- app/init/push_notifications.ts
Cherry pick of #5015 on release-1.38.
/cc  @migbot
> Automated cherry pick of #5015

- app/screens/gallery/footer/index.tsx
- app/screens/gallery/gallery.js
- app/screens/gallery/gallery_video.tsx
- app/screens/gallery/gallery_viewer.tsx
- app/screens/gallery/video_controls.tsx
- types/screens/gallery.d.ts
Fixes the ability to tap on the play button to reproduce the video by removing the pointerEvents on the parent view as well as hiding and displaying the gallery header & footer while the video is playing and the overlay shows / hides
https://mattermost.atlassian.net/browse/MM-30866
https://mattermost.atlassian.net/browse/MM-31202
> MM-31202 | MM-30866 fix: Video playback button & hide header footer on playback

- app/components/post_body_additional_content/post_body_additional_content.js
- app/components/post_body_additional_content/post_body_additional_content.test.js
Cherry pick of #5021 on release-1.38.
/cc  @migbot
> Automated cherry pick of #5021

- app/screens/gallery/footer/index.tsx
- app/screens/gallery/gallery.js
- app/screens/gallery/gallery_video.tsx
- app/screens/gallery/gallery_viewer.tsx
- app/screens/gallery/video_controls.tsx
- types/screens/gallery.d.ts
Cherry pick of #5014 on release-1.38.
/cc  @enahum
> Automated cherry pick of #5014

- patches/react-native-keyboard-tracking-view+5.7.0.patch
Cherry pick of #5024 on release-1.38.
/cc  @migbot
> Automated cherry pick of #5024

- app/components/post_draft/uploads/uploads.js
The original issue was that the error messages were not cleared from state after being displayed. I made some further improvements so that the error remains if it needs to be shown again, rather then hiding it first and then showing it again, and it is also removed when the user takes a successful action.
https://mattermost.atlassian.net/browse/MM-30247
* iPhone SE, iOS 14.2
> [MM-30247] Improve upload attachment error handling

- app/components/post_draft/uploads/uploads.js
Cherry pick of #5026 on release-1.38.
/cc  @migbot
> Automated cherry pick of #5026

- app/actions/websocket/index.ts
- app/actions/websocket/websocket.test.js
Cherry pick of #5000 on release-1.38.
> Automated cherry pick of #5000

- app/components/channel_loader/__snapshots__/channel_loader.test.js.snap
- app/components/channel_loader/channel_loader.js
- app/components/channel_loader/channel_loader.test.js
- app/screens/channel/channel_base.js
- assets/base/i18n/en.json
> Manual cherry pick of #5031

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5035 on release-1.38.
/cc  @migbot
> Automated cherry pick of #5035

- app/components/__snapshots__/badge.test.js.snap
- app/components/badge.js
- app/components/badge.test.js
- app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
- app/components/sidebars/main/channels_list/channel_item/channel_item.js
- app/components/sidebars/main/channels_list/switch_teams_button/__snapshots__/switch_teams_button.test.js.snap
- app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
- app/components/sidebars/main/teams_list/teams_list_item/__snapshots__/teams_list_item.test.js.snap
- app/components/sidebars/main/teams_list/teams_list_item/teams_list_item.js
- app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/__snapshots__/main_sidebar_drawer_button.test.js.snap
- app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.js
- detox/e2e/support/ui/component/channels_list.js
- detox/e2e/support/ui/component/main_sidebar.js
- detox/e2e/support/ui/component/teams_list.js
- detox/e2e/support/ui/screen/channel.js
- detox/e2e/support/ui/screen/select_team.js
- detox/e2e/test/smoke_test/mention_badges.e2e.js
- Added test for MM-T3255 in `smoke_test/mention_badges.e2e.js`
- Added new testIDs and updated unit tests
- Added new helper functions
Notes:
1. Created this PR on top of https://github.com/mattermost/mattermost-mobile/pull/4990 as I needed existing components and screens in there.
JIRA: https://mattermost.atlassian.net/browse/MM-30286
TM4J Cases:
- [MM-T3255](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3255)
> MM-30286 Detox/E2E: Add e2e test for MM-T3255

- app/components/autocomplete/index.js
- app/components/edit_channel_info/index.js
- app/components/post_draft/draft_input/draft_input.js
- app/components/post_draft/post_input/post_input.js
- app/constants/device.js
- app/screens/channel/channel.ios.js
- app/screens/edit_post/edit_post.js
- app/screens/thread/__snapshots__/thread.ios.test.js.snap
- app/screens/thread/thread.ios.js
- patches/react-native-keyboard-tracking-view+5.7.0.patch
Cherry pick of #5042 on release-1.39.
/cc  @migbot
> Automated cherry pick of #5042

- app/components/autocomplete/index.js
- app/components/edit_channel_info/index.js
- app/components/post_draft/draft_input/draft_input.js
- app/components/post_draft/post_input/post_input.js
- app/constants/device.js
- app/screens/channel/channel.ios.js
- app/screens/edit_post/edit_post.js
- app/screens/thread/__snapshots__/thread.ios.test.js.snap
- app/screens/thread/thread.ios.js
- patches/react-native-keyboard-tracking-view+5.7.0.patch
> Manual cherry pick of #5042

- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #5048 on release-1.38.
/cc  @enahum
> Automated cherry pick of #5048

- app/components/channel_loader/channel_loader.js
- app/components/channel_loader/channel_loader.test.js
Cherry pick of #5055 on release-1.38.
/cc  @migbot
> Automated cherry pick of #5055

- app/actions/navigation/index.js
Cherry pick of #5049 on release-1.38.
/cc  @enahum
> Automated cherry pick of #5049

- .circleci/config.yml
- package-lock.json
- package.json
- scripts/precommit/i18n.sh
> Add check for empty translation source strings

- app/actions/views/channel.js
- app/actions/views/permalink.ts
- app/components/markdown/markdown_link/markdown_link.js
- app/components/post_draft/draft_input/draft_input.js
- app/components/post_draft/draft_input/draft_input.test.js
- app/components/post_draft/draft_input/index.js
- app/components/post_list/post_list.js
- app/components/post_list/post_list.test.js
- app/constants/deep_linking.js
- app/mm-redux/actions/integrations.ts
- app/utils/draft.js
- app/utils/url.js
- assets/base/i18n/en.json
Cherry pick of #4620 on release-1.39.
/cc  @larkox
> Automated cherry pick of #4620

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #5084 on release-1.39.
/cc  @migbot
> Automated cherry pick of #5084

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5086 on release-1.39.
/cc  @migbot
> Automated cherry pick of #5086

- app/components/sidebars/main/channels_list/channel_item/index.js
Cherry pick of #5094 on release-1.39.
/cc  @migbot
> Automated cherry pick of #5094

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5096 on release-1.39.
/cc  @migbot
> Automated cherry pick of #5096

- app/components/markdown/markdown_link/markdown_link.js
Cherry pick of #5098 on release-1.39.
> Automated cherry pick of #5098

- detox/e2e/support/server_api/index.js
- detox/e2e/support/server_api/preference.js
- detox/e2e/support/server_api/user.js
- detox/e2e/support/utils.js
- detox/e2e/test/teams/teams_order.e2e.js
- Added test for MM-T3646 in `teams/teams_order.e2e.js`
- Added new preference api `support/server_api/preference.js`
- Fixed comments in `support/utils.js`; removed `testIDMatcherMap` function - I mistakenly included this in a previous PR but used only for my local testing.
JIRA: https://mattermost.atlassian.net/browse/MM-31272
TM4J Cases:
- [MM-T3646](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3646)
> MM-31272 Detox/E2E - Add e2e test for MM-T3646

- app/init/push_notifications.ts
On Android at times the device id used to receive push notifications wasn't being attached to the session as the registration completed before the redux store was initialized.
This PR adds a recursion until it can be properly set & registered.
https://mattermost.atlassian.net/browse/MM-31873
> MM-31873 fix race condition that prevented the device id registration

- app/init/push_notifications.ts
Cherry pick of #5104 on release-1.39.
/cc  @enahum
> Automated cherry pick of #5104

- app/utils/file.js
- app/utils/file.test.js
Cherry pick of #5109 on release-1.39.
/cc  @enahum
> Automated cherry pick of #5109

- app/actions/views/channel.js
- app/actions/views/channel.test.js
- app/selectors/channel.js
Cherry pick of #5106 on release-1.39.
> Automated cherry pick of #5106

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5112 on release-1.39.
/cc  @migbot
> Automated cherry pick of #5112

- app/components/file_attachment_list/file_attachment_list.js
- app/components/image_viewport.js
- app/components/sidebars/main/main_sidebar.ios.js
- app/components/sidebars/main/main_sidebar.test.js
- app/init/device.ts
- app/init/global_event_handler.js
- app/mattermost.js
- packager/moduleNames.js
- packager/modules.android.js
- packager/modules.ios.js
On Tablets, the channel sidebar can be kept permanently opened, and the available real state gets smaller, this PR fixes the layout and respond to its changes when the permanent sidebar is kept or removed.
This PR also sets the permanent sidebar as visible for tablets first login
https://mattermost.atlassian.net/browse/MM-31764
> MM-31764 Fix image attachment layout when permanent sidebar is visible

- app/mm-redux/client/client4.ts
Adds a no-store Cache-control to requests so that they are not stored in the Cache.db for iOS
https://mattermost.atlassian.net/browse/MM-32008
> MM-32008 Do not cache request body

- app/components/reactions/index.js
- app/screens/post_options/index.js
- app/selectors/emojis.js
Cherry pick of #5121 on release-1.40.
/cc  @enahum
> Automated cherry pick of #5121

- android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
- app/screens/notification/index.tsx
- patches/react-native-navigation+7.8.1.patch
Cherry pick of #5132 on release-1.40.
/cc  @enahum
> Automated cherry pick of #5132

- app/components/autocomplete/emoji_suggestion/emoji_suggestion.js
- app/components/autocomplete/emoji_suggestion/emoji_suggestion.test.js
- app/components/emoji_picker/emoji_picker.test.js
- app/components/emoji_picker/index.js
Cherry pick of #5120 on release-1.40.
> Automated cherry pick of #5120

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
@shazm Here's a previous PR with similar changes for comparison: https://github.com/mattermost/mattermost-mobile/pull/5084
> Bump app version number to 1.40.0

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #5140 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5140

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
@shazm Here's a previous PR with similar changes for comparison: https://github.com/mattermost/mattermost-mobile/pull/5112
> Bump app build number to 342

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5142 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5142

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5151 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5151

- app/components/post_draft/draft_input/draft_input.js
Quick double taps of the send button was causing a message to be sent multiple times because, while the text input was cleared on the first tap, it was reset back to the original text on the subsequent tap.
https://mattermost.atlassian.net/browse/MM-32398
> [MM-32398] Prevent double tap of send button

- app/components/post_draft/draft_input/draft_input.js
Cherry pick of #5154 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5154

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5158 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5158

- app/components/autocomplete/at_mention_item/at_mention_item.tsx
Place (you) before username.
https://mattermost.atlassian.net/browse/MM-32661
> [MM-32661] Place (you) before username

- app/components/autocomplete/at_mention_item/at_mention_item.tsx
Cherry pick of #5168 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5168

- app/components/markdown/markdown.js
- app/components/markdown/markdown.test.js
Cherry pick of #5164 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5164

- app/components/progressive_image/progressive_image.js
- app/components/retriable_fast_image/index.tsx
- app/components/retriable_fast_image/retriable_fast_image.test.js
Cherry pick of #5167 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5167

- app/components/custom_list/channel_list_row/channel_list_row.js
- app/screens/channel_info/__snapshots__/channel_info.test.js.snap
- app/screens/channel_info/archive/archive.tsx
- app/screens/channel_info/channel_info.js
- app/screens/channel_info/leave/leave.tsx
- app/screens/more_channels/__snapshots__/more_channels.test.js.snap
- app/screens/more_channels/more_channels.js
- detox/e2e/support/ui/component/alert.js
- detox/e2e/support/ui/component/bottom_sheet.js
- detox/e2e/support/ui/component/index.js
- detox/e2e/support/ui/screen/channel_info.js
- detox/e2e/support/ui/screen/more_channels.js
- detox/e2e/test/channels/archived_channels.e2e.js
- detox/e2e/test/channels/create_public_channel.e2e.js
- Added test for MM-T3618 in `channels/archived_channels.e2e.js`
- Added new component `support/ui/component/bottom_sheet.js`
- Added/updated testIDs
JIRA: https://mattermost.atlassian.net/browse/MM-31256
TM4J Cases:
- [MM-T3618](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3618)
> MM-31256 Detox/E2E: Add e2e for MM-T3618

- app/components/channel_icon.js
- app/components/custom_list/user_list_row/__snapshots__/user_list_test.test.js.snap
- app/components/custom_list/user_list_row/user_list_row.js
- app/components/custom_list/user_list_row/user_list_test.test.js
- app/components/sidebars/main/channels_list/channel_item/__snapshots__/channel_item.test.js.snap
- app/components/sidebars/main/channels_list/channel_item/channel_item.js
- app/screens/channel_info/__snapshots__/channel_info.test.js.snap
- app/screens/channel_info/__snapshots__/channel_info_header.test.js.snap
- app/screens/channel_info/channel_info.js
- app/screens/channel_info/channel_info_header.js
- app/screens/channel_info/channel_info_header.test.js
- app/screens/more_dms/more_dms.js
- detox/e2e/support/ui/screen/channel_info.js
- detox/e2e/support/ui/screen/more_direct_messages.js
- detox/e2e/test/channel_info/header.e2e.js
- detox/e2e/test/smoke_test/group_message_channel.e2e.js
- Added tests for MM-T3213 in `smoke_test/group_message_channel.e2e.js`
- Added/updated testIDs and snap files
JIRA: https://mattermost.atlassian.net/browse/MM-30696
TM4J Cases:
- [MM-T3213](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3213)
> MM-30696 Detox/E2E: Add e2e for MM-T3213

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5173 on release-1.40.
/cc  @migbot
> Automated cherry pick of #5173

- app/screens/gallery/footer/index.tsx
- app/screens/gallery/gallery.js
- app/screens/gallery/gallery_viewer.tsx
- app/utils/images.js
This PR suggests a few updates to the animations to improve the smoothness and timing of some of the new gallery updates.
1. Speeds up the transition for opening an image from the channel list
2. Speeds up the transition for closing the gallery as well
3. Increases the sensitivity of swiping down to close the gallery
4. Speeds up and smooths out the transition of swiping between images (left/right). 
5. Speeds up the transition of the footer sliding down when tapping the share icon
https://mattermost.atlassian.net/browse/MM-31049
This PR was tested on: iOS simulator
I couldn't get Android up and running easily
> Updates to animations for new gallery

- app/components/embedded_bindings/button_binding/button_binding.tsx
- app/components/embedded_bindings/menu_binding/menu_binding.tsx
- app/mm-redux/types/apps.ts
- app/screens/channel_info/bindings/bindings.tsx
- app/screens/post_options/bindings/bindings.tsx
- app/utils/apps.test.ts
Rename URL to Path in Apps Call
https://mattermost.atlassian.net/browse/MM-31508
> [MM-31508] Rename URL to Path in Call

- app/mm-redux/client/client4.ts
- app/mm-redux/types/apps.ts
Add context to call
None
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/82
Redux: https://github.com/mattermost/mattermost-redux/pull/1379
> Add user agent to call context

- app/screens/apps_form/app_form_selector/app_form_selector.tsx
There is no state in this component, and the value is never used.
None
> Remove unneeded state reference

- app/mm-redux/client/client4.ts
Change user agent query on fetch bindings to make it more intention revealing.
None
Proxy: https://github.com/mattermost/mattermost-plugin-apps/pull/82
Webapp: https://github.com/mattermost/mattermost-redux/pull/1388
> Change user agent query on fetch bindings

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #5203 on release-1.41.
/cc  @migbot
> Automated cherry pick of #5203

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5205 on release-1.41.
/cc  @migbot
> Automated cherry pick of #5205

- fastlane/Fastfile
Need to document the new env vars for:
* IOS_API_KEY_ID
* IOS_API_ISSUER_ID
* IOS_API_KEY
* IOS_IN_HOUSE
Also add to the doc how to create a new App Store connect API Key in the [Users Page](https://appstoreconnect.apple.com/access/api) and a link for more info to take people to the [App Store Connect API Docs](https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api)
> Fix deployment of iOS to TestFlight

- fastlane/Fastfile
Cherry pick of #5208 on release-1.41.
/cc  @enahum
> Automated cherry pick of #5208

- android/app/src/main/java/com/mattermost/share/RealPathUtil.java
https://mattermost.atlassian.net/browse/MM-33495
> MM-33495 Sanitize filename in Android ShareExtension

- android/app/src/main/java/com/mattermost/share/RealPathUtil.java
Cherry pick of #5210 on release-1.41.
/cc  @enahum
> Automated cherry pick of #5210

- .circleci/config.yml
Cherry pick of #5214 on release-1.41.
/cc  @enahum
> Automated cherry pick of #5214

- android/app/src/main/java/com/mattermost/helpers/RealPathUtil.java
Apply Sanitization of the filename for the Android RealPathUtil as done in v1 #5210
> [V2] MM-33495 Sanitize filename in Android ShareExtension

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5224 on release-1.41.
/cc  @migbot
> Automated cherry pick of #5224

- app/components/emoji/emoji.js
- app/components/markdown/markdown.js
- app/components/markdown/markdown_emoji/markdown_emoji.js
- app/screens/channel_add_members/channel_add_members.js
- app/screens/search/__snapshots__/search.test.js.snap
- app/screens/search/search.js
- detox/e2e/support/ui/component/post.js
- detox/e2e/support/ui/component/post_list.js
- detox/e2e/support/ui/screen/channel_add_members.js
- detox/e2e/support/ui/screen/index.js
- detox/e2e/support/ui/screen/long_post.js
- detox/e2e/support/ui/screen/search.js
- detox/e2e/support/ui/screen/search_result_post.js
- detox/e2e/test/smoke_test/channel_add_members.e2e.js
- detox/e2e/test/smoke_test/channel_manage_members.e2e.js
- detox/e2e/test/smoke_test/message_posting.e2e.js
- detox/e2e/test/smoke_test/search.e2e.js
- detox/e2e/test/smoke_test/select_team.e2e.js
- Added tests for MM-T3197, MM-T3225, MM-T3239, MM-T3274 in
- `detox/e2e/test/smoke_test/channel_add_members.e2e.js`
- `detox/e2e/test/smoke_test/message_posting.e2e.js`
- `detox/e2e/test/smoke_test/search.e2e.js` 
- `detox/e2e/test/smoke_test/select_team.e2e.js`
- Added new component
- `detox/e2e/support/ui/screen/channel_add_members.js`
- Added new testIDs
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-30427
TM4J Cases:
- [MM-T3197](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3197)
- [MM-T3225](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T …
> MM-30427 Detox/E2E: Add e2e for MM-T3197, MM-T3225, MM-T3239, MM-T3274

- README.md
- app/constants/view.js
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/changelog
Update RequiredServer to ESR version 5.31.0
https://mattermost.atlassian.net/browse/MM-33742
> [MM-33742] Update RequiredServer

- README.md
- app/constants/view.js
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/changelog
Cherry pick of #5242 on release-1.42.
/cc  @migbot
> Automated cherry pick of #5242

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #5246 on release-1.42.
/cc  @migbot
> Automated cherry pick of #5246

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5248 on release-1.42.
/cc  @migbot
> Automated cherry pick of #5248

- app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
- app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
- assets/base/i18n/en.json
Cherry pick of #5238 on release-1.42.
/cc  @larkox
> Automated cherry pick of #5238

- app/screens/apps_form/apps_form_component.tsx
Cherry pick of #5236 on release-1.42.
/cc  @larkox
> Automated cherry pick of #5236

- app/components/embedded_bindings/button_binding/button_binding.tsx
- app/components/post_body_additional_content/post_body_additional_content.js
Several values were not taken from the right place and were not showing the bindings embedded in posts.
None
> Fix embedded bindings

- app/components/embedded_bindings/button_binding/button_binding.tsx
- app/components/post_body_additional_content/post_body_additional_content.js
Cherry pick of #5244 on release-1.42.
/cc  @larkox
> Automated cherry pick of #5244

- app/actions/views/command.ts
Cherry pick of #5259 on release-1.42.
> Automated cherry pick of #5259

- app/actions/views/command.ts
- app/actions/views/post.js
- app/components/embedded_bindings/button_binding/button_binding.tsx
- app/components/embedded_bindings/button_binding/index.ts
- app/components/embedded_bindings/menu_binding/index.ts
- app/components/embedded_bindings/menu_binding/menu_binding.tsx
- app/components/post_header/__snapshots__/post_header.test.js.snap
- app/components/post_header/post_header.js
- app/mm-redux/types/apps.ts
- app/screens/apps_form/apps_form_container.tsx
- app/screens/apps_form/index.ts
- app/screens/channel_info/bindings/bindings.tsx
- app/screens/channel_info/bindings/index.ts
- app/screens/post_options/bindings/bindings.tsx
- app/screens/post_options/bindings/index.ts
- types/actions/posts.d.ts
Cherry pick of #5256 on release-1.42.
> Automated cherry pick of #5256

- android/app/src/main/java/com/mattermost/share/RealPathUtil.java
https://mattermost.atlassian.net/browse/MM-32828
> MM-32828 Copy temp file if isMediaDocument contentUri is null

- android/app/src/main/java/com/mattermost/share/RealPathUtil.java
Cherry pick of #5269 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5269

- app/screens/search/__snapshots__/search.test.js.snap
- app/screens/search/search.js
https://mattermost.atlassian.net/browse/MM-31496
> MM-31496 Fix modifier typo in search screen

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
- app/components/at_mention/at_mention.test.js
Fixes: #5081
https://mattermost.atlassian.net/browse/MM-31874
> MM-31874 Properly use theme mention highlight color

- app/screens/gallery/footer/prepare_file/prepare_file.tsx
Fixes: #5218
https://mattermost.atlassian.net/browse/MM-33778
> MM-33778 Cancel gallery prepare file when Android's back button is pressed

- android/app/src/main/java/com/mattermost/rnbeta/MattermostCredentialsHelper.java
- patches/react-native-keychain+6.2.0.patch
Cherry pick of #5261 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5261

- app/screens/search/__snapshots__/search.test.js.snap
- app/screens/search/search.js
Cherry pick of #5267 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5267

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
- app/components/at_mention/at_mention.test.js
Cherry pick of #5268 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5268

- app/screens/gallery/footer/prepare_file/prepare_file.tsx
Cherry pick of #5270 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5270

- NOTICE.txt
Cherry pick of #5284 on release-1.42.
/cc  @amyblais
> Automated cherry pick of #5284

- app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
Cherry pick of #5278 on release-1.42.
/cc  @hanzei
> Automated cherry pick of #5278

- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/xml/app_restrictions.xml
- app/init/emm_provider.js
- app/screens/sso/index.tsx
- app/screens/sso/sso_with_redirect_url.tsx
- app/utils/general.js
- app/utils/url.js
- assets/base/i18n/en.json
Cherry pick of #5274 on release-1.41.
> Automated cherry pick of #5274

- app/components/post_list/post_list.js
- detox/.detoxrc.json
- detox/e2e/support/ui/component/alert.js
- detox/e2e/support/ui/component/post_options.js
- detox/e2e/support/ui/screen/channel.js
- detox/e2e/support/ui/screen/channel_add_members.js
- detox/e2e/support/ui/screen/channel_info.js
- detox/e2e/support/ui/screen/channel_members.js
- detox/e2e/support/ui/screen/permalink.js
- detox/e2e/support/ui/screen/thread.js
- detox/e2e/test/smoke_test/message_deletion.e2e.js
- detox/e2e/test/smoke_test/message_posting.e2e.js
- ios/Podfile.lock
- Added tests for MM-T3189, MM-T3231, MM-T3233 in
- `detox/e2e/test/smoke_test/message_deletion.e2e.js`
- `detox/e2e/test/smoke_test/message_posting.e2e.js`
- Added testIDs
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-30430
TM4J Cases:
- [MM-T3189](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3189)
- [MM-T3231](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3231)
- [MM-T3233](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3233 …
> MM-30430 Detox/E2E: MM-T3189, MM-T3231, MM-T3233

- app/database/admin/data_operator/comparators/index.ts
- app/database/admin/data_operator/handlers/index.ts
- app/database/admin/data_operator/handlers/test.ts
- app/database/admin/data_operator/operators/index.ts
- app/database/admin/data_operator/operators/test.ts
- app/database/admin/data_operator/utils/index.ts
- app/database/admin/database_manager/test.ts
- app/database/default/models/servers.ts
- app/database/server/models/channel.ts
- app/database/server/models/my_team.ts
- app/database/server/models/slash_command.ts
- app/database/server/models/team.ts
- app/database/server/schema/table_schemas/channel.ts
- app/database/server/schema/table_schemas/slash_command.ts
- app/database/server/schema/table_schemas/team.ts
- app/database/server/schema/test.ts
- types/database/channel.d.ts
- types/database/database.d.ts
- types/database/my_team.d.ts
- types/database/servers.d.ts
- types/database/slash_command.d.ts
- types/database/team.d.ts
The DataOperator is responsible for the safe handling of data in/out of the database. In here, we are working on all the entities associated to the Team section of the 'server' schemas.
https://mattermost.atlassian.net/browse/MM-33224
> MM-33224 [v2] Data Operator Team section

- app/components/profile_picture/profile_picture.js
Cherry pick of #5302 on release-1.42.
/cc  @migbot
> Automated cherry pick of #5302

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
Mentions for non existent users were being wrongly highlighted.
https://mattermost.atlassian.net/browse/MM-34714
> MM-34714 fix mention highlight to dismiss mentions for non existent users

- app/components/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
- app/components/post_attachment_opengraph/post_attachment_opengraph.js
- app/components/post_attachment_opengraph/post_attachment_opengraph.test.js
Cherry pick of #5294 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5294

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
Cherry pick of #5300 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5300

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5309 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5309

- app/components/sidebars/main/channels_list/channel_item/channel_item.js
- app/screens/about/about.js
- app/screens/settings/advanced_settings/advanced_settings.js
- app/screens/user_profile/__snapshots__/user_profile.test.js.snap
- app/screens/user_profile/user_profile.js
- app/screens/user_profile/user_profile_row.js
- detox/e2e/support/ui/component/alert.js
- detox/e2e/support/ui/screen/about.js
- detox/e2e/support/ui/screen/advanced_settings.js
- detox/e2e/support/ui/screen/channel_add_members.js
- detox/e2e/support/ui/screen/index.js
- detox/e2e/support/ui/screen/user_profile.js
- detox/e2e/test/smoke_test/about.e2e.js
- detox/e2e/test/smoke_test/advanced_settings.e2e.js
- detox/e2e/test/smoke_test/channel_add_members.e2e.js
- detox/e2e/test/smoke_test/direct_messages.e2e.js
- ios/Podfile.lock
- Added tests for MM-T3196, MM-T3210, MM-T3211, MM-T3262, MM-T3264 in
- `detox/e2e/test/smoke_test/about.e2e.js`
- `detox/e2e/test/smoke_test/advanced_settings.e2e.js`
- `detox/e2e/test/smoke_test/channel_add_members.e2e.js`
- `detox/e2e/test/smoke_test/direct_messages.e2e.js`
- Added new screens
- `detox/e2e/support/ui/screen/about.js`
- `detox/e2e/support/ui/screen/advanced_settings.js`
- `detox/e2e/support/ui/screen/user_profile.js`
- Added testIDs
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-30431
TM4J Cases:
- [MM-T3196](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T3196)
- [MM-T3210](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassia …
> MM-30431 Detox/E2E: Added e2e for MM-T3196, MM-T3210, MM-T3211, MM-T3262, MM-T3264

- app/mm-redux/client/client4.test.js
- app/mm-redux/client/client4.ts
Cherry pick of #5322 on release-1.42.
> Automated cherry pick of #5322

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5324 on release-1.42.
/cc  @migbot
> Automated cherry pick of #5324

- app/components/autocomplete/at_mention/at_mention.js
- app/components/autocomplete/channel_mention/channel_mention.js
- app/components/autocomplete/channel_mention/index.js
Cherry pick of #5327 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5327

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5331 on release-1.42.
/cc  @migbot
> Automated cherry pick of #5331

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5341 on release-1.42.
/cc  @enahum
> Automated cherry pick of #5341

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- add issue/pr templates
- Add a release not section in the PR template to facilitate the release note process.
After this PR get approval, I will setup the webhook
JIRA: https://mattermost.atlassian.net/browse/DOPS-371
This PR was tested on: N/A
N/A
```release-note
NONE
```
> add PR/Issue template and release notes section in the PR template

- app/screens/edit_post/edit_post.js
Cherry pick of #5349 on release-1.43.
/cc  @shazm
> Automated cherry pick of #5349

- android/app/src/main/java/com/mattermost/share/ShareModule.java
- share_extension/types/index.d.ts
- share_extension/utils/index.tsx
Cherry pick of #5353 on release-1.43.
/cc  @shazm
> Automated cherry pick of #5353

- app/client/rest/apps.ts
- app/mm-redux/actions/apps.ts
Cherry pick of #5316 on release-1.43.
> Automated cherry pick of #5316

- app/actions/apps.ts
- app/actions/views/command.ts
- app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts
- app/components/embedded_bindings/button_binding/button_binding.tsx
- app/components/embedded_bindings/button_binding/index.ts
- app/components/embedded_bindings/menu_binding/index.ts
- app/components/embedded_bindings/menu_binding/menu_binding.tsx
- app/screens/apps_form/apps_form_component.tsx
- app/screens/apps_form/apps_form_container.tsx
- app/screens/apps_form/index.ts
- app/screens/channel_info/bindings/bindings.tsx
- app/screens/channel_info/bindings/index.ts
- app/screens/post_options/bindings/bindings.tsx
- app/screens/post_options/bindings/index.ts
- types/actions/apps.d.ts
Cherry pick of #5304 on release-1.43.
```release-note
NONE
```
> Automated cherry pick of #5304

- app/mm-redux/actions/users.ts
Cherry pick of #5308 on release-1.43.
/cc  @enahum
> Automated cherry pick of #5308

- app/components/at_mention/__snapshots__/at_mention.test.js.snap
- app/components/at_mention/at_mention.js
Cherry pick of #5366 on release-1.43.
/cc  @enahum
> Automated cherry pick of #5366

- app/components/post_draft/__snapshots__/post_draft.test.js.snap
- app/components/post_draft/post_draft.js
- patches/react-native-keyboard-tracking-view+5.7.0.patch
Cherry pick of #5365 on release-1.43.
/cc  @enahum
> Automated cherry pick of #5365

- android/app/build.gradle
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Cherry pick of #5371 on release-1.43.
/cc  @migbot
> Automated cherry pick of #5371

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5372 on release-1.43.
/cc  @migbot
> Automated cherry pick of #5372

- detox/e2e/support/ui/component/channels_list.js
- detox/e2e/support/ui/screen/more_channels.js
- detox/e2e/test/account_settings/clock_display.e2e.js
- detox/e2e/test/account_settings/language_settings.e2e.js
- detox/e2e/test/channels/archived_channels.e2e.js
- detox/e2e/test/smoke_test/channels.e2e.js
- detox/e2e/test/teams/teams_order.e2e.js
- Added tests for MM-T291, MM-T292, MM-T304, MM-T1689, MM-T1690, MM-T1691, MM-T1692, MM-T1712 in
- `detox/e2e/test/account_settings/clock_display.e2e.js`
- `detox/e2e/test/account_settings/language_settings.e2e.js`
- `detox/e2e/test/channels/archived_channels.e2e.js`
- Stabilized tests in
- `detox/e2e/test/smoke_test/channels.e2e.js`
- `detox/e2e/test/teams/teams_order.e2e.js`
- Updated helper functions
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35073
Zephyr cases:
- [MM-T291](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T291)
- [MM-T292](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.te …
> MM-35311 Detox/E2E: Add e2e for clock settings, language settings, and archived channels

- app/components/post_draft/post_input/post_input.js
- app/components/post_draft/post_input/post_input.test.js
- app/constants/device.js
Cherry pick of #5379 on release-1.43.
/cc  @enahum
> Automated cherry pick of #5379

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5385 on release-1.43.
/cc  @migbot
> Automated cherry pick of #5385

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java
Set the app affinity to blank on Android
https://mattermost.atlassian.net/browse/MM-35992
Android 10
```release-note
NONE
```
> MM-35992 set android activity affinity to blank

- app/components/autocomplete/at_mention_item/at_mention_item.tsx
- detox/e2e/support/server_api/user.js
- detox/e2e/support/ui/component/alert.js
- detox/e2e/support/ui/component/autocomplete.js
- detox/e2e/support/ui/screen/channel.js
- detox/e2e/support/ui/screen/permalink.js
- detox/e2e/support/ui/screen/thread.js
- detox/e2e/test/autocomplete/at_mention.e2e.js
- detox/e2e/test/autocomplete/autocomplete.e2e.js
- detox/e2e/test/messaging/at_mention.e2e.js
- detox/e2e/test/smoke_test/search.e2e.js
- Added tests for MM-T168, MM-T169, MM-T170, MM-T171, MM-T172, MM-T1798, MM-T2349 in
- `detox/e2e/test/autocomplete/autocomplete.e2e.js`
- `detox/e2e/test/messaging/at_mention.e2e.js`
- Fixed duplicate name issue
- Added new testIDs, added new helper functions modified `generateRandomUser` to have shorter values, modified `getAtMentionItem` to return child elements and updated affected tests
Note: @anurag6713 I added you in this PR because I had to remove the dupe name in the autocomplete. Not sure if you're already fixing it on another PR but just making you aware that I'm removing the dupe to make the tests pass.
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35674
Zephyr cases:
- [MM-T168](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlass …
> MM-35674 Detox/E2E: Add e2e for autocomplete and at-mention

- .circleci/config.yml
> Force CI to use npm 6.14.11

- NOTICE.txt
Cherry pick of #5415 on release-1.44.
/cc  @amyblais
> Automated cherry pick of #5415

- .circleci/config.yml
Cherry pick of #5414 on release-1.44.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #5414

- fastlane/Gemfile
- fastlane/Gemfile.lock
> Fix Fastlane WebHook

- fastlane/Gemfile
- fastlane/Gemfile.lock
Cherry pick of #5424 on release-1.44.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #5424

- .circleci/config.yml
> set npm version as part of the npm-dependencies CI task
