mattermost/mattermost-mobile

- app/components/autocomplete/slash_suggestion/slash_suggestion_item.tsx
- app/components/autocomplete_selector/autocomplete_selector.js
- app/components/widgets/settings/bool_setting.js
- app/components/widgets/settings/text_setting.js
- app/screens/apps_form/apps_form_component.tsx
Add markdown to apps forms field descriptions and errors.
https://mattermost.atlassian.net/browse/MM-35179
Webapp: https://github.com/mattermost/mattermost-webapp/pull/8219
```release-note
Add markdown support for app fields descriptions and errors.
```
> Add markdown to apps forms descriptions and errors

- app/mm-redux/constants/preferences.ts
- app/selectors/emojis.js
Base skin selection on user preference selected from the desktop
[MM-35910](https://mattermost.atlassian.net/browse/MM-35910)
This PR was tested on: ios simulator
android was not tested as gradle refused to install it, I believe this is related to my machine setup and not the PR itself
```release-note
NONE
```
> [MM-35910]use user skin preferences for emoji

- app/init/global_event_handler.js
Display the option for other teams you can join after deleting cache & data.
Fixes: #5512
JIRA: https://mattermost.atlassian.net/browse/MM-36880
```release-note
Fixed a bug where the option to join another team was not present after deleting cache & data
```
> MM-36880 Load other teams you can join when deleting cache

- app/actions/views/channel.js
- app/components/post_list/index.ts
- app/components/post_list/post_list.tsx
- app/screens/channel/channel_post_list/channel_post_list.js
- app/screens/channel/channel_post_list/channel_post_list.test.js
- app/screens/channel/channel_post_list/index.js
- app/screens/thread/__snapshots__/thread.ios.test.js.snap
- app/screens/thread/thread.android.js
- app/screens/thread/thread.ios.js
- patches/react-native+0.64.2.patch
Brings back the pull to refresh functionality on channels and threads, and actually fetch the latest posts in the channel or the posts that belong to the thread depending on the screen the user is in.
JIRA: https://mattermost.atlassian.net/browse/MM-36881
```release-note
Added back pull to refresh
```
on Android we should test, check and double check that there is no performance degradation while scrolling the post list.
> MM-36881 Bring back refresh control for channels and threads

- detox/e2e/support/ui/component/alert.js
- detox/e2e/test/signin_authentication/select_server.e2e.js
- Added test for MM-T2348 in
- `detox/e2e/test/signin_authentication/select_server.e2e.js`
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35680
Zephyr cases:
- [MM-T2348](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2348)
```release-note
NONE
```
> MM-35680 Detox/E2E: Add e2e for untrusted certificate prompt

- app/screens/apps_form/apps_form_component.tsx
- assets/base/i18n/en.json
When adding a field submission response had a error that did not map to any field, it considered as if no errors occurred and closed. Now we are showing a general error specifying the field and the error.
https://mattermost.atlassian.net/browse/MM-34640
Webapp: https://github.com/mattermost/mattermost-webapp/pull/8269
```release-note
NONE
```
> MM-34640 Handle missing error on error response

- app/components/markdown/markdown_emoji/__snapshots__/markdown_emoji.test.js.snap
- app/components/markdown/markdown_emoji/markdown_emoji.js
- app/components/markdown/markdown_emoji/markdown_emoji.test.js
The markdown emoji component did not had a function to handle a hard break so a post like the one described here #5545 caused a crash.
Fixes: #5545
JIRA: https://mattermost.atlassian.net/browse/MM-37232
```release-note
Fixed a crash when a message with only emoji's includes a hard break
```
> MM-37232 Fix crash on markdown emoji with hardbreak parser

- app/init/network_manager.ts
Previously, the network manager was not waiting for the clients to be created.  This PR adds an awaits within the NetworkManager init process.
> [Gekidou] Awaiting client creation

- app/components/custom_status/custom_status_expiry.test.tsx
Quick fix on failed unit test with custom expiry status
https://github.com/mattermost/mattermost-mobile/pull/5434#issuecomment-885200233
```release-note
NONE
```
> Quick fix on failed unit test with custom expiry status

- app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
If an em dash is added to a command by introducing to dashes on iOS, it is considered as two dashes.
https://mattermost.atlassian.net/browse/MM-33891
```release-note
NONE
```
> MM-33891 Add em dash support for commands

- app/screens/channel_info/index.js
Fixed the custom status invalid prop warning issue in the ChannelInfo screen
Conversation link - https://community.mattermost.com/core/pl/33szr5jid3r3mre1hgo4r55snc
- iPhone 12 Simulator - iOS 14.4
- Android Emulator - Pixel_3a_API_30_x86 - Android 10
```release-note
Fixed the custom status invalid prop warning issue in the ChannelInfo screen
```
> Custom status warning issue fix

- patches/react-native-navigation+7.18.1.patch
- share_extension/components/channel_button.tsx
- share_extension/components/team_button.tsx
Fixes a crash when using the Android Share Extension due to changes in the `react-native-navigation` library
```release-note
NONE
```
> Fix android share extension crash

- app/actions/views/root.js
- app/components/network_indicator/network.tsx
- app/init/push_notifications.ts
- app/screens/channel/channel_base.js
When the app was sitting in the background and a user tapped on a push notification (which brings the app to the foreground) there were three issues:
1. A race condition that did not cancel the previous setTimeout
2. Two sources from where we called the function to clear the channel notifications
3. The channel id from which we needed to cancel the notifications was not being updated properly thus it used the last one set (first current channel Id)
https://mattermost.atlassian.net/browse/MM-37660
```release-note
Fixed a race condition when bringing the app to the foreground by tapping in a notification that belongs to a channel other than the current channel that cause the current channel to missed any mentions if it had any.
```
Additional note: We need to bring this fix to the Gekidou …
> MM-37660 Fix keep mention for channel A when opening a push notification on channel B

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java
At times the senderId or current user avatar will fail to fetch and the Android push notification crashes, this PR checks for the existence instead of assuming the avatar is there to prevent the crash.
https://mattermost.atlassian.net/browse/MM-37674
```release-note
Added a new config setting ServiceSettings.FooBar. Added a new column Foo to the Users table.
```
```release-note
Fixed a silent crash that could happen for some users when receiving a push notification on Android
```
> MM-37674 Fix android push notification crash

- app/components/pasteable_text_input/__snapshots__/index.test.js.snap
- app/components/pasteable_text_input/index.js
- app/components/pasteable_text_input/index.test.js
- app/components/post_draft/__snapshots__/post_draft.test.js.snap
- app/components/post_draft/draft_input/draft_input.js
- app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap
- app/components/post_draft/post_input/post_input.js
- app/components/post_draft/post_input/post_input.test.js
- app/components/post_draft/quick_actions/quick_actions.js
- app/components/post_draft/quick_actions/quick_actions.test.js
- app/components/post_draft/uploads/uploads.js
- app/components/post_draft/uploads/uploads.test.js
When uploading files by browsing files and images or when capturing a photo/video send the screenId that matches the action so that the file is attached to the right post. This also applies to pasting files.
Changes applies to both Android and iOS
https://mattermost.atlassian.net/browse/MM-37609
```release-note
Fixed attaching files to the correct post
```
> MM-37609 Specify screenId for files uploads handler

- app/mm-redux/actions/posts.test.js
- app/mm-redux/actions/posts.ts
When a message failed to post an id was being assign to the post object saved in the store that matched the `pending_post_id` so that the storage layer can do its thing.
Not sure since when, but now the server is complaining that you cannot "update an existing Post", the mobile app will now send and empty string as the post id every time we attempt to post. I wonder if the server change was done on purpose or if there is something unexpected that happened there. In any case if the change on the server was on purpose, it then should be marked as a breaking change as old app version will not be able to retry successfully to post a message with a newer server. 
https://mattermost.atlassian.net/browse/MM-37577
```release-note
NONE
```
> MM-37577 Do not set post id when posting a message

- app/components/global_threads/global_threads.tsx
- app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap
- app/components/sidebars/main/channels_list/list/list.js
- app/mm-redux/actions/threads.ts
- app/mm-redux/reducers/entities/threads.ts
- app/mm-redux/utils/channel_utils.ts
- app/screens/post_options/post_options.js
- app/screens/thread/thread_base.js
- app/store/middlewares/helpers.js
- app/store/middlewares/middleware.test.js
* Fixes app crash on opening channel header
* Fixes app crash on opening permalink from permalink screen
* Fixes showing duplicates channels while searching in "Jump to..."
* Fixes auto following the thread on opening the thread view when there are unreads
* Fixes updation of threads state (Read/Unread/Deleted) of already loaded threads
* Fixes counter showing as blank due to threads sync issue
* Doesn't show Follow Thread/Message when CRT is not enabled
https://mattermost.atlassian.net/browse/MM-37485
https://mattermost.atlassian.net/browse/MM-37602
https://mattermost.atlassian.net/browse/MM-37610
https://mattermost.atlassian.net/browse/MM-37684
https://mattermost.atlassian.net/browse/MM-37719
https://mattermost.atlassian.net/browse/MM-37522 …
> MM-37485 MM-37602 MM-37610 MM-37684 MM-37719 MM-37522 MM-37720  App crash, Sync issue fixes

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
When a notification was received on Android and the app was in the foreground we were sending the event to JS twice, this PR removes the duplication of the event being emitted.
```release-note
NONE
```
> Android Send Notification event to JS only once when the app is in the foreground

- app/components/network_indicator/network.tsx
- app/screens/edit_post/edit_post.js
When the channel is switch we clear push notifications in the drawer (if any) that belong to the channel being viewed, this was calling to mark the channel as read. Made it so it only marks the channel as read only on reconnect.
This PR also fixes the buttons blinking seen on the edit post screen every time a key was being pressed.
https://mattermost.atlassian.net/browse/MM-37840
https://mattermost.atlassian.net/browse/MM-37841
```release-note
NONE
```
> [MM-37840, MM-37841] do not mark channel as read when clearing push notifications

- app/actions/views/command.ts
- app/actions/views/post.js
- app/actions/websocket/posts.test.js
- app/components/autocomplete/slash_suggestion/slash_suggestion.tsx
- app/components/post_draft/draft_input/draft_input.js
- app/mm-redux/types/integrations.ts
- app/mm-redux/types/posts.ts
- detox/e2e/plugins/post_message_as.js
- detox/e2e/support/server_api/post.js
- detox/webhook_server.js
Removing the deprecated `Posts.ParentId`.
Not entirely sure if this can be merged prior to 6.0 release. It should be okay given we've been using rootId for a long time but we can always wait to be on the safe side. The `release-6.0` branch doesn't seem to exist yet so pointing to master for now.
https://mattermost.atlassian.net/browse/MM-29217
```release-note
Removed deprecated Posts.ParentId in favor of the semantically equivalent Posts.RootId
```
https://github.com/mattermost/mattermost-server/pull/17923
https://github.com/mattermost/enterprise/pull/1019
https://github.com/mattermost/mattermost-webapp/pull/8401
https://github.com/mattermost/mattermost-api-reference/pull/648
> [MM-29217] Remove Posts.ParentId

- app/mm-redux/utils/channel_utils.ts
Fixes filtering of unread channels with CRT
- https://mattermost.atlassian.net/browse/MM-37602
- ios 12 simulator, ios 14.4 
```release-note
NONE
```
> [MM-37602] fix channel unread filtering for CRT

- app/components/load_more_posts/load_more_posts.js
When fixing the performance issues on Android by flipping the post list instead of inverting, the component that shows a `loading messages` text was left behind. This PR fixes it.
https://mattermost.atlassian.net/browse/MM-38174
```release-note
NONE
```
> Fix upside down loading message text while scrolling the post list

- ios/MattermostShare/ChannelsViewController.swift
- ios/MattermostShare/ShareViewController.swift
Fixes a crash when trying to share content into Mattermost on iOS and the app is configured to use AppConfig with the `inAppPinCode` setting to authenticate the user with biometrics before allowing the sharing of content.
https://mattermost.atlassian.net/browse/MM-38299
Fixes: #5657
```release-note
Fixes a crash when attempting to share content into Mattermost on iOS when Biometric authentication is required.
```
To test the app needs to be enrolled with an EMM Provider and have the `inAppPinCode` setting set as `"true"`
> Fix Share extension authentication and error alerts

- app/components/sidebars/main/channels_list/switch_teams_button/__snapshots__/switch_teams_button.test.js.snap
- app/components/sidebars/main/channels_list/switch_teams_button/switch_teams_button.js
- app/components/team_icon/__snapshots__/team_icon.test.js.snap
- app/components/team_icon/team_icon.js
This PR "fixes" the starkness of the button when using a light sidebar background colour by inverting the colours.
https://mattermost.atlassian.net/browse/MM-37686
iPhone Simulator (iPhone 12, iOS 14.5)
```release-note
NONE
```
> [MM-37686] Invert colours for teams button to "fix" starkness on light backgrounds

- app/components/attachment_button/index.js
- app/components/post_draft/quick_actions/image_quick_action/index.tsx
The image picker library re-writes images to resize them and this does not support `gif` files, so they only resize the image using the first frame and not the entire gif animation. By setting the quality to be 100% the resize image processing does not take place and gifs work as expected.
https://mattermost.atlassian.net/browse/MM-38309
Fixes: #5653
```release-note
Fixed upload of animated gif files on Android
```
> Do not resize images to upload

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Android has a feature where a user can snooze notifications, this notifications are snoozed on a per-channel basis, to handle it properly notifications needs to have a group summary which was not being created if notifications where manually dismissed at some point. This PR makes sure that when all notifications from a channel are cleared or dismissed the next notification will then create a group summary, ensuring that every notification being displayed has one and can be snoozed accordingly.
N/A
```release-note
Fixed ability to snooze push notifications on Android
```
> Properly handle notification snooze on Android

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
With this PR we are going to clean up the share preferences that hold notification tracking when a new version is installed. We do this to ensure that notifications are in sync with the drawer as when you install a new version notifications from the drawer get removed.
```release-note
NONE
```
> Android clear notification preferences on version change

- app/screens/channel_info/bindings/bindings.tsx
- app/screens/channel_info/channel_info_row.js
Channel Info row is expecting a textID and default message in order to create a `<FormattedText>` component for the element label. This created lots of warnings for bindings, since they are not system defined, and therefore have not a translation in the i18n bundle. This also could create some issues if coincidentally, the formed text id that was being formed became the same as some translation id we have in the system.
In order to solve this, we have removed the requirement of the text id, and only create the `<FormattedText>` field when it is given.
Another solution would have been to move the localization out of this component, and let the elements be directly the component to render (or the translated text), but that solution would imply a bigger changelog.
None
```release-note
None …
```
> Fix warnings on channel info row Formatted Text

- app/components/post_list/post/body/content/embedded_bindings/button_binding/button_binding.tsx
- app/components/post_list/post/body/content/embedded_bindings/menu_binding/menu_binding.tsx
- app/screens/apps_form/apps_form_component.tsx
- app/screens/channel_info/bindings/bindings.tsx
- app/screens/post_options/bindings/bindings.tsx
Previously, bindings in other locations than commands will always submit, ignoring fields like "form". Now, if a binding has a form, it will automatically open the app form without communicating with the app.
Webapp: https://github.com/mattermost/mattermost-webapp/pull/8784
None
```release-note
NONE
```
> Open forms in bindings on all locations

- app/client/rest/posts.ts
- app/mm-redux/actions/search.ts
- app/screens/search/channel_display_name/__snapshots__/channel_display_name.test.js.snap
- app/screens/search/channel_display_name/channel_display_name.js
- app/screens/search/channel_display_name/channel_display_name.test.js
- app/screens/search/channel_display_name/index.js
- app/screens/search/channel_display_name/index.test.js
Previously, channel mentions and saved posts only showed you the results for the current team. This PR makes it possible to show for several teams.
Saved posts should work fine with any server version for normal users. Sysadmins will be shown messages from channels/teams they are not members from, which may create some bugs. Those are addressed in this PR: https://github.com/mattermost/mattermost-server/pull/18380
Multiteam mentions require changes in the server, which are in this PR: https://github.com/mattermost/mattermost-server/pull/18371
This PR would open the path to allow multi-team search both on front and back-end. We just need to clarify how do we specify the team or all teams in the search query.
In contrast to Webapp, opening threads from a different team was possible before …
> [MM-38216] Add multiteam mentions and saved posts

- share_extension/screens/channel_list.tsx
- share_extension/screens/team_list.tsx
Fixing Android crash on the share extension when clearing a previous channel search
https://mattermost.atlassian.net/browse/MM-38855
Fixes: #5693
```release-note
Fixed a crash when clearing a previous channel search done in the Android Share Extension
```
> Fix android extension crash

- app/actions/local/channel.ts
- app/actions/remote/entry.ts
- app/actions/remote/retry.ts
- app/actions/remote/team.ts
- app/actions/remote/user.ts
- app/client/rest/teams.ts
- app/database/models/server/my_team.ts
- app/database/operator/server_data_operator/handlers/team.test.ts
- app/database/operator/server_data_operator/transformers/team.test.ts
- app/database/operator/server_data_operator/transformers/team.ts
- app/database/schema/server/table_schemas/my_team.ts
- app/database/schema/server/test.ts
- app/queries/servers/entry.ts
- app/queries/servers/team.ts
- ios/Mattermost/MattermostManaged.m
- types/api/teams.d.ts
- types/database/models/servers/my_team.d.ts
- types/database/raw_values.d.ts
Removes the myTeam data that holds team unreads as well as removes request to fetch team unreads from the server. We will rely on the info in MyChannel as the source of truth for unreads
```release-note
NONE
```
> Remove team unreads and rely on channel member instead

- app/components/post_draft/draft_input/draft_input.js
- app/components/post_draft/draft_input/draft_input.test.js
- app/utils/draft.js
- assets/base/i18n/en.json
PR makes `@here` mentions trigger a confirmation modal, similarly to `@all` and `@channel` when `EnableConfirmNotificationsToChannel` is set.
https://mattermost.atlassian.net/browse/MM-31389
```release-note
Included @here mentions in the `EnableConfirmNotificationsToChannel` config setting.
```
https://github.com/mattermost/mattermost-webapp/pull/8852
> [MM-31389] Show confirm modal for `@here` mentions

- app/components/sidebars/main/channels_list/list/list.js
Fixes a crash on android as the JS prototype for `replaceAll` has not been added to the version of JSC that ships with Android, this is now replaced with a regular expression with the `replace` function instead.
```release-note
NONE
```
> fix android crash: change replaceAll with replace as is not available on some JSC

- android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/xml/app_restrictions.xml
- app/queries/app/servers.ts
- app/screens/server/form.tsx
- app/screens/server/index.tsx
- assets/base/config.json
Following https://github.com/mattermost/mattermost-mobile/pull/5663 now we check if the server is already being used by checking the server identifier, this way we prevent adding the same server twice, even if the user enters a different url for the same server.
In a similar way we also check if the display name to inform the user in case they already have another server registered with the same name.
Also added a default setting in the `config.json` that allows to set a default server name as well as we are including an EMM managed configuration to set a default server name.
https://mattermost.atlassian.net/browse/MM-39735
Not related to this ticket: I've added a small fix for Android push notifications.
```release-note
NONE
```
> [Gekidou] Unique servers

- app/components/sidebars/main/channels_list/channels_list.js
- assets/base/i18n/en.json
Cherry pick of #5797 on release-1.48.
/cc  @cwarnermm
```release-note
NONE
```
> Automated cherry pick of #5797

- patches/@react-native-community+netinfo+6.0.4.patch
It has been reported that the netInfo library is causing high battery consumption https://github.com/react-native-netinfo/react-native-netinfo/issues/178 as it performs repeated reachability tests to determine if the device has internet connection. We don't really make use of this functionality as we have our own implementation to check if the server is reachable or not, thus disabling this functionality should at least attempt to reduce the battery consumption.
```release-note
NONE
```
> Disable reachability test

- patches/@react-native-community+netinfo+6.0.4.patch
Cherry pick of #5812 on release-1.48.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #5812

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Cherry pick of #5828 on release-1.48.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #5828

- android/app/src/main/AndroidManifest.xml
Android 11 onwards (API 30+) Android hides all other apps and services which are not part of the core system apps/services by default, this PR adds a query to the Android Manifest to allow Mattermost to open the YouTube app.
```release-note
Fixed opening the YouTube app from within Mattermost
```
> Added YouTube query to Android Manifest

- app/components/markdown/markdown_image/markdown_image.js
- app/components/markdown/markdown_table_image/markdown_table_image.tsx
- app/utils/images.test.ts
- app/utils/images.ts
Fixes a crash for markdown table images when the source does not match cause of the use of an image proxy and also adds support for inline SVG images in markdown
SVG's can cause a slight pop as we don't have the dimensions before hand.
https://mattermost.atlassian.net/browse/MM-40530
```release-note
* Fixed a crash on markdown table images
* Added SVG support for markdown inline images
```
> MM-40530 Support SVG for markdown inline images

- app/actions/views/root.js
- app/actions/views/user.js
- app/actions/websocket/index.ts
- app/init/fetch.js
- app/init/fetch.test.js
- app/init/global_event_handler.js
- app/init/global_event_handler.test.js
- app/mm-redux/reducers/entities/general.ts
- app/utils/general.js
Currently with the special deployment of community the app can become **unusable** and is totally unresponsive.
What cause this behavior is that community deployment uses different pods to provide HA as for some reason it reports the `x-version-id` with different hashes, this was causing the app to detect a "new" version and to update the config & license in a constant loop blocking the UI.
In this PR we made a few changes in behavior, first of all the server version being recorded is only the semantic version, so they'll always be the same as long as the server is not upgraded. Apart from this, whenever we receive a new config or license we are executing a deep comparison with the value that we currently have in the store to determine if it needs to be updated or not.
The config & …
> Gracefully handle different x-version-id being reported

- app/actions/websocket/index.ts
- app/actions/websocket/system.ts
This PR handles the following teams websocket events:
Websocket handler is removed, however the costant is not.  `WebsocketEvents.HELLO` is being used here. 
https://github.com/mattermost/mattermost-mobile/blob/gekidou/app/client/websocket/index.ts#L226
These values were stored when initially loaded in the WDB, but not included in the websocket license data. On a websocket event, the client information is sanitized with `GetSanitizedClientLiense()` whichi removes the following.
```
"SkuName":"Mattermost Enterprise Edition E10 - 12 Month End User Subscription",
"StartsAt":"1614574800000",
"Name":"Joram Wilander",
"SkuShortName":"E10",
"ExpiresAt":"1646110800000",
```
https://mattermost.atlassian.net/browse/MM-39729
```release-note
```
> [Gekidou MM-39729] Websocket Events - hello, license, config

- ios/Mattermost/Info.plist
Adding audio background capability to iOS build to allow calls to stay on when app goes into background.
https://mattermost.atlassian.net/browse/MM-41753
```release-note
NONE
```
> [MM-41753] Calls: keep audio on when app is on background

- app/components/markdown/markdown_image/index.js
- app/components/markdown/markdown_image/markdown_image.js
- app/components/markdown/markdown_table_image/index.js
- app/components/markdown/markdown_table_image/markdown_table_image.tsx
- package-lock.json
- patches/react-native-svg+12.1.1.patch
Apparently servers that use the image proxy does not properly return svg images and thus the library throws an error trying to parse an empty string instead of a valid xml.
The webapp does handle this by rendering a broken image, this PR aims to do the same as the webapp.
As seen in this image, the image proxy does not return the svg image
I would advice to look into the reason why the image proxy does not handle this and return an empty body.
https://mattermost.atlassian.net/browse/MM-41879
```release-note
NONE
```
> Fix when SVG uri does not return data in the url

- app/actions/views/root.js
- app/init/push_notifications.ts
- app/types/push_notification.d.ts
With the introduction of this PR https://github.com/mattermost/mattermost-push-proxy/pull/87 Push notifications on iOS will now wake the app if it was not running so we need to make the init process to NOT treat the `initial notification` as the app being opened by tapping on it. So essentially after you received the notification, if the app icon is pressed it should open the application but not switch to the channel of the incoming notification.
This in needed in preparation for the alpha release as the push proxy will need to be updated by then.
```release-note
NONE
```
> Make iOS notifications compatible with background fetch (v1)

- app/components/sidebars/settings/__snapshots__/settings_sidebar.test.js.snap
- app/components/sidebars/settings/settings_sidebar.test.js
- app/components/sidebars/settings/settings_sidebar_base.js
- app/constants/custom_status.ts
- app/screens/custom_status/custom_status_modal.tsx
Fixes issue where setting a custom status fails silently as the sidebar always closes after the request is completed (where it is successful or not). This PR keeps the sidebar open if setting a custom status fails so the error is visible to the user, and closes the sidebar when the request is successful.
Fixes [MM-39149](https://mattermost.atlassian.net/browse/MM-39149)
- iPhone 13, iOS 15.2
https://user-images.githubusercontent.com/23694620/154714636-6430f2fb-b40e-45fc-a4ed-6b1f08b74931.mp4
```release-note
NONE
```
> [MM-39149] Setting a Custom Status is Failing Silently

- app/components/post_list/post/post.tsx
- app/database/operator/server_data_operator/handlers/post.ts
This PR fixes a couple of things:
1. The handler onPress for the Post component was not calling `removePost` when the post was deleted.
2. The more important fix is the operator for `handlePosts` here are are only storing the posts that were fetch that have not been deleted and we are removing from the database any post that was deleted on the server that we still have in the database.
```release-note
NONE
```
> [Gekidou] Post removal

- app/actions/websocket/category.ts
For some strange reason when saving/unsaving a post or anything else that triggers a preference change also triggers a category updated websocket event (which in itself is bug). Regardless this PR adds some defensive code just in case.
```release-note
NONE
```
> [Gekidou] Fix categories WS action

- app/actions/remote/role.ts
- app/actions/websocket/preferences.ts
- app/database/models/server/channel.ts
- app/database/models/server/team.ts
- app/database/operator/server_data_operator/handlers/channel.test.ts
- app/database/operator/server_data_operator/handlers/channel.ts
- app/database/operator/server_data_operator/handlers/reaction.test.ts
- app/database/operator/server_data_operator/handlers/reaction.ts
- app/database/operator/server_data_operator/handlers/user.test.ts
- app/database/operator/server_data_operator/handlers/user.ts
- app/database/operator/server_data_operator/index.ts
- app/database/operator/server_data_operator/transformers/channel.test.ts
- app/database/operator/server_data_operator/transformers/channel.ts
- app/database/operator/server_data_operator/transformers/user.test.ts
- app/database/operator/server_data_operator/transformers/user.ts
- app/database/operator/utils/reaction.ts
- app/queries/servers/categories.ts
- app/queries/servers/channel.ts
- app/queries/servers/post.ts
- app/queries/servers/team.ts
- types/database/models/servers/channel.d.ts
- types/database/models/servers/team.d.ts
Fixes in this PR:
1. at times for very old server data we were attempted to fetch an empty role which returns `null` by the server, now we are filtering empty roles (string) before fetching
2. The reactions handler was deleting all other reactions that matched the same emoji name on a post, basically each post could have one reaction per emoji as we were using the `getUniqueRawsBy` helper that receives only one key and in this case was the `emojiName`, as we get the list of all reactions from the post, is safe to compare them all and not only a filtered one.
3. prepareDeleteTeams, prepareDeleteChannels & prepareDeletePosts iterate over their relations and children to delete them as well, some of those may not have records and an error is thrown, here we made it safe so it does not throw …
> [Gekidou] various fixes

- app/actions/remote/entry/app.ts
- app/actions/remote/entry/common.ts
- app/actions/remote/entry/notification.ts
- app/actions/websocket/index.ts
- app/components/team_sidebar/team_sidebar.tsx
- app/queries/servers/team.ts
There was a race condition caused by the team_sidebar where we fetched other teams as the screen could've mount before finishing with the requests in the background on a normal or push notification app entry, this could conflict with team record preparation.
On top of that the conflict was mainly cause we use to delete all teams that we had no membership present in the fetch response, this was changed to only delete the teams if you were previously a member and are no longer.
```release-note
NONE
```
> Fixes a race condition and deleting only teams that you no longer belong to

- app/actions/local/category.ts
Only custom categories are pruned.
Fixes https://mattermost.atlassian.net/browse/MM-42166
```release-note
```
> Filters to prune only custom categories

- app/screens/settings/timezone/select_timezone/__snapshots__/select_timezone.test.js.snap
- app/screens/settings/timezone/select_timezone/select_timezone.js
Also some small code improvements:
- renamed header to searchBar
- moved searchBarInput to getStyleSheet
Both of which are logical to me and are more consistent with e.g. screens/channel_members
Fix the search bar to be consistent with the manage members search bar
Fixes https://github.com/mattermost/mattermost-server/issues/16244#event-6194983442
Fixes https://mattermost.atlassian.net/browse/MM-23644
This PR was tested on: iPhone 11, iOS 15.3.1
```release-note
Changed search bar in manual time zone selection view to be consistent with the rest of the app
```
> Fix time zone settings search bar (MM-23644)

- app/products/calls/store/reducers/calls.test.js
- app/products/calls/store/reducers/calls.ts
- Switching to a different app and back results in blank CallScreen and losing call status (even though the call is still connected working the same as before the app switch). Affected both Android and iOS.
- Fix: don't erase the joined state when receiving new calls data (which happens on every reconnect)
- Looking at the code, I can't think of a way this would affect the rest of the calls product, and I tested with both OSes. 
- https://mattermost.atlassian.net/browse/MM-42358
- n/a
```release-note
Fixed a bug that resulted in dropping the Call state when switching to another app and returning.
```
> MM-42358: Calls Mobile: Android/iOS switching app bugs

- app/actions/remote/post.ts
When a message failed (or took some time to be created in the server) was not being added to the database.
This was due to `delete_at` not defined, and used to do a filter on the database layer. I decided to define `delete_at` instead of checking in the database for 0 or undefined.
None
```release-note
NONE
```
> Fix message not being added to the database when it fails

- app/components/channel_list/header/__snapshots__/header.test.tsx.snap
- app/components/channel_list/header/header.tsx
- app/components/floating_text_input_label/index.tsx
- app/screens/home/account/index.tsx
- app/screens/home/channel_list/channel_list.tsx
- app/screens/home/index.tsx
- app/screens/login/form.tsx
- app/screens/login/index.tsx
- app/screens/server/form.tsx
- app/screens/server/header.tsx
- app/screens/server/index.tsx
- detox/e2e/init.js
- detox/e2e/support/server_api/system.js
- detox/e2e/support/test_config.js
- detox/e2e/support/ui/component/alert.js
- detox/e2e/support/ui/component/index.js
- detox/e2e/support/ui/screen/account.js
- detox/e2e/support/ui/screen/channel_list.js
- detox/e2e/support/ui/screen/home.js
- detox/e2e/support/ui/screen/index.js
- detox/e2e/support/ui/screen/login.js
- detox/e2e/support/ui/screen/server.js
- detox/e2e/support/utils/email.js
- detox/e2e/test/server_login/connect_to_server.e2e.js
- detox/e2e/test/server_login/login_by_email.e2e.js
- detox/e2e/test/smoke_test/server_login.e2e.js
- Added initial test cases for server connection and login
- Created associated zephyr test cases under `Mobile V2` folder
Mobile V2/Smoke Test:
[MM-T4675](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4675)
Mobile V2/Server Login:
[MM-T4676](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4676)
[MM-T4677](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4677)
Note: So as not to balloon this PR and future PRs, I'll create separate PRs for test cases …
> MM-41855 Detox/E2E: Initial e2e tests in Gekidou

- app/components/markdown/markdown.js
- app/components/markdown/markdown.test.js
Support link highlighting on capitalized link scheme. A _scheme_ refer to the first part of a URL, such as `https://`. Currently, `https://` gets highlighted, but `Https://` (capital H) does not. 
As a fix, ignore capitalization to highlight both versions. (This is useful, since on mobile, most users have auto-capitalize sentence turned on, which capitalizes the first character of a sentence / message.)
Added some unit tests to verify the functionality.
Jira ticket: [29280](https://mattermost.atlassian.net/browse/MM-29280)
Note: this Jira ticket mentioned Android, but I fixed this on iOS. However, the issue seems pretty universal to me.
This PR was tested on: iPhone 12, iOS 15.1.1
```release-note
Added support for link highlighting when a capitalized link scheme, such as Https:// instead …
```
> Support link highlighting on capitalized link scheme

- app/actions/local/file.ts
- app/components/post_list/post/body/files/files.tsx
- app/components/post_list/post/body/files/index.ts
- app/components/post_list/post/body/files/video_file.tsx
- app/components/post_list/post/body/index.tsx
- app/components/post_list/post/index.ts
- app/components/post_list/post/post.tsx
- app/database/operator/server_data_operator/transformers/post.ts
- app/queries/servers/file.ts
- app/screens/gallery/footer/download_with_action/index.tsx
- app/screens/gallery/video_renderer/index.tsx
- app/utils/file/index.ts
- assets/base/i18n/en.json
- ios/patches/SessionDelegate.patch
- types/screens/gallery.d.ts
Start using the file `localPath` when available.
When we upload files, the files set a `localPath` that initially was being overwritten by the createPost action, with these changes we are making sure that if the `localPath` is set is not overwritten. Also the files component now check if the `localPath` still exists as the OS could delete them as they are in the cache folder, and if still present we use that instead of fetching the file again.
For video playback, if the video cannot be stream (current issue with community) we allow the users to download the video and then we set a `localPath` for the file record.
Finally this PR also includes a fix to the Alamofire patch to check for the uncompress bytes header in lowercase as well the same way Android does it.
```release-note
NONE
```
> [Gekidou] Use localPath when available

- app/screens/settings/theme/__snapshots__/theme.test.js.snap
- app/screens/settings/theme/theme.js
Can't confirm by scrolling if `custom theme` is checked (in Advanced Settings > Display > Theme Screen) using an Android Emulator
https://mattermost.atlassian.net/browse/MM-42533
Samsung Galaxy M31 - Android 11
Android Emulator M1 Preview
iPhone 13 Simulator - iOS 15.2
> [MM-42533] Fix hidden custom theme

- tsconfig.json
Exclude typescript check in detox folder from the main app, detox has its own typescript configuration and we prevent ts check from failing if the node modules from the detox folder have not been installed.
Merging right away but this is an FYI for @josephbaylon 
```release-note
NONE
```
> [Gekidou] Exclude detox from typescript check

- app/components/markdown/index.tsx
Currently we don't support latex on mobile but there is some work in progress for that and the commonmark library now expects a renderer for it, until we add support we'll be using the paragraph renderer instead to avoid the crash.
```release-note
NONE
```
> Fix crash when latex is used

- app/components/markdown/markdown.js
- package-lock.json
With the updated commonmark library the parser takes into account latex which had no renderer assigned, and this caused the app to crash.
In this PR we are assigning the renderer to be just a regular paragraph as #5651 should include the rendering of the latex code.
This PR also includes a small change in determine if markdown images have a size set (this just avoids a prop type warning being displayed in dev mode)
https://mattermost.atlassian.net/browse/MM-42624
```release-note
Fixed crash when attempting to render latex code present in a message
```
> [v1] Prevent crash when latex is used

- app/components/friendly_date/index.tsx
There is a flaky test for the `FriendlyDate` component, where a date's value is being truncated while being slightly lower than the intended value, resulting in the number being a whole number lower than the intended value. It's unclear exactly what is causing the flaky test, but it may have something to do with daylight savings time.
This PR makes it so we first round to the nearest tenth before taking the `Math.floor` of the number. This makes it so `9.958333333333334` is rounded to `10.0` before taking the floor.
See https://app.circleci.com/pipelines/github/mattermost/mattermost-mobile/13663/workflows/77d1d1f1-0bbb-4cde-91ec-15ff8f624328/jobs/21150 and https://community-daily.mattermost.com/core/pl/6w31xfko9f84dgqgy4e9gw5s6c
Fixes https://mattermost.atlassian.net/browse/MM-42707
> FriendlyDate component - Round dates to nearest 10th before taking floor

- app/components/post_list/post/header/index.ts
- app/components/post_list/thread_overview/index.ts
- app/queries/servers/post.ts
The current query to get replies count is querying `postsInThread` table to get the timestamps and returning a different count. This will query the table with the given root Id.
This PR was tested on: Android 11
```release-note
NONE
```
> Gekidou - Replies count query fix

- app/screens/edit_server/form.tsx
- app/screens/edit_server/header.tsx
- app/screens/edit_server/index.tsx
- app/screens/server/index.tsx
- detox/e2e/support/server_api/user.ts
- detox/e2e/support/ui/component/alert.ts
- detox/e2e/support/ui/screen/edit_server.ts
- detox/e2e/support/ui/screen/index.ts
- detox/e2e/support/ui/screen/server.ts
- detox/e2e/test/server_login/server_list.e2e.ts
- detox/e2e/test/smoke_test/server_login.e2e.ts
- Added e2e for server list
- Created associated zephyr test cases under `Mobile V2` folder
Mobile V2/Smoke Test: Added step for adding new server
[MM-T4675](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4675)
Mobile V2/Server Login: Added several steps for Server List e2e
[MM-T4691](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4691)
https://mattermost.atlassian.net/browse/MM-42406
```release-note
NONE
```
> Detox/E2E: Server List e2e tests in Gekidou

- app/database/models/server/user.ts
- app/database/operator/server_data_operator/handlers/reaction.ts
- app/database/operator/server_data_operator/transformers/reaction.test.ts
- app/database/operator/server_data_operator/transformers/reaction.ts
- app/database/operator/server_data_operator/transformers/user.test.ts
- app/database/operator/server_data_operator/transformers/user.ts
- app/database/schema/server/table_schemas/user.ts
- app/database/schema/server/test.ts
- app/utils/user/index.ts
- types/database/models/servers/user.d.ts
When fetching users for shared channels, they will have a 'remote_id' property set in their user profile server response.  With this PR, we are creating a new field in the Users table schema and propagating this change throughout the database and codebase. 
https://mattermost.atlassian.net/browse/MM-42787
```release-note
NONE
```
> MM-42787 - Gekidou User DB field remote_id

- app/actions/remote/channel.ts
- app/actions/remote/entry/app.ts
- app/actions/remote/entry/notification.ts
- app/database/operator/server_data_operator/transformers/channel.ts
- app/init/credentials.ts
- app/utils/user/index.ts
1. when using multiple servers it was always setting as the initial url the first server that had credentials registered instead of the active server, this cause the requests to be executed for the wrong initial server first
2. Attempt to improve the update of the DM display name to avoid empty strings
3. Made it so that DMs and GMs do not display `Someone`
4. Start fetching the data for other servers after the initial server finishes fetching initial load.
```release-note
NONE
```
> [Gekidou] multi server fixes

- app/products/calls/components/__snapshots__/call_avatar.test.js.snap
- app/products/calls/components/call_avatar.tsx
- app/products/calls/screens/call/__snapshots__/call_screen.test.js.snap
- app/products/calls/screens/call/call_screen.tsx
- Polish a few UI rough edges:
- Current speaker indicator (the halo effect) didn't match the webapp's. Fixed that for iOS, and closer (but not exact) for android.
- The microphone icon was a too high on iOS when the avatars were small (when screensharing)
- The raised hand icon was a too low on Android
- The user's own name now has the `(you)` identifier, matching the webapp.
- https://mattermost.atlassian.net/browse/MM-42790
- https://mattermost.atlassian.net/browse/MM-42791
- iOS simulators
iOS before:
iOS after: 
Android before:
Android after:
```release-note
Polished UI for Calls.
```
> MM-42790 MM-42791 - UI Polish

- app/database/models/server/team.ts
- app/database/models/server/thread.ts
- app/database/models/server/thread_in_team.ts
- app/database/operator/server_data_operator/handlers/thread.test.ts
- app/database/operator/server_data_operator/handlers/thread_in_team.ts
- app/database/operator/server_data_operator/transformers/thread.ts
- app/database/schema/server/table_schemas/thread.ts
- app/database/schema/server/table_schemas/thread_in_team.ts
- app/database/schema/server/test.ts
- types/database/models/servers/thread.d.ts
- types/database/models/servers/thread_in_team.d.ts
- types/database/raw_values.d.ts
The convention is that only threads being in the `ThreadsInTeam` will be shown in a thread list,
and that only threads marked as `loaded_in_global_threads` are being shown
in the _All Threads_ tab in the list.
So when a thread arrives through different means, whether it's a WS event,
or just fetching a (*new) thread by opening it in a channel, etc...
we'll need to check if it's newer than any of the existing threads in the _All Threads_ list.
If it is it will be added in the `ThreadsInTeam` and will be marked as `loaded_in_global_threads: true`.
If it's not newer but it is an unread thread it will still be added in the `ThreadsInTeam`
but marked as `loaded_in_global_threads: false`.
This commit refactors `loaded_in_global_threads` field from the `Thread` table
to the `ThreadsInTeam` table …
> [Gekidou DB]: Refactors thread and threads_in_team tables

- app/components/edit_channel_info/index.js
- app/constants/view.js
- app/screens/edit_channel/edit_channel.js
This is part of a series of pull requests aim to reduce the limit of channel display name as well as channel URL (referred to as name) to one character assuming there are no technical reasons for the 2 char limit.
Note: It seems to me that the create channel screen does not give user the ability to change the channelURL but they are allowed to do so in the editing screen. For this PR, my change is mainly on the editChannel screen. I noticed that the minLength limit is not enforced so I had added that validation as well.
Fixes https://github.com/mattermost/mattermost-server/issues/19788
JIRA: https://mattermost.atlassian.net/browse/MM-41909
Related PR: https://github.com/mattermost/mattermost-server/pull/19845
```release-note
NONE
```
> MM-41909: Allow 1 char channel name

- app/components/post_list/index.tsx
For some unknown reason we had the useEffect to listen to a dep change for a ref.current which caused the list to scroll to the bottom as the ref current object changed.
The reality is that refs should not be part of effect dependencies, so that was wrong in the first place, and secondly this also fixes the fact that the list was being scrolled to the bottom causing a UX problem.
```release-note
NONE
```
> PostList do not scroll to bottom after the first onEndReached

- ios/Podfile.lock
- package-lock.json
- package.json
- patches/@rudderstack+rudder-sdk-react-native+1.2.1.patch
- patches/@stream-io+flat-list-mvcp+0.10.1.patch
- patches/react-native-hw-keyboard-event+0.0.4.patch
- Bump up version of `@mattermost/react-native-emm` to `1.2.1` (https://github.com/mattermost/react-native-emm/pull/7)
- Apply patches for `@rudderstack/rudder-sdk-react-native`, `@stream-io/flat-list-mvcp`, `react-native-hw-keyboard-event`
- This so `./gradle assembleAndroidTest` builds successfully on android.
```release-note
NONE
```
> Apply patch for minSdkVersion

- app/actions/local/thread.ts
- app/actions/remote/thread.ts
- app/database/models/server/team.ts
- app/database/models/server/thread.ts
- app/database/models/server/thread_in_team.ts
- app/database/operator/server_data_operator/handlers/thread.test.ts
- app/database/operator/server_data_operator/handlers/thread.ts
- app/database/operator/server_data_operator/handlers/thread_in_team.ts
- app/database/operator/server_data_operator/transformers/thread.ts
- types/api/threads.d.ts
- types/database/database.d.ts
`loadedInGlobalThreads` cannot be a property of the thread, the DB will
fail with unknown column upon saving.
This commit adds it as an argument of `handleThreads`,
and `handleThreadInTeam`.
Fixes wrong `foreignKey` in THREAD table associations.
```release-note
NONE
```
> [Gekidou HOTFIX] fixes saving threads in the DB

- app/actions/local/channel.ts
- app/actions/remote/post.ts
LastPostAt was not being updated as the prepare function was always returning `undefined` instead of the prepared model, apart from that we needed to update the last post at when posting a new message
```release-note
NONE
```
> [Gekidou] Fix update lastPostAt

- app/components/post_list/combined_user_activity/combined_user_activity.tsx
- app/components/post_list/post/body/reactions/reactions.tsx
- app/components/post_list/post/post.tsx
- app/components/post_list/thread_overview/thread_overview.tsx
- app/screens/bottom_sheet/index.tsx
- app/screens/navigation.ts
Instead of setting the BottomSheet initialSnap to the opened index, we set it to the one closed and set the value of `enabledBottomInitialAnimation` so that it does not animate automatically. Then on mount, we snap to the initial index so that the animation run smoothly.
We now are passing options to `showModalOverCurrentContext` when opening the bottom sheet, to remove the alpha animation on the modal.
in the bottom sheet component, I added a ref for `firstRun` so that when `close` triggers the first time it does not do anything until we animate the bottom sheet to open for the first time (as soon as the component mounts).
https://mattermost.atlassian.net/browse/MM-42698
```release-note
NONE
```
> [Gekidou] Fix bottom sheet initial animation

- app/screens/create_direct_message/create_direct_message.tsx
When searching for a user the display name of the channel was set incorrectly as we were looking into the loaded profiles instead of the selected profiles.
```release-note
NONE
```
> [Gekidou] Fix create DM when searching profile

- app/queries/servers/thread.ts
While going through the code I notice that we are calling getConfig but not using it; hence, this PR removes it.
```release-note
NONE
```
> Gekidou - Removed redundant getConfig call

- app/components/channel_list/categories/categories.tsx
- app/components/channel_list/categories/index.ts
- app/queries/servers/channel.ts
This PR fixes the unreads category section by:
* Observe the value column of the preferences in case the unreads section preferences toggle its value
* Exclude archived channels from the unreads category section
* To be able to scroll through all categories including the unreads one, we now include the render on the section in the `renderItems` of the Categories FlatList, without it if there are enough unreads scrolling to other categories is impossible.
https://mattermost.atlassian.net/browse/MM-43326
```release-note
NONE
```
> [Gekidou] unreads category section

- app/components/channel_list/header/header.test.tsx
- app/components/channel_list/header/header.tsx
- app/components/channel_list/header/plus_menu/item.tsx
- app/components/channel_list/index.test.tsx
- app/components/markdown/at_mention/at_mention.tsx
- app/components/markdown/markdown_code_block/index.tsx
- app/components/markdown/markdown_image/index.tsx
- app/components/markdown/markdown_link/markdown_link.tsx
- app/components/post_list/post/body/failed/index.tsx
- app/screens/edit_profile/components/profile_image_picker.tsx
- app/screens/home/account/components/options/user_presence/index.tsx
- app/utils/helpers.ts
- test/intl-test-helper.tsx
This PR adds a helper to set the snapPoints of the Bottom Sheet.
in this PR the following BottomSheets are now using the helper:
* Home screen plus menu
* At Mention long press
* Markdown code block long press
* Markdown image long press
* Markdown link long press
* Post failed
* Edit profile picture (account screen)
* Profile status (account screen)
https://mattermost.atlassian.net/browse/MM-42746
```release-note
NONE
```
> [Gekidou] bottomSheet snapPoint helper

- app/components/jumbo_emoji/index.tsx
- app/components/post_list/more_messages/more_messages.tsx
- app/components/post_list/post/body/files/files.tsx
- app/screens/bottom_sheet/index.tsx
* [Fix JumboEmoji cutoff on Android](https://github.com/mattermost/mattermost-mobile/commit/4540670e73b75dfb11cb51d5f2cc7c219e857794) by setting the lineHeight for the new line separator
* [MM-43604 Fix More messages bar position](https://github.com/mattermost/mattermost-mobile/commit/900d7b163392d37b3589212dece644c5a323b630) by setting different values for iOS, Tablet and Android
* [MM-43532 Fix tap next to a single image to open trigger onPress](https://github.com/mattermost/mattermost-mobile/commit/00e56d9c5b0338d9833d792a396c296c84d87c1f) By removing the flex container for single attachments
* [MM-43606 Show backdrop when canceling the bottom sheet close](https://github.com/mattermost/mattermost-mobile/commit/34f8d12d83d786a34ca7ef67002565c0a0456dc3) by reverting the opacity when the …
> [Gekidou] bugs squash

- app/screens/select_server/select_server.js
When multiple SSO's are available and email/password is not were were not showing the LoginOptions screen. This PR should fix it.
https://mattermost.atlassian.net/browse/MM-43607
Fixes: #6183
```release-note
Fixed Login when multiple SSO methods are enabled while email/password is disabled.
```
> Show login options when using multiple SSO login methods

- app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
- app/screens/login/index.tsx
- app/screens/navigation.ts
- app/screens/server/index.tsx
- app/screens/sso/index.tsx
- app/screens/sso/sso.test.tsx
- app/utils/server/index.ts
- test/setup.ts
When selecting a server without an active session from the server list, take the user directly to the login screen and bypass the Add Server screen.
https://mattermost.atlassian.net/browse/MM-43640
```release-note
NONE
```
> [Gekidou] Show login screen when selecting a previous server

- app/actions/local/channel.ts
- app/database/subscription/unreads.ts
- app/init/push_notifications.ts
* When switching channels we'll call `cancelChannelNotifications` to remove notifications that belong to the channel.
* When canceling notifications on iOS we will update the badge number to match the remaining mentions on all servers.
* Once the app receives a clear notification (which depends on  https://github.com/mattermost/mattermost-push-proxy/pull/102) we also run `cancelChannelNotifications`
* Adds a suffix to the deviceId platform being registered in the session. Once this PR is merged we need to make sure the previous referenced PR for the push proxy is merged and deployed in order to properly receive notifications.
https://mattermost.atlassian.net/browse/MM-43486
```release-note
NONE
```
> [Gekidou] set badge count on cancel notifications

- app/client/rest/base.ts
- app/client/rest/index.ts
- app/client/rest/plugins.ts
- app/constants/calls.ts
- app/constants/websocket.ts
- app/products/calls/hooks.ts
- app/products/calls/store/action_types/calls.ts
- app/products/calls/store/actions/calls.test.js
- app/products/calls/store/actions/calls.ts
- app/products/calls/store/reducers/calls.ts
- app/products/calls/store/selectors/calls.ts
- app/products/calls/store/types/calls.ts
- app/products/calls/websocket.ts
- app/screens/channel/channel.android.js
- app/screens/channel/channel.ios.js
- app/screens/channel/channel_base.js
- app/screens/channel/index.js
- ios/Podfile.lock
- Customers are reporting many debug loglines with: ` Access to route for non-existent plugin       caller="app/plugin_requests.go:37" missing_plugin_id=com.mattermost.calls url=/plugins/com.mattermost.calls/config error="plugin not found: com.mattermost.calls"`
- This is because we were using an http request to `calls/config` and `calls/channels` as a check for whether the plugin is enabled. But this outputs the debug line above. 
- We needed a solution that would check if the plugin was enabled but wouldn't output the debug line. 
- Settled on pulling the publicly accessible plugin webapp manifests and checking if calls is registered there. If it is it's enabled.
- Bonus: We can use that to short-circuit some of the channel components (the calls banners), which will speed up the app.
- …
> MM-43904 - Fix: Calls: "Access to route for non-existent plugin" error log

- app/actions/remote/custom_emoji.ts
- app/components/emoji/index.tsx
At the time we fetch posts, if the posts have custom emojis in the metadata we do fetch the emojis from the server, but custom emojis used in custom status are not loaded.
The option was to load custom emojis if present in the user props everywhere we fetch users or go with fetching the custom emojis from the emoji component when the emoji is not present (this approach allows us to use custom emojis in other places as well in the future)
The emojis are grouped together as much as possible the same way is done when fetching users by ids.
https://mattermost.atlassian.net/browse/MM-43955
```release-note
NONE
```
> Fetch missing custom emojis

- app/screens/post_options/options/copy_text_option.tsx
- app/screens/post_options/options/delete_post_option.tsx
- app/screens/post_options/options/mark_unread_option.tsx
- app/screens/post_options/options/pin_channel_option.tsx
- app/screens/thread_options/options/mark_as_unread_option.tsx
For some options, dismissing the post/thread options after executing certain actions that update the DB, the post options would not dismiss, this PR ensures that the post options dismisses before executing the action.
https://mattermost.atlassian.net/browse/MM-43971
```release-note
NONE
```
> Dismiss post options before executing action

- app/products/calls/store/actions/calls.test.js
- app/products/calls/store/actions/calls.ts
- Error discovered in testing, I made batching the actions overly complicated, which broke the simple `dispatch(loadConfig())` here: https://github.com/mattermost/mattermost-mobile/blob/912287fbe054d5edf49e725eb14d294d248e7423/app/products/calls/hooks.ts#L60  
- Fixing it by simplifying the batching.
- Apologies for the churn, everyone. Thank you @josephbaylon for finding it. Will involve Joseph earlier.
- @amyblais I'll need to cherry-pick again, and I'll add the label for 1.52. Thanks!
- https://mattermost.atlassian.net/browse/MM-43904
- Fixes #6210 
```release-note
NONE
```
> MM-43904 - Fix: Calls batch actions

- app/components/jumbo_emoji/index.tsx
- app/components/markdown/markdown.tsx
- app/screens/bottom_sheet/index.tsx
- app/screens/edit_post/post_error/index.tsx
- app/screens/global_threads/index.tsx
- app/screens/global_threads/threads_list/header/index.tsx
- app/screens/global_threads/threads_list/threads_list.tsx
- app/screens/home/channel_list/categories_list/threads_button/__snapshots__/threads_button.test.tsx.snap
- app/screens/home/channel_list/categories_list/threads_button/threads_button.tsx
- app/screens/thread/thread.tsx
- detox/e2e/support/ui/component/alert.ts
- detox/e2e/support/ui/component/post.ts
- detox/e2e/support/ui/component/post_list.ts
- detox/e2e/support/ui/screen/channel.ts
- detox/e2e/support/ui/screen/edit_post.ts
- detox/e2e/support/ui/screen/global_threads.ts
- detox/e2e/support/ui/screen/index.ts
- detox/e2e/support/ui/screen/post_options.ts
- detox/e2e/support/ui/screen/server_list.ts
- detox/e2e/support/ui/screen/thread.ts
- detox/e2e/test/channels/channel_list.e2e.ts
- detox/e2e/test/messaging/message_delete.e2e.ts
- detox/e2e/test/messaging/message_draft.e2e.ts
- detox/e2e/test/messaging/message_edit.e2e.ts
- detox/e2e/test/messaging/message_post.e2e.ts
- detox/e2e/test/messaging/message_reply.e2e.ts
- detox/e2e/test/server_login/server_list.e2e.ts
- detox/e2e/test/smoke_test/messaging.e2e.ts
- Added e2e for messaging (draft, post, edit, delete, reply), and messaging smoke test
- Fixed step/verification on server list e2e
- Added test for MM-T4728_7 on channel list e2e
- Not included in this PR are global threads and messaging with at mentions, markdowns, etc
- Created associated zephyr test cases under `Mobile V2` folder
Mobile V2/Messaging:
[MM-T4781](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4781) - Message Draft
[MM-T4782](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4782) - Message Post …
> Detox/E2E: Messaging e2e tests in Gekidou

- app/screens/channel/channel_post_list/channel_post_list.tsx
- app/utils/post/index.ts
When the onEndReached of the list was being hit, we ended up re-sorting the posts in order to fetch more posts based on the last post id present in the post list.
What was happening before, when there are more posts to be fetched, the list behaved "OK" because the observer kicked in and we got the posts again correctly sorted from the database. The problem is actually when there are no more posts to fetch as no new posts were added to the db and the posts array was re-sorted, that caused the list to render incorrectly.
The fix consists on not re-sorting the posts array for two reason:
1. posts are already sorted by createAt, we just need to get the last one instead
2. By avoiding a sort we gain on performance.
https://mattermost.atlassian.net/browse/MM-43991
```release-note
NONE
```
> [Gekidou] fix flip of post list

- app/actions/remote/team.ts
On team switch we are fetching all the channels and unreads. This should have been done already on init, and synced through websockets, so there is no need to fetch them again.
Thanks @jwilander for the help on this.
None
```release-note
NONE
```
> Remove unneeded actions on team switch

- app/components/channel_item/index.ts
- app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
With the mute setting, we don't need to worry about category muted state as the server updates the notify props for each channel inside the category.
```release-note
```
> Fixes channel muting inside category

- app/client/rest/threads.ts
- app/screens/thread_options/thread_options.tsx
1. Put needs a request body and earlier we skipped as we aren't sending data but now we are sending empty object.
2. Thread Options snap points on android are hiding the menu. Using the snap points similar to post options 
https://mattermost.atlassian.net/browse/MM-44308
This PR was tested on: Android 11, iOS 15.2
https://user-images.githubusercontent.com/3680799/168697258-1cefc405-6505-4967-8f46-ef70c07e55fc.mp4
```release-note
NONE
```
> [Gekidou MM-44308] CRT Android unable to read/follow the thread

- app/components/autocomplete/at_mention/at_mention.tsx
- app/components/autocomplete/at_mention/index.ts
Use local users for At Mention autocomplete.
There are an important drawback to this: It seems we may not have the full membership of a channel, so it is hard to determine which users are in the channel or not. Same for the team. So we are showing all users across the server.
The current behaviour is:
- Try searching in the server
- If it doesn't return any error, use the server values.
- If it returns an error, use local values
The main use of this is to be able to look and use at mentions while offline.
Part of https://mattermost.atlassian.net/browse/MM-44107
```release-note
NONE
```
> Use local users for At Mention Autocomplete

- app/components/post_list/date_separator/index.tsx
- app/components/post_list/new_message_line/index.tsx
- app/components/post_list/post/body/content/youtube/index.tsx
- app/components/post_list/post/body/files/files.tsx
- app/components/post_list/post/post.tsx
- app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap
- app/components/post_list/thread_overview/thread_overview.tsx
- app/components/post_with_channel_info/channel_info/channel_info.tsx
- app/components/post_with_channel_info/post_with_channel_info.tsx
This changes the post padding from 20 to 16 to allow for a bit more width for the content.
Fixes:
https://mattermost.atlassian.net/browse/MM-44208
https://mattermost.atlassian.net/browse/MM-44040
This PR was tested on: iOS Simulator (iPhone 13)
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td><img width="564" alt="image" src="https://user-images.githubusercontent.com/2040554/169358801-9af01976-269e-4ec9-ab2b-4067dab65d74.png"></td>
</tr>
</table>
```release-note
NONE
```
> [Gekidou - MM-44258] Modifies post padding to 16

- app/actions/local/channel.ts
- app/actions/remote/channel.ts
- app/actions/remote/entry/common.ts
- app/database/operator/server_data_operator/handlers/channel.ts
- app/database/operator/server_data_operator/transformers/channel.ts
- app/queries/servers/channel.ts
- app/queries/servers/entry.ts
- app/queries/servers/post.ts
- app/queries/servers/thread.ts
- app/screens/home/channel_list/categories_list/categories/unreads/index.ts
- app/utils/thread/index.ts
- types/database/database.d.ts
During the app entry we are fetching the user preferences and `myChannel` data at the same time. `isCRTEnabled` is always returned as `false` as the data is not available in the DB.
We are processing and passing the value of `isCRTEnabled` manually so that correct data gets saved in the DB depending on the CRT setting.
https://mattermost.atlassian.net/browse/MM-44156
https://mattermost.atlassian.net/browse/MM-44210
```release-note
NONE
```
> CRT fixes for MM-44210 & MM-44156

- app/utils/post_list/index.ts
If we delete system posts, we were getting a weird behavior. On iOS I saw crashes (because the props were being set to null) and on Android just the messages still be there.
This PR solves the issue (even though did not dive deep into why the differences between the tests I did on iOS and the tests I did on Android).
None
```release-note
NONE
```
> Properly handle deleted system posts

- app/screens/snack_bar/index.tsx
This PR ensures that the `sourceScreen` and the  `event.componentId`  are different and by doing so, the snackbar shows up like it should.
https://mattermost.atlassian.net/browse/MM-44423
```release-note
NONE
```
> MM-44423 : Gekidou - event screenDidDisappear called twice

- app/utils/markdown/index.ts
Udpates heading styles to use Metropolis and adjust some spacing for markdown rendering.
Fixes: https://mattermost.atlassian.net/browse/MM-44209
This PR was tested on: iOS Simulator (iPhone 13), Android Simulator (Pixel 3)
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
```release-note
NONE
```
> [Gekidou MM-44209] Markdown heading style updates

- app/actions/remote/channel.ts
- app/actions/remote/entry/app.ts
- app/actions/remote/entry/common.ts
- app/actions/remote/notifications.ts
- app/actions/remote/retry.ts
- app/actions/remote/user.ts
- app/actions/websocket/channel.ts
- app/components/formatted_date/index.tsx
- app/hooks/team_switch.ts
- app/screens/home/channel_list/additional_tablet_view/additional_tablet_view.tsx
- app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
- app/screens/home/channel_list/categories_list/categories/categories.tsx
- package-lock.json
- types/database/models/servers/channel.d.ts
- Improved loading of DM/GM by:
1. Load on demand only DM's and GM's that are visible in the channel list per category
2. Load missing direct messages info after a small delay after entry
* Batch DM's by 300 requests in parallel
* Introduce the use of the [Group Channel User Profiles API](https://api.mattermost.com/#operation/GetUsersByIds) which allows us to fetch up to 50 group message channel at a time which reduces the  amount of requests and time
- Improve team switching by updating the loading state on the next tick instead of waiting 200ms
- Improve perceived performance on app entry by adding the same loading indicator as the team switching
- Fixed the path from upgrading from v1 to v2
- Fixed a random locale issue that could format the date in the wrong language
```release-note …
```
> [Gekidou] perf improvement & fix upgrade path

- app/components/team_sidebar/add_team/add_team_slide_up.tsx
- app/components/team_sidebar/add_team/index.tsx
- app/components/team_sidebar/index.ts
- app/components/team_sidebar/team_sidebar.tsx
- app/screens/select_team/index.ts
- app/screens/select_team/no_teams.tsx
- app/screens/select_team/select_team.tsx
- app/screens/select_team/team_list.tsx
The create team screen is scheduled for post-ga, so we have to get rid of all the options where we create the team.
I decided to comment it out, so we can reuse the work already done.
None
```release-note
NONE
```
> Comment out create team options until we have a create team screen

- app/components/emoji_picker/sections/index.tsx
- app/screens/apps_form/apps_form_component.tsx
- app/screens/create_or_edit_channel/channel_info_form.tsx
- app/screens/edit_profile/edit_profile.tsx
- app/screens/edit_server/form.tsx
- app/screens/edit_server/index.tsx
- app/screens/forgot_password/index.tsx
- app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
- app/screens/interactive_dialog/index.tsx
- app/screens/login/form.tsx
- app/screens/login/index.tsx
- app/screens/mfa/index.tsx
- app/screens/server/form.tsx
- app/screens/server/index.tsx
On several places we added ts-expect-error regarding legacy refs. This may be problematic, since potentially may hide other errors in the future.
The fix was actually to pass null to the useRef function.
None
```release-note
NONE
```
> Remove ts-expect-error regarding legacy refs

- app/components/emoji/index.tsx
- app/components/markdown/markdown.tsx
- app/components/markdown/markdown_latex_block/index.tsx
- app/components/markdown/markdown_latex_inline/index.tsx
- app/utils/emoji/helpers.ts
This PR addresses 3 things:
1. When using the app at the same time as the webapp and the theme is updating on the webapp, correct colors where not being updated because of the renderer reference used by the Markdown component
2. Latex now uses the correct color value for the math formulas
3. Emoji with unicode were attempting to find an emoji on the server without need
```release-note
NONE
```
> [Gekidou] Update Markdown theme

- app/products/calls/components/call_message/call_message.tsx
- app/products/calls/components/call_message/index.ts
- app/products/calls/components/channel_info/start_call.tsx
- app/products/calls/components/join_call/index.ts
- app/products/calls/components/join_call/join_call.test.js
- app/products/calls/components/join_call/join_call.tsx
- app/products/calls/store/selectors/calls.test.js
- app/products/calls/store/selectors/calls.ts
- app/products/calls/store/types/calls.ts
PR makes the necessary changes to support the new `MaxCallParticipants` config setting.
@cpoile Again I tried to simplify as much as possible but will need some help testing this to make sure I haven't missed some edge case.
https://mattermost.atlassian.net/browse/MM-44651
https://github.com/mattermost/mattermost-plugin-calls/pull/93
```release-note
Added support for the new MaxCallParticipants config setting
```
> [MM-44651] Implement MaxCallParticipants config setting

- app/helpers/database/index.ts
- app/queries/servers/channel.ts
- app/screens/find_channels/unfiltered_list/index.ts
- app/screens/home/channel_list/categories_list/categories/unreads/index.ts
- app/screens/home/channel_list/categories_list/subheader/search_field/index.tsx
The find channel screen has two states, when first opened (unfiltered) and when searching (filtered)
This PR is about sorting the unfiltered section by mention / unread (each by last_post_at) and excluding muted channels that have no mentions in them (same as the unread section in the channel list)
Also fixes a bug where the find channels screen could be opened multiple times if tapped rapidly.
https://mattermost.atlassian.net/browse/MM-44690
```release-note
NONE
```
> [Gekidou] Sort unfiltered find channels by mention / unread

- app/screens/global_threads/threads_list/thread/thread.tsx
Small UI tweaks to the Thread Item for the Global Threads View to align better with designed components:
- The channel name label that shows on thread list items has extra horizontal padding that shouldn’t be there.
- The font used for the author should be open sans body 200
- The time stamp appears too light and should be using body 50 
- Update margin under header
- Update margin under footer
- Reduce badge space on the left
Fixes https://mattermost.atlassian.net/browse/MM-44791
This PR was tested on: iOS and Android Simulator
<table>
<tr>
<td>iOS</td>
<td>Android</td>
</tr>
<tr>
<td>
</td>
<td><img width="472" alt="Screen Shot 2022-06-03 at 11 19 31 AM" src="https://user-images.githubusercontent.com/2040554/171884512-8ccabbd2-d1ee-4126-a075-77e1c38db3bb.png"></td>
</tr>
</table> …
> [Gekidou MM-44791] Styling changes to thread items in global threads view

- app/database/models/server/channel_membership.ts
- app/database/models/server/team_membership.ts
- app/database/operator/server_data_operator/handlers/team.test.ts
- app/database/operator/server_data_operator/handlers/team.ts
- app/database/operator/server_data_operator/transformers/channel.ts
- app/database/operator/server_data_operator/transformers/team.ts
- app/database/schema/server/table_schemas/channel_membership.ts
- app/database/schema/server/table_schemas/team_membership.ts
- app/database/schema/server/test.ts
- docs/database/server/server.md
- types/api/channels.d.ts
- types/database/database.d.ts
- types/database/models/servers/channel_membership.d.ts
- types/database/models/servers/team_membership.d.ts
The User Profile screen needs to display a badge when the user is a TeamAdmin or a Channel Admin. This means that we need to store the `scheme_admin` prop of the team & channel memberships
```release-note
NONE
```
> [Gekidou] Update database to hold if a user is a team or channel admin

- app/components/markdown/markdown_table/index.tsx
- app/constants/screens.ts
- app/screens/index.tsx
- app/screens/table/index.tsx
When a post contains a table, tapping on the table opens a screen showing the entire content of the table.
```release-note
NONE
```
> [Gekidou] Open & Render Tables in their own screen

- .circleci/config.yml
As we approach the first public release of the v2 beta app, we are going to stop delivering the beta app for v1
```release-note
NONE
```
> Exclude Beta builds from v1

- app/components/user_list_row/index.tsx
- app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
Tutorials for server and user lists were being displayed even after the screen was closed quickly.
Applies to server tutorial and create/open DM
https://mattermost.atlassian.net/browse/MM-45134
```release-note
NONE
```
> [Gekidou] Do not show tutorial if screen is closed

- app/products/calls/connection.ts
- app/products/calls/websocket.ts
Fixes https://github.com/mattermost/mattermost-plugin-calls/issues/112
https://github.com/mattermost/mattermost-plugin-calls/pull/114
https://mattermost.atlassian.net/browse/MM-45155
Tested on my Android test device and looks good.
@cpoile Could you give it a try on an iOS device as well just to confirm? I can provide a test server and credentials.
```release-note
Add support for using Calls when the Mattermost installation is served under a subpath.
```
> [MM-45155] Add support for Calls when MM installation is served under a subpath

- app/components/post_draft/index.ts
- app/components/post_draft/post_draft.tsx
In some circunstances (like jumping to a message from the permalink view) we change channels without unmounting and mounting again the post draft. The post draft is not updating the value when the draft changes on purpose, to avoid back and forth with the information between the database, the local state, and the native state.
This lead to the draft never updating when switching to a different channel, and some other potential nasty bugs along the way (navigating to a readOnly channel this way may show you the channel as a normal channel).
I updated the observer to take in mind changes in the props, and added an effect to update the value of the draft and cursor position whenever we switch channels or threads.
None
```release-note
Fix bug where the draft lingers when switching to a …
```
> Fix lingering draft when switching channels while never leaving the channel screen

- app/components/channel_icon/dm_avatar/dm_avatar.tsx
Show's the archived icon for a user that has been archived in the DM's list.
Tech note: This does call the it's own parent component again, but in the logic it exits out earlier with the `isArchived={true}` option without calling itself.
Fixes https://mattermost.atlassian.net/browse/MM-45142
```release-note
```
> [Gekidou] [Bug] DM Icon will be 'archive-outline' if user is archived

- app/actions/remote/thread.ts
We are marking the thread as read for every user switching to the thread screen. This PR will make sure to mark as read for only the users following the thread.
https://mattermost.atlassian.net/browse/MM-45251
```release-note
NONE
```
> [Gekidou MM-45251] CRT Thread auto follow on navigating to the thread screen 

- app/components/post_list/date_separator/index.tsx
- app/components/post_list/post/index.ts
- app/queries/servers/role.ts
- app/queries/servers/thread.ts
- app/screens/channel/channel_post_list/index.ts
While investigating https://mattermost.atlassian.net/browse/MM-45181 , I saw some blocking when receiving a message through the websocket in the current channel.
I have done a few tweaks that seem to alleviate the problem, mainly by "memoizing the observables" (using `distinctUntilChanged`), so there are no uneeded re-renders or recalculation of observables.
One of the problems I saw in Flipper is that the observables of all the loaded posts were triggering, which with the changes, they re-render less often. I also saw that the date separator was not memoized. This was left as is in another PR since in general, there won't be many date separators in the channel, but I decided to add here to take account for not so active channels.
May fix https://mattermost.atlassian.net/browse/MM-45181 …
> Minor performance improvements in post list

- app/components/floating_text_input_label/index.tsx
Long labels were not showing correctly. This was mainly seeing in the login screen. We have made it so they show only one line.
https://mattermost.atlassian.net/browse/MM-45173
```release-note
Fix long labels on login page.
```
> Make FloatingTextInputLabels no longer than one line

- app/screens/thread/thread_post_list/index.ts
- app/screens/thread/thread_post_list/thread_post_list.tsx
When CRT is enabled, In the thread screen, we are marking the thread as read whenever a new post is received. We should only mark the following threads as read.
```release-note
NONE
```
> [Gekidou] Thread auto follow on receiving new post when user is in a NOT-FOLLOWING thread

- app/actions/remote/channel.ts
- app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts
- app/components/markdown/markdown_link/markdown_link.tsx
- app/queries/servers/channel.ts
- app/utils/channel/index.ts
- index.ts
Tapping on a channel link closed the current channel, instead of navigate. Doing so in a thread generated some errors because it was trying to instantiate a new channel screen.
This PR tries to solve that problem, by not removing the channel screen from the stack, and not dismissing to root.
There is still two outstanding issues that will be handled in a different ticket:
- Changing to another channel, even if the channel is loaded in the database and needs no network actions, is taking too long.
- Taking too long to move to another channel (be it because of network issues or performance issues) has no feedback at all, making the user think the app is unresponsive.
https://mattermost.atlassian.net/browse/MM-45217
```release-note
Fix issue with channel links
```
> Fix links to channels closing the channel

- app/components/channel_actions/info_box/index.tsx
- app/components/markdown/hashtag/index.tsx
- app/components/post_list/post/body/reactions/reactions.tsx
- app/constants/screens.ts
- app/context/theme/index.tsx
- app/screens/channel/header/header.tsx
- app/screens/custom_status/index.tsx
- app/screens/find_channels/quick_options/quick_options.tsx
- app/screens/home/channel_list/categories_list/header/plus_menu/index.tsx
- app/screens/navigation.ts
- app/screens/post_options/options/edit_option.tsx
- app/screens/post_options/reaction_bar/reaction_bar.tsx
- app/utils/server/index.ts
- app/utils/theme/index.ts
- index.ts
- test/setup.ts
We were removing the screen from the Navigation Store stack when the modals were dismissed by a swipe gesture because there could be other screens in the stack https://github.com/mattermost/mattermost-mobile/commit/986de96ba5ffbcac25a60fc297580deba95a7395 with this PR that is no longer needed as we disallow modals dismissal with gestures.
Apart from that a small refactor around theming to prevent the weird bugs where the screens end up with a mix theme, one applied to components and the other to the native screen.
```release-note
NONE
```
> [Gekidou] Fix theming and navigation stack tracking

- app/components/post_list/post/post.tsx
There have been some reports (and I've seen it myself) when at times when we scroll in the post list there are some posts that are not responding to taps. After some investigation this could be cause of the use of a negative margin inside a FlatList.
This PR aims to keep the UX the same but changes the way styling is done and removes the need of the negative margin.
```release-note
NONE
```
> [Gekidou] Fix touch not responding on some posts

- app/actions/remote/post.ts
- app/actions/websocket/posts.ts
- app/components/post_list/post/body/index.tsx
- app/database/operator/server_data_operator/handlers/posts_in_channel.ts
When sending an at-mention, if that at-mention triggers an ephemeral (to add certain person to the channel) there was a race condition giving us problem in the postsInChannel table.
Two "fixes" has been provided together in this PR. Moving the post handling nearer the batch, and not updating postsInChannel if there is no need to update.
Both fixes will make this more reliable, but may not be enough.
There was also a minor error regarding pending posts not showing as failed after the expected time. That has been also solved.
https://mattermost.atlassian.net/browse/MM-45191
```release-note
Fix at mentions when it triggers a "add person to channel" message.
Old not send messages will now appear as failed.
```
> Fix at mention that triggers ephemeral message

- app/actions/remote/entry/common.ts
- app/actions/remote/post.ts
- app/actions/websocket/index.ts
- app/screens/home/channel_list/categories_list/header/loading_unreads.tsx
- app/screens/navigation.ts
As stated in the ticket, the loader next to the server displayname kept spinning when we add a new server.
This PR fixes this issue by: 
1. Ensuring that this component loading state is dictated only when it receives an event, so that it just doesn't spin on mount.
2. Add a workaround on top of the `cancelAnimation` function call due to a bug on reanimated 2.  [The bug](https://github.com/software-mansion/react-native-reanimated/issues/2733) in itself prevents a shared value that switches between two values from being interrupted/cancelled.
@coltoneshaw  - I'm adding you to this PR so that you can verify if the builds work for you.
https://mattermost.atlassian.net/browse/MM-45456
```release-note
NONE
```
> MM-45456 - Gekidou LoadingUnreads component keeps spinning

- app/components/option_item/index.tsx
- app/screens/bottom_sheet/content.tsx
- app/screens/browse_channels/channel_dropdown.tsx
- app/screens/home/search/results/filter.tsx
- app/screens/home/search/results/header.tsx
- assets/base/i18n/en.json
This PR removes the show results button because the filter was converted to a single select option
- remove show results button
- if the user selects the initial filter again, dismiss the modal and don't fetch the data again
- calculate the snap height dynamically and remove magic number
- remove from i18n
https://mattermost.atlassian.net/browse/MM-45521
Before:
After: 
```release-note
```
> [Gekidou  MM-45521] Remove show results button

- app/database/migration/server/index.ts
- app/database/models/server/group.ts
- app/database/operator/server_data_operator/transformers/group.test.ts
- app/database/operator/server_data_operator/transformers/group.ts
- app/database/schema/server/index.ts
- app/database/schema/server/table_schemas/group.ts
- app/database/schema/server/test.ts
- types/api/groups.d.ts
- types/database/models/servers/group.d.ts
Introduces new 'member_count' field in the Groups table for https://github.com/mattermost/mattermost-mobile/pull/6460
https://mattermost.atlassian.net/browse/MM-44759
```release-note
```
> [Gekidou] [Migration] Adds member_count to groups table

- detox/e2e/support/server_api/default_config.json
- detox/e2e/test/autocomplete/channel_mention.e2e.ts
- detox/e2e/test/channels/archive_channel.e2e.ts
- detox/e2e/test/channels/browse_channels.e2e.ts
- detox/e2e/test/channels/channel_list.e2e.ts
- detox/e2e/test/channels/find_channels.e2e.ts
- detox/e2e/test/messaging/markdown_latex.e2e.ts
- detox/e2e/test/server_login/server_list.e2e.ts
- detox/e2e/test/smoke_test/channels.e2e.ts
- detox/e2e/test/smoke_test/server_login.e2e.ts
- detox/e2e/test/smoke_test/threads.e2e.ts
- detox/e2e/test/threads/follow_and_unfollow_thread.e2e.ts
- detox/e2e/test/threads/global_threads.e2e.ts
- detox/e2e/test/threads/mark_thread_as_read_and_unread.e2e.ts
- detox/e2e/test/threads/open_thread_in_channel.e2e.ts
- detox/e2e/test/threads/reply_to_thread.e2e.ts
- detox/e2e/test/threads/save_and_unsave_thread.e2e.ts
- Fixed e2e for channel mention, server list, global threads, mark thread as read and unread, and server login
- Updated `default_config.json` with pertinent default settings and removed redundant setup from affected tests
- Updated associated zephyr test cases under `Mobile V2` folder
Mobile V2/Autocomplete:
[MM-T4879_8](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4879) - Channel Mention - should be able to autocomplete archived channel
Mobile V2/Server Login:
[MM-T4691_6](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4691) - Server List - should be able …
> Detox/E2E: Fix broken iOS e2e tests in Gekidou

- app/actions/local/thread.ts
- app/actions/remote/thread.ts
- app/actions/websocket/threads.ts
- app/components/post_list/more_messages/index.ts
- app/components/post_list/more_messages/more_messages.tsx
- app/components/post_list/post/post.tsx
- app/components/post_list/post_list.tsx
- app/init/push_notifications.ts
- app/screens/thread/thread.tsx
- app/screens/thread/thread_post_list/index.ts
- app/screens/thread/thread_post_list/thread_post_list.tsx
- app/store/ephemeral_store.ts
- types/api/threads.d.ts
This PR implements displaying a new message line and bar on the thread screen when CRT is enabled.
https://mattermost.atlassian.net/browse/MM-39318
https://mattermost.atlassian.net/browse/MM-39318
<table><tr><td><img src="https://user-images.githubusercontent.com/3680799/179781723-474ffdc5-aaae-45d7-a71d-0ed13bb94e0b.png" width="360" /></td><td><img src="https://user-images.githubusercontent.com/3680799/179781597-1b52c10c-ad4c-4468-b3d1-0c619c4b2905.png" width="360" /></td></tr></table>
```release-note
NONE
```
> [Gekidou MM-40089 MM-39318] CRT New Messages Line

- app/components/post_list/more_messages/more_messages.tsx
While adding NEW MESSAGES banner to the thread screen when CRT is enabled, the condition has broken the design for the Channel. 
```release-note
NONE
```
> [Gekidou] - New Messages banner condition fix for the channel screen

- app/products/calls/connection.ts
- app/products/calls/websocket.ts
PR adds support for reconnecting the signaling (websocket) client in case of a disconnect.
https://github.com/mattermost/mattermost-plugin-calls/pull/145
https://mattermost.atlassian.net/browse/MM-43838
```release-note
Calls: implemented WebSocket reconnection support
```
> [MM-43838] Calls: WebSocket reconnection support

- README.md
Few people realize that active development moved to that branch, so let's but a giant notice at the top of the readme.
> Update README to point to gekidou

- app/components/post_list/combined_user_activity/index.ts
We were not using observeWithColumns in combinedUserAcitivyPost, leading to some minor errors.
None
```release-note
Fixed minor issues with combinedUserActivity posts.
```
> Add observeWithColumns where needed in CombinedUserActivity Post

- app/components/post_draft/typing/index.tsx
- app/screens/gallery/footer/copy_public_link/index.tsx
- app/screens/gallery/footer/download_with_action/index.tsx
- app/screens/gallery/video_renderer/index.tsx
* fixes the position of the toast inside the gallery to respect the safe area insets on iOS devices
* fixes the video dimensions when rotating the device
* during video playback it allows the footer and header to be shown/hidden by tapping anywhere on the video
* Fixes a small memory leak in the `<Typing>` component
https://mattermost.atlassian.net/browse/MM-45680
https://mattermost.atlassian.net/browse/MM-45681
```release-note
NONE
```
> [Gekidou] gallery footer and video

- app/components/files/document_file.tsx
- app/components/files/file.tsx
- app/components/files/file_info.tsx
- app/components/files/files.tsx
- app/components/files/image_file_overlay.tsx
- app/components/post_list/date_separator/index.tsx
- app/components/post_list/post/body/index.tsx
- app/components/post_list/post_list.tsx
- app/screens/home/recent_mentions/recent_mentions.tsx
- app/screens/home/saved_messages/saved_messages.tsx
- app/screens/home/search/results/results.tsx
- app/screens/pinned_messages/pinned_messages.tsx
There are several components I encountered during the search screen design that pass theme as props. This PR removes the props and makes use of the `useTheme` hook. There are many other components where `theme` is being passed in as a prop.  This PR only focused on components that were used with the Search Screen.
N/A 
```release-note
NONE
```
> [Gekidou] Get theme from useTheme

- detox/e2e/test/channels/unarchive_channel.e2e.ts
- env.d.ts
- Added e2e for channels unarchive channel
- Also fixed `react-native-dotenv` typescript import warning
- Created associated zephyr test cases under `Mobile V2` folder
Mobile V2/Channels:
[MM-T4944](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4944) - Unarchive Channel
https://mattermost.atlassian.net/browse/MM-45822
```release-note
NONE
```
> Detox/E2E: Channel Info Unarchive e2e tests in Gekidou

- android/app/src/main/java/com/mattermost/share/ShareModule.java
Some android apps set both `EXTRA_STREAM` and `EXTRA_TEXT` in order to send text along with an image when you use their share functionality. Currently Mattermost Mobile only gets the image when this happens.
An example app that does this is [Knotwords](https://play.google.com/store/apps/details?id=com.noodlecake.knotwords) (to test complete a daily puzzle and try to share your result with Mattermost)
This PR enables Mattermost to also send the text alongside the image.
- Oneplus 6 (Android 11)
- Samsung Galaxy 10+ (Android 12)
```release-note
Fixed sharing of text alongside an image on Android
```
> Accept text shared with image on Android

- app/components/post_draft/typing/index.tsx
When we see a user is typing, if we switch channels, in certain circumstances it still showed the user typing from a different channel. This PR makes sure that on channelId change, all relevant states are cleared.
Disclaimer: I was not able to reproduce the original issue, so not sure if this solves it 100%, but the code seems sound.
https://mattermost.atlassian.net/browse/MM-45393
```release-note
None
```
> Fix other name showing on typing

- app/components/channel_actions/channel_actions.tsx
- app/screens/channel/header/header.tsx
- app/screens/channel/header/quick_actions/index.tsx
- app/screens/channel_info/options/index.tsx
- app/utils/channel/index.ts
The links to the DMs and GMs was not working correctly, and we actually don't want to show it, so we removed it.
None
```release-note
Remove copy channel link from DMs and GMS.
```
> Remove copy link from DMs and GMs

- app/managers/network_manager.ts
- package-lock.json
- package.json
- test/setup.ts
Sometimes, we were having troubles with the app getting stuck on login. The issue was tracked down to `react-native-device-info` implementation of `getUserAgent`. The root cause was not identified, but substituting the library to use `react-native-user-agent` solved the issue.
None
```release-note
NONE
```
> Substitue rn-device-info by rn-user-agent when fetching the user agent

- app/screens/permalink/permalink.tsx
When on the permalink view, if you click to join a channel, and the connection is slow, it just stays there until the response comes.
After joining, the "Jump to recent messages" button did not update, so it was not responsive.
This fix both.
None
```release-note
Improve UX on Permalink view.
Fix unresponsive "Jump to recent messages" just after joining the channel through the Permalink view.
```
> Fix permalink not entering loading status after join channel and fix button functionality after joining the channel.

- app/actions/local/thread.ts
- app/actions/remote/post.ts
- app/actions/remote/thread.ts
- app/client/rest/posts.ts
- app/components/post_list/post_list.tsx
- app/init/push_notifications.ts
- app/screens/permalink/permalink.tsx
- app/screens/thread/thread_post_list/index.ts
- app/screens/thread/thread_post_list/thread_post_list.tsx
- types/api/posts.d.ts
This PR Implements pagination in the thread screen with the supported servers and solves a bug related to auto-following a thread. Recently I have separated `viewing the thread` from  `reading the read` and missed the checks that the user should follow the thread in order to mark it as read as well. 
https://mattermost.atlassian.net/browse/MM-42232
https://mattermost.atlassian.net/browse/MM-46043
```release-note
NONE
```
> [Gekidou MM-42242 MM-46043] Paginating Threads

- app/actions/websocket/channel.ts
When receiving the websocket event of the user being added to a channel, we were not passing the correct value to "prepareOnly". This caused call the batching with models with no prepare state.
None
```release-note
Fix bug when the user is added to a channel from a different client / user.
```
> Fix channel added websocket message

- app/actions/websocket/group.ts
- app/actions/websocket/index.ts
- app/constants/websocket.ts
- app/queries/servers/group.ts
- types/database/database.d.ts
This PR handles the websocket events for groups being associated / dissociated with Channels.
NOTE: Awaiting https://github.com/mattermost/mattermost-mobile/pull/6529 to be merged in first.
https://mattermost.atlassian.net/browse/MM-45533
iPad Mini / iOS 15.5 (Device)
Pixel 5 / API30 (Sim)
```release-note
```
> [Gekidou] Handles Group Channel WebSocket Events

- app/managers/network_manager.ts
- assets/base/i18n/en.json
This ticket replaces the message to the user when they have entered an invalidly formatted server URL.
**Before**
**After**
https://mattermost.atlassian.net/browse/MM-45178
```release-note
```
> [Gekidou MM-45178] Improve wording about url not being a valid one

- app/actions/remote/session.ts
- app/actions/remote/systems.ts
- app/init/launch.ts
- app/utils/sentry.ts
This PR just fixes some logging mispellings.
https://mattermost.atlassian.net/browse/MM-46237
```release-note
```
> [Gekidou MM-46237] Correct spelling for log messages

- app/client/rest/base.ts
- app/client/rest/users.ts
- types/api/client.d.ts
Custom headers were not forwarded to the native client to be included in the requests.
```release-note
NONE
```
> Pass down client custom headers to native

- app/screens/settings/advanced/index.tsx
- app/utils/file/index.ts
This is part of a series of fixes - but to speed things up, this PR fixes the advanced settings by properly deleting all files in the cache directory.  Another fix to this PR is when we delete the 'data' for a server, then only that server's data is now being deleted.
I tested it on both iOS (simulator) and Android (device) by placing all kinds of file types in that directory.
https://mattermost.atlassian.net/browse/MM-46252
```release-note
NONE
```
> MM-46252 : Gekidou - Settings - Fixes Advanced Settings

- app/client/rest/channels.ts
When converting a channel to private, we were using a non existing API. Now we are using the correct one.
https://mattermost.atlassian.net/browse/MM-46005
```release-note
Fix converting a channel to private.
```
> Fix convert to private

- app/products/calls/connection/websocket_event_handlers.ts
- app/products/calls/screens/call_screen/call_screen.tsx
- We were getting errors for `Popping component failed` (see https://mattermost.atlassian.net/browse/MM-46302), found that the call screen seems to "render" even after it's been popped.
- This relates to the question @enahum had about why we are rendering the call screen when the `currentCall` is `null` (https://mattermost.atlassian.net/browse/MM-46050). Now I understand why we can get to that point in the code and have a null `currentCall`. The call screen renders a few times after it's been popped, and by that time the `currentCall` has been set to `null`. So just return a null because the screen will be unmounted async shortly.
- I am keeping the pop there, just in case, but we're ignoring the error because it's expected. 
- https://mattermost.atlassian.net/browse/MM-46302
- …
> MM-46050 MM-46302 - Fix for call screen popping errors

- app/products/calls/actions/calls.test.ts
- app/products/calls/actions/calls.ts
- app/products/calls/state/actions.test.ts
- app/products/calls/state/actions.ts
- This fixes a bug reported by a community member and observed every now and then while using the app:
- https://mattermost.atlassian.net/browse/MM-46301 happens when we try to connect to a call but the connection fails. Happens less often, now that we're sending an explicit leave ws message, but it could still happen for certain edge cases. Now we don't initialize the currentCall until we receive the userJoin event for the current user.
- https://mattermost.atlassian.net/browse/MM-46301
- https://mattermost.atlassian.net/browse/MM-45973
```release-note
Calls: Fix for CurrentCallBar appearing when call failed to connect
```
> MM-46301 MM-45973: Refactor currentCall logic; fix CurrentCallBar bug

- app/client/graphQL/entry.ts
There was an error when reading the graphQL query from the server. Apparently, we didn't need to stringify the body. Not sure when this changed, since it used to work.
None
```release-note
Fix graphQL queries
```
> Fix graphQL error

- app/actions/websocket/channel.ts
- app/actions/websocket/index.ts
- app/products/calls/actions/calls.ts
- app/products/calls/client/rest.ts
- app/products/calls/state/actions.ts
This is an important improvement:
- Reconnect wasn't working (we were missing servers that have GraphQL enabled)
- We are now fetching the channel call state when joining a channel. This fixes the weird state noted in the ticket.
- Note: this is the mobile-friendly version of what the webapp does (which is to fetch the current channel's call state whenever you switch to that channel). We're relying on websocket events to keep our channel state up to date on mobile.
- https://mattermost.atlassian.net/browse/MM-46325
```release-note
NONE
```
> MM-46325: Improve Calls mobile state sync

- app/components/post_draft/send_handler/send_handler.tsx
- We were "falling through" the slash command, but we shouldn't because the user could cancel their end call command in the dialog box. So just stop the slash command from being sent, since we do all the end call logic client side anyway.
- https://mattermost.atlassian.net/browse/MM-46228
```release-note
NONE
```
> MM-46228 - Calls: endcall should not send the slash command

- app/products/calls/screens/call_screen/call_screen.tsx
- Finished the load test behavior simulator, which made me realize we only allow one speaker to be highlighted at once on mobile. So fixing that.
- https://mattermost.atlassian.net/browse/MM-46465
- Before:
- After:
```release-note
Calls: Display speaking indicator for multiple participants at the same time
```
> MM-46465 - Calls: Fix for unable to see >1 participant speaking at same time

- app/components/autocomplete/at_mention/at_mention.tsx
- app/components/autocomplete/channel_mention/channel_mention.tsx
- app/utils/helpers.ts
This brings the way it worked on V1 and web. Since originally we were using redux, we were filtering always the redux results. Now we are using the data provided by the server, so we only filter when there is a trailing space, since the server apparently trim the spaces of the term for the search.
This adds an extra filtering that could be done at the server, but 0/5.
https://mattermost.atlassian.net/browse/MM-45279
```release-note
Autocomplete now closes after a space if there are no more results.
```
> Make it so a space after autocomplete channels and users closes the autocomplete

- app/screens/global_threads/threads_list/thread/index.ts
- app/screens/global_threads/threads_list/thread/thread.tsx
- app/screens/global_threads/threads_list/threads_list.tsx
This PR fixes the following:
1. Observing the post instead of relatively fetching it to avoid the crashes
2. Loads the newest threads on global threads loading
3. Doesn't render the thread item when a post or channel data doesn't exist (As we are not clearing the threads when the user leaves the channel)
NOTE: Clearing of threads when the user leaves the channel will be addressed in a different PR. This PR only avoids the crashes by not rendering the thread item.
https://mattermost.atlassian.net/browse/MM-46531
https://mattermost.atlassian.net/browse/MM-46098
```release-note
NONE
```
> Gekidou: MM-46531 - CRT observe post and load new threads on load

- app/components/option_box/animated.tsx
- app/components/option_box/index.tsx
As discussed in #6578 the OptionBox component is now using 60 as minWidth in order to fit on an iPhone SE
```release-note
NONE
```
> fix option box minHeight so that it fits on iPhone SE

- app/screens/bottom_sheet/index.tsx
When the bottom sheet is expanded and then moved to another position the backdrop disappears,  this PR fixes it.
```release-note
NONE
```
> Fix bottom sheet backdrop

- app/screens/mfa/index.tsx
In the MFA screen, when we submit, we check for the errors. We were checking different errors to show them in different ways, but the last error, we did not return. That made the app to go to the home screen, which was either empty (if you had no other servers) or the last server you were on.
Also noticed a "GO TO NO TEAMS" log, so I fixed it too. Before, if we had no teams in the server, it would have just stayed there doing nothing. Now it properly moves to the teams screen.
None
```release-note
Fix MFA login for wrong tokens and no teams.
```
> Fix MFA when introducing wrong token or having no teams

- app/actions/remote/entry/gql_common.ts
When using GraphQL we were not stopping the loading unreads spinner.
This was due to the relevant call to load unreads didn't have the "send event" parameter set.
None
```release-note
Fix loading spinner not disappearing on GraphQL
```
> Fix loading unreads not stopping with GraphQL

- patches/jail-monkey+2.7.0.patch
- patches/react-native-hw-keyboard-event+0.0.4.patch
- Created patches for `jail-monkey` and `react-native-hw-keyboard-event` to fix android build using `./gradlew assembleAndroidTest`
NA
NA
```release-note
NONE
```
> Gekidou: Create patches for node modules failing on android build

- android/app/src/main/AndroidManifest.xml
- app/products/calls/screens/call_screen/call_screen.tsx
- ios/Podfile.lock
- package-lock.json
- Two quick fixes:
- MM-46685 - adding the correct dependencies in the useEffect
- MM-45753 - Android 11 changed it's permissions and looks like it broke the speakerphone, had to hunt down which one we were missing, this looks like it was it. Also updated our react-native-incall-manager fork.
- https://mattermost.atlassian.net/browse/MM-46685
- https://mattermost.atlassian.net/browse/MM-45753
```release-note
Calls: Fix for Android speakerphone button.
```
> MM-46685 MM-45753 - Fix voice activity indicator and Android speakerphone

- app/client/graphQL/entry.ts
We were missing the "updateAt" field on the channel queries. When adding channels to the database, we are checking if the delete_at or update_at fields change. Since these were not changing (always defaulted to 0) changes in the channels were not being visible.
None
```release-note
Fix channel names not changing.
```
> Added missing field to gql query

- app/actions/remote/entry/app.ts
- app/actions/remote/entry/common.ts
- app/actions/remote/entry/gql_common.ts
- app/actions/remote/entry/notification.ts
Notification entry is doing more logic, mainly around navigating to the correct channel / thread, that was not ported to the graphQL entry logic.
This led to notifications not opening the correct channel when opening the app from them.
None
```release-note
Fix notification entry not opening the correct channel
```
> Fix notification entry on graphQL

- patches/react-native-notifications+4.3.1.patch
When ExtendedSessionLengthWithActivity is set to false, we create a alarm to notify the user of the session being expired.
On Android 31+, two things were added:
- Requirement for the IMMUTABLE flag (or MUTABLE)
- Specific permission for setting up alarms
I am not sure how time sensitive this notification is, but according to the [documentation](https://developer.android.com/training/scheduling/alarms), a simple set should show the image within the hour of the designed time (unless in case of battery saving restrictions).
```release-note
Fix crash on login
```
> Fix login crash when ExtendedSessionLengthWithActivity === false

- app/init/push_notifications.ts
- patches/react-native-notifications+4.3.1.patch
This PR fixes the new intent caused when opening a notification while the app is sitting in the background.
```release-note
NONE
```
> [Gekidou] Patch RNNotification Android

- app/client/graphQL/entry.ts
- app/utils/graphql.ts
There were still some fields missing in some parts of the queries. I did a check to find what other fields that we are using may be missing, but not sure 100% everything is in place.
For ChannelMembership LastPostAt there seems to be no gql endpoint, but should not be a problem, because we are using the channel last post at to calculate this.
None
```release-note
Add missing fields on entry logic.
```
> Add missing GQL fields

- app/init/push_notifications.ts
Receiving multiple In-app notifications is blocking the navigation. To solve the issue, before showing the in-app notification, we dismiss the previous notification.
[More information at ](https://community.mattermost.com/core/pl/8b85e9e45pgh3er3wycnpciu6a)
This PR was tested on: iOS 15.6.1
```release-note
```
> Receiving multiple In-app notifications is blocking the navigation

- app/components/post_list/post/header/header.tsx
- app/components/post_list/post/header/reply/index.tsx
- app/components/post_list/post/index.ts
- app/components/post_list/post/post.tsx
- app/components/post_priority/post_priority_label.tsx
- app/constants/post.ts
- app/queries/servers/post.ts
- app/queries/servers/system.ts
- assets/base/i18n/en.json
- types/api/config.d.ts
Implements phase 1 of the Message Priority feature displaying only the labels beside the post.
https://mattermost.atlassian.net/browse/MM-46584
Works with server PR:  https://github.com/mattermost/mattermost-server/pull/20875
<table>
<tr>
<th> With CRT </th>
<th> Without CRT </th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
Added labels for message priority.
```
> [Gekidou MM-43992] Display message priority labels for the posts 

- app/actions/local/systems.ts
- app/actions/remote/entry/app.ts
- app/actions/remote/entry/common.ts
- app/actions/remote/entry/gql_common.ts
- app/actions/remote/entry/login.ts
- app/actions/remote/entry/notification.ts
- app/actions/remote/groups.ts
- app/actions/remote/systems.ts
- app/actions/websocket/index.ts
- app/client/graphQL/entry.ts
gqlCommon, the logic that queried the gql information to the server was doing too much, making it harder to reconcile the rest and gqlcode. We have eliminated part of the logic there to just return the same as the `entry` endpoint we used to have. That way, all the logic of the different entry methods can be re-used.
Some other refactoring has been piggybacked.
None
```release-note
Entry logic improvements.
```
> Refactor entry to better share between rest and GQL

- app/actions/websocket/threads.ts
We are saving the threads received through the WebSockets with "loaded in global threads" flag as true. In case there is a delay in sync or we receive a thread through the WebSocket during the sync, next sync will send the new thread's `lastReplyAt` and it can create gaps in the thread or result in stale threads. 
https://mattermost.atlassian.net/browse/MM-45205
https://mattermost.atlassian.net/browse/MM-46899
```release-note
NONE
```
> [Gekidou MM-46899 MM-45205] Thread sync issue

- app/screens/home/channel_list/categories_list/threads_button/__snapshots__/threads_button.test.tsx.snap
- app/screens/home/channel_list/categories_list/threads_button/index.ts
- app/screens/home/channel_list/categories_list/threads_button/threads_button.test.tsx
- app/screens/home/channel_list/categories_list/threads_button/threads_button.tsx
This PR pins the `Threads` button to the top of the channel list sidebar when `unread` filters is on.  This is the same behavior when unread filters is off. 
As describe in the ticket, this only occurs when the user has the `Settings` > `Sidebar` > `Group unread channels separately` set to `false`
https://mattermost.atlassian.net/browse/MM-45046
| unread filters on, no unreads | unread filters on, with unreads | unread filters off |
| -- | --- | -- |
| <img width="455" alt="image" src="https://user-images.githubusercontent.com/7575921/189466734-c0177370-5b70-42ae-a6d5-80629cb68374.png"> | <img width="439" alt="image" src="https://user-images.githubusercontent.com/7575921/189466777-2a92ef22-d814-4256-993d-2fba3895b44c.png">  | <img width="460" alt="image" …
> [Gekidou MM-45046] Always show threads button when filtered and unfiltered

- app/components/autocomplete/autocomplete.tsx
- app/components/autocomplete/channel_mention_item/channel_mention_item.tsx
This PR allows wrapping long channel name text into two lines. @matthewbirtch, if the two lines are not desired, the only other option is to use one line, but none of the slug will be shown with long channel names.
It also removes an unused, but defined styling object
```release-note
```
> [Gekidou MM-46847] allow wrapping long channel text in autocomplete

- app/queries/servers/channel.ts
- app/screens/home/channel_list/categories_list/categories/body/index.ts
This PR excludes showing DMs that are created, but not have any posts, in the LHS channel list.
* Log into mobile as User-A
* From another client, login with User-B
* add a DM with User-A, but do not add any posts to the DM
* **OBSERVE:** User-A does not show DM with User-B in the channel list
* From User-B client, add a post to the DM with User-A
* **OBSERVE:** User-A now sees the DM show up in the channel list
Repeat the above test, but have User-B create a GM. **OBSERVE** User-A sees the same observations from above
https://mattermost.atlassian.net/browse/MM-45506
```release-note
```
> [Gekidou MM-45506] Do not include empty DM and GMs in Channel List

- app/components/post_list/post/post.tsx
This PR fixes the crashes caused by accessing the `priority` property.
https://community.mattermost.com/core/pl/6na9ynzab3fy8d3ie3pb4cjrtc
```release-note
NONE
```
> [Gekidou] Fix for crash caused due to accessing "priority" property

- app/actions/remote/systems.ts
- app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
Before login, we are getting the config, to decide whether to use GraphQL or REST. A race condition made it so the first entry call was done through the GraphQL path, but the deferred actions through the REST path, creating several problems.
I also noticed the fetch missing dm information call was done more often than needed, so I fixed that also.
None
```release-note
Fix dm names not showing after login
```
> Fix login not showing the usernames

- app/products/calls/connection.ts
- Handle the candidate message, which we've been forgetting to do. Fixes the problem.
- Tested pre and post on the pixel and iphone.
- v2 fix: #6658 
- https://mattermost.atlassian.net/browse/MM-47003
```release-note
Calls: fixed a bug where a call started from mobile would appear to start, but then fail after 30 seconds.
```
> MM-47003 - Calls - Fix for: peer connection timeout (v1)

- app/products/calls/connection/connection.ts
- app/products/calls/connection/simple-peer.ts
- app/products/calls/state/actions.ts
- Handle the candidate message, which we've been forgetting to do. Fixes the problem.
- Tested pre and post on the pixel and iphone.
- Also: Better error reporting, and clean up the currentCall state if we fail to connect to a call.
- https://mattermost.atlassian.net/browse/MM-47003
```release-note
Calls: fixed a bug where a call started from mobile would appear to start, but then fail after 5 seconds.
```
> MM-47003 - Calls - Fix for: peer connection timeout

- app/queries/servers/channel.ts
- app/queries/servers/role.ts
- app/screens/browse_channels/index.ts
- app/screens/channel/channel_post_list/intro/public_or_private_channel/public_or_private_channel.tsx
- app/screens/channel/channel_post_list/intro/townsquare/index.tsx
- app/utils/channel/index.ts
- app/utils/role/index.ts
Permissions defaulted to true (like the one for read only channels) were not respecting at all the permissions.
None
```release-note
Fix permissions defaulted to true.
```
> Fix permissions defaulting to true

- patches/react-native-keyboard-tracking-view+5.7.0.patch
When multiple post inputs are mounted, we use a mechanism to pause the tracking, this pause was only taking into consideration the scrollview so that it does not resize but left out the accessory view (the input in itself)
The revised patch to the library makes sure that the accessory view does not change position either.
https://mattermost.atlassian.net/browse/MM-47376
```release-note
NONE
```
> [Gekidou] Fix iOS keyboard tracking when paused

- app/constants/screens.ts
- app/init/push_notifications.ts
- app/screens/navigation.ts
- index.ts
When we receive notifications while the app is in the foreground, and in-app notification overlay is being presented, this overlay is kept out of the navigation stack in order to be able to push and pop screens on top of the current screen.
The way we were keeping the overlay out of the stack is by checking the screen props in the `registerComponentDidAppearListener` event, there is a bug in the navigation library (I did not try and figure it out as there is too much code involved) where the props are missing in the event (normally when the same screen is triggered repeatedly aka: 3 consecutive notifications) thus the overlay being registered as part of the stack, when attempting to open a channel, the top screen `InAppNotification` was already dismissed thus nothing can be push on top of …
> [Gekidou] Fix switch to channel when notification is dismissed

- ios/Mattermost.xcodeproj/xcshareddata/xcschemes/MattermostShare.xcscheme
- ios/MattermostShare/Views/InitialView.swift
Fixes the iOS share extension navigation bar theme on init.
Adds missing scheme for the Mattermost Share extension
https://mattermost.atlassian.net/browse/MM-47381
```release-note
NONE
```
> [Gekidou] Fix navbar theme in share extension

- ios/Mattermost/MattermostManaged.m
On iOS, make sure the react-native exported `isRunningInSplitView` executes the split view check in the main queue. Some call paths on the react native side seem to call the check from a background thread.
None
This PR was tested on: iPhone 13 Pro, iOS 15.6.1
n/a
```release-note
NONE
```
> iOS: Perform the split view check in main queue. (Some call paths caused the check to be done in a background thread)

- app/actions/remote/entry/common.ts
- app/actions/remote/entry/gql_common.ts
If we are no longer a member of a team and the server fails to tell us so (i.e. doesn't return a membership with delete_at > 0) we end up with a not working team in the database. This makes sure there is a cleanup.
None
```release-note
Make sure non-member teams are removed from the UI.
```
> Remove not member teams on startup

- app/components/search/index.tsx
This PR changes the UX for creating a DM so that text existing in the search input will be cleared after a user selects a user.
Repro Steps
1. `+` button to the right of the team in channels view
2. `Open a Direct Message`
3. Type some text in the `Search` input field to filter users
4. Tap a user
5. Observe the user is added
6. Observe the search input is cleared of the text.
Before: Item 6) was not occurring and the text stayed in the search input.
https://mattermost.atlassian.net/browse/MM-47486
```release-note
```
> [Gekidou MM-47486] Clear the search input after selecting a user

- app/components/post_draft/draft_handler/draft_handler.tsx
- app/components/post_draft/draft_input/index.tsx
- app/components/post_draft/post_draft.tsx
- app/components/post_draft/post_input/post_input.tsx
- app/components/post_draft/send_handler/send_handler.tsx
Hide autocomplete when the input is blurred.
DISCLAIMER:
- This is only for the post input. Other locations where this does not apply (yet):
- Search
- Edit post
- Channel info form
https://mattermost.atlassian.net/browse/MM-28453
```release-note
Autocomplete now gets closed when the input is blurred.
```
> Hide autocomplete when the input is blurred.

- app/components/markdown/hashtag/index.tsx
- app/components/markdown/markdown.tsx
When a message include a hashtag in a heading, now the heading style is also applied to the hashtag.
https://mattermost.atlassian.net/browse/MM-47968
```release-note
NONE
```
> [Gekidou] apply heading style to hashtags

- app/init/push_notifications.ts
This PR fixes the issue with in-app notifications being displayed for the active thread. 
https://mattermost.atlassian.net/browse/MM-47224
This PR was tested on: iOS 16, Android 11
```release-note
NONE
```
> [Gekidou MM-47224] Don’t show in app notifications for the active thread

- app/components/channel_icon/index.tsx
- app/components/channel_item/channel_item.tsx
Prevent bolding on muted channels when unread
[MM-47498](https://mattermost.atlassian.net/browse/MM-47498)
This PR was tested on: ios
```release-note
fixed bold channel when unread and muted
```
> [MM-47498] Don't bold muted channels

- README.md
- app/constants/calls.ts
- app/constants/view.js
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/changelog
Cherry pick of #6701 on release-1.56.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #6701

- app/components/navigation_header/index.tsx
- app/components/navigation_header/search.tsx
- app/components/search/index.tsx
- app/screens/home/index.tsx
- app/screens/home/search/search.tsx
This PR makes a change so that when a user clicks a modifier in the search screen, they search input gets focussed and the keyboard shows.
https://mattermost.atlassian.net/browse/MM-48006
```release-note
```
> [Gekidou MM-48006] Show keyboard when select a modifier

- app/components/autocomplete/index.ts
This fixes a bug in autocomplete where the `false` value needs to be emitted via the `of` operator.
N/A
This PR was tested on: iPhone 14
```release-note
```
> [Bug] Emit boolean with "of" operator

- app/components/post_draft/quick_actions/file_quick_action/index.tsx
Updates the file attachment icon in the post-draft to a paperclip instead of the document. 
- It aligns better with the webapp
- It better represents a broader set of attachment types
- Current icon represents document file types while we can upload any type of attachment
Fixes https://mattermost.atlassian.net/browse/MM-48200
This PR was tested on: iPhone 14 Simulator (iOS 16.1)
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img width="564" alt="image" src="https://user-images.githubusercontent.com/2040554/200195205-b2fa5428-fa0c-48a2-b888-050a6a788ba4.png"></td>
<td><img width="564" alt="image" src="https://user-images.githubusercontent.com/2040554/200195190-7358cda5-322f-4334-8e08-1adc773407e5.png"></td>
</tr>
</table>
```release-note
NONE
```
> [Gekidou MM-48200] Update attachment icon to paperclip

- app/actions/websocket/index.ts
- app/products/calls/state/actions.test.ts
- app/products/calls/state/actions.ts
- This ticket was an investigation of the behaviour of calls when the app goes into the background. We investigated how the state is handled, how the call's ws connection behaves, which messages get lost, and what happens on bringing the app back from the background.
- The ideal solution would be to move all calls-related ws events to the calls-owned ws, which doesn't close when the app goes to the background. Then the call's state will always be up to date when the user brings the app back. But that's infeasible at the moment (it's a lot of engineering work for only a little user-facing benefit). 
- The compromise we landed on was to make sure the reconnect logic updates all the calls state, and let that sync the app when it's brought to the foreground (same as what the webapp relies …
> MM-45972 - Calls: test ws messages when app is in background

- app/constants/events.ts
- app/products/calls/components/current_call_bar/current_call_bar.tsx
- app/products/calls/connection/websocket_event_handlers.ts
- app/products/calls/screens/call_screen/call_screen.tsx
- app/products/calls/state/actions.test.ts
- app/products/calls/state/actions.ts
- app/products/calls/types/calls.ts
- @enahum noticed that the voiceOn (who is currently speaking) state in the `CurrentCallBar` was completely lost when you move around screens, which is not a great UX. It's even worse when you move from watching the `CurrentCallBar` (and seeing UserA speaking) to the `CallScreen` (and then see no-one speaking), or vise versa.
- So moving the voiceOn state to the `CurrentCall` state. The detailed state (other than "there is a call happening") is only observed by the `CurrentCallBar` and the `CallScreen`, so it shouldn't cause any performance issues. (But I do have a benchmarking branch, so if you want numbers it will take an hour to set it up and run them.)
- Second ticket was "Call bar speaker is flaky" -- this was happening because the old method only kept the most recent speaker. So if …
> MM-47763 - Calls: "who is speaking" state

- app/components/no_results_with_term/index.tsx
This PR fixes a styling issue when no results exist for Messages or FIles searches. 
Before : 
After : 
<details>
<summary>Details</summary>
</details>
```release-note
```
> [Gekidou MM-47765] Add horizontal padding to empty results 

- app/components/files/file.tsx
- app/screens/home/search/results/file_result.tsx
- app/screens/home/search/results/file_results.tsx
This PR fixes an issue when the file search results are returned with only one image. There is possibly a bug in the `calculateDimensions` function, but I chose to fix it in the file_results so that I don't have the possibility of messing up some other components that use that function.
| Before | After |
| -- | -- |
|  <img width="300" alt="image" src="https://user-images.githubusercontent.com/7575921/200678113-0b795e3f-3e47-443a-b3ef-8147921df235.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/7575921/200678014-c78011fa-062b-49a4-a610-8244db98c7d8.png"> |
https://mattermost.atlassian.net/browse/MM-48281
```release-note
```
> [Gekidou MM-48281] Fix issue with single image result extending to full height of the image

- app/products/calls/actions/calls.test.ts
- app/products/calls/actions/calls.ts
- report from Sentry.
- This is odd, because the server should return an empty slice if there are no calls. If the calls plugin isn't running, the `loadCalls` fn shouldn't be run. I suspect the calls plugin crashed.
- This change at least means the mobile app won't crash if this happens again.
- https://mattermost.atlassian.net/browse/MM-48447
```release-note
NONE
```
> MM-48447 - Calls: guard against possible bad response from server (null)

- app/queries/servers/channel.ts
- app/screens/find_channels/unfiltered_list/index.ts
- app/screens/find_channels/unfiltered_list/unfiltered_list.tsx
Removes the unreads section from the channel switcher. Only recent channels are listed with unread channels retaining the bolded formatting.
[MM-47481](https://mattermost.atlassian.net/browse/MM-47481)
- iPhone 14 Pro, iOS 16
- Pixel 5, Android 13
|iOS|![MM-47481 (iPhone)](https://user-images.githubusercontent.com/23694620/199076478-17d3ca9d-f51b-4dab-aa7a-c81f0d6c01f6.png)|
|--|--|
|Android|<img width="440" alt="MM-47481 (Android)" src="https://user-images.githubusercontent.com/23694620/199076553-b721347d-d98e-400a-8037-658aca7e6272.png">|
```release-note
NONE
```
> [MM-47481] Remove Unread Channels From Channels Switcher

- README.md
Update branch names to reflect that gekidou is now main and the default branch
```release-note
NONE
```
> Update branches names in v1

- app/components/team_sidebar/team_list/team_item/team_icon.tsx
Switch teamname display from 'capitalize' -> 'uppercase' like it happens in webapp.
https://mattermost.atlassian.net/browse/MM-48526
**before**:
**after**:
```release-note
Modified team initials display to uppercase
```
> [MM-48526] Switch teamname display from 'capitalize' -> 'uppercase'

- app/screens/channel_info/options/index.tsx
We are going to hide the "mobile notification preferences" option under channel info until MM-44652 is implemented.
https://mattermost.atlassian.net/browse/MM-44652
```release-note
NONE
```
> MM-44652 : Temporarily hides NotificationPreferences

- app/actions/local/category.ts
- app/actions/remote/retry.ts
- app/actions/remote/team.ts
- app/actions/websocket/teams.ts
- app/queries/servers/categories.ts
- app/queries/servers/entry.ts
When a category is deleted while the app is not opened it remained in the database as the code path for entry was not pruning the categories that were not present in the response.
https://mattermost.atlassian.net/browse/MM-48624
```release-note
NONE
```
@matthewbirtch added you as a reviewer to test the app as you were the reporter of this bug.
> Fix categories where a previously deleted category was not removed

- app/screens/edit_profile/edit_profile.tsx
On Android, while selecting the last two fields (nickname & position) the item was being hidden by the keyboard.
```release-note
NONE
```
> Fix Android edit profile keyboard aware scroll view

- app/actions/remote/entry/common.ts
- app/actions/remote/entry/gql_common.ts
- app/actions/websocket/index.ts
Show spinner when we start a websocket reconnect on the current server, to show that the app is doing something on the background.
https://mattermost.atlassian.net/browse/MM-48776
```release-note
Improve loading spinner behaviour
```
> Start spinner on websocket reconnect

- app/components/selected_users/index.tsx
Fixes the bottom space for the selected users panel on iOS devices while the keyboard is not shown.
https://mattermost.atlassian.net/browse/MM-48826
```release-note
NONE
```
> Create DM/GM Screen - fix extra space in selected users bottom panel

- app/screens/post_options/options/mark_unread_option/index.ts
- app/screens/post_options/options/mark_unread_option/mark_unread_option.tsx
For non-CRT while on the Thread screen marking a post as unread was marking the thread as unread instead of the channel, now we check that the user is using CRT to mark the thread as unread or the channel accordingly
https://mattermost.atlassian.net/browse/MM-48548
```release-note
NONE
```
> fix Mark as unread a post on non-crt

- app/screens/home/tab_bar/home.tsx
- ios/NotificationService/NotificationService.swift
When receiving a notification while you are on a thread, the app badge icon was not being updated to match the amount of mentions across all servers while the app was in the background.
A very easy way to reproduce:
* Set the notifications to trigger while offline, away or online
* switch to channel A and then go to the Thread screen
* Have another user send a notification on channel A while you are in the Thread screen
Note: if channel A is a DM, no need to mention the user.
Important: It seems that the server has some code to not send the notification if the user has been active for a period of time https://github.com/mattermost/mattermost-server/blob/master/app/notification_push.go#L548 that appears to be [20 seconds](https://github.com/mattermost/mattermost-server/blob/717a4d04a925d496 …
> Update icon badge on Notification

- app/constants/events.ts
- app/hooks/keyboard_tracking.ts
- app/init/app.ts
- app/screens/channel/channel.tsx
- app/screens/find_channels/index.tsx
- app/screens/navigation.ts
- app/screens/thread/thread.tsx
The way we were tracking screens to issue an event to resume/pause the keyboard tracking view was checking only for certain screens, but some other were omitted causing the problem.
With this new approach, every time the component is not at the top of the stack we pause the tracking and resume otherwise. This is accomplish with the `commandListener` and `commandCompleteListener` from the navigation library and then we don't need to use the event emitter.
https://mattermost.atlassian.net/browse/MM-48494
```release-note
NONE
```
> Refactor how keyboard tracking is resumed & paused

- app/components/markdown/markdown.tsx
Fix markdown component to add the background color to mention keywords
https://mattermost.atlassian.net/browse/MM-48762
```release-note
NONE
```
> set mentionHighlightBg background for mention keywords

- app/components/post_list/post_list.tsx
The highlighted post when opening the permalink view was setting is offset to the top of the view instead of centering it.
https://mattermost.atlassian.net/browse/MM-47862
```release-note
NONE
```
> center highlighted post in permalink view

- app/actions/local/systems.ts
- app/constants/database.ts
- app/queries/servers/system.ts
- app/screens/global_threads/global_threads.tsx
- app/screens/global_threads/index.tsx
- save the lastview globalThreadsTab to the database after unmounting the threads view
- default to all on first opening of the threads view
This PR persists the global thread tab (`All Your Threads` or `Unreads`) to the system table
* the default record value is `all` 
* the value is updated after unmounting the Threads screen
Fixes https://mattermost.atlassian.net/browse/MM-47516
```release-note
```
> [MM-47516] Persist globalThreadsTab to System Table

- app/actions/websocket/index.ts
- app/actions/websocket/posts.ts
- app/components/option_item/index.tsx
- app/components/post_draft/post_input/post_input.tsx
- app/constants/navigation.ts
- app/constants/screens.ts
- app/hooks/android_back_handler.ts
- app/hooks/keyboard_tracking.ts
- app/init/app.ts
- app/init/push_notifications.ts
- app/products/calls/alerts.ts
- app/products/calls/screens/call_screen/call_screen.tsx
- app/screens/channel/channel.tsx
- app/screens/custom_status/index.tsx
- app/screens/custom_status_clear_after/index.tsx
- app/screens/home/channel_list/channel_list.tsx
- app/screens/home/index.tsx
- app/screens/navigation.ts
- app/store/navigation_store.ts
- app/utils/theme/index.ts
Refactor the NavigationStore:
- easier names to follow
- start using the registerCommandListener to keep the navigation store up to date based on the command
- Keep screenPoppedListener as the command listener does not get triggered when the back button in the navigation is pressed [very old and unresolved issue](https://github.com/wix/react-native-navigation/issues/4666)
- As modals get removed we remove all screens that were open in the modal context
- Properly handle `popTo` and `popToRoot`
This resolve the issue when trying to go to a screen when the previous screen in the store did not exist.
```release-note
NONE
```
> Refactor NavigationStore

- fastlane/Fastfile
Small change to a path in the `Fastfile` to allow for the unsigned ios builds to complete.
> V2 unsigned build fix for ios

- app/products/calls/components/current_call_bar/current_call_bar.tsx
- app/products/calls/screens/call_screen/call_screen.tsx
- Mistake caused the displayname to default to usernames. Fixed now.
- https://mattermost.atlassian.net/browse/MM-48949
```release-note
NONE
```
> MM-48949 - Calls: Displayname not showing correctly in call screen

- app/products/calls/screens/call_screen/call_screen.tsx
- This occurred rarely, but it was reproducible on the iPhone 13 sim using the exact profiles as in the ticket.
- Also, filling up the call with 20 profiles would sometimes cause the scrollview to stop before it had scolled to the last row (last row was only visible if you swiped and held up, and would scroll back below the screen after letting go).
- Both issues are fixed now
- https://mattermost.atlassian.net/browse/MM-48664
- sims
- Before:
- After:
```release-note
NONE
```
> MM-48664 - Calls: Profiles cut off sometimes

- app/actions/remote/entry/common.ts
- app/actions/remote/entry/gql_common.ts
- app/queries/servers/thread.ts
- app/utils/thread/index.ts
CRT feature flag is removed from Server 7.6. This PR removes the check if the server version is 7.6
https://mattermost.atlassian.net/browse/MM-48855
This PR was tested on: iOS 16
```release-note
NONE
```
> [MM-48855] Remove CRT feature flag from 7.6

- app/constants/device.ts
- app/managers/analytics.ts
- app/screens/bottom_sheet/index.tsx
- app/screens/home/channel_list/channel_list.tsx
- app/screens/home/tab_bar/index.tsx
Fix the issues where foldable phones were considering they were a tablet depending on how they were opened, and not changing the mode when moving into the other position, by not allowing "tablet mode" in Android.
There is still one small issue when passing from the smaller screen to the bigger one where a small white line appears on top of every screen, as if the whole navigation had been shifted a few pixels.
https://mattermost.atlassian.net/browse/MM-48139
https://mattermost.atlassian.net/browse/MM-48138
```release-note
Fix behaviour on foldable devices
```
> Fix foldable devices by not allowing tablet mode on android

- app/screens/home/search/results/header.tsx
- app/screens/home/search/results/results.tsx
- app/screens/home/search/search.tsx
This PR resolves two search bugs. 
Repro (using Community)
* from `Contributors` search for `File`
* change file filter to `Presentations` 
* observe: files reduced to only presentations
* change search team from `Contributors` to `Staff`
* observe: filter `Presentations` still selected
* observe: files reduced to only `Presentation` files on `Staff` team.
This issue was caused by transforming x-translation while still loading results.  To try to repro:
* search for a term
* switch to files team before the results come in
Expected: view files results or tab changes to messages 
Observed: view messages results while in file tab.
https://mattermost.atlassian.net/browse/MM-48280
https://mattermost.atlassian.net/browse/MM-48279
https://mattermost.atlassian.net/browse/MM-48192
This PR was …
> [MM-48192, MM-48279] Search - don't reset file filter when a user changes teams.

- app/actions/remote/channel.ts
- app/actions/remote/team.ts
- app/actions/websocket/channel.ts
- app/components/team_sidebar/team_list/team_item/team_item.tsx
- app/queries/servers/channel.ts
- app/queries/servers/team.ts
This PR solves the issues on the ticket and a few others:
- Race condition on team_item that fetches from the database an undefined team before being removed from the flatlist (id undefined issue)
- Navigation issue where we were navigating to the last team (which was the one were removing). This provoked the issue of re-entering the app and seeing "couldn't load this server".
- Similar issue when navigating to the last channel. This would only be observable on tablets, since they are the ones that show several channels.
- Corner case issue on both teams and channels where the "default channel to join" was the channel we were deleting.
- Minor refactoring to accommodate the case of archived channels.
https://mattermost.atlassian.net/browse/MM-48948
```release-note
Fix issue when being …
```
> Fix issues when removing a user from a team

- app/screens/home/search/results/results.tsx
This PR fixes and issue where rotating a tablet does not recalculate the sceen width. The dimensions reference as a dependency does not change, even though its values do.  use the width as a dependency instead.
```release-note
```
> [MM-48328] Use the width as a dependency instead of dimensions reference

- .circleci/config.yml
- detox/.detoxrc.json
- detox/package.json
- fastlane/Fastfile
- Combined fastlane for iOS unsigned and simulator
- Enabled build of iOS simulator both in release and PR
- release build will be useful for RainforestQA testing
- PR build will be useful for mobile E2E tests so that the pipeline in GitLab will take advantage of just picking up the artifacts from S3.
none, from channel discussion - https://community.mattermost.com/core/pl/nrn7p4uq1igbinwxitccoqifsa
```release-note
NONE
```
> Combine fastlane for iOS unsigned and simulator and enable build of iOS simulator both in release and PR

- android/app/src/androidTest/java/com/mattermost/rnbeta/DetoxTest.java
- detox/.detoxrc.json
- Update `DetoxTest.java` to fix the android detox build based on latest https://wix.github.io/Detox/docs/introduction/project-setup#42-adding-an-auxiliary-android-test
- Upgrade detox simulator to iPhone 14
NA
```release-note
NONE
```
> Detox/E2E: Fix android detox build and upgrade simulator to iPhone 14

- app/components/emoji/emoji.tsx
- app/components/emoji/index.tsx
- app/components/markdown/markdown.tsx
- app/components/markdown/markdown_code_block/index.tsx
- app/components/syntax_highlight/index.tsx
- types/components/emoji.ts
- types/components/syntax_highlight.ts
Improving cold start by removing the need to import some files during startup operation, those files are still loaded but deferred by using inline requires.
The Syntax highlight library seems to be extremely large and thus was taking a while to load and the Emojis require the emoji.json file which is 1.1Mb in size to be loaded as well.
When the app opens (specially for if the current server is licensed) it mounts the `AnnoucementBanner` component which uses `RemoveMarkdown` and one of the children uses `Markdown` this two last components have imports for `Emoji` and `SyntaxHighlight`. Also the `ChannelItem`(s) shown in the home screen for DM's it would use the Emoji component
To test this is required to run the app in release mode for example with `npm run android -- --variant=release` …
> Improve cold start

- NOTICE.txt
- app/managers/network_manager.ts
- ios/Podfile.lock
- package-lock.json
- package.json
- test/setup.ts
This PR makes it so that the user-agent sent by the mobile app always follows the same format regardless of the platform with the following format: `Mattermost Mobile/version+build (OS; OSVersion; Device Model)`
E.g
Android: `Mattermost Mobile/2.0.0+443 (Android; 13; Pixel 4)`
iOS: `Mattermost Mobile/2.0.0+443 (iOS; 16.2; iPhone 12)`
```release-note
NONE
```
> standardize user-agent

- app/hooks/keyboard_tracking.ts
There was a race condition caused by not starting to track the keyboard on mount
https://community.mattermost.com/core/pl/1s64ukdeatdx5ehih8ycb5ne4h
```release-note
NONE
```
> Resume keyboard tracking on mount

- app/components/files/files.tsx
- app/components/files/video_file.tsx
- app/screens/gallery/document_renderer/document_renderer.tsx
- app/screens/gallery/footer/download_with_action/index.tsx
- app/screens/gallery/video_renderer/error.tsx
- app/screens/gallery/video_renderer/index.tsx
- assets/base/i18n/en.json
Changes the way the video playback error is presented so that the user can take action (Download) instead of showing an alert box.
When the video has no poster and it failed to playback
When video has a poster and fails to playback
When the downloaded video cannot playback (same without the poster if not available)
https://mattermost.atlassian.net/browse/MM-48968
https://mattermost.atlassian.net/browse/MM-48965
```release-note
NONE
```
> Restyle video playback error

- app/actions/remote/terms_of_service.ts
- app/database/operator/server_data_operator/transformers/user.ts
- app/queries/servers/terms_of_service.ts
- app/screens/home/channel_list/index.ts
- app/screens/terms_of_service/index.ts
- app/screens/terms_of_service/terms_of_service.tsx
The initial implementation was making some assumptions regarding websocket events that was not real:
- The User Updated event never brings the Terms of service information (it is stored in a completely different table)
- Get Users brings the Terms of service information for this user (initial load gets the correct information)
- There is no websocket event to tell you that the terms of service information has been accepted
This should fix all those issues.
NONE
```release-note
Fix terms of service erratic behaviour
```
> Fix terms of service

- app/database/models/server/category.ts
- app/screens/home/channel_list/categories_list/categories/header/index.ts
- types/database/models/servers/category.ts
The hasChannels lazy query, only used to determine if the favorites category should render the header was not taking into account archived channels, so this PR changes the lazy query for an observable function on the model to account for the archived channels.
https://mattermost.atlassian.net/browse/MM-48995
```release-note
NONE
```
> Do not show favorites category if it only contain archived channels

- ios/Gekidou/Sources/Gekidou/Storage/Database+Mentions.swift
- ios/Gekidou/Sources/Gekidou/Storage/Database+Posts.swift
When a new notification arrives we were:
* setting the posts in channel and posts in thread but did not exclude those posts that could have been deleted by then, thus the edges could be wrong.
* The badge number being set was using the total count of mentions but did not exclude those from archived channels.
```release-note
NONE
```
> iOS notifications badge and posts in channel/thread

- app/components/post_draft/draft_input/index.tsx
- app/components/post_draft/quick_actions/post_priority_action/index.tsx
- app/components/post_draft/quick_actions/quick_actions.tsx
- app/components/post_draft/send_handler/send_handler.tsx
- app/components/post_list/post/header/header.tsx
- app/components/post_list/post/post.tsx
- app/components/post_priority/post_priority_label.tsx
- app/components/post_priority/post_priority_picker/index.tsx
- types/api/posts.d.ts
We have changed how priority gets saved in the server, so now instead of post.props we are using post.metadata.priority.
This commit adds the relevant changes for posts' priority to work in the mobile app.
https://mattermost.atlassian.net/browse/MM-49219
```release-note
Fixed a bug regarding post priority labels
```
> MM-49219: fixes post priority

- app/screens/navigation.ts
The tab bar animation is triggered earlier when coming back to the home screen.
This PR does not address anything related to the navigation header animations.
https://mattermost.atlassian.net/browse/MM-49234
```release-note
NONE
```
> Trigger tab bar animation earlier

- app/actions/websocket/index.ts
- app/components/connection_banner/connection_banner.tsx
- app/components/connection_banner/index.ts
- app/managers/websocket_manager.ts
- app/screens/home/channel_list/servers/servers_list/server_item/websocket/index.ts
- app/screens/home/channel_list/servers/servers_list/server_item/websocket/websocket.tsx
- types/global/websocket.d.ts
We were only taking in account whether the websocket was connected or not to show the server unreachable state. Now we take into account whether it is waiting to connect after coming back from the background.
The changes are:
- The time to connect other servers websockets is now 5 instead of 20 seconds
- The connection banner has a connecting state (only viewable if after coming from the background you switch to a different ~~team~~ server within 5 seconds)
- The connection banner shows automatically if we are connecting (instead of wait for a few seconds)
- The server list won't show anything if we are in the connecting state (same as if connected)
Some of these decisions were discussed here: https://community.mattermost.com/core/pl/gowtbtm3sf8cbyrsyxnjie69fr …
> Fix server unreachable message showing too often

- app/components/selected_users/index.tsx
- app/components/tutorial_highlight/long_press.tsx
- app/components/tutorial_highlight/swipe_left.tsx
- app/products/calls/components/channel_info_start/channel_info_start_button.tsx
- app/screens/channel_info/options/index.tsx
- app/screens/create_direct_message/create_direct_message.tsx
- app/screens/settings/advanced/index.tsx
- detox/e2e/support/ui/screen/browse_channels.ts
- detox/e2e/support/ui/screen/channel_info.ts
- detox/e2e/support/ui/screen/channel_list.ts
- detox/e2e/support/ui/screen/create_direct_message.ts
- detox/e2e/support/ui/screen/create_or_edit_channel.ts
- detox/e2e/support/ui/screen/login.ts
- detox/e2e/support/ui/screen/server_list.ts
- detox/e2e/test/autocomplete/create_channel.e2e.ts
- detox/e2e/test/autocomplete/edit_channel.e2e.ts
- detox/e2e/test/channels/channel_info.e2e.ts
- detox/e2e/test/channels/channel_list.e2e.ts
- detox/e2e/test/channels/create_direct_message.e2e.ts
- detox/e2e/test/channels/favorite_and_unfavorite_channel.e2e.ts
- detox/e2e/test/channels/leave_channel.e2e.ts
- detox/e2e/test/channels/mute_and_unmute_channel.e2e.ts
- detox/e2e/test/messaging/save_and_unsave_message.e2e.ts
- detox/e2e/test/server_login/connect_to_server.e2e.ts
- detox/e2e/test/server_login/server_list.e2e.ts
- detox/e2e/test/smoke_test/messaging.e2e.ts
- detox/e2e/test/smoke_test/server_login.e2e.ts
- detox/e2e/test/smoke_test/threads.e2e.ts
- detox/e2e/test/teams/invite_people.e2e.ts
- detox/e2e/test/threads/mark_thread_as_read_and_unread.e2e.ts
- Added/updated test IDs
- Fixed and stabilized failing e2e based on latest code
- Associated test management changes here: https://github.com/mattermost/mattermost-test-management/pull/36
Note: This is built and tested using XCode 14.2 (iOS 16.2 and iPhone 14). To build and run ios locally for a specific simulator you can append the simulator of choice, so that
```
npm run ios --simulator='iPhone 14'
```
NA
```release-note
NONE
```
> Detox/E2E Maintenance: Fix broken iOS e2e tests

- app/database/models/server/category.ts
- app/screens/home/channel_list/categories_list/categories/header/index.ts
- types/database/models/servers/category.ts
Hides the favorites category if it has no channels or channels other than the current one have been archived.
https://mattermost.atlassian.net/browse/MM-48995
```release-note
NONE
```
> Do not display the favorites category when it has no channels

- app/actions/remote/channel.ts
Set the timestamp of `delete_at` to 0 when **un**archiving a channel.
https://mattermost.atlassian.net/browse/MM-49420
```release-note
NONE
```
> Fix unarchive action

- app/components/post_list/index.ts
- app/components/post_list/more_messages/more_messages.tsx
- app/components/post_list/new_message_line/index.tsx
- app/components/post_list/post/index.ts
- app/components/post_list/post/post.tsx
- app/components/post_list/post_list.tsx
- app/components/post_with_channel_info/index.ts
- app/components/post_with_channel_info/post_with_channel_info.tsx
- app/queries/servers/post.ts
- app/screens/global_threads/threads_list/threads_list.tsx
- app/screens/home/recent_mentions/index.ts
- app/screens/home/recent_mentions/recent_mentions.tsx
- app/screens/home/saved_messages/index.ts
- app/screens/home/saved_messages/saved_messages.tsx
- app/screens/home/search/results/file_results.tsx
- app/screens/home/search/results/index.tsx
- app/screens/home/search/results/post_results.tsx
- app/screens/home/search/results/results.tsx
- app/screens/pinned_messages/index.ts
- app/screens/pinned_messages/pinned_messages.tsx
- app/utils/emoji/helpers.ts
- app/utils/post_list/index.ts
- types/components/post_list.ts
One small optimization is to reduce the amount of queries executed in the post component
- custom emojis are now queried at the list level instead that on every post.
- appsEnabled is also queried at the list level
- At the list level we also query the database to get which of those posts in the list have been saved
- The query for highlighted reply bar only happens on the channel screen and when the user has CRT disabled
- The function to prepare the post list now returns the list of items wrapped in types where the post item include a reference to the previous and next post to avoid this calculation on every `renderItem` 
Fixes: https://mattermost.atlassian.net/browse/MM-47428
```release-note
NONE
```
> Reduce the amount of queries to display the PostList

- app/actions/remote/custom_emoji.ts
- app/components/emoji/emoji.tsx
- app/init/app.ts
Use Promise.allSettle so that when fetching custom emojis if one of them does not exist instead of failing the entire operation, those that do exist and are retrieved get stored in the database
Also consider custom emojis that end in `/-\d$/` to not be unicode
```release-note
NONE
```
> Use Promise.allSettle when fetching emojis

- app/database/models/server/my_channel.ts
- app/queries/servers/channel.ts
- app/screens/home/channel_list/servers/index.tsx
- app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
- app/screens/home/tab_bar/home.tsx
- ios/Gekidou/Sources/Gekidou/Storage/Database+Mentions.swift
This PR excludes the mentions count from the muted channels in the badges displayed in:
1. Servers list
2. Teams list
3. Server Icon
4. Home Icon on the footer bar
5. iOS badge when notification is received
https://mattermost.atlassian.net/browse/MM-47406
This PR was tested on: iOS 16
```release-note
NONE
```
> [MM-47406] Exclude muted channel's mentions count

- detox/save_report.js
- detox/utils/artifacts.js
- detox/utils/report.js
- detox/utils/test_cases.js
- Added `COMMIT_HASH` wherever necessary in save report
- Associated pipeline changes: https://git.internal.mattermost.com/qa/mobile-e2e-testing/-/merge_requests/13
The definitions of the environment variables are as follows,
```
BRANCH=<generated_pr_branch>
BUILD_ID=<pipeline_id>
COMMIT_HASH=<short_commit_hash>
```
Also, to disable saving results to zephyr on non-release runs,
```
ZEPHYR_ENABLE='false'
```
With respect to running e2e test against release, the following environment variables would apply,
```
RELEASE_VERSION=<e.g. 2.0.0>
RELEASE_BUILD_NUMBER=<e.g. 466>
RELEASE_DATE=<optional>
```
NA
NA
```release-note
NONE
```
> Detox Report: Add commit hash to report

- app/screens/channel/channel_post_list/intro/direct_channel/direct_channel.tsx
Post List intro for your own DM channel was missing the user avatar.
```release-note
NONE
```
> Display own DM avatar in channel intro

- android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
- app/components/files/video_file.tsx
- ios/GekidouWrapper.swift
- ios/Mattermost/MattermostManaged.m
- patches/react-native-create-thumbnail+1.6.4.patch
The video thumbnails were being generated by using the public link of the file instead of the file preview directly, with this PR we are now wrapping the library function in `MattermostManaged` module so that the session header is injected in the request, allowing us to remove the need to fetch the public link of the file from the server.
```release-note
NONE
```
> Generate video thumb from file url instead of public url

- ios/Gekidou/Sources/Gekidou/Networking/Network+Mentions.swift
- ios/Gekidou/Sources/Gekidou/Storage/Database+Posts.swift
Fix two crashes
1. When fetching the channel member, `mention_count_root` is not present in older servers and unwrapping was causing a crash
2. When filtering the list of posts and removing the deleted ones, if the list is empty, access to `first` and `last` crash as it returns `nil`
```release-note
NONE
```
> Fix crashes found in NotificationService

- app/components/markdown/markdown_code_block/index.tsx
When we added some code with syntax highlight, the code was properly highlighted on the preview, but sometimes not highlighted on the full screen view (when using aliases as JS instead of JavaScript).
This fixes that issue.
Jira: https://mattermost.atlassian.net/browse/MM-49616
```release-note
Fix syntax highlight on full screen on particular cases.
```
> [MM-49616] Fix code syntax highlight on full screen view

- detox/utils/report.js
- Fixed reporting build link for `TYPE=PR` so that it points to the build artifact created by the `ios-build-to-s3` job of `mobile-e2e-testing`
- Associated pipeline changes: https://git.internal.mattermost.com/qa/mobile-e2e-testing/-/merge_requests/15
NA
NA
```release-note
NONE
```
> Detox Reporting: Fix artifact link

- app/utils/theme/index.ts
In PR #6946 was wrongly removed the `EphemeralStore.theme` assignment
https://mattermost.atlassian.net/browse/MM-49622
```release-note
NONE
```
> Add back wrongly removed Ephemeral.theme assignment

- ios/NotificationService/NotificationService.swift
Trying to add an integer directly to the log was throwing `EXEC_BAD_ACCESS`
```release-note
NONE
```
> Add String description in log arguments

- ios/NotificationService/NotificationService.swift
Cherry pick of #6961 on release-2.0.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #6961

- app/actions/websocket/posts.ts
- app/actions/websocket/threads.ts
1. When CRT is enabled, On receiving a thread post (new post/edited) are being saved as channel posts, and on navigating to the channel, the channel looks empty as the saved posts are of a thread and no root posts are there but `since` parameter uses this updated value and doesn't load previous posts.
2. DM threads will not have a team_id, so use the `currentTeamId` to save the thread in `threadsInTeam` table. 
https://mattermost.atlassian.net/browse/MM-49619
```release-note
NONE
```
> [MM-49619] Channel doesn't show the posts

- app/screens/login/index.tsx
The error:
When we add the server, sometimes the login form does not appear.
The assumption:
The detox build, for some reason ends up calling the "componentDidAppear" navigation event before the effect to register the listener is executed.
The solution:
Use an effect that sets the value of translateX to 0 after the first render, effectively starting the animation.
The caveat:
What is done should be the same as doing it on `componentDidAppear`, but not sure whether there is some material difference there, so I kept the `componentDidAppear` event. If we consider the effect is going to be the same, we could remove the `componentDidAppear` event.
None
```release-note
NONE
```
> Fix e2e login error

- android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
For some reason I misinterpreted the if and thought that those avatar where for the session notifications, which is not true at all.
This PR adds the urlOverride to all instances of userAvatar, as it should.
https://mattermost.atlassian.net/browse/MM-38660
```release-note
Android: Properly show webhook avatar instead of user avatar in notifications.
```
> Add webhook image to notification in missing scenarios

- app/constants/database.ts
- app/database/manager/index.ts
- app/utils/file/index.ts
- app/utils/security.ts
This removes two migrations that we went through during the beta phase, but are no longer needed.
- Move config from the system table to its own table
- Move db names from raw urls to base64 strings
None
```release-note
NONE
```
> Remove uneeded database migrations

- app/components/post_draft/send_handler/send_handler.tsx
- app/products/calls/actions/calls.ts
- app/products/calls/actions/index.ts
- app/products/calls/alerts.ts
- app/products/calls/components/calls_custom_message/calls_custom_message.tsx
- app/products/calls/components/calls_custom_message/index.ts
- app/products/calls/components/channel_info_start/channel_info_start_button.tsx
- app/products/calls/components/channel_info_start/index.ts
- app/products/calls/components/join_call_banner/index.ts
- app/products/calls/components/join_call_banner/join_call_banner.tsx
- app/products/calls/connection/connection.ts
- assets/base/i18n/en.json
- Refactor the `leaveAndJoinWithAlert` function for simplicity (also so that we can use it with slash commands)
- Add client-side handling for the slash commands: `start`, `join`, `leave`
- https://mattermost.atlassian.net/browse/MM-48836
```release-note
Calls: Enable slash commands for calls: start, join, leave
```
> MM-48836 - Calls: handle slash commands

- app/constants/post.ts
- app/products/calls/utils.ts
- Didn't catch it from manual testing, my apologies.
- Be more specific in how we're determining if a msg is CallsCustomMessage
- https://mattermost.atlassian.net/browse/MM-49927
Before:
After:
```release-note
Calls: Fix bug when displaying recording messages
```
> [MM-49927] Calls: Fix recording message

- android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
- android/app/src/main/java/com/mattermost/helpers/NotificationHelper.java
- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
The bundle stored in the extra may not contain a `root_id` causing the `bundle.getString` to return null and thus accessing a null pointer was causing a crash.
Also ensures that the notification channels are created before getting the identifier
https://mattermost.atlassian.net/browse/MM-49985
https://mattermost.atlassian.net/browse/MM-49953
```release-note
Fixed a crash when dismissing a notification on android
```
> Fix crash when dismissing notification on android

- app/components/channel_item/index.ts
- app/components/common_post_options/copy_permalink_option/index.tsx
- app/components/common_post_options/follow_thread_option/index.ts
- app/components/files/index.ts
- app/components/post_draft/post_input/index.ts
- app/components/post_draft/send_handler/index.ts
- app/components/post_list/post/body/add_members/index.ts
- app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx
- app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx
- app/components/post_list/post/body/reactions/index.ts
- app/components/post_list/post/footer/index.ts
- app/components/post_list/post/header/index.ts
- app/components/post_list/post/index.ts
- app/components/post_list/post/system_message/index.tsx
- app/components/post_with_channel_info/channel_info/index.ts
- app/queries/servers/channel.ts
- app/queries/servers/file.ts
- app/queries/servers/reaction.ts
- app/queries/servers/thread.ts
- app/screens/channel/channel_post_list/intro/direct_channel/index.ts
- app/screens/channel/channel_post_list/intro/direct_channel/member/index.ts
- app/screens/channel_info/title/group_message/index.ts
- app/screens/edit_post/index.tsx
- app/screens/gallery/footer/index.ts
- app/screens/permalink/index.ts
- app/screens/post_options/index.ts
- app/screens/reactions/index.ts
- app/screens/thread_options/index.ts
- ios/Mattermost.xcodeproj/project.pbxproj
- share_extension/components/channel_item/index.ts
Replaced all direct access to child record for the corresponding query / observable to avoid crashes caused by the inner `find` when the child record is not present in the database.
https://mattermost.atlassian.net/browse/MM-49967
Fixes: #6989
Fixes: #7020
```release-note
Fixed a potential crash when trying access non existent database records.
```
> Do not access record children directly to avoid crashes if the child is not present in the db

- android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
- android/app/src/main/java/com/mattermost/helpers/NotificationHelper.java
- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Cherry pick of #7029 on release-2.0.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #7029

- app/screens/post_options/index.ts
https://mattermost.atlassian.net/browse/MM-49951
```release-note
Fixed the ability to mark a post as unread if the post was created from a webhook.
```
> Allow user to mark post as unread that was posted by a webhook

- android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
Fixes a silent crash on Android.
Potential causes: 
* the app updated but has not been opened yet, so the databases have not been created.
* For some reason the app failed to create the database and potentially alerted the user that the upgrade could not be performed.
https://mattermost.atlassian.net/browse/MM-50005
```release-note
NONE
```
> catch exceptions in Android Database helper

- app/screens/post_options/index.ts
Cherry pick of #7016 on release-2.1.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #7016

- app/screens/forgot_password/index.tsx
- app/screens/login/index.tsx
- app/screens/mfa/index.tsx
- app/screens/onboarding/index.tsx
- app/screens/server/index.tsx
- app/screens/sso/index.tsx
When the component mounts set the translation to 0 so that the forms moves to the correct position, in screens of the login flow. This fixes the issue when users turn off animations in their device settings.
Fixes: #7053
```release-note
Fixed some screens in the login flow not showing the content when animations are turned off in the device settings
```
> Fix the animation that occurs in login flow

- android/app/src/main/java/com/mattermost/helpers/BitmapCache.kt
- android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
- android/app/src/main/java/com/mattermost/helpers/Network.java
- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
- app/init/push_notifications.ts
- ios/Podfile.lock
- package-lock.json
- package.json
Ensure android permissions for push notifications are requested.
On top of it, refactor native code to use the Networking library for consistency, simplification and to reduce the amount of times the token is retrieved from the KeyStore.
Also the user profile images now use an in-memory cache to reduce the amount of requests. (iOS uses a disk cache instead)
```release-note
Ensures the permissions required to receive push notifications is always requested if needed.
```
> Request permissions for Android push notifications and refactor

- ios/Gekidou/Sources/Gekidou/Networking/Network.swift
- ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Delegate.swift
- ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift
Sharing files with the Share extension on a bad network would silently fail after the request times out
By using the default timeout settings that sets the `timeoutIntervalForRequest` 30 seconds and `timeoutIntervalForResource` for 7 days, now the extension is able to complete the process of sharing the files as seen in the following results
https://mattermost.atlassian.net/browse/MM-50009
```release-note
NONE
```
> Use timeout defaults for iOS Share Extension and Notification Service

- app/actions/remote/thread.ts
- app/screens/global_threads/threads_list/index.ts
Since was using `last_reply_at` to sync the latest threads. Now that we have a fix on the server side in which queries with `Greater than or equal`, we will add `+1` to the value to prevent loading the same threads again.
This PR also fixes phantom unread dot.
https://github.com/mattermost/mattermost-server/pull/22228
https://mattermost.atlassian.net/browse/MM-48010
This PR was tested on: iOS 16
```release-note
NONE
```
> [MM-48010] Threads since value change

- app/products/calls/actions/calls.test.ts
- app/products/calls/components/join_call_banner/index.ts
- app/products/calls/state/actions.test.ts
- app/products/calls/state/actions.ts
- app/products/calls/types/calls.ts
- This is a weird one. The problem: the join call banner startTime appears to be unset, and so defaults to `0`, creating a `53 years ago` message.
- I traced the code paths that update the call state's `startTime` and I can't see how it would be `0` or `undefined` and yet the participants are populated (as can be seen in the screenshot in the ticket). So either:
1. there's a problem on the server and it didn't send the `start_at` field in the `call_start` ws event (unlikely, given how straightforward that code is), or 
2. there's a problem where the CallState observer, or `BehaviorSubject` is failing to update (those are RxJS internals, which I don't fully understand), or 
3. there's a problem with how I was piping the calls state, and the second pipe (the one that produced …
> MM-48605: Calls - Fix for start time in join call banner is incorrect

- app/products/calls/alerts.ts
- app/products/calls/rtcpeer/index.ts
- ios/Podfile.lock
- package-lock.json
- package.json
- Implementing https://mattermost.atlassian.net/browse/MM-46048 for the mobile side
- Required two bug fixes from the `react-native-webrtc` folks. Now that those are in, this is working.
- Tested and is backwards compatible.
- Has no UX changes
- https://mattermost.atlassian.net/browse/MM-49065
```release-note
Calls: Implemented glare free negotiation
```
> MM-49065 - Calls: Implement glare free negotiation

- ios/Mattermost/Modules/SplitViewModule.swift
Fixes a crash on iOS lower than 16 when opening any item in the gallery was attempting to set the allowed orientations of the device.
https://mattermost.atlassian.net/browse/MM-50457
Fixes: #7106 
This PR was tested on: iPhone 7 iOS 15.5
```release-note
Fixed a crash on iOS lower than 16.x when opening an item in the gallery
```
> Fix iOS programmatically orientation crash on OS below 16

- app/components/files/index.ts
- app/queries/servers/system.test.ts
- app/queries/servers/system.ts
- app/screens/gallery/document_renderer/index.ts
- app/screens/gallery/footer/index.ts
- app/screens/home/search/results/file_options/option_menus/index.tsx
- app/screens/home/search/results/index.tsx
The logic about the checking if files can be uploaded was wrong. I fixed it and added some tests for it.
I also piggybacked some changes about the download logic, to centralize it, and added also tests.
Fix https://mattermost.atlassian.net/browse/MM-50448
```release-note
Fix bug where "enableMobileUploadFiles" setting was not working correctly.
```
> Fix upload permissions and centralize download permissions

- app/queries/servers/channel.ts
The query to get a channel by name was forcing a match with a teamId, thus DMs and GM's that were using the query were never found.
https://mattermost.atlassian.net/browse/MM-50484
```release-note
Fixed open a DM with a user by tapping "Send Message" in their user profile bottom sheet
```
> Fix open channel of existing DM

- app/queries/servers/channel.ts
- app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
- app/screens/home/channel_list/categories_list/categories/body/index.ts
DM's with deactivated users were being displayed in the channel list, now it only shows if it was the last unread channel
https://mattermost.atlassian.net/browse/MM-49935
```release-note
Fixed channel list to not display DM's with people that have been deactivated.
```
> Do not show archived dms in the category list

- app/screens/home/channel_list/categories_list/categories/unreads/index.ts
Add observer on the missing `is_unread` column in the unreads section of the channel list
https://mattermost.atlassian.net/browse/MM-50441
```release-note
NONE
```
> Observe on is_unread in the channel list unread section

- app/helpers/database/index.test.ts
- app/helpers/database/index.ts
- app/queries/servers/channel.ts
- app/queries/servers/group.ts
- app/queries/servers/user.ts
The implementation of `Q.sanitizeLikeString` uses the regex `/[^a-zA-Z0-9]/g` which replace all non-latin characters to `_`, this causes issues when trying to search channels in other languages.
The solution is to replace the regex to use one that only replace those characters that are not safe allowing non-latin characters.
https://mattermost.atlassian.net/browse/MM-50345
Fixes: #7052 
```release-note
Fixed searching for channels and users with non-latin characters
```
> Sanitize sqlite like queries and allow non-latin characters

- app/components/post_draft/post_input/post_input.tsx
The `KeyboardDidHide` event is being triggered when the AppState changes to active but does not actually dismisses the keyboard, but we were calling to blur the input which in turn did dismissed the keyboard, the fix is about not blurring the input which then keeps the keyboard opened.
https://mattermost.atlassian.net/browse/MM-50455
Fixes: #7107 
```release-note
NONE
```
> Do not dismiss keyboard when app is brought to the foreground

- app/actions/remote/entry/common.ts
- app/actions/remote/entry/gql_common.ts
We were not fetching the profiles on the GraphQL scenario since we already had the pretty display name. This caused the member count to be always 0.
https://mattermost.atlassian.net/browse/MM-50714
```release-note
Fix Group Message member count showing as 0 on GraphQL enabled instances.
```
> Fix Group Message member count on GraphQL scenario

- app/queries/servers/post.ts
When deleting a post, we were always deleting the `postsInThread` model. This caused the thread view to show no posts when we delete one.
This PR only delete the `postsInThread` model on root posts.
Fix https://mattermost.atlassian.net/browse/MM-50492
```release-note
Fix missing posts in a thread when a post get deleted
```
> Remove posts in thread only when removing root posts

- app/components/post_draft/post_input/post_input.tsx
- app/hooks/input.ts
- app/screens/create_or_edit_channel/channel_info_form.tsx
- app/screens/edit_post/edit_post.tsx
Changes directly added through either the value prop or the `setNativeProp` to the InputText are creating `changeText` events on iOS. That plus some events being lost is creating the "double tilde" issue. The same happens for commands and emojis.
This PR handle this by addressing any change in the value outside from the input as "prioritary", and forcing the change to propagate to the input side before handling any other change text event.
This can affect any place where the autocomplete is used. Those are:
- Channel screen -> Post input
- Thread screen -> Post input (should be the same component as the previous one)
- Edit Post Screen -> Post input
- Search Screen -> Search input (there should be no changes here)
- Channel Edit / Create screen -> Header input
Android behaviour should …
> Fix double tilde by waiting for text values to propagate

- app/products/calls/connection/connection.ts
- ios/Podfile.lock
- package-lock.json
- package.json
PR fixes a crash when receiving tracks. It took forever to debug mostly because the error was so confusing (see https://github.com/react-native-webrtc/react-native-webrtc/issues/1333 for context). Turns out logging complex objects like tracks and streams is not a good idea so I changed it to simply log their ids.
I am also bumping `react-native-webrtc` version to fix another unrelated bug (https://github.com/react-native-webrtc/react-native-webrtc/issues/1309).
Fixes #7155 
/cc @cpoile 
https://mattermost.atlassian.net/browse/MM-50806
```release-note
Calls: fixed crash on joining calls.
```
> [MM-50806] Calls: fix crash on joining call

- ios/NotificationService/NotificationService.swift
When the server is set to send push notifications with a generic message and only the sender name, on iOS the title of the notification was showing the sender Id as the channel name is empty
Now we default to the senderName when the channel name is empty (the channel name is empty only in this scenario) so that the title shows the sender name and then modify the message content to remove the sender name from the generic message (this is already done on Android)
Thus the notification is shown as
```
Sender name (title)
mentioned you. (content)
```
https://mattermost.atlassian.net/browse/MM-50477
```release-note
Fixed push notification display when set as generic message with sender only
```
> Fix iOS push notification when set as generic message with sender name

- app/components/post_list/post/body/reactions/reactions.tsx
- app/utils/emoji/helpers.ts
Based on this report https://community.mattermost.com/core/pl/7fg4y85hp3y6fx8dxt5nujdixo I was able to find that the cause of it was that we attempted to get the length (as in how many people reacted) for an reaction that is not present caused by a race condition where the `reactionsByName` map is not ready yet.. very very rare, but happened.
```release-note
NONE
```
> Fix potential reaction crash

- app/components/post_list/combined_user_activity/combined_user_activity.tsx
- app/screens/post_options/index.ts
Fixes the post option to not to show the Reply option when in the thread screen.
https://mattermost.atlassian.net/browse/MM-50206
```release-note
NONE
```
> use sourceScreen instead of location in post options

- app/components/post_draft/post_input/post_input.tsx
- ios/Podfile
- ios/Podfile.lock
iOS was not connecting the WS over TLS 1.3, the change here https://github.com/mattermost/Starscream/commit/9575b6781d1262247096af73617ae3acb2b139a0 uses the TCPTransport instead of the FoundationTransport which does connect over TLS1.3 which uses [NWConnection](https://developer.apple.com/documentation/network/nwconnection)  instead of [InputStream](https://developer.apple.com/documentation/foundation/inputstream/) and [OutputStream](https://developer.apple.com/documentation/foundation/outputstream)
Also piggyback a fix for saving the draft when the component unmounts, the reason is that there was a race condition when posting a message as the effect was running every time the `value` prop changed
```release-note
Added support for connecting the WebSocket over TLS1.3
```
> support WS connection over TLS1.3

- app/init/push_notifications.ts
Fixes potential race condition when registering the device to receive push notifications by adding the event handlers before invoking the registration for notifications as well as always call register for notifications in case the token is refreshed.
https://community.mattermost.com/core/pl/7cnpp6ydepycjx9u6nmfe4r1ja
```release-note
NONE
```
> Fix push notification token registration race/missing

- android/app/src/main/java/com/mattermost/helpers/push_notification/Channel.kt
- app/constants/preferences.ts
- app/database/operator/server_data_operator/handlers/channel.ts
- app/queries/servers/categories.ts
- app/queries/servers/channel.ts
- app/screens/home/channel_list/categories_list/categories/body/category_body.test.tsx
- app/screens/home/channel_list/categories_list/categories/body/category_body.tsx
- app/screens/home/channel_list/categories_list/categories/body/index.ts
- app/screens/home/channel_list/categories_list/categories/unreads/index.ts
- app/utils/categories.ts
- ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification+FetchData.swift
- types/database/models/servers/category.ts
The sort order of the channels list per category when applied was missing some important behaviors to match the other clients.
* Fixes the sort order for alphanumeric
* Fixes reacting to sorting changes per category
* Surfaces all channels with mentions
* https://mattermost.atlassian.net/browse/MM-50311
* https://mattermost.atlassian.net/browse/MM-50956
```release-note
NONE
```
> Refactor category channels to react to setting changes and apply the correct order

- app/client/websocket/index.ts
- app/utils/config.ts
- package-lock.json
- package.json
There are rare cases where initialize can be called twice at the same time, leading to `conn.open` to be called twice. This creates two connections on the native side, handled by the same client on javascript, creating several issues.
This still needs some changes on the network library, that should be either patched here, or version pumped here.
Related to: https://github.com/mattermost/react-native-network-client/pull/114
```release-note
Improve behaviour of websocket connections
```
> Fix race condition when the same websocket gets initialized twice

- app/screens/home/channel_list/categories_list/categories/index.ts
In order to promote the `Group Unread Channels` out of experimental, it has to be supported by mobile. This is the first step to get it to parity with web, so we can finally promote it to non experimental.
None
```release-note
Respect `ExperimentalGroupUnreadChannels` server config.
```
> Consider ExperimentalGroupUnreadChannels for unreads on top

- app/products/calls/components/call_avatar.tsx
- app/products/calls/components/emoji_list.tsx
- app/products/calls/components/emoji_pill.tsx
- app/products/calls/state/actions.test.ts
- app/products/calls/state/actions.ts
- app/products/calls/types/calls.ts
- ios/Podfile.lock
- The change to `emoji-picker-react` on the webapp side changed the emoji names a bit, and some emojis are not in the emoji name map on the mobile side. 
- So, we're changing the name being sent, and for the names that aren't in the map we're now sending the literal as a fallback. This PR passes along that literal.
An example is the nesting dolls that needed the `_` in the name, and the eye in a speech balloon, whos name is not in the map so the literal is being used:
Paired webapp PR: https://github.com/mattermost/mattermost-plugin-calls/pull/357
- https://mattermost.atlassian.net/browse/MM-51226
```release-note
Calls: Fix emoji rendering for rare emojis
```
> MM-51226 - Calls: Emojis not showing in reaction stream

- app/components/user_list/index.tsx
- app/screens/manage_channel_members/manage_channel_members.tsx
Members list was merging the profiles with the membership. Probably this was meant to be done in early implementations to get the scheme_admin and scheme_guest values into the profile, but that is no longer used. ~~Just in case, I merged the roles, since they are indeed different (system_guest on the user, channel_guest on the member).~~
Removed the composition between member and profile because it is not used and was generating some performance issues on change (re-rendering all elements on the list).
Also piggybacked a performance fix that had to do with getting to the end of the member list. When we get to the end of the member list, we continually are fetching the same set of members. That has been solved not passing the `fetchMore` prop, since, at the moment, we are not paginating …
> Fix guest badge not appearing on member list

- app/utils/categories.ts
We were passing the `notifyPropsPerChannel` object instead of the proper notify prop of the channel, making all channels "not being muted".
https://mattermost.atlassian.net/browse/MM-51384
```release-note
NONE
```
> Fix muted channels not being filtered out on the categories list

- app/products/calls/actions/calls.ts
- ios/Podfile.lock
- package-lock.json
- package.json
- types/modules/react-native-incall-manager.d.ts
- By manually turning off the speakerphone, we were inadvertently starting the proximity sensor/notice (i.e., the screen would turn dark, to prevent the caller from pressing buttons with their face while on a call). 
- Also updating the in-call manager while we're at it.
- Found this while investigating the racy connection issue (https://mattermost.atlassian.net/browse/MM-49663)
- https://mattermost.atlassian.net/browse/MM-51362
```release-note
NONE
```
> MM-51362 - Fix proximity notice engaging after call ended

- app/products/calls/state/actions.test.ts
- app/products/calls/state/actions.ts
- Reproduction steps from ticket:
1. UserA starts call from browser.
1. UserB joins call from mobile.
1. UserA starts screen sharing.
1. UserB opens call screen.
1. UserA leaves call without explicitly stopping screen sharing.
1. Crash happens for UserB.
- Issue was we were not clearing the screensharing state when user leaves. Missed that. 
- Added a test to make sure it doesn't regress.
- https://mattermost.atlassian.net/browse/MM-51469
```release-note
Calls: Fixed a bug that caused a crash when the current presenter leaves the call without stopping screenshare.
```
> MM-51469 - Calls: Fix for app crashes when screen presenter leaves

- app/utils/categories.ts
The `isUnreadChannel` was using the `isMuted` value to check in the mentions, when it doesn't matter whether the channel is muted or not: if it has mentions, it is unread.
This change was made after seeing an issue where a channel was properly showing the mentions, but it was being filtered on the collapsed categories. My guess is that something else is setting the mentions without properly updating the `isUnread` value, but haven't looked into it.
The issue got solved with restarting the app, so probably has nothing to do with other "phantom notification" issues we have seen around.
None
```release-note
Fix some notifications not showing when the category is collapsed.
```
> Consider unread when mentions are present regardless of muted state

- app/products/calls/utils.ts
- Participants who raised their hands first will always be ordered first, maintaining the raised hand order regardless of other states (e.g., voice on).
- https://mattermost.atlassian.net/browse/MM-50533
- Related on webapp: https://github.com/mattermost/mattermost-plugin-calls/pull/380
```release-note
Calls: Raised hand will take precedence when ordering participants in the call screen.
```
> MM-50533 - Calls: Prioritize raised hand when ordering participants

- app/utils/file/file_picker/index.ts
Once the user has been denied permission to access the camera roll, when they try to access it again, the alert is not being displayed 
(Images attached)
The following error is displayed in the Metro debug:
TypeError: Cannot read property 'title' of undefined
TypeError: Cannot read property 'title' of undefined
In my opinion the problem starts in:
https://github.com/mattermost/mattermost-mobile/blob/main/app/utils/file/file_picker/index.ts#L296
attachFileFromPhotoGallery()
at line 304=> await this.hasPhotoPermission('photo');
hasPhotoPermission()
at line 173=> this.getPermissionDeniedMessage(source)
getPermissionDeniedMessage()
at line 116=> this.getPermissionMessages(msgForSource);
at getPermissionMessages()
from line 36=>
There is no 'photo' : {title,text} element defined in the …
> photo permission alert is not displayed properly

- package-lock.json
- patches/react-native-navigation+7.32.1.patch
on android, when receiving an in-app notification or the snackbar is shown, the gestures were being captured by the overlay instead of passing down to the screen below.
https://mattermost.atlassian.net/browse/MM-51389
```release-note
NONE
```
> Prevent in-app notification and snackbar from blocking gestures

- app/products/calls/components/reaction_bar.tsx
- app/products/calls/screens/call_screen/call_screen.tsx
- There was pretty bad UX in landscape mode on Android, and iOS didn't support it. 
- Expanded the screensharing view to fill all available space. The goal was to optimize for viewing screensharing, so: removed reactions and "viewing x's screen".
- The reaction bar was originally showing under the controls (it could be pressed while also watching screensharing). Changed that to be part of the buttons, which toggle when pressing the screensharing video. (see screenshots)
- Tweaked the header bar in landscape mode to show the time and collapse buttons more clearly.
- @tanmay-des Can you take a look at these and let us know what you'd like tweaked? Thank you.
- https://mattermost.atlassian.net/browse/MM-51227
Android:
iOS:
```release-note …
```
> MM-51227 - Calls: Landscape mode optimizations for screensharing

- app/components/channel_actions/manage_members_label/manage_members_label.tsx
When a member was removed from the channel, we refetched the channel stats, but before actually removing the user, so the value would stay the same until we refetch it again.
This makes sure we fetch the channel stats only after the user is removed.
https://mattermost.atlassian.net/browse/MM-50289
```release-note
Members count gets updated after removing users.
```
> Update members count on remove users

- .circleci/config.yml
```release-note
NONE
```
note: in case of a 2.2.1 dot release, this also needs cherry-picking to the release-2.2 branch
> use xcode 14.2.0 on circleCI

- ios/Podfile.lock
- package-lock.json
- package.json
Bump react-native-network-client to fix issues with reconnecting websockets
```release-note
Fix websocket not connecting on rare scenarios
```
> Bump react-native-network-client to version 1.3.3

- app/screens/in_app_notification/index.tsx
The Safe Area context is not available for in-app-notifications on android, this was done on purpose as it forces the layout to not start where it should. Reverting the changes to avoid the crash caused by not having the context available.
credit goes to @ Muhammadqasim001 for the find
```release-note
NONE
```
> revert changes made to in_app_notifications

- app/components/post_draft/quick_actions/file_quick_action/index.tsx
Fix file attachment only allowing for one file, instead of many files.
Fix https://mattermost.atlassian.net/browse/MM-52145
Fix #7273 
```release-note
Now you can select several files when attaching files to a message.
```
> Fix file attachment limited to one file

- app/client/rest/posts.ts
- app/screens/channel/channel_post_list/channel_post_list.tsx
Sometimes, channels appear as empty when they are not. I forced the issue by adding an "empty chunk" at the end of the channel (with `earliest` and `latest` as `Date.now() + 1`). Part of the issue is in that we don't load new posts for that channel, and even if we do, the posts don't intersect with the empty chunk. New posts in the channel fix this, but until new posts are made, it won't trigger.
To fix it, we are removing a couple of safeguards.
- We allow `getPostBefore` to receive an empty postId. That will just take the latest posts.
- We consider that `lastPost` may be empty on an empty chunk.
- Even if the channel has no posts, we try to get posts, just in case.
The only thing I am not sure about this PR is the change on `canLoadPosts.current = (result.posts?.length ?? 1) > 0;`. My …
> Fix channels showing empty

- app/actions/websocket/posts.ts
When we enter through the notification entry, first we navigate to the channel, then we connect the websockets. When we connect the websockets, if there are reliable websockets, we get the missing events. One of the missing events is "message posted".
If we already fetched the channel, these events will be considered after marking the channel as read. This was causing the channel to become once more unread, and remove the New posts lines.
Not handling the websocket event if we have already the post in the system fixes the issue.
https://mattermost.atlassian.net/browse/MM-51243
```release-note
NONE
```
> Fix channel not marked as unread on notification entry

- app/actions/websocket/posts.ts
- app/store/ephemeral_store.ts
- patches/@nozbe+watermelondb+0.25.5.patch
When the websocket reconnects, the reliable websockets may kick in, sending all missing websocket events at once. Since the handling of the websockets is done asyncronous and without blocking, some websockets events may be handled in a different order than the expected.
In this PR we are focusing on the order Create -> Edit -> Delete. When we create a post, it takes some time. Then the edit or delete events may be triggered, but since the post is not yet in the database (create hasn't finished), they will silently fail. But then Create will finish with the original information (not the edited nor the deleted information).
This PR tries to alleviate that issue by tracking what Edit and Delete events has been received over non-existing posts, to apply them in case the post is being …
> Fix out of order websocket events for posts

- app/actions/local/thread.ts
- app/actions/remote/channel.ts
- app/actions/remote/team.ts
- app/components/channel_actions/leave_channel_label/leave_channel_label.tsx
- app/components/markdown/hashtag/index.tsx
- app/queries/servers/thread.ts
- app/screens/navigation.ts
- app/screens/thread/thread_follow_button/index.ts
- app/utils/error_handling.ts
The navigation library seems to have a bug that causes the props not being set when opening in succession a screen with the same id, so when the Thread screen is already opened and a notification for the same Thread is tapped, the app attempts to reopen the same screen and the bug is hit causing the following crash
There is a double fix here:
1. Dismiss the previous screens earlier to give enough time to the library to reset its values
2. In the case where the props that the screen receives are undefined, then we use the value we set in the Ephemeral store as a fallback to prevent the crash and use the correct values.
Additionally combined dismissAllModals and popToRoot calls into `dismissAllModalsAndPopToRoot` as well as added `dismissAllOverlays` as the Gallery screen is in fact an …
> Fix the query undefined comparison when threadId prop is not set by the nav library

- .solidarity
Just what it says in the title. I was able to build and run the iOS app in the simulator with this version of NPM, so I figured it would be fine to have it match that while still recommending the newer version of NPM
These are the versions of Node and NPM that we use for web
```
harrison-mm:mattermost-mobile harrison $ npm --version
7.24.0
harrison-mm:mattermost-mobile harrison $ node --version
v16.10.0
```
```release-note
NONE
```
> Reduce minimum NPM version to match web app

- app/actions/local/thread.ts
- app/screens/thread/index.tsx
- app/screens/thread/thread.tsx
- app/screens/thread/thread_follow_button/index.ts
Moved the addition of the follow thread button on the Thread screen navigation bar to be added when the Thread screen is mounted (this to avoid a race condition). Also when tapping on a notification that belongs to the same thread that is already being displayed, keeps the Thread screen on top.
```release-note
NONE
```
> small refactor to include thread follow button

- README.md
- app/constants/supported_server.ts
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/changelog
v7.1.0 ESR is going out of support on May 15th.
https://mattermost.atlassian.net/browse/MM-52167
> Update supported ESR version

- app/components/autocomplete/channel_mention/index.ts
- app/constants/autocomplete.ts
- types/api/config.d.ts
The channel autocomplete can be a bit obtrusive in certain cultures such as Korean where tildes are used more regularly in messages, so we've added a setting to make it require typing two letters after the tilde before the autocomplete triggers.
https://mattermost.atlassian.net/browse/MM-52173
https://github.com/mattermost/mattermost-server/pull/22952
https://user-images.githubusercontent.com/3277310/233412110-1ee2e9f3-a469-4e8c-9fa4-3ab466332cd9.mp4
```release-note
Added support for ExperimentalSettings.DelayChannelAutocomplete
```
> MM-52173 Add setting to delay channel autocomplete

- app/screens/navigation.ts
There is still an issue happening on receiving multiple push notifications. This change is a fix for edge-case scenario, not covered by previous fixes in #7237
```
TypeError: Cannot read property 'payload' of undefined
at <global>(app/screens/in_app_notification/index.tsx:144:33)
at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:3525:22)
```
The issue is caused by usage of the same component id in the following call sequence happened in a short time interval:
- `showOverlay`
- `dismissOverlay` (by timeout)
- `showOverlay`
`dismissOverlay` call schedules the call to release the native component, stored by component id. Creation of second native component as a pending for presentation component with the same id will replace the first one in …
> Fixed exception on accessing 'payload' of undefined in InAppNotification

- app/products/calls/actions/calls.ts
- app/products/calls/client/rest.ts
- app/products/calls/types/calls.ts
- package-lock.json
- package.json
- This continues the migration to using a common set of types between the plugin and the mobile code.
- https://mattermost.atlassian.net/browse/MM-52342
```release-note
NONE
```
> MM-52342 - Use CallState and CallChannelState from @mattermost/calls

- app/components/files/file.tsx
- app/components/files/image_file.tsx
When a post has a single image attached and the image matches the small image dimensions, the style applied was causing the image not to appear on screen.
Moved some variables around so that they are only defined when needed.
```release-note
NONE
```
-->
> fix small images style

- app/actions/remote/post.ts
- package-lock.json
The server will allow sys admins to set the create_at when creating a post, this PR makes it so that the server is always responsible for setting the create_at instead of allowing the client to do so.
https://mattermost.atlassian.net/browse/MM-52327
Fixes: #7294
```release-note
NONE
```
> Always let the server set the create_at timestamp

- app/components/selected_users/index.tsx
- app/screens/thread/thread.tsx
- app/screens/thread/thread_follow_button/index.ts
- app/screens/thread/thread_follow_button/thread_follow_button.tsx
Same as in https://github.com/mattermost/mattermost-mobile/pull/7317 the `threadId` is not available as a prop due to a bug in the navigation library, which causes the app to crash when attempting to query the database with an `undefined` value.
The idea here is so that a totally new component is created for the right button.
Also fixes https://mattermost.atlassian.net/browse/MM-49383 which is related to the `selected_users` component
```release-note
Fixed a crash when opening a push notification for a Thread on CRT when the Thread screen was already opened in the background
```
> Fix Thread button crash

- app/components/autocomplete/slash_suggestion/slash_suggestion_item.tsx
- app/components/emoji/emoji.tsx
- app/components/markdown/markdown_image/index.tsx
- app/components/markdown/markdown_table_image/index.tsx
- app/components/profile_picture/image.tsx
- app/components/progressive_image/index.tsx
- app/components/progressive_image/thumbnail.tsx
- app/screens/in_app_notification/icon.tsx
- patches/react-native-fast-image+8.6.3.patch
- types/components/emoji.ts
There might be errors with how FastImage handle local images, so we are making sure local images are handled by RN Image instead.
None
```release-note
Use RN Image on local images to avoid cache problems.
```
> Use RN Image for local images instead of FastImage

- app/components/settings/radio_setting/radio_entry.tsx
When build interactive dialog radio elements not shown when device use light theme(Android) and difficult to read(iPhone)
https://github.com/mattermost/mattermost-server/issues/22326
This PR was tested on: TECNO P8 Android, Samsung Galaxy S7 Edge Android, iPhone 11 Pro
before: 
after:
```release-note
Fixed Interactive dialog radio buttons style when light theme use
```
> Fixed Interactive dialog radio buttons style

- app/screens/post_options/options/copy_text_option.tsx
Copy Text was waiting for the bottom sheet to disappear before putting the text into the clipboard. Now we put it as soon as we hit the button.
Fix https://github.com/mattermost/mattermost-mobile/issues/7287
Fix https://mattermost.atlassian.net/browse/MM-52218
```release-note
Improve reaction time for Copy Text option
```
> Improve copy text response time

- patches/@sentry+utils+7.47.0.patch
On https://github.com/mattermost/mattermost-mobile/issues/7266 we have an Maximum call stack size exceeded. The clearer symptom is because we are recursively calling `_dropUndefinedKeys` which is consuming what is left of the stack.
This PR adds a limit to `_dropUndefinedKeys` so it is rarer that it consumes the stack.
In my opinion, this is just a patch, and does not solve the underlying problem, but may help us discover what is going on, or at least ease the user experience.
Partly deasl with https://mattermost.atlassian.net/browse/MM-52153
```release-note
Improved behaviour around "Maximum call stack size exceeded" errors.
```
> Patch _dropUndefinedKeys to limit the depth

- app/components/selected_users/index.tsx
- app/hooks/device.ts
- app/screens/channel_add_members/channel_add_members.tsx
- app/screens/create_direct_message/create_direct_message.tsx
- app/screens/create_or_edit_channel/channel_info_form.tsx
- app/screens/edit_post/edit_post.tsx
- app/screens/find_channels/filtered_list/filtered_list.tsx
- app/screens/find_channels/index.tsx
- app/screens/find_channels/unfiltered_list/unfiltered_list.tsx
- app/screens/invite/invite.tsx
- app/screens/invite/selection.tsx
We were adding a padding to the list to make up for the keyboard height.  This is needed in iOS, but not on Android. And iPads need a special treatment.
In order to simplify this, I did some refactoring to get the keyboard overlap, and use it wherever necessary.
Fix https://mattermost.atlassian.net/browse/MM-49196
```release-note
Android: Remove unneeded space after the list in Find Channels screen
```
> Remove unneeded padding on the FindChannels screen on Android

- app/actions/remote/groups.ts
- app/client/rest/groups.ts
We were asking for groups without having the license, which resulted in errors both in the server and the client. These errors were innocuous but were dirtying the logs. This remove these unneeded calls.
I also removed several client calls that were not being used to reduce the code. They can be added again in the future if needed.
Fix https://mattermost.atlassian.net/browse/MM-50052
```release-note
Remove unneeded group calls that were appearing in the logs.
```
> Add license checks to several groups calls

- app/screens/forgot_password/index.tsx
- app/screens/login/index.tsx
- app/screens/mfa/index.tsx
- app/screens/sso/sso_with_redirect_url.tsx
At some point, the title on the server screen changed from `mentionColor` to `centerChannelColor`. This was done for the server screen, but not for other "login" screens. This fixed for all other screens (Forgot password + forgot password success, login, sso login and mfa).
Fix https://mattermost.atlassian.net/browse/MM-49940
```release-note
Fix theming in log in screen
```
> Fix all references to mention color on "login" screens

- app/helpers/api/user.ts
We render at mentions in message attachments and the `pretext`/`text` fields are capable of mentioning users, but we don't currently load users that are mentioned there.
Full disclaimer, I wasn't able to test this locally since my dev environment is broken, but these changes match the ones made in https://github.com/mattermost/mattermost-server/pull/23460
https://mattermost.atlassian.net/browse/MM-52888
https://github.com/mattermost/mattermost-server/pull/23460
This PR was tested on: **I wasn't able to test this since my dev environment broke again**
```release-note
Ensured users mentioned in message attachments are loaded by the app
```
> MM-52888 Always load users mentioned in message attachments

- app/actions/remote/channel.ts
- app/client/rest/channels.ts
We were calling `getMemberInChannel` and using it as a user, instead of as a user membership. This can create several issues, specially when dealing with the current user, since several fields could be overwritten when they shouldn't (notify props and roles).
This fixes the issue.
Fix https://mattermost.atlassian.net/browse/MM-52965
```release-note
Fix rare issue when changing the role of the current user in a channel.
```
> Fix bad use of updatelocaluser on fetchChannelMember

- .github/workflows/github-release.yml
Use proper names for build artifacts on release workflow
```release-note
```
> fix: Fix expected names for releases

- app/init/push_notifications.ts
Mark thread as read was being called on notifications, creating a infinite loop with the server.
NONE
```release-note
Fix issue where reading a thread may lead the phone and server to overwork
```
> Fix MarkThreadAsRead on notifications

- app/components/files/image_file.tsx
- app/components/progressive_image/index.tsx
The footer of some messages was overlapping with the image attachment when the image was smaller than 48 pixels in height or width
Tests: Create posts in CRT and none CRT mode with single and multiple images that exceed and lower than the minimum size 48x48 and the posts with the images should display correctly.
Perhaps a channel with multiple posts with combination of images ex:
* Single image with height lower than 48
* Single image with width lower than 48
* Single image with dimensions higher than 48x48
* Repeat by attaching multiple images from 2 with a maximum of 10 images (a max of 6 should be enough)
https://mattermost.atlassian.net/browse/MM-53243
```release-note
Fixed the overlap between image attachments and the post footer in CRT
```
> Fix image attachment overlap

- app/actions/remote/groups.ts
- app/actions/remote/post.ts
- app/utils/errors.ts
Fixed some errors that were polluting the logs:
- Fetching unreads from archived channels when not allowed to see archived channels
- Fetching groups on unlicensed servers (there was a bug on https://github.com/mattermost/mattermost-mobile/pull/7369 )
- Logs showing `Unknown error` at the end of every error
Fix https://mattermost.atlassian.net/browse/MM-53214
Fix https://mattermost.atlassian.net/browse/MM-50052
```release-note
Remove unneeded fetch posts for unread archived channels that were appearing in the logs.
Remove unneeded group calls that were appearing in the logs.
Improve logging.
```
> Fix fetching unreads from archived channels, fetching groups on unlicensed servers and logs

- app/actions/remote/notifications.ts
- app/init/app.ts
- app/init/launch.ts
- app/screens/navigation.ts
- app/store/ephemeral_store.ts
- app/store/navigation_store.ts
- index.ts
Fix several problems in init where react context is closed but other state is still in memory.
It is hard to see the main issues of this problem, and a bit weird to reproduce. The easiest way I found to reproduce is to close the app pressing the back button on Android. This will kill react, but some other stuff will stay in memory. A clear side effect of this is that opening a notification then will show a log error saying something like "Home screen not found", but will run apparently fine.
Smoke test on Android and iOS relative to init (from the app button, bringing the app back from the background and opening from a notification, both when the app is closed and open) is appreciated, along with similar tests when closing the android app by pressing the back button.
May fix …
> Fix problems related to closing react but keeping other state

- app/components/markdown/markdown_code_block/index.tsx
Allow the codeblock on a post to transition to the code block screen when tapping on it while the keyboard is opened.
https://mattermost.atlassian.net/browse/MM-53346
```release-note
NONE
```
> fix open code block when keyboard is opened

- android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
- app/managers/session_manager.ts
- app/utils/mattermost_managed.ts
- ios/Gekidou/Sources/Gekidou/Keychain.swift
- ios/GekidouWrapper.swift
- ios/Mattermost/MattermostManaged.m
We were caching the token to not access too often the Keychain on iOS, but that cache was not getting invalidated on logout.
This was creating problems with Push Notifications where a wrong token was used to get the notification message, resulting in the message showing "session expired".
Fix https://mattermost.atlassian.net/browse/MM-52991
- Log in
- Close the app
- Receive a notification: It shows the message alright
- Log out
- Log back in
- Close the app
- Receive a notification
Expected:
The notification shows alright
Before the fix:
The notfication shows as if the message was "session expired"
```release-note
Fix case where notifications would show "Session expired" instead of the message.
```
> Fix ios cache

- app/queries/servers/post.ts
Remove the Post Priority feature flag. This is no longer needed as it has been enabled for a while and it now relies on the ServiceSettings.PostPriority config setting
https://mattermost.atlassian.net/browse/MM-48931
https://github.com/mattermost/mattermost/pull/23735
```release-note
None
```
> Remove Post Priority Feature Flag

- app/components/user_item/user_item.tsx
- app/screens/reactions/reactors_list/reactor/reactor.tsx
- app/utils/user/index.ts
At times it can happen that the user that reacted to a post is not present in the local database cause of an error while fetching the user, with this PR we make sure the app does not crash as well as we fetch the missing user to update the UI
https://mattermost.atlassian.net/browse/MM-53604
```release-note
Fixed a crash when listing the people that reacted with a certain emoji and the user is missing
```
> fix: crash when reactor is missing

- app/screens/channel_files/channel_files.tsx
- app/screens/manage_channel_members/manage_channel_members.tsx
there is an issue on Android, when we press the hardware back button in the Members and Files UI of a channel, the App goes to background instead of redirecting to the channel information.
Pinned messages UI works fine
please take a look to the screenshots, (GIF images, please open individually to completely watch them)
Files UI => app goes to background
Members UI => app goes to background
Pinned UI => app goes to channel info (OK)
```release-note
```
> use useAndroidHardwareBackHnd on Files and Members

- app/components/markdown/hashtag/index.tsx
When tapping on a hashtag the search was not including the `#` symbol, thus the search was looking for the word instead of the hashtag
https://mattermost.atlassian.net/browse/MM-53704
```release-note
Fixed hashtag search to match the hashtag and not the word
```
> Fix search hashtag

- app/screens/edit_post/edit_post.tsx
This PR fixes the Save button not grayed out and disabled when editing a message with a post that exceeds the char limit.
https://mattermost.atlassian.net/browse/MM-53343
This PR was tested on: pixel 6, galaxy note 20
Before:
https://github.com/mattermost/mattermost-mobile/assets/10082627/c28ce67a-ea65-4d82-b7fd-9b4c4e55ff55
After:
https://github.com/mattermost/mattermost-mobile/assets/10082627/c782ee40-8e5a-4402-8d21-4862da4c3118
```release-note
NONE
```
> MM-53343 - save button not grayed out when edit message is too long

- app/screens/login/form.tsx
- types/api/config.d.ts
Mobile app changes for allowing servers to customize the Forgot Password link.
Related server/web app PR: https://github.com/mattermost/mattermost/pull/23831
https://mattermost.atlassian.net/browse/MM-53249
```release-note
NONE
```
> [MM-53249] Allow server to hide or customize the Forgot Password link

- app/components/files/file.tsx
- app/components/files/files.tsx
- app/components/files_search/file_results.tsx
- app/screens/home/search/results/header.tsx
- app/screens/home/search/results/header_button.tsx
- app/screens/home/search/results/post_results.tsx
- app/screens/home/search/results/results.tsx
- app/screens/home/search/search.tsx
- app/screens/home/search/team_picker_icon.tsx
- assets/base/i18n/en.json
This pull request reduces the padding/margins to make space for the Messages/Files tab on the Search Page. Without reducing these spaces the Team Icon was getting above the sort icon you can see it in the following screenshots.
It moves as well the number of results in the files/messages tabs to the FlatList result
Feel free to let me know if I need to update more things.
[Github Issue](https://github.com/mattermost/mattermost/issues/23725)
[Jira Issue](https://mattermost.atlassian.net/browse/MM-48225)
- iPhone SE (3rd Generation) - iOS 16.4
- Nexus S - API 25
```release-note
Reduces the padding/margins on the Files Tab in the Search Page
```
> [MM-48225] Reduce Padding/Margins from Files Tab and moving the Search Results to the FlatList

- app/screens/settings/display_theme/custom_theme.tsx
- app/screens/settings/display_theme/display_theme.tsx
When a user has a custom theme set and attempts to change the `Theme` from within the settings screen, the custom theme was not able to be re-selected before leaving the screen
https://mattermost.atlassian.net/browse/MM-53811
```release-note
Fixed selecting the custom theme from the display setting
```
> Fix re-selection of custom theme

- app/screens/home/search/search.tsx
In the latest build, when I open the keyboard to input text on the tab search, it overlaps the content of the recent search item. This PR adds KeyboardAvoidingView to fix this issue.
None
- Iphone 13 Simulator (iOS 16.1)
- Samsung S10 plus (Android 12)
Before fix:
https://github.com/mattermost/mattermost-mobile/assets/28721870/ee4da287-381d-4cb2-9062-f509d5d2a451
https://github.com/mattermost/mattermost-mobile/assets/28721870/e518c8b3-abeb-49f1-88b1-c05bf24a966f
After fix:
https://github.com/mattermost/mattermost-mobile/assets/28721870/af3f9d55-c724-4313-ab88-9f79e439c4cd
https://github.com/mattermost/mattermost-mobile/assets/28721870/9f3429f0-8398-4805-b22c-ab2955f1f22f
```release-note
Fix keyboard overlap with recent search items in the search tab
```
> Fix keyboard overlap with recent search items in the search tab

- android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java
- app/managers/session_manager.ts
- app/utils/mattermost_managed.ts
- ios/Gekidou/Sources/Gekidou/Keychain.swift
- ios/GekidouWrapper.swift
- ios/Mattermost/MattermostManaged.m
Remove keychain cache, since it was not being properly invalidated in all instances of the notification service.
Fix https://mattermost.atlassian.net/browse/MM-52991
```release-note
Fix notifications showing a session expired message when it shouldn't.
```
> Remove keychain cache to avoid token invalidation problems

- app/components/user_list/index.tsx
This PR fixes the label that shows Admin/Member when the managing members are on the Members screen of a channel.
The label was showing just `Member` for all users and now is differentiating between Admin and Member users.
[Reported Issue](https://github.com/mattermost/mattermost/issues/23864)
- iOS Simulator, iOS 16.4
- Android Emulator, Nexus 5 API 31
```release-note
Shows correctly the Member/Admin label on a UserRow inside the Members Screen when managing users
```
> Fix: Show admin on channel members

- app/actions/local/user.ts
- app/actions/remote/post.ts
- app/actions/remote/user.ts
- app/database/operator/base_data_operator/index.ts
- app/database/operator/server_data_operator/comparators/files.ts
- app/database/operator/server_data_operator/comparators/thread.ts
- app/database/operator/server_data_operator/comparators/user.ts
- app/database/operator/server_data_operator/handlers/post.ts
- app/database/operator/server_data_operator/handlers/thread.test.ts
- app/database/operator/server_data_operator/handlers/thread.ts
- app/database/operator/server_data_operator/handlers/user.test.ts
- app/database/operator/server_data_operator/handlers/user.ts
- types/database/database.ts
Trying to figure out the issue where the app gets hanged when opening the post options, I found that some database batches were taking more than expected. The most troublesome was the periodic status fetch, that was getting the status of all the users in the channel, and no matter the new status, updating and re-rendering all users in the channel (avatars, status, etc...). I also made some similar improvements for when we get the posts for a channel. If we already have all the posts, now we almost don't update any field in the database, improving the batching time.
None
```release-note
Some performance improvements.
```
> Add some performance improvements

- app/actions/remote/user.ts
Looking for other bugs, I found this potential improvement.
Everything that has a `@` prepended is considered a mention, and we try to find a user or a group with that name. So we end up making two calls to the server  if they don't exist: one to get the user with that name, and then another call to get the group with that name.
The problem is when that is no longer found due to changes in usernames or non mention words (for example, a twitter plugin that post any twitter message with the corresponding `@`). In that case, every time the post is rendered, it will try to fetch the missing mentions. So scrolling up and down a channel with many of these can create a ton of unneeded requests.
The solution is to have a "memory cache" of the usernames that we have already tried to fetch on this …
> Avoid unneeded group fetches

- app/screens/global_threads/threads_list/header/index.tsx
I found a special case when users increase their device font sizes (old people may do this). This leads to the disappearance of the button Mark all as read in Thread, especially for android devices. This button is an important feature, so it should not be hidden even though the text is long. Hence I create a minor fix for it for this case. In normal case, it's doesn't change anything.
This PR was tested on:  ios and android.
Before fix, the button icon mark all as read disappears:
After fix, the button is still available in any case:
```release-note
Fixed UI button Mark all as read in Thread disappear when the font size is large
```
> Fixed UI button Mark all as read in Thread disappear when the font size is large

- app/components/post_list/post/body/acknowledgements/users_list/users_list.tsx
- app/screens/bottom_sheet/index.tsx
- app/screens/index.tsx
When there are many users in the acknowledgement list, we cannot scroll the list to the bottom.
None.
This PR was tested on:  ios
Before fix, we cannot scroll the user list. We must grab it outside the list to expand it first:
https://github.com/mattermost/mattermost-mobile/assets/39702132/395b3a2b-b946-4dc6-a75a-629e854866fe
After fix, we can expand and scroll the whole list (similar to facebook's bottom sheet reaction)
https://github.com/mattermost/mattermost-mobile/assets/39702132/c630c49b-b63f-438d-b409-f296faed9390
```release-note
Fix cannot scroll acknowledgement bottom sheet of user list when there are many users
```
> Fix cannot scroll acknowledgement bottom sheet of user list when there are many users

- app/screens/find_channels/filtered_list/index.ts
- app/screens/find_channels/unfiltered_list/index.ts
- app/screens/find_channels/utils.ts
This PR filters the channels from archived teams during the channels search (cmd + k).
Root cause:
Even when the Websocket event works correctly at the moment of the team deletion by receiving the team deletedEvent and removing the team and associated channels from the channels search, once the app have been reloaded the subsequent searches of unfiltered recent channels and filtered channels do include the channels from archived teams. (see video below)
https://github.com/mattermost/mattermost-mobile/assets/10082627/0bb254d4-b245-4fd4-948d-5a4fb9c8d976
https://mattermost.atlassian.net/browse/MM-53849
This PR was tested on: pixel 6, iphone 14 (emulators)
Before:
https://github.com/mattermost/mattermost-mobile/assets/10082627/bce8742c-5b5a-4b4a-a4ba-e16ad0c2e766
After: …
> MM-53849 - hide channels from archived teams during channels search

- app/screens/find_channels/filtered_list/filtered_list.tsx
There was a problem at the moment of styling  the name of the open channels where the user was not member of during the channels searching using the find channels modal (cmd + k).
This PR makes sure that the filtered list component styles correctly the ChannelItem component by verifying it is actually an Open channel and does contain a teamId.
https://mattermost.atlassian.net/browse/MM-53927
This PR was tested on: Pixel 6, Iphone 14 (emulators), Note 20
Before:
https://github.com/mattermost/mattermost-mobile/assets/10082627/3c8be86a-3884-41f8-b2e6-39a9a88f09d4
After:
https://github.com/mattermost/mattermost-mobile/assets/10082627/d291db7b-eb13-4d73-9fe0-bb80b6a99d54
```release-note
NONE
```
> MM-53927 - fix channel names not shown during search

- app/products/calls/connection/websocket_client.ts
PR fixes an issue that could cause the websocket client for Calls to be leaked in some rare (but possible) event. We move the reconnect logic into its own method and solely rely on the `closed` boolean to decide whether we should reconnect or not.
Refer to [parent PR](https://github.com/mattermost/mattermost-plugin-calls/pull/492) for full context and reproduction sequence.
https://mattermost.atlassian.net/browse/MM-53994
```release-note
Fixed a potential issue causing calls sessions to be stuck.
```
> [MM-53994] Calls: fix potential websocket client leak

- app/actions/remote/post.ts
- app/helpers/database/index.ts
- app/screens/permalink/permalink.tsx
On #7481 we introduced a bug where permalinks no longer show the messages.
This is because we were using on a few fetch functions a non-expected pattern. Instead of returning the raw client provided objects as many other remote functions, we were returning the models. And to do so, we were filtering the models that were on the Post table on the list of models passed to write to the database.
With #7481 we no longer store all posts, but only those that are different. So if there is no new post in the list retrieved from the server, we won't show any post.
To simplify this, we made it so the fetch functions work as expected (returning the raw client objects), and just let the caller deal with fetching the models from the database.
This only affected the permalink, and the paging of the …
> Fix posts not showing on permalink view

- android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
- Android should not add reply functionality to messages that are not marked `can_reply`.
- This will allow Android to match how iOS handles the `category` field.
- Sister to: https://github.com/mattermost/mattermost-push-proxy/pull/106
- This is ultimately because Calls wants to remove the "Okay" etc. auto reply options when we send a new call notification. https://mattermost.atlassian.net/browse/MM-53924
- iOS: 16.5.1, iPhone 14
```release-note
NONE
```
> MM-53924 - Android should use category to allow replies

- app/client/rest/general.ts
- https://github.com/mattermost/mattermost/pull/24177 removed the `/opengraph` endpoint
- And the `getOpenGraphMetadata` was unused, so removing it.
- https://mattermost.atlassian.net/browse/MM-54223
```release-note
NONE
```
> MM-54223 - Remove unused getOpenGraphMetadata

- package.json
https://typicode.github.io/husky/getting-started.html#install
https://blog.typicode.com/husky-git-hooks-autoinstall/
husky doesn't get autoinstalldc anymore so it seems like we need to specify `husky install` explicitly. 
husky fix
> Fix husky by adding npm prepare script

- app/database/operator/server_data_operator/handlers/user.ts
- app/helpers/api/preference.ts
This warning is logged frequently in my development environment, and it's a bit noisy. I also noticed that the warning message isn't accurate, so I changed it to only log that warning when the input array is actually empty.
This PR was tested on: iOS Simulator (various)
```release-note
NONE
```
> Fix handlePreferences warning

- android/app/src/main/AndroidManifest.xml
- app/products/calls/connection/connection.ts
- app/products/calls/connection/foreground_service.ts
- ios/Mattermost/Info.plist
- jest.config.js
- package-lock.json
- package.json
- A recent Android update seems to have changed the way apps are allowed to use the microphone from the background (or we only actually tested for a short period of time and it's always been this way). 
- This update fixes that by turning Mattermost into a foreground service, but only when a call is active. Otherwise there's no change to Mattermost. (See: https://developer.android.com/guide/components/foreground-services, and the react native module I used is: https://github.com/voximplant/react-native-foreground-service -- that's a helper to define a service class, register it, and start it up.)
- That part doesn't affect iOS. The iOS change is slight -- add `voip` to the list of background modes. This is just a protection, I'm not 100% sure it does anything.
-  Note: there's a little …
> MM-54553 - Calls: Enable microphone input in background (Android)

- app/actions/local/thread.ts
When opening the reply screen from a permalink, keep the current channel unless the team changes.
https://mattermost.atlassian.net/browse/MM-54969
```release-note
Fixed remain in current channel when replying a post from the permalink view
```
> Fix reply from permalink

- app/database/models/server/category.ts
`toCategoryWithChannels` is used by code that moves channels between categories which only happens on mobile for newly created/joined channels and when favouriting/unfavouriting channels. Currently, it returns channels in reversed order, so existing channels in that category get reversed when either of those are done.
https://mattermost.atlassian.net/browse/MM-54887
```release-note
Fixed channel order in category being reversed after favoriting or unfavoriting a channel
```
> MM-54887 Fix category order being reversed after moving a channel

- app/utils/categories.ts
Specially for DMs with no posts opened by yourself, the "recent" order on webapp and mobile was different.
Why is that? Because mobile only considers the last post at, while webapp considers the createAt too.
Fix https://mattermost.atlassian.net/browse/MM-55144
```release-note
Minor fix on channel order by recency
```
> Fix recent sorting difference with webapp

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Bumping build number in main to make sure we don't have a mismatch with the release branch for next betas.
Usually we bump in main and cherrypick to the release branch, but I missed it this time.
```release-note
NONE
```
> Bump app build number to 492

- app/components/post_list/more_messages/more_messages.tsx
- app/components/post_list/post_list.tsx
- app/products/calls/components/floating_call_container.tsx
- app/products/calls/hooks.ts
- app/screens/channel/channel.tsx
- app/screens/channel/channel_post_list/channel_post_list.tsx
- Implements new design for more_messages bar (https://www.figma.com/file/WVbRdxA4aRFdw410j2DxxU/MM-51513-Ringing-in-DMs%2C-GMs-(Mobile)?type=design&node-id=1378-95706&mode=design&t=CoxDrNZEd8wk9Y0B-0)
- Tried to clarify how spacing is calculated
- Refactored to remove some of the props.
- More messages bar now correctly handles all the variations of calls banners.
- https://mattermost.atlassian.net/browse/MM-55010
- Android: 13, Galaxy Tab s7+
- iOS: 16.5.1, iPhone 14
| channel screen by itself | thread screen by itself |
|--|--|
| ![IMG_1338](https://github.com/mattermost/mattermost-mobile/assets/1490756/f68d84e4-e5be-4a02-a4cd-16e0ac43a498) | ![IMG_1339](https://github.com/mattermost/mattermost-mobile/assets/1490756/45c1bdfa-cb71-488b-87d6-fe25d5178879) |
| …
> MM-55010  - Calls: more messages bar adjustments

- app/screens/server/index.tsx
https://mattermost.atlassian.net/browse/MM-55413
Fixes: #7655 
```release-note
Allow to reconnect to a previous server after migrating the app to a new device
```
> Allow connecting to a previous server if credentials are not in the keychain

- app/products/calls/components/floating_call_container.tsx
- app/products/calls/components/incoming_calls_container.tsx
- app/products/calls/observers/index.ts
- app/screens/channel/index.tsx
- app/screens/home/channel_list/channel_list.tsx
- app/screens/home/channel_list/index.ts
- app/screens/thread/index.tsx
- Adding the incoming calls banners to the channel list screen
- Took this opportunity to do some refactoring and cleanup.
- https://mattermost.atlassian.net/browse/MM-54277
- Figma: https://www.figma.com/file/WVbRdxA4aRFdw410j2DxxU/MM-51513-Ringing-in-DMs%2C-GMs-(Mobile)?type=design&node-id=1429-18525&mode=design&t=VuGgjjADk1BaJEVV-0
- Android: 13, Galaxy Tab s7+
- iOS: 16.5.1, iPhone 14
| iOS | Android |
|--|--|
| ![IMG_63F1D1662281-1](https://github.com/mattermost/mattermost-mobile/assets/1490756/c5d64d04-05ec-493f-8f56-12c6247cacf4) | ![Screenshot_20231120-183802](https://github.com/mattermost/mattermost-mobile/assets/1490756/8b77647a-2238-4cb0-be41-cf484a4f1126) | 
Tablet:
| vertical mobile mode | tablet horizontal state | horizontal mobile state |
|--|--|--|
| …
> MM-54277 - Calls: Add incoming banners to channel_list screen

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package-lock.json
- package.json
Bump build 496 version 2.10.1
NB: I'm having trouble running Fastlane on my machine, so i replicated the changes from PR https://github.com/mattermost/mattermost-mobile/pull/7668 (this will soon not be an issue anymore, when we implement the fastlane automation using [this PR](https://github.com/mattermost/mattermost-mobile/pull/7685) as a base)
```release-note
NONE
```
> Bump to version 2.10.1 build 496

- app/components/post_draft/draft_input/index.tsx
- app/utils/post/index.ts
Added condition so 'Recipients must be @mentioned' no longer appears for messages sent in DM channel when **Apply**ing **Send persistent notifications** was chosen by selecting the **Message Priority**<img src="https://docs.mattermost.com/_images/Priority-Message-Icon.svg" width=20/> on [Enterprise and Professional plans](https://docs.mattermost.com/collaborate/message-priority.html)  like below:
Fixes https://github.com/mattermost/mattermost-mobile/issues/25116
Jira https://mattermost.atlassian.net/browse/MM-54529
This PR was tested on: Android emulator
before | after
-|-
```release-note
Added channelType param to persistentNotificationsConfirmation.
```
> [MM-54529] Prevent Persistent Notifications Error Message for DM Channel

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
- package.json
Bump build 499 version 2.12.0.
NB: I'm having trouble running Fastlane on my machine, so i replicated the changes from PR https://github.com/mattermost/mattermost-mobile/pull/7668 (this will soon not be an issue anymore, when we implement the fastlane automation using [this PR](https://github.com/mattermost/mattermost-mobile/pull/7685) as a base)
```release-note
NONE
```
> Bump to version 2.12.0 build 499

- app/components/floating_text_input_label/index.tsx
- app/screens/settings/notification_auto_responder/notification_auto_responder.tsx
This PR fix the height of floating text input for automatic replies.
Fixes https://github.com/mattermost/mattermost/issues/25248
This PR was tested on:  Android 12 - One UI Core 4.1
```release-note
Fixes the height of automatic replies input text box.
```
> [MM-51088] fix: height for multiple line floating text input

- scripts/bump.sh
The version bump script works, but contains a typo at PR creation time: it should try to merge the new branch against `BRANCH_TO_BUILD`, but instead always creates the PR against `main`. E.g.: https://github.com/mattermost/mattermost-mobile/pull/7719
This PR fixes that, so that we're able to fully control which branch to bump the build/version numbers for.
https://mattermost.atlassian.net/browse/CLD-6707
```release-note
NONE
```
> Fix typo: use correct base branch in PR creation

- app/actions/remote/role.ts
- app/constants/general.ts
After adding a limit to the get roles by names endpoint, this PR updates the client's logic to batch the roles requests honoring the threshold.
Related to https://github.com/mattermost/mattermost/pull/25215
https://mattermost.atlassian.net/browse/MM-55094
```release-note
NONE
```
> Improves get roles by names requests to batch them following the new endpoint limit

- .github/workflows/build-android-beta.yml
Fix branch convention for single build 
```release-note
```
> fix: Fix branch convention for beta android single build

- fastlane/Pluginfile
This works around the recent yanking of the `find_replace_string` ruby plugin from RubyGems, as reported here: https://github.com/jonathanneilritchie/fastlane-plugin-find_replace_string/issues/3#issue-2060246328
After verifying this this works, we also need to backport this to all active release branches,
https://mattermost.atlassian.net/browse/CLD-6883
```release-note
NONE
```
> CLD-6883 Fix build script failure

- app/utils/url/path.ts
This PR fixes an issue where the webapp cannot switch to a DM channel when the other user is a remote user (shared channel) with a colon in the user name.  The underlying issue is the URLs for DM channels are [now validated via regex](https://github.com/mattermost/mattermost/pull/24622) and failed due to the presence of a colon in the DM username.
The fix is to allow colons in the `IDENTIFIER_PATH_PATTERN`  regex used to validate channel URLs.
See:  https://github.com/mattermost/mattermost/pull/25887
https://mattermost.atlassian.net/browse/MM-56530
also fixes https://mattermost.atlassian.net/browse/MM-52576
```release-note
Fixes switching to a Direct Message channel with a shared channel user (user from another server).
```
> Fix channel switcher routing for DMs with remote users

- app/screens/channel_add_members/channel_add_members.tsx
removes from the list of users to be added as a channel member those users who have been deactivated.
https://mattermost.atlassian.net/browse/MM-56513
PR to restrict it from the server https://github.com/mattermost/mattermost/pull/25954 (current apps used with the server that has this patch, would just show an alert message with an error)
```release-note
NONE
```
> MM-56513 Do not display deactivated users to add channel members

- scripts/bump.sh
Sometimes we need to open version bump PRs direclty to the release branches, rather than the master branch (e.g. for patch releases). In such cases, the milestone does not exist on Github anymore, which currently leads to [the version bump script failing](https://github.com/mattermost/delivery-platform/actions/runs/7609996579/job/20722402016).
This PR removes the strict dependency on the milestone existing, 
https://mattermost.atlassian.net/browse/CLD-7006
```release-note
NONE
```
> CLD-7006 Fix version bump script

- scripts/bump.sh
PR https://github.com/mattermost/mattermost-mobile/pull/7774 contained an error in the implementation, which this PR fixes.
This also solves other issues reported by the shellcheck tool (aside from the `.env` import; thanks @phoinixgrr for raising this!).
https://mattermost.atlassian.net/browse/CLD-7006
```release-note
NONE
```
> CLD-7006 Fix version bump script pt2

- app/screens/home/channel_list/categories_list/index.tsx
When the server has no teams, foldable devices that started the app folded, got into a weird state when unfolding them. This was due to the value `tabletWidth` not being set, since the effect was checking the && of the two conditions, instead of each condition separately.
This only happens when there are no teams because `moreThanOneTeam` is false, so changes in `isTablet` are not listened by the effect.
```release-note
Fix issue with foldable devices where sometimes it wasn't possible to navigate to Home in the unfolded view
```
> Fix foldable device LHS size when changing modes

- app/actions/remote/user.ts
- app/components/post_draft/send_handler/index.ts
- app/components/post_draft/send_handler/send_handler.tsx
- app/components/post_list/index.ts
- app/components/post_list/post/header/header.tsx
- app/components/post_list/post/header/index.ts
- app/components/post_list/post_list.tsx
- app/components/system_header/index.tsx
- app/screens/home/recent_mentions/index.ts
- app/screens/home/recent_mentions/recent_mentions.tsx
- app/screens/home/saved_messages/index.ts
- app/screens/home/saved_messages/saved_messages.tsx
- app/screens/home/search/results/index.tsx
- app/screens/home/search/results/post_results.tsx
- app/screens/home/search/results/results.tsx
- app/screens/pinned_messages/index.ts
- app/screens/pinned_messages/pinned_messages.tsx
- app/screens/settings/display/display.tsx
- app/screens/settings/display/index.tsx
- app/utils/draft/index.ts
- app/utils/post_list/index.ts
- app/utils/timezone.ts
- types/api/config.d.ts
Removed usages of `ExperimentalTimezone` and `isTimeZoneEnabled` to permanently enable timezone support in the mobile app
Fixes https://github.com/mattermost/mattermost/issues/24665
NA
```release-note
NONE
```
> [MM-54704] Permanently enable timezone support in the mobile app

- ios/Mattermost/Info.plist
Previously committed a change that was not intended to not allow arbitrary loads on iOS.
https://mattermost.atlassian.net/browse/MM-56725
Fixes: #7800 
```release-note
Fixed http connections on iOS that was previously removed.
```
> revert change to allow arbitrary loads

- app/screens/home/channel_list/servers/index.tsx
Fixes the badge color for unread and mentions in the icon to switch servers.
https://mattermost.atlassian.net/browse/MM-56656
```release-note
Fixed the mention badge color of multiple servers
```
@amyblais consider this for 2.13.0
> Fix multi-server icon mention badge

- .github/actions/prepare-mobile-build/action.yaml
- .github/workflows/build-ios-beta.yml
- .github/workflows/build-ios-release.yml
- .github/workflows/build-pr.yml
- .github/workflows/github-release.yml
- Saves almost 10 minutes in all iOS build jobs.
before:
after:
```release-note
NONE
```
> MacOS-latest-xlarge for m1 github runners

- detox/package-lock.json
- detox/package.json
- detox/utils/artifacts.js
This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).
```console
$ npx aws-sdk-js-codemod@0.26.1 -t v2-to-v3 detox/utils/artifacts.js
```
Similar to https://github.com/mattermost/mattermost/pull/25301
From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.
N/A
N/A
```release-note
NONE
```
> chore: migrate AWS SDK for JavaScript v2 APIs to v3

- app/components/markdown/markdown.tsx
- app/components/post_list/post/body/message/message.tsx
Unsafe links can potentially be generated by LLMs in the Mattermost AI plugin. For example a prompt injection could occour that tells the AI to create a malicious link that contains private data in the query paramenter: `http://badserver.com/all/my?private=data`
This adds the ability to restrict posts that have this unsafe property by adding an unsafe links post prop and passing a rendering option. This option prevents posts from rendering links and it prevents markdown images from being rendered.
Webapp PR: https://github.com/mattermost/mattermost/pull/26129
```release-note
NONE
```
> Add handling of posts with unsafe links.

- .github/actions/prepare-ios-build/action.yaml
This PR solves an incompatibility between the [latest watchman formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/w/watchman.rb) and the current MacOS runners.
Analysis of the root cause: the `brew install watchman` command seems to try to install both python 3.11 (required by e.g. `azure-cli`) and python 3.12 (required by the latest `watchman`, already present in the system but outdated), and these two formulae versions compete for the corresponding python symlinks under `/usr/local/bin`, which causes the installation to fail. As a workaround, we pre-install the latest `python@3.12` before installing watchman, for this to be handled cleanly.
https://mattermost.atlassian.net/browse/CLD-7296
```release-note
NONE
```
> CLD-7296 Fix watchman installation after dependency changes

- app/components/post_list/post_list.tsx
On https://github.com/mattermost/mattermost-mobile/pull/7851 we added a feature that was considering the post list always had posts to show.
This is not true, since the first time we navigate to a channel, the post list gets rendered while still fetching the posts for the channel. This caused an issue when trying to access the id of the first post.
This PR solves the issue.
Fix https://mattermost.atlassian.net/browse/MM-57530
```release-note
NONE
```
Fixes an issue introduced into a PR that hasn't been released yet.
> Fix id error when moving to a channel

- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/Podfile.lock
- package-lock.json
- package.json
- patches/@sentry+utils+7.100.1.patch
On https://github.com/mattermost/mattermost-mobile/pull/7891 I added the privacy files, but I made the big mistake of not running the app after setting this up. The result is that the `sentry` package was also declaring this privacy file and making conflicts with our own.
This was solved on later versions of sentry, so I updated the dependency to the latest, as https://github.com/mattermost/mattermost-mobile/pull/7863 was going to do either way.
The idea to push this PR separately is because right now it is not possible to create a build because of this failure.
None
```release-note
NONE
```
> Update sentry to fix error with the Privacy files

- index.ts
Improved startup performance by using polyfill-force on all @formatjs polyfills. `require('@formatjs/*/polyfill')` calls `shouldPolyfill()` method which in some instances could take over 2000ms.
When using Samsung Galaxy S9, it was observed that the startup time even after initial install was taking over 7s to move from splash screen to server screen.  Added a bunch of logInfo() between ./index.ts => ./app/screen/server/index.tsx and discovered that the biggest execution time was during polyfill-ing.  At first, created a dynamic loading as example can be found here: https://formatjs.io/docs/polyfills/intl-pluralrules/
```
import {shouldPolyfill} from '@formatjs/intl-pluralrules/should-polyfill'
async function polyfill(locale: string) {
const unsupportedLocale = shouldPolyfill(locale)
// …
```
> fix: use polyfill-force to improve startup time

- app/components/post_list/post_list.tsx
Only on threads, we were seeing a weird behavior of the pull to refresh functionality.
It will blur the images, and sometimes won't go back to its original state.
The main difference was we were passing the `disablePullToRefresh` prop to the post list. This prop decided whether to pass or not the `onRefresh` function. This seems to cause the whole list to re-render when changing form `undefined` to a proper function.
Moving the logic of `disablePullToRefresh` inside the `onRefresh` makes it so the flat list always has a `onRefresh` function, and does not re-render the complete list.
Fix https://mattermost.atlassian.net/browse/MM-57063
```release-note
Fix erratic behavior when pull up to refresh on a thread
```
> Fix erratic behavior of pull to refresh on threads

- app/screens/post_options/post_options.tsx
Fixes https://github.com/mattermost/mattermost/issues/26674
Fixes Jira https://mattermost.atlassian.net/browse/MM-52675
```release-note
When clicking on the "Copy Text" list item in a channel post dot menu (accessed by clicking the three dots) for a post that includes embedded images using markdown, the clipboard now receives the markdown as was entered into the original post instead of one that includes a proxy link.
```
> [MM-52675] Use message_source in copy text action (#26674)

- android/app/src/main/AndroidManifest.xml
- ios/Podfile.lock
- package-lock.json
- package.json
- patches/@voximplant+react-native-foreground-service+3.0.2.patch
- The recent bump to Android 34 (#7863) broke calls, this fixes it. Android 34 requires more specific permissions and some new code for foreground services (we're using that to make the call continue while the app is in the background).
- Totally understandable and unanticipated consequence of updating things. But it highlights a problem we have with mobile -- no calls e2e test infra. Until we get that, I wonder if we could request manual testing from @DHaussermann or myself on any react-native or Android SDK bumps like that, to make sure Calls doesn't break?
- Related, I reverted the `react-native-webrtc` upgrade from that PR as well -- we don't want to upgrade that without thorough testing. It's a fast-moving package and often breaks things. If possible, could XYZ update that when …
> [MM-58074] Calls: Fix crashing app when starting/joining call

- .github/actions/prepare-android-build/action.yaml
Use Java 17 in CI to fix build problems
```release-note
NONE
```
> Use Java 17 in CI

- app/actions/remote/channel.ts
- app/actions/websocket/index.ts
- app/screens/channel/channel_post_list/channel_post_list.tsx
When we mark a channel as read on the server, the "active channel" gets set. This handles how we receive push notifications.
This PR makes sure we unset the active channel when we exit from the channel screen, or we send the app to the background.
I also piggybacked a fix for channels in other servers being read when they should not.
Fix https://mattermost.atlassian.net/browse/MM-57000
```release-note
Improve status management to avoid missing notifications
Fix issue where channels from other servers may get read on startup
```
> Properly unset the active channel in the server

- app/components/post_list/post/body/content/image_preview/image_preview.tsx
The ImagePreview component for some reason (code from 2Y) ago was using the wrong Animated component, now replaced with the one provided by the reanimated library.
This was causing the library to access a property directly that causes the crash as it should only be accessible in the UI Thread (native side)
This crash is only happening after updating the Reanimated library with all the other deps done for 2.16, so this PR needs to be cherry picked.
https://mattermost.atlassian.net/browse/MM-58137
```release-note
NONE
```
> MM-58137 Fix crash by importing the correct Animated component

- app/screens/home/channel_list/servers/servers_list/server_item/options/option.tsx
We were using the wrong text color from the theme. This was not a problem in most of the themes, because it was coincident with the color of the icon, but on Quartz theme they are different.
Now the theme color used for the text and the icon are the same.
Fix https://mattermost.atlassian.net/browse/MM-56657
```release-note
Fix server option text on Quartz theme
```
> Fix server options text by in Quartz theme

- app/screens/in_app_notification/index.tsx
On react native gesture handler v2.16.0 they changed the default flex for GestureHandlerRootView from 0 to 1.
This caused the gesture handler to fit the whole screen, catching the input even if the overlay was set not to catch taps in the background.
Passing the new flex solves the issue.
Fix https://mattermost.atlassian.net/browse/MM-32183
```release-note
NONE
```
Issue introduced in https://github.com/mattermost/mattermost-mobile/pull/7863 which is not yet in the release branch.
> Fix notification impeding the input in the rest of the app

- app/screens/home/tab_bar/home.tsx
- ios/NotificationService/NotificationService.swift
While testing I noticed that, specially when the app was in the background, the notification badge was not being updated.
After some testing, I think the root cause is a race condition. The notification badge is set on the native side looking at the values in the database. But the database is not updated until the information is processed in the JS side. So more often than not, the information in the database is not yet ready. This is a bigger issue if the database returns 0 mentions, since 0 has a bigger meaning in this context.
We solve this by updating the badge on the frontend when we are in the background, and assigning nil in the native side, so the badge stays the same.
(Documentation reference: https://developer.apple.com/documentation/usernotifications/unmutablenotificationcontent …
> Avoid race condition setting the badge number when the app is in the background

- app/products/calls/actions/calls.ts
- app/products/calls/client/rest.ts
- app/products/calls/screens/participants_list/index.ts
- app/products/calls/screens/participants_list/participants_list.tsx
- assets/base/i18n/en.json
- Add the mute all command in the participant list for hosts
- Designs: https://www.figma.com/file/8C0ojMc778Zx3a0nm66Edw/MM-56584-Host-Controls?node-id=1270%3A54648&mode=dev
- https://mattermost.atlassian.net/browse/MM-57470
- Android: 13, Galaxy Tab s7+
- iOS: 16.5.1, iPhone 14
```release-note
Calls: Host controls, mute all option added to participants list
```
> [MM-57460] - Calls: Host controls, add mute all to participant list

- android/app/build.gradle
- ios/Mattermost.xcodeproj/project.pbxproj
- ios/Mattermost/Info.plist
- ios/MattermostShare/Info.plist
- ios/NotificationService/Info.plist
Bump app build number to 521.
Generated manually as this week's build number bump workflow failed because of an occasional hiccup: https://github.com/mattermost/delivery-platform/actions/runs/9029904371/job/24813150605
```release-note
NONE
```
> Bump app build number to 521

- scripts/bump.sh
Fix for a better error message when the PR creation fails, on a version bump script ruin
```release-note
NONE
```
> Move away from curl and jq for the version bump script

- scripts/bump.sh
This PR solves an error introduced here: https://github.com/mattermost/mattermost-mobile/pull/7957/files
tldr: if `grep` doesn't find the given pattern, it will not only print nothing (which was the intention) but also silently exit with error code 1. This is why the workflow keeps failing.
The solution is to move to `sed` instead, to perform the same task.
https://mattermost.atlassian.net/browse/CLD-7793
```release-note
NONE
```
> Fix MILESTONE_FOUND command

- app/components/autocomplete/at_mention/at_mention.tsx
In https://github.com/mattermost/mattermost-mobile/pull/7506 we changed the behavior of the user autocomplete. Among other things, we made an async call where there was no async call, and we were not waiting for it, causing the `loading` state setting back to false before setting the users. This let the autocomplete think there are no results to show.
Awaiting that line solves the issue.
Fix https://mattermost.atlassian.net/browse/MM-58493
```release-note
NONE
```
I think the offending PR has not yet being released. If it has been released, then the release note should show:
Fix issue where the user autocomplete doesn't show in the search screen on some circumstances
> Fix user autocomplete not always showing on search screen

- app/components/autocomplete/at_mention/at_mention.tsx
We were always getting the users from the database on user autocomplete, which may not have all the information.
We fix that by appending at the end the rest of the users received from the API.
https://mattermost.atlassian.net/browse/MM-58504
```release-note
NONE
```
Issue introduced probably by https://github.com/mattermost/mattermost-mobile/pull/7506 , which (I think) never made it to production.
> Fix user autocomplete not showing users not in channel

- app/screens/bottom_sheet/index.tsx
- app/screens/emoji_picker/index.tsx
- app/screens/post_priority_picker/footer.tsx
- app/screens/post_priority_picker/post_priority_picker.test.tsx
- test/setup.ts
We were passing the post priority footer (with the buttons to apply) to the bottom sheet, but these were never added in the tablet version.
I made it so the bottom sheet wrapper adds the footer so future implementations take that into account.
The only other component that uses the footer is the emoji picker. I tried to make this work this way, but the picker seemed to have too much custom logic to do it in a different way. We may consider making changes on this in the future.
https://mattermost.atlassian.net/browse/MM-58193
```release-note
Fix apply button not appearing on iPads when trying to set the post priority
```
> Fix priority footer on tablets

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/xml/data_extraction_rules.xml
- patches/react-native-exception-handler+2.10.10.patch
- patches/react-native-notifications+5.1.0.patch
This PR patches a couple of dependencies to set the activities and services with the flag of exported=false
Also address in this PR, corrections to our own Manifest file to apply exported=false and other improvements, specially around backups.
```release-note
NONE
```
> T271: Prevent access to Android components if they do not need external comms

- app/utils/config.test.ts
- app/utils/datetime.test.ts
- app/utils/error_handling.test.ts
- app/utils/errors.test.ts
- app/utils/errors.ts
- app/utils/files.test.ts
- test/setup.ts
continue to add unit tests to the utils folder for the effort to increase the overall tests coverage for the entire app to 80%
```release-note
NONE
```
> Add unit tests to utils config, datetime, error_handling, errors and files

- ios/Mattermost/Info.plist
This PR changed the UIRequiredDeviceCapabilities value for iOS: https://github.com/mattermost/mattermost-mobile/pull/8011
However, after it was merged, Apple refused to accept the weekly beta build:  https://github.com/mattermost/mattermost-mobile/actions/runs/9646645994/job/26603731918#step:5:9750
Looking up some docs it seems the correct value expected by UIRequiredDeviceCapabilities is `arm64`: https://developer.apple.com/documentation/bundleresources/information_property_list/uirequireddevicecapabilities/
After this PR is merged, i'll trigger a new beta build for iOS cc @amyblais 
https://mattermost.atlassian.net/browse/CLD-7948
```release-note
NONE
```
> Fix typo in UIRequiredDeviceCapabilities for iOS

- build/notice-file/config.yaml
A recent PR migrated some functionality to local modules referenced in `package.json`: https://github.com/mattermost/mattermost-mobile/pull/8011
The code is local to the repository, and thus doesn't need to be reported in the `NOTICE.txt` file. The new notice-file-generator config file format supports the `ignoreDependencies` field to do just that.
https://mattermost.atlassian.net/browse/CLD-7943
```release-note
NONE
```
> Ignore local deps in notice-file-generator config

- android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.kt
While looking into the notifications acks, I noticed that notifications stopped arriving (not sure why). The logcat was complaining about `getCurrentActivity` being called on a undefined object in this line.
Not sure how to reproduce the bug, but after this change, I didn't see it happening again in the tests.
NONE
```release-note
NONE
```
The bug seems introduced by https://github.com/mattermost/mattermost-mobile/commit/b8c088cc70887ab054f7cd32a8fc14a186b3ee71 , so it shouldn't be in any released version.
> Fix null reference error in notifications

- fastlane/Fastfile
The filename in the URL should be `Mattermost.apk`, not `Mattermost-universal.apk`. For instance:
- I have fixed the URL manually for the 2.17.1 release: https://github.com/mattermost/mattermost-mobile/releases/tag/v2.17.1
- The 2.17.0 release contains the old URL instead, which doesn't work: https://github.com/mattermost/mattermost-mobile/releases/tag/v2.17.0
For reference: the change likely happened between [the 1.41.1 release](https://github.com/mattermost/mattermost-mobile/releases/tag/v1.41.1) and [the 1.42.0 release](https://github.com/mattermost/mattermost-mobile/releases/tag/v1.42.0) in 2021, although I couldn't find the exact change that caused the filename to change in the first place.
https://mattermost.atlassian.net/browse/CLD-6866
```release-note
NONE
```
> Fix the Universal Android build download URL for releases

- app/managers/network_manager.ts
The `deviceName` may contain non-ASCII characters such as CJK or other characters. Some devices may not support this behavior. It is recommended to remove `deviceName` or move it to another field to avoid such issues.
This issue was primarily observed on the Samsung A22, but it did not occur on my Xperia 1 V.
None
Samsung A22, Android 13
Xperia 1 V, Android 13
```release-note
NONE
```
> Fix User Agent issue in some device

- app/managers/performance_metrics_manager/index.test.ts
- app/managers/performance_metrics_manager/index.ts
- app/managers/performance_metrics_manager/performance_metrics_batcher.test.ts
- app/managers/performance_metrics_manager/performance_metrics_batcher.ts
Specially on iOS, we seem to have a race condition with the load measures. I added a retry (in case the masure is not yet on the JS side) and a warning if even after the retries is not there.
Right now the retry will delay the measure up to 300ms. Given we are in the realm of several seconds for mobile load, I don't think this will skew too much the metrics.
https://mattermost.atlassian.net/browse/MM-59280
```release-note
NONE
```
> Graciously handle load measure when there is no mark

- app/actions/local/category.test.ts
Improving our unit test coverage of app/actions/local/category.
Coverage for this file goes from 30.33% -> 85.39% statements.
n/a
```release-note
NONE
```
> Add unit tests for app/actions/local/category

- app/components/autocomplete/at_mention/at_mention.tsx
- app/components/autocomplete/at_mention/constants.ts
- app/components/autocomplete/at_mention/types.ts
- app/components/autocomplete/at_mention/utils.ts
- assets/base/i18n/en.json
On https://github.com/mattermost/mattermost-mobile/commit/105073ce7638248ad4a87e5c1bc2c3c0c69111b2 the "Out of Channel" section was removed from the user autocomplete per the feature specifications, but after the change was made, we realized we still nee the "Out of Channel" section.
This PR reverts back the changes related to removing the out of channel section, and do a bit of cleanup moving the different util functions, types and constants to their own files for better readability of the component file.
Fix https://mattermost.atlassian.net/browse/MM-58508
```release-note
Restore "Out of Channel" section on user autocomplete
```
> Restore out of channel and some cleanup

- scripts/postinstall.sh
Fix issue when running `npm install` and the error shows up as
```
Generating app assets
Copying sound assets for bundling
cp: android/app/src/main/res/raw is not a directory
```
I see in Fastfile that the directory is being created prior to copying the sound file.
```release-note
```
> fix: add mkdir of "android/app/src/main/res/raw/" in postinstall

- app/utils/channel/index.test.ts
- app/utils/channel/index.ts
- app/utils/deep_link/index.test.ts
- app/utils/document/index.test.ts
- app/utils/draft/index.test.ts
- app/utils/emoji/helpers.test.ts
- app/utils/emoji/helpers.ts
Increase unit test coverage for utils/channels utils/deep_link utils/document utils/draft and utils/emoji/helpers
```release-note
NONE
```
> Add more utils unit test coverage

- app/actions/local/file.test.ts
- app/actions/local/group.test.ts
Improving our unit test coverage of app/actions/local/file and app/actions/local/group.
Coverage for file.ts goes from 11.76% -> 100% statements.
Coverage for group.ts goes from 8.33% -> 91.66% statements.
n/a
n/a
```release-note
NONE
```
> Add unit tests for app/actions/local/file and app/actions/local/group

- detox/save_report.js
Reverted previous change to `ZEPHYR_ENABLE` for it requires a string
none
If no release notes are required write NONE. Use past-tense. Newlines are stripped.
Example:
```release-note
NONE
```
> fix: saving test report

- app/actions/local/post.test.ts
Improving our unit test coverage of app/actions/local/post.
Coverage for this file goes from 2.11% -> 99.29% statements.
n/a
n/a
```release-note
NONE
```
> Add unit tests for app/actions/local/post

- app/utils/file/index.test.ts
- app/utils/file/index.ts
Increase the unit test coverage for the file utils.
n/a
```release-note
NONE
```
> add file utils unit tests

- app/screens/home/channel_list/servers/index.tsx
The Add Server footer was being added and causing an error trying to access a hook outside of the gorhom provider for the bottom sheet as on Tablet it opens as a Modal.
Note: The Add Server button was being added twice as well.
https://mattermost.atlassian.net/browse/MM-59527
```release-note
Fixed the server list modal displayed on Tablets
```
> Fix server list bottom sheet on tablet

- app/actions/remote/entry/login.ts
- app/managers/performance_metrics_manager/index.ts
- share_extension/index.tsx
On the performance metrics we have seen that specially on Android, we are seeing a lot of load events over 30 seconds. This is out of the ordinary. I found two instances where this might happen:
- On initial login, after we already have logged in, if we close the app by hitting the back button and open it again, the target will be set and the performance metric will be generated. Nevertheless, the "init time" will be still set to the time we opened the app before login.
- When we open the share menu, the app opens. If we then open the app, the load logic will send a performance metric based on the init time when the share menu was opened.
I solved this by making sure we skip the load metric on those two scenarios.
NONE
```release-note
Improve load time performance metrics
```
> Avoid registering wrong performance load logs

- android/app/src/main/AndroidManifest.xml
- libraries/@mattermost/rnshare/android/src/main/java/com/mattermost/rnshare/ShareWorker.kt
On Android devices, when sharing photos (from camera or internal storage), or files, or screenshots, the app will more likely crash.  This is because the app is now being built using target SDK version of 34 (Android 14).  Recent changes on [Android 14](https://developer.android.com/about/versions/14/changes/fgs-types-required)
> Caution: If your app doesn't fulfill all of the runtime requirements for starting a foreground service, the system throws a [SecurityException](https://developer.android.com/reference/java/lang/SecurityException) after you call startForeground() for that service. This prevents the foreground service from starting, might cause a running foreground service to be removed from the foreground process state, and might cause your app to crash. …
> fix: (MM-59956) Android crash when sharing

- app/actions/local/systems.test.ts
- app/actions/local/systems.ts
Add unit test coverage of app/actions/local/systems.
Coverage for this file goes from 0.78% -> 91.79% statements.
https://mattermost.atlassian.net/browse/MM-59618
n/a
n/a
```release-note
NONE
```
> MM-59618 Add unit test coverage of app/actions/local/systems

- app/actions/local/channel_bookmark.test.ts
Add unit test coverage of app/actions/local/channel_bookmark.
Coverage for this file goes from 0% -> 100% statements.
https://mattermost.atlassian.net/browse/MM-59617
n/a
n/a
```release-note
NONE
```
> MM-59617 Add unit tests for actions/local/channel_bookmark

- ios/Mattermost/Info.plist
Remove strings related to location permissions since we don't use location permissions.
```release-note
NONE
```
> Remove location strings from info.plist

- app/actions/remote/search.ts
- app/screens/channel_files/channel_files.tsx
The attachment list API was failing due to an incorrect API call. The API call to fetch files should include teamId, which was missing. This PR resolves the issue by retrieving the teamId for DMs and GMs (since teamId is not stored for DMs and GMs inside the `channels` table, it needs to be fetched from the systems table) and then making the API call to fetch files with the correct teamId.
https://mattermost.atlassian.net/browse/MM-54528
```release-note
NONE
```
> Attachment list in view info for DMs and GMs mobile

- app/components/post_draft/post_input/post_input.tsx
- app/screens/home/index.tsx
- app/screens/home/search/search.tsx
- libraries/@mattermost/hardware-keyboard/src/index.tsx
The events for the hardware keys were set on mount, and any change after that did not reflect afterwards. Therefore, the `sendMessage` function used is the one that thought that the empty message is the message to post, and that is why it looked like "it was not working".
Properly handling dependencies and so on fixes the issue.
Fix https://mattermost.atlassian.net/browse/MM-60220
```release-note
Fix issue where iPad hardware keyboard may not work as intended
```
> Fix hardware keys not working as expected

- app/components/post_draft/post_input/post_input.tsx
During the libraries updates, the PasteableTextInput library started to set the `autoCapitalize` prop by default to `none` instead of `sentences`.
The real fix should be done in the library, but this PR can be used as an interim solution.
https://mattermost.atlassian.net/browse/MM-60263
```release-note
Fix bug where the Android Keyboard may not autocapitalize the first letter of a sentence by default when writing a post
```
> Quick fix for post input not capitalizing the start of sentences

- app/products/calls/types/calls.ts
- app/screens/sso/sso_authentication.tsx
- assets/base/i18n/en.json
Adds a transitional screen when the SSO is successful
https://hub.mattermost.com/private-core/pl/55xw79opufn6jrzawkuzrrxjtc
```release-note
Added a new message to SSO login screen when the login is successful.
```
> fix sso login success message

- app/products/calls/components/captions.tsx
- app/products/calls/connection/websocket_event_handlers.ts
It took a while to track this down but it looks like https://github.com/mattermost/mattermost-mobile/pull/8011 caused a regression in the way the style of the live captions container for calls behaved. The bottom-based positioning changed in a way that caused the container not to show at all. I am not sure if this was a change on our side or simply due to updating some stuff.
Since we are here, I am also fixing a related issue with the calls jobs state not getting synched as expected.
https://mattermost.atlassian.net/browse/MM-60291
```release-note
Fixed a regression that prevented live captions for calls to show
```
> [MM-60291] Fix rendering of live captions

- app/utils/navigation/index.test.ts
Adds code coverage to 100% for app/utils/navigation
https://mattermost.atlassian.net/browse/MM-59572
```release-note
NONE
```
> add unit tests for app/utils/navigation

- app/utils/notification/index.test.ts
- test/setup.ts
code coverage for app/utils/notifications
https://mattermost.atlassian.net/browse/MM-59573
```release-note
NONE
```
> add unit tests to app/utils/notification

- android/app/src/main/AndroidManifest.xml
To comply with [this new policy](https://support.google.com/googleplay/android-developer/answer/14115180) of Google, I removed the `READ_MEDIA_VIDEO` and `READ_MEDIA_IMAGE` permissions.
These were added in https://github.com/mattermost/mattermost-mobile/pull/6667 , my guess when the `@react-native-camera-roll/camera-roll` was added.
We are not asking or checking for those particular permissions in the code, and after some testing, I didn't see anything breaking after removing the permissions, but further tests would be needed.
The reason why we don't need these is that we are using native image pickers, and not using anything extra to read the images / videos, so it should be fine.
Please let me know if I may be missing something.
Fix https://mattermost.atlassian.net/browse/MM-59810 …
> Remove unneeded permissions

- app/screens/sso/components/auth_error.tsx
- app/screens/sso/components/auth_redirect.tsx
- app/screens/sso/components/auth_success.tsx
- app/screens/sso/index.tsx
- app/screens/sso/sso_authentication.tsx
- app/screens/sso/sso_authentication_with_external_browser.tsx
- assets/base/i18n/en.json
- types/api/config.d.ts
Introducing a client config property that determines if the mobile app should use the default external browser to perform SSO Authentication instead of the internal one. https://github.com/mattermost/mattermost/pull/28180
Important: We want to include this in a dot release so that ships as soon as possible.
Also addresses an issue reported in #8206 
https://mattermost.atlassian.net/browse/MM-60332
Fixes: #8206
Fixes: #8155
```release-note
Added config setting NativeAppSettings -> MobileExternalBrowser that tells the mobile app to perform the SSO Authentication using the external default browser
```
> open an external browser when the server config for MobileExternalBrowse is set to true

- detox/e2e/test/messaging/message_draft.e2e.ts
Removed reference to fixed issue ` -- KNOWN ISSUE: MM-50298`.
During audit of mobile tests, found a reference in https://github.com/mattermost/mattermost-mobile/blob/main/detox/e2e/test/messaging/message_draft.e2e.ts  to a "known issue" that has since been fixed and closed: https://mattermost.atlassian.net/browse/MM-50298
```release-note
NONE
```
> feat(test): Mobile message drafts: Remove outdated reference to fixed issue

- detox/e2e/test/messaging/message_reply.e2e.ts
Removed outdated note ` -- KNOWN ISSUE: MM-50206`
During audit of mobile tests, found a reference in https://github.com/mattermost/mattermost-mobile/blob/main/detox/e2e/test/messaging/message_reply.e2e.ts to a "known issue" that has since been fixed and closed: https://mattermost.atlassian.net/browse/MM-50206.
```release-note-none
NONE
```
> feat(test): Mobile reply: Remove outdated note about fixed issue

- app/components/button/index.tsx
- app/screens/review_app/index.tsx
Fix "rate my app" broken styles 🤦 
https://mattermost.atlassian.net/browse/MM-60534
- [ x] Has UI changes
This PR was tested on: android and ios emulator
Before:
After:
Android:
ios:
```release-note
NONE
```
> MM-60534 -fix rate my app broken styles

- app/components/markdown/markdown.tsx
- types/global/markdown.ts
The following ticket reported that images that were wrapped into a link inside Markdown were not triggering the link itself, but just opened the image.
Previous behavior:
https://github.com/user-attachments/assets/6260c2d1-c831-40d3-9835-ac602ca8c70b
I changed the behavior, now if an image is inside a link in Markdown, the user will be able to navigate to the link:
https://github.com/user-attachments/assets/c69ed639-3f00-49ab-b586-7fcdd9dbffb1
https://mattermost.atlassian.net/browse/MM-60425
https://github.com/mattermost/mattermost-mobile/issues/8208
- iOS Simulator 17.2
- Android Simulator API 33
It doesn't have any UI changes
```release-note
Images inside Links within Markdown are now clickable for link navigation.
```
> MM-60425 Making clickable images work inside Markdown

- app/components/animated_number/index.tsx
* tried to include everything into useMemo was an anti-pattern
* moved back to useMemo + useEffect
* previousNumber and animateToNumber comparison has some flaw when dealing with difference length between the two
```release-note
```
> fix: (MM-59973) emoji count 0 update

- app/database/operator/server_data_operator/handlers/channel.ts
- app/queries/servers/channel_bookmark.ts
When sorting the channel bookmarks on the webapp, the WS event was not changing the update_at property of the objects
We are now also updating the local records if the `sort_order` has changed to fix the sorting updates while the server does not have the changes included in https://github.com/mattermost/mattermost/pull/28807
https://mattermost.atlassian.net/browse/MM-60644
https://github.com/mattermost/mattermost/pull/28807
```release-note
Fixed the sort order of channel bookmarks when sorted on a different client
```
> fix bookmarks sort order when WS does not bump update_at

- app/utils/search/index.test.ts
Adds code coverage for utils/search from 0% to 100%
https://mattermost.atlassian.net/browse/MM-59578
```release-note
NONE
```
> Add utils/search unit tests

- .eslintrc.json
* Changing the rule for exhaustive-deps to 'warn' vs 'off'
* not properly having the correct dependencies in useEffect or useMemo can cause a significant issue, such as: https://github.com/mattermost/mattermost-mobile/pull/8146
```release-note
```
> chore: exhaustive-deps eslint rules from 'off' to 'warn'

- app/constants/sso.ts
- app/screens/sso/sso.test.tsx
- assets/base/config.json
- fastlane/Fastfile
The authentication schemes were hardcoded to use `mmauthbeta` for our Beta app and `mmauth` for our release app. While the server allows this schemes to be changed in order to be used with custom mobile builds, the mobile app did not have a way to easily customize them, having to make some changes in the code before compiling.
This PR introduces a couple of environment variables to be able to change these authentication schemes on build time.
Note: This is backwards compatible so that the app builds the same way as before if no env var is set.
N/A.
```release-note
NONE
```
> Add support for Auth Scheme customization on build time

- app/init/push_notifications.ts
Adding some logs for the notification device token registration flow, this way we can inspect the device logs to determine if the token was registered or not, in case of no, then why
N/A
```release-note
NONE
```
> Add logs when notification device tokens is registered or fails to do so

- app/components/post_list/post/header/header.tsx
- app/components/post_list/post/post.tsx
- app/components/system_header/index.tsx
- assets/base/i18n/en.json
Added a visible to you text on ephemeral posts.
Fixes https://github.com/mattermost/mattermost/issues/28201
This PR was tested on:  Android Emulator Pixel 8a
```release-note
Added visible to you text on ephemeral posts
```
> feat: Add visible to you text on ephemeral posts

- app/components/team_sidebar/team_list/index.ts
The code to sort the teams based on the order established by the preferences wasn't working, the preferences are already sorted and if no preferences set we sort by the display name of the team.
Noticed this issue since we started to add more teams on Hub.
https://mattermost.atlassian.net/browse/MM-60723
```release-note
Fixed sort of teams in the Team Sidebar by following the user preferences if set.
```
> Fix sidebar teams order

- app/actions/remote/preference.test.ts
Add unit tests for actions/remote/preference. Coverage increases from 38.13% to 94.91%.
https://mattermost.atlassian.net/browse/MM-59448
n/a
```release-note
NONE
```
> MM-59448 Add tests to actions/remote/preference

- app/actions/remote/groups.test.ts
Add unit tests for actions/remote/groups. Coverage increases from 17.59% to 100%.
https://mattermost.atlassian.net/browse/MM-59436
n/a
```release-note
NONE
```
> MM-59436 Add tests to actions/remote/groups

- app/actions/remote/search.test.ts
Add unit tests for actions/remote/search. Coverage increases from 0% to 94.93%.
https://mattermost.atlassian.net/browse/MM-59422
n/a
```release-note
NONE
```
> MM-59422 Add tests to actions/remote/search

- app/components/badge/index.tsx
- app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
While fixing issue with https://github.com/mattermost/mattermost-mobile/pull/8312, there has been a few changes to the badge in the server list requested by @asaadmahmood.
This PR was tested on: iPhone 15 Simulator, 17.4.1
```release-note
```
> feat:proper badge theme use for server list

- app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap
- app/components/post_list/thread_overview/thread_overview.test.tsx
- app/components/post_list/thread_overview/thread_overview.tsx
- assets/base/i18n/en.json
- detox/e2e/test/smoke_test/messaging.e2e.ts
Hide the `ThreadOverview` component when a thread doesn't yet have replies.
Fixes: https://mattermost.atlassian.net/browse/MM-53775
Fixes: https://github.com/mattermost/mattermost/issues/24646
This PR was tested on: iOS Simulator, v18.1
```release-note
Hide the thread overview until there are replies.
```
> MM-53775: Hide Thread Overview until there are replies

- libraries/@mattermost/rnutils/ios/RNUtilsWrapper.swift
A couple of things were fixed here, first instead of using the window frame we are using the window bounds and secondly we only consider it to be a tablet layout if the app takes at least 2/3 of the screen width.
* `bounds`: Represents the window’s coordinate system and its size within its own context. The origin is typically (0,0), with width and height that represent the actual size of the window's content area.
* `frame`: Represents the window’s rectangle relative to its parent coordinate system, typically the screen’s coordinate space. If the window is rotated or scaled, the frame will change to reflect its position and orientation relative to the screen.
Using bounds is generally more reliable for checking size because:
1. **Orientation Independence**: bounds always represents the …
> Fix iPad split screen

- app/actions/remote/command.test.ts
- app/actions/remote/command.ts
Add unit tests for actions/remote/command. Coverage increases from x% to 95.06%.
This was my first time using GitHub Copilot Chat to help write tests. As a result it took me longer than usual to write these but they are more thorough than some of the other tests I've written.
https://mattermost.atlassian.net/browse/MM-59444
n/a
```release-note
NONE
```
> MM-59444 Add tests for actions/remote/command

- patches/@react-native-community+cli-platform-apple+13.6.9.patch
Fix issue so that `npm run ios` command will work again.  Fix suggested from:
https://github.com/react-native-community/cli/issues/2383#issuecomment-2440664971
```release-note
```
> chore: patch getBuildSettings to allow run ios from cli

- app/actions/remote/entry/common.ts
- app/actions/remote/thread.ts
We made some improvements to the performance of login here https://github.com/mattermost/mattermost-mobile/pull/8306 but there were two bugs that are fixed in this PR.
1. We were requesting channels, posts and others for the initial team even though we already have that data.
2. The exclusion of threads in DMs was checking for version 10.2.0 which is wrong, that PR just landed in master, so for the time being we just dedupe the models.
N/A
```release-note
NONE
```
> fix entry logic to not re-fetch data for the initial team

- app/hooks/device.ts
- app/screens/forgot_password/index.tsx
- app/screens/index.tsx
- app/screens/login/form.tsx
- app/screens/login/index.tsx
- app/screens/mfa/index.tsx
- app/screens/server/form.tsx
- app/screens/server/index.tsx
Fixes the scrolling of the contents of the following screens on iPhone, iPad & Android as part of broken window fixes
- Server
- Login
- Forgot password
- MFA
https://mattermost.atlassian.net/browse/MM-56150
Fixes: #8291
```release-note
NONE
```
> fix screen position for server / login / forgot password & mfa

- app/screens/custom_status/components/custom_status_input.tsx
- app/screens/custom_status/components/custom_status_suggestion/custom_status_suggestion.tsx
- app/screens/custom_status/custom_status.tsx
- clear button on long statuses was being drawn on top of the text
- not using same font as rest of the app
- recent status were having huge space between text and clear button
[MM-61129](https://mattermost.atlassian.net/browse/MM-61129)
This PR was tested on: android and ios simulators
```release-note
fix UI for editing custom status
```
[MM-61129]: https://mattermost.atlassian.net/browse/MM-61129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> prevent overlap of clear button, fix font, reduce space on recent statuses

- app/actions/remote/category.test.ts
Add unit tests for actions/remote/category. Coverage increases from 3.77% to 98.11%.
https://mattermost.atlassian.net/browse/MM-59450
n/a
```release-note
NONE
```
> MM-59450 Add tests for actions/remote/category

- app/components/team_sidebar/team_list/index.test.tsx
- app/components/team_sidebar/team_list/index.ts
With the amount of unions, filtering and mapping done in the team sidebar let's add some protective code to ensure the `id` is never undefined.
N/A
Potential cherry-pick for 2.23
```release-note
NONE
```
> Ensure myTeam.id is not undefined

- app/components/files/file_info.tsx
Text on React Native must be surrounded by a Text tag.
This particular text was breaking searches (and any other place where file infos where showing a date)
https://mattermost.atlassian.net/browse/MM-62057
Catched before release
```release-note
NONE
```
> Surround text on file info for searches

- app/components/post_list/combined_user_activity/combined_user_activity.tsx
- app/utils/post_list/index.ts
We were considering the `actorId` to be a required prop, but not all messages show the actor id.
https://mattermost.atlassian.net/browse/MM-62083
```release-note
NONE
```
> Fix join/leave messages not showing

- app/queries/servers/channel.test.ts
- app/queries/servers/channel.ts
Add unit tests for queries/server/channel. Coverage increases from x% to 97.71%. Apologies that it's a bit of a long one. I used copilot to help write a lot of the tests.
https://mattermost.atlassian.net/browse/MM-59779
n/a
```release-note
NONE
```
> MM-59779 Add tests for queries/server/channel

- app/components/post_list/post/body/content/message_attachments/attachment_image/index.tsx
- app/constants/image.ts
- app/utils/images/index.ts
Fixed the overflow if a message attachment is wider than the Viewport. (https://developers.mattermost.com/integrate/reference/message-attachments/#images)
This is done by modifying the `getViewPortWidth` and introducing a new `VIEWPORT_IMAGE_ATTACHMENT_OFFSET`.
The value of it is calculated with the padding of the `MessageAttachment` component (2 * 12) + the padding of the `AttachmentImage` component (2,5 + 5) => 31,5
https://github.com/mattermost/mattermost-mobile/blob/9b450cf68b60b47ebcb4ca84af9cc07293397567/app/components/post_list/post/body/content/message_attachments/message_attachment.tsx#L42
https://github.com/mattermost/mattermost-mobile/blob/9b450cf68b60b47ebcb4ca84af9cc07293397567/app/components/post_list/post/body/content/message_attachments/attachment_image/index.tsx#L26-L28 …
> fix: fixed image overflow in message attachments

- app/utils/server/index.ts
- app/utils/server/server.test.ts
- assets/base/i18n/en.json
Remove end user message for unsupported servers. We keep the admin message.
Fix https://mattermost.atlassian.net/browse/MM-59408
```release-note
End users won't receive messages about being on unsupported servers
```
> Remove end user message for unsupported servers

- app/actions/websocket/channel.test.ts
- app/actions/websocket/channel.ts
Add unit tests to actions/websocket/channel increasing coverage to 94.33%.
https://mattermost.atlassian.net/browse/MM-59652
n/a
```release-note
NONE
```
> MM-59652 Add unit tests to actions/websocket/channel

- app/components/settings/bool_setting.tsx
- app/components/settings/radio_setting/index.tsx
- app/components/settings/text_setting.tsx
- app/screens/interactive_dialog/dialog_element.tsx
- app/screens/interactive_dialog/index.tsx
We were forcing having a value for the dialog elements. This PR removes that limitation, and fixes the types around it.
Fix: https://mattermost.atlassian.net/browse/MM-62299
```release-note
Fix issue with interactive dialog not showing all the elements
```
> Fix interactive dialogs not showing

- app/screens/interactive_dialog/dialog_element.tsx
- app/screens/interactive_dialog/index.tsx
- app/utils/integrations.ts
The handling of the number field was not done right for a long time. We were passing a number value to the text input `value` property, which was completely ignoring it (since it was not a string).
The changes we did to be more coherent with the types surfaced the issue, by showing `NaN` in the input when we removed completely the number.
This PR solves that, and makes sure we only send on the submission proper numbers, and not the empty string for number values.
Fix https://mattermost.atlassian.net/browse/MM-62334
```release-note
Improve number field validation on Interactive Dialogs
```
> Fix interactive dialog number handling

- app/client/rest/tracking.test.ts
- app/client/rest/tracking.ts
This PR is to improve the categorization of requests by keeping track of requests start time.  As an example:
```
Request 1:   |++++++++++------------|
Request 2:        |+++++++++++++----------------|
Request 3:                          |+++++++++---------|
Request 4:                                     |++++++-----|
Request 5:                                      |+++++----|
Request 6:                                       |+++++----|
Request 7:                                       |+++++----|
Request 8:                                        |++++-----|
Request 9:                                         |++++-----|
Request 10:                                        |++++++---|
Request 11:                                        |++++++---|
Request 12: …
```
> fix: improve parallel requests calculation

- app/utils/opengraph.test.ts
- app/utils/opengraph.ts
Increase test coverage of utils/opengraph to 98.5%.
https://mattermost.atlassian.net/browse/MM-59600
```
PASS  app/utils/opengraph.test.ts
Utility Functions
getDistanceBW2Points
✓ calculates the distance correctly (1 ms)
✓ calculates the distance correctly with custom attributes
getNearestPoint
✓ finds the nearest point correctly
✓ returns an empty object if points array is empty (1 ms)
✓ finds the nearest point with custom attributes
✓ updates nearest point based on distance comparison
fetchRaw
✓ should fetch raw HTML from a URL (1 ms)
✓ should return response if not ok
✓ should return error message on fetch failure
getFavIcon
✓ should return the largest favicon URL (5 ms)
✓ should return default favicon URL if no icons found
✓ should handle shortcut icon rel …
```
> MM-59600 Add unit tests to utils/opengraph

- app/actions/remote/search.ts
- app/client/rest/categories.test.ts
- app/client/rest/channel_bookmark.test.ts
- app/client/rest/channels.test.ts
- app/client/rest/emojis.test.ts
- app/client/rest/files.test.ts
- app/client/rest/files.ts
- app/client/rest/general.test.ts
- app/client/rest/groups.test.ts
- app/client/rest/integrations.test.ts
- app/client/rest/nps.test.ts
- app/client/rest/plugins.test.ts
- app/client/rest/posts.test.ts
- app/client/rest/preferences.test.ts
- app/client/rest/teams.test.ts
- app/client/rest/threads.test.ts
- app/client/rest/tos.test.ts
- app/client/rest/users.test.ts
Increase test coverage of client/rest to 96.77%.
* https://mattermost.atlassian.net/browse/MM-59667
* https://mattermost.atlassian.net/browse/MM-59668
* https://mattermost.atlassian.net/browse/MM-59669
* https://mattermost.atlassian.net/browse/MM-59670
* https://mattermost.atlassian.net/browse/MM-59672
* https://mattermost.atlassian.net/browse/MM-59673
* https://mattermost.atlassian.net/browse/MM-59674
* https://mattermost.atlassian.net/browse/MM-59675
* https://mattermost.atlassian.net/browse/MM-59676
* https://mattermost.atlassian.net/browse/MM-59677
* https://mattermost.atlassian.net/browse/MM-59678
* https://mattermost.atlassian.net/browse/MM-59679
* https://mattermost.atlassian.net/browse/MM-59680
* https://mattermost.atlassian.net/browse/MM-59681
* …
> MM-59683 + more - Add tests to client/rest

- app/actions/remote/retry.test.ts
Increase test coverage of actions/remote/retry to 97.77%.
https://mattermost.atlassian.net/browse/MM-59433
n/a
```release-note
NONE
```
> MM-59433 Add unit tests to actions/remote/retry

- app/client/websocket/index.test.ts
- app/client/websocket/index.ts
Increase test coverage of client/websocket to 84.9%.
https://mattermost.atlassian.net/browse/MM-59684
n/a
```release-note
NONE
```
> MM-59684 Add tests for client/websocket

- app/utils/user/index.test.ts
- app/utils/user/index.ts
Increase test coverage of utils/user to 96.4%.
https://mattermost.atlassian.net/browse/MM-59586
n/a
```release-note
NONE
```
> MM-59586 Add tests for utils/user

- app/actions/websocket/posts.test.ts
- app/actions/websocket/posts.ts
Increase test coverage of actions/websocket/posts to 92.3%.
https://mattermost.atlassian.net/browse/MM-59656
n/a
```release-note
NONE
```
> MM-59656 Add tests for actions/websocket/posts

- app/actions/websocket/event.test.ts
Increase test coverage of actions/websocket/event to 96.91%.
https://mattermost.atlassian.net/browse/MM-59653
n/a
```release-note
NONE
```
> MM-59653 Add tests for actions/websocket/event

- app/screens/bottom_sheet/index.tsx
This PR isolates an issue brought by @lindalumitchell as can be seen in this video ([link](https://github.com/mattermost/mattermost-mobile/pull/8421#issuecomment-2586374627)).  The issue is when a user tries to open the server list on bottom sheet, it is being dismissed right away (sporadically).  This issue is not replicable on simulator or even release mode on real device.  Odd!
https://github.com/mattermost/mattermost-mobile/pull/8421
iPhone 13 Pro (18.2.1)
Fix (i hope!):
https://github.com/user-attachments/assets/ccab9c58-3bb1-4da4-87cc-0858314758bb
```release-note
```
> fix: RN 0.76.5 issue with bottom sheet disappearing

- app/actions/websocket/teams.test.ts
Increase test coverage for actions/websocket/teams to 97.43%.
https://mattermost.atlassian.net/browse/MM-59661
```release-note
NONE
```
> MM-59661 Add tests for actions/websocket/teams

- app/actions/websocket/category.test.ts
- app/actions/websocket/category.ts
- app/actions/websocket/integrations.test.ts
- app/actions/websocket/preferences.test.ts
- app/actions/websocket/reactions.test.ts
- app/actions/websocket/roles.test.ts
- app/actions/websocket/system.test.ts
- app/actions/websocket/threads.test.ts
Increase test coverage for remaining actions/websocket/ files.
https://mattermost.atlassian.net/browse/MM-59657
https://mattermost.atlassian.net/browse/MM-59660
https://mattermost.atlassian.net/browse/MM-59655
https://mattermost.atlassian.net/browse/MM-59659
https://mattermost.atlassian.net/browse/MM-59651
https://mattermost.atlassian.net/browse/MM-59662
https://mattermost.atlassian.net/browse/MM-59658
```release-note
NONE
```
> Add tests to remaining actions/websocket files

- app/components/channel_bookmarks/channel_bookmark/bookmark_icon.test.tsx
- app/components/channel_bookmarks/channel_bookmark/bookmark_icon.tsx
- app/components/files/file_icon.tsx
Emoji associated to bookmark is missing. This is due to emoji name being stored as `:computer-rage:`.  The fix is to parse out the `:` from emoji name.
Fixes: https://mattermost.atlassian.net/browse/MM-60645
iPhone 16 Simulator (18.2)
```release-note
```
> fix(MM-60645): missing bookmark emoji

- app/screens/gallery/video_renderer/error.tsx
- app/screens/gallery/video_renderer/index.tsx
- app/screens/share_feedback/index.tsx
- app/utils/images/index.test.ts
- app/utils/images/index.ts
- Fixed resize image when Tablet screen is resized
- Fixed the share feedback screen layout
- Fixed the layout when there is an error with the playback of a video
https://mattermost.atlassian.net/browse/MM-62043
https://mattermost.atlassian.net/browse/MM-61951
https://mattermost.atlassian.net/browse/MM-62100
```release-note
Fixed resize image when Tablet screen is resized
Fixed the share feedback screen layout
Fixed the layout when there is an error with the playback of a video
```
> Fix broken windows

- app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
- app/components/channel_item/channel_item.tsx
- app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
Fixed the active label colour for channels and threads that have been unread. This is a regression from draft PR: https://github.com/mattermost/mattermost-mobile/pull/8280
https://mattermost.atlassian.net/browse/MM-62726
This PR was tested on: IOS 17.5
```release-note
NONE
```
> MM-62726 fix the active label color for channel and thread

- app/components/channel_item/__snapshots__/channel_item.test.tsx.snap
- app/components/channel_item/channel_item.tsx
- app/components/threads_button/__snapshots__/threads_button.test.tsx.snap
Cherry pick of #8523 on release-2.25.
/cc  @Rajat-Dabade
```release-note
NONE
```
> Automated cherry pick of #8523

- app/actions/remote/entry/common.test.ts
- app/actions/remote/entry/common.ts
Add tests for entry common functions.
https://mattermost.atlassian.net/browse/MM-59426
n/a
```release-note
NONE
```
> MM-59426 Add tests for entry common functions

- app/hooks/apps.test.tsx
- app/hooks/autocomplete.test.ts
- app/hooks/channel_switch.test.ts
- app/hooks/device.test.tsx
- app/hooks/device.ts
- app/hooks/did_update.test.tsx
- app/hooks/fetching_thread.test.ts
- app/hooks/freeze.test.ts
- app/hooks/handle_send_message.test.tsx
- app/hooks/handle_send_message.ts
- app/hooks/header.test.tsx
- app/hooks/input.test.ts
- app/hooks/navigate_back.test.ts
- app/hooks/navigation_button_pressed.test.ts
- app/hooks/persistent_notification_props.test.ts
- app/hooks/show_more.test.ts
- app/hooks/team_switch.test.ts
- app/hooks/teams_loading.test.ts
- app/hooks/why_did_you_update.test.ts
Add tests for remaining app/hooks files.
https://mattermost.atlassian.net/browse/MM-59741
https://mattermost.atlassian.net/browse/MM-59742
https://mattermost.atlassian.net/browse/MM-59743
https://mattermost.atlassian.net/browse/MM-59744
https://mattermost.atlassian.net/browse/MM-59745
https://mattermost.atlassian.net/browse/MM-59747
https://mattermost.atlassian.net/browse/MM-59749
https://mattermost.atlassian.net/browse/MM-59751
https://mattermost.atlassian.net/browse/MM-59752
https://mattermost.atlassian.net/browse/MM-59755
https://mattermost.atlassian.net/browse/MM-59756
https://mattermost.atlassian.net/browse/MM-59757
https://mattermost.atlassian.net/browse/MM-59758
https://mattermost.atlassian.net/browse/MM-59759
https://mattermost.atlassian.net/browse/MM-59760 …
> MM-59741 + others - Add tests for remaining app/hooks files

- app/client/rest/general.test.ts
There was a race between the expected URL `Date.now()` and the one in the ping function. Unfortunately this makes the test a little worse but it's not a critical test so it's probably fine.
n/a
n/a
```release-note
NONE
```
> Fix flaky client/rest/general/ping test

- app/queries/servers/preference.test.ts
Add tests for preference query functions.
https://mattermost.atlassian.net/browse/MM-59787
n/a
```release-note
NONE
```
> MM-59787 Add tests for preference query functions

- app/queries/servers/entry.test.ts
Add tests for entry query functions.
https://mattermost.atlassian.net/browse/MM-59782
n/a
```release-note
NONE
```
> MM-59782 Add entry query function tests

- app/i18n/index.test.ts
- app/i18n/index.ts
Add tests for i18n files.
https://mattermost.atlassian.net/browse/MM-59761
n/a
```release-note
NONE
```
> MM-59761 Add tests for i18n functionality

- app/actions/remote/channel.ts
- package-lock.json
With the changes made during the load bandwidth effort, we changed the API's being called to fetch the channels and channel memberships of the user. The idea was to fetch these memberships in parallel based on the channels we got, but the endpoint returns a paginated of up to 200 members per request we were coming short as the idea was to calculate the remaining requests to be executed based on the amount of channels that we got back. The channels endpoint returns a number of channels if we do exclude the deleted channels and that does not correlate with the members we fetch, so some members can be missing, so the app here "guesses" that the user is no longer a part of the channel.
To correct this, we are now requesting the memberships in serial, iterating over the pagination until the …
> fix: remove from channel

- app/database/operator/server_data_operator/handlers/post.test.ts
- app/database/operator/server_data_operator/handlers/post.ts
On https://github.com/mattermost/mattermost-mobile/pull/8468 , with the addition to edit file attachments on web, we added logic to remove the file attachments when the server said certain post no longer had one.
This surfaced an issue where the server is not sending the post metadata in all the relevant events. In particular, we pinpointed that the "Thread Updated" websocket event is not sending any metadata. The lack of metadata leads the code to think the files has been removed, and therefore removes from the local database.
To handle this in a backwards compatible manner, we check the `file_ids` field, instead of relying on the metadata. Nevertheless, we should consider fixing in the server the fact that we are not sending the metadata in all posts.
Fix …
> Check file id instead of metadata for file removal

- app/hooks/android_adjust_soft_keyboard/index.test.ts
- app/hooks/android_adjust_soft_keyboard/index.ts
- app/screens/channel/channel.tsx
- app/screens/thread/thread.tsx
For some reason when switching away from the app, the adjust nothing does not really work if the keyboard is previously opened, so this ensures the keyboard is closed before applying the adjust nothing to the activity.
https://mattermost.atlassian.net/browse/MM-62855
```release-note
Fixed certain scenarios where the keyboard area in the channel and thread screen takes more space than it should.
```
> Fix android keyboard area when switching apps

- app/actions/remote/apps.test.ts
- app/actions/remote/channel_bookmark.test.ts
- app/actions/remote/systems.test.ts
- app/actions/remote/terms_of_service.test.ts
Add tests for channel bookmarks, systems, apps and tos files in remote/actions.
https://mattermost.atlassian.net/browse/MM-59445
https://mattermost.atlassian.net/browse/MM-59435
https://mattermost.atlassian.net/browse/MM-59443
n/a
```release-note
NONE
```
> MM-59445 + others - Add tests for channel bookmarks, systems, apps and tos files in remote/actions

- app/screens/home/search/search.test.tsx
- app/screens/home/search/search.tsx
- ios/Gekidou/Package.resolved
To replicate the webapp behavior, changing team must reset from from:/in: filters.
I added a test for the search page, thanks to Aider, but I couldn't figure out how to test specifically what I changed, because it depends on `bottomsheet` and I couldn't make it work (i had to mock them).
https://mattermost.atlassian.net/browse/MM-62898
This PR was tested on: ios and android simulator
Playthrough:
- select a modifier `from: [user]`.
- type "error" or any text that'll provide a result
- confirm the search worked to get to the result page.
- change team
- notice the filter has been removed.
https://github.com/user-attachments/assets/175e6186-9eac-46da-95b4-6ba28d4fe019
```release-note
NONE
```
> [MM-62898] Reset filter when changing team

- android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
- android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java
- app/screens/home/recent_mentions/recent_mentions.tsx
- app/screens/home/saved_messages/saved_messages.tsx
- app/screens/home/search/search.tsx
- ios/Podfile.lock
- package-lock.json
- package.json
Fixes push notification fetching data and replying to the notification on android
Fixes the UI when switching between tabs on the home screen
https://mattermost.atlassian.net/browse/MM-62943
```release-note
NONE
```
> 2.25 fixes

- .github/actions/prepare-node-deps/action.yaml
- android/settings.gradle
- ios/Podfile.lock
- package-lock.json
- package.json
- patches/expo-image+2.0.4.patch
- scripts/postinstall.sh
Fixes: https://mattermost.atlassian.net/browse/MM-62375
See changes in my own fork of APNG4Android (until I have permission to post to mattermost/APNG4Android): https://github.com/rahimrahman/APNG4Android/commit/74dd31cf4363b012c7d81fb8356f85d96d29ff24
Google Pixel 6a, Android 14
```release-note
```
> fix(MM-62375): OOM on gif

- app/actions/local/scheduled_post.ts
- app/actions/remote/scheduled_post.test.ts
- app/actions/remote/scheduled_post.ts
- app/actions/websocket/scheduled_post.test.ts
- app/actions/websocket/scheduled_post.ts
Adds websocket handling for scheduled post events
Fixes https://mattermost.atlassian.net/browse/MM-63111
ios emulator
```release-note
None
```
> Websocket extension

- app/actions/remote/user.test.ts
- app/actions/remote/user.ts
- app/client/rest/base.ts
- app/client/rest/custom_profile_attributes.test.ts
- app/client/rest/custom_profile_attributes.ts
- app/components/floating_text_input_label/index.tsx
- app/hooks/field_refs.test.ts
- app/hooks/field_refs.ts
- app/screens/edit_profile/components/email_field.tsx
- app/screens/edit_profile/components/field.tsx
- app/screens/edit_profile/components/form.test.tsx
- app/screens/edit_profile/components/form.tsx
- app/screens/edit_profile/edit_profile.tsx
- app/screens/edit_profile/index.ts
- types/screens/edit_profile.ts
Add custom profile attributes to user profile and be able to edit them.
[MM-62701](https://mattermost.atlassian.net/browse/MM-62701)
[MM-62176](https://mattermost.atlassian.net/browse/MM-62176)
This PR was tested on: iOS emulator iPhone and iPad, Pixel 8
```release-note
Add custom profile attributes to the edit profile screen
```
[MM-62701]: https://mattermost.atlassian.net/browse/MM-62701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MM-62176]: https://mattermost.atlassian.net/browse/MM-62176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-62701] [MM-62176]Edit custom profile attributes in user profile

- fastlane/Gemfile
- fastlane/Gemfile.lock
- Pin version of nokogiri (and bump from `1.16.7` to `1.16.8`)
NA
NA
NA
NA
```release-note
NONE
```
> Pin and bump nokogiri

- package-lock.json
When we bump versions, all the needed files get their version updated but the package lock. This should be automated, but in the meanwhile we do it manually.
NONE
```release-note
NONE
```
> Bump package-lock.json version to 2.26

- app/actions/remote/user.test.ts
- app/actions/remote/user.ts
- app/client/rest/custom_profile_attributes.ts
- app/screens/edit_profile/components/form.test.tsx
- app/screens/edit_profile/components/form.tsx
- app/screens/user_profile/custom_attributes.tsx
- app/screens/user_profile/user_info.test.tsx
- app/screens/user_profile/user_info.tsx
- app/utils/user/index.ts
- types/api/custom_profile_attributes.d.ts
- types/api/users.d.ts
- types/screens/edit_profile.ts
Add ordering to the profile attributes.
While at it, reunite types/calls and do a bit of clean up from the last two CPA PRs
[MM-62666](https://mattermost.atlassian.net/browse/MM-62666)
This PR was tested on: ios simulator, android pixel 8
no UI changes, as this is just ordering the fields
```release-note
NONE
```
[MM-62666]: https://mattermost.atlassian.net/browse/MM-62666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-62666] Cpa sort order

- app/database/manager/__mocks__/index.ts
- app/database/manager/index.ts
- app/init/managed_app.ts
- app/init/push_notifications.ts
- app/managers/apps_manager.test.ts
- app/managers/apps_manager.ts
- app/managers/draft_upload_manager/index.test.ts
- app/managers/draft_upload_manager/index.ts
- app/managers/global_event_handler.ts
- app/managers/integrations_manager.ts
- app/managers/network_manager.ts
- app/managers/performance_metrics_manager/index.test.ts
- app/managers/performance_metrics_manager/index.ts
- app/managers/session_manager.test.ts
- app/managers/session_manager.ts
- app/managers/websocket_manager.ts
- app/store/ephemeral_store.ts
- app/store/navigation_store.ts
- app/utils/error_handling.ts
- test/test_helper.ts
The singletons we use, when we try to import them, the IDE automatically set the file name, instead of the name of the class (e.g. `test_helper` vs. `TestHelper`.
This is due to the variable returned in the default not having a name. This is solved by changing the name of the class, and storing the new object in a constant before exporting it.
NONE
```release-note
NONE
```
> Enforce names for singleton imports

- app/components/post_draft/read_only/index.tsx
When a channel is read only, the arrow indicator that there are more messages to read below was showing on top of the read only channel element (broken window) when in fact it should be hidden
TBD
| Before | After |
| :-----: | :----: |
| ![image](https://github.com/user-attachments/assets/669c927c-b45b-47bf-bd39-cb99383d604b) | ![image](https://github.com/user-attachments/assets/e84adb51-db75-49e0-9af7-4c87f295ee5e) |
```release-note
NONE
```
> Fix more messages indicator on read only channels

- app/constants/screens.ts
- app/context/extra_keyboard/index.tsx
- app/hooks/device.ts
- app/screens/interactive_dialog/index.tsx
- libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/RNUtilsModuleImpl.kt
- patches/react-native-keyboard-aware-scroll-view+0.9.5.patch
This PR Addresses two things:
On one hand in the interactive dialog was blocking other elements of the dialog without being able to scroll til the end, on the other hand, Android 10 and below has a problem setting the windowSoftInputMode as `adjustNothing` as it does not trigger the events for keyboardDidShow and keyboardDidHide, so the keyboard was blocking the text field.
Fixes: #8514 
https://mattermost.atlassian.net/browse/MM-62896
```release-note
Fixes an issue where the keyboard blocks the text input
```
> MM-62896 Keyboard blocks input

- app/components/post_draft/post_draft.tsx
- app/screens/navigation.ts
This PR removes (for now) the use of ExtraKeyboard on Android.
The reason for this is that:
1. We are not really using that area for other components at the moment.
2. React Native does not report keyboardDidShow and KeyboardDidHide on Android 10 and below if the `windowSoftInputMode` is set as `adjustNothing`
3. [useAnimatedKeyboard](https://docs.swmansion.com/react-native-reanimated/docs/device/useAnimatedKeyboard) modifies the Android screen and had an issue where it did not update the values in certain scenarios like when switching from one channel to another keeping the same screen (ex: tap on a channel link) while the keyboard was opened.
https://mattermost.atlassian.net/browse/MM-62855
```release-note
Fixes a blank space between the content an the keyboard on Android
```
> Do not use extra keyboard on Android

- android/app/build.gradle
- app/actions/remote/custom_emoji.test.ts
- app/actions/remote/custom_emoji.ts
- app/components/emoji/emoji.tsx
- app/constants/emoji.ts
- app/screens/emoji_picker/picker/filtered/emoji_item.tsx
- app/screens/emoji_picker/picker/filtered/filtered.tsx
- app/screens/emoji_picker/picker/footer/index.tsx
- app/screens/emoji_picker/picker/sections/emoji_image.tsx
- app/screens/emoji_picker/picker/sections/emoji_row.tsx
- app/screens/emoji_picker/picker/sections/index.tsx
- app/screens/emoji_picker/picker/sections/section_header.tsx
- app/utils/emoji/prefetch.test.ts
- app/utils/emoji/prefetch.ts
- ios/Podfile.lock
- package-lock.json
- package.json
- patches/@shopify+flash-list+1.7.3.patch
- types/screens/emoji_selector.d.ts
As I was working on https://github.com/mattermost/mattermost-mobile/pull/8645 I noticed that from time to time the emoji picker was not being protected against screenshots on iOS this due to the time it took to render the screen as the protection did not find the right view when added. Aside from that on Android, specially when searching for emojis, after a few custom emojis loaded it always ended crashing the app.
So in the end, I've changed SectionList to FlashList as it helps improve the first time to render (no benchmarks on my end only that with it, the references PR always finds the view to protect, always)
Although the above helped with time to interaction and first time to render, on Android the crash remained, so I ended up moving back to the react-native Image component that is …
> Improve emoji picker performance introducing flashList

- app/screens/settings/notification_mention/mention_settings.tsx
Add KeyboardAwareScrollView to Settings -> Notifications -> Mentions to avoid the keyboard from blocking the text input if the input grows when there are many keywords listed.
https://mattermost.atlassian.net/browse/MM-63395
This PR was tested on: Android & iOS
```release-note
NONE
```
> fix keyboard blocking input on mentions notifications settings

- app/hooks/use_external_link.test.ts
- app/hooks/use_external_link.ts
On https://github.com/mattermost/mattermost/pull/30444 we found a couple of problems with the `useExternalLink` hook.
This PR fixes those problems on the mobile code too.
NONE
```release-note
NONE
```
> Update useExternalLink to match webapp

- app/components/post_list/post/body/message/message.tsx
- app/context/theme/index.tsx
- app/screens/settings/display_theme/display_theme.tsx
At times rendering a markdown table was causing a jump display on loop and this was due to a few things
1. The message component, that renders the markdown updates the state on layout to determine if the component should be displayed as a long message, this was being triggered multiple times, so the first fix is to set the height only if needed.
2. The reason the onLayout was firing multiple times was because the theme even though is the same, it was being updated multiple times as the provider uses JSON.parse which returns a new object every time, so the fix here was to create a memory cache of the themes so that is always the same object until it changes.
3. Additionally, when switching themes, we were updating it more than once, when changing which is correct but also when loading the …
> Avoid unnecessary re-renders

- ios/Podfile.lock
- package-lock.json
- package.json
Cherry pick of #8681 on release-2.27.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #8681

- app/actions/local/scheduled_post.test.ts
- app/actions/local/scheduled_post.ts
- app/components/draft_scheduled_post/draft_scheduled_post.tsx
- app/database/operator/server_data_operator/handlers/post.test.ts
- app/database/operator/server_data_operator/handlers/post.ts
- app/database/operator/server_data_operator/transformers/post.ts
- app/queries/servers/scheduled_post.ts
- app/screens/draft_scheduled_post_options/send_draft.test.tsx
- app/screens/draft_scheduled_post_options/send_draft.tsx
- app/screens/global_drafts/components/tabbed_contents/tabbed_contents.tsx
- app/utils/scheduled_post/index.ts
- app/utils/scheduled_post/scheduled_post.test.ts
- assets/base/i18n/en.json
- types/database/database.ts
This PR handles two API calls when sending a scheduled post: first, creating the post, and then deleting the scheduled post. The issue arises when the post is successfully created, but the scheduled post deletion fails. To address this, we now update the local database with an error code and notify the user via an alert, prompting them to manually delete the scheduled post, since the message has already been sent to the appropriate channel or thread.
```release-note
NONE
```
> Handling 2 API for scheduled post (createPost and deleteScheduledPost)

- app/actions/remote/thread.ts
- app/utils/thread/index.ts
This improve the handling of threads, to fix an issue where read threads were not marked as such.
The fixes are the following:
- Set the correct direction so the pagination is done as it should
- Remove the limit of pages, since we want to get all the changes since the last time we synced.
- Take into account the `last_viewed_at` for calculations on "which one is the latest thread I have".
Fix https://mattermost.atlassian.net/browse/MM-63211
```release-note
Fix some threads not getting marked as read when read from a different device.
```
> Better handle threads sync

- ios/ErrorReporting/Sentry.swift
2 months ago, when upgrading React-Native 0.76.5 (see [PR](https://github.com/mattermost/mattermost-mobile/pull/8421)), there's [a change in Sentry.swift](https://github.com/mattermost/mattermost-mobile/commit/2f3dfbbbfab3e9bfb70531e0023b471d57e1f0ac#diff-f7cade0586eaa6a2c6f7dff56e6e710808944652e836efb13481e1f77d0721e8R18-R19) which change the boolean value of `enableCaptureFailedRequests` from `false` to `true`.  Since then, we've been logging all failed request errors which caused MM Sentry account to go over the limit.  This PR reverts that one change.
More information about enableCaptureFailedRequests and HTTPClientError can be found here: https://docs.sentry.io/platforms/apple/guides/ios/configuration/http-client-errors/
It is enabled by default, and we had it turned off.  But 2 …
> fix(MM-63460): HTTPClientError spam

- app/components/post_draft/post_draft.tsx
- app/hooks/autocomplete.ts
Seem that useKeyboardHeight is already deducting the keyboard height on Android, so by substracting it again we are leaving a very small area for the content.
[MM-63481](https://mattermost.atlassian.net/browse/MM-63481)
This PR was tested on: ios Simulator, Pixel 8, Xiaomi 8
| Before  | After |
| ------------- | ------------- |
| ![rn_image_picker_lib_temp_13133391-2704-4d08-802e-988ea0b4803b (1)](https://github.com/user-attachments/assets/d01d8164-fd20-4a9f-b97a-d11a1d03d975) | ![rn_image_picker_lib_temp_d0257bdd-67c9-4d09-8317-ba613c246058](https://github.com/user-attachments/assets/e7675072-0304-4f5f-ad39-5ab7ca27e0fc) |
```release-note
fix autocomplete area being too small on android devices
```
[MM-63481]: https://mattermost.atlassian.net/browse/MM-63481?atlOrigin=eyJpIjoiNWRkNTljNzYx …
> [MM-63481] Don't substract keyboard height in Android as it was already substracted

- app/screens/edit_profile/edit_profile.test.tsx
- app/screens/edit_profile/edit_profile.tsx
Order wasn't maintained when editing a field (deletion or modification)
[MM-62176](https://mattermost.atlassian.net/browse/MM-62176)
This PR was tested on: ios Simulator, Pixel 8, Xiaomi 8
```release-note
fix fields being reordered after editing
```
[MM-62176]: https://mattermost.atlassian.net/browse/MM-62176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-62176] fix ordering after edit

- package-lock.json
- package.json
Updates the mobile app with the latest (forked) commonmark dependency from https://github.com/mattermost/commonmark.js/pull/22. (Note the commit is temporary, to be replaced with a tagged version once merged.)
Fixes: https://mattermost.atlassian.net/browse/MM-63537
- ~~[ ] Added or updated unit tests (required for all new features)~~
- ~~[ ] Has UI changes~~
- ~~[ ] Includes text changes and localization file updates~~
- ~~[ ] Have tested against the 5 core themes to ensure consistency between them.~~
This PR was tested on: iOS Simulator (iPhone 16 Pro, iOS 18.2)
N/A
```release-note
Upgrade forked commonmark to 0.31.2-0
```
> upgrade to @mattermost/commonmark@0.31.2-0

- app/actions/local/draft.test.ts
- app/actions/local/draft.ts
- app/screens/global_drafts/components/tabbed_contents/draftTabsHeader.tsx
- app/screens/global_drafts/components/tabbed_contents/tabbed_contents.test.tsx
- app/screens/global_drafts/components/tabbed_contents/tabbed_contents.tsx
- app/screens/navigation.ts
Issue: When clicking "See All" from the scheduled post indicator in the channel, it navigates to the draft screen with the Scheduled Posts tab selected — but the tab appears empty. Also, when you tap the back button, it takes you to an empty channel screen.
https://mattermost.atlassian.net/browse/MM-63634
```release-note
```
> Fix the issue when click on see all tab in from channel takes to the empty scheduled post screen. 

- package-lock.json
TDLR:
- Remove unused `rnshield` dependency
Full description:
While working on SBOM things I realized the dependency was called out in `package-lock.json` but not the SBOM, so then I did some investigation and realized it's because it's not used at all.
If you delete `node_modules/` and `package-lock.json` and regenerate it, the dependency gets removed, but I didn't want to make a bunch of other changes so I just opted to remove the one unused dependency. 
NA
```release-note
NONE
```
> Remove unused rnshield dependency

- android/app/build.gradle
- fastlane/Fastfile
This fixes the deployment of beta app and release app to the play store by not including the Universal APK.
The universal APK is no longer included in the Github release.
The reason for this is that the ABI's that we currently build cover all the supported devices at this point in time.
N/A
```release-note
NONE
```
> Explicitly build the universal apk

- app/screens/create_direct_message/create_direct_message.tsx
- detox/e2e/test/channels/create_direct_message.e2e.ts
The create direct message screen was showing deactivated accounts in the user list, which was confusing for users. This PR fixes the issue by properly filtering out deactivated users.
Fixes https://mattermost.atlassian.net/browse/MM-63374
This PR was tested on: iOS simulator
N/A
```release-note
Fixed an issue where deactivated accounts would appear in the create direct message screen.
```
> Fix direct message screen showing deactivated accounts

- app/products/calls/client/rest.ts
- app/products/calls/connection/connection.test.ts
- app/products/calls/connection/connection.ts
- app/products/calls/types/calls.ts
- app/products/calls/utils.ts
- package-lock.json
- package.json
PR addresses a forward compatibility issue triggered by running some new logic we added in https://github.com/mattermost/mattermost-mobile/pull/8745 against an older backend (either Calls plugin or RTCD service, depending on which one was configured).
A test plan for both backward and forward compatibility is attached to the JIRA ticket.
Fixes https://github.com/mattermost/mattermost-plugin-calls/issues/1010
https://github.com/mattermost/mattermost-plugin-calls/pull/1011
https://github.com/mattermost/calls-common/pull/52
https://mattermost.atlassian.net/browse/MM-63889
```release-note
Calls: fixed a regression that caused unmuting to fail when running the latest app against an older plugin version (earlier than v1.7.0).
```
> [MM-63889] Calls: Add backend version check to enable DC locking

- app/products/calls/client/rest.ts
- app/products/calls/connection/connection.test.ts
- app/products/calls/connection/connection.ts
- app/products/calls/types/calls.ts
- app/products/calls/utils.ts
- package-lock.json
- package.json
Cherry-pick of https://github.com/mattermost/mattermost-mobile/pull/8799 to `release-2.27` branch.
https://mattermost.atlassian.net/browse/MM-63889
```release-note
Calls: fixed a regression that caused unmuting to fail when running the latest app against an older plugin version (earlier than v1.7.0).
```
> [MM-63889] Cherry-pick to `release-2.27`

- app/actions/remote/scheduled_post.test.ts
- app/actions/remote/scheduled_post.ts
- app/components/post_draft/draft_input/draft_input.tsx
- app/components/post_draft/draft_input/index.ts
- app/components/post_draft/send_button/index.tsx
- app/components/post_draft/send_button/send_button.test.tsx
- app/components/post_draft/send_button/send_button.tsx
- app/queries/servers/scheduled_post.ts
- app/screens/global_drafts/index.ts
- app/screens/home/channel_list/categories_list/index.tsx
I added a check to verify if a valid license exists before showing the scheduled post tooltip on the send draft button when opening a channel for the first time.
https://mattermost.atlassian.net/browse/MM-63841
```release-note
NONE
```
Regarding test: We already have ticket for this: https://mattermost.atlassian.net/browse/MM-62286, will cover in it.
> Unlicensed server should not show the tooltip on channel send button

- app/screens/reschedule_draft/reschedule_draft.tsx
I removed the unnecessary `setIsUpdating(false)` call from the `reschedule_draft` component.
When saving the updated date and time for a scheduled post, we were calling `setIsUpdating(false)` even after a successful update. This triggered a re-render of the component, which caused the DateTimePicker (calendar) to flash briefly after the modal was closed.
We don't actually need to reset `isUpdating` after a successful update because the `onClose` function dismisses the modal, and when the modal is reopened, everything is already reset to the initial state.
Now, we only update `isUpdating` if there's an error during the save.
https://mattermost.atlassian.net/browse/MM-63750
https://github.com/user-attachments/assets/e8a8f3ee-3288-4d73-a784-0dddcfb67faa …
> Android: Fix Rescheduling pop back calendar

- app/products/calls/components/current_call_bar/current_call_bar.tsx
PR fixes a UX issue with how we render the call bar in case of long user/channel names. The fix is pretty simple and I opted to use `ellipsizeMode=middle` since we want to retain the end of the two lines ("is talking..." and the call duration respectively).
Unfortunately, doing something fancier (e.g. wrapping on multi lines) is either fairly complex or not well supported. (see https://reactnative.dev/docs/text#ellipsizemode for details). 
I think this is a good enough compromise.
https://mattermost.atlassian.net/browse/MM-63382
Tested on Google Pixel 7 Pro (Android 13)
*Before*
*After*
```release-note
Fixed a UX issue where the call bar did not render correctly when displaying exceptionally long user or channel names.
```
> [MM-63382] Calls: Fix rendering of long user/channel name in call bar

- app/constants/license.ts
- app/screens/channel/channel_feature_checks.test.tsx
- app/screens/channel/channel_feature_checks.ts
- app/screens/channel/header/channel_banner/channel_banner.test.tsx
Renamed Premium SKU to `Enterprise Advanced`.
Server PR - https://github.com/mattermost/mattermost/pull/30882
Fixes https://mattermost.atlassian.net/browse/MM-63928
```release-note
None
```
> Renamed premium SKU to Enterprise Advanced

- patches/react-native-navigation+7.45.0.patch
During the dependency upgrade, we removed one line in the patch for react native navigation that was overriding the default behavior of the back button. Removing this line made it so the default behavior (in general close the app) translated into doing nothing.
Reverting that small change in the patch seems to do the trick.
FIX https://mattermost.atlassian.net/browse/MM-63921
```release-note
Fix back button not closing the app
```
> Fix back button not closing the app

- app/context/extra_keyboard/index.tsx
With the new ExtraKeyboard logic, we were not considering the hardware keyboard. Removing the check makes it so we consider it.
https://mattermost.atlassian.net/browse/MM-62874
```release-note
Fix hardware keyboard on iPad overlapping the input in threads
```
> [MM-62874] Fix iPad hw keyboard overlapping input

- app/screens/latex/index.tsx
- app/screens/latex/latex.test.tsx
Latex code blocks didn't have error boundaries, which caused a crash on malformed latex.
FIX https://mattermost.atlassian.net/browse/MM-63817
```release-note
Fix issue where the app may crash when viewing malformed latex code
```
> Add error boundary to latex code

- app/database/operator/server_data_operator/transformers/category.ts
By default, we were settings the categories to sort order `recent` on mobile. The default should have been the empty string, which defaults to alphabetical order. That fixes the inconsistencies with web.
The data in the database is already "wrong", so in order to fix it, we would need to log out and log back in.
Fix https://mattermost.atlassian.net/browse/MM-54396
```release-note
Fix inconsistencies between web and mobile category sorting. (May require logging out and log back in to fix)
```
> Fix category sorting difference between mobile and web

- package-lock.json
- package.json
Updates prismjs to address CVE-2024-53382. No version of `react-syntax-highlighter` and `refactor` had the non-vulnerable version so we had to install prismjs as a direct dependency and then override the version for  `react-syntax-highlighter` and `refactor` 
N/A
N/A
N/A
```release-note
NONE
```
> Update transitive dependency prismjs

- app/actions/remote/notifications.test.ts
- app/actions/remote/notifications.ts
- After a long couple days of debugging and log setting, I discovered the issue: we were validating message attachments, and at this point: https://github.com/mattermost/mattermost-mobile/blob/5c2153f83b14d44e8f1b51b6a6ce1e079fa46c1d/app/utils/message_attachment.ts#L98-L100
we were failing the validation because (in the customer's example post), we were sending `"short": true` but it was ending up as `"short": 1` at this point, thus failing the validation.
- I was about to push a fix that changed the validation, but that didn't feel right. /Why/ was `short` being converted to a 1? - It turns out, `NSJSONSerialization` was serializing data's bools as 1 and 0 here: https://github.com/mattermost/mattermost-mobile/blob/58830b5acb26388a4f042d56ccb799651f414b6d/ios/Mattermost/AppDelegate.mm#L116 …
> [MM-63553] Fix for: messages received on the background on iOS lose the props

- app/components/markdown/markdown_link/markdown_link.tsx
- app/screens/channel_info/extra/extra.tsx
- assets/base/i18n/en.json
This pull request improves the UX of copying links by detecting whether a copied value is an email address or a regular URL. If the link is an email (e.g., `mailto:example@example.com`), the copy action will now:
- Strip the `mailto:` prefix before copying.
- Show the bottom sheet option as “Copy Email Address” instead of “Copy URL” as requested [here](https://github.com/mattermost/mattermost/issues/29525).
Fixes https://github.com/mattermost/mattermost/issues/29525 (https://mattermost.atlassian.net/browse/MM-61995)
This PR was tested on: iPhone 16 Pro, iOS 18.4
```release-note
Updated the copy action label to “Copy Email Address” for Markdown-rendered email links.
```
> [MM-61995] Correct copying instructions when long-pressing an email in messages & headers

- types/api/channels.d.ts
as part of https://github.com/mattermost/mattermost-mobile/pull/8860 a value was missing from the types api model. This PR adds that type and fixes the TSC errors in main.
N/A
```release-note
NONE
```
> MM-63935- abac end user indicators db fix

- app/actions/websocket/posts.test.ts
- app/actions/websocket/posts.ts
Updated epehemeral posts didn't provide a create at, making it to 0. Our logic, on update, update any field provided by the server (the server has the source of truth), and therefore was setting the create at to 0. This made so the chunk logic for messages hide the ephemeral message.
The fix just make sure that when the create at is 0, we don't update it.
https://mattermost.atlassian.net/browse/MM-58461
```release-note
Fix actions on ephemeral messages hiding the message.
```
> Fix ephemeral messages disappearing when updating them

- app/components/markdown/markdown_image/index.tsx
- app/components/markdown/markdown_table_image/index.tsx
- app/utils/markdown/index.test.ts
- app/utils/markdown/index.ts
For markdown Images, if there is a presence of an image proxy, the key did not match the url in the metadata.
N/A
```release-note
NONE
```
> use the actual url in the metadata if there is an image proxy being used

- app/screens/home/search/bottom_sheet_team_list.tsx
- app/screens/home/search/team_picker.tsx
On a two team setup, the second team was unreachable. To fix it, I simplified the logic to display.
Note: cutting in half the third team was intentional to prompt the user to scroll
[MM-64354](https://mattermost.atlassian.net/issues/MM-64354)
This PR was tested on: Android 8
| 3+ Teams | 2 Teams |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/d0d4dbf1-36a1-4250-a2c2-033e1cd2a139) | ![image](https://github.com/user-attachments/assets/45a2f4a0-5d33-482e-bd28-75ad7726b1d8) |
```release-note
Fixed being unable to reach the second team on team selection in the search screen.
```
[MM-64354]: https://mattermost.atlassian.net/browse/MM-64354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-64354] Simplify snappoints based on team numbers

- app/constants/tooltip.ts
One of the detox tests was failing because the JS thread was busy. I tracked this down to the tooltip on the drafts/scheduled messages screen.
We were passing the width to the styles, which mess up with the width calculation done in the library. This ended up the library getting into an infinite loop measuring the child and trying to adjust the width.
It is fixed by setting a maxWidth instead of a hardcoded width.
There was almost no visual cue but a small flickering on the width of the component.
NONE
```release-note
Fix some flickering on the tooltip in the drafts screen.
```
> Fix scheduled messages tooltip entering an infinite resize loop

- app/database/operator/server_data_operator/handlers/index.test.ts
- app/database/operator/server_data_operator/handlers/index.ts
This PR fixes the issue of not updating the custom emojis image when they are updated on the web application but didn't change it's name.
For example, if the user creates a custom emoji named `test` and then renders it on Mobile, after that the user goes and deletes this custom emoji and creates another one with the same name `test`, the image was not being updated on Mobile, it would keep using the image of the first one created, this PR fixes that.
When the custom emojis are to be updated on the WatermelonDB, I just fetch for emojis with the same name as the ones to be created on the DB, and if it finds it, I delete this ones so it can be created again with a new id, since we use this property to render the images.
https://github.com/mattermost/mattermost/issues/30711
This PR was tested …
> Custom Emojis not updating on application

- app/database/operator/server_data_operator/handlers/category.test.ts
- app/database/operator/server_data_operator/handlers/category.ts
Category Channels are being updated every time the app starts.  This caused unnecessary strain on the device's resources.  This PR adds a check to ensure that it only creates an array of raw data when there are changes.
A sample of 1 of the category channels model:
```
"__original": {"_changed": "", "_status": "created", "category_id": "channels_nujm848e1t8s7rak8wbi3anwar_1fmcqbq1uigyunw3uon39cgg9r", "channel_id": "jcwpsc9bd7gxj8npen3qupqjsr", "id": "1fmcqbq1uigyunw3uon39cgg9r_jcwpsc9bd7gxj8npen3qupqjsr", "sort_order": 0}
"_raw": {"_changed": "", "_status": "created", "category_id": "channels_nujm848e1t8s7rak8wbi3anwar_1fmcqbq1uigyunw3uon39cgg9r", "channel_id": "jcwpsc9bd7gxj8npen3qupqjsr", "id": "1fmcqbq1uigyunw3uon39cgg9r_jcwpsc9bd7gxj8npen3qupqjsr", "sort_order": 0}
```
Nothing …
> feat(MM-64361): categoryChannels update ONLY when necessary

- app/actions/remote/performance.test.ts
- app/client/rest/constants.ts
- app/client/rest/tracking.ts
- app/managers/performance_metrics_manager/test_utils.ts
The objective of this PR is trying to solve an old issue with the application that misses `Accept` headers on requests, and this triggers some security issues on monitoring the application like `ModSecurity` for example.
The `Accept` header will only be added if the `doFetch` is called without it, if it's specified it will replace what the ClientTracking does.
Let's discuss the implementation.
https://github.com/mattermost/mattermost-mobile/issues/4760
Android API 33 and iOS 18.4
N/A
```release-note
Adds a default header to requests as `application/json`
```
> Add Accept Header on ClientTracking

- app/actions/local/thread.ts
- app/components/threads_button/index.ts
- app/database/subscription/unreads.ts
- app/queries/servers/team.test.ts
- app/queries/servers/team.ts
- app/queries/servers/thread.ts
- app/screens/global_threads/index.tsx
- app/screens/global_threads/threads_list/index.ts
- app/screens/home/channel_list/categories_list/categories/unreads/index.ts
While simplifying the logic around team unreads, a "default true" argument got the best of me, provoking that we include DM and GMs on the calculations for thread unreads.
This PR add relevant tests and fix the issue by passing the correct argument.
https://mattermost.atlassian.net/browse/MM-64335
```release-note
Fix issue where a unread thread on a dm/gm would mark all teams as unread.
```
> Fix GM/DM unread threads highlighting all teams as unreads

- app/actions/remote/custom_profile.test.ts
- app/actions/remote/custom_profile.ts
- app/actions/remote/user.test.ts
- app/actions/remote/user.ts
- app/components/autocomplete_selector/index.tsx
- app/database/models/server/custom_profile_field.ts
- app/screens/edit_profile/components/form.test.tsx
- app/screens/edit_profile/components/form.tsx
- app/screens/edit_profile/components/select_field.test.tsx
- app/screens/edit_profile/components/select_field.tsx
- app/screens/edit_profile/edit_profile.test.tsx
- app/screens/edit_profile/edit_profile.tsx
- app/screens/edit_profile/index.ts
- app/screens/integration_selector/integration_selector.tsx
- app/screens/user_profile/custom_attributes.test.tsx
- app/screens/user_profile/custom_attributes.tsx
- app/screens/user_profile/index.ts
- app/screens/user_profile/label.test.tsx
- app/screens/user_profile/label.tsx
- app/screens/user_profile/label_link.test.tsx
- app/screens/user_profile/label_link.tsx
- app/screens/user_profile/user_info.test.tsx
- app/screens/user_profile/user_info.tsx
- app/utils/user/index.test.ts
- app/utils/user/index.ts
- assets/base/i18n/en.json
- types/api/custom_profile_attributes.d.ts
- types/database/models/servers/custom_profile_field.ts
- types/screens/edit_profile.ts
Add types on top of User Attributes
Also fixed 
- how search looked in autocomplete
- bug that UA was handled differently depending on wether it was loaded from DB or fetched from the server. Now everything updates from the DB
[MM-62700](https://mattermost.atlassian.net/browse/MM-62700)
This PR was tested on: Pixel 8, iOS Simulator
| Header | Header |
|--------|--------|
| user profile | <img src="https://github.com/user-attachments/assets/75c14167-c54f-4647-8436-910f65c31a8f" height="400"> |
| edit profile | <img src="https://github.com/user-attachments/assets/d0bfe177-9785-401a-9172-b8b7596be14f" height="400"> |
| edit select | <img src="https://github.com/user-attachments/assets/cc8dff7e-2920-48fa-a8f1-c4ef4c8520a6" height="400">  |
| edit multi | <img …
> [MM-62700] User Attribute types

- app/actions/local/thread.ts
- app/components/threads_button/index.ts
- app/database/subscription/unreads.ts
- app/queries/servers/team.test.ts
- app/queries/servers/team.ts
- app/queries/servers/thread.ts
- app/screens/global_threads/threads_list/index.ts
- app/screens/home/channel_list/categories_list/categories/unreads/index.ts
* Fix GM/DM unread threads highlighting all teams as unreads
* Use options object instead of boolean flags
```release-note
Fix GM/DM unread threads highlighting all teasm as unreads.
```
> MANUAL CHERRYPICK: Fix GM/DM unread threads highlighting all teams as unreads (#8905)

- app/actions/local/channel.test.ts
- app/actions/local/channel.ts
- app/actions/remote/post.ts
- app/actions/websocket/posts.test.ts
- app/actions/websocket/posts.ts
- app/components/channel_item/channel_item.tsx
- app/components/channel_item/index.ts
On the webapp, messages that have the urgent priority set and have mentions show as red. This is not the case on mobile. 
Before 
After:
https://mattermost.atlassian.net/browse/MM-62038
```release-note
Urgent mentions get a properly coloured mention badge
```
> Urgent mentions do not get the properly coloured mention badge

- .github/workflows/github-release.yml
- Fix commit hash for download-artifact (https://github.com/actions/download-artifact/releases/tag/v4.3.0)
```release-note
NONE
```
> Fix commit hashes for download artifacts

- app/screens/edit_profile/components/form.test.tsx
- app/screens/edit_profile/components/form.tsx
- app/screens/edit_profile/edit_profile.test.tsx
- app/screens/edit_profile/edit_profile.tsx
- app/utils/user/index.ts
- types/api/custom_profile_attributes.d.ts
Previously it was saving everythin wether it changed or not, this caused some issues when something in the profile is linked via saml
https://mattermost.atlassian.net/issues/MM-64358
This PR was tested on: iPhone 13 pro using Hub
```release-note
fix error when saving non-editable custom profile attributes
```
> [MM-64358] don't save unneeded custom profile attributes

- app/components/post_draft/uploads/index.test.tsx
- app/components/post_draft/uploads/index.tsx
- app/components/post_draft/uploads/upload_item/index.test.tsx
- app/components/post_draft/uploads/upload_item/index.tsx
- app/components/post_draft/uploads/upload_item/upload_remove.tsx
- app/components/post_draft/uploads/upload_item/upload_retry.tsx
- app/screens/edit_post/edit_post.test.tsx
- app/screens/edit_post/edit_post.tsx
- app/screens/edit_post/edit_post_input/edit_post_input.test.tsx
- app/screens/edit_post/edit_post_input/edit_post_input.tsx
- app/screens/edit_post/post_error/index.tsx
Updated style for showing the attachments in the draft and Edit post screen. 
https://mattermost.atlassian.net/browse/MM-64415
```release-note
NONE
```
> MM-64415 Attachment style updated for draft and Edit post screen

- app/components/autocomplete/autocomplete.tsx
- app/components/autocomplete/emoji_suggestion/emoji_suggestion.tsx
- app/components/post_draft/post_draft.tsx
- app/screens/create_or_edit_channel/channel_info_form.tsx
- app/screens/edit_post/edit_post.test.tsx
- app/screens/edit_post/edit_post.tsx
- app/screens/edit_post/index.test.tsx
- app/screens/edit_post/index.tsx
- app/screens/home/search/search.tsx
The issue was in the edit post functionality, where users editing a post with file attachments but no text would incorrectly see a delete confirmation dialog when clicking save, instead of being able to save the post with just the attachments. This happened because the code was checking whether the post originally had files attached rather than checking the current state of files in the post editor. The fix involved changing the logic to check the current file state instead of the original post state, ensuring that posts with attachments but no text will save normally, while truly empty posts with no text and no files will still appropriately trigger the delete confirmation dialog. This simple change resolved the user experience issue where legitimate posts containing only file …
> Edit mode when no text and no attachment on save calls delete post

- app/products/playbooks/actions/local/version.test.ts
- app/products/playbooks/actions/local/version.ts
We want to remove the playbooks information as soon as the user does not have access to it. To do so, we remove all the information the moment the we notice the plugin is not longer enabled.
Fix https://mattermost.atlassian.net/browse/MM-64803
```release-note
NONE
```
> Purge playbooks data when the plugin gets disabled

- app/actions/websocket/index.test.ts
- app/actions/websocket/index.ts
- app/managers/websocket_manager.test.ts
- app/managers/websocket_manager.ts
- app/products/playbooks/actions/remote/runs.test.ts
- app/products/playbooks/actions/remote/runs.ts
- app/products/playbooks/actions/websocket/reconnect.test.ts
- app/products/playbooks/actions/websocket/reconnect.ts
- app/products/playbooks/database/queries/version.test.ts
- app/products/playbooks/database/queries/version.ts
- app/screens/channel/header/header.test.tsx
- app/screens/channel/header/header.tsx
When we are already in a channel, and we lose connection, we need to re-fetch the playbooks for that channel, to be back in sync.
This PR handles that, and also does some refactoring so all actions needed during reconnect by playbooks are done in the same place.
Fix https://mattermost.atlassian.net/browse/MM-64802
```release-note
NONE
```
> Fetch playbooks when we reconnect and we are on a channel

- app/products/playbooks/screens/playbook_run/checklist/checklist.test.tsx
- app/products/playbooks/screens/playbook_run/checklist/checklist.tsx
- app/products/playbooks/screens/playbook_run/checklist/index.test.tsx
- app/products/playbooks/screens/playbook_run/checklist/index.ts
In the runs view, we were listening to the ordered items, and then calculating the progress from that. The problem was that when a item changes, the order doesn't change, so the `items` object stays the same.
Instead of that, we moved all the progress to a observer on the list of items (instead of the sorted items).
Fix https://mattermost.atlassian.net/browse/MM-64722
```release-note
NONE
```
> Fix progress numbers on playbook runs

- app/components/document/index.tsx
We want to display a specific alert when Secure File Mode Preview is enabled and the document is not a PDF.
N/A
```release-note
NONE
```
> use alertOnlyPDFSupported for document files

- app/utils/user/index.test.ts
- app/utils/user/index.ts
if sort_order is not present it is converted to MAX_INTEGER as a fail-safe mechanism. In a couple of places of the code this was not properly checked and it was converting 0 to MAX_INTEGER causing the wrong sorting.
[MM-64936](https://mattermost.atlassian.net/browse/MM-64936)
This PR was tested on: android and ios emulators
```release-note
Fix sorting problem when moving a field from CPA to the first position
```
[MM-64936]: https://mattermost.atlassian.net/browse/MM-64936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-64936] Fix sort_order 0 being converted to MAX_INTEGER

- app/products/playbooks/screens/playbook_run/checklist/checklist.tsx
On playbooks, a long checklist name was moving the "done" text out of the box, and didn't look "right". We added an ellipsis.
We still need to consider whether we want an ellipsis or we want to keep it multiline, so the whole name can be read.
Fix https://mattermost.atlassian.net/browse/MM-64764
```release-note
NONE
```
> Add ellipsis to the checklist title

- app/products/playbooks/actions/remote/runs.test.ts
- app/products/playbooks/actions/remote/runs.ts
Cherry pick of #9088 on release-2.32.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #9088

- app/screens/bottom_sheet/index.tsx
When implementing the bottom sheet for playbooks, I added some logic to the bottom sheet to make it automatically scrollable. While doing that, I added extra logic for tablets, but it seems I didn't test it because a previous "isTablet" check was shortcircuiting the logic.
I also added the "bottom sheet list fix" used in other places in the code. Not sure if needed, though.
Fix https://mattermost.atlassian.net/browse/MM-65739
```release-note
NONE
```
> Fix playbooks bottom sheet not scrolling on ipad

- ios/Mattermost/Extensions/RNNotificationEventHandler+HandleReplyAction.m
In some places, a "nil" value is not possible to pass. In those scenarios, on iOS they may use an object called NSNull to represent nil values.
Since it is an object, it will return true to the `!= nil` check, so we have to check directly for NSNull.
https://mattermost.atlassian.net/browse/MM-66069
```release-note
NONE
```
> Fix error on notification reply on iOS
