.circleci/config.yml
Cherry pick of #5427 on release-1.44.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5427

app/mattermost.js, app/telemetry/index.ts
=> fix start since launch metric

android/app/src/main/java/com/mattermost/share/RealPathUtil.java, patches/react-native-image-picker+2.3.4.patch
Cherry pick of #5432 on release-1.44.
/cc  @enahum
=> Automated cherry pick of #5432

app/screens/channel_info/index.js
Cherry pick of #5436 on release-1.44.
/cc  @manojmalik20
=> Automated cherry pick of #5436

app/components/post_list/post/body/reactions/reaction.tsx
Cherry pick of #5438 on release-1.44.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5438

app/components/network_indicator/network.tsx, app/components/post_list/post_list.tsx, app/mm-redux/actions/users.ts, app/screens/pinned_posts/pinned_posts.js, app/screens/recent_mentions/recent_mentions.js, app/screens/saved_posts/saved_posts.js
fixes get status as soon as appstate is in the foreground and re-render post list when theme changes
https://mattermost.atlassian.net/browse/MM-36360
https://mattermost.atlassian.net/browse/MM-36361
```release-note
NONE
```
=> 1.44 fixes

app/components/network_indicator/network.tsx, app/components/post_list/post_list.tsx, app/mm-redux/actions/users.ts, app/screens/pinned_posts/pinned_posts.js, app/screens/recent_mentions/recent_mentions.js, app/screens/saved_posts/saved_posts.js
Cherry pick of #5444 on release-1.44.
/cc  @enahum
=> Automated cherry pick of #5444

app/components/post_draft/post_draft.js, app/components/post_list/post_list.tsx, app/hooks/index.ts, app/hooks/reset_native_scrollview.ts, app/screens/channel/channel.ios.js, app/screens/channel/channel_base.js, app/screens/channel/channel_post_list/channel_post_list.js
Cherry pick of #5447 on release-1.44.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5447

app/components/network_indicator/network.tsx
Cherry pick of #5456 on release-1.44.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5456

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  359

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #5458 on release-1.44.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5458

app/components/post_draft/post_draft.js
https://mattermost.atlassian.net/browse/MM-36588
```release-note
Fixed iOS where the keyboard was covering the messages on the channel screen
```
=> MM-36588 iOS: rebind the correct post list to the native view

app/components/post_draft/post_draft.js
Cherry pick of #5472 on release-1.44.
/cc  @enahum
=> Automated cherry pick of #5472

app/actions/websocket/index.ts, app/components/custom_status/custom_status_emoji.tsx, app/components/post_list/post/header/header.tsx, detox/e2e/test/custom_statuses/custom_status.e2e.js
Cherry pick of #5476 on release-1.44.
/cc  @manojmalik20
=> Automated cherry pick of #5476

app/init/push_notifications.test.js, app/init/push_notifications.ts, app/screens/channel/channel_base.js, app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.js, app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.test.js
https://mattermost.atlassian.net/browse/MM-36628
```release-note
Fixed the badge count on the app icon for iOS
```
=> MM-36628 fix iOS app icon badge count

app/components/post_draft/uploads/upload_item/upload_item.js, package.json, patches/rn-fetch-blob+0.12.0.patch
This PR fixes the progress indicator for all files that are being uploaded simultaneously.
https://mattermost.atlassian.net/browse/MM-36623
```release-note
NONE
```
=> Fix upload progress indicator when uploading multiple files at once

app/init/push_notifications.test.js, app/init/push_notifications.ts, app/screens/channel/channel_base.js, app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.js, app/screens/channel/channel_nav_bar/main_sidebar_drawer_button/main_sidebar_drawer_button.test.js
Cherry pick of #5480 on release-1.44.
/cc  @enahum
=> Automated cherry pick of #5480

app/components/markdown/markdown_link/markdown_link.js
https://mattermost.atlassian.net/browse/MM-36532
```release-note
Fixed channel link navigation
```
=> MM-36532 navigate to channel from any screen when channel link is pressed

app/init/global_event_handler.js
Clear Cookies without having to delete the underlying files that store cookies.
```release-note
NONE
```
=> Clear cookies but keep files

app/components/post_list/post_list.tsx
Cherry pick of #5489 on release-1.44.
/cc  @enahum
=> Automated cherry pick of #5489

app/components/sidebars/main/channels_list/filtered_list/filtered_list.js, app/selectors/autocomplete.js
When searching for users show those that match ignoring the `@` sign.
https://mattermost.atlassian.net/browse/MM-17135
```release-note
Fixed at-sign is not ignore when searching for users
```
=> MM-17135 ignore at sign when searching for users

app/actions/navigation/index.js, app/actions/navigation/index.test.js
There is a bug in RNN so we need to handle the animation options a bit differently
https://mattermost.atlassian.net/browse/MM-36745
```release-note
Fixed an animation transition when displaying the options menu on iOS
```
=> MM-36745 Fix animation for showModalOverCurrentContext

app/mm-redux/constants/preferences.ts, app/selectors/emojis.js
Cherry pick of #5502 on release-1.45.
=> Automated cherry pick of #5502

app/actions/navigation/index.js, app/actions/navigation/index.test.js
Cherry pick of #5507 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5507

app/components/post_list/post/header/header.tsx, app/components/post_list/post/post.tsx
Fixes the auto responder post being rendered properly.
Note: I wasn't able to repro the "issue" when enabling the setting on the webapp was not being reflected on the mobile app.
https://mattermost.atlassian.net/browse/MM-36808
Fixes: #5513
```release-note
Fixed the render of auto responder posts
```
=> MM-36808 fix auto responder posts

app/components/post_list/post/header/header.tsx, app/components/post_list/post/post.tsx
Cherry pick of #5505 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5505

app/init/global_event_handler.js
Cherry pick of #5516 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5516

app/actions/views/channel.js, app/components/post_list/index.ts, app/components/post_list/post_list.tsx, app/screens/channel/channel_post_list/channel_post_list.js, app/screens/channel/channel_post_list/channel_post_list.test.js, app/screens/channel/channel_post_list/index.js, app/screens/thread/__snapshots__/thread.ios.test.js.snap, app/screens/thread/thread.android.js, app/screens/thread/thread.ios.js, patches/react-native+0.64.2.patch
Cherry pick of #5511 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5511

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  362

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #5522 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5522

app/components/channel_intro/channel_intro.js, app/components/post_list/combined_user_activity/combined_user_activity.tsx, app/components/post_list/post/index.ts, app/components/post_list/post/post.tsx, app/components/post_list/post_list.tsx, app/components/post_list/post_list_refresh_control.tsx, ios/Podfile.lock, package-lock.json
this PR aims to fix the performance degradation on Android after bringing back the option to pull to refresh.
on iOS behavior and performance should remain the same and for Android the performance issues should not be present and the user should have the option to pull to refresh when at the bottom of the post list.
```release-note
NONE
```
=> MM-36881 Fix scroll perf degradation with pull to refresh enabled

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java, android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java, app/actions/views/edit_profile.js, app/components/attachment_button/index.js, app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/profile_picture/profile_picture.tsx, app/components/sidebars/main/channels_list/filtered_list/filtered_list.js, app/init/push_notifications.test.js, app/init/push_notifications.ts, app/screens/settings/notification_settings_mobile/index.js, app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js, ios/Podfile.lock, package-lock.json
This PR addresses the bugs found during release testing
https://mattermost.atlassian.net/browse/MM-36908
https://mattermost.atlassian.net/browse/MM-36935
https://mattermost.atlassian.net/browse/MM-36929
https://mattermost.atlassian.net/browse/MM-36928
https://mattermost.atlassian.net/browse/MM-36920
https://mattermost.atlassian.net/browse/MM-36922
```release-note
NONE
```
=> 1.45 Release testing bug fixes

app/components/channel_intro/channel_intro.js, app/components/post_list/combined_user_activity/combined_user_activity.tsx, app/components/post_list/post/index.ts, app/components/post_list/post/post.tsx, app/components/post_list/post_list.tsx, app/components/post_list/post_list_refresh_control.tsx, ios/Podfile.lock, package-lock.json
Cherry pick of #5525 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5525

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java, android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java, app/actions/views/edit_profile.js, app/components/attachment_button/index.js, app/components/autocomplete/emoji_suggestion/emoji_suggestion.js, app/components/profile_picture/profile_picture.tsx, app/components/sidebars/main/channels_list/filtered_list/filtered_list.js, app/init/push_notifications.test.js, app/init/push_notifications.ts, app/screens/settings/notification_settings_mobile/index.js, app/screens/settings/notification_settings_mobile/notification_settings_mobile.android.js
Cherry pick of #5529 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5529

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #5537 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5537

app/components/autocomplete/at_mention_item/at_mention_item.tsx, app/screens/user_profile/user_profile_row.js, detox/e2e/support/ui/component/autocomplete.js, detox/e2e/support/utils/email.js, detox/e2e/support/utils/index.js, detox/e2e/test/autocomplete/autocomplete.e2e.js, detox/e2e/test/main_sidebar/main_sidebar.e2e.js, detox/e2e/test/messaging/channel_link.e2e.js, detox/e2e/test/messaging/emojis_and_reactions.e2e.js, detox/e2e/test/messaging/hashtags.e2e.js, detox/e2e/test/messaging/message_draft.e2e.js, detox/e2e/test/messaging/message_posting.e2e.js, detox/e2e/test/smoke_test/add_reaction.e2e.js, detox/e2e/test/smoke_test/email_notifications.e2e.js, detox/e2e/test/smoke_test/public_channels.e2e.js
- These are maintenance fixes. Ran the suite and fixed failing tests found locally.
- Moved `detox/e2e/support/utils.js` to `detox/e2e/support/utils/index.js`
- Added email utils
- `detox/e2e/support/utils/email.js`
Note: Will run the suite against android and will create a separate PR for that.
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-37128
```release-note
NONE
```
=> MM-37128 Detox/E2E Maintenance: Fix failing tests - iOS

app/utils/role/index.ts
=> [Gekidou] hasPermission role utility

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java, android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java, android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java, android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
Groups the Android push notifications by channel
https://mattermost.atlassian.net/browse/MM-37134
```release-note
Fixed Android push notifications so that they are grouped by channel.
```
=> MM-37134 Properly group Android push notifications by channel

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java, android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java, android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java, android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java
Cherry pick of #5548 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5548

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump Version to 1.45.1 and Build to 364

app/components/markdown/markdown_emoji/__snapshots__/markdown_emoji.test.js.snap, app/components/markdown/markdown_emoji/markdown_emoji.js, app/components/markdown/markdown_emoji/markdown_emoji.test.js
Cherry pick of #5547 on release-1.45.
/cc  @enahum
=> Automated cherry pick of #5547

detox/e2e/support/ui/screen/login.js, detox/e2e/test/channel_moderation/remove_user_from_channel.e2e.js, detox/e2e/test/messaging/channel_link.e2e.js, detox/e2e/test/messaging/hashtags.e2e.js, detox/e2e/test/signin_authentication/select_server.e2e.js, detox/e2e/test/smoke_test/search.e2e.js
- These are maintenance fixes. Ran the suite and fixed failing tests found locally when running against Android.
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-37129
```release-note
NONE
```
=> MM-37129 Detox/E2E Maintenance: Fix failing tests - Android

app/components/post_list/combined_user_activity/combined_user_activity.tsx, app/components/post_list/combined_user_activity/index.ts, assets/base/i18n/en.json, package-lock.json
https://mattermost.atlassian.net/browse/MM-37298
```release-note
Fixed displaying current user when multiple people are part of join / leave messages
```
=> MM-37298 fix missing current user in system join / leave messages

detox/e2e/test/smoke_test/message_posting.e2e.js
- Added e2e for posting multi-line emojis
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-37232
```release-note
NONE
```
=> MM-37232 Detox/E2E: Add e2e for posting multi-line emojis

app/components/friendly_date/friendly_date.test.tsx
Friendly date component test case is failing in some dev environments. 
https://mattermost.atlassian.net/browse/MM-37427
```release-note
NONE
```
=> MM-37427 Fixed failing Friendly date test case

app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap, app/components/sidebars/main/channels_list/list/index.js, app/components/sidebars/main/channels_list/list/list.js, app/components/sidebars/main/threads_entry/threads_entry.tsx, app/constants/view.js, app/mm-redux/selectors/entities/channels.ts
Makes the "Threads" item in the sidebar as fixed.
https://mattermost.atlassian.net/browse/MM-37456
This PR was tested on: iOS 14.5, iPhone 12 Simulator, Android 11 Pixel XL emulator
https://user-images.githubusercontent.com/3680799/127208468-cff3d0e5-e99c-4da9-b27b-d7b0323d01d1.mp4
```release-note
NONE
```
=> MM-37456 "Threads" item in the sidebar should not scroll

app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap, app/components/sidebars/main/channels_list/list/index.js, app/components/sidebars/main/channels_list/list/list.js, app/components/sidebars/main/threads_entry/threads_entry.tsx, app/constants/view.js, app/mm-redux/selectors/entities/channels.ts
Cherry pick of #5575 on release-1.46.
=> Automated cherry pick of #5575

NOTICE.txt
Cherry pick of #5579 on release-1.46.
/cc  @amyblais
=> Automated cherry pick of #5579

types/database/models/servers/channel.d.ts, types/database/models/servers/group.d.ts, types/database/models/servers/post.d.ts, types/database/models/servers/user.d.ts
Fixes models type definition so we can subquery
```release-note
NONE
```
=> [Gekidou] Fix database models type definition

app/context/theme/index.tsx, app/screens/channel/index.tsx, ios/Podfile.lock, package-lock.json
* Use the latest commit from network-client that resolves the double Auth header for android requests
* Set the global theme if no theme is assigned to current team
* Make it so the current channel screen does not crashes when there is no current team or channel selected
```release-note
NONE
```
=> [Gekidou] fixes

app/database/models/server/channel.ts, app/database/models/server/post.ts, app/database/models/server/posts_in_channel.ts, app/database/models/server/posts_in_thread.ts, app/database/operator/server_data_operator/handlers/posts_in_channel.ts, app/database/operator/server_data_operator/handlers/posts_in_thread.ts, app/database/operator/server_data_operator/transformers/post.test.ts, app/database/operator/server_data_operator/transformers/post.ts, app/database/schema/server/table_schemas/posts_in_channel.ts, app/database/schema/server/table_schemas/posts_in_thread.ts, app/database/schema/server/test.ts, app/queries/servers/post.ts, types/database/models/servers/posts_in_channel.d.ts, types/database/models/servers/posts_in_thread.d.ts, types/database/raw_values.d.ts
Update PostsInChannel and PostsInThread model to allow for multiple chunks at the same time to handle potential gaps.
```release-note
NONE
```
=> [Gekidou] Allow multiple posts in thread and posts in channel for a specific root or channel

patches/react-native-navigation+7.18.1.patch, share_extension/components/channel_button.tsx, share_extension/components/team_button.tsx
Cherry pick of #5596 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5596

app/actions/navigation/index.js, app/screens/edit_profile/edit_profile.js
Properly dismiss Edit profile screen by passing the componentId of the screen being dismissed
https://mattermost.atlassian.net/browse/MM-37666
```release-note
NONE
```
Dev review not needed
=> MM-37666 Properly dismiss edit profile screen

app/actions/views/root.js, app/components/network_indicator/network.tsx, app/init/push_notifications.ts, app/screens/channel/channel_base.js
Cherry pick of #5597 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5597

app/actions/navigation/index.js, app/screens/edit_profile/edit_profile.js
Cherry pick of #5599 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5599

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java
Cherry pick of #5601 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5601

app/components/pasteable_text_input/__snapshots__/index.test.js.snap, app/components/pasteable_text_input/index.js, app/components/pasteable_text_input/index.test.js, app/components/post_draft/__snapshots__/post_draft.test.js.snap, app/components/post_draft/draft_input/draft_input.js, app/components/post_draft/post_input/__snapshots__/post_input.test.js.snap, app/components/post_draft/post_input/post_input.js, app/components/post_draft/post_input/post_input.test.js, app/components/post_draft/quick_actions/quick_actions.js, app/components/post_draft/quick_actions/quick_actions.test.js, app/components/post_draft/uploads/uploads.js, app/components/post_draft/uploads/uploads.test.js
Cherry pick of #5595 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5595

app/mm-redux/actions/posts.test.js, app/mm-redux/actions/posts.ts
Cherry pick of #5602 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5602

app/components/sidebars/settings/settings_sidebar.ios.js, app/components/sidebars/settings/settings_sidebar_base.js, app/screens/custom_status_clear_after/clear_after_menu_item.tsx, app/screens/custom_status_clear_after/clear_after_modal.tsx
- Fixed the MM-37608 issue
- Fixed the MM-37416 issue
- https://mattermost.atlassian.net/browse/MM-37608
- https://mattermost.atlassian.net/browse/MM-37416
- iPhone 12 Simulator - iOS 14.4
- Android Emulator - Pixel_3a_API_30_x86 - Android 10
```release-note
Fixed the MM-37608 and MM-37416 issues
```
=> MM-37608 and MM-37416 issue fixes

app/components/sidebars/settings/settings_sidebar.ios.js, app/components/sidebars/settings/settings_sidebar_base.js, app/screens/custom_status_clear_after/clear_after_menu_item.tsx, app/screens/custom_status_clear_after/clear_after_modal.tsx
Cherry pick of #5592 on release-1.46.
/cc  @manojmalik20
=> Automated cherry pick of #5592

app/components/global_threads/global_threads.tsx, app/components/sidebars/main/channels_list/list/__snapshots__/list.test.js.snap, app/components/sidebars/main/channels_list/list/list.js, app/mm-redux/actions/threads.ts, app/mm-redux/reducers/entities/threads.ts, app/mm-redux/utils/channel_utils.ts, app/screens/post_options/post_options.js, app/screens/thread/thread_base.js, app/store/middlewares/helpers.js, app/store/middlewares/middleware.test.js
Cherry pick of #5612 on release-1.46.
=> Automated cherry pick of #5612

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Cherry pick of #5620 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5620

app/components/network_indicator/network.tsx, app/screens/edit_post/edit_post.js
Cherry pick of #5623 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5623

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  368

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #5625 on release-1.46.
/cc  @enahum
=> Automated cherry pick of #5625

app/screens/custom_status/custom_status_suggestion.tsx
Custom Status: Don't show 'Custom Date and Time' for recent statuses
Fixes [https://mattermost.atlassian.net/browse/MM-37423](https://mattermost.atlassian.net/browse/MM-37423)
Simulator IPhone 12 - Version: 14.5,
Emulator Google Pixel XL API 29 - Version:10
```release-note
* Remove Date and Time label from recents custom status
```
=> [MM-37423] Custom Status: Don't show 'Custom Date and Time' for recent statuses

app/client/rest/posts.ts
- Be consistent with query parameter names
Related PRs: 
- https://github.com/mattermost/mattermost-server/pull/18260
- https://github.com/mattermost/mattermost-webapp/pull/8700 
- https://mattermost.atlassian.net/browse/MM-36792
```release-note
NONE
```
=> [MM-36792] Consistent query param names

detox/e2e/support/test_config.js, detox/e2e/support/utils/email.js
- Fix failing email notifications e2e
NA
```release-note
NONE
```
=> Detox/E2E: Minor fix to email

app/actions/apps.ts, app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser.ts, app/components/autocomplete/slash_suggestion/app_command_parser/app_command_parser_dependencies.ts, app/components/post_list/post/body/content/embedded_bindings/embedded_binding.tsx, app/mm-redux/reducers/entities/__snapshots__/apps.test.js.snap, app/mm-redux/reducers/entities/apps.ts, app/screens/apps_form/apps_form_component.tsx, app/utils/apps.test.ts, app/utils/apps.ts
Sync with changes on https://github.com/mattermost/mattermost-webapp/pull/8249
Also piggybacking the changes on https://github.com/mattermost/mattermost-webapp/pull/8782
https://mattermost.atlassian.net/browse/MM-33575
https://mattermost.atlassian.net/browse/MM-33362
https://mattermost.atlassian.net/browse/MM-33436
https://mattermost.atlassian.net/browse/MM-33824
```release-note
Better binding filtering for Apps Framework
```
=> Sync binding filtering with webapp

NOTICE.txt
Cherry pick of #5688 on release-1.47.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #5688

share_extension/screens/channel_list.tsx, share_extension/screens/team_list.tsx
Cherry pick of #5696 on release-1.47.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5696

android/app/build.gradle, android/app/src/main/java/com/mattermost/rnbeta/MainApplication.java, android/settings.gradle
Enables WatermelonDB JSI on Android
See https://nozbe.github.io/WatermelonDB/CHANGELOG.html#performance for reasoning
```release-note
NONE
```
=> [Gekidou] Enable wdb-jsi on Android

app/actions/remote/entry.ts, app/init/launch.ts, app/utils/file/index.ts, app/utils/mattermost_managed.ts, ios/Mattermost/MattermostManaged.m, types/launch/index.ts
Entry point when the app gets updated from v1 to Gekidou
```release-note
NONE
```
=> [Gekidou] Entry point when upgrading from v1

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  371

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #5715 on release-1.47.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5715

app/components/sidebars/main/channels_list/list/list.js
Cherry pick of #5801 on release-1.48.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5801

app/i18n/index.ts, ios/Mattermost.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock
This PR enables Hermes JS engine on iOS. Hermes is already enabled on Android
```release-note
NONE
```
=> [Gekidou] Enable Hermes on iOS

NOTICE.txt
Cherry pick of #5805 on release-1.48.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #5805

app/screens/options_modal/options_modal.js, package-lock.json
Not sure what happened and why is not dismissing the modal but by passing the `componentId` to the dismissModal function we are ensuring the modal does get dismissed.
https://mattermost.atlassian.net/browse/MM-39913
```release-note
NONE
```
=> Fix options modal dismiss for OptionsModal

app/screens/options_modal/options_modal.js, package-lock.json
Cherry pick of #5819 on release-1.48.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5819

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  379

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #5824 on release-1.48.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5824

app/components/autocomplete/at_mention_group/at_mention_group.js, app/components/autocomplete/special_mention_item.js, package-lock.json, share_extension/components/channel_type.tsx
https://mattermost.atlassian.net/browse/MM-40040
```release-note
NONE
```
=> replace account-group-outline with account-multiple-outline compass icon

app/components/autocomplete/at_mention_group/at_mention_group.js, app/components/autocomplete/special_mention_item.js, package-lock.json, share_extension/components/channel_type.tsx
Cherry pick of #5826 on release-1.48.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5826

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  380

app/components/post_list/post/body/files/file_icon.tsx, app/components/post_list/post/body/files/files.tsx, app/screens/gallery/gallery.js, app/screens/gallery/gallery_viewer.tsx, app/screens/gallery/index.js, types/screens/gallery.d.ts
For some reason unclear to me the Gallery had an undefined height when opening while on CRT mode, regardless of the reason it is better to get those values from the Dimensions module instead of relying on having the values on redux.
In addition this fixes some broken compass icons for the attachment file types.
[MM-40160](https://mattermost.atlassian.net/browse/MM-40160)
```release-note
Fixed a crash on CRT when opening the Gallery view from within a thread
```
=> [MM-40160] Crt gallery fix

app/screens/login/form.tsx, app/screens/server/form.tsx
* Fixes the theme applied when switching back and forth between dark/light
* Fixes the tracking of login id & password for the connect button
```release-note
NONE
```
=> [Gekidou] Fix login form theming and fields tracking

app/components/post_list/post/body/files/file_icon.tsx, app/components/post_list/post/body/files/files.tsx, app/screens/gallery/gallery.js, app/screens/gallery/gallery_viewer.tsx, app/screens/gallery/index.js, types/screens/gallery.d.ts
Cherry pick of #5833 on release-1.48.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5833

android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java, android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotificationHelper.java, android/app/src/main/java/com/mattermost/rnbeta/NotificationDismissService.java, android/app/src/main/java/com/mattermost/rnbeta/NotificationPreferencesModule.java, app/actions/views/channel.js, app/constants/view.js, app/init/push_notifications.test.js, app/init/push_notifications.ts, app/screens/channel/channel.android.js, app/screens/thread/thread_base.js, ios/Mattermost/AppDelegate.m
Cherry pick of #5669 on release-1.48.
```release-note
NONE
```
=> Automated cherry pick of #5669

android/app/src/main/AndroidManifest.xml
Cherry pick of #5841 on release-1.48.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5841

ios/Podfile.lock, package-lock.json
=> [Gekidou] Update pods

app/components/loading/__snapshots__/index.test.tsx.snap, app/components/loading/index.tsx, app/screens/channel/failed_channels/index.tsx, app/screens/channel/failed_teams/index.tsx, app/screens/login/form.tsx, app/screens/mfa/index.tsx, app/screens/server/form.tsx
Add color to loading spinners. This is based on our discussions on the channel and my PR on browse channels.
This small PR will allow @avinashlng1080 to work with this changes, and reduce the size of the browse channels PR.
None
```release-note
None
```
=> [Gekidou] Add color to loading spinners

app/actions/views/custom_status.ts
Fixes custom status update with no expiry.
Fixes https://mattermost.atlassian.net/browse/MM-40206
```release-note
Fixes custom status updates with no expiry.
```
=> Fixes custom status update with no expiry

ios/Mattermost/MattermostManaged.m, patches/@nozbe+watermelondb+0.24.0.patch
This PR fixes a crash when the app is being hot reloaded during development as well as a crash when the user logs out and logs back in without closing the app.
```release-note
NONE
```
=> Fix re-login and hot reload crash

app/actions/views/custom_status.ts
Cherry pick of #5881 on release-1.48.
/cc  @shazm
```release-note
NONE
```
=> Automated cherry pick of #5881

android/app/build.gradle, assets/base/i18n/en.json, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Version 1.48.2 build 382

app/constants/database.ts, app/database/manager/__mocks__/index.ts, app/database/manager/index.ts, app/database/models/server/category.ts, app/database/models/server/category_channel.ts, app/database/models/server/channel.ts, app/database/models/server/index.ts, app/database/models/server/my_channel.ts, app/database/operator/server_data_operator/comparators/index.ts, app/database/operator/server_data_operator/handlers/category.test.ts, app/database/operator/server_data_operator/handlers/category.ts, app/database/operator/server_data_operator/index.ts, app/database/operator/server_data_operator/transformers/category.test.ts, app/database/operator/server_data_operator/transformers/category.ts, app/database/schema/server/index.ts, app/database/schema/server/table_schemas/category.ts, app/database/schema/server/table_schemas/category_channel.ts, app/database/schema/server/table_schemas/index.ts, app/database/schema/server/test.ts, types/api/category.d.ts, types/database/database.d.ts, types/database/models/servers/category.d.ts, types/database/models/servers/category_channel.d.ts, types/database/raw_values.d.ts
Introduces `Category` & `CategoryChannel` for sidebar categories.
https://mattermost.atlassian.net/browse/MM-38765
```release-note
```
=> [Gekidou] Sidebar Categories (Database only)

NOTICE.txt
Cherry pick of #5923 on release-1.49.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #5923

app/actions/views/permalink.ts, app/mm-redux/actions/threads.ts, app/mm-redux/selectors/entities/posts.ts, app/screens/permalink/index.js, app/screens/permalink/permalink.js, app/screens/thread/index.js
Cherry pick of #5758 on release-1.49.
```release-note
NONE
```
=> Automated cherry pick of #5758

app/actions/views/root.js, app/actions/views/user.js, app/actions/websocket/index.ts, app/init/fetch.js, app/init/fetch.test.js, app/init/global_event_handler.js, app/init/global_event_handler.test.js, app/mm-redux/reducers/entities/general.ts, app/utils/general.js
Cherry pick of #5927 on release-1.49.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5927

fastlane/Fastfile
Added the support for submitting Android app bundle to Google Play
```release-note
Added the support for submitting Android app bundle to Google Play
```
=> Added the support for submitting Android app bundle to Google Play

fastlane/Fastfile
=> Fastlane upload_file_to_s3 to use all files that match the extension

fastlane/Fastfile
Cherry pick of #5941 on release-1.49.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5941

app/queries/servers/team.ts
Minor fix to switch teams from tablets when there is no history in the team.
None
```release-note
NONE
```
=> Fix team switch when there is no history in the team

android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java, android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java, app/actions/local/channel.ts, app/actions/remote/entry/app.ts, app/actions/remote/entry/common.ts, app/actions/remote/entry/login.ts, app/actions/remote/entry/notification.ts, app/actions/remote/group.ts, app/actions/remote/role.ts, app/actions/remote/team.ts, app/actions/remote/user.ts, app/actions/websocket/index.ts, app/actions/websocket/users.ts, app/client/rest/base.ts, app/client/rest/index.test.js, app/init/global_event_handler.ts, app/init/websocket_manager.ts, app/queries/servers/system.ts, app/utils/supported_server/index.ts
Fixes & Refactors some logic around the entry point as well as the websocket first connection and reconnection
Also implements the changes around `X-Version-Id` made in this PR https://github.com/mattermost/mattermost-mobile/pull/5927 for v1
```release-note
NONE
```
=> [Gekidou] Fix & small refactor to the app entry logic and WS reconnection

app/screens/server/index.tsx
fix: Remove error of displayName, url error if present on handleConnect server screen
Fixes https://github.com/mattermost/mattermost-server/issues/19510
1. Samsung Galaxy M40
Android 10
```release-note
NONE
```
=> [Gekidou] fix: Remove error of displayName, url error if present on handleConnect

ios/Mattermost/Info.plist
Cherry pick of #5959 on release-1.49.
```release-note
NONE
```
=> Automated cherry pick of #5959

app/screens/navigation.ts
As the title
```release-note
NONE
```
=> Prevent the app from crashing when a screen has not been registered

app/components/markdown/at_mention/index.tsx, app/components/markdown/markdown_code_block/index.tsx, app/components/markdown/markdown_image/index.tsx, app/components/markdown/markdown_link/index.tsx, app/components/post_draft/quick_actions/camera_quick_action/camera_type.tsx, app/components/post_list/post/body/failed/index.tsx, app/components/team_sidebar/add_team/add_team_slide_up.tsx, app/components/team_sidebar/add_team/team_list_item/team_list_item.tsx, app/screens/browse_channels/dropdown_slideup.tsx, app/screens/edit_profile/components/edit_profile_picture.tsx, app/screens/home/account/components/options/user_presence/index.tsx, app/screens/home/channel_list/servers/servers_list/server_item/index.tsx, app/screens/navigation.ts, app/screens/post_options/components/reaction_bar/reaction_bar.tsx, app/utils/file/file_picker/index.ts, app/utils/server/index.ts
Properly dismiss bottomSheet or a bottomSheet based screen.
```release-note
NONE
```
=> Use dismissBottomSheet helper function instead of emitting an event

app/components/markdown/markdown_image/index.js, app/components/markdown/markdown_image/markdown_image.js, app/components/markdown/markdown_table_image/index.js, app/components/markdown/markdown_table_image/markdown_table_image.tsx, package-lock.json, patches/react-native-svg+12.1.1.patch
Cherry pick of #5973 on release-1.49.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5973

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  385

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #5975 on release-1.49.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5975

app/actions/remote/post.ts, app/screens/post_options/options/pin_channel_option.tsx, app/screens/post_options/post_options.tsx, package-lock.json
This PR takes care of un/pinning a post in the post options menu.
https://mattermost.atlassian.net/browse/MM-41942
```release-note
NONE
```
=> MM-41942 - Gekidou Post option Pin message

app/actions/views/root.js, app/init/push_notifications.ts, app/types/push_notification.d.ts
Cherry pick of #5969 on release-1.49.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5969

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/file_viewer_provider_paths.xml
This PR fixes the issue where users on Android were unable to open files like pdf and others. This was cause a change in the OS requirements.
https://mattermost.atlassian.net/browse/MM-41968
```release-note
Fixed an issue on Android that document files were not opening
```
=> Fix Android file preview

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/file_viewer_provider_paths.xml
Cherry pick of #5992 on release-1.49.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #5992

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump version build 1.49.1 build 386

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #6003 on release-1.49.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6003

app/actions/remote/channel.ts
in the action `fetchMyChannelsForTeam` we were storing channels and then categories but not batching them, at times this caused a race condition and a warning being displayed.
There is no reason why we should not batch this models into the database at the same time, so that is done with this PR.
```release-note
NONE
```
=> Batch categories and channels in fetchMyChannelsForTeam action

app/client/websocket/index.ts, app/init/websocket_manager.ts
For reliable WebSockets on Android we need to attach the Authorization header for the server to identify the previous connection Id, this is not required on iOS as it uses a cookie Jar which android does not.
Also on Android we had a battery drain as the background timer was not stopping after the first run, now by changing the way it was implemented it does.
Finally fixed the WS reconnection after the device receives back network connection as before the socket was being closed by an error but the conn state was not set as closed.
```release-note
NONE
```
=> [Gekidou] Fixes WS reconnection

ios/Mattermost/AppDelegate.m
Handle test notifications in iOS.
Server: https://github.com/mattermost/mattermost-server/pull/19610
Push Proxy: https://github.com/mattermost/mattermost-push-proxy/pull/96
None
```release-note
NONE
```
=> Handle test notifications on iOS

app/actions/local/post.ts, app/actions/remote/post.ts, app/components/formatted_markdown_text/index.tsx, app/components/markdown/at_mention/index.tsx, app/components/post_list/combined_user_activity/combined_user_activity.tsx, app/components/post_list/combined_user_activity/last_users.tsx, app/components/system_header/index.tsx, app/screens/post_options/index.ts, app/screens/post_options/options/delete_post_option.tsx, app/screens/post_options/post_options.tsx
Fix alignment of the combined system messages text and fixed the post_options so it properly displays the Delete option for this combined system messages. Finally made some changes to the delete action in order to be able to delete the combined system messages post.
Thanks to @jfrerich for noticing the issue.
```release-note
NONE
```
=> [Gekidou] combined system message

app/components/channel_list/categories/body/__snapshots__/category_body.test.tsx.snap, app/components/channel_list/categories/body/category_body.tsx, app/components/channel_list/categories/categories.tsx, app/constants/index.ts, app/constants/list.ts
Adds a few performance optimisations to the `FlatList` rendering the category / channel list in the sidebar.
Fixes https://mattermost.atlassian.net/browse/MM-42333
```release-note
```
=> [Gekidou] Sidebar Categories FlatList Optimisations

app/products/calls/screens/call/__snapshots__/call_screen.test.js.snap, app/products/calls/screens/call/call_screen.test.js, app/products/calls/screens/call/call_screen.tsx, app/products/calls/screens/call/index.ts, app/products/calls/store/action_types/calls.ts, app/products/calls/store/actions/calls.test.js, app/products/calls/store/actions/calls.ts, app/products/calls/store/reducers/calls.ts, app/products/calls/store/selectors/calls.ts, app/products/calls/store/types/calls.ts, ios/Mattermost.xcodeproj/project.pbxproj, package-lock.json
- Add a `Speaker` button to the call screen
- https://mattermost.atlassian.net/browse/MM-42332
- iOS iPhone 7 Plus
- Android Pixel 6
- iOS:
- Android:
```release-note
Adding a Speakerphone button to the calls interface
```
=> [MM-42332] Calls: Add speakerphone button

app/components/channel_list/categories/body/category_body.test.tsx, app/components/channel_list/categories/body/category_body.tsx, app/components/channel_list/categories/body/channel/channel_list_item.test.tsx, app/components/channel_list/categories/body/channel/channel_list_item.tsx, app/components/channel_list/categories/body/channel/index.ts, app/components/channel_list/categories/body/index.ts, app/components/channel_list/categories/categories.tsx, app/components/channel_list/categories/index.ts, app/database/models/server/category.ts
Updates channel-list sorting inside categories:
- Alpha sort now handles the channel being muted
- Sorting has been moved from component to the withObservable HOC
Fixes https://mattermost.atlassian.net/browse/MM-42165
```release-note
```
=> Sorting categories body in the observable

app/components/post_draft/draft_input/index.tsx
Add radius to the input box
https://mattermost.atlassian.net/browse/MM-39687
```release-note
NONE
```
=> Add Input radius

app/actions/local/category.ts, app/components/channel_list/categories/body/__snapshots__/category_body.test.tsx.snap, app/components/channel_list/categories/body/category_body.tsx, app/components/channel_list/categories/body/channel/__snapshots__/channel_list_item.test.tsx.snap, app/components/channel_list/categories/body/channel/channel_list_item.test.tsx, app/components/channel_list/categories/body/channel/channel_list_item.tsx, app/components/channel_list/categories/body/index.ts, app/components/channel_list/categories/header/__snapshots__/header.test.tsx.snap, app/components/channel_list/categories/header/header.tsx, package-lock.json
Adds category collapsing with animations.
Fixes https://mattermost.atlassian.net/browse/MM-42163
```release-note
```
=> Gekidou category collapse animated

app/components/channel_list/threads/__snapshots__/threads.test.tsx.snap, app/screens/post_options/index.ts, app/screens/post_options/options/follow_option/follow_option.tsx, app/screens/post_options/options/follow_option/index.tsx, app/screens/post_options/post_options.tsx
Continued digging into Gekidou/Mobile v2 for my OSF and grabbed this ticket. Hopefully I didn't duplicate any work here but once again it was a good learning experience for me to understand how everything works some more.
Test with CRT turned both on and off.
I couldn't find any existing tests to extend for this, happy to add a test if someone can point me to where they are for these. Also happy to add new tests for this area if there aren't any yet.
https://mattermost.atlassian.net/browse/MM-40084
iPhone 13, iOS 15.0 simulator
```release-note
NONE
```
=> MM-40084 Add follow message/thread on long press

app/components/channel_list/categories/body/category_body.tsx, app/components/channel_list/categories/body/index.ts
=> Adds DM/GM limit based on pref

app/database/models/app/global.ts, app/database/models/app/info.ts, app/database/models/app/servers.ts, app/database/models/server/channel.ts, app/database/models/server/channel_info.ts, app/database/models/server/channel_membership.ts, app/database/models/server/custom_emoji.ts, app/database/models/server/draft.ts, app/database/models/server/file.ts, app/database/models/server/my_channel.ts, app/database/models/server/my_channel_settings.ts, app/database/models/server/my_team.ts, app/database/models/server/post.ts, app/database/models/server/posts_in_channel.ts, app/database/models/server/posts_in_thread.ts, app/database/models/server/preference.ts, app/database/models/server/reaction.ts, app/database/models/server/role.ts, app/database/models/server/slash_command.ts, app/database/models/server/system.ts, app/database/models/server/team.ts, app/database/models/server/team_channel_history.ts, app/database/models/server/team_membership.ts, app/database/models/server/team_search_history.ts, app/database/models/server/terms_of_service.ts, app/database/models/server/thread.ts, app/database/models/server/thread_in_team.ts, app/database/models/server/thread_participant.ts, app/database/models/server/user.ts, types/database/models/servers/post.d.ts
As the title says, we have WDB models on one hand and the types under the sub-folder '@typings' but the two were not 'connected.  This PR fixes this issue.
```release-note
NONE
```
=> Gekidou - Fix to make all models implement their respective interface

app/components/channel_icon/index.tsx, app/components/channel_list/categories/body/__snapshots__/category_body.test.tsx.snap, app/components/channel_list/categories/body/category_body.test.tsx, app/components/channel_list/categories/body/category_body.tsx, app/components/channel_list/categories/body/channel/__snapshots__/channel_list_item.test.tsx.snap, app/components/channel_list/categories/body/channel/channel_list_item.test.tsx, app/components/channel_list/categories/body/channel/channel_list_item.tsx, app/components/channel_list/categories/body/channel/index.ts, app/components/channel_list/categories/body/index.ts, app/database/operator/server_data_operator/transformers/channel.ts
Performance improvements done during pair programming with @enahum and @avinashlng1080 , directed towards the team switch action.
None
```release-note
NONE
```
=> [Gekidou] Address performance improvements on team switch action

app/components/autocomplete/at_mention/at_mention.tsx, app/components/autocomplete/channel_mention/channel_mention.tsx, app/components/navigation_header/header.tsx, app/components/post_draft/draft_handler/index.ts, app/components/post_draft/index.ts, app/components/post_draft/post_input/index.ts, app/components/post_draft/quick_actions/index.ts, app/components/post_draft/typing/index.tsx, app/components/post_draft/uploads/index.tsx, app/components/post_list/combined_user_activity/index.ts, app/components/post_list/post/body/reactions/reaction.tsx, app/components/post_list/post/body/reactions/reactions.tsx, app/components/post_list/post/index.ts, app/screens/channel/channel_post_list/index.ts, package-lock.json, package.json
Several performance improvements from the Home to Channel switch.
Wait for comments on the reasoning behind these changes.
None
```release-note
NONE
```
=> [Gekidou] Performance improvements on Home to Channel

app/actions/websocket/posts.ts
The component that shows how many unread messages are in the channel reads from the `myChannel.msgCount` so we need to get the delta to be accurate.
```release-note
NONE
```
=> [Gekidou] Use delta for mark as unread

package-lock.json, package.json
Cherry pick of #6145 on release-1.51.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6145

app/products/calls/components/floating_call_container.tsx
Using a hook inside the callback of a function is not really the way to use it, this PR makes it so that the hook is used in the function component and then applies the values to the needed styles and it does memoize them just to prevent re-calculations and re-renders
```release-note
NONE
```
=> Fix floating container using a hook inside the styles

app/products/calls/components/floating_call_container.tsx
Cherry pick of #6146 on release-1.51.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6146

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  391

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #6159 on release-1.51.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6159

app/components/channel_list/index.tsx
Fixes the initial width for the channel list (sidebar) on Tablets.
```release-note
NONE
```
=> [Gekidou] Fix initial Channel list width on iPad

app/components/team_sidebar/add_team/team_list.tsx, app/components/team_sidebar/add_team/team_list_item/team_list_item.tsx, app/screens/bottom_sheet/button.tsx, app/screens/bottom_sheet/content.tsx
Update bottom sheet styles for title and button
* Title: Heading 600 SemiBold
* Button: Body 200 SemiBold
https://mattermost.atlassian.net/browse/MM-42747
```release-note
NONE
```
=> [Gekidou] Update bottom sheet style for title and button

app/actions/websocket/channel.ts, app/queries/servers/channel.ts
Fix an issue where receiving a DM from a new user does not appear in the channel list
None
```release-note
NONE
```
=> [Gekidou] Fix new DM issue

app/actions/remote/channel.ts, app/actions/websocket/channel.ts, app/components/channel_list/categories/body/category_body.test.tsx, app/components/channel_list/categories/body/category_body.tsx, app/components/channel_list/categories/body/channel/channel_list_item.test.tsx, app/components/channel_list/categories/body/channel/channel_list_item.tsx, app/components/channel_list/categories/body/channel/index.ts, app/components/channel_list/categories/body/index.ts, app/components/channel_list/categories/categories.tsx, app/components/channel_list/categories/index.ts, app/components/channel_list/categories/unreads/index.ts, app/components/channel_list/categories/unreads/unreads.test.tsx, app/components/channel_list/categories/unreads/unreads.tsx, index.ts
Performance improvements. Details in the comments.
```release-note
None
```
=> Performance improvements in the area of home and channel switch.

app/screens/select_server/select_server.js
Cherry pick of #6185 on release-1.51.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6185

app/init/managed_app.ts
https://mattermost.atlassian.net/browse/MM-43485
```release-note
NONE
```
=> Use device locale to display the untrusted device alert

app/components/navigation_header/header.tsx
https://mattermost.atlassian.net/browse/MM-43897
```release-note
NONE
```
=> Fix Back button position in Navigation Header

app/components/post_list/index.ts, app/components/post_list/post_list.tsx, app/screens/channel/channel_post_list/channel_post_list.tsx, app/screens/channel/channel_post_list/index.ts, app/screens/home/recent_mentions/recent_mentions.tsx, app/screens/permalink/permalink.tsx, app/screens/saved_posts/saved_posts.tsx, app/screens/thread/thread_post_list/index.ts, app/screens/thread/thread_post_list/thread_post_list.tsx, app/utils/post_list/index.ts
https://mattermost.atlassian.net/browse/MM-43890
```release-note
NONE
```
=> [Gekidou] Do not set new line message indicator on own posts

app/client/rest/base.ts, app/client/rest/index.ts, app/client/rest/plugins.ts, app/constants/calls.ts, app/constants/websocket.ts, app/products/calls/hooks.ts, app/products/calls/store/action_types/calls.ts, app/products/calls/store/actions/calls.test.js, app/products/calls/store/actions/calls.ts, app/products/calls/store/reducers/calls.ts, app/products/calls/store/selectors/calls.ts, app/products/calls/store/types/calls.ts, app/products/calls/websocket.ts, app/screens/channel/channel.android.js, app/screens/channel/channel.ios.js, app/screens/channel/channel_base.js, app/screens/channel/index.js
Cherry pick of #6210 on release-1.51.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #6210

app/components/channel_item/channel_item.tsx
=> [Gekidou] Hide archive channels in channel list

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Dot release 1.51.2

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  396

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #6218 on release-1.52.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6218

app/init/push_notifications.ts
https://mattermost.atlassian.net/browse/MM-43899
```release-note
NONE
```
=> Preserve notifications when tapping or clearing notifications from a channel

app/components/channel_item/custom_status/custom_status.tsx, app/components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap, app/components/custom_status/custom_status_emoji.tsx, app/components/post_list/post/header/header.tsx, app/screens/custom_status/components/custom_status_emoji.tsx, app/screens/custom_status/components/custom_status_input.tsx, app/screens/custom_status/components/custom_status_suggestion.tsx
https://mattermost.atlassian.net/browse/MM-43942
```release-note
NONE
```
=> [Gekidou] Fix alignment of custom status

app/components/channel_item/index.ts, app/screens/home/channel_list/categories_list/categories/unreads/index.ts
Also excludes muted channels from grouped unreads unless they have a mention.
```release-note
```
=> Gekidou unreads mention fix

app/components/channel_item/index.ts, app/components/team_sidebar/team_list/team_item/index.ts, app/database/subscription/unreads.ts, app/queries/servers/channel.ts, app/screens/home/channel_list/categories_list/categories/unreads/index.ts, app/screens/home/channel_list/servers/index.tsx, app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx, app/screens/home/tab_bar/home.tsx
https://mattermost.atlassian.net/browse/MM-43901
```release-note
NONE
```
=> [Gekidou] Exclude muted channels from unread badges

app/components/user_list_row/index.tsx, app/screens/create_direct_message/selected_users/selected_user.tsx
https://mattermost.atlassian.net/browse/MM-43945
https://mattermost.atlassian.net/browse/MM-43946
```release-note
NONE
```
=> [Gekidou] Fix create direct message styles

app/products/calls/store/actions/calls.test.js, app/products/calls/store/actions/calls.ts
Cherry pick of #6229 on release-1.52.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #6229

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 397

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  398

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #6236 on release-1.52.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6236

app/components/channel_item/channel_item.tsx, app/components/channel_item/index.ts, app/screens/home/channel_list/categories_list/categories/body/category_body.tsx, app/screens/home/channel_list/categories_list/categories/header/__snapshots__/header.test.tsx.snap, app/screens/home/channel_list/categories_list/categories/header/header.tsx, package-lock.json
Updates the channel and category muted opacity based on https://www.figma.com/file/a9w2q3JnVvBwo2IScP8j3K/Phase-1-Design\?node-id\=4171%3A136108
```release-note
```
=> [Gekidou] Updated styling opacities

app/components/post_list/post/post.tsx
https://mattermost.atlassian.net/browse/MM-44021
```release-note
NONE
```
=> [Gekidou] Dismiss keyboard when a post is pressed

app/components/post_draft/typing/index.tsx
Fix the issue with the scrolling by delaying 500ms the re-render that hides the typing.
https://mattermost.atlassian.net/browse/MM-43999
```release-note
NONE
```
=> Fix typing

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  399

app/screens/home/channel_list/categories_list/categories/body/category_body.tsx, app/screens/home/channel_list/categories_list/categories/body/index.ts
https://mattermost.atlassian.net/browse/MM-44027
```release-note
NONE
```
=> Show unread channels when category is collapsed

app/screens/home/channel_list/categories_list/categories/body/index.ts
Filter archived channels from channel list unless is the active channel.
```release-note
NONE
```
=> [Gekidou] Filter archived channels from channel list

app/screens/thread/thread.tsx
https://mattermost.atlassian.net/browse/MM-43970
```release-note
NONE
```
=> [Gekidou] go back when root post is deleted in thread view

app/components/navigation_header/header.tsx, app/components/post_draft/typing/index.tsx, app/constants/post_draft.ts, app/constants/screens.ts, app/screens/channel/channel_post_list/channel_post_list.tsx, app/screens/channel/channel_post_list/intro/direct_channel/member/member.tsx, app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
* Add space to bottom of channel content
* Clicking username/avatar in channel crashes app
* Loading state of server item button is misaligned
* user is typing shows on channel rather than thread and styling
* https://mattermost.atlassian.net/browse/MM-44005
* https://mattermost.atlassian.net/browse/MM-43998
* https://mattermost.atlassian.net/browse/MM-44033
* https://mattermost.atlassian.net/browse/MM-44035
```release-note
NONE
```
=> [Gekidou] bug fixes

app/components/team_sidebar/add_team/index.tsx, app/components/team_sidebar/team_list/team_item/team_icon.tsx
https://mattermost.atlassian.net/browse/MM-44064
```release-note
NONE
```
=> [Gekidou] Team icon style

app/components/autocomplete/autocomplete.tsx, app/constants/autocomplete.ts
Correct autocomplete position on tablets
None
```release-note
NONE
```
=> Fix autocomplete position on tablets

app/components/channel_item/channel_item.tsx, app/components/floating_text_input_label/index.tsx, app/components/markdown/channel_mention/channel_mention.tsx, app/components/post_list/post/post.tsx, app/components/server_icon/__snapshots__/server_icon.test.tsx.snap, app/components/server_icon/index.tsx, app/components/team_sidebar/team_list/team_item/team_item.tsx, app/constants/events.ts, app/screens/channel/channel.tsx, app/screens/channel/channel_post_list/channel_post_list.tsx, app/screens/channel/channel_post_list/intro/intro.tsx, app/screens/find_channels/filtered_list/filtered_list.tsx, app/screens/find_channels/index.tsx, app/screens/gallery/footer/footer.tsx, app/screens/home/channel_list/channel_list.tsx, app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx, app/screens/home/index.tsx, app/screens/server/form.tsx, app/screens/server/index.tsx
Fixes multiple small issues reported [here](https://docs.google.com/document/d/1DzLinBmTZIo_3kqxlvp_oU4gAz6-rBo4weY-flfVQs4/edit)
```release-note
NONE
```
=> [Gekidou] Various fixes

app/actions/remote/general.ts, app/client/rest/base.ts, app/client/rest/general.ts, types/api/client.d.ts
=> [Gekidou] Set 5s as default timeout for ping action

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 400

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to  401

app/queries/servers/thread.ts
=> Observe CRT preference with values

android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java, app/actions/remote/post.ts, app/components/post_list/post/body/failed/index.tsx, app/components/post_list/post/post.tsx, app/constants/post.ts, app/database/models/server/post.ts, app/utils/file/file_picker/index.ts, app/utils/post/index.ts, package-lock.json, types/database/models/servers/post.d.ts
* Adds functionality to "Try again" on a failed post.
* Fixes an issue attaching files on Android
https://mattermost.atlassian.net/browse/MM-44418
https://mattermost.atlassian.net/browse/MM-44425
```release-note
NONE
```
=> [Gekidou] retry post

app/screens/post_options/reaction_bar/reaction_bar.tsx
https://mattermost.atlassian.net/browse/MM-44464
```release-note
NONE
```
=> Wait until bottom sheet closes before adding the reaction

assets/base/i18n/en.json
Update i18n to reflect a previous change done on the default message.
https://mattermost.atlassian.net/browse/MM-44039
```release-note
NONE
```
=> Update en.json to show proper message on threads tab

app/actions/remote/groups.ts, app/client/rest/groups.ts, app/components/autocomplete/at_mention/at_mention.tsx
This follows on the API modifications made in https://github.com/mattermost/mattermost-mobile/pull/6261, and adds the other missing methods required for https://github.com/mattermost/mattermost-mobile/pull/6276;
- Get memberships (users), teams and channels [relations] for a given Group
- Get groups associated to a given team, channel and user
https://mattermost.atlassian.net/browse/MM-43981
```release-note
```
=> [Gekidou] Groups API Calls

app/constants/calls.ts, app/products/calls/components/call_message/__snapshots__/call_message.test.js.snap, app/products/calls/components/call_message/call_message.tsx, app/products/calls/components/call_message/index.ts, app/products/calls/components/channel_info/start_call.tsx, app/products/calls/components/join_call/__snapshots__/join_call.test.js.snap, app/products/calls/components/join_call/index.ts, app/products/calls/components/join_call/join_call.test.js, app/products/calls/components/join_call/join_call.tsx, app/products/calls/connection.ts, app/products/calls/store/actions/calls.test.js, app/products/calls/store/actions/calls.ts, app/products/calls/store/selectors/calls.ts, app/products/calls/store/types/calls.ts
Cherry pick of #6318 on release-1.53.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #6318

app/products/calls/components/call_message/call_message.tsx, app/products/calls/components/call_message/index.ts, app/products/calls/components/channel_info/start_call.tsx, app/products/calls/components/join_call/index.ts, app/products/calls/components/join_call/join_call.test.js, app/products/calls/components/join_call/join_call.tsx, app/products/calls/store/selectors/calls.test.js, app/products/calls/store/selectors/calls.ts, app/products/calls/store/types/calls.ts
Cherry pick of #6334 on release-1.53.
```release-note
NONE
```
=> Automated cherry pick of #6334

app/screens/login/index.tsx
https://mattermost.atlassian.net/browse/MM-44665
```release-note
NONE
```
=> [Gekidou] Ease the way the keyboard can be dismissed in the login screen

app/components/channel_item/channel_item.tsx
https://mattermost.atlassian.net/browse/MM-44726
```release-note
NONE
```
=> Use sidebarUnreadText for unread channel item

app/actions/remote/post.ts, app/screens/permalink/index.ts, app/screens/permalink/permalink.tsx
https://mattermost.atlassian.net/browse/MM-44468
```release-note
NONE
```
=> [Gekidou] Show permalink view with CRT enabled

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump version to 1.53.0 Build 404

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #6345 on release-1.53.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6345

app/screens/global_threads/threads_list/empty_state.tsx, app/screens/global_threads/threads_list/threads_list.tsx, app/screens/pinned_messages/empty/index.tsx, app/screens/saved_posts/components/empty.tsx
https://mattermost.atlassian.net/browse/MM-44804
```release-note
NONE
```
=> [Gekidou] Align empty states

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 405

app/screens/permalink/permalink.tsx, app/utils/permalink/index.ts
This PR changes the UI of the permalink view excluding the UI related to the non-happy path. The non-happy path is being worked on #6294 I believe.
https://mattermost.atlassian.net/browse/MM-42107
```release-note
NONE
```
=> [Gekidou] Permalink UI (excluding non-happy path)

app/actions/remote/entry/app.ts, app/actions/remote/entry/common.ts, app/actions/remote/post.ts, app/actions/websocket/channel.ts, app/actions/websocket/index.ts, app/database/operator/server_data_operator/handlers/category.ts, app/database/operator/server_data_operator/handlers/channel.ts, app/database/operator/server_data_operator/handlers/team.ts, app/database/operator/server_data_operator/handlers/user.ts, app/database/operator/server_data_operator/transformers/channel.ts, app/queries/servers/channel.ts, app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap, app/screens/home/channel_list/categories_list/categories/body/category_body.tsx, app/screens/home/channel_list/categories_list/categories/body/index.ts, app/screens/home/channel_list/categories_list/header/__snapshots__/header.test.tsx.snap, app/screens/home/channel_list/categories_list/header/header.tsx, app/screens/home/channel_list/categories_list/header/loading_unreads.tsx, app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
Optimization to only store data that has changed.
```release-note
NONE
```
=> [Gekidou] handlers perf

app/actions/remote/channel.ts, app/actions/remote/user.ts
=> [Gekidou] Fetch missing GM display name

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 406

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 407

app/screens/home/index.tsx
This PR disables the search screen until it is feature complete
N/A
```release-note
NONE
```
=> Disable the search screen

app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap, app/screens/home/channel_list/categories_list/categories/unreads/index.ts, app/screens/home/channel_list/categories_list/categories/unreads/unreads.test.tsx, app/screens/home/channel_list/categories_list/categories/unreads/unreads.tsx, app/screens/home/channel_list/categories_list/header/__snapshots__/header.test.tsx.snap, app/screens/home/channel_list/categories_list/header/loading_unreads.tsx
Fixes an issue when CRT was enabled and there were unread Threads but not unread channels the empty state for unread channels was showing up.
https://mattermost.atlassian.net/browse/MM-45124
```release-note
NONE
```
=> [Gekidou] Show unread empty state if there are not unread threads

app/components/option_item/index.tsx
https://mattermost.atlassian.net/browse/MM-45143
```release-note
NONE
```
=> [Gekidou] Set the color for the Switch component based on the theme

app/client/rest/files.ts
=> [Gekidou] Set default timeout to 3 minutes when uploading files

app/actions/remote/post.ts
In certain scenarios we were fetching posts but not the authors or users mentioned in the messages, which led to a crash as it could not find the user.
```release-note
NONE
```
=> [Gekidou] Fetch post authors when fetching posts

app/actions/local/channel.ts, app/actions/local/thread.ts, app/actions/remote/entry/notification.ts
Ensure the theme is set when opening the app from a push notification
https://mattermost.atlassian.net/browse/MM-45160
https://mattermost.atlassian.net/browse/MM-45111
```release-note
NONE
```
=> [Gekidou] Set theme when opening the app from a push notification

app/queries/servers/channel.ts, app/screens/find_channels/filtered_list/filtered_list.tsx, app/screens/find_channels/filtered_list/index.ts, app/screens/find_channels/index.tsx, app/screens/find_channels/quick_options/quick_options.tsx, app/screens/find_channels/unfiltered_list/unfiltered_list.tsx
This PR makes some changes in the Query to get the Direct messages in the find channel screen and reduces the local search from ~3 seconds to < 100ms on android and from ~1s to < 50ms on iOS
Also changes the timing in the animations to improve on perceived perf
Note: This PR seems to work better than #6390 
```release-note
NONE
```
=> [Gekidou] Improve performance on find channels queries

app/actions/remote/groups.ts, app/screens/channel_info/options/edit_channel/index.tsx, app/screens/create_or_edit_channel/channel_info_form.tsx, app/screens/navigation.ts, app/screens/user_profile/options.tsx, app/screens/user_profile/title/avatar.tsx, app/screens/user_profile/user_profile.tsx
The StatusBar was getting all white when moving to certain screens, in particular Create or Edit Channel.
While fixing this, I realized some other minor style issues, among others, the Autocomplete positioning. I tried to fix those too.
None
```release-note
Fix Status Bar going white on certain screens like Create or Edit Channel.
Improve Create or Edit channel styles.
Improve Create or Edit channel autocomplete positioning.
```
=> Fix Status Bar color, and some minor adjustments in the create channel screen

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 409

app/components/remove_markdown.js
Latex in the root post is crashing the global threads screen
https://mattermost.atlassian.net/browse/MM-45404
```release-note
NONE
```
=> Fix for Latex in the root post is crashing global threads 

app/screens/gallery/footer/avatar/index.tsx
Fixes the border issue around the avatars in gallery view.
[MM-45336](https://mattermost.atlassian.net/browse/MM-45336)
- iPhone 13 / iOS 5.5 SIM
```release-note
```
=> [Gekidou] Avatar Border in Gallery View Fix

app/components/remove_markdown/index.tsx
Latex in the root post is crashing the global threads screen
https://mattermost.atlassian.net/browse/MM-45404
```release-note
NONE
```
=> [Gekidou MM-45404] Fix for Latex in the root post is crashing global threads 

app/products/calls/client/rest.ts, app/products/calls/store/actions/calls.ts, app/products/calls/store/types/calls.ts, types/modules/react-native-webrtc.d.ts
PR adds support for generating short-lived TURN credentials.
https://mattermost.atlassian.net/browse/MM-45001
https://github.com/mattermost/mattermost-plugin-calls/pull/116
```release-note
Added support for generating short-lived TURN credentials
```
=> [MM-45001] Add support for generating short-lived TURN credentials

app/queries/servers/thread.ts
Exclude already prepared threads.
```release-note
NONE
```
=> [Gekidou] Fix loading threads

app/products/calls/client/rest.ts, app/products/calls/store/actions/calls.ts, app/products/calls/store/types/calls.ts, types/modules/react-native-webrtc.d.ts
Cherry pick of #6404 on release-1.54.
```release-note
NONE
```
=> Automated cherry pick of #6404

android/app/src/main/java/com/mattermost/helpers/RealPathUtil.java, app/client/rest/files.ts, app/managers/draft_upload_manager/index.ts, app/utils/file/file_picker/index.ts, app/utils/file/index.ts
https://mattermost.atlassian.net/browse/MM-45011
```release-note
NONE
```
=> [Gekidou] Fix video uploads

app/database/operator/server_data_operator/handlers/category.ts, app/database/operator/server_data_operator/handlers/channel.ts, app/database/operator/server_data_operator/handlers/group.ts, app/database/operator/server_data_operator/handlers/post.ts, app/database/operator/server_data_operator/handlers/reaction.ts, app/database/operator/server_data_operator/handlers/team.ts, app/database/operator/server_data_operator/handlers/thread.ts, app/database/operator/server_data_operator/handlers/user.ts, app/hooks/navigation_button_pressed.tsx, docs/database/server/server.md
This PR aims to correct: 
1. obsolete `throws` comment in the various database handlers
2. fix ts typing for the useNavButtonPressed hook
3. add the missing relationship link between ThreadsInTeam and Thread tables.
```release-note
NONE
```
=> Gekidou Minor Fixes

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 412

app/components/profile_picture/image.tsx, app/components/profile_picture/index.tsx, app/screens/gallery/footer/details/index.tsx, app/screens/gallery/footer/footer.tsx, app/screens/gallery/lightbox_swipeout/index.tsx, app/screens/gallery/viewer/index.tsx, app/screens/user_profile/title/avatar.tsx, app/screens/user_profile/title/index.tsx, types/screens/gallery.d.ts
From the User profile screen we can now open the avatar in the gallery view. Feel free to push a commit if something needs addressing
```release-note
NONE
```
=> [Gekidou] Open User avatar in gallery

app/components/markdown/markdown_latex_block/index.tsx, app/components/post_draft/post_input/post_input.tsx, app/context/theme/index.tsx, app/screens/create_direct_message/user_list.tsx, app/screens/home/channel_list/categories_list/categories/body/category_body.tsx, app/screens/home/channel_list/categories_list/categories/unreads/index.ts, app/screens/latex/index.tsx, app/screens/settings/display_timezone/display_timezone.tsx, app/screens/settings/display_timezone_select/index.tsx, app/screens/settings/display_timezone_select/timezone_row.tsx, app/screens/user_profile/user_profile.tsx
Fixes various bugs, if anything feel free to push a commit into this PR
https://mattermost.atlassian.net/browse/MM-45621
https://mattermost.atlassian.net/browse/MM-45604
https://mattermost.atlassian.net/browse/MM-45591
https://mattermost.atlassian.net/browse/MM-45590
https://mattermost.atlassian.net/browse/MM-45589
https://mattermost.atlassian.net/browse/MM-45572
https://mattermost.atlassian.net/browse/MM-45549
https://mattermost.atlassian.net/browse/MM-45720
```release-note
NONE
```
=> Gekidou bugs fixes

app/screens/home/search/recent_searches/recent_item.tsx
Theme had to be removed as prop from the recent_item component.
```release-note
NONE
```
=> Gekidou - Fix recent item component

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 413

app/actions/remote/channel.ts, app/components/autocomplete/at_mention/index.ts, app/components/channel_actions/set_header_box/index.ts, app/components/markdown/at_mention/at_mention.tsx, app/components/post_draft/post_input/index.ts, app/components/post_list/combined_user_activity/index.ts, app/components/post_list/post/body/index.tsx, app/components/post_list/post/body/reactions/index.ts, app/components/post_list/post/index.ts, app/components/post_list/post/post.tsx, app/constants/events.ts, app/hooks/channel_switch.ts, app/queries/servers/role.ts, app/screens/channel/channel.tsx, app/screens/channel/header/index.ts, app/screens/find_channels/quick_options/index.ts, app/screens/home/channel_list/categories_list/header/index.ts, app/screens/post_options/index.ts
Result of the exploration on the performance when clicking a channel link from a different channel.
Not relevant performance improvement has been found, but the experience has been improved slightly, by making sure we change to the new channel as soon as we can, before loading the post (which will degrade the experience).
More comments in the code for each relevant change.
https://mattermost.atlassian.net/browse/MM-45483
```release-note
Minor tweaks on channel switch
```
=> Add minor fixes and performance improvements on channel switch

app/products/calls/connection.ts
- Fixing this in two ways: 
- Don't call `replaceTrack` if peer is destroyed. (could have done this in simple-peer, but didn't want to change that code--I'm not totally sure why he's throwing an error and not just doing a `if (this.destroying || this.destroyed) {` on line 368 of `simple-peer.ts`)
- Wrapping calls to `replaceTrack` in a try/catch just in case the error is coming from `sender` being destroyed.
- Unfortunately I can't think of a way to reproduce this and test, but the fix is pretty simple.
- I have added this to the v2 branch, no need for a separate PR there.
- https://mattermost.atlassian.net/browse/MM-44102
Example:
```release-note
Calls: Fix for crash on "cannot replaceTrack after peer is destroyed" error
```
=> MM-44102 - Fix for: Crash on peer destroyed error

package-lock.json, package.json
The network library has been updated to accomodate a fix for when rounding up numbers with different locale.  It can be found here:  https://github.com/mattermost/react-native-network-client/commit/c32749d6eb52ab577fa388ba4c7a0dfcacc6e9ff
```release-note
NONE
```
=> [Gekidou] Fix rounding numbers with different locale

app/actions/remote/post.ts, app/components/post_list/post/body/index.tsx, app/components/post_list/post/post.tsx, app/components/post_list/post_list.tsx, app/screens/permalink/index.ts, app/screens/permalink/permalink.tsx
This PR Fixes Permalink view for the replies when CRT is enabled.
https://mattermost.atlassian.net/browse/MM-40096
<table><tr><td>BEFORE <img src="https://user-images.githubusercontent.com/3680799/180081094-12bdc23e-4fc7-43fb-8a81-0e78ec2fcbd0.png" /></td><td>AFTER <img src="https://user-images.githubusercontent.com/3680799/180081102-29a13990-2f2f-4905-8423-4aa71bd58628.png" /></td></tr></table>
```release-note
NONE
```
=> [Gekidou MM-40096] Permalink view for replies when CRT is enabled

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 415

app/actions/remote/groups.ts, app/actions/websocket/group.ts, app/actions/websocket/index.ts, app/client/rest/groups.ts, app/constants/websocket.ts
Handles the `group_received` websocket event.
https://mattermost.atlassian.net/browse/MM-43772
- iPad Mini / iOS 15.5 [Device]
- Pixel 5 / API30 [SIM]
```release-note
```
=> [Gekidou] Handle Group Received WebSocket Event

android/app/src/main/java/com/mattermost/share/ShareModule.java
Cherry pick of #6324 on release-1.55.
/cc  @t0mm0
```release-note
NONE
```
=> Automated cherry pick of #6324

detox/e2e/support/ui/component/alert.ts, detox/e2e/test/threads/global_threads.e2e.ts
Misc maintenance:
- Fixed global threads and unarchive channel tests
NA
```release-note
NONE
```
=> Detox/E2E: Fix global threads and unarchive channel tests

app/mattermost.js, app/store/ephemeral_store.js
Cherry pick of #6503 on release-1.55.
/cc  @jpmastermind
```release-note
NONE
```
=> Automated cherry pick of #6503

app/screens/apps_form/apps_form_field.tsx
Cherry pick of #5640 on release-1.55.
/cc  @jfrerich
```release-note
NONE
```
=> Automated cherry pick of #5640

ios/Mattermost.xcodeproj/project.pbxproj, ios/Podfile.lock
=> fix podfile lock missing user-agent

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 417

app/screens/home/channel_list/categories_list/header/loading_unreads.tsx
=> Fix load channels animation

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  418

app/client/rest/channels.ts, app/mm-redux/actions/channels.test.js
Apply https://github.com/mattermost/mattermost-mobile/pull/6562 to V1
None
```release-note
Fix convert channel to private
```
=> Fix convert channel to private

app/actions/remote/entry/app.ts, app/database/manager/__mocks__/index.ts, app/database/manager/index.ts, app/utils/file/index.ts, app/utils/mattermost_managed.ts, app/utils/security.ts, ios/Mattermost/MattermostManaged.m
Fix MM-46309
https://mattermost.atlassian.net/browse/MM-46309
```release-note
NONE
```
=> Fix MM-46309

app/utils/file/index.ts
https://mattermost.atlassian.net/browse/MM-46438
```release-note
NONE
```
=> [Gekidou] Fix mimeType undefined in isImage utility

app/components/autocomplete_selector/autocomplete_selector.tsx, app/components/post_list/post/body/content/message_attachments/action_menu/action_menu.tsx, app/mm-redux/types/apps.ts, app/screens/apps_form/apps_form_field.tsx, app/screens/interactive_dialog/dialog_element.js
Cherry pick of #5398 on release-1.55.
```release-note
NONE
```
=> Automated cherry pick of #5398

app/client/rest/channels.ts, app/mm-redux/actions/channels.test.js
Cherry pick of #6568 on release-1.55.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #6568

detox/e2e/config.js, detox/e2e/custom_sequencer.js, detox/package-lock.json, detox/package.json
- Added custom test sequencer for parallel testing
https://mattermost.atlassian.net/browse/MM-41857
NA
```release-note
NONE
```
=> Detox/E2E: Add custom test sequencer

app/managers/global_event_handler.ts, app/utils/file/index.ts
https://mattermost.atlassian.net/browse/MM-46300
```release-note
NONE
```
=> MM-46300 Clear cached images on logout

app/actions/websocket/index.ts
I introduced a bug on my last fix regarding gql by asking for a field that was not yet implemented. This is fixed in this PR:
https://github.com/mattermost/mattermost-server/pull/20956#pullrequestreview-1098782699
On this PR we are making sure we add a fallback to the graphQL path on websocket reconnect, which was still missing.
None
```release-note
Fix missing messages bug on graphQL instances.
```
=> Add fallback to rest on websocket reconnect

app/screens/home/account/account.tsx, app/screens/home/account/components/options/index.tsx
This PR fixes the ScrollView on the account screen so that is scrollable on small screen devices.
https://mattermost.atlassian.net/browse/MM-46515
```release-note
NONE
```
=> [Gekidou] Fix account screen scrollable options

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 424

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to  425

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 426

app/actions/local/draft.ts, app/components/files/voice_recording_file.tsx, app/components/post_draft/draft_input/message_input.tsx, app/components/post_draft/draft_input/voice_input.tsx, app/components/post_draft/send_handler/send_handler.tsx, app/components/post_list/post/body/body.tsx, app/queries/servers/system.ts, types/api/config.d.ts
I tested the wiring using a proper recording from the library, and added some fixes and improvements.
None
```release-note
NONE
```
=> Improve wiring after test with the recording library

android/app/src/main/AndroidManifest.xml, ios/Podfile.lock, package-lock.json, package.json
=> [Voice message] add react-native-audio-recorder-player mp3 fork

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 428

detox/e2e/test/autocomplete/channel_mention.e2e.ts, detox/e2e/test/autocomplete/edit_channel_header.e2e.ts, detox/e2e/test/channels/create_direct_message.e2e.ts, detox/e2e/test/channels/favorite_and_unfavorite_channel.e2e.ts
Minor maintenance:
- Fixed verifications
- Added a step to post message on direct messages and updated associated Zephyr cases
NA
```release-note
NONE
```
=> Detox/E2E: Verification fixes and added a step to post message on direct messages

.circleci/config.yml, android/gradle.properties
=> CI Build fix

app/actions/remote/entry/common.ts, app/actions/remote/entry/gql_common.ts, app/actions/remote/session.ts, app/actions/remote/user.ts, app/managers/global_event_handler.ts
As reported during MatterCon, as the phone changes its timezone, the new timezone was not being automatically reflected.
https://mattermost.atlassian.net/browse/MM-47482
```release-note
NONE
```
=> [Gekidou] auto update timezone when device changes its location

app/screens/gallery/footer/footer.tsx, app/screens/gallery/header/index.tsx, app/screens/gallery/video_renderer/index.tsx
This PR fixes:
- the header and footer of the gallery view
- The downloading toast on videos that fail to playback
- The touch on video controls for android
https://mattermost.atlassian.net/browse/MM-47649
```release-note
NONE
```
=> Fix gallery header & footer as well as download video toast

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 429

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 430

android/gradle.properties, fastlane/Fastfile
Fixes Android release build
```release-note
NONE
```
=> [v1] fix Fastfile for android release

android/gradle.properties, fastlane/Fastfile
Cherry pick of #6725 on release-1.56.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6725

app/screens/home/channel_list/categories_list/__snapshots__/index.test.tsx.snap, app/screens/home/channel_list/categories_list/header/__snapshots__/header.test.tsx.snap, app/screens/home/channel_list/categories_list/header/header.tsx
Removes down arrow next to team name and removes feedback animation when tapping on the team name.
[MM-46991](https://mattermost.atlassian.net/browse/MM-46991)
- iPhone 14 Pro, iOS 16
- Pixel 5, Android 13
| iOS  |<img width="419" alt="image" src="https://user-images.githubusercontent.com/23694620/198710983-a7f66a89-1c6c-4477-bea6-749b857f10bd.png">|
|---|---|
| Android |<img width="402" alt="image" src="https://user-images.githubusercontent.com/23694620/198708943-4bd9fd23-1a56-4b94-84d3-71b0c0750d5c.png">| 
```release-note
NONE
```
=> [MM-46991] Remove Down Arrow Next to Team Name

app/components/post_list/thread_overview/__snapshots__/thread_overview.test.tsx.snap, app/constants/preferences.ts
https://mattermost.atlassian.net/browse/MM-46703
```release-note
NONE
```
=> Update denim theme link color

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=>  [Gekidou] Bump app build number to 432

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 433

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #6736 on release-1.56.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6736

app/components/team_sidebar/team_list/team_item/team_item.tsx
- Updates the theme color of the border used on the unread badge and mention badge
- Small tweak to the position of the unread badge
- Small tweak to the border radius on the selected team in the team sidebar
Fixes https://mattermost.atlassian.net/browse/MM-48199
This PR was tested on: iPhone 14 Simulator
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
```
=> [Gekidou MM-48199] Minor UI tweaks to team sidebar

app/actions/remote/preference.ts, app/actions/websocket/posts.ts
Remove todos that are no longer valid from the code.
https://mattermost.atlassian.net/browse/MM-43474
https://mattermost.atlassian.net/browse/MM-43472
```release-note
NONE
```
=> Remove no longer needed todos

README.md, app/constants/calls.ts, app/constants/view.js, fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/changelog
Reverts mattermost/mattermost-mobile#6701
=> Revert "Update ESR version"

app/components/post_list/more_messages/more_messages.tsx
Fixes the more messages bar to be shown in the correct position on iOS with and without insets.
https://mattermost.atlassian.net/browse/MM-45861
```release-note
NONE
```
=> [Gekidou] Fix more messages bar on iOS without insets

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 437

app/utils/sentry.ts
=> Check that Sentry is enabled and set

patches/react-native-notifications+4.3.3.patch
=> Fix iOS notifications patch

README.md
Update readme to reflect new version
```release-note
NONE
```
=> Update readme to reflect new version

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 439

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 440

app/screens/integration_selector/index.ts, app/screens/integration_selector/index.tsx, app/screens/integration_selector/integration_selector.tsx
Refactor multiselect code, moving observables to index and screen component code to its file. Using setstate function for muliselect data
```release-note
Refactor multiselect to remove useCallback deps. Moving observables to its own file
```
=> Refactor multiselect code

app/screens/integration_selector/index.ts, app/screens/integration_selector/integration_selector.tsx
Changes related to https://github.com/mattermost/mattermost-mobile/pull/6790 🤦 
```release-note
Refactor multi-select toggle selection and remove handling
```
=> Refactor using generic item toggleMap function

app/utils/file/index.ts
Address latest feedback
https://mattermost.atlassian.net/browse/MM-46309
```release-note
Address MM-46309
```
=> [MM-46320] Address feedback

app/screens/settings/about/about.tsx, app/screens/settings/about/learn_more.tsx, assets/base/config.json
This PR cleans up some unused local config variables, consolidate others and update a few values
https://mattermost.atlassian.net/browse/MM-48418
```release-note
NONE
```
=> Gekidou Clean up local config

app/screens/browse_channels/channel_list.tsx, app/screens/create_direct_message/create_direct_message.tsx
https://mattermost.atlassian.net/browse/MM-48369
```release-note
NONE
```
=> Fix the color for no results when there are no more channels to join

app/actions/local/team.ts, app/components/post_with_channel_info/channel_info/index.ts, app/components/team_sidebar/team_list/team_item/index.ts
https://mattermost.atlassian.net/browse/MM-48547
```release-note
NONE
```
@jgilliam17 adding you to verify the fix as you reported the bug
=> [MM-48547] Fix potential crash by accessing the team directly from another model

app/actions/remote/channel.ts, app/products/calls/actions/calls.ts, app/products/calls/alerts.ts, app/products/calls/observers/index.ts, app/products/calls/state/actions.test.ts, app/products/calls/state/actions.ts, app/products/calls/types/calls.ts, app/products/calls/utils.test.ts, app/screens/channel/channel.tsx, app/screens/channel/header/header.tsx, app/screens/channel/header/index.ts, app/screens/channel/index.tsx, app/screens/channel_info/channel_info.tsx, app/screens/channel_info/index.ts
- This PR addresses the move to GA requirements for mobile from https://docs.google.com/document/d/1Tr8OBH4nPSN3SIMXWKY-_TMV-C0ht5zxmc2rLthZlLA/edit .
- It requires a corresponding GA PR from the calls repo, which isn't submitted yet. But the changes here are backwards compatible.
- I've gone through all the test cases outlined this sheet (don't use the tables in the doc, the linking isn't working reliably): https://docs.google.com/spreadsheets/d/1aRc_zq2gaLLjTTx6ua1KwVfFRGD51xLYsNRRG5MUIH0/edit#gid=0 )
- There are three combinations of App (new x old) x Server (new x old), ignoring the case of App old - Server old. For each of those, you need to test x iOS & Android. For each cell in the test cases you have to test the expected outcome and the other possibilities (the negative outcomes). …
=> MM-48753 - Calls: GA requirements

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 441

app/components/server_user_list/index.tsx, app/screens/integration_selector/integration_selector.tsx
removing an element form the selected option list from the search bar wasn't removing them from the selection list below, this fixes it.
```release-note
Fix selected options to be removed when it's a user list selector
```
=> Fix multiselect on users list integration selector

fastlane/Fastfile
- Surround with double quotes so that `#{data_path}` is resolved
NA
```release-note
NONE
```
=> Fix fastlane simulator lane

app/components/markdown/markdown.tsx, app/components/post_list/post/body/message/message.tsx, app/components/remove_markdown/index.tsx, app/screens/global_threads/threads_list/thread/thread.tsx, app/utils/markdown/index.ts
https://mattermost.atlassian.net/browse/MM-48621
```release-note
NONE
```
=> Fix inline code blocks in thread preview

app/screens/home/search/search.tsx
https://mattermost.atlassian.net/browse/MM-48250
```release-note
NONE
```
=> Close autocomplete when search input is not in focus

app/components/search/index.tsx, app/screens/home/search/initial/initial.tsx, app/screens/home/search/initial/modifiers/index.tsx, app/screens/home/search/initial/modifiers/modifier.tsx, app/screens/home/search/search.tsx, patches/react-native-elements+3.4.2.patch
as summary
https://mattermost.atlassian.net/browse/MM-48050
```release-note
NONE
```
=> Place cursor position in between the phrase modifier

app/components/profile_picture/status.tsx, app/hooks/keyboard_tracking.ts
https://mattermost.atlassian.net/browse/MM-49012
https://mattermost.atlassian.net/browse/MM-48953
```release-note
NONE
```
=> Fix ios keyboard tracking and profile status theme

app/screens/home/search/initial/modifiers/modifier.tsx
https://mattermost.atlassian.net/browse/MM-48050
```release-note
NONE
```
=> Fix caret position on search phrase

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 443

package.json
=> remove unused scripts from package.json

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> [Gekidou] Bump app build number to 444

app/queries/servers/user.ts
https://github.com/mattermost/mattermost-mobile/pull/6578 added a workaround to fix an issue with scheme_admin. By looking at the code, the only possible issue I found is that we were observing the list and not observing with columns.
This should solve the issue.
https://mattermost.atlassian.net/browse/MM-46418
```release-note
Technical debt
```
=> Fix MM46418

app/queries/servers/thread.ts
Since the server returns all threads the user is following even when they left the channel, UI is displaying an unread indicator. This PR fixes the issue by querying the threads from the available/undeleted channel.
```release-note
NONE
```
=> Badges should include thread mentions from the undeleted channels

app/components/syntax_highlight/index.tsx
[Community convo](https://community.mattermost.com/core/pl/irrmb4e4ntyrjq84ay7mookkry)
```release-note
NONE
```
=> use correct syntax highlight styles for github code theme

app/queries/servers/system.ts, app/screens/home/channel_list/categories_list/categories/body/index.ts
https://mattermost.atlassian.net/browse/MM-49238
```release-note
NONE
```
=> Show the current channel when category is collapsed on tablets

app/components/markdown/markdown.tsx, app/components/markdown/markdown_table_cell/index.tsx, app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap, app/components/syntax_highlight/renderer.tsx, app/screens/code/index.tsx
Allow text to be selectable on tables when in full view. Also, added minor tweaks to improve the way it shows the table with inline images and latex.
https://mattermost.atlassian.net/browse/MM-45930
```release-note
You can now select text from tables when they are shown in full screen
```
=> Allow to select text from tables on full view

app/hooks/keyboard_tracking.ts
=> Fix race condition for keyboard tracker

app/components/markdown/markdown.tsx, app/components/markdown/markdown_latex_inline/index.tsx, app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap, app/screens/permalink/permalink_error.tsx, app/utils/markdown/index.ts
Align text with the latex.
https://mattermost.atlassian.net/browse/MM-45466
```release-note
Fix inline latex alignment
```
=> Align latex with text

android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java
For notifications, we are sending the override username directly in the sender_name field, but the override icon url was sent in the `override_icon_url` field. This PR takes account for that when showing the avatar.
https://mattermost.atlassian.net/browse/MM-38660
```release-note
Fix webhook notifications showing wrong avatar.
```
=> Fix webhook picture on notifications

app/actions/remote/notifications.ts, app/actions/websocket/index.ts, app/store/ephemeral_store.ts, ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift, ios/Mattermost/Info.plist, ios/Mattermost/Mattermost.entitlements, ios/NotificationService/NotificationService.swift
Adds profile images to the iOS push notifications
it also fixes an issue where the new line message indicator was being removed after bringing the app from the background by tapping a notification.
For production release the entitlement needs to be added to the profile
https://mattermost.atlassian.net/browse/MM-30348
```release-note
NONE
```
=> Notifications profile images

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  445

.solidarity
- Remove bundler check from solidarity file
NA
```release-note
NONE
```
=> Remove Bundler check from Solidarity

app/components/markdown/markdown.tsx, app/components/markdown/markdown_latex_inline/index.tsx, app/components/post_list/post/system_message/__snapshots__/system_message_helpers.test.js.snap, app/screens/permalink/permalink_error.tsx, app/utils/markdown/index.ts
This reverts commit 450b6e1a211b547c0ac764c90121ea924b4c1f20.
```release-note
NONE
```
=> Revert "Align latex with text (#6900)"

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  446

app/components/floating_text_input_label/index.tsx
https://mattermost.atlassian.net/browse/MM-49386
```release-note
NONE
```
=> Fix floating input style

app/components/common_post_options/copy_permalink_option/copy_permalink_option.tsx, app/components/common_post_options/follow_thread_option/follow_thread_option.tsx, app/components/common_post_options/reply_option.tsx, app/components/common_post_options/save_option.tsx, app/screens/post_options/options/app_bindings_post_option.tsx, app/screens/post_options/options/copy_text_option.tsx, app/screens/post_options/options/delete_post_option.tsx, app/screens/post_options/options/edit_option.tsx, app/screens/post_options/options/mark_unread_option/mark_unread_option.tsx, app/screens/post_options/options/pin_channel_option.tsx, app/screens/post_options/post_options.tsx, app/screens/post_options/reaction_bar/reaction_bar.tsx, app/screens/thread_options/options/mark_as_unread_option.tsx, app/screens/thread_options/options/open_in_channel_option.tsx, app/screens/thread_options/thread_options.tsx
When tapping in one of the options for the Post and Thread options screen, ensure the correct bottom sheet is being dismissed.
https://mattermost.atlassian.net/browse/MM-49421
```release-note
NONE
```
=> Dismiss correct bottom sheet screen for post / thread options

android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java, android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java, patches/react-native-navigation+7.30.6.patch
- Fixes the navigation library so that the app is sent to the background after using the back handler twice while in the home screen
- Fixes a crash when received a push notification and fails to retrieve the user avatar.
- Fixes a crash cause by react native screens (see https://github.com/software-mansion/react-native-screens#android)
https://mattermost.atlassian.net/browse/MM-45952
```release-note
NONE
```
=> Android Fixes

app/screens/settings/advanced/index.tsx, app/utils/file/index.ts, ios/Gekidou/Sources/Gekidou/FileCache.swift, ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift, ios/NotificationService/NotificationService.swift
This PR adds a cache for the profile images for the push notifications on iOS and fixes the delete cache in the advance settings
```release-note
NONE
```
=> Cache push notification profile image and add logs

app/actions/local/channel.ts, app/actions/websocket/channel.ts, app/actions/websocket/index.ts, app/actions/websocket/posts.ts, app/init/push_notifications.ts
Report here https://community.mattermost.com/core/pl/qbrdjmcojfb7droh77ysgxkfxa
```release-note
NONE
```
=> Preserve new message line on WS reconnect

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  447

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  448

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  449

app/constants/screens.ts, app/screens/navigation.ts, app/utils/theme/index.ts
=> Fix navigation theming

app/client/websocket/index.ts, app/components/connection_banner/connection_banner.tsx, app/managers/websocket_manager.ts
Cherry pick of #6948 on release-2.0.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #6948

app/components/markdown/markdown_code_block/index.tsx
Cherry pick of #6944 on release-2.0.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #6944

app/actions/remote/post.ts, app/managers/session_manager.ts, app/screens/navigation.ts
=> Fix some issues found by Sentry

app/utils/theme/index.ts
Cherry pick of #6959 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6959

app/actions/remote/post.ts, app/managers/session_manager.ts, app/screens/navigation.ts
Cherry pick of #6962 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6962

app/actions/websocket/posts.ts, app/actions/websocket/threads.ts
Cherry pick of #6960 on release-2.0.
```release-note
NONE
```
=> Automated cherry pick of #6960

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 451

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #6967 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6967

app/screens/home/search/initial/modifiers/modifier.tsx
https://mattermost.atlassian.net/browse/MM-49624
```release-note
NONE
```
=> Fix the caret position when using the search phrase modifier

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  452

app/screens/home/search/initial/modifiers/modifier.tsx
Cherry pick of #6972 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6972

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #6974 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #6974

app/screens/home/search/results/file_options/option_menus/option_menus.tsx
When a user performs a search and selects the open in channel option from the file menu options, dismiss the bottom sheet.
https://mattermost.atlassian.net/browse/MM-48282
```release-note
```
=> [MM-48282] When user selects open in channel, dismiss the bottom sheet

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  453

app/products/calls/components/calls_custom_message/calls_custom_message.tsx
- Show call thread title in root calls post
- https://mattermost.atlassian.net/browse/MM-49746
```release-note
Calls: Show the call thread in root calls posts.
```
=> MM-49746 - Calls: Show call thread title in root calls post

app/utils/deep_link/index.ts, app/utils/url/test.ts
https://mattermost.atlassian.net/browse/MM-49850
```release-note
Fixed opening a link when the server is hosted on a subpath.
```
=> Fix matchDeepLink when server is on a subpath

app/utils/deep_link/index.ts, app/utils/url/test.ts
Cherry pick of #7010 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7010

app/components/channel_item/index.ts, app/components/common_post_options/copy_permalink_option/index.tsx, app/components/common_post_options/follow_thread_option/index.ts, app/components/files/index.ts, app/components/post_draft/post_input/index.ts, app/components/post_draft/send_handler/index.ts, app/components/post_list/post/body/add_members/index.ts, app/components/post_list/post/body/content/embedded_bindings/button_binding/index.tsx, app/components/post_list/post/body/content/embedded_bindings/menu_binding/index.tsx, app/components/post_list/post/body/reactions/index.ts, app/components/post_list/post/footer/index.ts, app/components/post_list/post/header/index.ts, app/components/post_list/post/index.ts, app/components/post_list/post/system_message/index.tsx, app/components/post_with_channel_info/channel_info/index.ts, app/queries/servers/channel.ts, app/queries/servers/file.ts, app/queries/servers/reaction.ts, app/queries/servers/thread.ts, app/screens/channel/channel_post_list/intro/direct_channel/index.ts, app/screens/channel/channel_post_list/intro/direct_channel/member/index.ts, app/screens/channel_info/title/group_message/index.ts, app/screens/edit_post/index.tsx, app/screens/gallery/footer/index.ts, app/screens/permalink/index.ts, app/screens/post_options/index.ts, app/screens/reactions/index.ts, app/screens/thread_options/index.ts, share_extension/components/channel_item/index.ts
Cherry pick of #7028 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7028

android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java, android/app/src/main/java/com/mattermost/helpers/NotificationHelper.java, android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java
Cherry pick of #7029 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7029

android/app/src/main/java/com/mattermost/helpers/DatabaseHelper.kt
Cherry pick of #7027 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7027

.circleci/config.yml
=> Fix CI to include postinstall script of react-native-webrtc

.circleci/config.yml
Cherry pick of #7043 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7043

ios/Podfile.lock, package-lock.json, package.json
```release-note
Disable top domain level verification
```
=> disable top domain level verification

ios/Podfile.lock, package-lock.json, package.json
Cherry pick of #7045 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7045

ios/Gekidou/.swiftpm/xcode/xcshareddata/xcschemes/Gekidou.xcscheme, ios/Gekidou/Sources/Gekidou/FileCache.swift, ios/Gekidou/Sources/Gekidou/Keychain.swift, ios/Gekidou/Sources/Gekidou/Networking/PushNotification.swift, ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift, ios/Mattermost.xcodeproj/project.pbxproj, ios/MattermostShare/Extensions/Color.swift, ios/MattermostShare/ShareViewController.swift, ios/MattermostShare/ViewModels/ShareViewModel.swift, ios/MattermostShare/Views/ErrorViews/ErrorSharingView.swift, ios/MattermostShare/Views/InitialView.swift, ios/MattermostShare/Views/NavigationButtons/PostButton.swift, ios/NotificationService/NotificationService.swift
Cherry pick of #7032 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7032

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  454

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7042 on release-2.1.
/cc  @avinashlng1080
```release-note
NONE
```
=> Automated cherry pick of #7042

app/actions/websocket/index.ts, app/constants/websocket.ts
Plugin WS events that don't need to do any logic, but need to be handled. :-)
https://mattermost.atlassian.net/browse/MM-49006
```release-note
Handle Plugin related events
```
=> [MM-49006] Handle Plugin related events

app/screens/onboarding/index.tsx, app/screens/server/index.tsx
When the component mounts set the translation to 0 so that the forms moves to the correct position, in screens of the login flow that it was missing. This fixes the issue when users turn off animations in their device settings.
Related PR for the dot release submitted separately
```release-note
NONE
```
=> Fix the animation that occurs in login flow

app/screens/onboarding/index.tsx, app/screens/server/index.tsx
Cherry pick of #7054 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7054

app/actions/local/category.ts
Cherry pick of #7057 on release-2.1.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7057

app/actions/local/category.ts
Manual cherry pick of #7057 
```release-note
NONE
```
=> Fix add to default category code for dms and gms (#7057)

android/app/src/main/java/com/mattermost/helpers/BitmapCache.kt, android/app/src/main/java/com/mattermost/helpers/CustomPushNotificationHelper.java, android/app/src/main/java/com/mattermost/helpers/Network.java, android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java, android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java, android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java, app/init/push_notifications.ts, ios/Podfile.lock, package-lock.json, package.json
Cherry pick of #7059 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7059

app/actions/remote/channel.ts
Cherry pick of #7060 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7060

ios/Gekidou/Sources/Gekidou/Networking/Network.swift, ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Delegate.swift, ios/Gekidou/Sources/Gekidou/Networking/ShareExtension+Post.swift
Cherry pick of #7051 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7051

app/actions/remote/thread.ts, app/screens/global_threads/threads_list/index.ts
Cherry pick of #7082 on release-2.1.
```release-note
NONE
```
=> Automated cherry pick of #7082

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to  455

fastlane/Fastfile
=> Add set_app_version_build to Fastlane

fastlane/Fastfile
=> Replace package and imports for Kotlin files

fastlane/Fastfile
Cherry pick of #7090 on release-2.0.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7090

app/utils/server/index.ts
Remove mentions of Free OAuth since these services are restricted for some users.
Ref: https://github.com/mattermost/mattermost-mobile/pull/7009#issuecomment-1418615392
https://mattermost.atlassian.net/browse/MM-49868
```release-note
NONE
```
=> MM-49868: Remove mentions of Free OAuth in OpenID-Connect section

android/app/src/main/AndroidManifest.xml, android/app/src/unsigned/java/com/mattermost/flipper/ReactNativeFlipper.java
Fixes android 13 notification permission request and unsigned builds
```release-note
NONE
```
=> Android fix

android/app/src/main/AndroidManifest.xml, android/app/src/unsigned/java/com/mattermost/flipper/ReactNativeFlipper.java
Cherry pick of #7099 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7099

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 456

app/products/calls/rtcpeer/index.ts
- Port of fix from https://github.com/mattermost/mattermost-plugin-calls/pull/328
- Tested on iOS and Android
- https://mattermost.atlassian.net/browse/MM-50415
```release-note
NONE
```
=> MM-50415 - Fix addIceCandidate error due to potential race

ios/Mattermost/Modules/SplitViewModule.swift
Cherry pick of #7112 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7112

app/components/files/index.ts, app/queries/servers/system.test.ts, app/queries/servers/system.ts, app/screens/gallery/document_renderer/index.ts, app/screens/gallery/footer/index.ts, app/screens/home/search/results/file_options/option_menus/index.tsx, app/screens/home/search/results/index.tsx
Cherry pick of #7109 on release-2.1.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7109

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump version 2.1 build 457

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #7120 on release-2.1.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7120

app/components/touchable_emoji/index.tsx, app/components/touchable_emoji/skinned_emoji.tsx
https://mattermost.atlassian.net/browse/MM-50459
```release-note
Fixed applying the correct skin tone to emojis selected in the emoji picker
```
=> use the correct skin tone when selecting an emoji from the picker

app/actions/remote/session.ts, app/screens/forgot_password/index.tsx
- Users on both the Mattermost public version and beta version are receiving an error message: "Unable to reset your password". However, at least for the beta version, the email sends successfuly but the error is still shown. On the mobile web app version and on desktop, no issue is present.
- https://mattermost.atlassian.net/browse/MM-50501
This PR was tested on:  Realme 6 pro
https://user-images.githubusercontent.com/93595710/219104712-5a2205e9-7820-47e8-8e27-d0907279598b.mp4
```release-note
Fix "Unable to reset your password"
```
=> fix: reset password bug

app/screens/login/form.tsx, app/screens/login/index.tsx
https://mattermost.atlassian.net/browse/MM-45449
```release-note
NONE
```
=> allow scrolling in the login screen when keyboard is opened

app/screens/server/header.tsx, assets/base/i18n/en.json
Clarified onboarding text for new users.
https://mattermost.atlassian.net/browse/MM-46606
```release-note
NONE
```
=> Updated onboarding text

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 458

scripts/build.sh
Fixes #7150
```release-note
NONE
```
=> Fix local build

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump build number to 459
```release-note
NONE
```
=> Bump app build number to 459

app/screens/edit_profile/edit_profile.tsx
When editing the profile, now we trim the values so that there are no leading or trailing spaces.
https://mattermost.atlassian.net/browse/MM-50353
```release-note
NONE
```
=> ignore leading and trailing spaces when editing profile

app/screens/home/search/search.tsx
Listen to the "Enter" key of the hardware keyboard to trigger the search
https://mattermost.atlassian.net/browse/MM-48327
```release-note
NONE
```
=> trigger Search when hardware keyboard enter key is pressed

app/actions/remote/entry/common.ts, app/actions/websocket/index.ts
=> fix entry for tablets

app/components/selected_users/index.tsx, app/screens/create_direct_message/create_direct_message.tsx
https://mattermost.atlassian.net/browse/MM-47313
```release-note
NONE
```
=> Fix display name when open own DM

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump build number to 460
```release-note
NONE
```
=> Bump app build number to 460

app/components/team_sidebar/team_sidebar.tsx, app/screens/home/channel_list/categories_list/categories/body/index.ts, app/screens/home/channel_list/categories_list/categories/index.ts, app/screens/home/channel_list/categories_list/header/index.ts, app/screens/home/channel_list/categories_list/index.test.tsx, app/screens/home/channel_list/categories_list/index.tsx, app/screens/home/channel_list/channel_list.tsx, app/screens/home/channel_list/index.ts, app/utils/categories.ts
Fix performance issues introduced by #7170
Also fix the manual sort being reversed, introduced on the same PR
Also, piggybacked some minor performance improvements.
Fix #7186 
```release-note
Fix performance issue on team switch.
Minor performance improvements on team switch.
Fix channels being reversed on manually sorted categories.
```
=> Performance fixes and fix manual sort

ios/Podfile.lock
Adding missing podfile change directly into the release branch.
None
```release-note
None
```
=> [Release 2.2 cherrypick] Add missing podfile change

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Bump app version number to 2.2.0 and build number to 462
```release-note
NONE
```
=> Bump app version number to 2.2.0 and build number to 462

app/actions/remote/general.ts, app/actions/remote/post.ts, app/screens/home/tab_bar/home.tsx
Add debug logs for better understanding ongoing problems:
- Log the way we are "syncing" the badge on iOS for phantom notification issues.
- Log the error on post message (https://github.com/mattermost/mattermost-mobile/issues/7021)
- Log the error on server ping
```release-note
Add more information to the logs for better debugging.
```
=> Add debug logs

app/actions/remote/channel.ts, app/database/migration/server/index.ts, app/database/models/server/channel_info.ts, app/database/operator/server_data_operator/handlers/channel.ts, app/database/operator/server_data_operator/transformers/channel.test.ts, app/database/operator/server_data_operator/transformers/channel.ts, app/database/schema/server/index.ts, app/database/schema/server/table_schemas/channel_info.ts, app/database/schema/server/test.ts, app/queries/servers/channel.ts, app/utils/graphql.ts, docs/database/server/server.md, types/api/channels.d.ts, types/api/graphql.d.ts, types/database/models/servers/channel_info.ts, types/database/raw_values.d.ts
Add files_count column in ChannelInfo table and DB migration.
This is required for changes coming in this PR https://github.com/mattermost/mattermost-mobile/pull/7223
Fixes https://mattermost.atlassian.net/browse/MM-44655
This PR was tested on: Simulator iPhone 14, OS iOS 16.2
NA
```release-note
- Add files_count column in ChannelInfo table and DB migration
```
=> [MM-44655 ]: Add files_count column in ChannelInfo table and DB migration

app/components/channel_actions/manage_members_label/manage_members_label.tsx
Cherry pick of #7222 on release-2.3.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7222

app/init/launch.ts, app/init/push_notifications.ts, app/screens/in_app_notification/index.tsx, ios/Gekidou/Sources/Gekidou/Networking/Network+Users.swift, ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification+ProfileImage.swift, ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification.swift, ios/Gekidou/Sources/Gekidou/Storage/Database+Mentions.swift, ios/NotificationService/NotificationService.swift
Fix various sources of crashes when receiving push notifications on iOS
https://mattermost.atlassian.net/browse/MM-51580
https://mattermost.atlassian.net/browse/MM-51579
```release-note
NONE
```
=> Fix iOS Push notification crashes

ios/Mattermost/AppDelegate.mm
=> Enable flipper on iOS

app/components/markdown/markdown.tsx, app/components/markdown/markdown_image/index.tsx, app/components/markdown/markdown_table_image/index.tsx, app/components/post_list/post/body/content/image_preview/image_preview.tsx, app/components/post_list/post/body/content/image_preview/index.ts, app/components/post_list/post/body/content/index.tsx, app/components/post_list/post/body/content/message_attachments/attachment_fields.tsx, app/components/post_list/post/body/content/message_attachments/attachment_pretext.tsx, app/components/post_list/post/body/content/message_attachments/attachment_text.tsx, app/components/post_list/post/body/content/message_attachments/index.tsx, app/components/post_list/post/body/content/message_attachments/message_attachment.tsx, app/components/post_list/post/body/content/opengraph/opengraph.tsx, app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx, app/components/post_list/post/body/content/youtube/index.tsx, app/utils/images/index.ts, app/utils/url/index.ts, types/api/posts.d.ts
Handle undefined metadata all over the app
This is an extension of https://github.com/mattermost/mattermost-mobile/pull/7243
Partially fix https://mattermost.atlassian.net/browse/MM-51731
```release-note
Fix crash on markdown table images and prevents image related crashes on other parts of the app
```
=> Handle undefined metadata all over the app

app/components/markdown/markdown.tsx, app/components/markdown/markdown_image/index.tsx, app/components/markdown/markdown_table_image/index.tsx, app/components/post_list/post/body/content/image_preview/image_preview.tsx, app/components/post_list/post/body/content/image_preview/index.ts, app/components/post_list/post/body/content/index.tsx, app/components/post_list/post/body/content/message_attachments/attachment_fields.tsx, app/components/post_list/post/body/content/message_attachments/attachment_pretext.tsx, app/components/post_list/post/body/content/message_attachments/attachment_text.tsx, app/components/post_list/post/body/content/message_attachments/index.tsx, app/components/post_list/post/body/content/message_attachments/message_attachment.tsx, app/components/post_list/post/body/content/opengraph/opengraph.tsx, app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx, app/components/post_list/post/body/content/youtube/index.tsx, app/utils/images/index.ts, app/utils/url/index.ts, types/api/posts.d.ts
Cherry pick 720ac220704a49d878de633ef4a5efc77f44f88d
```release-note
NONE
```
=> Cherry pick - Handle undefined metadata all over the app (#7244)

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Bump mobile version to 2.3.0 and build number to 464
```release-note
NONE
```
=> Bump version to 2.3.0 and build number to 464

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick for 2.3.0 RC and beta 464
```release-note
NONE
```
=> Bump version to 2.3.0 and build number to 464 (#7256)

ios/Podfile.lock, package-lock.json, package.json
Cherry pick of #7249 on release-2.3.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7249

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 465

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7271 on release-2.3.
/cc  @m1lt0n
```release-note
NONE
```
=> Automated cherry pick of #7271

app/utils/file/file_picker/index.ts
Android 9 and below also require the write to storage permission in order to be able to save the photo/video being capture, this extra permission is not required for Android 10+
https://mattermost.atlassian.net/browse/MM-51766
```release-note
Fixed use camera to capture photo/video on Android 9 and below
```
=> Request missing write to storage permission to use the camera on Android 9 and below

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 468

app/actions/remote/post.ts
Cherry pick of #7323 on release-2.4.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7323

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump version 2.4.0 build 469

app/components/selected_users/index.tsx, app/screens/thread/thread.tsx, app/screens/thread/thread_follow_button/index.ts, app/screens/thread/thread_follow_button/thread_follow_button.tsx
Cherry pick of #7330 on release-2.4.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7330

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #7334 on release-2.4.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7334

app/components/autocomplete/slash_suggestion/slash_suggestion_item.tsx, app/components/emoji/emoji.tsx, app/components/markdown/markdown_image/index.tsx, app/components/markdown/markdown_table_image/index.tsx, app/components/profile_picture/image.tsx, app/components/progressive_image/index.tsx, app/components/progressive_image/thumbnail.tsx, app/screens/in_app_notification/icon.tsx, patches/react-native-fast-image+8.6.3.patch, types/components/emoji.ts
Cherry pick of #7329 on release-2.4.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7329

fastlane/Fastfile
https://mattermost.atlassian.net/browse/MM-52747
```release-note
NONE
```
=> Remove Fastlane message attachment icon

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 470

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7344 on release-2.4.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7344

ios/Gekidou/Sources/Gekidou/DataTypes/Post.swift
=> fix iOS messageSource Database Post model

app/components/channel_actions/manage_members_label/manage_members_label.tsx, app/components/user_list/index.tsx, app/constants/permissions.ts, app/screens/create_direct_message/create_direct_message.tsx, app/screens/manage_channel_members/manage_channel_members.tsx, app/screens/user_profile/user_profile.tsx, package-lock.json, package.json
Removed t function from the define Messages object and updated the mmjstool to the latest.
https://mattermost.atlassian.net/browse/MM-52748
none
none
```release-note
NONE
```
=> MM-52748 : Remove 't' functions for defineMessages in Mobile and update mmjstool version

app/components/option_item/index.tsx, app/products/calls/components/message_bar.tsx, app/screens/post_priority_picker/components/picker_option.tsx, app/screens/post_priority_picker/footer.tsx, app/screens/post_priority_picker/post_priority_picker.tsx, app/screens/post_priority_picker/utils.ts
The size of the elements on the post priority bottom sheet was not been calculated correctly. Removed the magic numbers and made sure everything was accounted for.
None
```release-note
NONE
```
=> Fix post priority bottom sheet

app/components/option_item/index.tsx, app/screens/post_priority_picker/components/picker_option.tsx, app/screens/post_priority_picker/footer.tsx, app/screens/post_priority_picker/post_priority_picker.tsx, app/screens/post_priority_picker/utils.ts
Cherry pick #7350 
```release-note
NONE
```
=> Cherry pick: Fix post priority bottom sheet (#7350)

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump app build number to 471
```release-note
None
```
=> Bump app build number to 471

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7353 on release-2.4.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7353

app/screens/manage_channel_members/index.tsx, app/screens/manage_channel_members/manage_channel_members.tsx, app/utils/user/index.ts
While dealing with https://mattermost.atlassian.net/browse/MM-50075, I discovered some other minor improvements on the manage members component. More details in comments.
Fix https://mattermost.atlassian.net/browse/MM-50075
Fix https://mattermost.atlassian.net/browse/MM-50037
```release-note
NONE
```
=> Improve manage members search

ios/Podfile.lock, package-lock.json
There seem to have been some minor changes not propagated to the .lock files, and were giving problems (at least on my environment). This seems to solve them.
None
```release-note
None
```
=> Update .lock files

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump app build number to 472
```release-note
NONE
```
=> Bump app build number to 472

app/actions/remote/user.ts
https://mattermost.atlassian.net/browse/MM-52987
```release-note
NONE
```
=> conditionally set the current user status

app/actions/local/user.ts, app/actions/websocket/index.ts, app/actions/websocket/users.ts, app/managers/websocket_manager.ts
Cherry pick of #7379 on release-2.5.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7379

app/screens/login/sso_options.tsx
https://mattermost.atlassian.net/browse/MM-52933
```release-note
Fixed duplicate text for SSO login method when only SSO is available
```
=> Remove double text for SSO login method

android/app/src/main/java/com/mattermost/helpers/push_notification/Post.kt, ios/Gekidou/Sources/Gekidou/DataTypes/Post.swift, ios/Gekidou/Sources/Gekidou/Networking/Network+Posts.swift, ios/Gekidou/Sources/Gekidou/Storage/Database+Posts.swift
Native code for fetching the usernames on post attachments.
Fix https://mattermost.atlassian.net/browse/MM-52937
```release-note
NONE
```
=> Native fetch users on attachments

app/screens/login/sso_options.tsx
Cherry pick of #7385 on release-2.5.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7385

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #7389 on release-2.5.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7389

app/components/post_list/post_list.tsx, app/screens/home/recent_mentions/recent_mentions.tsx, app/screens/home/saved_messages/saved_messages.tsx, app/screens/pinned_messages/pinned_messages.tsx, package-lock.json
Show the full image when scrolling in a channel / thread
https://mattermost.atlassian.net/browse/MM-53117
```release-note
NONE
```
=> Fix onViewableItemsChanged item id

app/components/post_list/post_list.tsx, app/screens/home/recent_mentions/recent_mentions.tsx, app/screens/home/saved_messages/saved_messages.tsx, app/screens/pinned_messages/pinned_messages.tsx, package-lock.json
Cherry pick of #7400 on release-2.5.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7400

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 475

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7402 on release-2.5.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7402

.github/workflows/github-release.yml
Fix working dir for release builds
```release-note
```
=> fix: fastlane working dir

.github/workflows/github-release.yml
Cherry pick of #7407 on release-2.5.
/cc  @toninis
```release-note
NONE
```
=> Automated cherry pick of #7407

.github/workflows/github-release.yml
Cherry pick of #7410 on release-2.5.
/cc  @toninis
```release-note
NONE
```
=> Automated cherry pick of #7410

.github/workflows/github-release.yml
=> set path and name for unsigned builds

.github/workflows/github-release.yml
Cherry pick of #7413 on release-2.5.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7413

app/components/files/image_file.tsx, app/components/progressive_image/index.tsx
Cherry pick of #7416 on release-2.5.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7416

app/init/push_notifications.ts
Cherry pick of #7417 on release-2.5.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7417

ios/Podfile.lock, package-lock.json, package.json
Bump react-native-network-client to 1.3.4
None
```release-note
NONE
```
=> Bump react-native-network-client to 1.3.4

ios/Podfile.lock, package-lock.json, package.json
Cherry pick of #7420 on release-2.5.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7420

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Bump build to 476 and version to 2.5.1
None
```release-note
NONE
```
=> Bump version to 2.5.1 build 476

fastlane/Fastfile
- Fixed iOS simulator download link
https://mattermost.atlassian.net/browse/CLD-5901
```release-note
NONE
```
=> CLD-5901 Fix: iOS simulator download link

android/app/src/main/java/com/mattermost/helpers/Network.java
Cherry pick of #7426 on release-2.6.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7426

app/actions/remote/notifications.ts, app/init/app.ts, app/init/launch.ts, app/screens/navigation.ts, app/store/ephemeral_store.ts, app/store/navigation_store.ts, index.ts
Cherry pick of #7405 on release-2.6.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7405

app/components/post_list/post/header/header.tsx, app/components/post_list/post/header/index.ts, app/components/post_list/post/header/tag/index.tsx, app/components/post_list/post/system_message/index.tsx, app/components/post_list/post/system_message/system_message.tsx, app/components/user_item/index.ts, app/components/user_item/user_item.tsx, app/screens/channel_info/title/direct_message/direct_message.tsx, app/screens/channel_info/title/direct_message/index.ts, app/screens/user_profile/index.ts, app/screens/user_profile/title/index.tsx, app/screens/user_profile/title/tag.tsx, app/screens/user_profile/user_profile.tsx, types/api/config.d.ts
Remove guest tags based on config
Fix https://mattermost.atlassian.net/browse/MM-53248
```release-note
Remove guest tags based on server configuration
```
=> Remove guest tags based on config

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump version to 2.6.0 and build to 477

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #7436 on release-2.6.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7436

android/app/src/main/java/com/mattermost/rnbeta/MattermostManagedModule.java, app/managers/session_manager.ts, app/utils/mattermost_managed.ts, ios/Gekidou/Sources/Gekidou/Keychain.swift, ios/GekidouWrapper.swift, ios/Mattermost/MattermostManaged.m
Cherry pick of #7412 on release-2.6.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7412

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 478

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7441 on release-2.6.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7441

app/actions/local/systems.ts, package-lock.json, patches/@nozbe+watermelondb+0.26.0.patch
It looks like in time as the database gets populated the app becomes sluggish, so the strategy here is to clean up the database with messages that are older than 14 days and perform a database [vacuum](https://www.sqlite.org/lang_vacuum.html)
https://mattermost.atlassian.net/browse/MM-51338
```release-note
NONE
```
=> 14 day data cleanup and vacuum

app/components/user_item/user_item.tsx, app/screens/reactions/reactors_list/reactor/reactor.tsx, app/utils/user/index.ts
Cherry pick of #7448 on release-2.6.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7448

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 479

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7451 on release-2.6.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7451

app/actions/remote/search.ts, app/client/rest/posts.ts, app/components/markdown/transform.ts, app/components/post_with_channel_info/post_with_channel_info.tsx, app/screens/home/search/results/post_results.tsx, app/screens/home/search/results/results.tsx, app/screens/home/search/search.tsx, app/utils/markdown/index.ts, types/api/posts.d.ts, types/api/search.d.ts
Searching posts will now match the search done in the webapp and highlights the words that match
https://mattermost.atlassian.net/browse/MM-44517
https://mattermost.atlassian.net/browse/MM-52670
```release-note
Fixed search results to match the webapp.
Added results highlight that matches the words being searched.
```
=> match desktop search and highlight results

app/screens/index.tsx, app/screens/join_team/join_team.tsx, app/screens/select_team/select_team.tsx
When joining a team or when listing available teams now we remove those teams that are archived from the list.
https://mattermost.atlassian.net/browse/MM-52997
```release-note
NONE
```
=> Do not show archived teams when browsing available teams

app/screens/settings/display_theme/custom_theme.tsx, app/screens/settings/display_theme/display_theme.tsx
Cherry pick of #7470 on release-2.7.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7470

app/screens/home/search/search.tsx
Cherry pick of #7465 on release-2.7.
/cc  @namanh-asher
```release-note
NONE
```
=> Automated cherry pick of #7465

app/actions/remote/channel.ts, app/actions/remote/preference.ts, app/actions/remote/user.ts, app/actions/websocket/index.ts, app/actions/websocket/posts.ts, app/components/channel_icon/dm_avatar/dm_avatar.tsx, app/components/channel_icon/dm_avatar/index.ts, app/queries/servers/channel.ts, app/queries/servers/user.ts, app/screens/home/channel_list/categories_list/categories/body/index.ts, app/utils/categories.ts
This PR fix some inconsistencies with the Browser way of showing DMs:
- Archived channels not properly being hidden
- Opened channels without messages not properly being shown
- Unavailable users on the database not being fetched from the server (and therefore, not being filtered out if needed)
Fix https://mattermost.atlassian.net/browse/MM-49935
Fix https://mattermost.atlassian.net/browse/MM-53024
Fix https://mattermost.atlassian.net/browse/MM-51530
```release-note
Remove some inconsistencies in the way DMs are shown in the sidebar between Mobile and Browser.
```
=> Fix DMs in sidebar

app/components/autocomplete/at_mention/at_mention.tsx, app/constants/autocomplete.ts, app/screens/home/search/results/post_results.tsx
- When typing user name in "Search messages & files", pressing space will not show the user list name anymore. Hence cannot search the user we want.
This PR was tested on:  ios and android.
Before fix, cannot search "Adam Caskey" and "le minh son" when pressing space.
https://github.com/mattermost/mattermost-mobile/assets/39702132/91198c0a-78c8-4632-9ec5-bff91ad9e7f8
After fix, pressing space will allow user to continue to search
https://github.com/mattermost/mattermost-mobile/assets/39702132/0f67f7e0-04ee-496f-8a25-e41fe1e78833
```release-note
Fix cannnot search user when pressing space
```
=> Fix cannot search user when pressing space

app/screens/home/search/results/post_results.tsx, app/utils/markdown/index.ts, ios/Podfile.lock, package-lock.json, package.json
Jira Ticket: https://mattermost.atlassian.net/browse/MM-53964
```release-note
NONE
```
=> update network library

app/screens/home/search/results/post_results.tsx, app/utils/markdown/index.ts, ios/Podfile.lock, package-lock.json, package.json
Cherry pick of #7493 on release-2.7.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7493

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 481

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7496 on release-2.7.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7496

app/components/autocomplete/at_mention/at_mention.tsx, app/constants/autocomplete.ts, app/screens/home/search/results/post_results.tsx
Cherry pick of #7486 on release-2.7.
/cc  @hpkhanh1610
```release-note
NONE
```
=> Automated cherry pick of #7486

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 482

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7503 on release-2.7.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7503

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump version to 2.8.0 and build to 483

app/actions/remote/post.ts, app/helpers/database/index.ts, app/screens/permalink/permalink.tsx
Cherry pick of #7531 on release-2.8.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7531

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 484

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7536 on release-2.8.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7536

ios/Podfile.lock, package-lock.json, package.json
Fixes iOS network requests not completing by an error introduced in https://github.com/mattermost/mattermost-mobile/pull/7533
```release-note
NONE
```
=> fix ios network requests

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 485

app/init/launch.ts, app/managers/global_event_handler.ts, app/screens/home/index.tsx, app/utils/deep_link/index.ts, app/utils/general/index.ts, app/utils/server/server.test.ts, assets/base/i18n/en.json, test/intl-test-helper.tsx
When a deeplink is invalid, show an alert
https://mattermost.atlassian.net/browse/MM-53902
```release-note
Added an alert when a deeplink is invalid
```
=> Add alert when deeplink is invalid

app/screens/mfa/index.tsx
Fix error display on MFA screen
https://mattermost.atlassian.net/browse/MM-54448
```release-note
Fix display error on MFA screen.
```
=> MFA error display

app/init/launch.ts, app/managers/global_event_handler.ts, app/screens/home/index.tsx, app/utils/deep_link/index.ts, app/utils/general/index.ts, app/utils/server/server.test.ts, assets/base/i18n/en.json, test/intl-test-helper.tsx
Cherry pick of #7538 on release-2.8.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7538

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
=> Bump app build number to 487

patches/react-native-navigation+7.37.0.patch
Cherry pick of #7557 on release-2.9.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #7557

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7570 on release-2.9.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7570

app/screens/settings/settings.tsx
Fixes https://github.com/mattermost/mattermost/issues/24113
This PR was tested on:  Pixel3a, Android 13 
NONE
```release-note
```
=> Mm 28872 configure links

app/components/tutorial_highlight/index.tsx, app/components/user_item/user_item.tsx, app/components/user_list/__snapshots__/index.test.tsx.snap, app/components/user_list_row/index.tsx, app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
Fix race condition when showing the tutorials for user lists and server list
Jira ticket: https://mattermost.atlassian.net/browse/MM-54575
```release-note
Fixed the app becoming unresponsive when a tutorial for the user or server list is partially showed
```
=> Fix race condition when showing the turorial

app/actions/local/thread.ts
Cherry pick of #7598 on release-2.10.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7598

app/components/tutorial_highlight/index.tsx, app/components/user_item/user_item.tsx, app/components/user_list/__snapshots__/index.test.tsx.snap, app/components/user_list_row/index.tsx, app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
Cherry pick of #7599 on release-2.10.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7599

NOTICE.txt
Cherry pick of #7607 on release-2.10.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #7607

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
=> Bump to version 2.10.0 build 490

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #7621 on release-2.10.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7621

ios/Podfile.lock, package-lock.json, package.json, patches/react-native-notifications+5.1.0.patch
(Still testing, pushing to discuss the solution)
Apparently, one of the patches was creating the notifications in a wrong way (as activity instead of as proper pending intent?).
Looking at the blame, it seems that the issue was about background notifications, that seem to be working fine with this change.
Also, updated the library since it is supposed to fix a few related things.
Fix https://mattermost.atlassian.net/browse/MM-54406
```release-note
Android: Fix issue where notifications don't open or open the wrong channel
```
=> Fix notifications not opening or going to the wrong channel on Android

app/components/markdown/markdown.tsx, app/components/markdown/markdown_link/markdown_link.tsx, app/screens/channel_info/extra/extra.tsx, assets/base/i18n/en.json
This PR adds the feature to copy channel header text.
Fixes https://github.com/mattermost/mattermost/issues/24613
This PR was tested on:  Android 12
```release-note
Implemented copy channel header text functionality.
```
=> copy header text in channel info implemented

app/screens/home/channel_list/categories_list/header/plus_menu/item.tsx
Fixed bug where icons were missing in plus menu
https://mattermost.atlassian.net/browse/MM-55186
This PR was tested on: iPhone emulator
```release-note
None
```
=> Fixed bug where icons were missing in plus menu

app/components/post_list/combined_user_activity/combined_user_activity.tsx, app/components/post_list/combined_user_activity/index.ts
There has been errors reported about a crash on `generateCombinedPost`. The only reason for this to happen is that the request to `queryPostsById` returns an empty list. I foresee two possible situations here:
- A malformed combined activity post (which should not happen, since we create them)
- Missing post in the database when the component is rendered (which should not happen, since at least the base post from where this was created should exist)
Either way, I added some defensive code that should work until the state gets back to normal.
I tested this by adding rubbish to the post ids in code, which made the post list render correctly, with the combined activity posts missing.
Fix https://mattermost.atlassian.net/browse/MM-54534
Fix …
=> MM-54534 Fix error around combined user activity

package-lock.json, package.json
Update `commonmark-react-renderer` package to the latest version. This will fix the following issues:
- Show LaTex in the "Channels" view
- Avoid error when clicking on "Threads" when a message contains LaTex
- Show the max nodes warning for messages with too many nodes
https://mattermost.atlassian.net/browse/MM-54936
Fixes https://github.com/mattermost/mattermost/issues/24982
This PR was tested on: IPhone SE, iOS 16.2
|  before  |  after  |
|----|----|
| <img width="311" alt="Screenshot 2023-10-24 at 22 58 50" src="https://github.com/mattermost/commonmark-react-renderer/assets/17082165/873352ae-0728-4e77-a22e-40ed2ef85424"> | <img width="321" alt="Screenshot 2023-10-24 at 22 59 50" src="https://github.com/mattermost/commonmark-react-renderer/assets/17082165/45c5ecbf-b528-4255-80ad-96b661e …
=> MM-54936 fix: render latex in messages

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Bump build and version number to 2.9.1 (491)
NONE
```release-note
NONE
```
=> Bump build and version number to 2.9.1 (491)

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump app build number to 492
NONE
```release-note
NONE
```
=> Bump app build number to 492

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump app build number to 493
```release-note
NONE
```
=> Bump app build number to 493

app/screens/server/index.tsx
Cherry pick of #7661 on release-2.11.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7661

app/components/post_list/more_messages/more_messages.tsx, app/products/calls/hooks.ts, app/screens/channel_info/options/auto_follow_threads/auto_follow_threads.tsx, app/screens/channel_info/options/ignore_mentions/ignore_mentions.tsx, assets/base/i18n/en.json, package-lock.json, package.json
Some minor maintenance fixes:
- Fix imports to remove `@app/`
- Update the mmjstool to accept `defineMessage`
- Run `i18n-extract` for missing strings
- (Piggyback) Remove the `t` function from some files
NONE
```release-note
NONE
```
=> Maintenance fixes

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Bump version to 2.11.0 and build number to 494
```release-note
NONE
```
=> Bump build main 494 and v2.11.0

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Manual cherry-pick of PR #7668
```release-note
NONE
```
=> Manual cherrypick of PR #7668

app/components/markdown/at_mention/at_mention.tsx, app/components/remove_markdown/at_mention/at_mention.tsx, app/components/remove_markdown/at_mention/index.ts, app/components/remove_markdown/index.tsx, app/hooks/markdown.ts
At mentions were not showing in `RemoveMarkdown` renderer. This PR makes them visible as the design.
https://mattermost.atlassian.net/browse/MM-55265
```release-note
Fix mentions not appearing in the global thread view.
```
=> Show at mentions in RemoveMarkdown renderer

.github/workflows/ci.yml
- This will make the CI run and report results on branches -- previously it was only run on PRs.
- https://mattermost.atlassian.net/browse/MM-55592
```release-note
NONE
```
=> MM-55592 - Add ci checks to main and release branches

app/products/calls/connection/connection.ts, app/products/calls/connection/websocket_client.ts
- Improve logging:
- namespace the logs from calls consistently
- add logging for signalling messages
- add logging for ice candidates
- https://mattermost.atlassian.net/browse/MM-54351
```release-note
NONE
```
=> MM-54351 - Calls: Improve logging

app/constants/server_errors.ts, app/screens/convert_gm_to_channel/convert_gm_to_channel_form/convert_gm_to_channel_form.tsx
Displayed channel name related errors with name field.
Fixes https://mattermost.atlassian.net/browse/MM-55460
This PR was tested on: iPhone 15 on emulator with XCode 15.
```release-note
none
```
=> Displayed channel related error with name field

app/actions/remote/reactions.ts, app/components/post_list/post/body/reactions/reactions.tsx, app/screens/post_options/reaction_bar/reaction_bar.tsx
- Enable toggling of emoji in Quick Reaction and Emoji Picker(currently only supports adding)
This feature is already implemented in the web app version. I've added the mobile version.
https://github.com/mattermost/mattermost/issues/19818
Jira https://mattermost.atlassian.net/browse/MM-42586
- Android: 14, Pixel 3a
- iOS: 15.5, iPhone 8
https://github.com/mattermost/mattermost-mobile/assets/59413880/d061262d-d0f5-4e82-9895-5519970dd7ba
https://github.com/mattermost/mattermost-mobile/assets/59413880/e8308d81-1f28-4f50-856e-cb698cd9abae
```release-note
Enable toggling of emoji in Quick Reaction and Emoji Picker(currently only supports adding)
```
=> [MM-42586] Reaction toggle behavior

app/actions/local/category.test.ts, app/actions/local/category.ts
Added the important test for managing GM conversion action.
Fixes https://mattermost.atlassian.net/browse/MM-55628
```release-note
none
```
=> Added one important test

app/managers/session_manager.ts
When we call logout several times (mainly when we enter the app and several "logout if needed" functions are executed at the same time) we had an issue with the theme being undefined in the server screen.
This makes so only one onlogout process can be running for each server at the same time.
FIX https://mattermost.atlassian.net/browse/MM-54710
FIX https://github.com/mattermost/mattermost-mobile/issues/7577
```release-note
Fix "Cannot read property 'centerChannelColor' of undefined" issue
```
=> Fix issue when logout is called several times for the same server

app/actions/remote/command.ts, app/components/markdown/markdown_link/markdown_link.tsx, app/utils/deep_link/index.ts, app/utils/url/path.ts, app/utils/url/test.ts, package-lock.json, package.json, types/launch/index.ts
Manual cherry pick of #7613 onto `release-2.11`
```release-note
NONE
```
=> MM-53902: deep link validation

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump build 497
NB: I'm having trouble running Fastlane on my machine, so i replicated the changes from PR https://github.com/mattermost/mattermost-mobile/pull/7687 (this will soon not be an issue anymore, when we implement the fastlane automation using [this PR](https://github.com/mattermost/mattermost-mobile/pull/7685) as a base)
```release-note
NONE
```
=> Bump build 497

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Manual cherrypick of https://github.com/mattermost/mattermost-mobile/pull/7692
```release-note
NONE
```
=> Cherrypick bump build 497 for 2.11

android/app/build.gradle, android/app/src/main/java/com/mattermost/rnbeta/FoldableObserver.kt, android/app/src/main/java/com/mattermost/rnbeta/MainActivity.java, android/app/src/main/java/com/mattermost/rnbeta/SplitViewModule.kt, app/actions/local/channel.ts, app/actions/local/thread.ts, app/actions/remote/channel.ts, app/actions/remote/entry/common.ts, app/actions/remote/team.ts, app/actions/websocket/index.ts, app/actions/websocket/posts.ts, app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx, app/components/threads_button/__snapshots__/threads_button.test.tsx.snap, app/constants/device.ts, app/context/device/index.test.tsx, app/context/device/index.tsx, app/database/components/index.tsx, app/hooks/device.ts, app/init/push_notifications.ts, app/managers/analytics.ts, app/products/calls/components/audio_device_button.tsx, app/products/calls/screens/call_screen/call_screen.tsx, app/screens/navigation.ts, app/utils/helpers.ts, ios/Mattermost/Modules/SplitViewModule.m, ios/Mattermost/Modules/SplitViewModule.swift, test/setup.ts, types/global/device.d.ts
Fixes the layout for Android tablets and foldables assigning the correct values for isTablet and isSplitView by following this guide https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes
also moved the native function to be synchronous instead of async
https://mattermost.atlassian.net/browse/MM-55621
```release-note
NONE
```
=> MM-55621 fix layout for tablets and foldables

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Bump app build number to 498
NB: I'm having trouble running Fastlane on my machine, so i replicated the changes from PR https://github.com/mattermost/mattermost-mobile/pull/7687 (this will soon not be an issue anymore, when we implement the fastlane automation using [this PR](https://github.com/mattermost/mattermost-mobile/pull/7685) as a base)
```release-note
NONE
```
=> Bump build version to 498

app/components/user_list/__snapshots__/index.test.tsx.snap, app/components/user_list_row/index.tsx, app/screens/home/channel_list/servers/servers_list/server_item/server_item.tsx
https://mattermost.atlassian.net/browse/MM-54575
```release-note
Fixed display of tutorials for the servers and user list when used for the first time
```
=> MM-54575 fix server & user list tutorials

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package.json
Cherry pick of #7705 on release-2.12.
/cc  @mvitale1989
```release-note
NONE
```
=> Automated cherry pick of #7705

scripts/bump.sh
While testing the various use cases for the `bump.sh` script in automation, I found a couple of issues with them.
https://mattermost.atlassian.net/browse/CLD-6707
```release-note
NONE
```
=> CLD-6707 Followup fixes

.github/workflows/build-pr.yml
Currently when we added the label `Build Apps for PR` mattermod picked this up and created the related branches .  
Related core [here](https://github.com/mattermost/mattermost-mattermod/blob/master/server/build_apps.go) . 
We will remove the related code which was used for mobile and desktop repositories in favor of the labeled pull request event. 
- Introduced two new labels `Build App for Android` and `Build App for iOS` for separate on demand builds
- Check status will be generated as before on the PR level
https://mattermost.atlassian.net/browse/CLD-5751
```release-note
NONE
```
=> feat: Enable true labeled trigger and deprecate mattermod

fastlane/Pluginfile
Cherry pick of #7740 on release-2.11.
/cc  @mvitale1989
```release-note
NONE
```
=> Automated cherry pick of #7740

app/components/syntax_highlight/index.tsx
Cherry pick of #7729 on release-2.13.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7729

app/screens/settings/display_theme/display_theme.tsx, package-lock.json
Fixes the selection of the previous custom theme
https://mattermost.atlassian.net/browse/MM-56542
```release-note
Fixed selection of custom theme
```
```
=> MM-56542 fix custom theme selection

app/screens/settings/display_theme/display_theme.tsx, package-lock.json
Cherry pick of #7762 on release-2.13.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7762

app/actions/remote/preference.ts
Updates user preferences in chunks of 100.
Fixes https://mattermost.atlassian.net/browse/MM-56085
```release-note
None
```
=> MM-56085 - Add paging for preferences

app/screens/login/index.tsx, app/screens/onboarding/index.tsx, app/screens/server/index.tsx, patches/@gorhom+bottom-sheet+4.5.1.patch
Cherry pick of #7786 on release-2.12.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7786

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7788 on release-2.13.
```release-note
NONE
```
=> Automated cherry pick of #7788

ios/Mattermost/Info.plist
Cherry pick of #7801 on release-2.12.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7801

app/constants/permissions.ts, assets/base/i18n/en.json, ios/Mattermost/Info.plist
Update iOS permissions texts to comply with the requirements.
https://mattermost.atlassian.net/browse/MM-56724
```release-note
Update purpose message for permissions in iOS
```
=> Update iOS permissions texts

app/screens/home/channel_list/servers/index.tsx
Cherry pick of #7795 on release-2.13.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7795

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #7870 on release-2.15.
```release-note
NONE
```
=> Automated cherry pick of #7870

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist
Cherry pick of #7877 on release-2.15.
```release-note
NONE
```
=> Automated cherry pick of #7877

ios/NotificationService/PrivacyInfo.xcprivacy, ios/PrivacyInfo.xcprivacy
Add missing privacy requirements for iOS
Fix https://mattermost.atlassian.net/browse/MM-57768
```release-note
NONE
```
=> Add missing privacy requirements

ios/NotificationService/PrivacyInfo.xcprivacy, ios/PrivacyInfo.xcprivacy
Cherry pick of #7902 on release-2.16.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7902

app/screens/manage_channel_members/manage_channel_members.tsx
Fix mattermost issue when typing quickly within search input
I noticed that when scrolling on the channel members list, all the users where not fully loaded but stuck by the limit of the `PER_PAGE_DEFAULT` variable.
I added the logic to load more users when reaching the bottom of the list. 
This PR was tested on: iPhone 15 & Android Pixel 3A API 34
```release-note
Fix: Channel members list not fully loaded
```
=> Fix channel members list not fully loaded

app/screens/manage_channel_members/manage_channel_members.tsx
Cherry pick of #7896 on release-2.16.
/cc  @Pkarle
```release-note
NONE
```
=> Automated cherry pick of #7896

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Manual cherrypick of PR #7915
None
```release-note
NONE
```
=> Manual cherrypick of PR #7915

app/components/post_list/more_messages/more_messages.tsx
Fix more messages style to cover the whole screen.
Not sure what changed that made this change necessary, but this should fix the issue.
Fix https://mattermost.atlassian.net/browse/MM-58107
```release-note
NONE
```
Fixes a regression that should have not make it to any release
=> Fix more messages style

app/products/calls/actions/calls.ts, app/products/calls/client/rest.ts, app/products/calls/screens/participants_list/index.ts, app/products/calls/screens/participants_list/participants_list.tsx, assets/base/i18n/en.json
Cherry pick of #7945 on release-2.17.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #7945

README.md, fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/changelog
Cherry pick of #7946 on release-2.17.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #7946

app/components/profile_picture/image.tsx, app/screens/edit_profile/components/edit_profile_picture.tsx, package-lock.json
Cherry pick of #7978 on release-2.17.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7978

app/components/autocomplete/at_mention/at_mention.tsx
Cherry pick of #7980 on release-2.17.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7980

app/screens/bottom_sheet/index.tsx, app/screens/emoji_picker/index.tsx, app/screens/post_priority_picker/footer.tsx, app/screens/post_priority_picker/post_priority_picker.test.tsx, test/setup.ts
Cherry pick of #7966 on release-2.18.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7966

ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m, ios/Mattermost/SDWebImageDownloaderOperation+Swizzle.m
replace swizzle method_exchangeImplementations with method_setImplementation
```release-note
NONE
```
=> T264: Do not use method swizzling in Objective-C

ios/Mattermost/RNNotificationEventHandler+HandleReplyAction.m, ios/Mattermost/SDWebImageDownloaderOperation+Swizzle.m
Cherry pick of #7991 on release-2.18.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7991

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/data_extraction_rules.xml, patches/react-native-exception-handler+2.10.10.patch, patches/react-native-notifications+5.1.0.patch
Cherry pick of #7990 on release-2.18.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #7990

.github/workflows/compatibility-matrix-testing.yml, .github/workflows/e2e-detox-pr.yml, .github/workflows/e2e-detox-release.yml, .github/workflows/e2e-detox-scheduled.yml, .github/workflows/e2e-detox-template.yml, detox/utils/report.js
- Remove ios build out of the template 
```release-note
NONE
```
=> fix: Remove mobile builds out of the template

app/utils/buttonStyles.test.ts, app/utils/buttonStyles.ts, app/utils/categories.test.ts, app/utils/categories.ts
Started to add unit tests to the utils folder for the effort to increase the overall tests coverage for the entire app to 80%
```release-note
NONE
```
=> Add unit tests to Utils buttonStyles and categories

README.md
Cherry pick of #7996 on release-2.18.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #7996

app/actions/remote/entry/common.ts, app/actions/websocket/index.ts, app/client/websocket/index.ts, app/managers/websocket_manager.ts, app/queries/servers/entry.ts, app/queries/servers/system.ts
Cherry pick of #7976 on release-2.18.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #7976

.github/actions/prepare-mobile-build/action.yaml, .github/workflows/github-release.yml
- Upgrade download artifacts code to fix missing package
- Adapted the code to the new version 
- Upgrade some other reusable actions 
https://mattermost.atlassian.net/browse/CLD-7914
```release-note
NONE
```
=> fix: Upgrade packages to fix broken release

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #8023 on release-2.18.
```release-note
NONE
```
=> Automated cherry pick of #8023

android/app/src/main/java/com/mattermost/helpers/RandomId.kt, app/components/formatted_text/index.tsx, app/utils/general/index.ts, ios/Gekidou/Sources/Gekidou/Storage/Database.swift, ios/Podfile.lock, package-lock.json, package.json, test/test_helper.ts
Use the UUID native functions to generate UUIDs.
Fix https://mattermost.atlassian.net/browse/MM-58743
```release-note
Improve how we generate UUIDs
```
=> Use UUID native functions

ios/Podfile.lock, package-lock.json, package.json, patches/react-native-navigation+7.40.0.patch
Fix share by updating the react native navigation library and patches from main.
NONE
```release-note
Fix crash that happened when sharing a file
```
=> Fix share by updating the react native nagivation patches

app/components/threads_button/__snapshots__/threads_button.test.tsx.snap, app/utils/apps.test.ts, app/utils/apps.ts, app/utils/font_family.test.ts, app/utils/font_family.ts, app/utils/groups.test.ts, app/utils/helpers.test.ts, app/utils/helpers.ts, app/utils/integrations.test.ts, app/utils/key_mirror.test.ts, app/utils/log.test.ts, app/utils/mattermost_managed.test.ts, app/utils/message_attachment_colors.test.ts, app/utils/mix.test.ts, app/utils/opengraph.test.ts, app/utils/opengraph.ts, app/utils/push_proxy.test.ts, app/utils/reviews.test.ts, app/utils/security.test.ts, app/utils/sentry.test.ts, app/utils/strings.test.ts, app/utils/strings.ts, app/utils/timezone.test.ts, app/utils/typography.test.ts, app/utils/typography.ts, test/setup.ts
Adding more unit tests for code coverage
```release-note
NONE
```
=> More utils unit tests

app/actions/local/channel.test.ts, app/actions/local/channel.ts
Improving our unit test coverage of app/actions/local/channel.
Coverage for this file goes from 27.98% -> 95.51% statements.
n/a
n/a
```release-note
NONE
```
=> Add unit tests for app/actions/local/channel

app/managers/performance_metrics_manager/index.test.ts, app/managers/performance_metrics_manager/index.ts, app/managers/performance_metrics_manager/performance_metrics_batcher.test.ts, app/managers/performance_metrics_manager/performance_metrics_batcher.ts
Cherry pick of #8052 on release-2.18.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8052

app/screens/edit_server/form.tsx, app/screens/forgot_password/index.tsx, app/screens/login/form.tsx, app/screens/mfa/index.tsx, app/screens/server/form.tsx
In the login flow, the styles for the buttons in disable mode were missing.. 
N/A
```release-note
NONE
```
=> Fix button ui when disabled

jest.config.js
Per discussion here https://hub.mattermost.com/private-core/pl/45bq7t1ps38w8ptjmwe8dbboow
n/a
n/a
```release-note
NONE
```
=> Update jest config to show coverage for correct folders

scripts/bump.sh
This PR adds Amy as a reviewer for the weekly build number bumping PR, to decrease the likelihood of forgetting to merge them in for the beta builds.
https://mattermost.atlassian.net/browse/CLD-8028
```release-note
NONE
```
=> Add Amy as a reviewer for the weekly build number bump PRs

app/actions/local/draft.test.ts
some changes to https://github.com/mattermost/mattermost-mobile/pull/8067
Tried placing setup/teardown block on top. Just helps in not repeating some code.
```release-note
NONE
```
=> chore: Place common beforeeach/aftereach top of file

app/actions/local/reactions.test.ts
Jira: https://mattermost.atlassian.net/browse/MM-59480
```release-note
NONE
```
=> Add unit test cases for reactions.ts

app/screens/home/channel_list/servers/index.tsx
Cherry pick of #8094 on release-2.19.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8094

app/actions/remote/post.ts, app/products/calls/actions/calls.ts, app/products/calls/alerts.ts, app/utils/apps.test.ts, app/utils/apps.ts, app/utils/helpers.ts, app/utils/url/test.ts
As stated.
Thread for context: https://hub.mattermost.com/private-core/pl/bk1ookoeabns78i48byacft86o
n/a
```release-note
NONE
```
=> fix issues found by sonarqube

app/utils/file/file_picker/index.test.ts, app/utils/file/file_picker/index.ts
Increase coverage from 0% to 95.16%
https://mattermost.atlassian.net/browse/MM-59561
```release-note
NONE
```
=> added unit tests for utils/file/file-picker

app/actions/remote/entry/login.ts, app/managers/performance_metrics_manager/index.ts, share_extension/index.tsx
Cherry pick of #8107 on release-2.19.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8107

fastlane/Fastfile, ios/Podfile.lock, package-lock.json, package.json
=> fix ios and android build

app/utils/opengraph.ts
https://hub.mattermost.com/private-core/pl/g1bma33jgpym3gfa8e8c6fstxh
```release-note
NONE
```
=> fix loop counters should not be assigned within the loop body

android/app/src/main/AndroidManifest.xml, libraries/@mattermost/rnshare/android/src/main/java/com/mattermost/rnshare/ShareWorker.kt
Cherry pick of #8122 on release-2.19.
```release-note
NONE
```
=> Automated cherry pick of #8122

app/utils/gallery/index.test.ts, app/utils/gallery/vectors.test.ts, app/utils/gallery/vectors.ts, test/setup.ts
Add test coverage to utils/gallery initially at 0%
https://mattermost.atlassian.net/browse/MM-59568
```release-note
NONE
```
=> add unit tests to utils/gallery

app/utils/images/index.test.ts, app/utils/images/index.ts
Add 100% code coverage for app/utils/images
https://mattermost.atlassian.net/browse/MM-59570
```release-note
NONE
```
=> Add unit tests for app/utils/images

app/utils/markdown/index.test.ts, app/utils/markdown/index.ts
https://mattermost.atlassian.net/browse/MM-59571
```release-note
NONE
```
=> add unit tests to app/utils/markdown

app/components/post_draft/post_input/post_input.tsx, app/screens/home/index.tsx, app/screens/home/search/search.tsx, libraries/@mattermost/hardware-keyboard/src/index.tsx
Cherry pick of #8156 on release-2.19.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8156

app/actions/local/thread.test.ts
Coverage increased from 18.12% to 93.12%.
https://mattermost.atlassian.net/browse/MM-59619
```release-note
NONE
```
=> MM-59619 Add unit tests for actions/local/thread

app/components/post_draft/post_input/post_input.tsx
Cherry pick of #8168 on release-2.19.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8168

app/actions/local/team.test.ts
JIRA: https://mattermost.atlassian.net/browse/MM-59616
```release-note
NONE
```
=> Mock date.now in flaky app/actions/team tests

app/products/calls/types/calls.ts, app/screens/sso/sso_authentication.tsx, assets/base/i18n/en.json
Cherry pick of #8174 on release-2.20.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8174

app/products/calls/components/captions.tsx, app/products/calls/connection/websocket_event_handlers.ts
Cherry pick of #8185 on release-2.20.
```release-note
NONE
```
=> Automated cherry pick of #8185

app/constants/post.ts, app/utils/post/index.test.ts
Increase code coverage for app/utils/post from 10.16% to 100%
https://mattermost.atlassian.net/browse/MM-59575
```release-note
NONE
```
=> add unit tests to app/utils/post

app/utils/permalink/index.test.ts, app/utils/permalink/index.ts
https://mattermost.atlassian.net/browse/MM-59574
```release-note
NONE
```
=> add unit tests to app/utils/permalink

app/actions/remote/channel.test.ts, app/actions/remote/channel.ts
Add unit tests for actions/remote/channel. Coverage increases from 5.01% to 88.24%.
https://mattermost.atlassian.net/browse/MM-59440
```release-note
NONE
```
=> MM-59440 Add unit tests for actions/remote/channel

app/actions/remote/entry/common.ts, app/actions/websocket/index.ts, app/client/rest/users.ts
Cherry pick of #8060 on release-2.21.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8060

app/screens/sso/components/auth_error.tsx, app/screens/sso/components/auth_redirect.tsx, app/screens/sso/components/auth_success.tsx, app/screens/sso/index.tsx, app/screens/sso/sso_authentication.tsx, app/screens/sso/sso_authentication_with_external_browser.tsx, assets/base/i18n/en.json, types/api/config.d.ts
Cherry pick of #8220 on release-2.21.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8220

detox/e2e/test/smoke_test/autocomplete.e2e.ts
Removed two references to now-closed issue https://mattermost.atlassian.net/browse/MM-50351 .
=> feat(test): Update test case to remove known issue that has been fixed

app/components/button/index.tsx, app/screens/review_app/index.tsx
Cherry pick of #8232 on release-2.21.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #8232

app/actions/remote/team.test.ts, app/actions/remote/team.ts
Add unit tests for actions/remote/channel. Coverage increases from 22.26% to 87.64%.
https://mattermost.atlassian.net/browse/MM-59434
n/a
```release-note
NONE
```
=> MM-59434 Add tests to actions/remote/team

app/products/calls/connection/connection.ts, package-lock.json, package.json
Cherry pick of #8255 on release-2.22.
```release-note
NONE
```
=> Automated cherry pick of #8255

NOTICE.txt
Cherry pick of #8258 on release-2.22.
```release-note
NONE
```
=> Automated cherry pick of #8258

app/constants/snack_bar.ts, app/screens/code/index.tsx, assets/base/i18n/en.json
Added a copy button at header of code view screen
Fixes https://github.com/mattermost/mattermost/issues/26912
This PR was tested on:  Android Emulator Pixel 8a
```release-note
Added a copy button in code view screen
```
=> feat: Add copy button on code view

app/utils/role/index.test.ts
Adds code coverage for utils/role from 0% to 100%
https://mattermost.atlassian.net/browse/MM-59577
```release-note
NONE
```
=> Add utils/role unit tests

app/utils/post_list/index.test.ts, app/utils/post_list/index.ts
Adds code coverage for utils/post_list from 0% to 92.81%
https://mattermost.atlassian.net/browse/MM-59576
```release-note
NONE
```
=> Add utils/post_list unit tests

app/actions/remote/user.test.ts, app/actions/remote/user.ts
Add unit tests for actions/remote/user. Coverage increases from 26.97% to 87.21%.
https://mattermost.atlassian.net/browse/MM-59447
n/a
```release-note
NONE
```
=> MM-59447 Add tests to actions/remote/user

app/products/calls/components/calls_custom_message/calls_custom_message.tsx, app/products/calls/utils.test.ts, app/products/calls/utils.ts
Applying similar changes from https://github.com/mattermost/mattermost-plugin-calls/pull/885
I am duplicating some code because it wasn't straightforward to have it in our common package, due to the dependency with the Post type.
https://mattermost.atlassian.net/browse/MM-61166
```release-note
NONE
```
=> [MM-61166] Ensure full validation of Calls post props

app/products/calls/components/calls_custom_message/calls_custom_message.tsx, app/products/calls/utils.test.ts, app/products/calls/utils.ts
Cherry pick of #8279 on release-2.22.
```release-note
NONE
```
=> Automated cherry pick of #8279

app/actions/remote/session.test.ts, app/actions/remote/session.ts, app/managers/session_manager.ts
Add unit tests for actions/remote/session. Coverage increases from 12.03% to 94.28%.
https://mattermost.atlassian.net/browse/MM-59438
n/a
```release-note
NONE
```
=> MM-59438 Add tests to actions/remote/session

app/actions/remote/notifications.test.ts, app/actions/remote/notifications.ts
Add unit tests for actions/remote/notifications. Coverage increases from 2.6% to 85.59%.
https://mattermost.atlassian.net/browse/MM-59423
n/a
```release-note
NONE
```
=> MM-59423 Add tests to actions/remote/notifications

app/actions/remote/post.test.ts, app/actions/remote/post.ts
Add unit tests for actions/remote/post. Coverage increases from 15% to 95.86%.
https://mattermost.atlassian.net/browse/MM-59449
n/a
```release-note
NONE
```
=> MM-59449 Add tests for actions/remote/post

android/app/src/main/res/xml/file_viewer_provider_paths.xml, android/app/src/main/res/xml/provider_paths.xml, patches/react-native-share+10.2.1.patch
See ticket.
https://mattermost.atlassian.net/browse/MM-60638
https://mattermost.atlassian.net/browse/MM-60637
Android Google Pixel 6
```release-note
```
=> fix(MM-60638): Provider Paths

android/app/src/main/res/xml/file_viewer_provider_paths.xml, android/app/src/main/res/xml/provider_paths.xml, patches/react-native-share+10.2.1.patch
Cherry pick of #8294 on release-2.22.
```release-note
NONE
```
=> Automated cherry pick of #8294

app/actions/remote/channel.test.ts, app/actions/remote/channel.ts, app/actions/remote/entry/common.ts, app/actions/remote/post.ts, app/actions/remote/team.test.ts, app/actions/remote/team.ts, app/actions/remote/thread.test.ts, app/actions/remote/thread.ts, app/actions/websocket/channel.ts, app/client/rest/threads.ts, app/components/team_sidebar/team_list/index.ts, app/database/operator/server_data_operator/transformers/thread.ts, app/helpers/database/index.ts, app/managers/network_manager.ts, ios/Podfile.lock, libraries/@mattermost/rnutils/ios/RNUtilsWrapper.swift, package-lock.json, package.json
Cherry pick of #8306 on release-2.23.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8306

app/components/progressive_image/index.tsx
Cherry pick of #8339 on release-2.23.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8339

README.md, fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/changelog
Cherry pick of #8330 on release-2.23.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #8330

app/components/markdown/error_boundary.tsx, app/components/markdown/markdown.test.tsx, app/components/markdown/markdown.tsx, assets/base/i18n/en.json, package-lock.json, package.json
Cherry pick of #8300 on release-2.23.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #8300

app/actions/remote/entry/common.ts, app/actions/remote/thread.ts
Cherry pick of #8349 on release-2.23.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8349

app/actions/local/category.test.ts, app/actions/local/draft.test.ts, app/actions/local/file.test.ts, app/actions/local/group.test.ts, app/actions/local/post.test.ts, app/actions/local/systems.test.ts, app/actions/local/thread.test.ts
Increase branch test coverage to 84.93% for all files in actions/local.
n/a
n/a
```release-note
NONE
```
=> Increase branch test coverage to over 80% for actions/local

app/actions/remote/custom_emoji.test.ts, app/actions/remote/custom_emoji.ts
Add unit tests for actions/remote/custom_emoji. Coverage increases from 10% to 92.59%.
https://mattermost.atlassian.net/browse/MM-59432
n/a
```release-note
NONE
```
=> MM-59432 Add tests for actions/remote/custom_emoji

app/components/team_sidebar/team_list/index.test.tsx, app/components/team_sidebar/team_list/index.ts
Cherry pick of #8375 on release-2.23.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8375

app/components/autocomplete_selector/index.tsx, app/components/formatted_text/index.tsx, app/components/markdown/channel_mention/channel_mention.tsx, app/components/markdown/markdown_image/index.tsx, app/components/markdown/markdown_table_image/index.tsx, app/components/post_list/combined_user_activity/combined_user_activity.tsx, app/components/post_list/combined_user_activity/last_users.tsx, app/components/post_list/post/body/content/image_preview/image_preview.tsx, app/components/post_list/post/body/content/message_attachments/action_button/index.tsx, app/components/post_list/post/body/content/message_attachments/message_attachment.tsx, app/components/post_list/post/body/content/opengraph/opengraph_image/index.tsx, app/components/post_list/post/system_message/system_message.tsx, app/components/selected_users/index.tsx, app/database/components/index.tsx, app/screens/apps_form/apps_form_component.tsx, app/screens/emoji_picker/picker/header/skintone_selector/skin_selector.tsx, app/screens/emoji_picker/picker/header/skintone_selector/skintone_selector.tsx, app/screens/in_app_notification/index.tsx, app/screens/integration_selector/integration_selector.tsx, app/screens/interactive_dialog/index.tsx, app/screens/invite/invite.tsx, app/screens/invite/summary_report.tsx, app/screens/permalink/permalink.tsx, app/utils/types.ts
Fix MM-61710
Fix https://mattermost.atlassian.net/browse/MM-61710
```release-note
NONE
```
=> Fix MM-61710

app/components/files/file_info.tsx
Cherry pick of #8391 on release-2.23.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8391

app/components/document/index.tsx, app/components/files/file_info.tsx, app/components/markdown/markdown_image/index.tsx, app/components/markdown/markdown_table_image/index.tsx, app/screens/channel_bookmark/components/bookmark_file/bookmark_file.tsx, app/screens/channel_bookmark/index.tsx, app/screens/gallery/footer/download_with_action/index.tsx, app/utils/file/file_picker/index.ts, app/utils/file/index.ts, app/utils/url/index.test.ts, app/utils/url/index.ts
Cherry pick of #8344 on release-2.23.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8344

app/components/post_list/combined_user_activity/combined_user_activity.tsx, app/utils/post_list/index.ts
Cherry pick of #8396 on release-2.23.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8396

app/components/post_list/post/body/content/message_attachments/attachment_image/index.tsx, app/constants/image.ts, app/utils/images/index.ts
Cherry pick of #8361 on release-2.23.
/cc  @fxnm
```release-note
NONE
```
=> Automated cherry pick of #8361

app/utils/server/index.ts, app/utils/server/server.test.ts, assets/base/i18n/en.json
Cherry pick of #8404 on release-2.24.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8404

app/constants/supported_server.ts
v9.11 ESR is the latest minimum supported ESR version.
Ticket
https://mattermost.atlassian.net/browse/CLD-8696
```release-note
NONE
```
=> Update supported ESR version

app/constants/supported_server.ts
Cherry pick of #8410 on release-2.24.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #8410

.gitignore
Add .aider* into gitignore
Enable the use of aider when development without accidentally adding .aider* files
```release-note
```
=> chore: add .aider* to gitignore

app/components/settings/bool_setting.tsx, app/components/settings/radio_setting/index.tsx, app/components/settings/text_setting.tsx, app/screens/interactive_dialog/dialog_element.tsx, app/screens/interactive_dialog/index.tsx
Cherry pick of #8427 on release-2.24.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8427

app/screens/interactive_dialog/dialog_element.tsx, app/screens/interactive_dialog/index.tsx, app/utils/integrations.ts
Cherry pick of #8431 on release-2.23.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8431

app/actions/remote/file.test.ts
Unit test for /remote/file.ts using Aider (sonnet 3.5).
https://mattermost.atlassian.net/browse/MM-59431
```
PASS  app/actions/remote/file.test.ts
actions/remote/file
downloadFile
✓ should download file successfully (3 ms)
downloadProfileImage
✓ should download profile image successfully
uploadFile
✓ should upload file successfully (1 ms)
✓ should use default callbacks when not provided
✓ should handle upload error
fetchPublicLink
✓ should fetch public link successfully (1 ms)
✓ should handle fetch error
URL building functions
✓ should build file URL
✓ should build absolute URL
✓ should build file preview URL (1 ms)
✓ should build file thumbnail URL
✓ should handle errors in URL building functions
=============================== Coverage summary …
```
=> test(MM-59431): file.ts unit test

app/client/rest/base.ts, app/client/rest/custom_profile_attributes.test.ts, app/client/rest/custom_profile_attributes.ts, app/client/rest/index.ts, app/client/rest/users.ts, app/screens/user_profile/custom_attributes.tsx, app/screens/user_profile/index.ts, app/screens/user_profile/label.tsx, app/screens/user_profile/user_info.tsx, app/screens/user_profile/user_profile.tsx, types/api/config.d.ts, types/api/custom_profile_attributes.d.ts, types/api/users.d.ts
Cherry pick of #8460 on release-2.25.
```release-note
NONE
```
=> Automated cherry pick of #8460

app/queries/app/servers.test.ts
Increase test coverage of queries/app/servers to 96.92%.
https://mattermost.atlassian.net/browse/MM-59776
n/a
```release-note
NONE
```
=> MM-59776 Add queries/app/servers tests

android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt, android/app/src/main/java/com/mattermost/helpers/database_extension/Thread.kt, app/actions/remote/entry/common.ts, app/actions/remote/thread.ts, app/database/operator/server_data_operator/transformers/thread.ts, app/queries/servers/thread.ts, app/screens/global_threads/threads_list/index.ts, app/screens/global_threads/threads_list/threads_list.tsx, app/utils/thread/index.ts, ios/Gekidou/Sources/Gekidou/PushNotification/PushNotification+FetchData.swift
Cherry pick of #8407 on release-2.25.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8407

app/screens/sso/index.tsx, app/screens/sso/sso.test.tsx, app/screens/sso/sso_authentication.tsx, app/screens/sso/sso_authentication_with_external_browser.tsx
Fix SSO bug.
https://mattermost.atlassian.net/browse/MM-62411
Device Name: iPhone 16
OS Version: iOS 18
Mattermost App Version: v2.23.1 on [hub.mattermost.com](http://hub.mattermost.com/)
n/a
```release-note
NONE
```
=> MM-62411 Retrying SSO does not trigger a redirect

app/components/formatted_date/__snapshots__/index.test.tsx.snap, app/components/formatted_date/index.test.tsx, app/components/formatted_date/index.tsx, assets/base/i18n/en.json, index.ts, package-lock.json, package.json
Cherrypick 592b380 to version 2.24
```release-note
NONE
```
=> Cherrypick 592b380 to version 2.24

app/components/files/file.tsx, app/components/files/files.test.tsx, app/components/files/files.tsx, app/components/files_search/file_results.tsx, app/database/operator/server_data_operator/handlers/post.test.ts, app/database/operator/server_data_operator/handlers/post.ts, app/hooks/files.test.ts, app/hooks/files.ts, app/hooks/gallery.ts, app/hooks/utils.test.tsx, app/hooks/utils.ts, test/api_mocks/file.ts
Cherry pick of #8468 on release-2.25.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8468

NOTICE.txt
Cherry pick of #8499 on release-2.25.
```release-note
NONE
```
=> Automated cherry pick of #8499

app/constants/database.ts, app/database/models/server/scheduled_post.ts, types/database/models/servers/scheduled_post.ts, types/database/raw_values.d.ts
Added types for schedule posts.
```release-note
NONE
```
=> Added types and model for scheduled post

app/managers/websocket_manager.test.ts
Add websocket manager tests.
https://mattermost.atlassian.net/browse/MM-59772
n/a
```release-note
NONE
```
=> MM-59772 Add websocket manager tests

app/components/post_list/post/body/add_members/add_members.tsx
We were applying the styles individually to each piece of the text. I just applied the general style to the whole text, and left the details to apply their own style.
I tried to add tests, but the `toHaveStyle` matcher doesn't seem to take into consideration style inheritance.
Fix https://mattermost.atlassian.net/browse/MM-61714
```release-note
Fix style of the ephemeral message that prompts you to add mentioned people to the channel
```
=> Fix styles for add people ephemeral message

app/managers/session_manager.test.ts, app/managers/session_manager.ts
Add session manager tests.
https://mattermost.atlassian.net/browse/MM-59771
n/a
```release-note
NONE
```
=> MM-59771 Add tests for session manager

app/screens/home/search/search.tsx
by trying to clear the info to show the hashtag it is going into an infinite loop of re-rendering.
[MM-62712](https://mattermost.atlassian.net/browse/MM-62712)
This PR was tested on: ios emulator
```release-note
NONE
```
[MM-62712]: https://mattermost.atlassian.net/browse/MM-62712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MM-62712] Fix hashtag loop

app/screens/home/search/search.tsx
Cherry pick of #8524 on release-2.25.
```release-note
NONE
```
=> Automated cherry pick of #8524

app/components/post_list/post_list.test.tsx, app/components/post_list/post_list.tsx, app/components/post_list/scroll_to_end_view.tsx
After upgrading to React-Native version 0.76 in this [PR](https://github.com/mattermost/mattermost-mobile/pull/8421), it was observed that on Android devices, after posting images, it would show 'New Message' sporadically even though the image posted is displayed at the bottom of the post list.
Investigation shows that the onScroll function is not registering y value of 0 where it would then set the lastPostId value to the latest post id (which is the image).
The fix is to reduce scrollEventThrottle value to the minimum (without removing the throttling) for Android devices so that onScroll will be called more frequently.
Also added unit testing, but realized later, I have no way to actually to test this issue.  And there are so much logic in this file that it probably to break it down the …
=> fix(MM-62461): uploading image attachment shows new message

app/components/post_list/post_list.test.tsx, app/components/post_list/post_list.tsx, app/components/post_list/scroll_to_end_view.tsx
Cherry pick of #8528 on release-2.25.
```release-note
NONE
```
=> Automated cherry pick of #8528

app/init/push_notifications.test.ts
Add tests for push notifications class.
https://mattermost.atlassian.net/browse/MM-59766
n/a
```release-note
NONE
```
=> MM-59766 Add tests for push notifications module

app/queries/servers/role.test.ts
Add tests for role query functions.
https://mattermost.atlassian.net/browse/MM-59789
n/a
```release-note
NONE
```
=> MM-59789 Add tests for role queries

app/queries/servers/team.test.ts
Add tests for team queries.
https://mattermost.atlassian.net/browse/MM-59790
n/a
```release-note
NONE
```
=> MM-59790 Add tests for team queries

app/client/rest/tracking.test.ts, app/client/rest/tracking.ts, app/screens/login/form.tsx, app/utils/errors.test.ts, app/utils/errors.ts
Prevent nesting errors that was causing MFA (and possibly other places) to fail.
While at it, made MFA more resilient to nested errors.
[MM-62777](https://mattermost.atlassian.net/browse/MM-62777)
This PR was tested on: ios simulator
```release-note
NONE
```
[MM-62777]: https://mattermost.atlassian.net/browse/MM-62777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MM-62777]: https://mattermost.atlassian.net/browse/MM-62777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MM-62777] Fix errors being nested. Make MFA code more resilient to this situation

app/client/rest/tracking.test.ts, app/client/rest/tracking.ts, app/screens/login/form.tsx, app/utils/errors.test.ts, app/utils/errors.ts
Cherry pick of #8531 on release-2.25.
```release-note
NONE
```
=> Automated cherry pick of #8531

android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
Add error information when push notification fail on Android
NONE
```release-note
NONE
```
=> Add logs for push errors on android

android/app/src/main/java/com/mattermost/helpers/PushNotificationDataHelper.kt
Cherry pick of #8540 on release-2.25.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8540

app/actions/remote/channel.ts, package-lock.json
Cherry pick of #8539 on release-2.25.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8539

app/init/launch.test.ts, app/init/launch.ts
Add tests for init/launch.ts.
https://mattermost.atlassian.net/browse/MM-59764
n/a
```release-note
NONE
```
=> MM-59764 Add tests for launch.ts initialization logic

app/store/navigation_store.test.ts
Add tests for NavigationStore.
https://mattermost.atlassian.net/browse/MM-59799
n/a
```release-note
NONE
```
=> MM-59799 Add tests for NavigationStore

app/managers/apps_manager.test.ts, app/managers/apps_manager.ts
Add tests for AppsManager.
https://mattermost.atlassian.net/browse/MM-59767
n/a
```release-note
NONE
```
=> MM-59767 Add tests for AppsManager

app/database/operator/server_data_operator/handlers/post.test.ts, app/database/operator/server_data_operator/handlers/post.ts
Cherry pick of #8549 on release-2.25.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8549

app/hooks/android_adjust_soft_keyboard/index.test.ts, app/hooks/android_adjust_soft_keyboard/index.ts, app/screens/channel/channel.tsx, app/screens/thread/thread.tsx
Cherry pick of #8554 on release-2.25.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8554

app/components/formatted_date/__snapshots__/index.test.tsx.snap, app/screens/home/channel_list/categories_list/header/header.tsx
With the changes on how we load data on login the plus menu was not being rendered correctly as it had missing dependencies in the `useCallback` causing it not to re-render properly as the roles now are loaded after the initial render.
https://mattermost.atlassian.net/browse/MM-62882
```release-note
NONE
```
=> Fix plus menu on home screen

app/screens/home/channel_list/categories_list/header/header.tsx
Cherry pick of #8560 on release-2.25.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8560

app/screens/home/search/search.test.tsx, app/screens/home/search/search.tsx
Cherry pick of #8564 on release-2.26.
/cc  @JulienTant
```release-note
NONE
```
=> Automated cherry pick of #8564

android/app/src/main/java/com/mattermost/rnbeta/NotificationReplyBroadcastReceiver.java, android/app/src/main/java/com/mattermost/rnbeta/ReceiptDelivery.java, app/screens/home/recent_mentions/recent_mentions.tsx, app/screens/home/saved_messages/saved_messages.tsx, app/screens/home/search/search.tsx, ios/Podfile.lock, package-lock.json, package.json
Cherry pick of #8578 on release-2.25.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8578

.github/actions/prepare-node-deps/action.yaml, android/settings.gradle, ios/Podfile.lock, package-lock.json, package.json, patches/expo-image+2.0.4.patch, scripts/postinstall.sh
Cherry pick of #8573 on release-2.26.
```release-note
NONE
```
=> Automated cherry pick of #8573

README.md
=> Update supported iOS version in Readme

README.md
Cherry pick of #8588 on release-2.26.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #8588

app/screens/scheduled_post_options/footer/scheduled_post_footer.tsx
Used button instead of TouchableOpacity
Fixes https://mattermost.atlassian.net/browse/MM-62757
iOS emulator
```release-note
None
```
=> Used button instead of TouchableOpacity

.github/dependabot.yaml
- Add multiple directories for dependabot 
```release-note
NONE
```
=> fix: Add multiple directories for dependabot

.github/dependabot.yaml
- Proper glob path 
```release-note
NONE
```
=> fix: Proper glob path 

ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/AppDelegate.mm, ios/NotificationService/NotificationService.swift, ios/Podfile, ios/Podfile.lock, package-lock.json, package.json
Cherry pick of #8555 on release-2.26.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8555

app/components/post_list/scroll_to_end_view.tsx, app/components/scheduled_post_indicator/scheduled_post_indicator.tsx
Fixed display of scheduled post indicator with user typing indicator
Fixes https://mattermost.atlassian.net/browse/MM-62871
iOS Emulator
https://github.com/user-attachments/assets/e6dac2c9-2e7d-4920-8ce4-dd04951bdc15
https://github.com/user-attachments/assets/954d4e03-70f0-4fe5-9809-dc2220aa071b
https://github.com/user-attachments/assets/7517e119-2994-4438-88e9-352ac1169b36
https://github.com/user-attachments/assets/7a0d90ae-1d3e-4538-961d-1142de4dac6d
```release-note
None
```
=> Scheduled post typing indicator and user typing indicator UI fix

.github/actions/prepare-android-build/action.yaml, .github/actions/prepare-ios-build/action.yaml, .github/actions/prepare-mobile-build/action.yaml, .github/actions/prepare-node-deps/action.yaml, .github/workflows/build-android-beta.yml, .github/workflows/build-android-release.yml, .github/workflows/build-ios-beta.yml, .github/workflows/build-ios-release.yml, .github/workflows/build-pr.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/compatibility-matrix-testing.yml, .github/workflows/e2e-android-template.yml, .github/workflows/e2e-detox-pr.yml, .github/workflows/e2e-detox-release.yml, .github/workflows/e2e-detox-scheduled.yml, .github/workflows/github-release.yml, app/context/extra_keyboard/index.tsx, app/hooks/device.ts, app/screens/interactive_dialog/index.tsx, libraries/@mattermost/rnutils/android/src/main/java/com/mattermost/rnutils/RNUtilsModuleImpl.kt, patches/react-native-keyboard-aware-scroll-view+0.9.5.patch
Cherry pick of #8646 on release-2.26.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8646

app/components/post_draft/post_draft.tsx, app/screens/navigation.ts
Cherry pick of #8651 on release-2.26.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8651

.github/actions/prepare-node-deps/action.yaml, package-lock.json, package.json, scripts/postinstall.sh
Cherry pick of #8622 on release-2.26.
```release-note
NONE
```
=> Automated cherry pick of #8622

app/components/post_list/post/body/message/message.tsx, app/context/theme/index.tsx, app/screens/settings/display_theme/display_theme.tsx
Cherry pick of #8673 on release-2.27.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8673

ios/Podfile.lock, package-lock.json, package.json
Fixes navigation performance degradation on iOS introduced by screen capture policy
```release-note
NONE
```
=> update react-native-emm fixes navigation perf degradation on iOS

app/components/draft_scheduled_post/draft_scheduled_post.tsx, app/screens/global_drafts/components/tabbed_contents/tabbed_contents.tsx, assets/base/i18n/en.json
=> Minor CSS and title fixes for Tablet scheduled post

ios/ErrorReporting/Sentry.swift
Cherry pick of #8693 on release-2.27.
```release-note
NONE
```
=> Automated cherry pick of #8693

app/components/post_draft/post_draft.tsx, app/hooks/autocomplete.ts
Cherry pick of #8697 on release-2.26.
```release-note
NONE
```
=> Automated cherry pick of #8697

app/screens/edit_profile/edit_profile.test.tsx, app/screens/edit_profile/edit_profile.tsx
Cherry pick of #8719 on release-2.27.
```release-note
NONE
```
=> Automated cherry pick of #8719

build/notice-file/config.yaml
Remove dependency from NOTICE file until we fix it 
https://mattermost.atlassian.net/browse/CLD-9023
```release-note
```
=> Add "APNG4Android" to ignoreDependencies in config.yaml

.github/actions/prepare-ios-build/action.yaml
Always build with the latest xcode version to comply with Apple marketplace
https://mattermost.atlassian.net/browse/CLD-8962
```release-note
Use latest XCode version for builds
```
=> feat: Add setup-xcode action to prepare-ios-build workflow

app/managers/security_manager/index.test.ts, app/managers/security_manager/index.ts
Fixes the flaky test
```release-note
NONE
```
=> Fix SecurityManager flaky test

.github/actions/prepare-ios-build/action.yaml
Cherry pick of #8742 on release-2.27.
/cc  @toninis
```release-note
NONE
```
=> Automated cherry pick of #8742

package-lock.json, package.json
Cherry-pick of #8762 to `release-2.27`
```release-note
NONE
```
=> Update calls-common (cherry-pick)

android/settings.gradle, package-lock.json, package.json, patches/expo-image+2.0.7.patch
Changes to [fix the problem with Android zero-click crash](https://mattermost.atlassian.net/browse/MM-62375) in this [PR](https://github.com/penfeizhou/APNG4Android/pull/233) has been merged and a new version of the package has been created (v3.0.3).  This PR imports the newer version of APNG4Android while waiting for expo-image to merge this PR.
There's no real code changes (in JS or native).  And the package update simplify the way mattermost-mobile app consume the fixes in a different library.
https://mattermost.atlassian.net/browse/MM-63733
Other tickets/PRs:
https://mattermost.atlassian.net/browse/MM-62375
https://github.com/penfeizhou/APNG4Android/pull/233
https://github.com/expo/expo/pull/36097
```release-note
```
=> chore(MM-63733): patch expo-image to use the latest version of APNG4Android

app/screens/navigation.ts, app/utils/helpers.ts
https://mattermost.atlassian.net/browse/MM-63571?focusedCommentId=178218
https://mattermost.atlassian.net/browse/MM-63571
```release-note
NONE
```
=> MM-63571 Android Sentry Error Checks

android/app/build.gradle, ios/Mattermost.xcodeproj/project.pbxproj, ios/Mattermost/Info.plist, ios/MattermostShare/Info.plist, ios/NotificationService/Info.plist, package-lock.json, package.json
Cherry pick of #8787 on release-2.28.
```release-note
NONE
```
=> Automated cherry pick of #8787

android/app/build.gradle, fastlane/Fastfile
Cherry pick of #8790 on release-2.28.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8790

app/products/calls/client/rest.ts, app/products/calls/connection/connection.test.ts, app/products/calls/connection/connection.ts, app/products/calls/types/calls.ts, app/products/calls/utils.ts, package-lock.json, package.json
Cherry pick of #8799 on release-2.28.
```release-note
NONE
```
=> Automated cherry pick of #8799

app/components/chips/base_chip.tsx, app/screens/emoji_picker/picker/header/skintone_selector/skintone_selector.tsx, app/screens/find_channels/filtered_list/filtered_list.tsx, app/screens/find_channels/quick_options/quick_options.tsx, app/screens/find_channels/unfiltered_list/unfiltered_list.tsx, share_extension/components/search_channels/search_channels.tsx
Cherry pick of #8794 on release-2.28.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8794

patches/react-native-navigation+7.45.0.patch
Cherry pick of #8827 on release-2.28.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8827

app/components/post_list/post/body/content/message_attachments/message_attachment.test.tsx, app/components/post_list/post/body/content/message_attachments/message_attachment.tsx
Remove some potential issues in message attachments.
[MM-63548](https://mattermost.atlassian.net/browse/MM-63548)
This PR was tested on: android pixel 8
But since there was no way to reproduce, this testing is inconclusive.
```release-note
NONE
```
[MM-63548]: https://mattermost.atlassian.net/browse/MM-63548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MM-63548] Address potential risks

app/products/calls/screens/participants_list/participants_list.tsx
PR fixes scrolling in call participants list.
https://mattermost.atlassian.net/browse/MM-63808
Tested on Google Pixel 7 Pro (Android 13)
https://github.com/user-attachments/assets/85ff67ca-8100-466e-86be-df904b59c439
```release-note
Calls: fixed an issue with scrolling the participants list
```
=> [MM-63808] Calls: Fix scrolling in participants list

app/actions/remote/notifications.test.ts, app/actions/remote/notifications.ts
Cherry pick of #8811 on release-2.28.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #8811

app/database/migration/server/index.ts, app/database/models/server/channel.ts, app/database/operator/server_data_operator/transformers/channel.ts, app/database/schema/server/index.ts, app/database/schema/server/table_schemas/channel.ts, app/database/schema/server/test.ts, types/database/models/servers/channel.ts
DB changes for https://github.com/mattermost/mattermost-mobile/pull/8848
N/A
N/A
N/A
```release-note
NONE
```
=> Mm 63935 abac end user indicators db isolated changes

app/database/migration/server/index.ts, app/database/models/server/channel.ts, app/database/operator/server_data_operator/transformers/channel.ts, app/database/schema/server/index.ts, app/database/schema/server/table_schemas/channel.ts, app/database/schema/server/test.ts, types/api/channels.d.ts, types/database/models/servers/channel.ts
Cherry pick of #8860 on release-2.29.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #8860

README.md, app/constants/supported_server.ts, fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/changelog
Cherry pick of #8835 on release-2.29.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #8835

app/actions/remote/channel_access_control_attributes.ts, app/client/rest/channels.ts, app/components/section_notice/__snapshots__/index.test.tsx.snap, app/components/section_notice/index.tsx, app/components/tag/index.tsx, app/hooks/access_control_attributes.test.ts, app/hooks/access_control_attributes.ts, app/screens/channel_add_members/channel_add_members.tsx, app/screens/manage_channel_members/index.tsx, app/screens/manage_channel_members/manage_channel_members.tsx, app/screens/settings/notifications/send_test_notification_notice/__snapshots__/send_test_notification_notice.test.tsx.snap, assets/base/i18n/en.json, types/api/channels.d.ts
Cherry pick of #8848  on release-2.29.
/cc  @pvev
```release-note
NONE
```
=> Mm 63935 abac end user indicators (#8848)

app/context/device/index.tsx, app/managers/security_manager/index.ts
Random fixes requested by software analysis
N/A
```release-note
NONE
```
=> Random fixes

app/context/device/index.tsx, app/managers/security_manager/index.ts
Cherry pick of #8874 on release-2.29.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #8874

app/managers/performance_metrics_manager/index.test.ts, app/managers/performance_metrics_manager/index.ts
This PR adds a new mark function to the Performance Metrics Manager to enable more detailed performance tracking with multiple marks. The function allows adding intermediate marks with optional details between the start and end of a metric measurement, providing better insights into the timing of different stages within a performance measurement.
Adding .mark(metricName, detail) at a few key places would create an output as shown below:
```
LOG  Performance marks for entryRest:
LOG  Mark 0 => 1:    2674.04ms    [startMetric => after getHasCRTChanged]
LOG  Mark 1 => 2:     261.07ms    [after getHasCRTChanged => after fetchMyTeams && fetchMe]
LOG  Mark 2 => 3:       5.57ms    [after fetchMyTeams && fetchMe => before fetchMyChannelsForTeam]
LOG  Mark 3 => 4:    1061.40ms    [before …
```
=> feat(MM-63936): add mark function in performance metrics manager

app/constants/tooltip.ts
Cherry pick of #8877 on release-2.29.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8877

app/components/markdown/index.ts
This PR fixes the issue that the mobile app was not using the configuration from the Server to render the minimum length for hashtags.
https://github.com/mattermost/mattermost/issues/27220
```release-note
Fixed the hashtag rendering to work with the minimum hashtag length configuration
```
=> Make the React Native App aware of the minimum hashtag length configuration

.github/workflows/github-release.yml
Cherry pick of #8939 on release-2.29.
/cc  @enzowritescode
```release-note
NONE
```
=> Automated cherry pick of #8939

.github/workflows/github-release.yml
fix typo on curl command of cyclonedx
```release-note
NONE
```
=> fix typo on curl command of cyclonedx

.github/workflows/github-release.yml
Cherry pick of #8944 on release-2.29.
/cc  @angeloskyratzakos
```release-note
NONE
```
=> Automated cherry pick of #8944

.github/workflows/github-release.yml
Cherry pick of #8945 on release-2.29.
/cc  @angeloskyratzakos
```release-note
NONE
```
=> Automated cherry pick of #8945

app/screens/home/search/search.tsx
Cherry pick of #8985 on release-2.31.
/cc  @Rajat-Dabade
```release-note
NONE
```
=> Automated cherry pick of #8985

app/products/playbooks/actions/local/version.test.ts, app/products/playbooks/actions/local/version.ts
Cherry pick of #8989 on release-2.31.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8989

app/products/playbooks/screens/playbook_run/playbook_run.tsx
Cherry pick of #8997 on release-2.31.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8997

app/actions/websocket/index.test.ts, app/actions/websocket/index.ts, app/managers/websocket_manager.test.ts, app/managers/websocket_manager.ts, app/products/playbooks/actions/remote/runs.test.ts, app/products/playbooks/actions/remote/runs.ts, app/products/playbooks/actions/websocket/reconnect.test.ts, app/products/playbooks/actions/websocket/reconnect.ts, app/products/playbooks/database/queries/version.test.ts, app/products/playbooks/database/queries/version.ts, app/screens/channel/header/header.test.tsx, app/screens/channel/header/header.tsx
Cherry pick of #8993 on release-2.31.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #8993

app/products/playbooks/actions/websocket/runs.test.ts, app/products/playbooks/components/channel_actions/playbook_runs_option/index.test.tsx, app/products/playbooks/components/channel_actions/playbook_runs_option/playbook_runs_option.test.tsx, app/products/playbooks/components/channel_actions/playbook_runs_option/playbook_runs_option.tsx, app/screens/channel/header/quick_actions/index.test.tsx, app/screens/channel/header/quick_actions/index.tsx, app/screens/channel_info/options/index.test.tsx, app/screens/channel_info/options/index.tsx
Cherry pick of #9000 on release-2.31.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #9000

app/products/playbooks/actions/websocket/events.ts, app/products/playbooks/actions/websocket/runs.test.ts, app/products/playbooks/actions/websocket/runs.ts, app/products/playbooks/constants/websocket.ts, app/products/playbooks/types/websocket.d.ts
Cherry pick of #9011 on release-2.31.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #9011

app/products/playbooks/constants/version.ts
Cherry pick of #9022 on release-2.31.
/cc  @marianunez
```release-note
NONE
```
=> Automated cherry pick of #9022

.github/workflows/github-release.yml
Cherry pick of #8952 on release-2.30.
/cc  @angeloskyratzakos
```release-note
NONE
```
=> Automated cherry pick of #8952

.github/workflows/github-release.yml
Cherry pick of #8953 on release-2.30.
/cc  @angeloskyratzakos
```release-note
NONE
```
=> Automated cherry pick of #8953

ios/Gekidou/Package.resolved, ios/Gekidou/Package.swift, ios/Mattermost.xcworkspace/xcshareddata/swiftpm/Package.resolved
This PR upgrades SQLite.Swift used in the iOS project to 0.15.4
N/A
```release-note
NONE
```
=> Upgrade SQLite.Swift to 0.15.4

.gitignore, eslint.precommit.config.mjs, scripts/clean.sh, scripts/pre-commit.sh
* `react-hooks/exhaustive-deps` should be an error but recognize that if we change that, we would have to fix all hooks dependencies (around 1400+).  This change will only error out when the developers are committing their changes, and will not cause any issue during lint.
* Also, pre-commit will work faster (on subsequent run) by using `--incremental` flag.  See
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#faster-subsequent-builds-with-the---incremental-flag
* The pre-commit.sh will exit after both checks (lint & tsc) have been executed, not exit when the first check finds an error.
```release-note
```
=> chore: error on react-hooks/exhaustive-deps during pre-commit

app/components/autocomplete/autocomplete.test.tsx, app/components/autocomplete/autocomplete.tsx, app/products/playbooks/screens/edit_command/edit_command.test.tsx, app/products/playbooks/screens/edit_command/edit_command.tsx, app/products/playbooks/screens/edit_command/edit_command_form.test.tsx, app/products/playbooks/screens/edit_command/edit_command_form.tsx
Cherry pick of #9136 on release-2.33.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #9136

ios/Mattermost/Extensions/RNNotificationEventHandler+HandleReplyAction.m
Cherry pick of #9181 on release-2.33.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #9181

app/components/selected_users/index.tsx, app/screens/channel_add_members/channel_add_members.tsx, app/screens/create_direct_message/create_direct_message.tsx
We changed a prop from being an object to be a set, and we didn't update how the size of the object was calculated.
Fix https://mattermost.atlassian.net/browse/MM-65971
Fix https://mattermost.atlassian.net/browse/MM-65967
```release-note
NONE
```
=> Fix selected users not showing in add member screen
